# GTEx global alignment

Two analyses per GTEx tissue, each testing whether the selected SHAP LV(s) recover the true tissue by ORA against the GTEx tissue gene-set database:

1. **top1**: the single highest-ranked SHAP LV per tissue.
2. **cumulative25**: the top-ranked LVs needed to reach `CUMULATIVE_PCT`% of cumulative SHAP per tissue, the same criterion used in `00_LV_importance_kmeans.ipynb` / `01_LV_importance_kmeans_biology.ipynb`.

In [1]:
library(here)
library(dplyr)
library(tidyr)
library(stringr)
library(Matrix)
library(clusterProfiler)


SHAP_DIR <- here('output', '03_model_biology', '01_gtex',
                 '02_rf_kmeans', '00_LV_importance_kmeans',
                 'gtex_feature_importance_kmeans_binary_shap')
OUT_DIR  <- here('output', '03_model_biology', '01_gtex', '02_rf_kmeans', '06_global_alignment')
dir.create(OUT_DIR, recursive = TRUE, showWarnings = FALSE)

CLAMP_RDS      <- here('output', '01_model_building', '02_gtex', '01_CLAMP', 'CLAMPfull.rds')
GTEX_TISSUE_DB <- here('data', 'archs4', 'GTEx_Tissues_pathMat.rds')

N_LVS_PER_TISSUE <- 1L
CUMULATIVE_PCT   <- 25  # same threshold as 01_LV_importance_kmeans_biology.ipynb
TOP_GENE_PCT     <- 0.01
FDR_THRESH       <- 0.05

here() starts at /home/msubirana/Documents/pivlab/clamp-analyses

Attaching package: ‘dplyr’

The following objects are masked from ‘package:stats’:

    filter, lag

The following objects are masked from ‘package:base’:

    intersect, setdiff, setequal, union

Attaching package: ‘Matrix’

The following objects are masked from ‘package:tidyr’:

    expand, pack, unpack

clusterProfiler v4.14.0 Learn more at https://yulab-smu.top/contribution-knowledge-mining/

Please cite:

G Yu. Thirteen years of clusterProfiler. The Innovation. 2024,
5(6):100722

Attaching package: ‘clusterProfiler’

The following object is masked from ‘package:stats’:

    filter

In [2]:
shap_all <- read.delim(file.path(SHAP_DIR, 'all_shap_positive.tsv'),
                       stringsAsFactors = FALSE, check.names = FALSE)

selected_lvs_top1 <- shap_all %>%
    dplyr::arrange(Tissue, Rank) %>%
    dplyr::group_by(Tissue) %>%
    dplyr::slice_head(n = N_LVS_PER_TISSUE) %>%
    dplyr::ungroup() %>%
    dplyr::rename(LV = Feature) %>%
    dplyr::select(Tissue, LV, Rank, Mean_SHAP_Tissue, Cumulative_SHAP, Cumulative_Percent)

selected_lvs_cum <- shap_all %>%
    dplyr::arrange(Tissue, Rank) %>%
    dplyr::group_by(Tissue) %>%
    dplyr::mutate(
        reaches_thresh = Cumulative_Percent >= CUMULATIVE_PCT,
        cutoff_rank = if (any(reaches_thresh)) min(Rank[reaches_thresh]) else max(Rank)
    ) %>%
    dplyr::filter(Rank <= cutoff_rank) %>%
    dplyr::ungroup() %>%
    dplyr::rename(LV = Feature) %>%
    dplyr::select(Tissue, LV, Rank, Mean_SHAP_Tissue, Cumulative_SHAP, Cumulative_Percent)

selections <- list(top1 = selected_lvs_top1, cumulative25 = selected_lvs_cum)

cat('Tissues:', dplyr::n_distinct(selected_lvs_top1$Tissue), '\n')
for (nm in names(selections)) {
    cat(sprintf('  [%s] selected LV/tissue rows: %d, unique LVs: %d\n',
                nm, nrow(selections[[nm]]), dplyr::n_distinct(selections[[nm]]$LV)))
}

dplyr::bind_rows(lapply(names(selections), function(nm) {
    selections[[nm]] %>%
        dplyr::count(Tissue, name = 'n_selected_lvs') %>%
        dplyr::mutate(analysis = nm)
})) %>%
    tidyr::pivot_wider(names_from = analysis, values_from = n_selected_lvs) %>%
    dplyr::arrange(Tissue)

Tissues: 23

  [top1] selected LV/tissue rows: 23, unique LVs: 21
  [cumulative25] selected LV/tissue rows: 79, unique LVs: 69

   Tissue                              top1 cumulative25
1  Adrenal Gland                       1    2
2  Artery - Tibial                     1    4
3  Cells - Cultured fibroblasts        1    4
4  Cells - EBV-transformed lymphocytes 1    6
5  Colon - Transverse                  1    3
6  Esophagus - Mucosa                  1    3
7  Heart - Atrial Appendage            1    2
8  Heart - Left Ventricle              1    6
9  Kidney - Cortex                     1    2
10 Liver                               1    3
11 Lung                                1    3
12 Muscle - Skeletal                   1    3
13 Nerve - Tibial                      1    3
14 Ovary                               1    3
15 Pancreas                            1    3
16 Pituitary                           1    5
17 Prostate                            1    4
18 Small Intestine - Terminal Ileum    1    5
19 Stomach                             1    2
20 Testis                              1    4
21 Thyroid                             1    2
22 Vagina                              1    3
23 Whole Blood                         1    4

In [3]:
clamp <- readRDS(CLAMP_RDS)
Z_full <- as.matrix(clamp$Z)
rm(clamp)

all_selected_lvs <- unique(unlist(lapply(selections, function(df) df$LV)))
selected_unique_lvs <- intersect(all_selected_lvs, colnames(Z_full))
missing_lvs <- setdiff(all_selected_lvs, colnames(Z_full))
if (length(missing_lvs) > 0) warning('Missing LVs in Z: ', paste(missing_lvs, collapse = ', '))

Z <- Z_full[, selected_unique_lvs, drop = FALSE]
rm(Z_full)
universe_genes <- rownames(Z)
n_top_genes <- max(1L, ceiling(TOP_GENE_PCT * nrow(Z)))

cat('Z:', nrow(Z), 'genes x', ncol(Z), 'unique LVs (union across analyses)\n')
cat('Top genes per LV:', n_top_genes, '\n')

Z: 21613 genes x 69 unique LVs (union across analyses)

Top genes per LV: 217

In [4]:
gtex_mat <- readRDS(GTEX_TISSUE_DB)
term_names <- unname(colnames(gtex_mat))

parse_gtex_tissue <- function(x) {
    x <- sub('^GTEx_Tissues_', '', x)
    x <- sub(' (Male|Female) [0-9]+-[0-9]+ Up$', '', x)
    x
}

normalize_text <- function(x) {
    x <- tolower(x)
    x <- gsub('[^a-z0-9]+', ' ', x)
    stringr::str_squish(x)
}

term2gene <- lapply(seq_along(term_names), function(i) {
    rownames(gtex_mat)[gtex_mat[, i] != 0]
})
names(term2gene) <- term_names

term2gene_df <- do.call(rbind, lapply(names(term2gene), function(term) {
    data.frame(term = term, gene = term2gene[[term]], stringsAsFactors = FALSE)
}))

term_map <- data.frame(
    term = term_names,
    parsed_tissue = parse_gtex_tissue(term_names),
    normalized_tissue = normalize_text(parse_gtex_tissue(term_names)),
    stringsAsFactors = FALSE
)

tissue_check <- dplyr::bind_rows(selections) %>%
    dplyr::distinct(Tissue) %>%
    dplyr::mutate(
        normalized_tissue = normalize_text(Tissue),
        matched_in_gtex_db = normalized_tissue %in% term_map$normalized_tissue,
        n_db_sets = vapply(normalized_tissue, function(x) sum(term_map$normalized_tissue == x), integer(1))
    )

cat('GTEx tissue gene sets:', length(term2gene), '\n')
stopifnot(all(tissue_check$matched_in_gtex_db))
tissue_check

GTEx tissue gene sets: 511

                                  Tissue
adrenal gland                     Adrenal Gland
artery tibial                     Artery - Tibial
cells cultured fibroblasts        Cells - Cultured fibroblasts
cells ebv transformed lymphocytes Cells - EBV-transformed lymphocytes
colon transverse                  Colon - Transverse
esophagus mucosa                  Esophagus - Mucosa
heart atrial appendage            Heart - Atrial Appendage
heart left ventricle              Heart - Left Ventricle
kidney cortex                     Kidney - Cortex
liver                             Liver
lung                              Lung
muscle skeletal                   Muscle - Skeletal
nerve tibial                      Nerve - Tibial
ovary                             Ovary
pancreas                          Pancreas
pituitary                         Pituitary
prostate                          Prostate
small intestine terminal ileum    Small Intestine - Terminal Ileum
stomach                           Stomach
testis                            Testis
thyroid                           Thyroid
vagina                            Vagina
whole blood                       Whole Blood
                                  normalized_tissue
adrenal gland                     adrenal gland
artery tibial                     artery tibial
cells cultured fibroblasts        cells cultured fibroblasts
cells ebv transformed lymphocytes cells ebv transformed lymphocytes
colon transverse                  colon transverse
esophagus mucosa                  esophagus mucosa
heart atrial appendage            heart atrial appendage
heart left ventricle              heart left ventricle
kidney cortex                     kidney cortex
liver                             liver
lung                              lung
muscle skeletal                   muscle skeletal
nerve tibial                      nerve tibial
ovary                             ovary
pancreas                          pancreas
pituitary                         pituitary
prostate                          prostate
small intestine terminal ileum    small intestine terminal ileum
stomach                           stomach
testis                            testis
thyroid                           thyroid
vagina                            vagina
whole blood                       whole blood
                                  matched_in_gtex_db n_db_sets
adrenal gland                     TRUE               11
artery tibial                     TRUE               12
cells cultured fibroblasts        TRUE               12
cells ebv transformed lymphocytes TRUE                9
colon transverse                  TRUE               11
esophagus mucosa                  TRUE               12
heart atrial appendage            TRUE               12
heart left ventricle              TRUE               12
kidney cortex                     TRUE                7
liver                             TRUE               11
lung                              TRUE               12
muscle skeletal                   TRUE               12
nerve tibial                      TRUE               12
ovary                             TRUE                6
pancreas                          TRUE               11
pituitary                         TRUE               11
prostate                          TRUE                6
small intestine terminal ileum    TRUE               11
stomach                           TRUE               11
testis                            TRUE                6
thyroid                           TRUE               12
vagina                            TRUE                6
whole blood                       TRUE               12

In [5]:
run_gtex_tissue_ora <- function(genes, universe) {
    res <- tryCatch(
        clusterProfiler::enricher(
            gene          = genes,
            universe      = universe,
            TERM2GENE     = term2gene_df,
            pAdjustMethod = 'BH',
            pvalueCutoff  = 1,
            qvalueCutoff  = 1,
            minGSSize     = 10,
            maxGSSize     = 500
        ),
        error = function(e) NULL
    )
    if (is.null(res)) return(NULL)
    df <- as.data.frame(res)
    if (nrow(df) == 0) return(NULL)
    df
}

top_genes_per_lv <- lapply(colnames(Z), function(lv) {
    vals <- Z[, lv]
    universe_genes[order(vals, decreasing = TRUE)[seq_len(n_top_genes)]]
})
names(top_genes_per_lv) <- colnames(Z)

ora_list <- lapply(names(top_genes_per_lv), function(lv) {
    df <- run_gtex_tissue_ora(top_genes_per_lv[[lv]], universe_genes)
    if (is.null(df)) return(NULL)
    df$LV <- lv
    df
})

ora_all <- do.call(rbind, Filter(Negate(is.null), ora_list))
if (is.null(ora_all)) {
    ora_all <- data.frame()
} else {
    rownames(ora_all) <- NULL
    ora_all <- ora_all %>%
        dplyr::left_join(term_map, by = c('ID' = 'term')) %>%
        dplyr::select(LV, ID, Description, parsed_tissue, normalized_tissue,
                      GeneRatio, BgRatio, pvalue, p.adjust, qvalue, geneID, Count)
}

write.csv(ora_all, file.path(OUT_DIR, 'gtex_tissue_ora_per_lv.csv'), row.names = FALSE)
cat('ORA rows:', nrow(ora_all), '\n')
head(ora_all)

ORA rows: 17905

  LV    ID
1 LV183 GTEx_Tissues_Adrenal Gland Male 40-49 Up
2 LV183 GTEx_Tissues_Adrenal Gland Male 50-59 Up
3 LV183 GTEx_Tissues_Adrenal Gland Male 20-29 Up
4 LV183 GTEx_Tissues_Adrenal Gland Female 20-29 Up
5 LV183 GTEx_Tissues_Adrenal Gland Female 60-69 Up
6 LV183 GTEx_Tissues_Adrenal Gland Male 60-69 Up
  Description                                parsed_tissue normalized_tissue
1 GTEx_Tissues_Adrenal Gland Male 40-49 Up   Adrenal Gland adrenal gland
2 GTEx_Tissues_Adrenal Gland Male 50-59 Up   Adrenal Gland adrenal gland
3 GTEx_Tissues_Adrenal Gland Male 20-29 Up   Adrenal Gland adrenal gland
4 GTEx_Tissues_Adrenal Gland Female 20-29 Up Adrenal Gland adrenal gland
5 GTEx_Tissues_Adrenal Gland Female 60-69 Up Adrenal Gland adrenal gland
6 GTEx_Tissues_Adrenal Gland Male 60-69 Up   Adrenal Gland adrenal gland
  GeneRatio BgRatio pvalue       p.adjust     qvalue
1 52/137    92/6121 2.918975e-65 8.202318e-63 8.202318e-63
2 52/137    93/6121 6.529532e-65 9.173993e-63 9.173993e-63
3 51/137    91/6121 1.157211e-63 1.083921e-61 1.083921e-61
4 50/137    91/6121 9.840988e-62 5.530635e-60 5.530635e-60
5 50/137    91/6121 9.840988e-62 5.530635e-60 5.530635e-60
6 50/137    92/6121 2.125165e-61 9.952854e-60 9.952854e-60
  geneID
1 CYP11B1/CYP17A1/CYP21A2/AS3MT/FAM166B/DBH/AMHR2/STAR/FAM43B/CYB561A3/FDXR/SNTB1/AADAC/IFITM10/KLHL4/SERPINA5/GSTA3/RMDN2/CYP11A1/FDX1/AKAP7/ABCB1/KCNK3/RGN/SLC16A9/RDX/KCNN2/MGARP/AKR1B1/ADGRV1/ASB4/ABCC3/NR5A1/KCNJ5/FNDC4/GSTA1/PORCN/SLC8B1/ALAS1/CYB5B/MCOLN3/KCTD14/KLHDC8B/DEXI/SEMA6A/MRAP/GALM/SREBF1/EPHX1/DLK1/C4B/C2CD2
2 CYP11B1/CYP17A1/CYP21A2/AS3MT/FAM166B/AMHR2/STAR/FAM43B/CYB561A3/FDXR/SNTB1/AADAC/IFITM10/KLHL4/SERPINA5/GSTA3/RMDN2/CYP11A1/FDX1/AKAP7/ABCB1/KCNK3/RGN/SLC16A9/RDX/KCNN2/MGARP/AKR1B1/ADGRV1/ASB4/ABCC3/NR5A1/KCNJ5/FNDC4/GSTA1/PORCN/SLC8B1/ALAS1/CYB5B/MCOLN3/KCTD14/DEXI/SEMA6A/MRAP/GALM/SREBF1/MRPL33/EPHX1/DLK1/C4B/ZSWIM5/C2CD2
3 CYP11B1/CYP17A1/CYP21A2/AS3MT/FAM166B/AMHR2/STAR/FAM43B/CYB561A3/FDXR/SNTB1/AADAC/IFITM10/KLHL4/SERPINA5/GSTA3/RMDN2/CYP11A1/FDX1/AKAP7/ABCB1/KCNK3/RGN/SLC16A9/RDX/KCNN2/MGARP/AKR1B1/ADGRV1/ASB4/ABCC3/NR5A1/KCNJ5/FNDC4/PORCN/SLC8B1/ALAS1/CYB5B/KLHDC8B/SLC37A2/ZNF117/SEMA6A/MRAP/GALM/TXN2/SREBF1/MRPL33/EPHX1/C4B/ZSWIM5/C2CD2
4 CYP11B1/CYP17A1/CYP21A2/AS3MT/FAM166B/AMHR2/STAR/CYB561A3/FDXR/SNTB1/AADAC/KLHL4/SERPINA5/GSTA3/RMDN2/CYP11A1/FDX1/AKAP7/ABCB1/KCNK3/RGN/SLC16A9/CYSLTR2/RDX/KCNN2/MGARP/AKR1B1/ADGRV1/ASB4/ABCC3/NR5A1/KCNJ5/GSTA1/PORCN/SLC8B1/ALAS1/CYB5B/ACSF2/KLHDC8B/DEXI/MRAP/GALM/SREBF1/MRPL33/SLC46A1/EPHX1/DLK1/ZSWIM5/C2CD2/INHA
5 CYP11B1/CYP17A1/CYP21A2/AS3MT/FAM166B/DBH/AMHR2/STAR/TH/CYB561A3/FDXR/SNTB1/AADAC/IFITM10/KLHL4/SERPINA5/GSTA3/RMDN2/CYP11A1/FDX1/AKAP7/ABCB1/KCNK3/RGN/SLC16A9/RDX/KCNN2/MGARP/NXPH1/AKR1B1/ASB4/ABCC3/NR5A1/KCNJ5/GSTA1/PORCN/SLC8B1/ALAS1/CYB5B/MCOLN3/KLHDC8B/DEXI/SEMA6A/MRAP/GALM/SREBF1/EPHX1/DLK1/ZSWIM5/C2CD2
6 CYP11B1/CYP17A1/CYP21A2/AS3MT/FAM166B/AMHR2/STAR/FAM43B/CYB561A3/FDXR/SNTB1/AADAC/IFITM10/KLHL4/GSTA3/RMDN2/CYP11A1/FDX1/AKAP7/ABCB1/KCNK3/RGN/SLC16A9/RDX/KCNN2/MGARP/NXPH1/AKR1B1/ADGRV1/ASB4/ABCC3/NR5A1/KCNJ5/FNDC4/GSTA1/PORCN/SLC8B1/ALAS1/CYB5B/MCOLN3/KLHDC8B/DEXI/SEMA6A/MRAP/GALM/SREBF1/EPHX1/DLK1/C4B/C2CD2
  Count
1 52
2 52
3 51
4 50
5 50
6 50

In [6]:
run_alignment_summary <- function(selected_lvs, ora_all, out_dir) {
    dir.create(out_dir, recursive = TRUE, showWarnings = FALSE)
    sig_ora <- ora_all %>% dplyr::filter(LV %in% selected_lvs$LV, p.adjust < FDR_THRESH)

    detail <- selected_lvs %>%
        dplyr::rowwise() %>%
        dplyr::mutate(
            normalized_true_tissue = normalize_text(Tissue),
            n_sig_terms = sum(sig_ora$LV == LV),
            n_true_terms = sum(sig_ora$LV == LV & sig_ora$normalized_tissue == normalized_true_tissue),
            tissue_correct = n_true_terms > 0,
            best_any_padj = {
                x <- sig_ora$p.adjust[sig_ora$LV == LV]
                if (length(x) == 0) NA_real_ else min(x, na.rm = TRUE)
            },
            best_true_padj = {
                x <- sig_ora$p.adjust[sig_ora$LV == LV & sig_ora$normalized_tissue == normalized_true_tissue]
                if (length(x) == 0) NA_real_ else min(x, na.rm = TRUE)
            },
            matched_terms = paste(sig_ora$ID[sig_ora$LV == LV & sig_ora$normalized_tissue == normalized_true_tissue], collapse = ' | ')
        ) %>%
        dplyr::ungroup()

    tissue_summary <- detail %>%
        dplyr::group_by(Tissue) %>%
        dplyr::summarise(
            n_selected_lvs = dplyr::n(),
            tissue_correct = any(tissue_correct),
            correct_lvs = paste(LV[tissue_correct], collapse = ';'),
            best_true_padj = if (all(is.na(best_true_padj))) NA_real_ else min(best_true_padj, na.rm = TRUE),
            .groups = 'drop'
        ) %>%
        dplyr::mutate(correct_score = as.integer(tissue_correct))

    final_pct_tissue_correct <- 100 * mean(tissue_summary$tissue_correct)
    final_summary <- data.frame(
        n_tissues = nrow(tissue_summary),
        n_tissues_correct = sum(tissue_summary$tissue_correct),
        pct_tissue_correct = final_pct_tissue_correct,
        stringsAsFactors = FALSE
    )

    write.csv(detail, file.path(out_dir, 'gtex_global_alignment_detail.csv'), row.names = FALSE)
    write.csv(tissue_summary, file.path(out_dir, 'gtex_global_alignment_summary.csv'), row.names = FALSE)
    write.csv(final_summary, file.path(out_dir, 'gtex_global_alignment_final_pct.csv'), row.names = FALSE)

    list(detail = detail, tissue_summary = tissue_summary, final_summary = final_summary)
}

results <- lapply(names(selections), function(nm) {
    run_alignment_summary(selections[[nm]], ora_all, file.path(OUT_DIR, nm))
})
names(results) <- names(selections)

dplyr::bind_rows(lapply(names(results), function(nm) {
    results[[nm]]$final_summary %>% dplyr::mutate(analysis = nm, .before = 1)
}))

  analysis     n_tissues n_tissues_correct pct_tissue_correct
1 top1         23        21                 91.30435
2 cumulative25 23        23                100.00000

In [7]:
cat('--- top1 ---\n')
results$top1$tissue_summary %>% dplyr::arrange(Tissue)

cat('--- cumulative25 ---\n')
results$cumulative25$tissue_summary %>% dplyr::arrange(Tissue)

--- top1 ---

   Tissue                              n_selected_lvs tissue_correct
1  Adrenal Gland                       1               TRUE
2  Artery - Tibial                     1               TRUE
3  Cells - Cultured fibroblasts        1               TRUE
4  Cells - EBV-transformed lymphocytes 1              FALSE
5  Colon - Transverse                  1               TRUE
6  Esophagus - Mucosa                  1               TRUE
7  Heart - Atrial Appendage            1               TRUE
8  Heart - Left Ventricle              1               TRUE
9  Kidney - Cortex                     1               TRUE
10 Liver                               1               TRUE
11 Lung                                1               TRUE
12 Muscle - Skeletal                   1               TRUE
13 Nerve - Tibial                      1               TRUE
14 Ovary                               1               TRUE
15 Pancreas                            1               TRUE
16 Pituitary                           1               TRUE
17 Prostate                            1               TRUE
18 Small Intestine - Terminal Ileum    1               TRUE
19 Stomach                             1               TRUE
20 Testis                              1               TRUE
21 Thyroid                             1               TRUE
22 Vagina                              1               TRUE
23 Whole Blood                         1              FALSE
   correct_lvs best_true_padj correct_score
1  LV183        8.202318e-63  1
2  LV563        3.743852e-05  1
3  LV546        8.440805e-59  1
4                         NA  0
5  LV562        1.194764e-43  1
6  LV84         2.870356e-82  1
7  LV420        2.313830e-62  1
8  LV505        1.936986e-78  1
9  LV229        7.554957e-44  1
10 LV21         3.218226e-60  1
11 LV26         4.239296e-43  1
12 LV137       3.982113e-102  1
13 LV329        3.772609e-73  1
14 LV330        2.350335e-19  1
15 LV450       6.131498e-100  1
16 LV105        4.177685e-31  1
17 LV174        1.770945e-08  1
18 LV452        5.068922e-61  1
19 LV227        7.782182e-75  1
20 LV299        1.372607e-44  1
21 LV246        3.902118e-77  1
22 LV80         1.655981e-51  1
23                        NA  0

--- cumulative25 ---

   Tissue                              n_selected_lvs tissue_correct
1  Adrenal Gland                       2              TRUE
2  Artery - Tibial                     4              TRUE
3  Cells - Cultured fibroblasts        4              TRUE
4  Cells - EBV-transformed lymphocytes 6              TRUE
5  Colon - Transverse                  3              TRUE
6  Esophagus - Mucosa                  3              TRUE
7  Heart - Atrial Appendage            2              TRUE
8  Heart - Left Ventricle              6              TRUE
9  Kidney - Cortex                     2              TRUE
10 Liver                               3              TRUE
11 Lung                                3              TRUE
12 Muscle - Skeletal                   3              TRUE
13 Nerve - Tibial                      3              TRUE
14 Ovary                               3              TRUE
15 Pancreas                            3              TRUE
16 Pituitary                           5              TRUE
17 Prostate                            4              TRUE
18 Small Intestine - Terminal Ileum    5              TRUE
19 Stomach                             2              TRUE
20 Testis                              4              TRUE
21 Thyroid                             2              TRUE
22 Vagina                              3              TRUE
23 Whole Blood                         4              TRUE
   correct_lvs                       best_true_padj correct_score
1  LV183;LV3                          8.202318e-63  1
2  LV563;LV90;LV387;LV37              7.034525e-35  1
3  LV546;LV91;LV363;LV111             8.440805e-59  1
4  LV21;LV123;LV378;LV547;LV116;LV90  1.084564e-27  1
5  LV562;LV368;LV108                  1.915969e-55  1
6  LV84;LV330;LV81                    2.870356e-82  1
7  LV420;LV509                        2.313830e-62  1
8  LV505;LV554;LV76;LV137;LV9;LV203   1.936986e-78  1
9  LV229;LV50                         2.475097e-72  1
10 LV21;LV455;LV59                    1.797065e-75  1
11 LV26;LV369;LV239                   4.239296e-43  1
12 LV137;LV68;LV535                  3.982113e-102  1
13 LV329;LV128;LV5                    3.772609e-73  1
14 LV330;LV32;LV3                     9.634315e-55  1
15 LV450;LV25;LV36                   6.131498e-100  1
16 LV105;LV322;LV217;LV155;LV487      4.177685e-31  1
17 LV174;LV559;LV324;LV152            7.587763e-36  1
18 LV452;LV368;LV197;LV25;LV277       5.068922e-61  1
19 LV227;LV36                         7.782182e-75  1
20 LV299;LV134;LV84;LV164             1.372607e-44  1
21 LV246;LV520                        3.902118e-77  1
22 LV80;LV569;LV94                    1.655981e-51  1
23 LV546;LV570;LV238;LV93             5.688445e-81  1

In [8]:
detail_cols <- c('Tissue', 'LV', 'Rank', 'Mean_SHAP_Tissue', 'Cumulative_Percent',
                 'tissue_correct', 'n_sig_terms', 'n_true_terms',
                 'best_true_padj', 'matched_terms')

cat('--- top1 ---\n')
results$top1$detail %>% dplyr::select(dplyr::all_of(detail_cols)) %>% dplyr::arrange(Tissue, Rank)

cat('--- cumulative25 ---\n')
results$cumulative25$detail %>% dplyr::select(dplyr::all_of(detail_cols)) %>% dplyr::arrange(Tissue, Rank)

--- top1 ---

   Tissue                              LV    Rank Mean_SHAP_Tissue
1  Adrenal Gland                       LV183 1    0.13753360
2  Artery - Tibial                     LV563 1    0.08563937
3  Cells - Cultured fibroblasts        LV546 1    0.11603051
4  Cells - EBV-transformed lymphocytes LV21  1    0.06096849
5  Colon - Transverse                  LV562 1    0.10610394
6  Esophagus - Mucosa                  LV84  1    0.13713745
7  Heart - Atrial Appendage            LV420 1    0.16581111
8  Heart - Left Ventricle              LV505 1    0.07538633
9  Kidney - Cortex                     LV229 1    0.15278041
10 Liver                               LV21  1    0.11317176
11 Lung                                LV26  1    0.15010394
12 Muscle - Skeletal                   LV137 1    0.14181925
13 Nerve - Tibial                      LV329 1    0.18907503
14 Ovary                               LV330 1    0.10650393
15 Pancreas                            LV450 1    0.11582342
16 Pituitary                           LV105 1    0.06718318
17 Prostate                            LV174 1    0.09906634
18 Small Intestine - Terminal Ileum    LV452 1    0.09925545
19 Stomach                             LV227 1    0.15247398
20 Testis                              LV299 1    0.12242106
21 Thyroid                             LV246 1    0.18365128
22 Vagina                              LV80  1    0.13772870
23 Whole Blood                         LV546 1    0.09567099
   Cumulative_Percent tissue_correct n_sig_terms n_true_terms best_true_padj
1  14.365823           TRUE          11          11            8.202318e-63
2   9.142689           TRUE          14          11            3.743852e-05
3  12.029419           TRUE          12          12            8.440805e-59
4   6.129557          FALSE          14           0                      NA
5  11.353268           TRUE          26          10            1.194764e-43
6  14.194683           TRUE          20          12            2.870356e-82
7  17.256570           TRUE          36          12            2.313830e-62
8   7.857362           TRUE          24          12            1.936986e-78
9  16.221166           TRUE          23           7            7.554957e-44
10 11.562922           TRUE          14          11            3.218226e-60
11 15.754183           TRUE          12          12            4.239296e-43
12 14.903882           TRUE          21          12           3.982113e-102
13 20.078495           TRUE          20          12            3.772609e-73
14 10.902846           TRUE          35           6            2.350335e-19
15 12.108141           TRUE          21          11           6.131498e-100
16  6.869564           TRUE          38          11            4.177685e-31
17 10.561153           TRUE          27           6            1.770945e-08
18 10.721531           TRUE          59          10            5.068922e-61
19 16.044456           TRUE          12          11            7.782182e-75
20 12.534167           TRUE           6           6            1.372607e-44
21 20.730621           TRUE          13          12            3.902118e-77
22 15.233942           TRUE          51           6            1.655981e-51
23 10.107371          FALSE          12           0                      NA
   matched_terms
1  GTEx_Tissues_Adrenal Gland Male 40-49 Up | GTEx_Tissues_Adrenal Gland Male 50-59 Up | GTEx_Tissues_Adrenal Gland Male 20-29 Up | GTEx_Tissues_Adrenal Gland Female 20-29 Up | GTEx_Tissues_Adrenal Gland Female 60-69 Up | GTEx_Tissues_Adrenal Gland Male 60-69 Up | GTEx_Tissues_Adrenal Gland Female 40-49 Up | GTEx_Tissues_Adrenal Gland Male 30-39 Up | GTEx_Tissues_Adrenal Gland Female 30-39 Up | GTEx_Tissues_Adrenal Gland Female 50-59 Up | GTEx_Tissues_Adrenal Gland Male 70-79 Up
2  GTEx_Tissues_Artery - Tibial Female 30-39 Up | GTEx_Tissues_Artery - Tibial Male 20-29 Up | GTEx_Tissues_Artery - Tibial Female 40-49 Up | GTEx_Tissues_Artery - Tibial Male 40-49 Up | GTEx_Tissues_Artery - Tibial Female 20-29 Up | GTEx_Tissues_Artery - Tibial Male 30-39 Up | GTEx_Tissues_Artery - Tibial Female 70-79 Up | GTEx_Tissues_Artery - Tibial Male 60-69 Up | GTEx_Tissues_Artery - Tibial Male 50-59 Up | GTEx_Tissues_Artery - Tibial Male 70-79 Up | GTEx_Tissues_Artery - Tibial Female 50-59 Up
3  GTEx_Tissues_Cells - Cultured Fibroblasts Female 40-49 Up | GTEx_Tissues_Cells - Cultured Fibroblasts Male 50-59 Up | GTEx_Tissues_Cells - Cultured Fibroblasts Male 60-69 Up | GTEx_Tissues_Cells - Cultured Fibroblasts Male 40-49 Up | GTEx_Tissues_Cells - Cultured Fibroblasts Female 50-59 Up | GTEx_Tissues_Cells - Cultured Fibroblasts Male 20-29 Up | GTEx_Tissues_Cells - Cultured Fibroblasts Female 60-69 Up | GTEx_Tissues_Cells - Cultured Fibroblasts Male 30-39 Up | GTEx_Tissues_Cells - Cultured Fibroblasts Male 70-79 Up | GTEx_Tissues_Cells - Cultured Fibroblasts Female 30-39 Up | GTEx_Tissues_Cells - Cultured Fibroblasts Female 20-29 Up | GTEx_Tissues_Cells - Cultured Fibroblasts Female 70-79 Up
4
5  GTEx_Tissues_Colon - Transverse Female 20-29 Up | GTEx_Tissues_Colon - Transverse Female 50-59 Up | GTEx_Tissues_Colon - Transverse Male 40-49 Up | GTEx_Tissues_Colon - Transverse Male 30-39 Up | GTEx_Tissues_Colon - Transverse Male 20-29 Up | GTEx_Tissues_Colon - Transverse Female 30-39 Up | GTEx_Tissues_Colon - Transverse Male 50-59 Up | GTEx_Tissues_Colon - Transverse Female 40-49 Up | GTEx_Tissues_Colon - Transverse Female 60-69 Up | GTEx_Tissues_Colon - Transverse Male 60-69 Up
6  GTEx_Tissues_Esophagus - Mucosa Male 40-49 Up | GTEx_Tissues_Esophagus - Mucosa Male 30-39 Up | GTEx_Tissues_Esophagus - Mucosa Male 50-59 Up | GTEx_Tissues_Esophagus - Mucosa Female 40-49 Up | GTEx_Tissues_Esophagus - Mucosa Male 20-29 Up | GTEx_Tissues_Esophagus - Mucosa Female 50-59 Up | GTEx_Tissues_Esophagus - Mucosa Female 20-29 Up | GTEx_Tissues_Esophagus - Mucosa Female 30-39 Up | GTEx_Tissues_Esophagus - Mucosa Female 60-69 Up | GTEx_Tissues_Esophagus - Mucosa Male 60-69 Up | GTEx_Tissues_Esophagus - Mucosa Female 70-79 Up | GTEx_Tissues_Esophagus - Mucosa Male 70-79 Up
7  GTEx_Tissues_Heart - Atrial Appendage Male 70-79 Up | GTEx_Tissues_Heart - Atrial Appendage Male 40-49 Up | GTEx_Tissues_Heart - Atrial Appendage Female 40-49 Up | GTEx_Tissues_Heart - Atrial Appendage Female 60-69 Up | GTEx_Tissues_Heart - Atrial Appendage Male 20-29 Up | GTEx_Tissues_Heart - Atrial Appendage Male 50-59 Up | GTEx_Tissues_Heart - Atrial Appendage Male 60-69 Up | GTEx_Tissues_Heart - Atrial Appendage Female 50-59 Up | GTEx_Tissues_Heart - Atrial Appendage Female 70-79 Up | GTEx_Tissues_Heart - Atrial Appendage Female 30-39 Up | GTEx_Tissues_Heart - Atrial Appendage Male 30-39 Up | GTEx_Tissues_Heart - Atrial Appendage Female 20-29 Up
8  GTEx_Tissues_Heart - Left Ventricle Female 50-59 Up | GTEx_Tissues_Heart - Left Ventricle Female 40-49 Up | GTEx_Tissues_Heart - Left Ventricle Female 60-69 Up | GTEx_Tissues_Heart - Left Ventricle Male 40-49 Up | GTEx_Tissues_Heart - Left Ventricle Female 30-39 Up | GTEx_Tissues_Heart - Left Ventricle Male 30-39 Up | GTEx_Tissues_Heart - Left Ventricle Male 50-59 Up | GTEx_Tissues_Heart - Left Ventricle Male 60-69 Up | GTEx_Tissues_Heart - Left Ventricle Female 20-29 Up | GTEx_Tissues_Heart - Left Ventricle Male 20-29 Up | GTEx_Tissues_Heart - Left Ventricle Female 70-79 Up | GTEx_Tissues_Heart - Left Ventricle Male 70-79 Up
9  GTEx_Tissues_Kidney - Cortex Female 50-59 Up | GTEx_Tissues_Kidney - Cortex Female 60-69 Up | GTEx_Tissues_Kidney - Cortex Male 70-79 Up | GTEx_Tissues_Kidney - Cortex Male 30-39 Up | GTEx_Tissues_Kidney - Cortex Male 60-69 Up | GTEx_Tissues_Kidney - Cortex Male 50-59 Up | GTEx_Tissues_Kidney - Cortex Male 40-49 Up
10 GTEx_Tissues_Liver Female 20-29 Up | GTEx_Tissues_Liver Male 50-59 Up | GTEx_Tissues_Liver Male 70-79 Up | GTEx_Tissues_Liver Female 60-69 Up | GTEx_Tissues_Liver Male 30-39 Up | GTEx_Tissues_Liver Female 50-59 Up | GTEx_Tissues_Liver Female 40-49 Up | GTEx_Tissues_Liver Male 40-49 Up | GTEx_Tissues_Liver Male 60-69 Up | GTEx_Tissues_Liver Female 30-39 Up | GTEx_Tissues_Liver Male 20-29 Up
11 GTEx_Tissues_Lung Female 50-59 Up | GTEx_Tissues_Lung Male 50-59 Up | GTEx_Tissues_Lung Male 30-39 Up | GTEx_Tissues_Lung Female 60-69 Up | GTEx_Tissues_Lung Male 40-49 Up | GTEx_Tissues_Lung Female 40-49 Up | GTEx_Tissues_Lung Female 20-29 Up | GTEx_Tissues_Lung Female 30-39 Up | GTEx_Tissues_Lung Female 70-79 Up | GTEx_Tissues_Lung Male 60-69 Up | GTEx_Tissues_Lung Male 20-29 Up | GTEx_Tissues_Lung Male 70-79 Up
12 GTEx_Tissues_Muscle - Skeletal Male 60-69 Up | GTEx_Tissues_Muscle - Skeletal Male 50-59 Up | GTEx_Tissues_Muscle - Skeletal Female 50-59 Up | GTEx_Tissues_Muscle - Skeletal Male 40-49 Up | GTEx_Tissues_Muscle - Skeletal Male 30-39 Up | GTEx_Tissues_Muscle - Skeletal Female 40-49 Up | GTEx_Tissues_Muscle - Skeletal Female 60-69 Up | GTEx_Tissues_Muscle - Skeletal Female 20-29 Up | GTEx_Tissues_Muscle - Skeletal Male 20-29 Up | GTEx_Tissues_Muscle - Skeletal Female 70-79 Up | GTEx_Tissues_Muscle - Skeletal Male 70-79 Up | GTEx_Tissues_Muscle - Skeletal Female 30-39 Up
13 GTEx_Tissues_Nerve - Tibial Male 50-59 Up | GTEx_Tissues_Nerve - Tibial Female 60-69 Up | GTEx_Tissues_Nerve - Tibial Female 50-59 Up | GTEx_Tissues_Nerve - Tibial Male 30-39 Up | GTEx_Tissues_Nerve - Tibial Male 60-69 Up | GTEx_Tissues_Nerve - Tibial Female 40-49 Up | GTEx_Tissues_Nerve - Tibial Male 20-29 Up | GTEx_Tissues_Nerve - Tibial Male 40-49 Up | GTEx_Tissues_Nerve - Tibial Male 70-79 Up | GTEx_Tissues_Nerve - Tibial Female 30-39 Up | GTEx_Tissues_Nerve - Tibial Female 20-29 Up | GTEx_Tissues_Nerve - Tibial Female 70-79 Up
14 GTEx_Tissues_Ovary Female 30-39 Up | GTEx_Tissues_Ovary Female 40-49 Up | GTEx_Tissues_Ovary Female 50-59 Up | GTEx_Tissues_Ovary Female 20-29 Up | GTEx_Tissues_Ovary Female 60-69 Up | GTEx_Tissues_Ovary Female 70-79 Up
15 GTEx_Tissues_Pancreas Male 40-49 Up | GTEx_Tissues_Pancreas Female 50-59 Up | GTEx_Tissues_Pancreas Male 60-69 Up | GTEx_Tissues_Pancreas Female 20-29 Up | GTEx_Tissues_Pancreas Female 40-49 Up | GTEx_Tissues_Pancreas Male 30-39 Up | GTEx_Tissues_Pancreas Female 60-69 Up | GTEx_Tissues_Pancreas Male 50-59 Up | GTEx_Tissues_Pancreas Female 30-39 Up | GTEx_Tissues_Pancreas Male 20-29 Up | GTEx_Tissues_Pancreas Male 70-79 Up
16 GTEx_Tissues_Pituitary Female 50-59 Up | GTEx_Tissues_Pituitary Male 50-59 Up | GTEx_Tissues_Pituitary Male 60-69 Up | GTEx_Tissues_Pituitary Male 70-79 Up | GTEx_Tissues_Pituitary Male 40-49 Up | GTEx_Tissues_Pituitary Female 60-69 Up | GTEx_Tissues_Pituitary Female 40-49 Up | GTEx_Tissues_Pituitary Male 20-29 Up | GTEx_Tissues_Pituitary Male 30-39 Up | GTEx_Tissues_Pituitary Female 20-29 Up | GTEx_Tissues_Pituitary Female 70-79 Up
17 GTEx_Tissues_Prostate Male 70-79 Up | GTEx_Tissues_Prostate Male 50-59 Up | GTEx_Tissues_Prostate Male 20-29 Up | GTEx_Tissues_Prostate Male 60-69 Up | GTEx_Tissues_Prostate Male 40-49 Up | GTEx_Tissues_Prostate Male 30-39 Up
18 GTEx_Tissues_Small Intestine - Terminal Ileum Male 50-59 Up | GTEx_Tissues_Small Intestine - Terminal Ileum Female 60-69 Up | GTEx_Tissues_Small Intestine - Terminal Ileum Male 60-69 Up | GTEx_Tissues_Small Intestine - Terminal Ileum Male 30-39 Up | GTEx_Tissues_Small Intestine - Terminal Ileum Male 40-49 Up | GTEx_Tissues_Small Intestine - Terminal Ileum Female 50-59 Up | GTEx_Tissues_Small Intestine - Terminal Ileum Female 30-39 Up | GTEx_Tissues_Small Intestine - Terminal Ileum Male 20-29 Up | GTEx_Tissues_Small Intestine - Terminal Ileum Female 40-49 Up | GTEx_Tissues_Small Intestine - Terminal Ileum Female 20-29 Up
19 GTEx_Tissues_Stomach Male 60-69 Up | GTEx_Tissues_Stomach Male 40-49 Up | GTEx_Tissues_Stomach Male 30-39 Up | GTEx_Tissues_Stomach Female 60-69 Up | GTEx_Tissues_Stomach Male 50-59 Up | GTEx_Tissues_Stomach Female 50-59 Up | GTEx_Tissues_Stomach Female 30-39 Up | GTEx_Tissues_Stomach Female 20-29 Up | GTEx_Tissues_Stomach Female 40-49 Up | GTEx_Tissues_Stomach Male 20-29 Up | GTEx_Tissues_Stomach Male 70-79 Up
20 GTEx_Tissues_Testis Male 60-69 Up | GTEx_Tissues_Testis Male 30-39 Up | GTEx_Tissues_Testis Male 20-29 Up | GTEx_Tissues_Testis Male 50-59 Up | GTEx_Tissues_Testis Male 40-49 Up | GTEx_Tissues_Testis Male 70-79 Up
21 GTEx_Tissues_Thyroid Male 30-39 Up | GTEx_Tissues_Thyroid Male 40-49 Up | GTEx_Tissues_Thyroid Male 20-29 Up | GTEx_Tissues_Thyroid Female 20-29 Up | GTEx_Tissues_Thyroid Female 40-49 Up | GTEx_Tissues_Thyroid Male 50-59 Up | GTEx_Tissues_Thyroid Male 60-69 Up | GTEx_Tissues_Thyroid Female 50-59 Up | GTEx_Tissues_Thyroid Female 30-39 Up | GTEx_Tissues_Thyroid Female 60-69 Up | GTEx_Tissues_Thyroid Female 70-79 Up | GTEx_Tissues_Thyroid Male 70-79 Up
22 GTEx_Tissues_Vagina Female 40-49 Up | GTEx_Tissues_Vagina Female 50-59 Up | GTEx_Tissues_Vagina Female 20-29 Up | GTEx_Tissues_Vagina Female 30-39 Up | GTEx_Tissues_Vagina Female 60-69 Up | GTEx_Tissues_Vagina Female 70-79 Up
23

--- cumulative25 ---

   Tissue                              LV    Rank Mean_SHAP_Tissue
1  Adrenal Gland                       LV183 1    0.13753360
2  Adrenal Gland                       LV3   2    0.13109711
3  Artery - Tibial                     LV563 1    0.08563937
4  Artery - Tibial                     LV90  2    0.07622058
5  Artery - Tibial                     LV387 3    0.05017576
6  Artery - Tibial                     LV37  4    0.04984620
7  Cells - Cultured fibroblasts        LV546 1    0.11603051
8  Cells - Cultured fibroblasts        LV91  2    0.07353234
9  Cells - Cultured fibroblasts        LV363 3    0.03988249
10 Cells - Cultured fibroblasts        LV111 4    0.03629320
11 Cells - EBV-transformed lymphocytes LV21  1    0.06096849
12 Cells - EBV-transformed lymphocytes LV123 2    0.05736047
13 Cells - EBV-transformed lymphocytes LV378 3    0.04349955
14 Cells - EBV-transformed lymphocytes LV547 4    0.03959304
15 Cells - EBV-transformed lymphocytes LV116 5    0.03855780
16 Cells - EBV-transformed lymphocytes LV90  6    0.03714729
17 Colon - Transverse                  LV562 1    0.10610394
18 Colon - Transverse                  LV368 2    0.06877310
19 Colon - Transverse                  LV108 3    0.06384546
20 Esophagus - Mucosa                  LV84  1    0.13713745
21 Esophagus - Mucosa                  LV330 2    0.06236011
22 Esophagus - Mucosa                  LV81  3    0.05179963
23 Heart - Atrial Appendage            LV420 1    0.16581111
24 Heart - Atrial Appendage            LV509 2    0.08608024
25 Heart - Left Ventricle              LV505 1    0.07538633
26 Heart - Left Ventricle              LV554 2    0.03955986
27 Heart - Left Ventricle              LV76  3    0.03777076
28 Heart - Left Ventricle              LV137 4    0.03156675
29 Heart - Left Ventricle              LV9   5    0.03133837
30 Heart - Left Ventricle              LV203 6    0.02920713
⋮  ⋮                                   ⋮     ⋮    ⋮
50 Pancreas                            LV36  3    0.05743860
51 Pituitary                           LV105 1    0.06718318
52 Pituitary                           LV322 2    0.05394565
53 Pituitary                           LV217 3    0.04820903
54 Pituitary                           LV155 4    0.04533581
55 Pituitary                           LV487 5    0.04460043
56 Prostate                            LV174 1    0.09906634
57 Prostate                            LV559 2    0.07941196
58 Prostate                            LV324 3    0.05172552
59 Prostate                            LV152 4    0.04912996
60 Small Intestine - Terminal Ileum    LV452 1    0.09925545
61 Small Intestine - Terminal Ileum    LV368 2    0.05130912
62 Small Intestine - Terminal Ileum    LV197 3    0.03477652
63 Small Intestine - Terminal Ileum    LV25  4    0.03438174
64 Small Intestine - Terminal Ileum    LV277 5    0.03407791
65 Stomach                             LV227 1    0.15247398
66 Stomach                             LV36  2    0.13149882
67 Testis                              LV299 1    0.12242106
68 Testis                              LV134 2    0.05612446
69 Testis                              LV84  3    0.05237065
70 Testis                              LV164 4    0.02497455
71 Thyroid                             LV246 1    0.18365128
72 Thyroid                             LV520 2    0.10675469
73 Vagina                              LV80  1    0.13772870
74 Vagina                              LV569 2    0.05409139
75 Vagina                              LV94  3    0.04560105
76 Whole Blood                         LV546 1    0.09567099
77 Whole Blood                         LV570 2    0.07754823
78 Whole Blood                         LV238 3    0.05634408
79 Whole Blood                         LV93  4    0.05188056
   Cumulative_Percent tissue_correct n_sig_terms n_true_terms best_true_padj
1  14.365823           TRUE          11          11           8.202318e-63
2  28.059334           TRUE          17          11           7.146307e-56
3   9.142689           TRUE          14          11           3.743852e-05
4  17.279846           TRUE          35          12           3.205225e-04
5  22.636511           TRUE          56          12           7.034525e-35
6  27.957992           TRUE          36          12           1.358742e-18
7  12.029419           TRUE          12          12           8.440805e-59
8  19.652857          FALSE          30           0                     NA
9  23.787658          FALSE          10           0                     NA
10 27.550342          FALSE          17           0                     NA
11  6.129557          FALSE          14           0                     NA
12 11.896376           TRUE          13           9           5.155853e-13
13 16.269668           TRUE           9           9           1.084564e-27
14 20.250212          FALSE           2           0                     NA
15 24.126677          FALSE          52           0                     NA
16 27.861334          FALSE          35           0                     NA
17 11.353268           TRUE          26          10           1.194764e-43
18 18.712085           TRUE          32          10           1.915969e-55
19 25.543638           TRUE          26          10           5.888874e-35
20 14.194683           TRUE          20          12           2.870356e-82
21 20.649390           TRUE          35          12           1.614259e-17
22 26.011013          FALSE          19           0                     NA
23 17.256570           TRUE          36          12           2.313830e-62
24 26.215256           TRUE          14          12           6.415559e-35
25  7.857362           TRUE          24          12           1.936986e-78
26 11.980605          FALSE          25           0                     NA
27 15.917374          FALSE           3           0                     NA
28 19.207511           TRUE          21           9           5.073309e-05
29 22.473845          FALSE          33           0                     NA
30 25.518044          FALSE           0           0                     NA
⋮  ⋮                  ⋮              ⋮           ⋮            ⋮
50 28.372774           TRUE          24          11           3.383003e-10
51  6.869564           TRUE          38          11           4.177685e-31
52 12.385574          FALSE          36           0                     NA
53 17.315008           TRUE          33          11           1.041281e-28
54 21.950651           TRUE          58          11           1.287772e-07
55 26.511101           TRUE          42          11           9.122056e-13
56 10.561153           TRUE          27           6           1.770945e-08
57 19.027013           TRUE           8           6           7.587763e-36
58 24.541310           TRUE          35           6           1.965100e-19
59 29.778901           TRUE           9           6           3.218385e-20
60 10.721531           TRUE          59          10           5.068922e-61
61 16.263920           TRUE          32          10           1.752322e-22
62 20.020465           TRUE          35           6           2.735555e-04
63 23.734366           TRUE          34           7           1.624953e-03
64 27.415447          FALSE          42           0                     NA
65 16.044456           TRUE          12          11           7.782182e-75
66 29.881749           TRUE          24          11           3.649967e-74
67 12.534167           TRUE           6           6           1.372607e-44
68 18.280509          FALSE          16           0                     NA
69 23.642516          FALSE          20           0                     NA
70 26.199552          FALSE           5           0                     NA
71 20.730621           TRUE          13          12           3.902118e-77
72 32.781128           TRUE          21           8           3.282934e-03
73 15.233942           TRUE          51           6           1.655981e-51
74 21.216901           TRUE          18           6           2.309602e-23
75 26.260758          FALSE          18           0                     NA
76 10.107371          FALSE          12           0                     NA
77 18.300124           TRUE          12          12           5.688445e-81
78 24.252718          FALSE          12           0                     NA
79 29.733753          FALSE          24           0                     NA
   matched_terms
1  GTEx_Tissues_Adrenal Gland Male 40-49 Up | GTEx_Tissues_Adrenal Gland Male 50-59 Up | GTEx_Tissues_Adrenal Gland Male 20-29 Up | GTEx_Tissues_Adrenal Gland Female 20-29 Up | GTEx_Tissues_Adrenal Gland Female 60-69 Up | GTEx_Tissues_Adrenal Gland Male 60-69 Up | GTEx_Tissues_Adrenal Gland Female 40-49 Up | GTEx_Tissues_Adrenal Gland Male 30-39 Up | GTEx_Tissues_Adrenal Gland Female 30-39 Up | GTEx_Tissues_Adrenal Gland Female 50-59 Up | GTEx_Tissues_Adrenal Gland Male 70-79 Up
2  GTEx_Tissues_Adrenal Gland Male 50-59 Up | GTEx_Tissues_Adrenal Gland Female 40-49 Up | GTEx_Tissues_Adrenal Gland Female 60-69 Up | GTEx_Tissues_Adrenal Gland Female 50-59 Up | GTEx_Tissues_Adrenal Gland Male 60-69 Up | GTEx_Tissues_Adrenal Gland Female 20-29 Up | GTEx_Tissues_Adrenal Gland Male 30-39 Up | GTEx_Tissues_Adrenal Gland Male 40-49 Up | GTEx_Tissues_Adrenal Gland Female 30-39 Up | GTEx_Tissues_Adrenal Gland Male 20-29 Up | GTEx_Tissues_Adrenal Gland Male 70-79 Up
3  GTEx_Tissues_Artery - Tibial Female 30-39 Up | GTEx_Tissues_Artery - Tibial Male 20-29 Up | GTEx_Tissues_Artery - Tibial Female 40-49 Up | GTEx_Tissues_Artery - Tibial Male 40-49 Up | GTEx_Tissues_Artery - Tibial Female 20-29 Up | GTEx_Tissues_Artery - Tibial Male 30-39 Up | GTEx_Tissues_Artery - Tibial Female 70-79 Up | GTEx_Tissues_Artery - Tibial Male 60-69 Up | GTEx_Tissues_Artery - Tibial Male 50-59 Up | GTEx_Tissues_Artery - Tibial Male 70-79 Up | GTEx_Tissues_Artery - Tibial Female 50-59 Up
4  GTEx_Tissues_Artery - Tibial Female 50-59 Up | GTEx_Tissues_Artery - Tibial Female 60-69 Up | GTEx_Tissues_Artery - Tibial Female 70-79 Up | GTEx_Tissues_Artery - Tibial Male 60-69 Up | GTEx_Tissues_Artery - Tibial Male 40-49 Up | GTEx_Tissues_Artery - Tibial Male 50-59 Up | GTEx_Tissues_Artery - Tibial Male 70-79 Up | GTEx_Tissues_Artery - Tibial Female 40-49 Up | GTEx_Tissues_Artery - Tibial Male 30-39 Up | GTEx_Tissues_Artery - Tibial Female 20-29 Up | GTEx_Tissues_Artery - Tibial Male 20-29 Up | GTEx_Tissues_Artery - Tibial Female 30-39 Up
5  GTEx_Tissues_Artery - Tibial Female 50-59 Up | GTEx_Tissues_Artery - Tibial Female 60-69 Up | GTEx_Tissues_Artery - Tibial Male 60-69 Up | GTEx_Tissues_Artery - Tibial Male 50-59 Up | GTEx_Tissues_Artery - Tibial Male 30-39 Up | GTEx_Tissues_Artery - Tibial Female 20-29 Up | GTEx_Tissues_Artery - Tibial Female 70-79 Up | GTEx_Tissues_Artery - Tibial Male 40-49 Up | GTEx_Tissues_Artery - Tibial Male 70-79 Up | GTEx_Tissues_Artery - Tibial Female 40-49 Up | GTEx_Tissues_Artery - Tibial Female 30-39 Up | GTEx_Tissues_Artery - Tibial Male 20-29 Up
6  GTEx_Tissues_Artery - Tibial Male 60-69 Up | GTEx_Tissues_Artery - Tibial Male 50-59 Up | GTEx_Tissues_Artery - Tibial Female 70-79 Up | GTEx_Tissues_Artery - Tibial Male 70-79 Up | GTEx_Tissues_Artery - Tibial Female 60-69 Up | GTEx_Tissues_Artery - Tibial Female 50-59 Up | GTEx_Tissues_Artery - Tibial Male 40-49 Up | GTEx_Tissues_Artery - Tibial Female 40-49 Up | GTEx_Tissues_Artery - Tibial Male 30-39 Up | GTEx_Tissues_Artery - Tibial Female 30-39 Up | GTEx_Tissues_Artery - Tibial Female 20-29 Up | GTEx_Tissues_Artery - Tibial Male 20-29 Up
7  GTEx_Tissues_Cells - Cultured Fibroblasts Female 40-49 Up | GTEx_Tissues_Cells - Cultured Fibroblasts Male 50-59 Up | GTEx_Tissues_Cells - Cultured Fibroblasts Male 60-69 Up | GTEx_Tissues_Cells - Cultured Fibroblasts Male 40-49 Up | GTEx_Tissues_Cells - Cultured Fibroblasts Female 50-59 Up | GTEx_Tissues_Cells - Cultured Fibroblasts Male 20-29 Up | GTEx_Tissues_Cells - Cultured Fibroblasts Female 60-69 Up | GTEx_Tissues_Cells - Cultured Fibroblasts Male 30-39 Up | GTEx_Tissues_Cells - Cultured Fibroblasts Male 70-79 Up | GTEx_Tissues_Cells - Cultured Fibroblasts Female 30-39 Up | GTEx_Tissues_Cells - Cultured Fibroblasts Female 20-29 Up | GTEx_Tissues_Cells - Cultured Fibroblasts Female 70-79 Up
8
9
10
11
12 GTEx_Tissues_Cells - EBV-transformed Lymphocytes Male 60-69 Up | GTEx_Tissues_Cells - EBV-transformed Lymphocytes Male 40-49 Up | GTEx_Tissues_Cells - EBV-transformed Lymphocytes Female 50-59 Up | GTEx_Tissues_Cells - EBV-transformed Lymphocytes Male 30-39 Up | GTEx_Tissues_Cells - EBV-transformed Lymphocytes Male 20-29 Up | GTEx_Tissues_Cells - EBV-transformed Lymphocytes Male 50-59 Up | GTEx_Tissues_Cells - EBV-transformed Lymphocytes Female 60-69 Up | GTEx_Tissues_Cells - EBV-transformed Lymphocytes Female 20-29 Up | GTEx_Tissues_Cells - EBV-transformed Lymphocytes Female 40-49 Up
13 GTEx_Tissues_Cells - EBV-transformed Lymphocytes Male 20-29 Up | GTEx_Tissues_Cells - EBV-transformed Lymphocytes Male 40-49 Up | GTEx_Tissues_Cells - EBV-transformed Lymphocytes Male 30-39 Up | GTEx_Tissues_Cells - EBV-transformed Lymphocytes Female 50-59 Up | GTEx_Tissues_Cells - EBV-transformed Lymphocytes Male 50-59 Up | GTEx_Tissues_Cells - EBV-transformed Lymphocytes Male 60-69 Up | GTEx_Tissues_Cells - EBV-transformed Lymphocytes Female 40-49 Up | GTEx_Tissues_Cells - EBV-transformed Lymphocytes Female 20-29 Up | GTEx_Tissues_Cells - EBV-transformed Lymphocytes Female 60-69 Up
14
15
16
17 GTEx_Tissues_Colon - Transverse Female 20-29 Up | GTEx_Tissues_Colon - Transverse Female 50-59 Up | GTEx_Tissues_Colon - Transverse Male 40-49 Up | GTEx_Tissues_Colon - Transverse Male 30-39 Up | GTEx_Tissues_Colon - Transverse Male 20-29 Up | GTEx_Tissues_Colon - Transverse Female 30-39 Up | GTEx_Tissues_Colon - Transverse Male 50-59 Up | GTEx_Tissues_Colon - Transverse Female 40-49 Up | GTEx_Tissues_Colon - Transverse Female 60-69 Up | GTEx_Tissues_Colon - Transverse Male 60-69 Up
18 GTEx_Tissues_Colon - Transverse Female 50-59 Up | GTEx_Tissues_Colon - Transverse Female 20-29 Up | GTEx_Tissues_Colon - Transverse Male 20-29 Up | GTEx_Tissues_Colon - Transverse Male 40-49 Up | GTEx_Tissues_Colon - Transverse Female 30-39 Up | GTEx_Tissues_Colon - Transverse Male 50-59 Up | GTEx_Tissues_Colon - Transverse Female 40-49 Up | GTEx_Tissues_Colon - Transverse Male 30-39 Up | GTEx_Tissues_Colon - Transverse Female 60-69 Up | GTEx_Tissues_Colon - Transverse Male 60-69 Up
19 GTEx_Tissues_Colon - Transverse Female 50-59 Up | GTEx_Tissues_Colon - Transverse Male 40-49 Up | GTEx_Tissues_Colon - Transverse Male 30-39 Up | GTEx_Tissues_Colon - Transverse Male 20-29 Up | GTEx_Tissues_Colon - Transverse Female 30-39 Up | GTEx_Tissues_Colon - Transverse Female 40-49 Up | GTEx_Tissues_Colon - Transverse Male 50-59 Up | GTEx_Tissues_Colon - Transverse Female 20-29 Up | GTEx_Tissues_Colon - Transverse Female 60-69 Up | GTEx_Tissues_Colon - Transverse Male 60-69 Up
20 GTEx_Tissues_Esophagus - Mucosa Male 40-49 Up | GTEx_Tissues_Esophagus - Mucosa Male 30-39 Up | GTEx_Tissues_Esophagus - Mucosa Male 50-59 Up | GTEx_Tissues_Esophagus - Mucosa Female 40-49 Up | GTEx_Tissues_Esophagus - Mucosa Male 20-29 Up | GTEx_Tissues_Esophagus - Mucosa Female 50-59 Up | GTEx_Tissues_Esophagus - Mucosa Female 20-29 Up | GTEx_Tissues_Esophagus - Mucosa Female 30-39 Up | GTEx_Tissues_Esophagus - Mucosa Female 60-69 Up | GTEx_Tissues_Esophagus - Mucosa Male 60-69 Up | GTEx_Tissues_Esophagus - Mucosa Female 70-79 Up | GTEx_Tissues_Esophagus - Mucosa Male 70-79 Up
21 GTEx_Tissues_Esophagus - Mucosa Male 20-29 Up | GTEx_Tissues_Esophagus - Mucosa Male 30-39 Up | GTEx_Tissues_Esophagus - Mucosa Male 40-49 Up | GTEx_Tissues_Esophagus - Mucosa Male 50-59 Up | GTEx_Tissues_Esophagus - Mucosa Female 20-29 Up | GTEx_Tissues_Esophagus - Mucosa Female 30-39 Up | GTEx_Tissues_Esophagus - Mucosa Female 50-59 Up | GTEx_Tissues_Esophagus - Mucosa Female 40-49 Up | GTEx_Tissues_Esophagus - Mucosa Female 60-69 Up | GTEx_Tissues_Esophagus - Mucosa Male 60-69 Up | GTEx_Tissues_Esophagus - Mucosa Female 70-79 Up | GTEx_Tissues_Esophagus - Mucosa Male 70-79 Up
22
23 GTEx_Tissues_Heart - Atrial Appendage Male 70-79 Up | GTEx_Tissues_Heart - Atrial Appendage Male 40-49 Up | GTEx_Tissues_Heart - Atrial Appendage Female 40-49 Up | GTEx_Tissues_Heart - Atrial Appendage Female 60-69 Up | GTEx_Tissues_Heart - Atrial Appendage Male 20-29 Up | GTEx_Tissues_Heart - Atrial Appendage Male 50-59 Up | GTEx_Tissues_Heart - Atrial Appendage Male 60-69 Up | GTEx_Tissues_Heart - Atrial Appendage Female 50-59 Up | GTEx_Tissues_Heart - Atrial Appendage Female 70-79 Up | GTEx_Tissues_Heart - Atrial Appendage Female 30-39 Up | GTEx_Tissues_Heart - Atrial Appendage Male 30-39 Up | GTEx_Tissues_Heart - Atrial Appendage Female 20-29 Up
24 GTEx_Tissues_Heart - Atrial Appendage Female 30-39 Up | GTEx_Tissues_Heart - Atrial Appendage Female 20-29 Up | GTEx_Tissues_Heart - Atrial Appendage Female 70-79 Up | GTEx_Tissues_Heart - Atrial Appendage Male 20-29 Up | GTEx_Tissues_Heart - Atrial Appendage Female 60-69 Up | GTEx_Tissues_Heart - Atrial Appendage Female 40-49 Up | GTEx_Tissues_Heart - Atrial Appendage Male 40-49 Up | GTEx_Tissues_Heart - Atrial Appendage Female 50-59 Up | GTEx_Tissues_Heart - Atrial Appendage Male 50-59 Up | GTEx_Tissues_Heart - Atrial Appendage Male 30-39 Up | GTEx_Tissues_Heart - Atrial Appendage Male 60-69 Up | GTEx_Tissues_Heart - Atrial Appendage Male 70-79 Up
25 GTEx_Tissues_Heart - Left Ventricle Female 50-59 Up | GTEx_Tissues_Heart - Left Ventricle Female 40-49 Up | GTEx_Tissues_Heart - Left Ventricle Female 60-69 Up | GTEx_Tissues_Heart - Left Ventricle Male 40-49 Up | GTEx_Tissues_Heart - Left Ventricle Female 30-39 Up | GTEx_Tissues_Heart - Left Ventricle Male 30-39 Up | GTEx_Tissues_Heart - Left Ventricle Male 50-59 Up | GTEx_Tissues_Heart - Left Ventricle Male 60-69 Up | GTEx_Tissues_Heart - Left Ventricle Female 20-29 Up | GTEx_Tissues_Heart - Left Ventricle Male 20-29 Up | GTEx_Tissues_Heart - Left Ventricle Female 70-79 Up | GTEx_Tissues_Heart - Left Ventricle Male 70-79 Up
26
27
28 GTEx_Tissues_Heart - Left Ventricle Female 50-59 Up | GTEx_Tissues_Heart - Left Ventricle Female 20-29 Up | GTEx_Tissues_Heart - Left Ventricle Female 60-69 Up | GTEx_Tissues_Heart - Left Ventricle Male 50-59 Up | GTEx_Tissues_Heart - Left Ventricle Female 40-49 Up | GTEx_Tissues_Heart - Left Ventricle Male 30-39 Up | GTEx_Tissues_Heart - Left Ventricle Male 40-49 Up | GTEx_Tissues_Heart - Left Ventricle Female 30-39 Up | GTEx_Tissues_Heart - Left Ventricle Male 20-29 Up
29
30
⋮  ⋮
50 GTEx_Tissues_Pancreas Female 50-59 Up | GTEx_Tissues_Pancreas Male 70-79 Up | GTEx_Tissues_Pancreas Male 60-69 Up | GTEx_Tissues_Pancreas Female 40-49 Up | GTEx_Tissues_Pancreas Male 40-49 Up | GTEx_Tissues_Pancreas Female 60-69 Up | GTEx_Tissues_Pancreas Female 30-39 Up | GTEx_Tissues_Pancreas Female 20-29 Up | GTEx_Tissues_Pancreas Male 50-59 Up | GTEx_Tissues_Pancreas Male 30-39 Up | GTEx_Tissues_Pancreas Male 20-29 Up
51 GTEx_Tissues_Pituitary Female 50-59 Up | GTEx_Tissues_Pituitary Male 50-59 Up | GTEx_Tissues_Pituitary Male 60-69 Up | GTEx_Tissues_Pituitary Male 70-79 Up | GTEx_Tissues_Pituitary Male 40-49 Up | GTEx_Tissues_Pituitary Female 60-69 Up | GTEx_Tissues_Pituitary Female 40-49 Up | GTEx_Tissues_Pituitary Male 20-29 Up | GTEx_Tissues_Pituitary Male 30-39 Up | GTEx_Tissues_Pituitary Female 20-29 Up | GTEx_Tissues_Pituitary Female 70-79 Up
52
53 GTEx_Tissues_Pituitary Female 50-59 Up | GTEx_Tissues_Pituitary Male 40-49 Up | GTEx_Tissues_Pituitary Male 50-59 Up | GTEx_Tissues_Pituitary Male 60-69 Up | GTEx_Tissues_Pituitary Female 40-49 Up | GTEx_Tissues_Pituitary Male 70-79 Up | GTEx_Tissues_Pituitary Female 60-69 Up | GTEx_Tissues_Pituitary Male 20-29 Up | GTEx_Tissues_Pituitary Female 20-29 Up | GTEx_Tissues_Pituitary Male 30-39 Up | GTEx_Tissues_Pituitary Female 70-79 Up

In [9]:
# Per-LV correctness within the cumulative25 selection (not just "any LV correct")
per_lv_summary <- results$cumulative25$detail %>%
    dplyr::group_by(Tissue) %>%
    dplyr::summarise(
        n_lvs = dplyr::n(),
        n_correct = sum(tissue_correct),
        pct_correct = 100 * n_correct / n_lvs,
        .groups = "drop"
    ) %>%
    dplyr::arrange(pct_correct)

print(per_lv_summary, n = Inf)

total_lvs <- sum(per_lv_summary$n_lvs)
total_correct <- sum(per_lv_summary$n_correct)
cat(sprintf(
    "\nOverall: %d/%d LV-tissue rows correct (%.1f%%) across cumulative25 selection\n",
    total_correct, total_lvs, 100 * total_correct / total_lvs
))
cat(sprintf("Tissues at 100%% LV concordance: %d/%d\n",
            sum(per_lv_summary$pct_correct == 100), nrow(per_lv_summary)))

write.csv(per_lv_summary, file.path(OUT_DIR, "cumulative25", "gtex_global_alignment_per_lv_pct.csv"), row.names = FALSE)

# A tibble: 23 × 4
   Tissue                              n_lvs n_correct pct_correct
   <chr>                               <int>     <int>       <dbl>
 1 Cells - Cultured fibroblasts            4         1        25
 2 Testis                                  4         1        25
 3 Whole Blood                             4         1        25
 4 Cells - EBV-transformed lymphocytes     6         2        33.3
 5 Heart - Left Ventricle                  6         2        33.3
 6 Muscle - Skeletal                       3         1        33.3
 7 Esophagus - Mucosa                      3         2        66.7
 8 Lung                                    3         2        66.7
 9 Nerve - Tibial                          3         2        66.7
10 Vagina                                  3         2        66.7
11 Pituitary                               5         4        80
12 Small Intestine - Terminal Ileum        5         4        80
13 Adrenal Gland                           2         2       100
14 Artery - Tibial                         4         4       100
15 Colon - Transverse                      3         3       100
16 Heart - Atrial Appendage                2         2       100
17 Kidney - Cortex                         2         2       100
18 Liver                                   3         3       100
19 Ovary                                   3         3       100
20 Pancreas                                3         3       100
21 Prostate                                4         4       100
22 Stomach                                 2         2       100
23 Thyroid                                 2         2       100

Overall: 54/79 LV-tissue rows correct (68.4%) across cumulative25 selection

Tissues at 100% LV concordance: 11/23

In [10]:
stopifnot(file.exists(file.path(OUT_DIR, 'gtex_tissue_ora_per_lv.csv')))

for (nm in names(selections)) {
    out_dir <- file.path(OUT_DIR, nm)
    expected_rows <- nrow(selections[[nm]])
    stopifnot(nrow(results[[nm]]$detail) == expected_rows)
    stopifnot(nrow(results[[nm]]$tissue_summary) == dplyr::n_distinct(shap_all$Tissue))
    stopifnot(file.exists(file.path(out_dir, 'gtex_global_alignment_detail.csv')))
    stopifnot(file.exists(file.path(out_dir, 'gtex_global_alignment_summary.csv')))
    stopifnot(file.exists(file.path(out_dir, 'gtex_global_alignment_final_pct.csv')))
    cat(sprintf(
        '[%s] Checks passed. Denominator = %d tissues and %d selected LV/tissue rows. Final %% tissue correct = %.2f\n',
        nm, nrow(results[[nm]]$tissue_summary), nrow(results[[nm]]$detail),
        results[[nm]]$final_summary$pct_tissue_correct
    ))
}

[top1] Checks passed. Denominator = 23 tissues and 23 selected LV/tissue rows. Final % tissue correct = 91.30
[cumulative25] Checks passed. Denominator = 23 tissues and 79 selected LV/tissue rows. Final % tissue correct = 100.00