💡 **Environment:** `clamp-analyses`

# Description

**Per-tissue drug-disease metrics** — an alternative to the "max across 49 tissues" aggregation.

The pipeline collapses each (drug, disease) pair's 49 tissue scores with a **max** before computing
a single pooled AUROC (`../14_signif_test/00_aggregate_predictions.ipynb`). `max` encodes the hypothesis
"one relevant tissue carries the signal for this pair." Replacing it with mean/median is *not* a
clean ablation (it tests a different, broad-sharing model). The clean instrument is to compute
**per-tissue AUROC/AUPRC and then aggregate across tissues**: this decomposes *where* the signal
lives and removes the per-pair tissue-selection step entirely.

This notebook reproduces the upstream aggregation **up to but not including the max** (rank within
each tissue's DOID distribution → mean across the 5 `n_top_genes` thresholds), then scores **each
tissue independently** over the 685-pair gold-standard universe. It is a **read-only consumer** of
the NB06–09 prediction HDF5s and `../14_signif_test/predictions_paired.pkl`; it does **not** modify
NB06–13, `libs/`, or the scoring convention. It **fails loud** if any of NB06–NB09 is missing or
incomplete (the 49-tissue completeness asserts are copied verbatim from `14_signif_test/00`).

Outputs:
- `per_tissue_scores.pkl` — the pre-max long frame `[trait, drug, method, tissue, score, true_class]`
  (685 × 4 × 49 = 133,540 rows), which retains the tissue axis.
- `per_tissue_metrics.csv` — AUROC / AUPRC / `auprc_log2_enrich` per `(method, tissue)` (4 × 49 = 196 rows).
- `max_aggregate_reference.csv` — the status-quo max-aggregate AUROC/AUPRC per method (0.583 / 0.625
  / 0.602 / 0.612), carried forward as the reference the per-tissue results are contrasted against.

# Modules loading

In [1]:
%load_ext autoreload
%autoreload 2

In [2]:
from pathlib import Path
from IPython.display import display

import numpy as np
import pandas as pd
from tqdm import tqdm
from sklearn.metrics import roc_auc_score, average_precision_score

from pyprojroot import here

# Settings

In [3]:
N_TISSUES = 49

# Fixed method order / sign convention (matches ../14_signif_test and ../per_disease_test).
METHOD_ORDER = [
    'gene_based',
    'module_based_archs4',
    'module_based_gtex',
    'module_based_recount2',
]

# Method -> canonical name (copied verbatim from 14_signif_test/00). NB06-NB09 already
# write the canonical names, so these display-name aliases are only a defensive
# fallback (the .get() default passes canonical names through).
METHOD_RENAME = {
    'Gene-based':              'gene_based',
    'Module-based (ARCHS4)':   'module_based_archs4',
    'Module-based (GTEx)':     'module_based_gtex',
    'Module-based (recount2)': 'module_based_recount2',
}

# All four methods in the full grid (gene baseline + three module models).
METHOD_THRESHOLDS = {
    'gene_based':            [-1.0, 50.0, 100.0, 250.0, 500.0],
    'module_based_archs4':   [-1.0, 5.0, 10.0, 25.0, 50.0],
    'module_based_gtex':     [-1.0, 5.0, 10.0, 25.0, 50.0],
    'module_based_recount2': [-1.0, 5.0, 10.0, 25.0, 50.0],
}
EXPECTED_METHODS = tuple(METHOD_THRESHOLDS)

In [4]:
DATA_DIR = here('data/drug_disease_associations')
display(DATA_DIR)
assert DATA_DIR.exists()

# Raw prediction HDF5 dirs for the four methods (NB06, NB07, NB08, NB09).
_PRED_BASE = here(
    'output/03_model_biology/00_archs4/02_drug_disease_associations')
PREDICTIONS_DIRS = {
    'gene_based':
        _PRED_BASE / '06_prediction_single_gene_based' / 'lincs' / 'predictions' / 'dotprod_neg',
    'module_based_archs4':
        _PRED_BASE / '07_prediction_module_based_archs4' / 'lincs' / 'predictions' / 'dotprod_neg',
    'module_based_gtex':
        _PRED_BASE / '08_prediction_module_based_gtex' / 'lincs' / 'predictions' / 'dotprod_neg',
    'module_based_recount2':
        _PRED_BASE / '09_prediction_module_based_recount2' / 'lincs' / 'predictions' / 'dotprod_neg',
}
# Map each method to the prediction notebook that produces it (for fail-loud msgs).
_METHOD_SOURCE_NB = {
    'gene_based':            'NB06 (06_prediction_single_gene_based)',
    'module_based_archs4':   'NB07 (07_prediction_module_based_archs4)',
    'module_based_gtex':     'NB08 (08_prediction_module_based_gtex)',
    'module_based_recount2': 'NB09 (09_prediction_module_based_recount2)',
}
for name, d in PREDICTIONS_DIRS.items():
    display((name, d))
    # Fail loud (do not silently score on partial data): the full 4-method grid
    # needs all of NB06-NB09 on disk.
    assert d.exists(), (
        f'{name} predictions missing -- run {_METHOD_SOURCE_NB[name]} first: {d}')

# The status-quo max-aggregate frame (produced by 14_signif_test/00).
PAIRED_PKL = _PRED_BASE / '14_signif_test' / 'predictions_paired.pkl'
assert PAIRED_PKL.exists(), f'run 14_signif_test/00_aggregate_predictions first: {PAIRED_PKL}'

OUTPUT_DIR = _PRED_BASE / '15_tissue_agg_test'
OUTPUT_DIR.mkdir(parents=True, exist_ok=True)
display(OUTPUT_DIR)

PosixPath('/home/msubirana/Documents/pivlab/clamp-analyses/data/drug_disease_associations')

('gene_based',
 PosixPath('/home/msubirana/Documents/pivlab/clamp-analyses/output/03_model_biology/00_archs4/02_drug_disease_associations/06_prediction_single_gene_based/lincs/predictions/dotprod_neg'))

('module_based_archs4',
 PosixPath('/home/msubirana/Documents/pivlab/clamp-analyses/output/03_model_biology/00_archs4/02_drug_disease_associations/07_prediction_module_based_archs4/lincs/predictions/dotprod_neg'))

('module_based_gtex',
 PosixPath('/home/msubirana/Documents/pivlab/clamp-analyses/output/03_model_biology/00_archs4/02_drug_disease_associations/08_prediction_module_based_gtex/lincs/predictions/dotprod_neg'))

('module_based_recount2',
 PosixPath('/home/msubirana/Documents/pivlab/clamp-analyses/output/03_model_biology/00_archs4/02_drug_disease_associations/09_prediction_module_based_recount2/lincs/predictions/dotprod_neg'))

PosixPath('/home/msubirana/Documents/pivlab/clamp-analyses/output/03_model_biology/00_archs4/02_drug_disease_associations/15_tissue_agg_test')

# Load PharmacotherapyDB gold standard

In [5]:
gold_standard = pd.read_pickle(DATA_DIR / 'gold_standard.pkl')
display(gold_standard.shape)
display(gold_standard['true_class'].value_counts())

(998, 3)

true_class
1    755
0    243
Name: count, dtype: int64

# Helpers (copied verbatim from NB10 / 14_signif_test/00)

In [6]:
def _get_tissue(data_value):
    """Extract tissue name from the metadata 'data' field."""
    prefix = 'spredixcan-mashr-zscores-'
    assert data_value.startswith(prefix), data_value
    tissue = data_value[len(prefix):]
    for suffix in (
        '-projection-archs4',
        '-projection-gtex',
        '-projection-recount2',
        '-projection',
        '-data',
    ):
        if tissue.endswith(suffix):
            return tissue[:-len(suffix)]
    raise ValueError(f'Cannot extract tissue from metadata data value: {data_value}')

# Load drug-disease predictions

Per file: rank `score` over the full DOID distribution, then inner-merge with the gold standard
(NB10 / 14_signif_test order — rank first, then keep gold-standard pairs).

In [ ]:
current_prediction_files = []
for d in PREDICTIONS_DIRS.values():
    current_prediction_files.extend(sorted(d.glob('*.h5')))
current_prediction_files.sort()
display(len(current_prediction_files))

In [8]:
# Load all prediction files, rank scores, merge with gold standard (NB10 logic).
predictions = []
skipped_files = []

for f in tqdm(current_prediction_files, ncols=100):
    metadata = pd.read_hdf(f, key='/metadata')
    method_name = METHOD_RENAME.get(
        metadata['method'].values[0], metadata['method'].values[0])
    if method_name not in METHOD_THRESHOLDS:
        skipped_files.append((f.name, method_name))
        continue

    # Rank within the full DOID distribution, then keep gold-standard pairs.
    prediction_data = pd.read_hdf(f, key='/prediction')
    prediction_data['score'] = prediction_data['score'].rank()
    prediction_data = pd.merge(
        prediction_data, gold_standard, on=['trait', 'drug'], how='inner')
    prediction_data['trait'] = prediction_data['trait'].astype('category')
    prediction_data['drug'] = prediction_data['drug'].astype('category')

    prediction_data = prediction_data.assign(method=method_name)
    prediction_data['method'] = pd.Categorical(
        prediction_data['method'], categories=EXPECTED_METHODS, ordered=True)
    prediction_data = prediction_data.assign(
        n_top_genes=metadata['n_top_genes'].values[0])

    data_value = metadata['data'].values[0]
    prediction_data = prediction_data.assign(data=data_value)
    prediction_data['data'] = prediction_data['data'].astype('category')
    prediction_data = prediction_data.assign(tissue=_get_tissue(data_value))

    predictions.append(prediction_data)

display(f'Skipped files: {len(skipped_files)}')
if skipped_files:
    display(skipped_files[:10])

  0%|                                                                       | 0/960 [00:00<?, ?it/s]

  0%|                                                               | 1/960 [00:00<03:20,  4.78it/s]

  0%|▏                                                              | 2/960 [00:00<02:52,  5.54it/s]

  0%|▏                                                              | 3/960 [00:00<02:44,  5.82it/s]

  0%|▎                                                              | 4/960 [00:00<02:43,  5.86it/s]

  1%|▎                                                              | 5/960 [00:00<02:40,  5.94it/s]

  1%|▍                                                              | 6/960 [00:01<02:38,  6.01it/s]

  1%|▍                                                              | 7/960 [00:01<02:34,  6.17it/s]

  1%|▌                                                              | 8/960 [00:01<02:33,  6.19it/s]

  1%|▌                                                              | 9/960 [00:01<02:34,  6.15it/s]

  1%|▋                                                             | 10/960 [00:01<02:37,  6.03it/s]

  1%|▋                                                             | 11/960 [00:01<02:38,  6.00it/s]

  1%|▊                                                             | 12/960 [00:02<02:43,  5.81it/s]

  1%|▊                                                             | 13/960 [00:02<02:41,  5.86it/s]

  1%|▉                                                             | 14/960 [00:02<02:43,  5.80it/s]

  2%|▉                                                             | 15/960 [00:02<02:42,  5.81it/s]

  2%|█                                                             | 16/960 [00:02<02:40,  5.87it/s]

  2%|█                                                             | 17/960 [00:02<02:37,  5.98it/s]

  2%|█▏                                                            | 18/960 [00:03<02:35,  6.04it/s]

  2%|█▏                                                            | 19/960 [00:03<02:34,  6.10it/s]

  2%|█▎                                                            | 20/960 [00:03<02:34,  6.10it/s]

  2%|█▎                                                            | 21/960 [00:03<02:33,  6.12it/s]

  2%|█▍                                                            | 22/960 [00:03<02:31,  6.20it/s]

  2%|█▍                                                            | 23/960 [00:03<02:30,  6.24it/s]

  2%|█▌                                                            | 24/960 [00:03<02:28,  6.29it/s]

  3%|█▌                                                            | 25/960 [00:04<02:27,  6.34it/s]

  3%|█▋                                                            | 26/960 [00:04<02:28,  6.27it/s]

  3%|█▋                                                            | 27/960 [00:04<02:31,  6.14it/s]

  3%|█▊                                                            | 28/960 [00:04<02:34,  6.03it/s]

  3%|█▊                                                            | 29/960 [00:04<02:34,  6.01it/s]

  3%|█▉                                                            | 30/960 [00:04<02:35,  5.98it/s]

  3%|██                                                            | 31/960 [00:05<02:37,  5.90it/s]

  3%|██                                                            | 32/960 [00:05<02:37,  5.88it/s]

  3%|██▏                                                           | 33/960 [00:05<02:35,  5.97it/s]

  4%|██▏                                                           | 34/960 [00:05<02:34,  6.00it/s]

  4%|██▎                                                           | 35/960 [00:05<02:33,  6.03it/s]

  4%|██▎                                                           | 36/960 [00:05<02:31,  6.10it/s]

  4%|██▍                                                           | 37/960 [00:06<02:32,  6.04it/s]

  4%|██▍                                                           | 38/960 [00:06<02:31,  6.08it/s]

  4%|██▌                                                           | 39/960 [00:06<02:30,  6.11it/s]

  4%|██▌                                                           | 40/960 [00:06<02:29,  6.16it/s]

  4%|██▋                                                           | 41/960 [00:06<02:27,  6.21it/s]

  4%|██▋                                                           | 42/960 [00:06<02:31,  6.05it/s]

  4%|██▊                                                           | 43/960 [00:07<02:30,  6.07it/s]

  5%|██▊                                                           | 44/960 [00:07<02:45,  5.55it/s]

  5%|██▉                                                           | 45/960 [00:07<02:41,  5.67it/s]

  5%|██▉                                                           | 46/960 [00:07<02:38,  5.75it/s]

  5%|███                                                           | 47/960 [00:07<02:37,  5.79it/s]

  5%|███                                                           | 48/960 [00:08<02:38,  5.76it/s]

  5%|███▏                                                          | 49/960 [00:08<02:35,  5.84it/s]

  5%|███▏                                                          | 50/960 [00:08<02:33,  5.92it/s]

  5%|███▎                                                          | 51/960 [00:08<02:32,  5.94it/s]

  5%|███▎                                                          | 52/960 [00:08<02:32,  5.97it/s]

  6%|███▍                                                          | 53/960 [00:08<02:30,  6.03it/s]

  6%|███▍                                                          | 54/960 [00:09<02:29,  6.07it/s]

  6%|███▌                                                          | 55/960 [00:09<02:27,  6.13it/s]

  6%|███▌                                                          | 56/960 [00:09<02:25,  6.23it/s]

  6%|███▋                                                          | 57/960 [00:09<02:23,  6.29it/s]

  6%|███▋                                                          | 58/960 [00:09<02:22,  6.34it/s]

  6%|███▊                                                          | 59/960 [00:09<02:22,  6.34it/s]

  6%|███▉                                                          | 60/960 [00:09<02:22,  6.33it/s]

  6%|███▉                                                          | 61/960 [00:10<02:22,  6.32it/s]

  6%|████                                                          | 62/960 [00:10<02:22,  6.32it/s]

  7%|████                                                          | 63/960 [00:10<02:23,  6.26it/s]

  7%|████▏                                                         | 64/960 [00:10<02:25,  6.17it/s]

  7%|████▏                                                         | 65/960 [00:10<02:26,  6.09it/s]

  7%|████▎                                                         | 66/960 [00:10<02:27,  6.04it/s]

  7%|████▎                                                         | 67/960 [00:11<02:30,  5.95it/s]

  7%|████▍                                                         | 68/960 [00:11<02:29,  5.98it/s]

  7%|████▍                                                         | 69/960 [00:11<02:26,  6.08it/s]

  7%|████▌                                                         | 70/960 [00:11<02:26,  6.08it/s]

  7%|████▌                                                         | 71/960 [00:11<02:26,  6.05it/s]

  8%|████▋                                                         | 72/960 [00:11<02:25,  6.09it/s]

  8%|████▋                                                         | 73/960 [00:12<02:25,  6.11it/s]

  8%|████▊                                                         | 74/960 [00:12<02:25,  6.10it/s]

  8%|████▊                                                         | 75/960 [00:12<02:22,  6.20it/s]

  8%|████▉                                                         | 76/960 [00:12<02:21,  6.27it/s]

  8%|████▉                                                         | 77/960 [00:12<02:20,  6.30it/s]

  8%|█████                                                         | 78/960 [00:12<02:20,  6.30it/s]

  8%|█████                                                         | 79/960 [00:13<02:20,  6.26it/s]

  8%|█████▏                                                        | 80/960 [00:13<02:20,  6.26it/s]

  8%|█████▏                                                        | 81/960 [00:13<02:21,  6.20it/s]

  9%|█████▎                                                        | 82/960 [00:13<02:22,  6.15it/s]

  9%|█████▎                                                        | 83/960 [00:13<02:24,  6.08it/s]

  9%|█████▍                                                        | 84/960 [00:13<02:24,  6.04it/s]

  9%|█████▍                                                        | 85/960 [00:14<02:26,  5.98it/s]

  9%|█████▌                                                        | 86/960 [00:14<02:27,  5.93it/s]

  9%|█████▌                                                        | 87/960 [00:14<02:28,  5.88it/s]

  9%|█████▋                                                        | 88/960 [00:14<02:27,  5.91it/s]

  9%|█████▋                                                        | 89/960 [00:14<02:26,  5.94it/s]

  9%|█████▊                                                        | 90/960 [00:14<02:25,  5.96it/s]

  9%|█████▉                                                        | 91/960 [00:15<02:28,  5.85it/s]

 10%|█████▉                                                        | 92/960 [00:15<02:27,  5.88it/s]

 10%|██████                                                        | 93/960 [00:15<02:23,  6.03it/s]

 10%|██████                                                        | 94/960 [00:15<02:20,  6.15it/s]

 10%|██████▏                                                       | 95/960 [00:15<02:19,  6.21it/s]

 10%|██████▏                                                       | 96/960 [00:15<02:21,  6.10it/s]

 10%|██████▎                                                       | 97/960 [00:16<02:22,  6.07it/s]

 10%|██████▎                                                       | 98/960 [00:16<02:19,  6.18it/s]

 10%|██████▍                                                       | 99/960 [00:16<02:18,  6.23it/s]

 10%|██████▎                                                      | 100/960 [00:16<02:21,  6.08it/s]

 11%|██████▍                                                      | 101/960 [00:16<02:23,  5.98it/s]

 11%|██████▍                                                      | 102/960 [00:16<02:25,  5.90it/s]

 11%|██████▌                                                      | 103/960 [00:17<02:27,  5.82it/s]

 11%|██████▌                                                      | 104/960 [00:17<02:27,  5.79it/s]

 11%|██████▋                                                      | 105/960 [00:17<02:29,  5.72it/s]

 11%|██████▋                                                      | 106/960 [00:17<02:29,  5.72it/s]

 11%|██████▊                                                      | 107/960 [00:17<02:30,  5.68it/s]

 11%|██████▊                                                      | 108/960 [00:17<02:30,  5.67it/s]

 11%|██████▉                                                      | 109/960 [00:18<02:31,  5.60it/s]

 11%|██████▉                                                      | 110/960 [00:18<02:33,  5.52it/s]

 12%|███████                                                      | 111/960 [00:18<02:28,  5.74it/s]

 12%|███████                                                      | 112/960 [00:18<02:24,  5.86it/s]

 12%|███████▏                                                     | 113/960 [00:18<02:22,  5.94it/s]

 12%|███████▏                                                     | 114/960 [00:18<02:21,  5.99it/s]

 12%|███████▎                                                     | 115/960 [00:19<02:20,  6.01it/s]

 12%|███████▎                                                     | 116/960 [00:19<02:22,  5.92it/s]

 12%|███████▍                                                     | 117/960 [00:19<02:22,  5.91it/s]

 12%|███████▍                                                     | 118/960 [00:19<02:22,  5.91it/s]

 12%|███████▌                                                     | 119/960 [00:19<02:22,  5.90it/s]

 12%|███████▋                                                     | 120/960 [00:19<02:24,  5.82it/s]

 13%|███████▋                                                     | 121/960 [00:20<02:30,  5.56it/s]

 13%|███████▊                                                     | 122/960 [00:20<02:32,  5.51it/s]

 13%|███████▊                                                     | 123/960 [00:20<02:32,  5.47it/s]

 13%|███████▉                                                     | 124/960 [00:20<02:36,  5.35it/s]

 13%|███████▉                                                     | 125/960 [00:20<02:33,  5.43it/s]

 13%|████████                                                     | 126/960 [00:21<02:30,  5.53it/s]

 13%|████████                                                     | 127/960 [00:21<02:28,  5.61it/s]

 13%|████████▏                                                    | 128/960 [00:21<02:24,  5.77it/s]

 13%|████████▏                                                    | 129/960 [00:21<02:22,  5.84it/s]

 14%|████████▎                                                    | 130/960 [00:21<02:19,  5.93it/s]

 14%|████████▎                                                    | 131/960 [00:21<02:16,  6.08it/s]

 14%|████████▍                                                    | 132/960 [00:22<02:13,  6.19it/s]

 14%|████████▍                                                    | 133/960 [00:22<02:12,  6.24it/s]

 14%|████████▌                                                    | 134/960 [00:22<02:11,  6.26it/s]

 14%|████████▌                                                    | 135/960 [00:22<02:11,  6.26it/s]

 14%|████████▋                                                    | 136/960 [00:22<02:12,  6.23it/s]

 14%|████████▋                                                    | 137/960 [00:22<02:14,  6.12it/s]

 14%|████████▊                                                    | 138/960 [00:23<02:15,  6.07it/s]

 14%|████████▊                                                    | 139/960 [00:23<02:20,  5.84it/s]

 15%|████████▉                                                    | 140/960 [00:23<02:22,  5.75it/s]

 15%|████████▉                                                    | 141/960 [00:23<02:24,  5.68it/s]

 15%|█████████                                                    | 142/960 [00:23<02:22,  5.75it/s]

 15%|█████████                                                    | 143/960 [00:23<02:20,  5.81it/s]

 15%|█████████▏                                                   | 144/960 [00:24<02:18,  5.90it/s]

 15%|█████████▏                                                   | 145/960 [00:24<02:16,  5.95it/s]

 15%|█████████▎                                                   | 146/960 [00:24<02:12,  6.12it/s]

 15%|█████████▎                                                   | 147/960 [00:24<02:10,  6.24it/s]

 15%|█████████▍                                                   | 148/960 [00:24<02:08,  6.31it/s]

 16%|█████████▍                                                   | 149/960 [00:24<02:07,  6.35it/s]

 16%|█████████▌                                                   | 150/960 [00:25<02:07,  6.35it/s]

 16%|█████████▌                                                   | 151/960 [00:25<02:07,  6.35it/s]

 16%|█████████▋                                                   | 152/960 [00:25<02:10,  6.20it/s]

 16%|█████████▋                                                   | 153/960 [00:25<02:10,  6.18it/s]

 16%|█████████▊                                                   | 154/960 [00:25<02:11,  6.13it/s]

 16%|█████████▊                                                   | 155/960 [00:25<02:13,  6.01it/s]

 16%|█████████▉                                                   | 156/960 [00:26<02:15,  5.95it/s]

 16%|█████████▉                                                   | 157/960 [00:26<02:15,  5.92it/s]

 16%|██████████                                                   | 158/960 [00:26<02:18,  5.80it/s]

 17%|██████████                                                   | 159/960 [00:26<02:22,  5.62it/s]

 17%|██████████▏                                                  | 160/960 [00:26<02:19,  5.72it/s]

 17%|██████████▏                                                  | 161/960 [00:26<02:17,  5.81it/s]

 17%|██████████▎                                                  | 162/960 [00:27<02:14,  5.92it/s]

 17%|██████████▎                                                  | 163/960 [00:27<02:17,  5.80it/s]

 17%|██████████▍                                                  | 164/960 [00:27<02:13,  5.97it/s]

 17%|██████████▍                                                  | 165/960 [00:27<02:10,  6.11it/s]

 17%|██████████▌                                                  | 166/960 [00:27<02:08,  6.17it/s]

 17%|██████████▌                                                  | 167/960 [00:27<02:07,  6.24it/s]

 18%|██████████▋                                                  | 168/960 [00:28<02:06,  6.26it/s]

 18%|██████████▋                                                  | 169/960 [00:28<02:05,  6.29it/s]

 18%|██████████▊                                                  | 170/960 [00:28<02:07,  6.21it/s]

 18%|██████████▊                                                  | 171/960 [00:28<02:06,  6.22it/s]

 18%|██████████▉                                                  | 172/960 [00:28<02:07,  6.18it/s]

 18%|██████████▉                                                  | 173/960 [00:28<02:08,  6.13it/s]

 18%|███████████                                                  | 174/960 [00:29<02:09,  6.07it/s]

 18%|███████████                                                  | 175/960 [00:29<02:11,  5.98it/s]

 18%|███████████▏                                                 | 176/960 [00:29<02:10,  6.00it/s]

 18%|███████████▏                                                 | 177/960 [00:29<02:12,  5.91it/s]

 19%|███████████▎                                                 | 178/960 [00:29<02:13,  5.86it/s]

 19%|███████████▎                                                 | 179/960 [00:29<02:12,  5.89it/s]

 19%|███████████▍                                                 | 180/960 [00:30<02:13,  5.83it/s]

 19%|███████████▌                                                 | 181/960 [00:30<02:12,  5.87it/s]

 19%|███████████▌                                                 | 182/960 [00:30<02:11,  5.90it/s]

 19%|███████████▋                                                 | 183/960 [00:30<02:09,  5.99it/s]

 19%|███████████▋                                                 | 184/960 [00:30<02:08,  6.04it/s]

 19%|███████████▊                                                 | 185/960 [00:30<02:07,  6.07it/s]

 19%|███████████▊                                                 | 186/960 [00:31<02:07,  6.08it/s]

 19%|███████████▉                                                 | 187/960 [00:31<02:07,  6.08it/s]

 20%|███████████▉                                                 | 188/960 [00:31<02:08,  6.03it/s]

 20%|████████████                                                 | 189/960 [00:31<02:07,  6.05it/s]

 20%|████████████                                                 | 190/960 [00:31<02:07,  6.03it/s]

 20%|████████████▏                                                | 191/960 [00:31<02:08,  5.97it/s]

 20%|████████████▏                                                | 192/960 [00:32<02:09,  5.93it/s]

 20%|████████████▎                                                | 193/960 [00:32<02:10,  5.90it/s]

 20%|████████████▎                                                | 194/960 [00:32<02:10,  5.88it/s]

 20%|████████████▍                                                | 195/960 [00:32<02:12,  5.76it/s]

 20%|████████████▍                                                | 196/960 [00:32<02:10,  5.86it/s]

 21%|████████████▌                                                | 197/960 [00:32<02:10,  5.84it/s]

 21%|████████████▌                                                | 198/960 [00:33<02:10,  5.84it/s]

 21%|████████████▋                                                | 199/960 [00:33<02:08,  5.93it/s]

 21%|████████████▋                                                | 200/960 [00:33<02:07,  5.94it/s]

 21%|████████████▊                                                | 201/960 [00:33<02:05,  6.06it/s]

 21%|████████████▊                                                | 202/960 [00:33<02:02,  6.18it/s]

 21%|████████████▉                                                | 203/960 [00:33<02:00,  6.27it/s]

 21%|████████████▉                                                | 204/960 [00:34<01:59,  6.33it/s]

 21%|█████████████                                                | 205/960 [00:34<01:58,  6.36it/s]

 21%|█████████████                                                | 206/960 [00:34<01:58,  6.36it/s]

 22%|█████████████▏                                               | 207/960 [00:34<01:58,  6.33it/s]

 22%|█████████████▏                                               | 208/960 [00:34<01:59,  6.30it/s]

 22%|█████████████▎                                               | 209/960 [00:34<02:00,  6.26it/s]

 22%|█████████████▎                                               | 210/960 [00:34<02:00,  6.21it/s]

 22%|█████████████▍                                               | 211/960 [00:35<02:01,  6.16it/s]

 22%|█████████████▍                                               | 212/960 [00:35<02:04,  6.02it/s]

 22%|█████████████▌                                               | 213/960 [00:35<02:05,  5.96it/s]

 22%|█████████████▌                                               | 214/960 [00:35<02:06,  5.88it/s]

 22%|█████████████▋                                               | 215/960 [00:35<02:05,  5.95it/s]

 22%|█████████████▋                                               | 216/960 [00:36<02:04,  5.99it/s]

 23%|█████████████▊                                               | 217/960 [00:36<02:04,  5.99it/s]

 23%|█████████████▊                                               | 218/960 [00:36<02:02,  6.07it/s]

 23%|█████████████▉                                               | 219/960 [00:36<02:02,  6.05it/s]

 23%|█████████████▉                                               | 220/960 [00:36<01:59,  6.19it/s]

 23%|██████████████                                               | 221/960 [00:36<01:57,  6.30it/s]

 23%|██████████████                                               | 222/960 [00:36<01:56,  6.36it/s]

 23%|██████████████▏                                              | 223/960 [00:37<01:55,  6.38it/s]

 23%|██████████████▏                                              | 224/960 [00:37<01:55,  6.38it/s]

 23%|██████████████▎                                              | 225/960 [00:37<01:55,  6.39it/s]

 24%|██████████████▎                                              | 226/960 [00:37<01:55,  6.36it/s]

 24%|██████████████▍                                              | 227/960 [00:37<01:56,  6.29it/s]

 24%|██████████████▍                                              | 228/960 [00:37<01:56,  6.27it/s]

 24%|██████████████▌                                              | 229/960 [00:38<01:57,  6.21it/s]

 24%|██████████████▌                                              | 230/960 [00:38<01:58,  6.15it/s]

 24%|██████████████▋                                              | 231/960 [00:38<02:00,  6.04it/s]

 24%|██████████████▋                                              | 232/960 [00:38<02:00,  6.05it/s]

 24%|██████████████▊                                              | 233/960 [00:38<02:01,  5.99it/s]

 24%|██████████████▊                                              | 234/960 [00:38<02:00,  6.03it/s]

 24%|██████████████▉                                              | 235/960 [00:39<01:59,  6.07it/s]

 25%|██████████████▉                                              | 236/960 [00:39<02:00,  5.98it/s]

 25%|███████████████                                              | 237/960 [00:39<02:00,  5.98it/s]

 25%|███████████████                                              | 238/960 [00:39<02:00,  6.00it/s]

 25%|███████████████▏                                             | 239/960 [00:39<01:59,  6.05it/s]

 25%|███████████████▎                                             | 240/960 [00:39<01:57,  6.12it/s]

 25%|███████████████▎                                             | 241/960 [00:40<01:57,  6.13it/s]

 25%|███████████████▍                                             | 242/960 [00:40<01:56,  6.16it/s]

 25%|███████████████▍                                             | 243/960 [00:40<01:56,  6.17it/s]

 25%|███████████████▌                                             | 244/960 [00:40<01:55,  6.18it/s]

 26%|███████████████▌                                             | 245/960 [00:40<01:56,  6.15it/s]

 26%|███████████████▋                                             | 246/960 [00:40<01:57,  6.08it/s]

 26%|███████████████▋                                             | 247/960 [00:41<01:58,  6.02it/s]

 26%|███████████████▊                                             | 248/960 [00:41<01:59,  5.96it/s]

 26%|███████████████▊                                             | 249/960 [00:41<01:59,  5.94it/s]

 26%|███████████████▉                                             | 250/960 [00:41<02:03,  5.76it/s]

 26%|███████████████▉                                             | 251/960 [00:41<02:03,  5.75it/s]

 26%|████████████████                                             | 252/960 [00:41<02:05,  5.65it/s]

 26%|████████████████                                             | 253/960 [00:42<02:02,  5.75it/s]

 26%|████████████████▏                                            | 254/960 [00:42<02:02,  5.76it/s]

 27%|████████████████▏                                            | 255/960 [00:42<02:01,  5.80it/s]

 27%|████████████████▎                                            | 256/960 [00:42<02:00,  5.83it/s]

 27%|████████████████▎                                            | 257/960 [00:42<02:00,  5.81it/s]

 27%|████████████████▍                                            | 258/960 [00:42<01:57,  5.96it/s]

 27%|████████████████▍                                            | 259/960 [00:43<01:57,  5.97it/s]

 27%|████████████████▌                                            | 260/960 [00:43<01:55,  6.05it/s]

 27%|████████████████▌                                            | 261/960 [00:43<01:55,  6.07it/s]

 27%|████████████████▋                                            | 262/960 [00:43<01:54,  6.09it/s]

 27%|████████████████▋                                            | 263/960 [00:43<01:54,  6.10it/s]

 28%|████████████████▊                                            | 264/960 [00:43<01:54,  6.06it/s]

 28%|████████████████▊                                            | 265/960 [00:44<01:55,  6.02it/s]

 28%|████████████████▉                                            | 266/960 [00:44<01:56,  5.96it/s]

 28%|████████████████▉                                            | 267/960 [00:44<01:56,  5.93it/s]

 28%|█████████████████                                            | 268/960 [00:44<01:57,  5.87it/s]

 28%|█████████████████                                            | 269/960 [00:44<01:58,  5.85it/s]

 28%|█████████████████▏                                           | 270/960 [00:44<01:58,  5.82it/s]

 28%|█████████████████▏                                           | 271/960 [00:45<01:59,  5.77it/s]

 28%|█████████████████▎                                           | 272/960 [00:45<01:59,  5.77it/s]

 28%|█████████████████▎                                           | 273/960 [00:45<01:58,  5.79it/s]

 29%|█████████████████▍                                           | 274/960 [00:45<01:58,  5.81it/s]

 29%|█████████████████▍                                           | 275/960 [00:45<01:57,  5.82it/s]

 29%|█████████████████▌                                           | 276/960 [00:45<01:56,  5.89it/s]

 29%|█████████████████▌                                           | 277/960 [00:46<01:55,  5.93it/s]

 29%|█████████████████▋                                           | 278/960 [00:46<01:53,  6.03it/s]

 29%|█████████████████▋                                           | 279/960 [00:46<01:53,  6.00it/s]

 29%|█████████████████▊                                           | 280/960 [00:46<01:52,  6.07it/s]

 29%|█████████████████▊                                           | 281/960 [00:46<01:51,  6.08it/s]

 29%|█████████████████▉                                           | 282/960 [00:46<01:52,  6.02it/s]

 29%|█████████████████▉                                           | 283/960 [00:47<01:52,  6.00it/s]

 30%|██████████████████                                           | 284/960 [00:47<01:52,  5.99it/s]

 30%|██████████████████                                           | 285/960 [00:47<01:54,  5.92it/s]

 30%|██████████████████▏                                          | 286/960 [00:47<01:54,  5.88it/s]

 30%|██████████████████▏                                          | 287/960 [00:47<01:55,  5.84it/s]

 30%|██████████████████▎                                          | 288/960 [00:48<01:55,  5.81it/s]

 30%|██████████████████▎                                          | 289/960 [00:48<01:56,  5.75it/s]

 30%|██████████████████▍                                          | 290/960 [00:48<01:57,  5.68it/s]

 30%|██████████████████▍                                          | 291/960 [00:48<01:57,  5.71it/s]

 30%|██████████████████▌                                          | 292/960 [00:48<01:55,  5.77it/s]

 31%|██████████████████▌                                          | 293/960 [00:48<01:56,  5.72it/s]

 31%|██████████████████▋                                          | 294/960 [00:49<01:58,  5.62it/s]

 31%|██████████████████▋                                          | 295/960 [00:49<01:55,  5.77it/s]

 31%|██████████████████▊                                          | 296/960 [00:49<01:52,  5.91it/s]

 31%|██████████████████▊                                          | 297/960 [00:49<01:50,  5.99it/s]

 31%|██████████████████▉                                          | 298/960 [00:49<01:49,  6.05it/s]

 31%|██████████████████▉                                          | 299/960 [00:49<01:49,  6.04it/s]

 31%|███████████████████                                          | 300/960 [00:50<01:49,  6.02it/s]

 31%|███████████████████▏                                         | 301/960 [00:50<01:49,  6.01it/s]

 31%|███████████████████▏                                         | 302/960 [00:50<01:48,  6.08it/s]

 32%|███████████████████▎                                         | 303/960 [00:50<01:47,  6.11it/s]

 32%|███████████████████▎                                         | 304/960 [00:50<01:47,  6.11it/s]

 32%|███████████████████▍                                         | 305/960 [00:50<01:47,  6.07it/s]

 32%|███████████████████▍                                         | 306/960 [00:51<01:49,  5.97it/s]

 32%|███████████████████▌                                         | 307/960 [00:51<01:48,  6.03it/s]

 32%|███████████████████▌                                         | 308/960 [00:51<01:49,  5.95it/s]

 32%|███████████████████▋                                         | 309/960 [00:51<01:48,  5.99it/s]

 32%|███████████████████▋                                         | 310/960 [00:51<01:47,  6.03it/s]

 32%|███████████████████▊                                         | 311/960 [00:51<01:48,  6.00it/s]

 32%|███████████████████▊                                         | 312/960 [00:52<01:47,  6.01it/s]

 33%|███████████████████▉                                         | 313/960 [00:52<01:46,  6.07it/s]

 33%|███████████████████▉                                         | 314/960 [00:52<01:43,  6.21it/s]

 33%|████████████████████                                         | 315/960 [00:52<01:42,  6.27it/s]

 33%|████████████████████                                         | 316/960 [00:52<01:43,  6.25it/s]

 33%|████████████████████▏                                        | 317/960 [00:52<01:42,  6.29it/s]

 33%|████████████████████▏                                        | 318/960 [00:52<01:41,  6.31it/s]

 33%|████████████████████▎                                        | 319/960 [00:53<01:41,  6.31it/s]

 33%|████████████████████▎                                        | 320/960 [00:53<01:42,  6.26it/s]

 33%|████████████████████▍                                        | 321/960 [00:53<01:43,  6.20it/s]

 34%|████████████████████▍                                        | 322/960 [00:53<01:45,  6.05it/s]

 34%|████████████████████▌                                        | 323/960 [00:53<01:46,  5.97it/s]

 34%|████████████████████▌                                        | 324/960 [00:53<01:47,  5.93it/s]

 34%|████████████████████▋                                        | 325/960 [00:54<01:49,  5.80it/s]

 34%|████████████████████▋                                        | 326/960 [00:54<01:48,  5.82it/s]

 34%|████████████████████▊                                        | 327/960 [00:54<01:47,  5.91it/s]

 34%|████████████████████▊                                        | 328/960 [00:54<01:45,  6.00it/s]

 34%|████████████████████▉                                        | 329/960 [00:54<01:44,  6.01it/s]

 34%|████████████████████▉                                        | 330/960 [00:54<01:43,  6.07it/s]

 34%|█████████████████████                                        | 331/960 [00:55<01:43,  6.06it/s]

 35%|█████████████████████                                        | 332/960 [00:55<01:41,  6.17it/s]

 35%|█████████████████████▏                                       | 333/960 [00:55<01:40,  6.25it/s]

 35%|█████████████████████▏                                       | 334/960 [00:55<01:39,  6.29it/s]

 35%|█████████████████████▎                                       | 335/960 [00:55<01:38,  6.32it/s]

 35%|█████████████████████▎                                       | 336/960 [00:55<01:38,  6.34it/s]

 35%|█████████████████████▍                                       | 337/960 [00:56<01:38,  6.30it/s]

 35%|█████████████████████▍                                       | 338/960 [00:56<01:39,  6.25it/s]

 35%|█████████████████████▌                                       | 339/960 [00:56<01:39,  6.23it/s]

 35%|█████████████████████▌                                       | 340/960 [00:56<01:40,  6.17it/s]

 36%|█████████████████████▋                                       | 341/960 [00:56<01:41,  6.11it/s]

 36%|█████████████████████▋                                       | 342/960 [00:56<01:43,  6.00it/s]

 36%|█████████████████████▊                                       | 343/960 [00:57<01:43,  5.96it/s]

 36%|█████████████████████▊                                       | 344/960 [00:57<01:45,  5.84it/s]

 36%|█████████████████████▉                                       | 345/960 [00:57<01:44,  5.87it/s]

 36%|█████████████████████▉                                       | 346/960 [00:57<01:43,  5.95it/s]

 36%|██████████████████████                                       | 347/960 [00:57<01:42,  5.97it/s]

 36%|██████████████████████                                       | 348/960 [00:57<01:41,  6.01it/s]

 36%|██████████████████████▏                                      | 349/960 [00:58<01:41,  6.02it/s]

 36%|██████████████████████▏                                      | 350/960 [00:58<01:39,  6.11it/s]

 37%|██████████████████████▎                                      | 351/960 [00:58<01:38,  6.21it/s]

 37%|██████████████████████▎                                      | 352/960 [00:58<01:36,  6.27it/s]

 37%|██████████████████████▍                                      | 353/960 [00:58<01:36,  6.31it/s]

 37%|██████████████████████▍                                      | 354/960 [00:58<01:35,  6.33it/s]

 37%|██████████████████████▌                                      | 355/960 [00:59<01:34,  6.37it/s]

 37%|██████████████████████▌                                      | 356/960 [00:59<01:35,  6.29it/s]

 37%|██████████████████████▋                                      | 357/960 [00:59<01:48,  5.58it/s]

 37%|██████████████████████▋                                      | 358/960 [00:59<01:45,  5.70it/s]

 37%|██████████████████████▊                                      | 359/960 [00:59<01:44,  5.76it/s]

 38%|██████████████████████▉                                      | 360/960 [00:59<01:44,  5.77it/s]

 38%|██████████████████████▉                                      | 361/960 [01:00<01:42,  5.82it/s]

 38%|███████████████████████                                      | 362/960 [01:00<01:42,  5.84it/s]

 38%|███████████████████████                                      | 363/960 [01:00<01:41,  5.91it/s]

 38%|███████████████████████▏                                     | 364/960 [01:00<01:39,  5.99it/s]

 38%|███████████████████████▏                                     | 365/960 [01:00<01:38,  6.03it/s]

 38%|███████████████████████▎                                     | 366/960 [01:00<01:37,  6.09it/s]

 38%|███████████████████████▎                                     | 367/960 [01:01<01:36,  6.13it/s]

 38%|███████████████████████▍                                     | 368/960 [01:01<01:35,  6.19it/s]

 38%|███████████████████████▍                                     | 369/960 [01:01<01:34,  6.24it/s]

 39%|███████████████████████▌                                     | 370/960 [01:01<01:33,  6.29it/s]

 39%|███████████████████████▌                                     | 371/960 [01:01<01:33,  6.30it/s]

 39%|███████████████████████▋                                     | 372/960 [01:01<01:33,  6.29it/s]

 39%|███████████████████████▋                                     | 373/960 [01:02<01:33,  6.29it/s]

 39%|███████████████████████▊                                     | 374/960 [01:02<01:34,  6.17it/s]

 39%|███████████████████████▊                                     | 375/960 [01:02<01:34,  6.16it/s]

 39%|███████████████████████▉                                     | 376/960 [01:02<01:37,  6.00it/s]

 39%|███████████████████████▉                                     | 377/960 [01:02<01:37,  5.98it/s]

 39%|████████████████████████                                     | 378/960 [01:02<01:38,  5.92it/s]

 39%|████████████████████████                                     | 379/960 [01:03<01:38,  5.88it/s]

 40%|████████████████████████▏                                    | 380/960 [01:03<01:38,  5.89it/s]

 40%|████████████████████████▏                                    | 381/960 [01:03<01:36,  6.01it/s]

 40%|████████████████████████▎                                    | 382/960 [01:03<01:35,  6.05it/s]

 40%|████████████████████████▎                                    | 383/960 [01:03<01:34,  6.08it/s]

 40%|████████████████████████▍                                    | 384/960 [01:03<01:34,  6.09it/s]

 40%|████████████████████████▍                                    | 385/960 [01:04<01:34,  6.10it/s]

 40%|████████████████████████▌                                    | 386/960 [01:04<01:34,  6.07it/s]

 40%|████████████████████████▌                                    | 387/960 [01:04<01:32,  6.18it/s]

 40%|████████████████████████▋                                    | 388/960 [01:04<01:31,  6.25it/s]

 41%|████████████████████████▋                                    | 389/960 [01:04<01:30,  6.30it/s]

 41%|████████████████████████▊                                    | 390/960 [01:04<01:30,  6.27it/s]

 41%|████████████████████████▊                                    | 391/960 [01:04<01:30,  6.31it/s]

 41%|████████████████████████▉                                    | 392/960 [01:05<01:31,  6.23it/s]

 41%|████████████████████████▉                                    | 393/960 [01:05<01:31,  6.21it/s]

 41%|█████████████████████████                                    | 394/960 [01:05<01:31,  6.20it/s]

 41%|█████████████████████████                                    | 395/960 [01:05<01:32,  6.13it/s]

 41%|█████████████████████████▏                                   | 396/960 [01:05<01:32,  6.07it/s]

 41%|█████████████████████████▏                                   | 397/960 [01:05<01:33,  6.02it/s]

 41%|█████████████████████████▎                                   | 398/960 [01:06<01:33,  5.98it/s]

 42%|█████████████████████████▎                                   | 399/960 [01:06<01:32,  6.07it/s]

 42%|█████████████████████████▍                                   | 400/960 [01:06<01:33,  5.98it/s]

 42%|█████████████████████████▍                                   | 401/960 [01:06<01:34,  5.93it/s]

 42%|█████████████████████████▌                                   | 402/960 [01:06<01:34,  5.88it/s]

 42%|█████████████████████████▌                                   | 403/960 [01:06<01:34,  5.90it/s]

 42%|█████████████████████████▋                                   | 404/960 [01:07<01:33,  5.94it/s]

 42%|█████████████████████████▋                                   | 405/960 [01:07<01:31,  6.05it/s]

 42%|█████████████████████████▊                                   | 406/960 [01:07<01:31,  6.09it/s]

 42%|█████████████████████████▊                                   | 407/960 [01:07<01:31,  6.07it/s]

 42%|█████████████████████████▉                                   | 408/960 [01:07<01:29,  6.14it/s]

 43%|█████████████████████████▉                                   | 409/960 [01:07<01:31,  6.03it/s]

 43%|██████████████████████████                                   | 410/960 [01:08<01:30,  6.10it/s]

 43%|██████████████████████████                                   | 411/960 [01:08<01:29,  6.12it/s]

 43%|██████████████████████████▏                                  | 412/960 [01:08<01:30,  6.04it/s]

 43%|██████████████████████████▏                                  | 413/960 [01:08<01:31,  5.98it/s]

 43%|██████████████████████████▎                                  | 414/960 [01:08<01:31,  5.94it/s]

 43%|██████████████████████████▎                                  | 415/960 [01:08<01:31,  5.97it/s]

 43%|██████████████████████████▍                                  | 416/960 [01:09<01:31,  5.97it/s]

 43%|██████████████████████████▍                                  | 417/960 [01:09<01:29,  6.06it/s]

 44%|██████████████████████████▌                                  | 418/960 [01:09<01:29,  6.04it/s]

 44%|██████████████████████████▌                                  | 419/960 [01:09<01:29,  6.05it/s]

 44%|██████████████████████████▋                                  | 420/960 [01:09<01:29,  6.04it/s]

 44%|██████████████████████████▊                                  | 421/960 [01:09<01:32,  5.85it/s]

 44%|██████████████████████████▊                                  | 422/960 [01:10<01:32,  5.81it/s]

 44%|██████████████████████████▉                                  | 423/960 [01:10<01:33,  5.73it/s]

 44%|██████████████████████████▉                                  | 424/960 [01:10<01:31,  5.84it/s]

 44%|███████████████████████████                                  | 425/960 [01:10<01:29,  6.00it/s]

 44%|███████████████████████████                                  | 426/960 [01:10<01:27,  6.13it/s]

 44%|███████████████████████████▏                                 | 427/960 [01:10<01:26,  6.14it/s]

 45%|███████████████████████████▏                                 | 428/960 [01:11<01:28,  6.04it/s]

 45%|███████████████████████████▎                                 | 429/960 [01:11<01:28,  5.99it/s]

 45%|███████████████████████████▎                                 | 430/960 [01:11<01:28,  6.01it/s]

 45%|███████████████████████████▍                                 | 431/960 [01:11<01:28,  5.96it/s]

 45%|███████████████████████████▍                                 | 432/960 [01:11<01:29,  5.91it/s]

 45%|███████████████████████████▌                                 | 433/960 [01:12<01:30,  5.83it/s]

 45%|███████████████████████████▌                                 | 434/960 [01:12<01:29,  5.90it/s]

 45%|███████████████████████████▋                                 | 435/960 [01:12<01:27,  5.99it/s]

 45%|███████████████████████████▋                                 | 436/960 [01:12<01:26,  6.04it/s]

 46%|███████████████████████████▊                                 | 437/960 [01:12<01:27,  5.99it/s]

 46%|███████████████████████████▊                                 | 438/960 [01:12<01:27,  6.00it/s]

 46%|███████████████████████████▉                                 | 439/960 [01:12<01:25,  6.07it/s]

 46%|███████████████████████████▉                                 | 440/960 [01:13<01:25,  6.07it/s]

 46%|████████████████████████████                                 | 441/960 [01:13<01:25,  6.07it/s]

 46%|████████████████████████████                                 | 442/960 [01:13<01:24,  6.16it/s]

 46%|████████████████████████████▏                                | 443/960 [01:13<01:23,  6.18it/s]

 46%|████████████████████████████▏                                | 444/960 [01:13<01:22,  6.22it/s]

 46%|████████████████████████████▎                                | 445/960 [01:13<01:22,  6.22it/s]

 46%|████████████████████████████▎                                | 446/960 [01:14<01:22,  6.21it/s]

 47%|████████████████████████████▍                                | 447/960 [01:14<01:23,  6.15it/s]

 47%|████████████████████████████▍                                | 448/960 [01:14<01:23,  6.11it/s]

 47%|████████████████████████████▌                                | 449/960 [01:14<01:25,  6.00it/s]

 47%|████████████████████████████▌                                | 450/960 [01:14<01:24,  6.04it/s]

 47%|████████████████████████████▋                                | 451/960 [01:14<01:24,  6.00it/s]

 47%|████████████████████████████▋                                | 452/960 [01:15<01:24,  6.04it/s]

 47%|████████████████████████████▊                                | 453/960 [01:15<01:22,  6.11it/s]

 47%|████████████████████████████▊                                | 454/960 [01:15<01:22,  6.14it/s]

 47%|████████████████████████████▉                                | 455/960 [01:15<01:22,  6.13it/s]

 48%|████████████████████████████▉                                | 456/960 [01:15<01:23,  6.03it/s]

 48%|█████████████████████████████                                | 457/960 [01:15<01:23,  6.04it/s]

 48%|█████████████████████████████                                | 458/960 [01:16<01:24,  5.95it/s]

 48%|█████████████████████████████▏                               | 459/960 [01:16<01:23,  5.97it/s]

 48%|█████████████████████████████▏                               | 460/960 [01:16<01:22,  6.03it/s]

 48%|█████████████████████████████▎                               | 461/960 [01:16<01:22,  6.06it/s]

 48%|█████████████████████████████▎                               | 462/960 [01:16<01:22,  6.06it/s]

 48%|█████████████████████████████▍                               | 463/960 [01:16<01:22,  6.05it/s]

 48%|█████████████████████████████▍                               | 464/960 [01:17<01:22,  6.05it/s]

 48%|█████████████████████████████▌                               | 465/960 [01:17<01:22,  6.01it/s]

 49%|█████████████████████████████▌                               | 466/960 [01:17<01:23,  5.92it/s]

 49%|█████████████████████████████▋                               | 467/960 [01:17<01:24,  5.84it/s]

 49%|█████████████████████████████▋                               | 468/960 [01:17<01:24,  5.81it/s]

 49%|█████████████████████████████▊                               | 469/960 [01:17<01:23,  5.87it/s]

 49%|█████████████████████████████▊                               | 470/960 [01:18<01:23,  5.89it/s]

 49%|█████████████████████████████▉                               | 471/960 [01:18<01:22,  5.93it/s]

 49%|█████████████████████████████▉                               | 472/960 [01:18<01:22,  5.95it/s]

 49%|██████████████████████████████                               | 473/960 [01:18<01:22,  5.94it/s]

 49%|██████████████████████████████                               | 474/960 [01:18<01:23,  5.82it/s]

 49%|██████████████████████████████▏                              | 475/960 [01:18<01:24,  5.77it/s]

 50%|██████████████████████████████▏                              | 476/960 [01:19<01:24,  5.74it/s]

 50%|██████████████████████████████▎                              | 477/960 [01:19<01:23,  5.82it/s]

 50%|██████████████████████████████▎                              | 478/960 [01:19<01:21,  5.92it/s]

 50%|██████████████████████████████▍                              | 479/960 [01:19<01:20,  5.94it/s]

 50%|██████████████████████████████▌                              | 480/960 [01:19<01:20,  5.96it/s]

 50%|██████████████████████████████▌                              | 481/960 [01:20<01:21,  5.91it/s]

 50%|██████████████████████████████▋                              | 482/960 [01:20<01:20,  5.92it/s]

 50%|██████████████████████████████▋                              | 483/960 [01:20<01:21,  5.82it/s]

 50%|██████████████████████████████▊                              | 484/960 [01:20<01:22,  5.76it/s]

 51%|██████████████████████████████▊                              | 485/960 [01:20<01:22,  5.73it/s]

 51%|██████████████████████████████▉                              | 486/960 [01:20<01:22,  5.76it/s]

 51%|██████████████████████████████▉                              | 487/960 [01:21<01:21,  5.77it/s]

 51%|███████████████████████████████                              | 488/960 [01:21<01:21,  5.76it/s]

 51%|███████████████████████████████                              | 489/960 [01:21<01:21,  5.81it/s]

 51%|███████████████████████████████▏                             | 490/960 [01:21<01:20,  5.84it/s]

 51%|███████████████████████████████▏                             | 491/960 [01:21<01:20,  5.82it/s]

 51%|███████████████████████████████▎                             | 492/960 [01:21<01:21,  5.72it/s]

 51%|███████████████████████████████▎                             | 493/960 [01:22<01:21,  5.75it/s]

 51%|███████████████████████████████▍                             | 494/960 [01:22<01:21,  5.72it/s]

 52%|███████████████████████████████▍                             | 495/960 [01:22<01:19,  5.83it/s]

 52%|███████████████████████████████▌                             | 496/960 [01:22<01:18,  5.90it/s]

 52%|███████████████████████████████▌                             | 497/960 [01:22<01:18,  5.88it/s]

 52%|███████████████████████████████▋                             | 498/960 [01:22<01:18,  5.85it/s]

 52%|███████████████████████████████▋                             | 499/960 [01:23<01:18,  5.85it/s]

 52%|███████████████████████████████▊                             | 500/960 [01:23<01:19,  5.81it/s]

 52%|███████████████████████████████▊                             | 501/960 [01:23<01:20,  5.72it/s]

 52%|███████████████████████████████▉                             | 502/960 [01:23<01:20,  5.67it/s]

 52%|███████████████████████████████▉                             | 503/960 [01:23<01:20,  5.64it/s]

 52%|████████████████████████████████                             | 504/960 [01:24<01:20,  5.65it/s]

 53%|████████████████████████████████                             | 505/960 [01:24<01:18,  5.76it/s]

 53%|████████████████████████████████▏                            | 506/960 [01:24<01:21,  5.60it/s]

 53%|████████████████████████████████▏                            | 507/960 [01:24<01:19,  5.71it/s]

 53%|████████████████████████████████▎                            | 508/960 [01:24<01:17,  5.80it/s]

 53%|████████████████████████████████▎                            | 509/960 [01:24<01:18,  5.75it/s]

 53%|████████████████████████████████▍                            | 510/960 [01:25<01:17,  5.77it/s]

 53%|████████████████████████████████▍                            | 511/960 [01:25<01:16,  5.86it/s]

 53%|████████████████████████████████▌                            | 512/960 [01:25<01:14,  5.99it/s]

 53%|████████████████████████████████▌                            | 513/960 [01:25<01:13,  6.04it/s]

 54%|████████████████████████████████▋                            | 514/960 [01:25<01:12,  6.12it/s]

 54%|████████████████████████████████▋                            | 515/960 [01:25<01:12,  6.11it/s]

 54%|████████████████████████████████▊                            | 516/960 [01:26<01:13,  6.07it/s]

 54%|████████████████████████████████▊                            | 517/960 [01:26<01:12,  6.11it/s]

 54%|████████████████████████████████▉                            | 518/960 [01:26<01:12,  6.12it/s]

 54%|████████████████████████████████▉                            | 519/960 [01:26<01:12,  6.05it/s]

 54%|█████████████████████████████████                            | 520/960 [01:26<01:12,  6.04it/s]

 54%|█████████████████████████████████                            | 521/960 [01:26<01:13,  5.98it/s]

 54%|█████████████████████████████████▏                           | 522/960 [01:27<01:12,  6.05it/s]

 54%|█████████████████████████████████▏                           | 523/960 [01:27<01:12,  6.05it/s]

 55%|█████████████████████████████████▎                           | 524/960 [01:27<01:11,  6.09it/s]

 55%|█████████████████████████████████▎                           | 525/960 [01:27<01:11,  6.11it/s]

 55%|█████████████████████████████████▍                           | 526/960 [01:27<01:11,  6.04it/s]

 55%|█████████████████████████████████▍                           | 527/960 [01:27<01:12,  5.94it/s]

 55%|█████████████████████████████████▌                           | 528/960 [01:28<01:13,  5.84it/s]

 55%|█████████████████████████████████▌                           | 529/960 [01:28<01:13,  5.86it/s]

 55%|█████████████████████████████████▋                           | 530/960 [01:28<01:11,  5.98it/s]

 55%|█████████████████████████████████▋                           | 531/960 [01:28<01:10,  6.07it/s]

 55%|█████████████████████████████████▊                           | 532/960 [01:28<01:09,  6.13it/s]

 56%|█████████████████████████████████▊                           | 533/960 [01:28<01:09,  6.15it/s]

 56%|█████████████████████████████████▉                           | 534/960 [01:28<01:09,  6.16it/s]

 56%|█████████████████████████████████▉                           | 535/960 [01:29<01:08,  6.17it/s]

 56%|██████████████████████████████████                           | 536/960 [01:29<01:09,  6.10it/s]

 56%|██████████████████████████████████                           | 537/960 [01:29<01:10,  5.99it/s]

 56%|██████████████████████████████████▏                          | 538/960 [01:29<01:10,  5.98it/s]

 56%|██████████████████████████████████▏                          | 539/960 [01:29<01:11,  5.91it/s]

 56%|██████████████████████████████████▎                          | 540/960 [01:29<01:10,  5.97it/s]

 56%|██████████████████████████████████▍                          | 541/960 [01:30<01:09,  6.05it/s]

 56%|██████████████████████████████████▍                          | 542/960 [01:30<01:08,  6.09it/s]

 57%|██████████████████████████████████▌                          | 543/960 [01:30<01:09,  6.04it/s]

 57%|██████████████████████████████████▌                          | 544/960 [01:30<01:08,  6.03it/s]

 57%|██████████████████████████████████▋                          | 545/960 [01:30<01:08,  6.06it/s]

 57%|██████████████████████████████████▋                          | 546/960 [01:30<01:08,  6.05it/s]

 57%|██████████████████████████████████▊                          | 547/960 [01:31<01:07,  6.09it/s]

 57%|██████████████████████████████████▊                          | 548/960 [01:31<01:06,  6.19it/s]

 57%|██████████████████████████████████▉                          | 549/960 [01:31<01:05,  6.24it/s]

 57%|██████████████████████████████████▉                          | 550/960 [01:31<01:05,  6.25it/s]

 57%|███████████████████████████████████                          | 551/960 [01:31<01:05,  6.22it/s]

 57%|███████████████████████████████████                          | 552/960 [01:31<01:05,  6.25it/s]

 58%|███████████████████████████████████▏                         | 553/960 [01:32<01:05,  6.23it/s]

 58%|███████████████████████████████████▏                         | 554/960 [01:32<01:05,  6.19it/s]

 58%|███████████████████████████████████▎                         | 555/960 [01:32<01:06,  6.11it/s]

 58%|███████████████████████████████████▎                         | 556/960 [01:32<01:06,  6.10it/s]

 58%|███████████████████████████████████▍                         | 557/960 [01:32<01:06,  6.05it/s]

 58%|███████████████████████████████████▍                         | 558/960 [01:32<01:05,  6.16it/s]

 58%|███████████████████████████████████▌                         | 559/960 [01:33<01:04,  6.21it/s]

 58%|███████████████████████████████████▌                         | 560/960 [01:33<01:04,  6.22it/s]

 58%|███████████████████████████████████▋                         | 561/960 [01:33<01:04,  6.21it/s]

 59%|███████████████████████████████████▋                         | 562/960 [01:33<01:04,  6.22it/s]

 59%|███████████████████████████████████▊                         | 563/960 [01:33<01:04,  6.20it/s]

 59%|███████████████████████████████████▊                         | 564/960 [01:33<01:04,  6.16it/s]

 59%|███████████████████████████████████▉                         | 565/960 [01:34<01:04,  6.14it/s]

 59%|███████████████████████████████████▉                         | 566/960 [01:34<01:04,  6.10it/s]

 59%|████████████████████████████████████                         | 567/960 [01:34<01:03,  6.18it/s]

 59%|████████████████████████████████████                         | 568/960 [01:34<01:03,  6.20it/s]

 59%|████████████████████████████████████▏                        | 569/960 [01:34<01:03,  6.19it/s]

 59%|████████████████████████████████████▏                        | 570/960 [01:34<01:02,  6.22it/s]

 59%|████████████████████████████████████▎                        | 571/960 [01:35<01:02,  6.22it/s]

 60%|████████████████████████████████████▎                        | 572/960 [01:35<01:02,  6.24it/s]

 60%|████████████████████████████████████▍                        | 573/960 [01:35<01:02,  6.15it/s]

 60%|████████████████████████████████████▍                        | 574/960 [01:35<01:02,  6.14it/s]

 60%|████████████████████████████████████▌                        | 575/960 [01:35<01:03,  6.09it/s]

 60%|████████████████████████████████████▌                        | 576/960 [01:35<01:02,  6.13it/s]

 60%|████████████████████████████████████▋                        | 577/960 [01:35<01:01,  6.20it/s]

 60%|████████████████████████████████████▋                        | 578/960 [01:36<01:01,  6.26it/s]

 60%|████████████████████████████████████▊                        | 579/960 [01:36<01:00,  6.28it/s]

 60%|████████████████████████████████████▊                        | 580/960 [01:36<01:00,  6.28it/s]

 61%|████████████████████████████████████▉                        | 581/960 [01:36<01:00,  6.27it/s]

 61%|████████████████████████████████████▉                        | 582/960 [01:36<01:00,  6.22it/s]

 61%|█████████████████████████████████████                        | 583/960 [01:36<01:00,  6.19it/s]

 61%|█████████████████████████████████████                        | 584/960 [01:37<01:01,  6.12it/s]

 61%|█████████████████████████████████████▏                       | 585/960 [01:37<01:01,  6.10it/s]

 61%|█████████████████████████████████████▏                       | 586/960 [01:37<01:01,  6.05it/s]

 61%|█████████████████████████████████████▎                       | 587/960 [01:37<01:01,  6.08it/s]

 61%|█████████████████████████████████████▎                       | 588/960 [01:37<01:00,  6.14it/s]

 61%|█████████████████████████████████████▍                       | 589/960 [01:37<01:00,  6.12it/s]

 61%|█████████████████████████████████████▍                       | 590/960 [01:38<01:00,  6.14it/s]

 62%|█████████████████████████████████████▌                       | 591/960 [01:38<00:59,  6.17it/s]

 62%|█████████████████████████████████████▌                       | 592/960 [01:38<01:00,  6.12it/s]

 62%|█████████████████████████████████████▋                       | 593/960 [01:38<01:00,  6.11it/s]

 62%|█████████████████████████████████████▋                       | 594/960 [01:38<01:00,  6.08it/s]

 62%|█████████████████████████████████████▊                       | 595/960 [01:38<00:59,  6.12it/s]

 62%|█████████████████████████████████████▊                       | 596/960 [01:39<00:58,  6.19it/s]

 62%|█████████████████████████████████████▉                       | 597/960 [01:39<00:58,  6.24it/s]

 62%|█████████████████████████████████████▉                       | 598/960 [01:39<00:57,  6.26it/s]

 62%|██████████████████████████████████████                       | 599/960 [01:39<00:57,  6.30it/s]

 62%|██████████████████████████████████████▏                      | 600/960 [01:39<00:58,  6.18it/s]

 63%|██████████████████████████████████████▏                      | 601/960 [01:39<00:58,  6.14it/s]

 63%|██████████████████████████████████████▎                      | 602/960 [01:40<00:58,  6.15it/s]

 63%|██████████████████████████████████████▎                      | 603/960 [01:40<00:58,  6.09it/s]

 63%|██████████████████████████████████████▍                      | 604/960 [01:40<01:01,  5.78it/s]

 63%|██████████████████████████████████████▍                      | 605/960 [01:40<01:03,  5.57it/s]

 63%|██████████████████████████████████████▌                      | 606/960 [01:40<01:03,  5.59it/s]

 63%|██████████████████████████████████████▌                      | 607/960 [01:40<01:01,  5.77it/s]

 63%|██████████████████████████████████████▋                      | 608/960 [01:41<00:59,  5.87it/s]

 63%|██████████████████████████████████████▋                      | 609/960 [01:41<00:58,  5.97it/s]

 64%|██████████████████████████████████████▊                      | 610/960 [01:41<00:58,  5.99it/s]

 64%|██████████████████████████████████████▊                      | 611/960 [01:41<00:57,  6.02it/s]

 64%|██████████████████████████████████████▉                      | 612/960 [01:41<00:57,  6.05it/s]

 64%|██████████████████████████████████████▉                      | 613/960 [01:41<00:58,  5.92it/s]

 64%|███████████████████████████████████████                      | 614/960 [01:42<00:57,  6.07it/s]

 64%|███████████████████████████████████████                      | 615/960 [01:42<00:55,  6.17it/s]

 64%|███████████████████████████████████████▏                     | 616/960 [01:42<00:55,  6.20it/s]

 64%|███████████████████████████████████████▏                     | 617/960 [01:42<00:55,  6.19it/s]

 64%|███████████████████████████████████████▎                     | 618/960 [01:42<00:55,  6.20it/s]

 64%|███████████████████████████████████████▎                     | 619/960 [01:42<00:55,  6.13it/s]

 65%|███████████████████████████████████████▍                     | 620/960 [01:43<00:55,  6.14it/s]

 65%|███████████████████████████████████████▍                     | 621/960 [01:43<00:55,  6.08it/s]

 65%|███████████████████████████████████████▌                     | 622/960 [01:43<00:56,  5.98it/s]

 65%|███████████████████████████████████████▌                     | 623/960 [01:43<00:57,  5.88it/s]

 65%|███████████████████████████████████████▋                     | 624/960 [01:43<00:58,  5.75it/s]

 65%|███████████████████████████████████████▋                     | 625/960 [01:43<00:58,  5.71it/s]

 65%|███████████████████████████████████████▊                     | 626/960 [01:44<00:57,  5.80it/s]

 65%|███████████████████████████████████████▊                     | 627/960 [01:44<00:57,  5.79it/s]

 65%|███████████████████████████████████████▉                     | 628/960 [01:44<00:56,  5.87it/s]

 66%|███████████████████████████████████████▉                     | 629/960 [01:44<00:56,  5.88it/s]

 66%|████████████████████████████████████████                     | 630/960 [01:44<00:57,  5.78it/s]

 66%|████████████████████████████████████████                     | 631/960 [01:44<00:57,  5.77it/s]

 66%|████████████████████████████████████████▏                    | 632/960 [01:45<00:55,  5.91it/s]

 66%|████████████████████████████████████████▏                    | 633/960 [01:45<00:54,  5.98it/s]

 66%|████████████████████████████████████████▎                    | 634/960 [01:45<00:55,  5.89it/s]

 66%|████████████████████████████████████████▎                    | 635/960 [01:45<00:55,  5.87it/s]

 66%|████████████████████████████████████████▍                    | 636/960 [01:45<00:55,  5.81it/s]

 66%|████████████████████████████████████████▍                    | 637/960 [01:45<00:56,  5.67it/s]

 66%|████████████████████████████████████████▌                    | 638/960 [01:46<00:56,  5.70it/s]

 67%|████████████████████████████████████████▌                    | 639/960 [01:46<00:56,  5.73it/s]

 67%|████████████████████████████████████████▋                    | 640/960 [01:46<00:55,  5.76it/s]

 67%|████████████████████████████████████████▋                    | 641/960 [01:46<00:55,  5.70it/s]

 67%|████████████████████████████████████████▊                    | 642/960 [01:46<00:55,  5.78it/s]

 67%|████████████████████████████████████████▊                    | 643/960 [01:47<00:54,  5.83it/s]

 67%|████████████████████████████████████████▉                    | 644/960 [01:47<00:53,  5.85it/s]

 67%|████████████████████████████████████████▉                    | 645/960 [01:47<00:53,  5.86it/s]

 67%|█████████████████████████████████████████                    | 646/960 [01:47<00:53,  5.91it/s]

 67%|█████████████████████████████████████████                    | 647/960 [01:47<00:53,  5.81it/s]

 68%|█████████████████████████████████████████▏                   | 648/960 [01:47<00:53,  5.85it/s]

 68%|█████████████████████████████████████████▏                   | 649/960 [01:48<00:53,  5.84it/s]

 68%|█████████████████████████████████████████▎                   | 650/960 [01:48<00:53,  5.82it/s]

 68%|█████████████████████████████████████████▎                   | 651/960 [01:48<00:54,  5.71it/s]

 68%|█████████████████████████████████████████▍                   | 652/960 [01:48<00:53,  5.74it/s]

 68%|█████████████████████████████████████████▍                   | 653/960 [01:48<00:53,  5.75it/s]

 68%|█████████████████████████████████████████▌                   | 654/960 [01:48<00:52,  5.82it/s]

 68%|█████████████████████████████████████████▌                   | 655/960 [01:49<00:51,  5.87it/s]

 68%|█████████████████████████████████████████▋                   | 656/960 [01:49<00:51,  5.87it/s]

 68%|█████████████████████████████████████████▋                   | 657/960 [01:49<00:51,  5.89it/s]

 69%|█████████████████████████████████████████▊                   | 658/960 [01:49<00:51,  5.86it/s]

 69%|█████████████████████████████████████████▊                   | 659/960 [01:49<00:51,  5.86it/s]

 69%|█████████████████████████████████████████▉                   | 660/960 [01:49<00:51,  5.83it/s]

 69%|██████████████████████████████████████████                   | 661/960 [01:50<00:50,  5.87it/s]

 69%|██████████████████████████████████████████                   | 662/960 [01:50<00:50,  5.93it/s]

 69%|██████████████████████████████████████████▏                  | 663/960 [01:50<00:49,  5.98it/s]

 69%|██████████████████████████████████████████▏                  | 664/960 [01:50<00:49,  5.97it/s]

 69%|██████████████████████████████████████████▎                  | 665/960 [01:50<00:49,  5.94it/s]

 69%|██████████████████████████████████████████▎                  | 666/960 [01:50<00:49,  5.92it/s]

 69%|██████████████████████████████████████████▍                  | 667/960 [01:51<00:49,  5.88it/s]

 70%|██████████████████████████████████████████▍                  | 668/960 [01:51<00:49,  5.86it/s]

 70%|██████████████████████████████████████████▌                  | 669/960 [01:51<00:49,  5.83it/s]

 70%|██████████████████████████████████████████▌                  | 670/960 [01:51<00:50,  5.76it/s]

 70%|██████████████████████████████████████████▋                  | 671/960 [01:51<00:49,  5.80it/s]

 70%|██████████████████████████████████████████▋                  | 672/960 [01:51<00:48,  5.93it/s]

 70%|██████████████████████████████████████████▊                  | 673/960 [01:52<00:47,  5.98it/s]

 70%|██████████████████████████████████████████▊                  | 674/960 [01:52<00:47,  6.03it/s]

 70%|██████████████████████████████████████████▉                  | 675/960 [01:52<00:47,  6.01it/s]

 70%|██████████████████████████████████████████▉                  | 676/960 [01:52<00:46,  6.08it/s]

 71%|███████████████████████████████████████████                  | 677/960 [01:52<00:46,  6.06it/s]

 71%|███████████████████████████████████████████                  | 678/960 [01:52<00:46,  6.10it/s]

 71%|███████████████████████████████████████████▏                 | 679/960 [01:53<00:45,  6.17it/s]

 71%|███████████████████████████████████████████▏                 | 680/960 [01:53<00:45,  6.22it/s]

 71%|███████████████████████████████████████████▎                 | 681/960 [01:53<00:44,  6.24it/s]

 71%|███████████████████████████████████████████▎                 | 682/960 [01:53<00:44,  6.25it/s]

 71%|███████████████████████████████████████████▍                 | 683/960 [01:53<00:44,  6.26it/s]

 71%|███████████████████████████████████████████▍                 | 684/960 [01:53<00:44,  6.23it/s]

 71%|███████████████████████████████████████████▌                 | 685/960 [01:54<00:44,  6.20it/s]

 71%|███████████████████████████████████████████▌                 | 686/960 [01:54<00:44,  6.17it/s]

 72%|███████████████████████████████████████████▋                 | 687/960 [01:54<00:44,  6.08it/s]

 72%|███████████████████████████████████████████▋                 | 688/960 [01:54<00:44,  6.06it/s]

 72%|███████████████████████████████████████████▊                 | 689/960 [01:54<00:45,  5.93it/s]

 72%|███████████████████████████████████████████▊                 | 690/960 [01:54<00:46,  5.79it/s]

 72%|███████████████████████████████████████████▉                 | 691/960 [01:55<00:45,  5.88it/s]

 72%|███████████████████████████████████████████▉                 | 692/960 [01:55<00:44,  5.98it/s]

 72%|████████████████████████████████████████████                 | 693/960 [01:55<00:44,  5.97it/s]

 72%|████████████████████████████████████████████                 | 694/960 [01:55<00:45,  5.84it/s]

 72%|████████████████████████████████████████████▏                | 695/960 [01:55<00:45,  5.82it/s]

 72%|████████████████████████████████████████████▏                | 696/960 [01:55<00:44,  5.90it/s]

 73%|████████████████████████████████████████████▎                | 697/960 [01:56<00:43,  6.04it/s]

 73%|████████████████████████████████████████████▎                | 698/960 [01:56<00:44,  5.95it/s]

 73%|████████████████████████████████████████████▍                | 699/960 [01:56<00:43,  6.07it/s]

 73%|████████████████████████████████████████████▍                | 700/960 [01:56<00:42,  6.15it/s]

 73%|████████████████████████████████████████████▌                | 701/960 [01:56<00:42,  6.11it/s]

 73%|████████████████████████████████████████████▌                | 702/960 [01:56<00:43,  5.90it/s]

 73%|████████████████████████████████████████████▋                | 703/960 [01:57<00:43,  5.91it/s]

 73%|████████████████████████████████████████████▋                | 704/960 [01:57<00:43,  5.91it/s]

 73%|████████████████████████████████████████████▊                | 705/960 [01:57<00:42,  5.94it/s]

 74%|████████████████████████████████████████████▊                | 706/960 [01:57<00:43,  5.85it/s]

 74%|████████████████████████████████████████████▉                | 707/960 [01:57<00:42,  5.95it/s]

 74%|████████████████████████████████████████████▉                | 708/960 [01:57<00:42,  6.00it/s]

 74%|█████████████████████████████████████████████                | 709/960 [01:58<00:41,  5.98it/s]

 74%|█████████████████████████████████████████████                | 710/960 [01:58<00:41,  5.97it/s]

 74%|█████████████████████████████████████████████▏               | 711/960 [01:58<00:41,  5.99it/s]

 74%|█████████████████████████████████████████████▏               | 712/960 [01:58<00:41,  6.04it/s]

 74%|█████████████████████████████████████████████▎               | 713/960 [01:58<00:40,  6.03it/s]

 74%|█████████████████████████████████████████████▎               | 714/960 [01:58<00:40,  6.10it/s]

 74%|█████████████████████████████████████████████▍               | 715/960 [01:59<00:39,  6.19it/s]

 75%|█████████████████████████████████████████████▍               | 716/960 [01:59<00:39,  6.25it/s]

 75%|█████████████████████████████████████████████▌               | 717/960 [01:59<00:38,  6.27it/s]

 75%|█████████████████████████████████████████████▌               | 718/960 [01:59<00:45,  5.28it/s]

 75%|█████████████████████████████████████████████▋               | 719/960 [01:59<00:43,  5.52it/s]

 75%|█████████████████████████████████████████████▊               | 720/960 [01:59<00:42,  5.67it/s]

 75%|█████████████████████████████████████████████▊               | 721/960 [02:00<00:41,  5.72it/s]

 75%|█████████████████████████████████████████████▉               | 722/960 [02:00<00:41,  5.80it/s]

 75%|█████████████████████████████████████████████▉               | 723/960 [02:00<00:40,  5.82it/s]

 75%|██████████████████████████████████████████████               | 724/960 [02:00<00:40,  5.81it/s]

 76%|██████████████████████████████████████████████               | 725/960 [02:00<00:39,  5.93it/s]

 76%|██████████████████████████████████████████████▏              | 726/960 [02:00<00:39,  5.99it/s]

 76%|██████████████████████████████████████████████▏              | 727/960 [02:01<00:38,  6.00it/s]

 76%|██████████████████████████████████████████████▎              | 728/960 [02:01<00:38,  6.00it/s]

 76%|██████████████████████████████████████████████▎              | 729/960 [02:01<00:38,  6.04it/s]

 76%|██████████████████████████████████████████████▍              | 730/960 [02:01<00:37,  6.08it/s]

 76%|██████████████████████████████████████████████▍              | 731/960 [02:01<00:37,  6.16it/s]

 76%|██████████████████████████████████████████████▌              | 732/960 [02:01<00:36,  6.26it/s]

 76%|██████████████████████████████████████████████▌              | 733/960 [02:02<00:35,  6.35it/s]

 76%|██████████████████████████████████████████████▋              | 734/960 [02:02<00:35,  6.41it/s]

 77%|██████████████████████████████████████████████▋              | 735/960 [02:02<00:34,  6.44it/s]

 77%|██████████████████████████████████████████████▊              | 736/960 [02:02<00:34,  6.48it/s]

 77%|██████████████████████████████████████████████▊              | 737/960 [02:02<00:34,  6.47it/s]

 77%|██████████████████████████████████████████████▉              | 738/960 [02:02<00:34,  6.41it/s]

 77%|██████████████████████████████████████████████▉              | 739/960 [02:03<00:34,  6.36it/s]

 77%|███████████████████████████████████████████████              | 740/960 [02:03<00:34,  6.33it/s]

 77%|███████████████████████████████████████████████              | 741/960 [02:03<00:35,  6.13it/s]

 77%|███████████████████████████████████████████████▏             | 742/960 [02:03<00:36,  6.04it/s]

 77%|███████████████████████████████████████████████▏             | 743/960 [02:03<00:35,  6.08it/s]

 78%|███████████████████████████████████████████████▎             | 744/960 [02:03<00:35,  6.00it/s]

 78%|███████████████████████████████████████████████▎             | 745/960 [02:04<00:36,  5.92it/s]

 78%|███████████████████████████████████████████████▍             | 746/960 [02:04<00:36,  5.86it/s]

 78%|███████████████████████████████████████████████▍             | 747/960 [02:04<00:37,  5.70it/s]

 78%|███████████████████████████████████████████████▌             | 748/960 [02:04<00:37,  5.73it/s]

 78%|███████████████████████████████████████████████▌             | 749/960 [02:04<00:37,  5.64it/s]

 78%|███████████████████████████████████████████████▋             | 750/960 [02:04<00:35,  5.88it/s]

 78%|███████████████████████████████████████████████▋             | 751/960 [02:05<00:34,  6.00it/s]

 78%|███████████████████████████████████████████████▊             | 752/960 [02:05<00:33,  6.14it/s]

 78%|███████████████████████████████████████████████▊             | 753/960 [02:05<00:33,  6.24it/s]

 79%|███████████████████████████████████████████████▉             | 754/960 [02:05<00:32,  6.32it/s]

 79%|███████████████████████████████████████████████▉             | 755/960 [02:05<00:32,  6.38it/s]

 79%|████████████████████████████████████████████████             | 756/960 [02:05<00:31,  6.41it/s]

 79%|████████████████████████████████████████████████             | 757/960 [02:06<00:31,  6.39it/s]

 79%|████████████████████████████████████████████████▏            | 758/960 [02:06<00:31,  6.34it/s]

 79%|████████████████████████████████████████████████▏            | 759/960 [02:06<00:31,  6.32it/s]

 79%|████████████████████████████████████████████████▎            | 760/960 [02:06<00:32,  6.24it/s]

 79%|████████████████████████████████████████████████▎            | 761/960 [02:06<00:32,  6.21it/s]

 79%|████████████████████████████████████████████████▍            | 762/960 [02:06<00:32,  6.17it/s]

 79%|████████████████████████████████████████████████▍            | 763/960 [02:06<00:32,  6.14it/s]

 80%|████████████████████████████████████████████████▌            | 764/960 [02:07<00:32,  6.08it/s]

 80%|████████████████████████████████████████████████▌            | 765/960 [02:07<00:32,  5.97it/s]

 80%|████████████████████████████████████████████████▋            | 766/960 [02:07<00:33,  5.79it/s]

 80%|████████████████████████████████████████████████▋            | 767/960 [02:07<00:33,  5.70it/s]

 80%|████████████████████████████████████████████████▊            | 768/960 [02:07<00:34,  5.57it/s]

 80%|████████████████████████████████████████████████▊            | 769/960 [02:08<00:33,  5.65it/s]

 80%|████████████████████████████████████████████████▉            | 770/960 [02:08<00:32,  5.87it/s]

 80%|████████████████████████████████████████████████▉            | 771/960 [02:08<00:31,  6.05it/s]

 80%|█████████████████████████████████████████████████            | 772/960 [02:08<00:30,  6.11it/s]

 81%|█████████████████████████████████████████████████            | 773/960 [02:08<00:30,  6.17it/s]

 81%|█████████████████████████████████████████████████▏           | 774/960 [02:08<00:29,  6.21it/s]

 81%|█████████████████████████████████████████████████▏           | 775/960 [02:09<00:29,  6.21it/s]

 81%|█████████████████████████████████████████████████▎           | 776/960 [02:09<00:29,  6.20it/s]

 81%|█████████████████████████████████████████████████▎           | 777/960 [02:09<00:29,  6.17it/s]

 81%|█████████████████████████████████████████████████▍           | 778/960 [02:09<00:29,  6.13it/s]

 81%|█████████████████████████████████████████████████▍           | 779/960 [02:09<00:29,  6.09it/s]

 81%|█████████████████████████████████████████████████▌           | 780/960 [02:09<00:29,  6.00it/s]

 81%|█████████████████████████████████████████████████▋           | 781/960 [02:10<00:30,  5.88it/s]

 81%|█████████████████████████████████████████████████▋           | 782/960 [02:10<00:30,  5.84it/s]

 82%|█████████████████████████████████████████████████▊           | 783/960 [02:10<00:30,  5.78it/s]

 82%|█████████████████████████████████████████████████▊           | 784/960 [02:10<00:31,  5.61it/s]

 82%|█████████████████████████████████████████████████▉           | 785/960 [02:10<00:31,  5.56it/s]

 82%|█████████████████████████████████████████████████▉           | 786/960 [02:10<00:31,  5.52it/s]

 82%|██████████████████████████████████████████████████           | 787/960 [02:11<00:30,  5.60it/s]

 82%|██████████████████████████████████████████████████           | 788/960 [02:11<00:30,  5.70it/s]

 82%|██████████████████████████████████████████████████▏          | 789/960 [02:11<00:29,  5.81it/s]

 82%|██████████████████████████████████████████████████▏          | 790/960 [02:11<00:28,  5.91it/s]

 82%|██████████████████████████████████████████████████▎          | 791/960 [02:11<00:28,  6.00it/s]

 82%|██████████████████████████████████████████████████▎          | 792/960 [02:11<00:27,  6.04it/s]

 83%|██████████████████████████████████████████████████▍          | 793/960 [02:12<00:27,  6.09it/s]

 83%|██████████████████████████████████████████████████▍          | 794/960 [02:12<00:27,  6.10it/s]

 83%|██████████████████████████████████████████████████▌          | 795/960 [02:12<00:27,  6.06it/s]

 83%|██████████████████████████████████████████████████▌          | 796/960 [02:12<00:27,  6.03it/s]

 83%|██████████████████████████████████████████████████▋          | 797/960 [02:12<00:27,  5.82it/s]

 83%|██████████████████████████████████████████████████▋          | 798/960 [02:12<00:27,  5.82it/s]

 83%|██████████████████████████████████████████████████▊          | 799/960 [02:13<00:27,  5.76it/s]

 83%|██████████████████████████████████████████████████▊          | 800/960 [02:13<00:27,  5.76it/s]

 83%|██████████████████████████████████████████████████▉          | 801/960 [02:13<00:28,  5.66it/s]

 84%|██████████████████████████████████████████████████▉          | 802/960 [02:13<00:27,  5.69it/s]

 84%|███████████████████████████████████████████████████          | 803/960 [02:13<00:27,  5.64it/s]

 84%|███████████████████████████████████████████████████          | 804/960 [02:14<00:28,  5.54it/s]

 84%|███████████████████████████████████████████████████▏         | 805/960 [02:14<00:27,  5.66it/s]

 84%|███████████████████████████████████████████████████▏         | 806/960 [02:14<00:26,  5.73it/s]

 84%|███████████████████████████████████████████████████▎         | 807/960 [02:14<00:26,  5.88it/s]

 84%|███████████████████████████████████████████████████▎         | 808/960 [02:14<00:25,  5.97it/s]

 84%|███████████████████████████████████████████████████▍         | 809/960 [02:14<00:24,  6.05it/s]

 84%|███████████████████████████████████████████████████▍         | 810/960 [02:14<00:24,  6.10it/s]

 84%|███████████████████████████████████████████████████▌         | 811/960 [02:15<00:24,  6.14it/s]

 85%|███████████████████████████████████████████████████▌         | 812/960 [02:15<00:24,  6.15it/s]

 85%|███████████████████████████████████████████████████▋         | 813/960 [02:15<00:23,  6.16it/s]

 85%|███████████████████████████████████████████████████▋         | 814/960 [02:15<00:23,  6.13it/s]

 85%|███████████████████████████████████████████████████▊         | 815/960 [02:15<00:23,  6.10it/s]

 85%|███████████████████████████████████████████████████▊         | 816/960 [02:15<00:23,  6.04it/s]

 85%|███████████████████████████████████████████████████▉         | 817/960 [02:16<00:23,  5.99it/s]

 85%|███████████████████████████████████████████████████▉         | 818/960 [02:16<00:24,  5.90it/s]

 85%|████████████████████████████████████████████████████         | 819/960 [02:16<00:24,  5.77it/s]

 85%|████████████████████████████████████████████████████         | 820/960 [02:16<00:24,  5.66it/s]

 86%|████████████████████████████████████████████████████▏        | 821/960 [02:16<00:24,  5.60it/s]

 86%|████████████████████████████████████████████████████▏        | 822/960 [02:17<00:24,  5.61it/s]

 86%|████████████████████████████████████████████████████▎        | 823/960 [02:17<00:24,  5.51it/s]

 86%|████████████████████████████████████████████████████▎        | 824/960 [02:17<00:24,  5.49it/s]

 86%|████████████████████████████████████████████████████▍        | 825/960 [02:17<00:24,  5.50it/s]

 86%|████████████████████████████████████████████████████▍        | 826/960 [02:17<00:24,  5.51it/s]

 86%|████████████████████████████████████████████████████▌        | 827/960 [02:17<00:23,  5.62it/s]

 86%|████████████████████████████████████████████████████▌        | 828/960 [02:18<00:22,  5.79it/s]

 86%|████████████████████████████████████████████████████▋        | 829/960 [02:18<00:22,  5.93it/s]

 86%|████████████████████████████████████████████████████▋        | 830/960 [02:18<00:21,  5.97it/s]

 87%|████████████████████████████████████████████████████▊        | 831/960 [02:18<00:21,  6.04it/s]

 87%|████████████████████████████████████████████████████▊        | 832/960 [02:18<00:20,  6.11it/s]

 87%|████████████████████████████████████████████████████▉        | 833/960 [02:18<00:20,  6.12it/s]

 87%|████████████████████████████████████████████████████▉        | 834/960 [02:19<00:20,  6.11it/s]

 87%|█████████████████████████████████████████████████████        | 835/960 [02:19<00:20,  6.07it/s]

 87%|█████████████████████████████████████████████████████        | 836/960 [02:19<00:20,  6.08it/s]

 87%|█████████████████████████████████████████████████████▏       | 837/960 [02:19<00:20,  6.03it/s]

 87%|█████████████████████████████████████████████████████▏       | 838/960 [02:19<00:20,  5.97it/s]

 87%|█████████████████████████████████████████████████████▎       | 839/960 [02:19<00:20,  5.91it/s]

 88%|█████████████████████████████████████████████████████▍       | 840/960 [02:20<00:20,  5.84it/s]

 88%|█████████████████████████████████████████████████████▍       | 841/960 [02:20<00:20,  5.79it/s]

 88%|█████████████████████████████████████████████████████▌       | 842/960 [02:20<00:20,  5.64it/s]

 88%|█████████████████████████████████████████████████████▌       | 843/960 [02:20<00:20,  5.57it/s]

 88%|█████████████████████████████████████████████████████▋       | 844/960 [02:20<00:20,  5.57it/s]

 88%|█████████████████████████████████████████████████████▋       | 845/960 [02:21<00:20,  5.49it/s]

 88%|█████████████████████████████████████████████████████▊       | 846/960 [02:21<00:20,  5.66it/s]

 88%|█████████████████████████████████████████████████████▊       | 847/960 [02:21<00:19,  5.77it/s]

 88%|█████████████████████████████████████████████████████▉       | 848/960 [02:21<00:19,  5.86it/s]

 88%|█████████████████████████████████████████████████████▉       | 849/960 [02:21<00:18,  6.02it/s]

 89%|██████████████████████████████████████████████████████       | 850/960 [02:21<00:17,  6.15it/s]

 89%|██████████████████████████████████████████████████████       | 851/960 [02:21<00:17,  6.23it/s]

 89%|██████████████████████████████████████████████████████▏      | 852/960 [02:22<00:17,  6.25it/s]

 89%|██████████████████████████████████████████████████████▏      | 853/960 [02:22<00:17,  6.25it/s]

 89%|██████████████████████████████████████████████████████▎      | 854/960 [02:22<00:17,  6.18it/s]

 89%|██████████████████████████████████████████████████████▎      | 855/960 [02:22<00:17,  6.15it/s]

 89%|██████████████████████████████████████████████████████▍      | 856/960 [02:22<00:16,  6.12it/s]

 89%|██████████████████████████████████████████████████████▍      | 857/960 [02:22<00:17,  6.00it/s]

 89%|██████████████████████████████████████████████████████▌      | 858/960 [02:23<00:16,  6.00it/s]

 89%|██████████████████████████████████████████████████████▌      | 859/960 [02:23<00:16,  5.95it/s]

 90%|██████████████████████████████████████████████████████▋      | 860/960 [02:23<00:17,  5.78it/s]

 90%|██████████████████████████████████████████████████████▋      | 861/960 [02:23<00:17,  5.74it/s]

 90%|██████████████████████████████████████████████████████▊      | 862/960 [02:23<00:17,  5.71it/s]

 90%|██████████████████████████████████████████████████████▊      | 863/960 [02:24<00:16,  5.83it/s]

 90%|██████████████████████████████████████████████████████▉      | 864/960 [02:24<00:16,  5.93it/s]

 90%|██████████████████████████████████████████████████████▉      | 865/960 [02:24<00:15,  6.08it/s]

 90%|███████████████████████████████████████████████████████      | 866/960 [02:24<00:15,  6.20it/s]

 90%|███████████████████████████████████████████████████████      | 867/960 [02:24<00:14,  6.29it/s]

 90%|███████████████████████████████████████████████████████▏     | 868/960 [02:24<00:14,  6.37it/s]

 91%|███████████████████████████████████████████████████████▏     | 869/960 [02:24<00:14,  6.40it/s]

 91%|███████████████████████████████████████████████████████▎     | 870/960 [02:25<00:14,  6.38it/s]

 91%|███████████████████████████████████████████████████████▎     | 871/960 [02:25<00:13,  6.36it/s]

 91%|███████████████████████████████████████████████████████▍     | 872/960 [02:25<00:13,  6.34it/s]

 91%|███████████████████████████████████████████████████████▍     | 873/960 [02:25<00:13,  6.25it/s]

 91%|███████████████████████████████████████████████████████▌     | 874/960 [02:25<00:13,  6.21it/s]

 91%|███████████████████████████████████████████████████████▌     | 875/960 [02:25<00:13,  6.18it/s]

 91%|███████████████████████████████████████████████████████▋     | 876/960 [02:26<00:13,  6.07it/s]

 91%|███████████████████████████████████████████████████████▋     | 877/960 [02:26<00:13,  6.01it/s]

 91%|███████████████████████████████████████████████████████▊     | 878/960 [02:26<00:13,  5.92it/s]

 92%|███████████████████████████████████████████████████████▊     | 879/960 [02:26<00:13,  5.79it/s]

 92%|███████████████████████████████████████████████████████▉     | 880/960 [02:26<00:13,  5.78it/s]

 92%|███████████████████████████████████████████████████████▉     | 881/960 [02:26<00:13,  5.70it/s]

 92%|████████████████████████████████████████████████████████     | 882/960 [02:27<00:13,  5.83it/s]

 92%|████████████████████████████████████████████████████████     | 883/960 [02:27<00:13,  5.91it/s]

 92%|████████████████████████████████████████████████████████▏    | 884/960 [02:27<00:12,  6.05it/s]

 92%|████████████████████████████████████████████████████████▏    | 885/960 [02:27<00:12,  6.19it/s]

 92%|████████████████████████████████████████████████████████▎    | 886/960 [02:27<00:11,  6.28it/s]

 92%|████████████████████████████████████████████████████████▎    | 887/960 [02:27<00:11,  6.35it/s]

 92%|████████████████████████████████████████████████████████▍    | 888/960 [02:28<00:11,  6.36it/s]

 93%|████████████████████████████████████████████████████████▍    | 889/960 [02:28<00:11,  6.39it/s]

 93%|████████████████████████████████████████████████████████▌    | 890/960 [02:28<00:10,  6.37it/s]

 93%|████████████████████████████████████████████████████████▌    | 891/960 [02:28<00:10,  6.35it/s]

 93%|████████████████████████████████████████████████████████▋    | 892/960 [02:28<00:10,  6.29it/s]

 93%|████████████████████████████████████████████████████████▋    | 893/960 [02:28<00:10,  6.23it/s]

 93%|████████████████████████████████████████████████████████▊    | 894/960 [02:29<00:10,  6.21it/s]

 93%|████████████████████████████████████████████████████████▊    | 895/960 [02:29<00:10,  6.06it/s]

 93%|████████████████████████████████████████████████████████▉    | 896/960 [02:29<00:10,  6.02it/s]

 93%|████████████████████████████████████████████████████████▉    | 897/960 [02:29<00:10,  5.92it/s]

 94%|█████████████████████████████████████████████████████████    | 898/960 [02:29<00:10,  5.85it/s]

 94%|█████████████████████████████████████████████████████████    | 899/960 [02:29<00:10,  5.85it/s]

 94%|█████████████████████████████████████████████████████████▏   | 900/960 [02:30<00:10,  5.72it/s]

 94%|█████████████████████████████████████████████████████████▎   | 901/960 [02:30<00:10,  5.72it/s]

 94%|█████████████████████████████████████████████████████████▎   | 902/960 [02:30<00:09,  5.85it/s]

 94%|█████████████████████████████████████████████████████████▍   | 903/960 [02:30<00:09,  6.03it/s]

 94%|█████████████████████████████████████████████████████████▍   | 904/960 [02:30<00:09,  6.08it/s]

 94%|█████████████████████████████████████████████████████████▌   | 905/960 [02:30<00:08,  6.21it/s]

 94%|█████████████████████████████████████████████████████████▌   | 906/960 [02:31<00:08,  6.30it/s]

 94%|█████████████████████████████████████████████████████████▋   | 907/960 [02:31<00:08,  6.27it/s]

 95%|█████████████████████████████████████████████████████████▋   | 908/960 [02:31<00:08,  6.32it/s]

 95%|█████████████████████████████████████████████████████████▊   | 909/960 [02:31<00:08,  6.32it/s]

 95%|█████████████████████████████████████████████████████████▊   | 910/960 [02:31<00:07,  6.33it/s]

 95%|█████████████████████████████████████████████████████████▉   | 911/960 [02:31<00:07,  6.26it/s]

 95%|█████████████████████████████████████████████████████████▉   | 912/960 [02:31<00:07,  6.22it/s]

 95%|██████████████████████████████████████████████████████████   | 913/960 [02:32<00:07,  6.19it/s]

 95%|██████████████████████████████████████████████████████████   | 914/960 [02:32<00:07,  6.16it/s]

 95%|██████████████████████████████████████████████████████████▏  | 915/960 [02:32<00:07,  6.13it/s]

 95%|██████████████████████████████████████████████████████████▏  | 916/960 [02:32<00:07,  6.03it/s]

 96%|██████████████████████████████████████████████████████████▎  | 917/960 [02:32<00:07,  5.88it/s]

 96%|██████████████████████████████████████████████████████████▎  | 918/960 [02:33<00:07,  5.85it/s]

 96%|██████████████████████████████████████████████████████████▍  | 919/960 [02:33<00:07,  5.78it/s]

 96%|██████████████████████████████████████████████████████████▍  | 920/960 [02:33<00:06,  5.77it/s]

 96%|██████████████████████████████████████████████████████████▌  | 921/960 [02:33<00:06,  5.79it/s]

 96%|██████████████████████████████████████████████████████████▌  | 922/960 [02:33<00:06,  5.88it/s]

 96%|██████████████████████████████████████████████████████████▋  | 923/960 [02:33<00:06,  5.83it/s]

 96%|██████████████████████████████████████████████████████████▋  | 924/960 [02:34<00:06,  5.90it/s]

 96%|██████████████████████████████████████████████████████████▊  | 925/960 [02:34<00:05,  5.99it/s]

 96%|██████████████████████████████████████████████████████████▊  | 926/960 [02:34<00:05,  6.10it/s]

 97%|██████████████████████████████████████████████████████████▉  | 927/960 [02:34<00:05,  6.20it/s]

 97%|██████████████████████████████████████████████████████████▉  | 928/960 [02:34<00:05,  6.21it/s]

 97%|███████████████████████████████████████████████████████████  | 929/960 [02:34<00:04,  6.25it/s]

 97%|███████████████████████████████████████████████████████████  | 930/960 [02:34<00:04,  6.19it/s]

 97%|███████████████████████████████████████████████████████████▏ | 931/960 [02:35<00:04,  6.14it/s]

 97%|███████████████████████████████████████████████████████████▏ | 932/960 [02:35<00:04,  6.12it/s]

 97%|███████████████████████████████████████████████████████████▎ | 933/960 [02:35<00:04,  5.96it/s]

 97%|███████████████████████████████████████████████████████████▎ | 934/960 [02:35<00:04,  5.84it/s]

 97%|███████████████████████████████████████████████████████████▍ | 935/960 [02:35<00:04,  5.82it/s]

 98%|███████████████████████████████████████████████████████████▍ | 936/960 [02:36<00:04,  5.80it/s]

 98%|███████████████████████████████████████████████████████████▌ | 937/960 [02:36<00:03,  5.78it/s]

 98%|███████████████████████████████████████████████████████████▌ | 938/960 [02:36<00:03,  5.74it/s]

 98%|███████████████████████████████████████████████████████████▋ | 939/960 [02:36<00:03,  5.72it/s]

 98%|███████████████████████████████████████████████████████████▋ | 940/960 [02:36<00:03,  5.84it/s]

 98%|███████████████████████████████████████████████████████████▊ | 941/960 [02:36<00:03,  5.94it/s]

 98%|███████████████████████████████████████████████████████████▊ | 942/960 [02:37<00:03,  5.95it/s]

 98%|███████████████████████████████████████████████████████████▉ | 943/960 [02:37<00:02,  6.09it/s]

 98%|███████████████████████████████████████████████████████████▉ | 944/960 [02:37<00:02,  6.12it/s]

 98%|████████████████████████████████████████████████████████████ | 945/960 [02:37<00:02,  6.11it/s]

 99%|████████████████████████████████████████████████████████████ | 946/960 [02:37<00:02,  6.11it/s]

 99%|████████████████████████████████████████████████████████████▏| 947/960 [02:37<00:02,  6.09it/s]

 99%|████████████████████████████████████████████████████████████▏| 948/960 [02:38<00:01,  6.08it/s]

 99%|████████████████████████████████████████████████████████████▎| 949/960 [02:38<00:01,  6.07it/s]

 99%|████████████████████████████████████████████████████████████▎| 950/960 [02:38<00:01,  6.04it/s]

 99%|████████████████████████████████████████████████████████████▍| 951/960 [02:38<00:01,  6.00it/s]

 99%|████████████████████████████████████████████████████████████▍| 952/960 [02:38<00:01,  5.97it/s]

 99%|████████████████████████████████████████████████████████████▌| 953/960 [02:38<00:01,  5.92it/s]

 99%|████████████████████████████████████████████████████████████▌| 954/960 [02:39<00:01,  5.83it/s]

 99%|████████████████████████████████████████████████████████████▋| 955/960 [02:39<00:00,  5.71it/s]

100%|████████████████████████████████████████████████████████████▋| 956/960 [02:39<00:00,  5.69it/s]

100%|████████████████████████████████████████████████████████████▊| 957/960 [02:39<00:00,  5.75it/s]

100%|████████████████████████████████████████████████████████████▊| 958/960 [02:39<00:00,  5.79it/s]

100%|████████████████████████████████████████████████████████████▉| 959/960 [02:39<00:00,  5.82it/s]

100%|█████████████████████████████████████████████████████████████| 960/960 [02:40<00:00,  5.84it/s]

100%|█████████████████████████████████████████████████████████████| 960/960 [02:40<00:00,  6.00it/s]

'Skipped files: 0'

In [9]:
predictions = pd.concat(predictions, ignore_index=True)
display(predictions.shape)
display(predictions.head())

(657600, 8)

,trait,drug,score,true_class,method,n_top_genes,data,tissue
0,DOID:0050741,DB00215,103099.5,1,gene_based,-1.0,spredixcan-mashr-zscores-Adipose_Subcutaneous-...,Adipose_Subcutaneous
1,DOID:0050741,DB00704,355210.0,1,gene_based,-1.0,spredixcan-mashr-zscores-Adipose_Subcutaneous-...,Adipose_Subcutaneous
2,DOID:0050741,DB00822,388169.0,1,gene_based,-1.0,spredixcan-mashr-zscores-Adipose_Subcutaneous-...,Adipose_Subcutaneous
3,DOID:10283,DB00014,80190.0,1,gene_based,-1.0,spredixcan-mashr-zscores-Adipose_Subcutaneous-...,Adipose_Subcutaneous
4,DOID:10283,DB00175,232448.0,0,gene_based,-1.0,spredixcan-mashr-zscores-Adipose_Subcutaneous-...,Adipose_Subcutaneous

## Validation checks (enforces NB06–NB09 completeness, copied from 14_signif_test/00)

In [10]:
assert not predictions.isna().any().any()

_method_counts = predictions['method'].value_counts().reindex(EXPECTED_METHODS)
display(_method_counts)

N_PREDICTIONS = predictions[['drug', 'trait']].drop_duplicates().shape[0]
display(f'Unique drug-disease pairs: {N_PREDICTIONS}')

for method_name, thresholds in METHOD_THRESHOLDS.items():
    expected = N_TISSUES * len(thresholds) * N_PREDICTIONS
    actual = int(_method_counts.loc[method_name])
    assert actual == expected, (
        f'{method_name}: expected {expected}, got {actual} -- '
        f'{_METHOD_SOURCE_NB[method_name]} must be complete '
        f'({N_TISSUES} tissues x {len(thresholds)} thresholds)')

# Tissue count sanity: exactly 49 distinct tissues, identical across methods.
_n_tissues = predictions.groupby('method', observed=True)['tissue'].nunique()
display(_n_tissues)
assert (_n_tissues == N_TISSUES).all(), 'tissue coverage is not a constant 49 across methods'
display('OK: completeness asserts pass (49 tissues x 5 thresholds x 685 pairs per method).')

method
gene_based               164400
module_based_archs4      164400
module_based_gtex        164400
module_based_recount2    164400
Name: count, dtype: int64

'Unique drug-disease pairs: 685'

method
gene_based               48
module_based_archs4      48
module_based_gtex        48
module_based_recount2    48
Name: tissue, dtype: int64

'OK: completeness asserts pass (49 tissues x 5 thresholds x 685 pairs per method).'

# Aggregate to per-tissue scores (mean over thresholds — **no max**)

Average ranks across the 5 `n_top_genes` thresholds (per trait, drug, method, tissue). This is
**step 1** of `14_signif_test/00`; we deliberately **stop before** the `groupby([trait, drug,
method]).max()` over tissues. The result keeps the tissue axis so each tissue can be scored
independently.

In [11]:
def _reduce_mean(x):
    return pd.Series({
        'score': x['score'].mean(),
        'true_class': x['true_class'].unique()[0],
    })


per_tissue_scores = (
    predictions
    .groupby(['trait', 'drug', 'method', 'tissue'], observed=True)
    .apply(_reduce_mean, include_groups=False)
    .dropna()
    .sort_index()
    .reset_index()
)
per_tissue_scores['method'] = pd.Categorical(
    per_tissue_scores['method'], categories=METHOD_ORDER, ordered=True)
display(per_tissue_scores.shape)
display(per_tissue_scores.head())

# 685 pairs x 4 methods x 49 tissues.
assert per_tissue_scores.shape[0] == len(EXPECTED_METHODS) * N_PREDICTIONS * N_TISSUES
assert per_tissue_scores.dropna().shape == per_tissue_scores.shape

(131520, 6)

,trait,drug,method,tissue,score,true_class
0,DOID:0050741,DB00215,gene_based,Adipose_Subcutaneous,52786.3,1.0
1,DOID:0050741,DB00215,gene_based,Adipose_Visceral_Omentum,73871.9,1.0
2,DOID:0050741,DB00215,gene_based,Adrenal_Gland,165504.3,1.0
3,DOID:0050741,DB00215,gene_based,Artery_Aorta,83904.3,1.0
4,DOID:0050741,DB00215,gene_based,Artery_Coronary,161434.9,1.0

In [12]:
out_scores = OUTPUT_DIR / 'per_tissue_scores.pkl'
per_tissue_scores.to_pickle(out_scores)
display(out_scores)

PosixPath('/home/msubirana/Documents/pivlab/clamp-analyses/output/03_model_biology/00_archs4/02_drug_disease_associations/15_tissue_agg_test/per_tissue_scores.pkl')

# Per-tissue metrics

For each `(method, tissue)` group (the 685 pairs scored in that single tissue) compute AUROC, AUPRC,
and `auprc_log2_enrich = log2(AUPRC / base_rate)`. The 685-pair label split is **constant across
tissues** (every tissue scores the identical pair universe), so both classes are always present and
every per-tissue metric is defined — no eligibility filtering is needed (unlike `per_disease_test`,
where the *disease* node varied).

In [13]:
def _tissue_metrics(g):
    y = g['true_class'].values.astype(int)
    s = g['score'].values
    n_total = len(y)
    n_pos = int(y.sum())
    n_neg = n_total - n_pos
    base_rate = n_pos / n_total
    auroc = roc_auc_score(y, s)
    auprc = average_precision_score(y, s)
    auprc_log2_enrich = float(np.log2(auprc / base_rate))
    return pd.Series({
        'n_pos': n_pos,
        'n_neg': n_neg,
        'n_total': n_total,
        'base_rate': base_rate,
        'auroc': auroc,
        'auprc': auprc,
        'auprc_log2_enrich': auprc_log2_enrich,
    })


per_tissue = (
    per_tissue_scores
    .groupby(['method', 'tissue'], observed=True)
    .apply(_tissue_metrics, include_groups=False)
    .reset_index()
)
per_tissue['method'] = pd.Categorical(per_tissue['method'], categories=METHOD_ORDER, ordered=True)
for c in ['n_pos', 'n_neg', 'n_total']:
    per_tissue[c] = per_tissue[c].astype(int)
for c in ['base_rate', 'auroc', 'auprc', 'auprc_log2_enrich']:
    per_tissue[c] = per_tissue[c].astype(float)
per_tissue = per_tissue.sort_values(['method', 'tissue']).reset_index(drop=True)

display(per_tissue.shape)
display(per_tissue.head())

# 4 methods x 49 tissues, no NaNs, constant label split across tissues.
assert per_tissue.shape[0] == len(METHOD_ORDER) * N_TISSUES
assert not per_tissue.isna().any().any()
assert per_tissue['n_pos'].nunique() == 1 and per_tissue['n_neg'].nunique() == 1, (
    'label split is not constant across tissues')
display(f"Constant per-tissue label split: {per_tissue['n_pos'].iloc[0]} pos / "
        f"{per_tissue['n_neg'].iloc[0]} neg (base_rate={per_tissue['base_rate'].iloc[0]:.4f})")

(192, 9)

,method,tissue,n_pos,n_neg,n_total,base_rate,auroc,auprc,auprc_log2_enrich
0,gene_based,Adipose_Subcutaneous,531,154,685,0.775182,0.523045,0.810025,0.063430
1,gene_based,Adipose_Visceral_Omentum,531,154,685,0.775182,0.530065,0.808614,0.060914
2,gene_based,Adrenal_Gland,531,154,685,0.775182,0.492657,0.807052,0.058125
3,gene_based,Artery_Aorta,531,154,685,0.775182,0.534626,0.819678,0.080521
4,gene_based,Artery_Coronary,531,154,685,0.775182,0.555403,0.823885,0.087907

'Constant per-tissue label split: 531 pos / 154 neg (base_rate=0.7752)'

In [14]:
# Macro-mean per-tissue AUROC by method (the aggregate-over-tissues estimand).
display(
    per_tissue.groupby('method', observed=True)[['auroc', 'auprc', 'auprc_log2_enrich']]
    .mean().reindex(METHOD_ORDER))

out_csv = OUTPUT_DIR / 'per_tissue_metrics.csv'
per_tissue.to_csv(out_csv, index=False)
display(out_csv)

                          auroc     auprc  auprc_log2_enrich
method
gene_based             0.541693  0.819677           0.080414
module_based_archs4    0.554799  0.824385           0.088534
module_based_gtex      0.526457  0.808315           0.060072
module_based_recount2  0.547066  0.820529           0.081873

PosixPath('/home/msubirana/Documents/pivlab/clamp-analyses/output/03_model_biology/00_archs4/02_drug_disease_associations/15_tissue_agg_test/per_tissue_metrics.csv')

# Max-aggregate reference (status quo)

Recompute the published **max-over-tissues** pooled AUROC/AUPRC per method directly from
`../14_signif_test/predictions_paired.pkl`. This is the number the per-tissue aggregate is contrasted
against in NB01 — it must reproduce 0.583 / 0.625 / 0.602 / 0.612 (gene / archs4 / gtex / recount2),
confirming our input frame matches `14_signif_test`.

In [15]:
paired = pd.read_pickle(PAIRED_PKL)
display(paired.shape)

_base_rate = paired.loc[paired['method'] == METHOD_ORDER[0], 'true_class'].mean()
rows = []
for m in METHOD_ORDER:
    g = paired[paired['method'] == m]
    y = g['true_class'].values.astype(int)
    s = g['score'].values
    auprc = average_precision_score(y, s)
    rows.append({
        'method': m,
        'auroc': roc_auc_score(y, s),
        'auprc': auprc,
        'auprc_log2_enrich': float(np.log2(auprc / (y.sum() / len(y)))),
    })
max_aggregate_reference = pd.DataFrame(rows)
display(max_aggregate_reference.round(4))

# Sanity tie-back to 14_signif_test / NB10.
_expected = {'gene_based': 0.583, 'module_based_archs4': 0.625,
             'module_based_gtex': 0.602, 'module_based_recount2': 0.612}
for _, r in max_aggregate_reference.iterrows():
    assert abs(r['auroc'] - _expected[r['method']]) < 0.005, (
        f"max-aggregate AUROC for {r['method']} = {r['auroc']:.4f}, "
        f"expected ~{_expected[r['method']]}")
display('OK: max-aggregate AUROC reproduces 14_signif_test (0.583 / 0.625 / 0.602 / 0.612).')

out_ref = OUTPUT_DIR / 'max_aggregate_reference.csv'
max_aggregate_reference.to_csv(out_ref, index=False)
display(out_ref)

(2740, 5)

                  method   auroc   auprc  auprc_log2_enrich
0             gene_based  0.5828  0.8446             0.1237
1    module_based_archs4  0.6240  0.8490             0.1312
2      module_based_gtex  0.5984  0.8377             0.1120
3  module_based_recount2  0.6118  0.8455             0.1253

'OK: max-aggregate AUROC reproduces 14_signif_test (0.583 / 0.625 / 0.602 / 0.612).'

PosixPath('/home/msubirana/Documents/pivlab/clamp-analyses/output/03_model_biology/00_archs4/02_drug_disease_associations/15_tissue_agg_test/max_aggregate_reference.csv')