💡 **Environment:** `clamp-analyses`

# Description

Builds the paired, identically-scored prediction frame for the cross-method AUROC/AUPRC significance test.

This notebook reads the raw drug-disease prediction HDF5 files from all four methods — **NB06** (single-gene baseline, `gene_based`), **NB07** (ARCHS4 module model, `module_based_archs4`), **NB08** (GTEx, `module_based_gtex`), and **NB09** (recount2, `module_based_recount2`) — and reproduces NB10's exact aggregation so every method is scored on an identical set of (drug, disease) pairs:

1. Per file: rank `score` over the full DOID distribution, then inner-merge with the gold standard.
2. Average ranks across the 5 `n_top_genes` thresholds (per trait, drug, method, tissue).
3. Take the max across the 49 tissues (per trait, drug, method).

Output: a paired frame `predictions_paired.pkl` (4 methods × 685 pairs) consumed by `01_paired_bootstrap_test.ipynb`.

> This notebook does **not** modify NB 06–13 or `libs/`. It **fails loud** if any of NB06–NB09 is missing or incomplete (NB08/NB09 must be run separately before the full grid can be aggregated).

# Modules loading

In [1]:
%load_ext autoreload
%autoreload 2

In [2]:
from pathlib import Path
from IPython.display import display

import numpy as np
import pandas as pd
from tqdm import tqdm

from pyprojroot import here

# Settings

In [3]:
N_TISSUES = 49

# Method -> canonical name (mirrors NB10). NB06-NB09 already write the canonical
# names ('gene_based', 'module_based_archs4', 'module_based_gtex',
# 'module_based_recount2'), so these display-name aliases are only a defensive
# fallback (the .get() default passes canonical names through).
# The bare 'Module-based' alias is intentionally omitted: it is ambiguous across
# datasets (archs4/gtex/recount2) and would misclassify GTEx/recount2 files as
# ARCHS4 in the full 4-method grid.
METHOD_RENAME = {
    'Gene-based':              'gene_based',
    'Module-based (ARCHS4)':   'module_based_archs4',
    'Module-based (GTEx)':     'module_based_gtex',
    'Module-based (recount2)': 'module_based_recount2',
}

# All four methods in the full grid (gene baseline + three module models).
METHOD_THRESHOLDS = {
    'gene_based':            [-1.0, 50.0, 100.0, 250.0, 500.0],
    'module_based_archs4':   [-1.0, 5.0, 10.0, 25.0, 50.0],
    'module_based_gtex':     [-1.0, 5.0, 10.0, 25.0, 50.0],
    'module_based_recount2': [-1.0, 5.0, 10.0, 25.0, 50.0],
}
EXPECTED_METHODS = tuple(METHOD_THRESHOLDS)

In [4]:
DATA_DIR = here('data/drug_disease_associations')
display(DATA_DIR)
assert DATA_DIR.exists()

# Raw prediction HDF5 dirs for the four methods (NB06, NB07, NB08, NB09).
_PRED_BASE = here(
    'output/03_model_biology/00_archs4/02_drug_disease_associations')
PREDICTIONS_DIRS = {
    'gene_based':
        _PRED_BASE / '06_prediction_single_gene_based' / 'lincs' / 'predictions' / 'dotprod_neg',
    'module_based_archs4':
        _PRED_BASE / '07_prediction_module_based_archs4' / 'lincs' / 'predictions' / 'dotprod_neg',
    'module_based_gtex':
        _PRED_BASE / '08_prediction_module_based_gtex' / 'lincs' / 'predictions' / 'dotprod_neg',
    'module_based_recount2':
        _PRED_BASE / '09_prediction_module_based_recount2' / 'lincs' / 'predictions' / 'dotprod_neg',
}
# Map each method to the prediction notebook that produces it (for fail-loud msgs).
_METHOD_SOURCE_NB = {
    'gene_based':            'NB06 (06_prediction_single_gene_based)',
    'module_based_archs4':   'NB07 (07_prediction_module_based_archs4)',
    'module_based_gtex':     'NB08 (08_prediction_module_based_gtex)',
    'module_based_recount2': 'NB09 (09_prediction_module_based_recount2)',
}
for name, d in PREDICTIONS_DIRS.items():
    display((name, d))
    # Fail loud (do not silently score on partial data): the full 4-method grid
    # needs all of NB06-NB09 on disk. NB08/NB09 must be run separately first.
    assert d.exists(), (
        f'{name} predictions missing -- run {_METHOD_SOURCE_NB[name]} first: {d}')

OUTPUT_DIR = here(
    'output/03_model_biology/00_archs4/02_drug_disease_associations/14_signif_test')
OUTPUT_DIR.mkdir(parents=True, exist_ok=True)
display(OUTPUT_DIR)

PosixPath('/home/msubirana/Documents/pivlab/clamp-analyses/data/drug_disease_associations')

('gene_based',
 PosixPath('/home/msubirana/Documents/pivlab/clamp-analyses/output/03_model_biology/00_archs4/02_drug_disease_associations/06_prediction_single_gene_based/lincs/predictions/dotprod_neg'))

('module_based_archs4',
 PosixPath('/home/msubirana/Documents/pivlab/clamp-analyses/output/03_model_biology/00_archs4/02_drug_disease_associations/07_prediction_module_based_archs4/lincs/predictions/dotprod_neg'))

('module_based_gtex',
 PosixPath('/home/msubirana/Documents/pivlab/clamp-analyses/output/03_model_biology/00_archs4/02_drug_disease_associations/08_prediction_module_based_gtex/lincs/predictions/dotprod_neg'))

('module_based_recount2',
 PosixPath('/home/msubirana/Documents/pivlab/clamp-analyses/output/03_model_biology/00_archs4/02_drug_disease_associations/09_prediction_module_based_recount2/lincs/predictions/dotprod_neg'))

PosixPath('/home/msubirana/Documents/pivlab/clamp-analyses/output/03_model_biology/00_archs4/02_drug_disease_associations/14_signif_test')

# Load PharmacotherapyDB gold standard

In [5]:
gold_standard = pd.read_pickle(DATA_DIR / 'gold_standard.pkl')
display(gold_standard.shape)
display(gold_standard.head())
display(gold_standard['true_class'].value_counts())

(998, 3)

        trait     drug  true_class
0  DOID:10652  DB00843           1
1  DOID:10652  DB00674           1
2  DOID:10652  DB01043           1
3  DOID:10652  DB00989           1
4  DOID:10652  DB00810           0

true_class
1    755
0    243
Name: count, dtype: int64

# Helpers (copied verbatim from NB10)

In [6]:
def _get_tissue(data_value):
    """Extract tissue name from the metadata 'data' field."""
    prefix = 'spredixcan-mashr-zscores-'
    assert data_value.startswith(prefix), data_value
    tissue = data_value[len(prefix):]
    for suffix in (
        '-projection-archs4',
        '-projection-gtex',
        '-projection-recount2',
        '-projection',
        '-data',
    ):
        if tissue.endswith(suffix):
            return tissue[:-len(suffix)]
    raise ValueError(f'Cannot extract tissue from metadata data value: {data_value}')

# Load drug-disease predictions

In [7]:
current_prediction_files = []
for d in PREDICTIONS_DIRS.values():
    current_prediction_files.extend(sorted(d.glob('*.h5')))
current_prediction_files.sort()
display(len(current_prediction_files))

980

In [8]:
# Load all prediction files, rank scores, merge with gold standard (NB10 logic).
predictions = []
skipped_files = []

for f in tqdm(current_prediction_files, ncols=100):
    metadata = pd.read_hdf(f, key='/metadata')
    method_name = METHOD_RENAME.get(
        metadata['method'].values[0], metadata['method'].values[0])
    if method_name not in METHOD_THRESHOLDS:
        skipped_files.append((f.name, method_name))
        continue

    # Rank within the full DOID distribution, then keep gold-standard pairs.
    prediction_data = pd.read_hdf(f, key='/prediction')
    prediction_data['score'] = prediction_data['score'].rank()
    prediction_data = pd.merge(
        prediction_data, gold_standard, on=['trait', 'drug'], how='inner')
    prediction_data['trait'] = prediction_data['trait'].astype('category')
    prediction_data['drug'] = prediction_data['drug'].astype('category')

    prediction_data = prediction_data.assign(method=method_name)
    prediction_data['method'] = pd.Categorical(
        prediction_data['method'], categories=EXPECTED_METHODS, ordered=True)
    prediction_data = prediction_data.assign(
        n_top_genes=metadata['n_top_genes'].values[0])

    data_value = metadata['data'].values[0]
    prediction_data = prediction_data.assign(data=data_value)
    prediction_data['data'] = prediction_data['data'].astype('category')
    prediction_data = prediction_data.assign(tissue=_get_tissue(data_value))

    predictions.append(prediction_data)

display(f'Skipped files: {len(skipped_files)}')
if skipped_files:
    display(skipped_files[:10])

  0%|                                                                       | 0/980 [00:00<?, ?it/s]

  0%|                                                               | 1/980 [00:00<03:30,  4.65it/s]

  0%|▏                                                              | 2/980 [00:00<03:13,  5.05it/s]

  0%|▏                                                              | 3/980 [00:00<03:09,  5.15it/s]

  0%|▎                                                              | 4/980 [00:00<03:02,  5.36it/s]

  1%|▎                                                              | 5/980 [00:00<02:56,  5.52it/s]

  1%|▍                                                              | 6/980 [00:01<02:53,  5.62it/s]

  1%|▍                                                              | 7/980 [00:01<02:51,  5.68it/s]

  1%|▌                                                              | 8/980 [00:01<02:56,  5.51it/s]

  1%|▌                                                              | 9/980 [00:01<02:56,  5.51it/s]

  1%|▋                                                             | 10/980 [00:01<02:55,  5.52it/s]

  1%|▋                                                             | 11/980 [00:02<02:52,  5.62it/s]

  1%|▊                                                             | 12/980 [00:02<02:47,  5.78it/s]

  1%|▊                                                             | 13/980 [00:02<02:47,  5.76it/s]

  1%|▉                                                             | 14/980 [00:02<02:52,  5.60it/s]

  2%|▉                                                             | 15/980 [00:02<02:53,  5.57it/s]

  2%|█                                                             | 16/980 [00:02<02:53,  5.55it/s]

  2%|█                                                             | 17/980 [00:03<02:54,  5.53it/s]

  2%|█▏                                                            | 18/980 [00:03<02:53,  5.56it/s]

  2%|█▏                                                            | 19/980 [00:03<02:48,  5.69it/s]

  2%|█▎                                                            | 20/980 [00:03<02:47,  5.75it/s]

  2%|█▎                                                            | 21/980 [00:03<02:49,  5.67it/s]

  2%|█▍                                                            | 22/980 [00:03<02:49,  5.66it/s]

  2%|█▍                                                            | 23/980 [00:04<02:49,  5.66it/s]

  2%|█▌                                                            | 24/980 [00:04<02:48,  5.68it/s]

  3%|█▌                                                            | 25/980 [00:04<02:45,  5.76it/s]

  3%|█▋                                                            | 26/980 [00:04<02:44,  5.79it/s]

  3%|█▋                                                            | 27/980 [00:04<02:43,  5.83it/s]

  3%|█▊                                                            | 28/980 [00:04<02:39,  5.98it/s]

  3%|█▊                                                            | 29/980 [00:05<02:36,  6.07it/s]

  3%|█▉                                                            | 30/980 [00:05<02:39,  5.96it/s]

  3%|█▉                                                            | 31/980 [00:05<02:37,  6.01it/s]

  3%|██                                                            | 32/980 [00:05<02:40,  5.90it/s]

  3%|██                                                            | 33/980 [00:05<02:42,  5.82it/s]

  3%|██▏                                                           | 34/980 [00:05<02:42,  5.81it/s]

  4%|██▏                                                           | 35/980 [00:06<02:39,  5.91it/s]

  4%|██▎                                                           | 36/980 [00:06<02:41,  5.83it/s]

  4%|██▎                                                           | 37/980 [00:06<02:43,  5.75it/s]

  4%|██▍                                                           | 38/980 [00:06<02:45,  5.70it/s]

  4%|██▍                                                           | 39/980 [00:06<02:46,  5.66it/s]

  4%|██▌                                                           | 40/980 [00:07<02:54,  5.39it/s]

  4%|██▌                                                           | 41/980 [00:07<02:52,  5.45it/s]

  4%|██▋                                                           | 42/980 [00:07<02:44,  5.69it/s]

  4%|██▋                                                           | 43/980 [00:07<02:48,  5.56it/s]

  4%|██▊                                                           | 44/980 [00:07<02:43,  5.72it/s]

  5%|██▊                                                           | 45/980 [00:07<02:40,  5.83it/s]

  5%|██▉                                                           | 46/980 [00:08<02:37,  5.93it/s]

  5%|██▉                                                           | 47/980 [00:08<02:36,  5.96it/s]

  5%|███                                                           | 48/980 [00:08<02:35,  5.99it/s]

  5%|███                                                           | 49/980 [00:08<02:34,  6.03it/s]

  5%|███▏                                                          | 50/980 [00:08<02:35,  5.98it/s]

  5%|███▏                                                          | 51/980 [00:08<02:35,  5.99it/s]

  5%|███▎                                                          | 52/980 [00:09<02:35,  5.98it/s]

  5%|███▎                                                          | 53/980 [00:09<02:32,  6.09it/s]

  6%|███▍                                                          | 54/980 [00:09<02:30,  6.14it/s]

  6%|███▍                                                          | 55/980 [00:09<02:29,  6.20it/s]

  6%|███▌                                                          | 56/980 [00:09<02:29,  6.20it/s]

  6%|███▌                                                          | 57/980 [00:09<02:28,  6.20it/s]

  6%|███▋                                                          | 58/980 [00:10<02:28,  6.19it/s]

  6%|███▋                                                          | 59/980 [00:10<02:27,  6.23it/s]

  6%|███▊                                                          | 60/980 [00:10<02:25,  6.31it/s]

  6%|███▊                                                          | 61/980 [00:10<02:25,  6.33it/s]

  6%|███▉                                                          | 62/980 [00:10<02:24,  6.35it/s]

  6%|███▉                                                          | 63/980 [00:10<02:24,  6.33it/s]

  7%|████                                                          | 64/980 [00:10<02:24,  6.33it/s]

  7%|████                                                          | 65/980 [00:11<02:25,  6.31it/s]

  7%|████▏                                                         | 66/980 [00:11<02:26,  6.25it/s]

  7%|████▏                                                         | 67/980 [00:11<02:26,  6.22it/s]

  7%|████▎                                                         | 68/980 [00:11<02:27,  6.20it/s]

  7%|████▎                                                         | 69/980 [00:11<02:27,  6.19it/s]

  7%|████▍                                                         | 70/980 [00:11<02:28,  6.14it/s]

  7%|████▍                                                         | 71/980 [00:12<02:27,  6.16it/s]

  7%|████▌                                                         | 72/980 [00:12<02:26,  6.18it/s]

  7%|████▌                                                         | 73/980 [00:12<02:33,  5.90it/s]

  8%|████▋                                                         | 74/980 [00:12<02:38,  5.71it/s]

  8%|████▋                                                         | 75/980 [00:12<02:43,  5.55it/s]

  8%|████▊                                                         | 76/980 [00:13<02:48,  5.36it/s]

  8%|████▊                                                         | 77/980 [00:13<02:47,  5.40it/s]

  8%|████▉                                                         | 78/980 [00:13<02:41,  5.60it/s]

  8%|████▉                                                         | 79/980 [00:13<02:34,  5.82it/s]

  8%|█████                                                         | 80/980 [00:13<02:30,  5.98it/s]

  8%|█████                                                         | 81/980 [00:13<02:28,  6.06it/s]

  8%|█████▏                                                        | 82/980 [00:14<02:27,  6.09it/s]

  8%|█████▎                                                        | 83/980 [00:14<02:26,  6.11it/s]

  9%|█████▎                                                        | 84/980 [00:14<02:25,  6.14it/s]

  9%|█████▍                                                        | 85/980 [00:14<02:28,  6.04it/s]

  9%|█████▍                                                        | 86/980 [00:14<02:30,  5.95it/s]

  9%|█████▌                                                        | 87/980 [00:14<02:33,  5.81it/s]

  9%|█████▌                                                        | 88/980 [00:15<02:33,  5.81it/s]

  9%|█████▋                                                        | 89/980 [00:15<02:29,  5.96it/s]

  9%|█████▋                                                        | 90/980 [00:15<02:28,  6.01it/s]

  9%|█████▊                                                        | 91/980 [00:15<02:27,  6.02it/s]

  9%|█████▊                                                        | 92/980 [00:15<02:28,  5.97it/s]

  9%|█████▉                                                        | 93/980 [00:15<02:32,  5.82it/s]

 10%|█████▉                                                        | 94/980 [00:16<02:32,  5.81it/s]

 10%|██████                                                        | 95/980 [00:16<02:30,  5.87it/s]

 10%|██████                                                        | 96/980 [00:16<02:29,  5.91it/s]

 10%|██████▏                                                       | 97/980 [00:16<02:27,  5.99it/s]

 10%|██████▏                                                       | 98/980 [00:16<02:25,  6.05it/s]

 10%|██████▎                                                       | 99/980 [00:16<02:25,  6.06it/s]

 10%|██████▏                                                      | 100/980 [00:17<02:25,  6.03it/s]

 10%|██████▎                                                      | 101/980 [00:17<02:28,  5.94it/s]

 10%|██████▎                                                      | 102/980 [00:17<02:27,  5.94it/s]

 11%|██████▍                                                      | 103/980 [00:17<02:28,  5.92it/s]

 11%|██████▍                                                      | 104/980 [00:17<02:29,  5.88it/s]

 11%|██████▌                                                      | 105/980 [00:17<02:27,  5.93it/s]

 11%|██████▌                                                      | 106/980 [00:18<02:30,  5.81it/s]

 11%|██████▋                                                      | 107/980 [00:18<02:29,  5.86it/s]

 11%|██████▋                                                      | 108/980 [00:18<02:27,  5.91it/s]

 11%|██████▊                                                      | 109/980 [00:18<02:25,  5.98it/s]

 11%|██████▊                                                      | 110/980 [00:18<02:24,  6.04it/s]

 11%|██████▉                                                      | 111/980 [00:18<02:22,  6.08it/s]

 11%|██████▉                                                      | 112/980 [00:19<02:22,  6.08it/s]

 12%|███████                                                      | 113/980 [00:19<02:22,  6.08it/s]

 12%|███████                                                      | 114/980 [00:19<02:23,  6.04it/s]

 12%|███████▏                                                     | 115/980 [00:19<02:23,  6.01it/s]

 12%|███████▏                                                     | 116/980 [00:19<02:23,  6.00it/s]

 12%|███████▎                                                     | 117/980 [00:19<02:22,  6.04it/s]

 12%|███████▎                                                     | 118/980 [00:20<02:22,  6.06it/s]

 12%|███████▍                                                     | 119/980 [00:20<02:21,  6.07it/s]

 12%|███████▍                                                     | 120/980 [00:20<02:21,  6.07it/s]

 12%|███████▌                                                     | 121/980 [00:20<02:22,  6.05it/s]

 12%|███████▌                                                     | 122/980 [00:20<02:21,  6.05it/s]

 13%|███████▋                                                     | 123/980 [00:20<02:24,  5.94it/s]

 13%|███████▋                                                     | 124/980 [00:21<02:24,  5.94it/s]

 13%|███████▊                                                     | 125/980 [00:21<02:22,  6.00it/s]

 13%|███████▊                                                     | 126/980 [00:21<02:20,  6.06it/s]

 13%|███████▉                                                     | 127/980 [00:21<02:20,  6.07it/s]

 13%|███████▉                                                     | 128/980 [00:21<02:20,  6.07it/s]

 13%|████████                                                     | 129/980 [00:21<02:20,  6.04it/s]

 13%|████████                                                     | 130/980 [00:22<02:21,  5.99it/s]

 13%|████████▏                                                    | 131/980 [00:22<02:22,  5.98it/s]

 13%|████████▏                                                    | 132/980 [00:22<02:22,  5.93it/s]

 14%|████████▎                                                    | 133/980 [00:22<02:23,  5.91it/s]

 14%|████████▎                                                    | 134/980 [00:22<02:25,  5.81it/s]

 14%|████████▍                                                    | 135/980 [00:22<02:23,  5.89it/s]

 14%|████████▍                                                    | 136/980 [00:23<02:26,  5.75it/s]

 14%|████████▌                                                    | 137/980 [00:23<02:24,  5.83it/s]

 14%|████████▌                                                    | 138/980 [00:23<02:24,  5.81it/s]

 14%|████████▋                                                    | 139/980 [00:23<02:23,  5.86it/s]

 14%|████████▋                                                    | 140/980 [00:23<02:24,  5.81it/s]

 14%|████████▊                                                    | 141/980 [00:23<02:21,  5.91it/s]

 14%|████████▊                                                    | 142/980 [00:24<02:20,  5.96it/s]

 15%|████████▉                                                    | 143/980 [00:24<02:20,  5.95it/s]

 15%|████████▉                                                    | 144/980 [00:24<02:19,  6.01it/s]

 15%|█████████                                                    | 145/980 [00:24<02:19,  6.00it/s]

 15%|█████████                                                    | 146/980 [00:24<02:19,  5.99it/s]

 15%|█████████▏                                                   | 147/980 [00:24<02:21,  5.90it/s]

 15%|█████████▏                                                   | 148/980 [00:25<02:20,  5.92it/s]

 15%|█████████▎                                                   | 149/980 [00:25<02:21,  5.87it/s]

 15%|█████████▎                                                   | 150/980 [00:25<02:20,  5.89it/s]

 15%|█████████▍                                                   | 151/980 [00:25<02:22,  5.80it/s]

 16%|█████████▍                                                   | 152/980 [00:25<02:21,  5.85it/s]

 16%|█████████▌                                                   | 153/980 [00:25<02:21,  5.84it/s]

 16%|█████████▌                                                   | 154/980 [00:26<02:26,  5.64it/s]

 16%|█████████▋                                                   | 155/980 [00:26<02:26,  5.62it/s]

 16%|█████████▋                                                   | 156/980 [00:26<02:24,  5.70it/s]

 16%|█████████▊                                                   | 157/980 [00:26<02:22,  5.76it/s]

 16%|█████████▊                                                   | 158/980 [00:26<02:19,  5.89it/s]

 16%|█████████▉                                                   | 159/980 [00:27<02:17,  5.98it/s]

 16%|█████████▉                                                   | 160/980 [00:27<02:15,  6.04it/s]

 16%|██████████                                                   | 161/980 [00:27<02:14,  6.09it/s]

 17%|██████████                                                   | 162/980 [00:27<02:14,  6.10it/s]

 17%|██████████▏                                                  | 163/980 [00:27<02:13,  6.12it/s]

 17%|██████████▏                                                  | 164/980 [00:27<02:13,  6.10it/s]

 17%|██████████▎                                                  | 165/980 [00:27<02:14,  6.07it/s]

 17%|██████████▎                                                  | 166/980 [00:28<02:13,  6.10it/s]

 17%|██████████▍                                                  | 167/980 [00:28<02:12,  6.13it/s]

 17%|██████████▍                                                  | 168/980 [00:28<02:13,  6.09it/s]

 17%|██████████▌                                                  | 169/980 [00:28<02:12,  6.12it/s]

 17%|██████████▌                                                  | 170/980 [00:28<02:10,  6.20it/s]

 17%|██████████▋                                                  | 171/980 [00:28<02:10,  6.20it/s]

 18%|██████████▋                                                  | 172/980 [00:29<02:09,  6.23it/s]

 18%|██████████▊                                                  | 173/980 [00:29<02:09,  6.24it/s]

 18%|██████████▊                                                  | 174/980 [00:29<02:08,  6.26it/s]

 18%|██████████▉                                                  | 175/980 [00:29<02:07,  6.30it/s]

 18%|██████████▉                                                  | 176/980 [00:29<02:09,  6.22it/s]

 18%|███████████                                                  | 177/980 [00:29<02:09,  6.19it/s]

 18%|███████████                                                  | 178/980 [00:30<02:09,  6.18it/s]

 18%|███████████▏                                                 | 179/980 [00:30<02:08,  6.25it/s]

 18%|███████████▏                                                 | 180/980 [00:30<02:07,  6.29it/s]

 18%|███████████▎                                                 | 181/980 [00:30<02:06,  6.31it/s]

 19%|███████████▎                                                 | 182/980 [00:30<02:06,  6.31it/s]

 19%|███████████▍                                                 | 183/980 [00:30<02:07,  6.27it/s]

 19%|███████████▍                                                 | 184/980 [00:31<02:07,  6.22it/s]

 19%|███████████▌                                                 | 185/980 [00:31<02:07,  6.25it/s]

 19%|███████████▌                                                 | 186/980 [00:31<02:07,  6.21it/s]

 19%|███████████▋                                                 | 187/980 [00:31<02:07,  6.24it/s]

 19%|███████████▋                                                 | 188/980 [00:31<02:07,  6.24it/s]

 19%|███████████▊                                                 | 189/980 [00:31<02:06,  6.27it/s]

 19%|███████████▊                                                 | 190/980 [00:31<02:05,  6.30it/s]

 19%|███████████▉                                                 | 191/980 [00:32<02:06,  6.25it/s]

 20%|███████████▉                                                 | 192/980 [00:32<02:06,  6.24it/s]

 20%|████████████                                                 | 193/980 [00:32<02:05,  6.26it/s]

 20%|████████████                                                 | 194/980 [00:32<02:05,  6.25it/s]

 20%|████████████▏                                                | 195/980 [00:32<02:04,  6.32it/s]

 20%|████████████▏                                                | 196/980 [00:32<02:03,  6.37it/s]

 20%|████████████▎                                                | 197/980 [00:33<02:02,  6.38it/s]

 20%|████████████▎                                                | 198/980 [00:33<02:03,  6.32it/s]

 20%|████████████▍                                                | 199/980 [00:33<02:03,  6.34it/s]

 20%|████████████▍                                                | 200/980 [00:33<02:03,  6.34it/s]

 21%|████████████▌                                                | 201/980 [00:33<02:03,  6.33it/s]

 21%|████████████▌                                                | 202/980 [00:33<02:04,  6.27it/s]

 21%|████████████▋                                                | 203/980 [00:34<02:03,  6.29it/s]

 21%|████████████▋                                                | 204/980 [00:34<02:03,  6.29it/s]

 21%|████████████▊                                                | 205/980 [00:34<02:02,  6.32it/s]

 21%|████████████▊                                                | 206/980 [00:34<02:02,  6.34it/s]

 21%|████████████▉                                                | 207/980 [00:34<02:02,  6.31it/s]

 21%|████████████▉                                                | 208/980 [00:34<02:01,  6.35it/s]

 21%|█████████████                                                | 209/980 [00:35<02:01,  6.33it/s]

 21%|█████████████                                                | 210/980 [00:35<02:01,  6.32it/s]

 22%|█████████████▏                                               | 211/980 [00:35<02:01,  6.32it/s]

 22%|█████████████▏                                               | 212/980 [00:35<02:01,  6.31it/s]

 22%|█████████████▎                                               | 213/980 [00:35<02:02,  6.28it/s]

 22%|█████████████▎                                               | 214/980 [00:35<02:00,  6.34it/s]

 22%|█████████████▍                                               | 215/980 [00:35<02:01,  6.31it/s]

 22%|█████████████▍                                               | 216/980 [00:36<02:01,  6.31it/s]

 22%|█████████████▌                                               | 217/980 [00:36<02:00,  6.33it/s]

 22%|█████████████▌                                               | 218/980 [00:36<01:59,  6.36it/s]

 22%|█████████████▋                                               | 219/980 [00:36<01:59,  6.36it/s]

 22%|█████████████▋                                               | 220/980 [00:36<01:59,  6.34it/s]

 23%|█████████████▊                                               | 221/980 [00:36<02:00,  6.30it/s]

 23%|█████████████▊                                               | 222/980 [00:37<02:01,  6.26it/s]

 23%|█████████████▉                                               | 223/980 [00:37<02:00,  6.27it/s]

 23%|█████████████▉                                               | 224/980 [00:37<01:59,  6.33it/s]

 23%|██████████████                                               | 225/980 [00:37<01:58,  6.35it/s]

 23%|██████████████                                               | 226/980 [00:37<01:58,  6.36it/s]

 23%|██████████████▏                                              | 227/980 [00:37<01:58,  6.36it/s]

 23%|██████████████▏                                              | 228/980 [00:38<01:58,  6.33it/s]

 23%|██████████████▎                                              | 229/980 [00:38<01:59,  6.29it/s]

 23%|██████████████▎                                              | 230/980 [00:38<01:59,  6.29it/s]

 24%|██████████████▍                                              | 231/980 [00:38<02:00,  6.23it/s]

 24%|██████████████▍                                              | 232/980 [00:38<01:58,  6.30it/s]

 24%|██████████████▌                                              | 233/980 [00:38<01:57,  6.38it/s]

 24%|██████████████▌                                              | 234/980 [00:38<01:56,  6.40it/s]

 24%|██████████████▋                                              | 235/980 [00:39<01:56,  6.41it/s]

 24%|██████████████▋                                              | 236/980 [00:39<01:57,  6.34it/s]

 24%|██████████████▊                                              | 237/980 [00:39<01:57,  6.34it/s]

 24%|██████████████▊                                              | 238/980 [00:39<01:58,  6.27it/s]

 24%|██████████████▉                                              | 239/980 [00:39<01:58,  6.27it/s]

 24%|██████████████▉                                              | 240/980 [00:39<02:03,  6.01it/s]

 25%|███████████████                                              | 241/980 [00:40<02:02,  6.04it/s]

 25%|███████████████                                              | 242/980 [00:40<02:00,  6.10it/s]

 25%|███████████████▏                                             | 243/980 [00:40<02:01,  6.06it/s]

 25%|███████████████▏                                             | 244/980 [00:40<02:00,  6.11it/s]

 25%|███████████████▎                                             | 245/980 [00:40<01:58,  6.19it/s]

 25%|███████████████▎                                             | 246/980 [00:40<02:03,  5.97it/s]

 25%|███████████████▎                                             | 247/980 [00:41<02:07,  5.75it/s]

 25%|███████████████▍                                             | 248/980 [00:41<02:09,  5.67it/s]

 25%|███████████████▍                                             | 249/980 [00:41<02:09,  5.66it/s]

 26%|███████████████▌                                             | 250/980 [00:41<02:09,  5.65it/s]

 26%|███████████████▌                                             | 251/980 [00:41<02:06,  5.77it/s]

 26%|███████████████▋                                             | 252/980 [00:41<02:06,  5.77it/s]

 26%|███████████████▋                                             | 253/980 [00:42<02:07,  5.69it/s]

 26%|███████████████▊                                             | 254/980 [00:42<02:08,  5.64it/s]

 26%|███████████████▊                                             | 255/980 [00:42<02:12,  5.48it/s]

 26%|███████████████▉                                             | 256/980 [00:42<02:13,  5.41it/s]

 26%|███████████████▉                                             | 257/980 [00:42<02:13,  5.42it/s]

 26%|████████████████                                             | 258/980 [00:43<02:13,  5.40it/s]

 26%|████████████████                                             | 259/980 [00:43<02:10,  5.52it/s]

 27%|████████████████▏                                            | 260/980 [00:43<02:11,  5.48it/s]

 27%|████████████████▏                                            | 261/980 [00:43<02:13,  5.40it/s]

 27%|████████████████▎                                            | 262/980 [00:43<02:13,  5.40it/s]

 27%|████████████████▎                                            | 263/980 [00:44<02:14,  5.33it/s]

 27%|████████████████▍                                            | 264/980 [00:44<02:14,  5.34it/s]

 27%|████████████████▍                                            | 265/980 [00:44<02:14,  5.31it/s]

 27%|████████████████▌                                            | 266/980 [00:44<02:13,  5.36it/s]

 27%|████████████████▌                                            | 267/980 [00:44<02:11,  5.43it/s]

 27%|████████████████▋                                            | 268/980 [00:44<02:09,  5.51it/s]

 27%|████████████████▋                                            | 269/980 [00:45<02:08,  5.51it/s]

 28%|████████████████▊                                            | 270/980 [00:45<02:10,  5.44it/s]

 28%|████████████████▊                                            | 271/980 [00:45<02:12,  5.35it/s]

 28%|████████████████▉                                            | 272/980 [00:45<02:23,  4.93it/s]

 28%|████████████████▉                                            | 273/980 [00:45<02:22,  4.95it/s]

 28%|█████████████████                                            | 274/980 [00:46<02:18,  5.08it/s]

 28%|█████████████████                                            | 275/980 [00:46<02:14,  5.25it/s]

 28%|█████████████████▏                                           | 276/980 [00:46<02:11,  5.35it/s]

 28%|█████████████████▏                                           | 277/980 [00:46<02:10,  5.40it/s]

 28%|█████████████████▎                                           | 278/980 [00:46<02:09,  5.44it/s]

 28%|█████████████████▎                                           | 279/980 [00:47<02:09,  5.43it/s]

 29%|█████████████████▍                                           | 280/980 [00:47<02:06,  5.53it/s]

 29%|█████████████████▍                                           | 281/980 [00:47<02:07,  5.48it/s]

 29%|█████████████████▌                                           | 282/980 [00:47<02:08,  5.44it/s]

 29%|█████████████████▌                                           | 283/980 [00:47<02:09,  5.39it/s]

 29%|█████████████████▋                                           | 284/980 [00:47<02:13,  5.22it/s]

 29%|█████████████████▋                                           | 285/980 [00:48<02:13,  5.19it/s]

 29%|█████████████████▊                                           | 286/980 [00:48<02:14,  5.17it/s]

 29%|█████████████████▊                                           | 287/980 [00:48<02:13,  5.20it/s]

 29%|█████████████████▉                                           | 288/980 [00:48<02:12,  5.22it/s]

 29%|█████████████████▉                                           | 289/980 [00:48<02:13,  5.17it/s]

 30%|██████████████████                                           | 290/980 [00:49<02:10,  5.30it/s]

 30%|██████████████████                                           | 291/980 [00:49<02:07,  5.42it/s]

 30%|██████████████████▏                                          | 292/980 [00:49<02:02,  5.61it/s]

 30%|██████████████████▏                                          | 293/980 [00:49<02:03,  5.54it/s]

 30%|██████████████████▎                                          | 294/980 [00:49<02:04,  5.49it/s]

 30%|██████████████████▎                                          | 295/980 [00:50<02:03,  5.53it/s]

 30%|██████████████████▍                                          | 296/980 [00:50<02:04,  5.49it/s]

 30%|██████████████████▍                                          | 297/980 [00:50<02:04,  5.48it/s]

 30%|██████████████████▌                                          | 298/980 [00:50<02:04,  5.46it/s]

 31%|██████████████████▌                                          | 299/980 [00:50<02:04,  5.46it/s]

 31%|██████████████████▋                                          | 300/980 [00:50<02:05,  5.42it/s]

 31%|██████████████████▋                                          | 301/980 [00:51<02:06,  5.37it/s]

 31%|██████████████████▊                                          | 302/980 [00:51<02:07,  5.33it/s]

 31%|██████████████████▊                                          | 303/980 [00:51<02:08,  5.28it/s]

 31%|██████████████████▉                                          | 304/980 [00:51<02:06,  5.33it/s]

 31%|██████████████████▉                                          | 305/980 [00:51<02:06,  5.34it/s]

 31%|███████████████████                                          | 306/980 [00:52<02:04,  5.40it/s]

 31%|███████████████████                                          | 307/980 [00:52<02:02,  5.51it/s]

 31%|███████████████████▏                                         | 308/980 [00:52<02:01,  5.55it/s]

 32%|███████████████████▏                                         | 309/980 [00:52<02:00,  5.57it/s]

 32%|███████████████████▎                                         | 310/980 [00:52<02:00,  5.57it/s]

 32%|███████████████████▎                                         | 311/980 [00:52<02:01,  5.50it/s]

 32%|███████████████████▍                                         | 312/980 [00:53<02:03,  5.42it/s]

 32%|███████████████████▍                                         | 313/980 [00:53<02:01,  5.50it/s]

 32%|███████████████████▌                                         | 314/980 [00:53<02:00,  5.51it/s]

 32%|███████████████████▌                                         | 315/980 [00:53<02:05,  5.30it/s]

 32%|███████████████████▋                                         | 316/980 [00:53<02:04,  5.34it/s]

 32%|███████████████████▋                                         | 317/980 [00:54<02:07,  5.22it/s]

 32%|███████████████████▊                                         | 318/980 [00:54<02:08,  5.17it/s]

 33%|███████████████████▊                                         | 319/980 [00:54<02:08,  5.15it/s]

 33%|███████████████████▉                                         | 320/980 [00:54<02:05,  5.26it/s]

 33%|███████████████████▉                                         | 321/980 [00:54<02:04,  5.28it/s]

 33%|████████████████████                                         | 322/980 [00:55<02:04,  5.30it/s]

 33%|████████████████████                                         | 323/980 [00:55<02:01,  5.40it/s]

 33%|████████████████████▏                                        | 324/980 [00:55<01:57,  5.58it/s]

 33%|████████████████████▏                                        | 325/980 [00:55<01:56,  5.64it/s]

 33%|████████████████████▎                                        | 326/980 [00:55<01:56,  5.61it/s]

 33%|████████████████████▎                                        | 327/980 [00:55<01:54,  5.70it/s]

 33%|████████████████████▍                                        | 328/980 [00:56<01:53,  5.77it/s]

 34%|████████████████████▍                                        | 329/980 [00:56<01:52,  5.79it/s]

 34%|████████████████████▌                                        | 330/980 [00:56<01:52,  5.80it/s]

 34%|████████████████████▌                                        | 331/980 [00:56<01:51,  5.81it/s]

 34%|████████████████████▋                                        | 332/980 [00:56<01:52,  5.79it/s]

 34%|████████████████████▋                                        | 333/980 [00:56<01:53,  5.69it/s]

 34%|████████████████████▊                                        | 334/980 [00:57<01:54,  5.65it/s]

 34%|████████████████████▊                                        | 335/980 [00:57<01:56,  5.55it/s]

 34%|████████████████████▉                                        | 336/980 [00:57<01:57,  5.49it/s]

 34%|████████████████████▉                                        | 337/980 [00:57<01:54,  5.61it/s]

 34%|█████████████████████                                        | 338/980 [00:57<01:55,  5.54it/s]

 35%|█████████████████████                                        | 339/980 [00:58<01:54,  5.58it/s]

 35%|█████████████████████▏                                       | 340/980 [00:58<01:53,  5.62it/s]

 35%|█████████████████████▏                                       | 341/980 [00:58<01:53,  5.65it/s]

 35%|█████████████████████▎                                       | 342/980 [00:58<01:50,  5.77it/s]

 35%|█████████████████████▎                                       | 343/980 [00:58<01:47,  5.95it/s]

 35%|█████████████████████▍                                       | 344/980 [00:58<01:47,  5.93it/s]

 35%|█████████████████████▍                                       | 345/980 [00:59<01:48,  5.84it/s]

 35%|█████████████████████▌                                       | 346/980 [00:59<01:48,  5.85it/s]

 35%|█████████████████████▌                                       | 347/980 [00:59<01:48,  5.84it/s]

 36%|█████████████████████▋                                       | 348/980 [00:59<01:49,  5.77it/s]

 36%|█████████████████████▋                                       | 349/980 [00:59<01:47,  5.86it/s]

 36%|█████████████████████▊                                       | 350/980 [00:59<01:49,  5.78it/s]

 36%|█████████████████████▊                                       | 351/980 [01:00<01:47,  5.83it/s]

 36%|█████████████████████▉                                       | 352/980 [01:00<01:50,  5.68it/s]

 36%|█████████████████████▉                                       | 353/980 [01:00<01:53,  5.51it/s]

 36%|██████████████████████                                       | 354/980 [01:00<01:54,  5.45it/s]

 36%|██████████████████████                                       | 355/980 [01:00<01:55,  5.41it/s]

 36%|██████████████████████▏                                      | 356/980 [01:01<01:56,  5.38it/s]

 36%|██████████████████████▏                                      | 357/980 [01:01<01:54,  5.44it/s]

 37%|██████████████████████▎                                      | 358/980 [01:01<01:52,  5.53it/s]

 37%|██████████████████████▎                                      | 359/980 [01:01<01:49,  5.66it/s]

 37%|██████████████████████▍                                      | 360/980 [01:01<01:49,  5.64it/s]

 37%|██████████████████████▍                                      | 361/980 [01:01<01:49,  5.68it/s]

 37%|██████████████████████▌                                      | 362/980 [01:02<01:47,  5.75it/s]

 37%|██████████████████████▌                                      | 363/980 [01:02<01:46,  5.80it/s]

 37%|██████████████████████▋                                      | 364/980 [01:02<01:46,  5.79it/s]

 37%|██████████████████████▋                                      | 365/980 [01:02<01:45,  5.81it/s]

 37%|██████████████████████▊                                      | 366/980 [01:02<01:46,  5.78it/s]

 37%|██████████████████████▊                                      | 367/980 [01:02<01:47,  5.68it/s]

 38%|██████████████████████▉                                      | 368/980 [01:03<01:45,  5.79it/s]

 38%|██████████████████████▉                                      | 369/980 [01:03<01:46,  5.75it/s]

 38%|███████████████████████                                      | 370/980 [01:03<01:48,  5.61it/s]

 38%|███████████████████████                                      | 371/980 [01:03<01:48,  5.60it/s]

 38%|███████████████████████▏                                     | 372/980 [01:03<01:46,  5.68it/s]

 38%|███████████████████████▏                                     | 373/980 [01:04<01:47,  5.64it/s]

 38%|███████████████████████▎                                     | 374/980 [01:04<01:46,  5.68it/s]

 38%|███████████████████████▎                                     | 375/980 [01:04<01:44,  5.77it/s]

 38%|███████████████████████▍                                     | 376/980 [01:04<01:43,  5.84it/s]

 38%|███████████████████████▍                                     | 377/980 [01:04<01:42,  5.88it/s]

 39%|███████████████████████▌                                     | 378/980 [01:04<01:41,  5.93it/s]

 39%|███████████████████████▌                                     | 379/980 [01:05<01:40,  5.96it/s]

 39%|███████████████████████▋                                     | 380/980 [01:05<01:41,  5.93it/s]

 39%|███████████████████████▋                                     | 381/980 [01:05<01:41,  5.92it/s]

 39%|███████████████████████▊                                     | 382/980 [01:05<01:42,  5.86it/s]

 39%|███████████████████████▊                                     | 383/980 [01:05<01:41,  5.86it/s]

 39%|███████████████████████▉                                     | 384/980 [01:05<01:42,  5.79it/s]

 39%|███████████████████████▉                                     | 385/980 [01:06<01:44,  5.69it/s]

 39%|████████████████████████                                     | 386/980 [01:06<01:46,  5.59it/s]

 39%|████████████████████████                                     | 387/980 [01:06<01:47,  5.54it/s]

 40%|████████████████████████▏                                    | 388/980 [01:06<01:48,  5.47it/s]

 40%|████████████████████████▏                                    | 389/980 [01:06<01:48,  5.45it/s]

 40%|████████████████████████▎                                    | 390/980 [01:06<01:50,  5.35it/s]

 40%|████████████████████████▎                                    | 391/980 [01:07<01:50,  5.35it/s]

 40%|████████████████████████▍                                    | 392/980 [01:07<01:46,  5.53it/s]

 40%|████████████████████████▍                                    | 393/980 [01:07<01:43,  5.66it/s]

 40%|████████████████████████▌                                    | 394/980 [01:07<01:41,  5.75it/s]

 40%|████████████████████████▌                                    | 395/980 [01:07<01:40,  5.82it/s]

 40%|████████████████████████▋                                    | 396/980 [01:08<01:40,  5.83it/s]

 41%|████████████████████████▋                                    | 397/980 [01:08<01:41,  5.77it/s]

 41%|████████████████████████▊                                    | 398/980 [01:08<01:40,  5.82it/s]

 41%|████████████████████████▊                                    | 399/980 [01:08<01:39,  5.82it/s]

 41%|████████████████████████▉                                    | 400/980 [01:08<01:40,  5.76it/s]

 41%|████████████████████████▉                                    | 401/980 [01:08<01:39,  5.81it/s]

 41%|█████████████████████████                                    | 402/980 [01:09<01:41,  5.72it/s]

 41%|█████████████████████████                                    | 403/980 [01:09<01:42,  5.62it/s]

 41%|█████████████████████████▏                                   | 404/980 [01:09<01:43,  5.54it/s]

 41%|█████████████████████████▏                                   | 405/980 [01:09<01:46,  5.40it/s]

 41%|█████████████████████████▎                                   | 406/980 [01:09<01:47,  5.32it/s]

 42%|█████████████████████████▎                                   | 407/980 [01:10<01:45,  5.42it/s]

 42%|█████████████████████████▍                                   | 408/980 [01:10<01:44,  5.46it/s]

 42%|█████████████████████████▍                                   | 409/980 [01:10<01:41,  5.62it/s]

 42%|█████████████████████████▌                                   | 410/980 [01:10<01:39,  5.72it/s]

 42%|█████████████████████████▌                                   | 411/980 [01:10<01:37,  5.81it/s]

 42%|█████████████████████████▋                                   | 412/980 [01:10<01:37,  5.80it/s]

 42%|█████████████████████████▋                                   | 413/980 [01:11<01:37,  5.83it/s]

 42%|█████████████████████████▊                                   | 414/980 [01:11<01:37,  5.82it/s]

 42%|█████████████████████████▊                                   | 415/980 [01:11<01:36,  5.84it/s]

 42%|█████████████████████████▉                                   | 416/980 [01:11<01:37,  5.79it/s]

 43%|█████████████████████████▉                                   | 417/980 [01:11<01:37,  5.80it/s]

 43%|██████████████████████████                                   | 418/980 [01:11<01:36,  5.83it/s]

 43%|██████████████████████████                                   | 419/980 [01:12<01:38,  5.71it/s]

 43%|██████████████████████████▏                                  | 420/980 [01:12<01:40,  5.60it/s]

 43%|██████████████████████████▏                                  | 421/980 [01:12<01:40,  5.56it/s]

 43%|██████████████████████████▎                                  | 422/980 [01:12<01:41,  5.51it/s]

 43%|██████████████████████████▎                                  | 423/980 [01:12<01:41,  5.51it/s]

 43%|██████████████████████████▍                                  | 424/980 [01:12<01:39,  5.59it/s]

 43%|██████████████████████████▍                                  | 425/980 [01:13<01:37,  5.68it/s]

 43%|██████████████████████████▌                                  | 426/980 [01:13<01:35,  5.79it/s]

 44%|██████████████████████████▌                                  | 427/980 [01:13<01:34,  5.87it/s]

 44%|██████████████████████████▋                                  | 428/980 [01:13<01:33,  5.91it/s]

 44%|██████████████████████████▋                                  | 429/980 [01:13<01:32,  5.96it/s]

 44%|██████████████████████████▊                                  | 430/980 [01:13<01:33,  5.91it/s]

 44%|██████████████████████████▊                                  | 431/980 [01:14<01:33,  5.87it/s]

 44%|██████████████████████████▉                                  | 432/980 [01:14<01:33,  5.87it/s]

 44%|██████████████████████████▉                                  | 433/980 [01:14<01:33,  5.82it/s]

 44%|███████████████████████████                                  | 434/980 [01:14<01:34,  5.78it/s]

 44%|███████████████████████████                                  | 435/980 [01:14<01:35,  5.71it/s]

 44%|███████████████████████████▏                                 | 436/980 [01:15<01:34,  5.74it/s]

 45%|███████████████████████████▏                                 | 437/980 [01:15<01:35,  5.68it/s]

 45%|███████████████████████████▎                                 | 438/980 [01:15<01:37,  5.56it/s]

 45%|███████████████████████████▎                                 | 439/980 [01:15<01:37,  5.54it/s]

 45%|███████████████████████████▍                                 | 440/980 [01:15<01:36,  5.59it/s]

 45%|███████████████████████████▍                                 | 441/980 [01:15<01:37,  5.52it/s]

 45%|███████████████████████████▌                                 | 442/980 [01:16<01:40,  5.34it/s]

 45%|███████████████████████████▌                                 | 443/980 [01:16<01:40,  5.36it/s]

 45%|███████████████████████████▋                                 | 444/980 [01:16<01:37,  5.50it/s]

 45%|███████████████████████████▋                                 | 445/980 [01:16<01:37,  5.49it/s]

 46%|███████████████████████████▊                                 | 446/980 [01:16<01:36,  5.54it/s]

 46%|███████████████████████████▊                                 | 447/980 [01:17<01:36,  5.54it/s]

 46%|███████████████████████████▉                                 | 448/980 [01:17<01:36,  5.52it/s]

 46%|███████████████████████████▉                                 | 449/980 [01:17<01:36,  5.52it/s]

 46%|████████████████████████████                                 | 450/980 [01:17<01:35,  5.55it/s]

 46%|████████████████████████████                                 | 451/980 [01:17<01:35,  5.53it/s]

 46%|████████████████████████████▏                                | 452/980 [01:17<01:35,  5.54it/s]

 46%|████████████████████████████▏                                | 453/980 [01:18<01:35,  5.49it/s]

 46%|████████████████████████████▎                                | 454/980 [01:18<01:37,  5.37it/s]

 46%|████████████████████████████▎                                | 455/980 [01:18<01:39,  5.29it/s]

 47%|████████████████████████████▍                                | 456/980 [01:18<01:40,  5.23it/s]

 47%|████████████████████████████▍                                | 457/980 [01:18<01:40,  5.18it/s]

 47%|████████████████████████████▌                                | 458/980 [01:19<01:40,  5.19it/s]

 47%|████████████████████████████▌                                | 459/980 [01:19<01:39,  5.24it/s]

 47%|████████████████████████████▋                                | 460/980 [01:19<01:39,  5.25it/s]

 47%|████████████████████████████▋                                | 461/980 [01:19<01:39,  5.22it/s]

 47%|████████████████████████████▊                                | 462/980 [01:19<01:37,  5.33it/s]

 47%|████████████████████████████▊                                | 463/980 [01:20<01:36,  5.36it/s]

 47%|████████████████████████████▉                                | 464/980 [01:20<01:35,  5.42it/s]

 47%|████████████████████████████▉                                | 465/980 [01:20<01:34,  5.48it/s]

 48%|█████████████████████████████                                | 466/980 [01:20<01:33,  5.49it/s]

 48%|█████████████████████████████                                | 467/980 [01:20<01:33,  5.48it/s]

 48%|█████████████████████████████▏                               | 468/980 [01:20<01:34,  5.44it/s]

 48%|█████████████████████████████▏                               | 469/980 [01:21<01:33,  5.45it/s]

 48%|█████████████████████████████▎                               | 470/980 [01:21<01:31,  5.60it/s]

 48%|█████████████████████████████▎                               | 471/980 [01:21<01:32,  5.49it/s]

 48%|█████████████████████████████▍                               | 472/980 [01:21<01:34,  5.35it/s]

 48%|█████████████████████████████▍                               | 473/980 [01:21<01:35,  5.31it/s]

 48%|█████████████████████████████▌                               | 474/980 [01:22<01:37,  5.19it/s]

 48%|█████████████████████████████▌                               | 475/980 [01:22<01:37,  5.20it/s]

 49%|█████████████████████████████▋                               | 476/980 [01:22<01:35,  5.26it/s]

 49%|█████████████████████████████▋                               | 477/980 [01:22<01:35,  5.28it/s]

 49%|█████████████████████████████▊                               | 478/980 [01:22<01:34,  5.33it/s]

 49%|█████████████████████████████▊                               | 479/980 [01:22<01:32,  5.42it/s]

 49%|█████████████████████████████▉                               | 480/980 [01:23<01:32,  5.38it/s]

 49%|█████████████████████████████▉                               | 481/980 [01:23<01:31,  5.47it/s]

 49%|██████████████████████████████                               | 482/980 [01:23<01:31,  5.44it/s]

 49%|██████████████████████████████                               | 483/980 [01:23<01:30,  5.49it/s]

 49%|██████████████████████████████▏                              | 484/980 [01:23<01:33,  5.33it/s]

 49%|██████████████████████████████▏                              | 485/980 [01:24<01:32,  5.37it/s]

 50%|██████████████████████████████▎                              | 486/980 [01:24<01:32,  5.33it/s]

 50%|██████████████████████████████▎                              | 487/980 [01:24<01:31,  5.41it/s]

 50%|██████████████████████████████▍                              | 488/980 [01:24<01:31,  5.39it/s]

 50%|██████████████████████████████▍                              | 489/980 [01:24<01:30,  5.43it/s]

 50%|██████████████████████████████▌                              | 490/980 [01:25<01:30,  5.40it/s]

 50%|██████████████████████████████▌                              | 491/980 [01:25<01:30,  5.41it/s]

 50%|██████████████████████████████▌                              | 492/980 [01:25<01:30,  5.41it/s]

 50%|██████████████████████████████▋                              | 493/980 [01:25<01:29,  5.43it/s]

 50%|██████████████████████████████▋                              | 494/980 [01:25<01:28,  5.47it/s]

 51%|██████████████████████████████▊                              | 495/980 [01:25<01:27,  5.55it/s]

 51%|██████████████████████████████▊                              | 496/980 [01:26<01:26,  5.57it/s]

 51%|██████████████████████████████▉                              | 497/980 [01:26<01:26,  5.61it/s]

 51%|██████████████████████████████▉                              | 498/980 [01:26<01:24,  5.70it/s]

 51%|███████████████████████████████                              | 499/980 [01:26<01:23,  5.75it/s]

 51%|███████████████████████████████                              | 500/980 [01:26<01:22,  5.79it/s]

 51%|███████████████████████████████▏                             | 501/980 [01:26<01:23,  5.76it/s]

 51%|███████████████████████████████▏                             | 502/980 [01:27<01:23,  5.71it/s]

 51%|███████████████████████████████▎                             | 503/980 [01:27<01:25,  5.57it/s]

 51%|███████████████████████████████▎                             | 504/980 [01:27<01:24,  5.62it/s]

 52%|███████████████████████████████▍                             | 505/980 [01:27<01:27,  5.43it/s]

 52%|███████████████████████████████▍                             | 506/980 [01:27<01:28,  5.36it/s]

 52%|███████████████████████████████▌                             | 507/980 [01:28<01:26,  5.47it/s]

 52%|███████████████████████████████▌                             | 508/980 [01:28<01:25,  5.51it/s]

 52%|███████████████████████████████▋                             | 509/980 [01:28<01:24,  5.56it/s]

 52%|███████████████████████████████▋                             | 510/980 [01:28<01:21,  5.75it/s]

 52%|███████████████████████████████▊                             | 511/980 [01:28<01:21,  5.77it/s]

 52%|███████████████████████████████▊                             | 512/980 [01:28<01:20,  5.79it/s]

 52%|███████████████████████████████▉                             | 513/980 [01:29<01:22,  5.68it/s]

 52%|███████████████████████████████▉                             | 514/980 [01:29<01:20,  5.76it/s]

 53%|████████████████████████████████                             | 515/980 [01:29<01:19,  5.82it/s]

 53%|████████████████████████████████                             | 516/980 [01:29<01:19,  5.86it/s]

 53%|████████████████████████████████▏                            | 517/980 [01:29<01:19,  5.84it/s]

 53%|████████████████████████████████▏                            | 518/980 [01:29<01:18,  5.86it/s]

 53%|████████████████████████████████▎                            | 519/980 [01:30<01:18,  5.85it/s]

 53%|████████████████████████████████▎                            | 520/980 [01:30<01:18,  5.88it/s]

 53%|████████████████████████████████▍                            | 521/980 [01:30<01:17,  5.89it/s]

 53%|████████████████████████████████▍                            | 522/980 [01:30<01:18,  5.87it/s]

 53%|████████████████████████████████▌                            | 523/980 [01:30<01:18,  5.82it/s]

 53%|████████████████████████████████▌                            | 524/980 [01:31<01:19,  5.76it/s]

 54%|████████████████████████████████▋                            | 525/980 [01:31<01:19,  5.69it/s]

 54%|████████████████████████████████▋                            | 526/980 [01:31<01:21,  5.60it/s]

 54%|████████████████████████████████▊                            | 527/980 [01:31<01:19,  5.68it/s]

 54%|████████████████████████████████▊                            | 528/980 [01:31<01:20,  5.62it/s]

 54%|████████████████████████████████▉                            | 529/980 [01:31<01:19,  5.64it/s]

 54%|████████████████████████████████▉                            | 530/980 [01:32<01:19,  5.66it/s]

 54%|█████████████████████████████████                            | 531/980 [01:32<01:19,  5.66it/s]

 54%|█████████████████████████████████                            | 532/980 [01:32<01:18,  5.67it/s]

 54%|█████████████████████████████████▏                           | 533/980 [01:32<01:18,  5.72it/s]

 54%|█████████████████████████████████▏                           | 534/980 [01:32<01:17,  5.77it/s]

 55%|█████████████████████████████████▎                           | 535/980 [01:32<01:16,  5.81it/s]

 55%|█████████████████████████████████▎                           | 536/980 [01:33<01:16,  5.83it/s]

 55%|█████████████████████████████████▍                           | 537/980 [01:33<01:22,  5.35it/s]

 55%|█████████████████████████████████▍                           | 538/980 [01:33<01:20,  5.50it/s]

 55%|█████████████████████████████████▌                           | 539/980 [01:33<01:18,  5.61it/s]

 55%|█████████████████████████████████▌                           | 540/980 [01:33<01:18,  5.64it/s]

 55%|█████████████████████████████████▋                           | 541/980 [01:34<01:18,  5.57it/s]

 55%|█████████████████████████████████▋                           | 542/980 [01:34<01:19,  5.52it/s]

 55%|█████████████████████████████████▊                           | 543/980 [01:34<01:19,  5.50it/s]

 56%|█████████████████████████████████▊                           | 544/980 [01:34<01:17,  5.65it/s]

 56%|█████████████████████████████████▉                           | 545/980 [01:34<01:17,  5.61it/s]

 56%|█████████████████████████████████▉                           | 546/980 [01:34<01:17,  5.58it/s]

 56%|██████████████████████████████████                           | 547/980 [01:35<01:20,  5.40it/s]

 56%|██████████████████████████████████                           | 548/980 [01:35<01:20,  5.38it/s]

 56%|██████████████████████████████████▏                          | 549/980 [01:35<01:18,  5.46it/s]

 56%|██████████████████████████████████▏                          | 550/980 [01:35<01:19,  5.44it/s]

 56%|██████████████████████████████████▎                          | 551/980 [01:35<01:17,  5.53it/s]

 56%|██████████████████████████████████▎                          | 552/980 [01:36<01:14,  5.78it/s]

 56%|██████████████████████████████████▍                          | 553/980 [01:36<01:14,  5.72it/s]

 57%|██████████████████████████████████▍                          | 554/980 [01:36<01:13,  5.77it/s]

 57%|██████████████████████████████████▌                          | 555/980 [01:36<01:13,  5.81it/s]

 57%|██████████████████████████████████▌                          | 556/980 [01:36<01:13,  5.75it/s]

 57%|██████████████████████████████████▋                          | 557/980 [01:36<01:14,  5.70it/s]

 57%|██████████████████████████████████▋                          | 558/980 [01:37<01:15,  5.61it/s]

 57%|██████████████████████████████████▊                          | 559/980 [01:37<01:15,  5.55it/s]

 57%|██████████████████████████████████▊                          | 560/980 [01:37<01:14,  5.63it/s]

 57%|██████████████████████████████████▉                          | 561/980 [01:37<01:13,  5.73it/s]

 57%|██████████████████████████████████▉                          | 562/980 [01:37<01:12,  5.73it/s]

 57%|███████████████████████████████████                          | 563/980 [01:37<01:13,  5.71it/s]

 58%|███████████████████████████████████                          | 564/980 [01:38<01:14,  5.56it/s]

 58%|███████████████████████████████████▏                         | 565/980 [01:38<01:15,  5.50it/s]

 58%|███████████████████████████████████▏                         | 566/980 [01:38<01:15,  5.49it/s]

 58%|███████████████████████████████████▎                         | 567/980 [01:38<01:15,  5.48it/s]

 58%|███████████████████████████████████▎                         | 568/980 [01:38<01:14,  5.55it/s]

 58%|███████████████████████████████████▍                         | 569/980 [01:39<01:13,  5.59it/s]

 58%|███████████████████████████████████▍                         | 570/980 [01:39<01:12,  5.63it/s]

 58%|███████████████████████████████████▌                         | 571/980 [01:39<01:10,  5.81it/s]

 58%|███████████████████████████████████▌                         | 572/980 [01:39<01:10,  5.77it/s]

 58%|███████████████████████████████████▋                         | 573/980 [01:39<01:11,  5.71it/s]

 59%|███████████████████████████████████▋                         | 574/980 [01:39<01:13,  5.54it/s]

 59%|███████████████████████████████████▊                         | 575/980 [01:40<01:14,  5.46it/s]

 59%|███████████████████████████████████▊                         | 576/980 [01:40<01:14,  5.44it/s]

 59%|███████████████████████████████████▉                         | 577/980 [01:40<01:12,  5.54it/s]

 59%|███████████████████████████████████▉                         | 578/980 [01:40<01:12,  5.58it/s]

 59%|████████████████████████████████████                         | 579/980 [01:40<01:11,  5.61it/s]

 59%|████████████████████████████████████                         | 580/980 [01:41<01:12,  5.55it/s]

 59%|████████████████████████████████████▏                        | 581/980 [01:41<01:12,  5.52it/s]

 59%|████████████████████████████████████▏                        | 582/980 [01:41<01:11,  5.53it/s]

 59%|████████████████████████████████████▎                        | 583/980 [01:41<01:10,  5.60it/s]

 60%|████████████████████████████████████▎                        | 584/980 [01:41<01:11,  5.57it/s]

 60%|████████████████████████████████████▍                        | 585/980 [01:41<01:09,  5.66it/s]

 60%|████████████████████████████████████▍                        | 586/980 [01:42<01:10,  5.63it/s]

 60%|████████████████████████████████████▌                        | 587/980 [01:42<01:10,  5.60it/s]

 60%|████████████████████████████████████▌                        | 588/980 [01:42<01:09,  5.66it/s]

 60%|████████████████████████████████████▋                        | 589/980 [01:42<01:08,  5.72it/s]

 60%|████████████████████████████████████▋                        | 590/980 [01:42<01:08,  5.71it/s]

 60%|████████████████████████████████████▊                        | 591/980 [01:42<01:09,  5.63it/s]

 60%|████████████████████████████████████▊                        | 592/980 [01:43<01:08,  5.68it/s]

 61%|████████████████████████████████████▉                        | 593/980 [01:43<01:08,  5.63it/s]

 61%|████████████████████████████████████▉                        | 594/980 [01:43<01:07,  5.70it/s]

 61%|█████████████████████████████████████                        | 595/980 [01:43<01:06,  5.76it/s]

 61%|█████████████████████████████████████                        | 596/980 [01:43<01:06,  5.79it/s]

 61%|█████████████████████████████████████▏                       | 597/980 [01:43<01:05,  5.87it/s]

 61%|█████████████████████████████████████▏                       | 598/980 [01:44<01:05,  5.85it/s]

 61%|█████████████████████████████████████▎                       | 599/980 [01:44<01:05,  5.84it/s]

 61%|█████████████████████████████████████▎                       | 600/980 [01:44<01:05,  5.78it/s]

 61%|█████████████████████████████████████▍                       | 601/980 [01:44<01:07,  5.65it/s]

 61%|█████████████████████████████████████▍                       | 602/980 [01:44<01:06,  5.67it/s]

 62%|█████████████████████████████████████▌                       | 603/980 [01:45<01:09,  5.44it/s]

 62%|█████████████████████████████████████▌                       | 604/980 [01:45<01:07,  5.56it/s]

 62%|█████████████████████████████████████▋                       | 605/980 [01:45<01:07,  5.55it/s]

 62%|█████████████████████████████████████▋                       | 606/980 [01:45<01:07,  5.58it/s]

 62%|█████████████████████████████████████▊                       | 607/980 [01:45<01:06,  5.60it/s]

 62%|█████████████████████████████████████▊                       | 608/980 [01:45<01:06,  5.57it/s]

 62%|█████████████████████████████████████▉                       | 609/980 [01:46<01:06,  5.57it/s]

 62%|█████████████████████████████████████▉                       | 610/980 [01:46<01:05,  5.62it/s]

 62%|██████████████████████████████████████                       | 611/980 [01:46<01:05,  5.64it/s]

 62%|██████████████████████████████████████                       | 612/980 [01:46<01:05,  5.64it/s]

 63%|██████████████████████████████████████▏                      | 613/980 [01:46<01:03,  5.74it/s]

 63%|██████████████████████████████████████▏                      | 614/980 [01:46<01:03,  5.78it/s]

 63%|██████████████████████████████████████▎                      | 615/980 [01:47<01:03,  5.72it/s]

 63%|██████████████████████████████████████▎                      | 616/980 [01:47<01:03,  5.69it/s]

 63%|██████████████████████████████████████▍                      | 617/980 [01:47<01:03,  5.69it/s]

 63%|██████████████████████████████████████▍                      | 618/980 [01:47<01:03,  5.68it/s]

 63%|██████████████████████████████████████▌                      | 619/980 [01:47<01:04,  5.59it/s]

 63%|██████████████████████████████████████▌                      | 620/980 [01:48<01:04,  5.61it/s]

 63%|██████████████████████████████████████▋                      | 621/980 [01:48<01:05,  5.51it/s]

 63%|██████████████████████████████████████▋                      | 622/980 [01:48<01:03,  5.62it/s]

 64%|██████████████████████████████████████▊                      | 623/980 [01:48<01:03,  5.65it/s]

 64%|██████████████████████████████████████▊                      | 624/980 [01:48<01:03,  5.57it/s]

 64%|██████████████████████████████████████▉                      | 625/980 [01:48<01:03,  5.56it/s]

 64%|██████████████████████████████████████▉                      | 626/980 [01:49<01:02,  5.62it/s]

 64%|███████████████████████████████████████                      | 627/980 [01:49<01:02,  5.64it/s]

 64%|███████████████████████████████████████                      | 628/980 [01:49<01:02,  5.63it/s]

 64%|███████████████████████████████████████▏                     | 629/980 [01:49<01:02,  5.58it/s]

 64%|███████████████████████████████████████▏                     | 630/980 [01:49<01:01,  5.73it/s]

 64%|███████████████████████████████████████▎                     | 631/980 [01:50<01:01,  5.69it/s]

 64%|███████████████████████████████████████▎                     | 632/980 [01:50<01:03,  5.52it/s]

 65%|███████████████████████████████████████▍                     | 633/980 [01:50<01:05,  5.31it/s]

 65%|███████████████████████████████████████▍                     | 634/980 [01:50<01:04,  5.40it/s]

 65%|███████████████████████████████████████▌                     | 635/980 [01:50<01:04,  5.31it/s]

 65%|███████████████████████████████████████▌                     | 636/980 [01:51<01:06,  5.15it/s]

 65%|███████████████████████████████████████▋                     | 637/980 [01:51<01:06,  5.18it/s]

 65%|███████████████████████████████████████▋                     | 638/980 [01:51<01:03,  5.40it/s]

 65%|███████████████████████████████████████▊                     | 639/980 [01:51<01:02,  5.46it/s]

 65%|███████████████████████████████████████▊                     | 640/980 [01:51<01:01,  5.49it/s]

 65%|███████████████████████████████████████▉                     | 641/980 [01:51<01:01,  5.53it/s]

 66%|███████████████████████████████████████▉                     | 642/980 [01:52<01:02,  5.45it/s]

 66%|████████████████████████████████████████                     | 643/980 [01:52<01:02,  5.42it/s]

 66%|████████████████████████████████████████                     | 644/980 [01:52<01:02,  5.39it/s]

 66%|████████████████████████████████████████▏                    | 645/980 [01:52<01:01,  5.44it/s]

 66%|████████████████████████████████████████▏                    | 646/980 [01:52<01:00,  5.51it/s]

 66%|████████████████████████████████████████▎                    | 647/980 [01:52<00:58,  5.66it/s]

 66%|████████████████████████████████████████▎                    | 648/980 [01:53<00:59,  5.54it/s]

 66%|████████████████████████████████████████▍                    | 649/980 [01:53<01:00,  5.50it/s]

 66%|████████████████████████████████████████▍                    | 650/980 [01:53<01:00,  5.48it/s]

 66%|████████████████████████████████████████▌                    | 651/980 [01:53<01:01,  5.39it/s]

 67%|████████████████████████████████████████▌                    | 652/980 [01:53<01:01,  5.33it/s]

 67%|████████████████████████████████████████▋                    | 653/980 [01:54<01:01,  5.35it/s]

 67%|████████████████████████████████████████▋                    | 654/980 [01:54<01:01,  5.32it/s]

 67%|████████████████████████████████████████▊                    | 655/980 [01:54<01:00,  5.34it/s]

 67%|████████████████████████████████████████▊                    | 656/980 [01:54<01:00,  5.37it/s]

 67%|████████████████████████████████████████▉                    | 657/980 [01:54<01:00,  5.32it/s]

 67%|████████████████████████████████████████▉                    | 658/980 [01:55<01:01,  5.27it/s]

 67%|█████████████████████████████████████████                    | 659/980 [01:55<01:01,  5.25it/s]

 67%|█████████████████████████████████████████                    | 660/980 [01:55<01:01,  5.21it/s]

 67%|█████████████████████████████████████████▏                   | 661/980 [01:55<00:59,  5.39it/s]

 68%|█████████████████████████████████████████▏                   | 662/980 [01:55<00:59,  5.38it/s]

 68%|█████████████████████████████████████████▎                   | 663/980 [01:55<00:58,  5.41it/s]

 68%|█████████████████████████████████████████▎                   | 664/980 [01:56<00:57,  5.54it/s]

 68%|█████████████████████████████████████████▍                   | 665/980 [01:56<00:57,  5.48it/s]

 68%|█████████████████████████████████████████▍                   | 666/980 [01:56<00:57,  5.44it/s]

 68%|█████████████████████████████████████████▌                   | 667/980 [01:56<00:58,  5.36it/s]

 68%|█████████████████████████████████████████▌                   | 668/980 [01:56<00:58,  5.31it/s]

 68%|█████████████████████████████████████████▋                   | 669/980 [01:57<00:58,  5.31it/s]

 68%|█████████████████████████████████████████▋                   | 670/980 [01:57<00:58,  5.30it/s]

 68%|█████████████████████████████████████████▊                   | 671/980 [01:57<00:58,  5.31it/s]

 69%|█████████████████████████████████████████▊                   | 672/980 [01:57<00:57,  5.37it/s]

 69%|█████████████████████████████████████████▉                   | 673/980 [01:57<00:56,  5.45it/s]

 69%|█████████████████████████████████████████▉                   | 674/980 [01:58<00:56,  5.38it/s]

 69%|██████████████████████████████████████████                   | 675/980 [01:58<00:57,  5.29it/s]

 69%|██████████████████████████████████████████                   | 676/980 [01:58<00:57,  5.28it/s]

 69%|██████████████████████████████████████████▏                  | 677/980 [01:58<00:58,  5.22it/s]

 69%|██████████████████████████████████████████▏                  | 678/980 [01:58<00:57,  5.21it/s]

 69%|██████████████████████████████████████████▎                  | 679/980 [01:58<00:57,  5.25it/s]

 69%|██████████████████████████████████████████▎                  | 680/980 [01:59<00:55,  5.39it/s]

 69%|██████████████████████████████████████████▍                  | 681/980 [01:59<00:55,  5.41it/s]

 70%|██████████████████████████████████████████▍                  | 682/980 [01:59<00:55,  5.36it/s]

 70%|██████████████████████████████████████████▌                  | 683/980 [01:59<00:56,  5.30it/s]

 70%|██████████████████████████████████████████▌                  | 684/980 [01:59<00:55,  5.29it/s]

 70%|██████████████████████████████████████████▋                  | 685/980 [02:00<00:55,  5.35it/s]

 70%|██████████████████████████████████████████▋                  | 686/980 [02:00<00:55,  5.27it/s]

 70%|██████████████████████████████████████████▊                  | 687/980 [02:00<00:55,  5.24it/s]

 70%|██████████████████████████████████████████▊                  | 688/980 [02:00<00:54,  5.35it/s]

 70%|██████████████████████████████████████████▉                  | 689/980 [02:00<00:54,  5.36it/s]

 70%|██████████████████████████████████████████▉                  | 690/980 [02:01<00:53,  5.41it/s]

 71%|███████████████████████████████████████████                  | 691/980 [02:01<00:53,  5.38it/s]

 71%|███████████████████████████████████████████                  | 692/980 [02:01<00:53,  5.35it/s]

 71%|███████████████████████████████████████████▏                 | 693/980 [02:01<00:52,  5.46it/s]

 71%|███████████████████████████████████████████▏                 | 694/980 [02:01<00:51,  5.52it/s]

 71%|███████████████████████████████████████████▎                 | 695/980 [02:01<00:50,  5.67it/s]

 71%|███████████████████████████████████████████▎                 | 696/980 [02:02<00:49,  5.70it/s]

 71%|███████████████████████████████████████████▍                 | 697/980 [02:02<00:50,  5.66it/s]

 71%|███████████████████████████████████████████▍                 | 698/980 [02:02<00:49,  5.66it/s]

 71%|███████████████████████████████████████████▌                 | 699/980 [02:02<00:50,  5.60it/s]

 71%|███████████████████████████████████████████▌                 | 700/980 [02:02<00:50,  5.57it/s]

 72%|███████████████████████████████████████████▋                 | 701/980 [02:03<00:50,  5.50it/s]

 72%|███████████████████████████████████████████▋                 | 702/980 [02:03<00:49,  5.58it/s]

 72%|███████████████████████████████████████████▊                 | 703/980 [02:03<00:48,  5.70it/s]

 72%|███████████████████████████████████████████▊                 | 704/980 [02:03<00:49,  5.63it/s]

 72%|███████████████████████████████████████████▉                 | 705/980 [02:03<00:49,  5.61it/s]

 72%|███████████████████████████████████████████▉                 | 706/980 [02:03<00:49,  5.51it/s]

 72%|████████████████████████████████████████████                 | 707/980 [02:04<00:49,  5.46it/s]

 72%|████████████████████████████████████████████                 | 708/980 [02:04<00:49,  5.46it/s]

 72%|████████████████████████████████████████████▏                | 709/980 [02:04<00:49,  5.44it/s]

 72%|████████████████████████████████████████████▏                | 710/980 [02:04<00:48,  5.52it/s]

 73%|████████████████████████████████████████████▎                | 711/980 [02:04<00:49,  5.43it/s]

 73%|████████████████████████████████████████████▎                | 712/980 [02:04<00:48,  5.55it/s]

 73%|████████████████████████████████████████████▍                | 713/980 [02:05<00:47,  5.59it/s]

 73%|████████████████████████████████████████████▍                | 714/980 [02:05<00:48,  5.46it/s]

 73%|████████████████████████████████████████████▌                | 715/980 [02:05<00:48,  5.45it/s]

 73%|████████████████████████████████████████████▌                | 716/980 [02:05<00:46,  5.62it/s]

 73%|████████████████████████████████████████████▋                | 717/980 [02:05<00:46,  5.63it/s]

 73%|████████████████████████████████████████████▋                | 718/980 [02:06<00:46,  5.58it/s]

 73%|████████████████████████████████████████████▊                | 719/980 [02:06<00:46,  5.62it/s]

 73%|████████████████████████████████████████████▊                | 720/980 [02:06<00:45,  5.65it/s]

 74%|████████████████████████████████████████████▉                | 721/980 [02:06<00:45,  5.64it/s]

 74%|████████████████████████████████████████████▉                | 722/980 [02:06<00:45,  5.65it/s]

 74%|█████████████████████████████████████████████                | 723/980 [02:06<00:45,  5.61it/s]

 74%|█████████████████████████████████████████████                | 724/980 [02:07<00:45,  5.62it/s]

 74%|█████████████████████████████████████████████▏               | 725/980 [02:07<00:45,  5.64it/s]

 74%|█████████████████████████████████████████████▏               | 726/980 [02:07<00:45,  5.63it/s]

 74%|█████████████████████████████████████████████▎               | 727/980 [02:07<00:44,  5.64it/s]

 74%|█████████████████████████████████████████████▎               | 728/980 [02:07<00:44,  5.73it/s]

 74%|█████████████████████████████████████████████▍               | 729/980 [02:08<00:43,  5.72it/s]

 74%|█████████████████████████████████████████████▍               | 730/980 [02:08<00:44,  5.67it/s]

 75%|█████████████████████████████████████████████▌               | 731/980 [02:08<00:44,  5.66it/s]

 75%|█████████████████████████████████████████████▌               | 732/980 [02:08<00:44,  5.60it/s]

 75%|█████████████████████████████████████████████▋               | 733/980 [02:08<00:44,  5.57it/s]

 75%|█████████████████████████████████████████████▋               | 734/980 [02:08<00:44,  5.55it/s]

 75%|█████████████████████████████████████████████▊               | 735/980 [02:09<00:43,  5.62it/s]

 75%|█████████████████████████████████████████████▊               | 736/980 [02:09<00:43,  5.62it/s]

 75%|█████████████████████████████████████████████▊               | 737/980 [02:09<00:42,  5.67it/s]

 75%|█████████████████████████████████████████████▉               | 738/980 [02:09<00:42,  5.63it/s]

 75%|█████████████████████████████████████████████▉               | 739/980 [02:09<00:42,  5.63it/s]

 76%|██████████████████████████████████████████████               | 740/980 [02:09<00:42,  5.58it/s]

 76%|██████████████████████████████████████████████               | 741/980 [02:10<00:42,  5.58it/s]

 76%|██████████████████████████████████████████████▏              | 742/980 [02:10<00:42,  5.60it/s]

 76%|██████████████████████████████████████████████▏              | 743/980 [02:10<00:41,  5.68it/s]

 76%|██████████████████████████████████████████████▎              | 744/980 [02:10<00:40,  5.83it/s]

 76%|██████████████████████████████████████████████▎              | 745/980 [02:10<00:39,  5.89it/s]

 76%|██████████████████████████████████████████████▍              | 746/980 [02:11<00:39,  5.85it/s]

 76%|██████████████████████████████████████████████▍              | 747/980 [02:11<00:40,  5.77it/s]

 76%|██████████████████████████████████████████████▌              | 748/980 [02:11<00:40,  5.70it/s]

 76%|██████████████████████████████████████████████▌              | 749/980 [02:11<00:40,  5.66it/s]

 77%|██████████████████████████████████████████████▋              | 750/980 [02:11<00:40,  5.66it/s]

 77%|██████████████████████████████████████████████▋              | 751/980 [02:11<00:40,  5.68it/s]

 77%|██████████████████████████████████████████████▊              | 752/980 [02:12<00:39,  5.83it/s]

 77%|██████████████████████████████████████████████▊              | 753/980 [02:12<00:39,  5.81it/s]

 77%|██████████████████████████████████████████████▉              | 754/980 [02:12<00:39,  5.79it/s]

 77%|██████████████████████████████████████████████▉              | 755/980 [02:12<00:39,  5.77it/s]

 77%|███████████████████████████████████████████████              | 756/980 [02:12<00:39,  5.74it/s]

 77%|███████████████████████████████████████████████              | 757/980 [02:12<00:38,  5.74it/s]

 77%|███████████████████████████████████████████████▏             | 758/980 [02:13<00:38,  5.70it/s]

 77%|███████████████████████████████████████████████▏             | 759/980 [02:13<00:38,  5.75it/s]

 78%|███████████████████████████████████████████████▎             | 760/980 [02:13<00:37,  5.82it/s]

 78%|███████████████████████████████████████████████▎             | 761/980 [02:13<00:37,  5.88it/s]

 78%|███████████████████████████████████████████████▍             | 762/980 [02:13<00:36,  5.93it/s]

 78%|███████████████████████████████████████████████▍             | 763/980 [02:13<00:36,  5.93it/s]

 78%|███████████████████████████████████████████████▌             | 764/980 [02:14<00:36,  5.92it/s]

 78%|███████████████████████████████████████████████▌             | 765/980 [02:14<00:36,  5.87it/s]

 78%|███████████████████████████████████████████████▋             | 766/980 [02:14<00:36,  5.82it/s]

 78%|███████████████████████████████████████████████▋             | 767/980 [02:14<00:36,  5.89it/s]

 78%|███████████████████████████████████████████████▊             | 768/980 [02:14<00:37,  5.67it/s]

 78%|███████████████████████████████████████████████▊             | 769/980 [02:15<00:37,  5.58it/s]

 79%|███████████████████████████████████████████████▉             | 770/980 [02:15<00:38,  5.51it/s]

 79%|███████████████████████████████████████████████▉             | 771/980 [02:15<00:38,  5.45it/s]

 79%|████████████████████████████████████████████████             | 772/980 [02:15<00:38,  5.36it/s]

 79%|████████████████████████████████████████████████             | 773/980 [02:15<00:39,  5.24it/s]

 79%|████████████████████████████████████████████████▏            | 774/980 [02:15<00:37,  5.45it/s]

 79%|████████████████████████████████████████████████▏            | 775/980 [02:16<00:37,  5.50it/s]

 79%|████████████████████████████████████████████████▎            | 776/980 [02:16<00:36,  5.64it/s]

 79%|████████████████████████████████████████████████▎            | 777/980 [02:16<00:35,  5.73it/s]

 79%|████████████████████████████████████████████████▍            | 778/980 [02:16<00:34,  5.79it/s]

 79%|████████████████████████████████████████████████▍            | 779/980 [02:16<00:34,  5.78it/s]

 80%|████████████████████████████████████████████████▌            | 780/980 [02:16<00:34,  5.76it/s]

 80%|████████████████████████████████████████████████▌            | 781/980 [02:17<00:34,  5.75it/s]

 80%|████████████████████████████████████████████████▋            | 782/980 [02:17<00:34,  5.73it/s]

 80%|████████████████████████████████████████████████▋            | 783/980 [02:17<00:33,  5.84it/s]

 80%|████████████████████████████████████████████████▊            | 784/980 [02:17<00:34,  5.72it/s]

 80%|████████████████████████████████████████████████▊            | 785/980 [02:17<00:34,  5.69it/s]

 80%|████████████████████████████████████████████████▉            | 786/980 [02:18<00:34,  5.59it/s]

 80%|████████████████████████████████████████████████▉            | 787/980 [02:18<00:34,  5.66it/s]

 80%|█████████████████████████████████████████████████            | 788/980 [02:18<00:35,  5.47it/s]

 81%|█████████████████████████████████████████████████            | 789/980 [02:18<00:35,  5.44it/s]

 81%|█████████████████████████████████████████████████▏           | 790/980 [02:18<00:35,  5.43it/s]

 81%|█████████████████████████████████████████████████▏           | 791/980 [02:18<00:34,  5.52it/s]

 81%|█████████████████████████████████████████████████▎           | 792/980 [02:19<00:33,  5.54it/s]

 81%|█████████████████████████████████████████████████▎           | 793/980 [02:19<00:33,  5.63it/s]

 81%|█████████████████████████████████████████████████▍           | 794/980 [02:19<00:32,  5.70it/s]

 81%|█████████████████████████████████████████████████▍           | 795/980 [02:19<00:31,  5.84it/s]

 81%|█████████████████████████████████████████████████▌           | 796/980 [02:19<00:31,  5.86it/s]

 81%|█████████████████████████████████████████████████▌           | 797/980 [02:19<00:31,  5.82it/s]

 81%|█████████████████████████████████████████████████▋           | 798/980 [02:20<00:31,  5.69it/s]

 82%|█████████████████████████████████████████████████▋           | 799/980 [02:20<00:31,  5.72it/s]

 82%|█████████████████████████████████████████████████▊           | 800/980 [02:20<00:31,  5.71it/s]

 82%|█████████████████████████████████████████████████▊           | 801/980 [02:20<00:31,  5.77it/s]

 82%|█████████████████████████████████████████████████▉           | 802/980 [02:20<00:30,  5.76it/s]

 82%|█████████████████████████████████████████████████▉           | 803/980 [02:21<00:30,  5.72it/s]

 82%|██████████████████████████████████████████████████           | 804/980 [02:21<00:30,  5.80it/s]

 82%|██████████████████████████████████████████████████           | 805/980 [02:21<00:30,  5.69it/s]

 82%|██████████████████████████████████████████████████▏          | 806/980 [02:21<00:30,  5.63it/s]

 82%|██████████████████████████████████████████████████▏          | 807/980 [02:21<00:31,  5.53it/s]

 82%|██████████████████████████████████████████████████▎          | 808/980 [02:21<00:30,  5.59it/s]

 83%|██████████████████████████████████████████████████▎          | 809/980 [02:22<00:30,  5.64it/s]

 83%|██████████████████████████████████████████████████▍          | 810/980 [02:22<00:29,  5.72it/s]

 83%|██████████████████████████████████████████████████▍          | 811/980 [02:22<00:29,  5.78it/s]

 83%|██████████████████████████████████████████████████▌          | 812/980 [02:22<00:28,  5.94it/s]

 83%|██████████████████████████████████████████████████▌          | 813/980 [02:22<00:28,  5.95it/s]

 83%|██████████████████████████████████████████████████▋          | 814/980 [02:22<00:27,  5.95it/s]

 83%|██████████████████████████████████████████████████▋          | 815/980 [02:23<00:27,  5.93it/s]

 83%|██████████████████████████████████████████████████▊          | 816/980 [02:23<00:27,  5.91it/s]

 83%|██████████████████████████████████████████████████▊          | 817/980 [02:23<00:27,  5.88it/s]

 83%|██████████████████████████████████████████████████▉          | 818/980 [02:23<00:27,  5.83it/s]

 84%|██████████████████████████████████████████████████▉          | 819/980 [02:23<00:27,  5.81it/s]

 84%|███████████████████████████████████████████████████          | 820/980 [02:23<00:27,  5.85it/s]

 84%|███████████████████████████████████████████████████          | 821/980 [02:24<00:27,  5.72it/s]

 84%|███████████████████████████████████████████████████▏         | 822/980 [02:24<00:28,  5.60it/s]

 84%|███████████████████████████████████████████████████▏         | 823/980 [02:24<00:28,  5.59it/s]

 84%|███████████████████████████████████████████████████▎         | 824/980 [02:24<00:28,  5.57it/s]

 84%|███████████████████████████████████████████████████▎         | 825/980 [02:24<00:27,  5.61it/s]

 84%|███████████████████████████████████████████████████▍         | 826/980 [02:25<00:27,  5.61it/s]

 84%|███████████████████████████████████████████████████▍         | 827/980 [02:25<00:26,  5.69it/s]

 84%|███████████████████████████████████████████████████▌         | 828/980 [02:25<00:26,  5.78it/s]

 85%|███████████████████████████████████████████████████▌         | 829/980 [02:25<00:26,  5.78it/s]

 85%|███████████████████████████████████████████████████▋         | 830/980 [02:25<00:25,  5.80it/s]

 85%|███████████████████████████████████████████████████▋         | 831/980 [02:25<00:25,  5.81it/s]

 85%|███████████████████████████████████████████████████▊         | 832/980 [02:26<00:25,  5.75it/s]

 85%|███████████████████████████████████████████████████▊         | 833/980 [02:26<00:25,  5.86it/s]

 85%|███████████████████████████████████████████████████▉         | 834/980 [02:26<00:25,  5.75it/s]

 85%|███████████████████████████████████████████████████▉         | 835/980 [02:26<00:24,  5.86it/s]

 85%|████████████████████████████████████████████████████         | 836/980 [02:26<00:24,  5.79it/s]

 85%|████████████████████████████████████████████████████         | 837/980 [02:26<00:24,  5.80it/s]

 86%|████████████████████████████████████████████████████▏        | 838/980 [02:27<00:24,  5.74it/s]

 86%|████████████████████████████████████████████████████▏        | 839/980 [02:27<00:24,  5.67it/s]

 86%|████████████████████████████████████████████████████▎        | 840/980 [02:27<00:25,  5.52it/s]

 86%|████████████████████████████████████████████████████▎        | 841/980 [02:27<00:25,  5.42it/s]

 86%|████████████████████████████████████████████████████▍        | 842/980 [02:27<00:24,  5.53it/s]

 86%|████████████████████████████████████████████████████▍        | 843/980 [02:28<00:24,  5.51it/s]

 86%|████████████████████████████████████████████████████▌        | 844/980 [02:28<00:23,  5.70it/s]

 86%|████████████████████████████████████████████████████▌        | 845/980 [02:28<00:23,  5.74it/s]

 86%|████████████████████████████████████████████████████▋        | 846/980 [02:28<00:23,  5.65it/s]

 86%|████████████████████████████████████████████████████▋        | 847/980 [02:28<00:23,  5.69it/s]

 87%|████████████████████████████████████████████████████▊        | 848/980 [02:28<00:23,  5.74it/s]

 87%|████████████████████████████████████████████████████▊        | 849/980 [02:29<00:23,  5.70it/s]

 87%|████████████████████████████████████████████████████▉        | 850/980 [02:29<00:25,  5.02it/s]

 87%|████████████████████████████████████████████████████▉        | 851/980 [02:29<00:24,  5.26it/s]

 87%|█████████████████████████████████████████████████████        | 852/980 [02:29<00:24,  5.26it/s]

 87%|█████████████████████████████████████████████████████        | 853/980 [02:29<00:23,  5.36it/s]

 87%|█████████████████████████████████████████████████████▏       | 854/980 [02:30<00:23,  5.32it/s]

 87%|█████████████████████████████████████████████████████▏       | 855/980 [02:30<00:24,  5.15it/s]

 87%|█████████████████████████████████████████████████████▎       | 856/980 [02:30<00:24,  5.16it/s]

 87%|█████████████████████████████████████████████████████▎       | 857/980 [02:30<00:24,  5.07it/s]

 88%|█████████████████████████████████████████████████████▍       | 858/980 [02:30<00:23,  5.27it/s]

 88%|█████████████████████████████████████████████████████▍       | 859/980 [02:31<00:22,  5.28it/s]

 88%|█████████████████████████████████████████████████████▌       | 860/980 [02:31<00:22,  5.28it/s]

 88%|█████████████████████████████████████████████████████▌       | 861/980 [02:31<00:21,  5.52it/s]

 88%|█████████████████████████████████████████████████████▋       | 862/980 [02:31<00:21,  5.59it/s]

 88%|█████████████████████████████████████████████████████▋       | 863/980 [02:31<00:21,  5.55it/s]

 88%|█████████████████████████████████████████████████████▊       | 864/980 [02:31<00:20,  5.59it/s]

 88%|█████████████████████████████████████████████████████▊       | 865/980 [02:32<00:20,  5.61it/s]

 88%|█████████████████████████████████████████████████████▉       | 866/980 [02:32<00:20,  5.61it/s]

 88%|█████████████████████████████████████████████████████▉       | 867/980 [02:32<00:19,  5.68it/s]

 89%|██████████████████████████████████████████████████████       | 868/980 [02:32<00:19,  5.62it/s]

 89%|██████████████████████████████████████████████████████       | 869/980 [02:32<00:20,  5.49it/s]

 89%|██████████████████████████████████████████████████████▏      | 870/980 [02:32<00:20,  5.47it/s]

 89%|██████████████████████████████████████████████████████▏      | 871/980 [02:33<00:20,  5.39it/s]

 89%|██████████████████████████████████████████████████████▎      | 872/980 [02:33<00:20,  5.32it/s]

 89%|██████████████████████████████████████████████████████▎      | 873/980 [02:33<00:20,  5.32it/s]

 89%|██████████████████████████████████████████████████████▍      | 874/980 [02:33<00:19,  5.47it/s]

 89%|██████████████████████████████████████████████████████▍      | 875/980 [02:33<00:18,  5.54it/s]

 89%|██████████████████████████████████████████████████████▌      | 876/980 [02:34<00:18,  5.53it/s]

 89%|██████████████████████████████████████████████████████▌      | 877/980 [02:34<00:18,  5.60it/s]

 90%|██████████████████████████████████████████████████████▋      | 878/980 [02:34<00:18,  5.65it/s]

 90%|██████████████████████████████████████████████████████▋      | 879/980 [02:34<00:17,  5.67it/s]

 90%|██████████████████████████████████████████████████████▊      | 880/980 [02:34<00:17,  5.69it/s]

 90%|██████████████████████████████████████████████████████▊      | 881/980 [02:34<00:17,  5.70it/s]

 90%|██████████████████████████████████████████████████████▉      | 882/980 [02:35<00:17,  5.60it/s]

 90%|██████████████████████████████████████████████████████▉      | 883/980 [02:35<00:17,  5.53it/s]

 90%|███████████████████████████████████████████████████████      | 884/980 [02:35<00:17,  5.48it/s]

 90%|███████████████████████████████████████████████████████      | 885/980 [02:35<00:17,  5.45it/s]

 90%|███████████████████████████████████████████████████████▏     | 886/980 [02:35<00:17,  5.31it/s]

 91%|███████████████████████████████████████████████████████▏     | 887/980 [02:36<00:17,  5.31it/s]

 91%|███████████████████████████████████████████████████████▎     | 888/980 [02:36<00:17,  5.34it/s]

 91%|███████████████████████████████████████████████████████▎     | 889/980 [02:36<00:16,  5.44it/s]

 91%|███████████████████████████████████████████████████████▍     | 890/980 [02:36<00:16,  5.47it/s]

 91%|███████████████████████████████████████████████████████▍     | 891/980 [02:36<00:16,  5.45it/s]

 91%|███████████████████████████████████████████████████████▌     | 892/980 [02:36<00:15,  5.56it/s]

 91%|███████████████████████████████████████████████████████▌     | 893/980 [02:37<00:15,  5.61it/s]

 91%|███████████████████████████████████████████████████████▋     | 894/980 [02:37<00:15,  5.68it/s]

 91%|███████████████████████████████████████████████████████▋     | 895/980 [02:37<00:15,  5.61it/s]

 91%|███████████████████████████████████████████████████████▊     | 896/980 [02:37<00:14,  5.66it/s]

 92%|███████████████████████████████████████████████████████▊     | 897/980 [02:37<00:14,  5.54it/s]

 92%|███████████████████████████████████████████████████████▉     | 898/980 [02:38<00:14,  5.59it/s]

 92%|███████████████████████████████████████████████████████▉     | 899/980 [02:38<00:14,  5.74it/s]

 92%|████████████████████████████████████████████████████████     | 900/980 [02:38<00:13,  5.72it/s]

 92%|████████████████████████████████████████████████████████     | 901/980 [02:38<00:13,  5.68it/s]

 92%|████████████████████████████████████████████████████████▏    | 902/980 [02:38<00:13,  5.76it/s]

 92%|████████████████████████████████████████████████████████▏    | 903/980 [02:38<00:13,  5.77it/s]

 92%|████████████████████████████████████████████████████████▎    | 904/980 [02:39<00:13,  5.75it/s]

 92%|████████████████████████████████████████████████████████▎    | 905/980 [02:39<00:13,  5.68it/s]

 92%|████████████████████████████████████████████████████████▍    | 906/980 [02:39<00:12,  5.71it/s]

 93%|████████████████████████████████████████████████████████▍    | 907/980 [02:39<00:12,  5.74it/s]

 93%|████████████████████████████████████████████████████████▌    | 908/980 [02:39<00:12,  5.74it/s]

 93%|████████████████████████████████████████████████████████▌    | 909/980 [02:39<00:12,  5.71it/s]

 93%|████████████████████████████████████████████████████████▋    | 910/980 [02:40<00:12,  5.73it/s]

 93%|████████████████████████████████████████████████████████▋    | 911/980 [02:40<00:11,  5.80it/s]

 93%|████████████████████████████████████████████████████████▊    | 912/980 [02:40<00:11,  5.84it/s]

 93%|████████████████████████████████████████████████████████▊    | 913/980 [02:40<00:11,  5.86it/s]

 93%|████████████████████████████████████████████████████████▉    | 914/980 [02:40<00:11,  5.87it/s]

 93%|████████████████████████████████████████████████████████▉    | 915/980 [02:40<00:11,  5.81it/s]

 93%|█████████████████████████████████████████████████████████    | 916/980 [02:41<00:11,  5.77it/s]

 94%|█████████████████████████████████████████████████████████    | 917/980 [02:41<00:10,  5.77it/s]

 94%|█████████████████████████████████████████████████████████▏   | 918/980 [02:41<00:10,  5.75it/s]

 94%|█████████████████████████████████████████████████████████▏   | 919/980 [02:41<00:10,  5.65it/s]

 94%|█████████████████████████████████████████████████████████▎   | 920/980 [02:41<00:10,  5.69it/s]

 94%|█████████████████████████████████████████████████████████▎   | 921/980 [02:42<00:10,  5.69it/s]

 94%|█████████████████████████████████████████████████████████▍   | 922/980 [02:42<00:10,  5.64it/s]

 94%|█████████████████████████████████████████████████████████▍   | 923/980 [02:42<00:10,  5.59it/s]

 94%|█████████████████████████████████████████████████████████▌   | 924/980 [02:42<00:10,  5.50it/s]

 94%|█████████████████████████████████████████████████████████▌   | 925/980 [02:42<00:09,  5.59it/s]

 94%|█████████████████████████████████████████████████████████▋   | 926/980 [02:42<00:09,  5.59it/s]

 95%|█████████████████████████████████████████████████████████▋   | 927/980 [02:43<00:09,  5.66it/s]

 95%|█████████████████████████████████████████████████████████▊   | 928/980 [02:43<00:09,  5.75it/s]

 95%|█████████████████████████████████████████████████████████▊   | 929/980 [02:43<00:08,  5.80it/s]

 95%|█████████████████████████████████████████████████████████▉   | 930/980 [02:43<00:08,  5.84it/s]

 95%|█████████████████████████████████████████████████████████▉   | 931/980 [02:43<00:08,  5.99it/s]

 95%|██████████████████████████████████████████████████████████   | 932/980 [02:43<00:08,  5.91it/s]

 95%|██████████████████████████████████████████████████████████   | 933/980 [02:44<00:08,  5.80it/s]

 95%|██████████████████████████████████████████████████████████▏  | 934/980 [02:44<00:07,  5.78it/s]

 95%|██████████████████████████████████████████████████████████▏  | 935/980 [02:44<00:07,  5.63it/s]

 96%|██████████████████████████████████████████████████████████▎  | 936/980 [02:44<00:07,  5.57it/s]

 96%|██████████████████████████████████████████████████████████▎  | 937/980 [02:44<00:07,  5.59it/s]

 96%|██████████████████████████████████████████████████████████▍  | 938/980 [02:45<00:07,  5.61it/s]

 96%|██████████████████████████████████████████████████████████▍  | 939/980 [02:45<00:07,  5.58it/s]

 96%|██████████████████████████████████████████████████████████▌  | 940/980 [02:45<00:07,  5.64it/s]

 96%|██████████████████████████████████████████████████████████▌  | 941/980 [02:45<00:06,  5.64it/s]

 96%|██████████████████████████████████████████████████████████▋  | 942/980 [02:45<00:06,  5.59it/s]

 96%|██████████████████████████████████████████████████████████▋  | 943/980 [02:45<00:06,  5.65it/s]

 96%|██████████████████████████████████████████████████████████▊  | 944/980 [02:46<00:06,  5.67it/s]

 96%|██████████████████████████████████████████████████████████▊  | 945/980 [02:46<00:06,  5.68it/s]

 97%|██████████████████████████████████████████████████████████▉  | 946/980 [02:46<00:05,  5.75it/s]

 97%|██████████████████████████████████████████████████████████▉  | 947/980 [02:46<00:05,  5.80it/s]

 97%|███████████████████████████████████████████████████████████  | 948/980 [02:46<00:05,  5.79it/s]

 97%|███████████████████████████████████████████████████████████  | 949/980 [02:46<00:05,  5.82it/s]

 97%|███████████████████████████████████████████████████████████▏ | 950/980 [02:47<00:05,  5.80it/s]

 97%|███████████████████████████████████████████████████████████▏ | 951/980 [02:47<00:05,  5.63it/s]

 97%|███████████████████████████████████████████████████████████▎ | 952/980 [02:47<00:05,  5.60it/s]

 97%|███████████████████████████████████████████████████████████▎ | 953/980 [02:47<00:04,  5.56it/s]

 97%|███████████████████████████████████████████████████████████▍ | 954/980 [02:47<00:04,  5.53it/s]

 97%|███████████████████████████████████████████████████████████▍ | 955/980 [02:48<00:04,  5.61it/s]

 98%|███████████████████████████████████████████████████████████▌ | 956/980 [02:48<00:04,  5.76it/s]

 98%|███████████████████████████████████████████████████████████▌ | 957/980 [02:48<00:04,  5.61it/s]

 98%|███████████████████████████████████████████████████████████▋ | 958/980 [02:48<00:03,  5.58it/s]

 98%|███████████████████████████████████████████████████████████▋ | 959/980 [02:48<00:03,  5.71it/s]

 98%|███████████████████████████████████████████████████████████▊ | 960/980 [02:48<00:03,  5.65it/s]

 98%|███████████████████████████████████████████████████████████▊ | 961/980 [02:49<00:03,  5.64it/s]

 98%|███████████████████████████████████████████████████████████▉ | 962/980 [02:49<00:03,  5.63it/s]

 98%|███████████████████████████████████████████████████████████▉ | 963/980 [02:49<00:02,  5.72it/s]

 98%|████████████████████████████████████████████████████████████ | 964/980 [02:49<00:02,  5.73it/s]

 98%|████████████████████████████████████████████████████████████ | 965/980 [02:49<00:02,  5.71it/s]

 99%|████████████████████████████████████████████████████████████▏| 966/980 [02:49<00:02,  5.87it/s]

 99%|████████████████████████████████████████████████████████████▏| 967/980 [02:50<00:02,  5.86it/s]

 99%|████████████████████████████████████████████████████████████▎| 968/980 [02:50<00:02,  5.80it/s]

 99%|████████████████████████████████████████████████████████████▎| 969/980 [02:50<00:01,  5.75it/s]

 99%|████████████████████████████████████████████████████████████▍| 970/980 [02:50<00:01,  5.68it/s]

 99%|████████████████████████████████████████████████████████████▍| 971/980 [02:50<00:01,  5.64it/s]

 99%|████████████████████████████████████████████████████████████▌| 972/980 [02:51<00:01,  5.72it/s]

 99%|████████████████████████████████████████████████████████████▌| 973/980 [02:51<00:01,  5.72it/s]

 99%|████████████████████████████████████████████████████████████▋| 974/980 [02:51<00:01,  5.88it/s]

 99%|████████████████████████████████████████████████████████████▋| 975/980 [02:51<00:00,  5.83it/s]

100%|████████████████████████████████████████████████████████████▊| 976/980 [02:51<00:00,  5.77it/s]

100%|████████████████████████████████████████████████████████████▊| 977/980 [02:51<00:00,  5.78it/s]

100%|████████████████████████████████████████████████████████████▉| 978/980 [02:52<00:00,  5.77it/s]

100%|████████████████████████████████████████████████████████████▉| 979/980 [02:52<00:00,  5.78it/s]

100%|█████████████████████████████████████████████████████████████| 980/980 [02:52<00:00,  5.83it/s]

100%|█████████████████████████████████████████████████████████████| 980/980 [02:52<00:00,  5.68it/s]

'Skipped files: 0'

In [9]:
predictions = pd.concat(predictions, ignore_index=True)
display(predictions.shape)
display(predictions.head())

(671300, 8)

,trait,drug,score,true_class,method,n_top_genes,data,tissue
0,DOID:0050741,DB00215,103099.5,1,gene_based,-1.0,spredixcan-mashr-zscores-Adipose_Subcutaneous-...,Adipose_Subcutaneous
1,DOID:0050741,DB00704,355210.0,1,gene_based,-1.0,spredixcan-mashr-zscores-Adipose_Subcutaneous-...,Adipose_Subcutaneous
2,DOID:0050741,DB00822,388169.0,1,gene_based,-1.0,spredixcan-mashr-zscores-Adipose_Subcutaneous-...,Adipose_Subcutaneous
3,DOID:10283,DB00014,80190.0,1,gene_based,-1.0,spredixcan-mashr-zscores-Adipose_Subcutaneous-...,Adipose_Subcutaneous
4,DOID:10283,DB00175,232448.0,0,gene_based,-1.0,spredixcan-mashr-zscores-Adipose_Subcutaneous-...,Adipose_Subcutaneous

## Validation checks (enforces NB06–NB09 completeness)

In [10]:
assert not predictions.isna().any().any()

_method_counts = predictions['method'].value_counts().reindex(EXPECTED_METHODS)
display(_method_counts)

N_PREDICTIONS = predictions[['drug', 'trait']].drop_duplicates().shape[0]
display(f'Unique drug-disease pairs: {N_PREDICTIONS}')

for method_name, thresholds in METHOD_THRESHOLDS.items():
    expected = N_TISSUES * len(thresholds) * N_PREDICTIONS
    actual = int(_method_counts.loc[method_name])
    assert actual == expected, (
        f'{method_name}: expected {expected}, got {actual} -- '
        f'{_METHOD_SOURCE_NB[method_name]} must be complete '
        f'({N_TISSUES} tissues x {len(thresholds)} thresholds)')

method
gene_based               167825
module_based_archs4      167825
module_based_gtex        167825
module_based_recount2    167825
Name: count, dtype: int64

'Unique drug-disease pairs: 685'

In [11]:
_tmp = predictions.groupby(['method', 'n_top_genes'], observed=True).size().rename('n')
display(_tmp)

for method_name, thresholds in METHOD_THRESHOLDS.items():
    method_counts = _tmp.loc[method_name]
    actual_thresholds = sorted(float(x) for x in method_counts.index)
    assert actual_thresholds == sorted(thresholds), (
        f'{method_name}: expected thresholds {sorted(thresholds)}, '
        f'got {actual_thresholds}')
    assert np.all(method_counts.values == N_TISSUES * N_PREDICTIONS), method_name

method                 n_top_genes
gene_based             -1.0           33565
                        50.0          33565
                        100.0         33565
                        250.0         33565
                        500.0         33565
module_based_archs4    -1.0           33565
                        5.0           33565
                        10.0          33565
                        25.0          33565
                        50.0          33565
module_based_gtex      -1.0           33565
                        5.0           33565
                        10.0          33565
                        25.0          33565
                        50.0          33565
module_based_recount2  -1.0           33565
                        5.0           33565
                        10.0          33565
                        25.0          33565
                        50.0          33565
Name: n, dtype: int64

# Aggregate predictions

1. Average ranks across `n_top_genes` thresholds (per trait, drug, method, tissue).
2. Take the max across tissues (per trait, drug, method).

Matches the PhenoPlier / NB10 aggregation exactly.

In [12]:
def _reduce_mean(x):
    return pd.Series({
        'score': x['score'].mean(),
        'true_class': x['true_class'].unique()[0],
    })


def _reduce_max(x):
    return pd.Series({
        'score': x['score'].max(),
        'true_class': x['true_class'].unique()[0],
    })

In [13]:
predictions_avg = (
    predictions
    .groupby(['trait', 'drug', 'method', 'tissue'], observed=True)
    .apply(_reduce_mean, include_groups=False)
    .dropna()
    .groupby(['trait', 'drug', 'method'], observed=True)
    .apply(_reduce_max, include_groups=False)
    .dropna()
    .sort_index()
    .reset_index()
)

In [14]:
display(predictions_avg.shape)
display(predictions_avg.head())

assert predictions_avg.shape[0] == len(EXPECTED_METHODS) * N_PREDICTIONS
assert predictions_avg.dropna().shape == predictions_avg.shape

# AUROC per method (sanity vs NB10:
# gene ~0.583, archs4 ~0.625, gtex ~0.602, recount2 ~0.612).
from sklearn.metrics import roc_auc_score
display(
    predictions_avg.groupby('method', observed=True)
    .apply(lambda x: roc_auc_score(x['true_class'], x['score']),
           include_groups=False)
    .rename('AUROC'))

(2740, 5)

          trait     drug                 method     score  true_class
0  DOID:0050741  DB00215             gene_based  316134.3         1.0
1  DOID:0050741  DB00215    module_based_archs4  324870.1         1.0
2  DOID:0050741  DB00215      module_based_gtex  349350.5         1.0
3  DOID:0050741  DB00215  module_based_recount2  398655.9         1.0
4  DOID:0050741  DB00704             gene_based  387103.6         1.0

method
gene_based               0.583382
module_based_archs4      0.625419
module_based_gtex        0.602484
module_based_recount2    0.612267
Name: AUROC, dtype: float64

## Save paired predictions

In [15]:
output_file = OUTPUT_DIR / 'predictions_paired.pkl'
display(output_file)
predictions_avg.to_pickle(output_file)

PosixPath('/home/msubirana/Documents/pivlab/clamp-analyses/output/03_model_biology/00_archs4/02_drug_disease_associations/14_signif_test/predictions_paired.pkl')