# 02 - LV traits & pathways tables

Loads SHAP results from `01_LV_importance_kmeans` and produces clean trait / pathway dataframes for every threshold combination.

💡 **Environment:** `clamp-analyses`

In [73]:
import warnings; warnings.filterwarnings('ignore')
import numpy as np
import pandas as pd
from pyprojroot.here import here
import urllib.request

import rpy2.robjects as ro
from rpy2.robjects.conversion import localconverter
from rpy2.robjects import pandas2ri
readRDS = ro.r['readRDS']

# Settings

In [74]:
OUTPUT_DIR   = here('output/gtex_feature_importance_kmeans_binary_shap')
MIN_PURITY   = 0.70
MIN_ACCURACY = 0.95
MIN_N        = 10_000   # min GWAS sample size for traits

pd.set_option('display.max_rows', None)
pd.set_option('display.max_colwidth', None)

# Load data

In [75]:
accuracy_df     = pd.read_csv(OUTPUT_DIR / 'accuracy_summary.tsv',     sep='\t')
shap_results_df = pd.read_csv(OUTPUT_DIR / 'all_shap_positive.tsv',    sep='\t')
cumulative_df   = pd.read_csv(OUTPUT_DIR / 'cumulative_importance.tsv', sep='\t')

print(accuracy_df.shape, shap_results_df.shape, cumulative_df.shape)

(36, 10) (18024, 6) (18024, 5)

In [76]:
phenoplier = pd.read_csv(
    here('data/gtex/phenoplier/gtex-gls-summary-phenomexcan.tsv.gz'),
    sep='\t', compression='gzip', low_memory=False
)[['lv', 'phenotype_desc', 'fdr']].rename(
    columns={'lv': 'LV', 'phenotype_desc': 'phenotype'})
print(phenoplier.shape)

(1668188, 3)

In [77]:
pheno_info_path = here('output/gtex/phenomexcan_simplified_phenotypes_info.tsv.gz')
if not pheno_info_path.exists():
    url = 'https://zenodo.org/records/14941353/files/phenomexcan-phenotypes_info.tsv.gz?download=1'
    urllib.request.urlretrieve(url, pheno_info_path)

pheno_info = pd.read_csv(pheno_info_path, sep='\t', compression='gzip', index_col='pheno_id')
pheno_info['n_eff'] = pheno_info['n'].combine_first(
    pheno_info['n_cases'] + pheno_info['n_controls'])
desc_to_n = (
    pheno_info.dropna(subset=['n_eff'])
    .groupby('description')['n_eff'].max().astype(int).to_dict()
)
print(f'Phenotypes with n: {len(desc_to_n)}')

Phenotypes with n: 4034

In [78]:
rds = readRDS(str(here('output/gtex/CLAMPfull.rds')))
sm  = rds.rx2('summary')
with localconverter(ro.default_converter + pandas2ri.converter):
    sm_vals = ro.conversion.rpy2py(sm)
summary_df = pd.DataFrame(
    data=sm_vals,
    index=sm.rownames if sm.rownames else None,
    columns=sm.colnames if sm.colnames else None,
)
summary_df['pathway'] = summary_df['pathway'].str.replace('C2CP_', '', regex=False)
print(summary_df.shape)

(2377, 7)

# Valid tissues

In [79]:
valid_tissues = (
    accuracy_df[
        (accuracy_df['Mean_Purity']                >= MIN_PURITY) &
        (accuracy_df['Best_Test_Balanced_Accuracy'] >= MIN_ACCURACY)
    ]['Tissue'].sort_values().tolist()
)
print(f'{len(valid_tissues)} valid tissues')
accuracy_df[accuracy_df['Tissue'].isin(valid_tissues)][
    ['Tissue','Mean_Purity','Best_Test_Balanced_Accuracy','LVs_for_80pct','LVs_for_90pct']
].set_index('Tissue').sort_values('Best_Test_Balanced_Accuracy', ascending=False)

25 valid tissues

,Mean_Purity,Best_Test_Balanced_Accuracy,LVs_for_80pct,LVs_for_90pct
Tissue,,,,
Adrenal Gland,1.000000,1.000000,34,63
Esophagus - Mucosa,0.858696,1.000000,40,86
Artery - Aorta,1.000000,1.000000,42,75
Cells - EBV-transformed lymphocytes,1.000000,1.000000,41,65
Cells - Cultured fibroblasts,1.000000,1.000000,40,71
Minor Salivary Gland,0.986395,1.000000,35,70
Lung,0.994280,1.000000,29,57
Liver,0.755853,1.000000,70,128
Heart - Atrial Appendage,0.995204,1.000000,48,93
Whole Blood,1.000000,1.000000,39,69
Stomach,0.996198,1.000000,30,69
Thyroid,0.991643,1.000000,50,94
Spleen,0.839721,1.000000,68,120
Muscle - Skeletal,0.996278,1.000000,47,73
Testis,1.000000,1.000000,46,87
Heart - Left Ventricle,0.961538,0.994023,76,130
Pancreas,0.973214,0.992537,52,106
Adipose - Subcutaneous,0.789864,0.992281,63,110
Nerve - Tibial,0.991961,0.992000,37,73
Pituitary,1.000000,0.991228,50,85
Artery - Tibial,0.986466,0.988722,45,84
Ovary,0.977011,0.985714,46,84
Adipose - Visceral (Omentum),0.805013,0.978788,72,129
Artery - Coronary,0.968037,0.977127,49,81
Prostate,0.986667,0.966667,39,79

# Helper functions

In [80]:
def top_lvs_at_pct(pct):
    """Return {tissue: [lv, ...]} covering `pct`% cumulative SHAP."""
    out = {}
    for tissue in valid_tissues:
        df_t  = cumulative_df[cumulative_df['Tissue'] == tissue].sort_values('Rank')
        mask  = df_t['Cumulative_Percent'] >= pct
        n     = int(df_t.loc[mask, 'Rank'].iloc[0]) if mask.any() else len(df_t)
        out[tissue] = shap_results_df[
            shap_results_df['Tissue'] == tissue
        ]['Feature'].head(n).tolist()
    return out


def trait_table(top_per_tissue, fdr_thresh, use_seen_lvs=True):
    """
    Build traits dataframe.
    Columns: Tissue | LV | shap_rank | phenotype | FDR | n_gwas
    """
    phen = phenoplier[phenoplier['fdr'] < fdr_thresh].copy()
    phen['n_gwas'] = phen['phenotype'].map(desc_to_n)
    phen = phen[phen['n_gwas'] >= MIN_N]

    rows, seen = [], set()
    for tissue in valid_tissues:
        for rank, lv in enumerate(top_per_tissue.get(tissue, []), 1):
            if use_seen_lvs and lv in seen:
                continue
            hits = phen[phen['LV'] == lv].sort_values('fdr')
            for _, r in hits.iterrows():
                rows.append(dict(Tissue=tissue, LV=lv, shap_rank=rank,
                                 phenotype=r['phenotype'],
                                 FDR=r['fdr'], n_gwas=int(r['n_gwas'])))
            if len(hits):
                seen.add(lv)
    return pd.DataFrame(rows)


def pathway_table(top_per_tissue, fdr_thresh, auc_thresh, use_seen_lvs=True):
    """
    Build pathways dataframe.
    Columns: Tissue | LV | shap_rank | pathway | AUC | FDR
    """
    summ = summary_df[
        (summary_df['AUC'] > auc_thresh) &
        (summary_df['FDR'] < fdr_thresh)
    ]
    rows, seen = [], set()
    for tissue in valid_tissues:
        for rank, lv in enumerate(top_per_tissue.get(tissue, []), 1):
            if use_seen_lvs and lv in seen:
                continue
            hits = summ[summ['LV'] == lv].sort_values('FDR')
            for _, r in hits.iterrows():
                rows.append(dict(Tissue=tissue, LV=lv, shap_rank=rank,
                                 pathway=r['pathway'],
                                 AUC=round(float(r['AUC']), 4),
                                 FDR=r['FDR']))
            if len(hits):
                seen.add(lv)
    return pd.DataFrame(rows)


# LV count comparison across cumulative thresholds
lv_counts = pd.DataFrame(
    {f'LVs@{p}%': [len(top_lvs_at_pct(p).get(t, [])) for t in valid_tissues]
     for p in [30, 40, 50, 60, 70]},
    index=valid_tissues
)
lv_counts.index.name = 'Tissue'
display(lv_counts)

,LVs@30%,LVs@40%,LVs@50%,LVs@60%,LVs@70%
Tissue,,,,,
Adipose - Subcutaneous,6,9,15,24,39
Adipose - Visceral (Omentum),7,12,19,30,46
Adrenal Gland,3,4,6,11,20
Artery - Aorta,5,8,12,17,27
Artery - Coronary,6,10,14,22,32
Artery - Tibial,5,8,13,19,28
Cells - Cultured fibroblasts,6,8,12,18,26
Cells - EBV-transformed lymphocytes,5,9,14,20,29
Esophagus - Mucosa,3,4,7,12,22
Heart - Atrial Appendage,4,6,11,18,29
Heart - Left Ventricle,8,12,20,31,48
Liver,8,12,19,28,43
Lung,2,4,7,11,17
Minor Salivary Gland,4,7,11,16,23
Muscle - Skeletal,4,8,13,20,31
Nerve - Tibial,3,6,10,15,23
Ovary,5,8,12,19,29
Pancreas,3,6,11,17,28
Pituitary,6,8,12,18,31
Prostate,3,6,10,15,23
Spleen,8,13,20,29,44
Stomach,3,4,6,11,17
Testis,5,9,13,19,29
Thyroid,2,4,9,17,29
Whole Blood,4,7,11,17,24

# Traits

Each cell below is one combination: `(cumulative %, FDR threshold, seen_lvs)`.

In [81]:
# pct=40%  FDR<0.01  seen_lvs=True
_tpt = top_lvs_at_pct(40)
_df  = trait_table(_tpt, fdr_thresh=0.01, use_seen_lvs=True)
print(f'pct=40%  FDR<0.01  seen_lvs=True  ->  {len(_df)} rows, {_df["Tissue"].nunique()} tissues, {_df["LV"].nunique()} LVs')
_df[['Tissue', 'LV', 'phenotype']]

pct=40%  FDR<0.01  seen_lvs=True  ->  344 rows, 23 tissues, 52 LVs

,Tissue,LV,phenotype
0,Adipose - Subcutaneous,LV378,"Blood clot, DVT, bronchitis, emphysema, asthma, rhinitis, eczema, allergy diagnosed by doctor: Hayfever, allergic rhinitis or eczema"
1,Adipose - Subcutaneous,LV378,Facial ageing
2,Adipose - Subcutaneous,LV378,"Age hay fever, rhinitis or eczema diagnosed"
3,Adipose - Subcutaneous,LV378,"Blood clot, DVT, bronchitis, emphysema, asthma, rhinitis, eczema, allergy diagnosed by doctor: None of the above"
4,Adipose - Visceral (Omentum),LV376,Heel broadband ultrasound attenuation (right)
5,Adipose - Visceral (Omentum),LV376,Heel broadband ultrasound attenuation (left)
6,Adipose - Visceral (Omentum),LV376,"Heel bone mineral density (BMD) T-score, automated (right)"
7,Adipose - Visceral (Omentum),LV376,"Heel quantitative ultrasound index (QUI), direct entry (right)"
8,Adipose - Visceral (Omentum),LV376,Heel bone mineral density (BMD) (right)
9,Adipose - Visceral (Omentum),LV376,Heel bone mineral density (BMD) (left)
10,Adipose - Visceral (Omentum),LV376,"Heel bone mineral density (BMD) T-score, automated (left)"
11,Adipose - Visceral (Omentum),LV376,"Heel quantitative ultrasound index (QUI), direct entry (left)"
12,Adipose - Visceral (Omentum),LV376,Heel bone mineral density (BMD)
13,Adipose - Visceral (Omentum),LV376,"Heel quantitative ultrasound index (QUI), direct entry"
14,Adipose - Visceral (Omentum),LV376,"Heel bone mineral density (BMD) T-score, automated"
15,Adipose - Visceral (Omentum),LV376,"Heel Broadband ultrasound attenuation, direct entry"
16,Adipose - Visceral (Omentum),LV376,Fractured/broken bones in last 5 years
17,Adipose - Visceral (Omentum),LV376,Diagnoses - main ICD10: N81 Female genital prolapse
18,Adipose - Visceral (Omentum),LV376,Palmar fascial fibromatosis [Dupuytren]
19,Adipose - Visceral (Omentum),LV106,"Disorders of gallbladder, biliary tract and pancreas"
20,Adipose - Visceral (Omentum),LV106,malignant neoplasm of male genital organs
21,Adipose - Visceral (Omentum),LV106,Malignant neoplasm of prostate
22,Adipose - Visceral (Omentum),LV106,Diagnoses - main ICD10: K80 Cholelithiasis
23,Adrenal Gland,LV3,Basophill percentage
24,Adrenal Gland,LV183,Mouth/teeth dental problems: Mouth ulcers
25,Adrenal Gland,LV183,Basophill count
26,Adrenal Gland,LV183,"Non-cancer illness code, self-reported: ulcerative colitis"
27,Adrenal Gland,LV183,Diagnoses - main ICD10: D61 Other aplastic anaemias
28,Artery - Aorta,LV145,"Hair colour (natural, before greying): Light brown"
29,Artery - Aorta,LV84,Venous thromboembolism
30,Artery - Aorta,LV84,DVT of lower extremities and pulmonary embolism
31,Artery - Aorta,LV84,DVT of lower extremities
32,Artery - Aorta,LV84,Illnesses of mother: Alzheimer's disease/dementia
33,Artery - Aorta,LV84,"Non-cancer illness code, self-reported: deep venous thrombosis (dvt)"
34,Artery - Aorta,LV84,"Blood clot, DVT, bronchitis, emphysema, asthma, rhinitis, eczema, allergy diagnosed by doctor: Blood clot in the leg (DVT)"
35,Artery - Aorta,LV84,Diagnoses - main ICD10: I80 Phlebitis and thrombophlebitis
36,Artery - Aorta,LV84,Palmar fascial fibromatosis [Dupuytren]
37,Artery - Aorta,LV84,"Blood clot, DVT, bronchitis, emphysema, asthma, rhinitis, eczema, allergy diagnosed by doctor: Blood clot in the lung"
38,Artery - Coronary,LV247,Eye problems/disorders: Glaucoma
39,Artery - Coronary,LV102,Felt loved as a child
40,Artery - Coronary,LV102,Yogurt/ice-cream consumers
41,Artery - Tibial,LV397,Illnesses of mother: Diabetes
42,Artery - Tibial,LV397,"Non-cancer illness code, self-reported: diabetes"
43,Artery - Tibial,LV397,Illnesses of father: Diabetes
44,Artery - Tibial,LV397,Diabetes diagnosed by doctor
45,Artery - Tibial,LV397,"Non-cancer illness code, self-reported: type 2 diabetes"
46,Artery - Tibial,LV397,"Non-cancer illness code, self-reported: gout"
47,Artery - Tibial,LV113,"Non-cancer illness code, self-reported: gout"
48,Artery - Tibial,LV113,Other malignant neoplasms of skin
49,Artery - Tibial,LV113,Diagnoses - main ICD10: C44 Other malignant neoplasms of skin
50,Cells - Cultured fibroblasts,LV111,"Non-cancer illness code, self-reported: rheumatoid arthritis"
51,Cells - Cultured fibroblasts,LV111,Rheumatoid arthritis
52,Cells - Cultured fibroblasts,LV111,Other/unspecified seropositiverheumatoid arthritis
53,Cells - Cultured fibroblasts,LV111,Diagnoses - main ICD10: M06 Other rheumatoid arthritis
54,Cells - Cultured fibroblasts,LV111,Other/unspecified rheumatoid arthritis
55,Cells - Cultured fibroblasts,LV111,Adult-onset Still disease
56,Cells - Cultured fibroblasts,LV111,Diagnoses - main ICD10: M05 Seropositive rheumatoid arthritis
57,Cells - Cultured fibroblasts,LV111,Seropositive rheumatoid arthritis
58,Cells - Cultured fibroblasts,LV111,"Non-cancer illness code, self-reported: multiple sclerosis"
59,Cells - Cultured fibroblasts,LV111,#Polyarthropathies
60,Cells - Cultured fibroblasts,LV180,Diagnoses - main ICD10: M72 Fibroblastic disorders
61,Cells - Cultured fibroblasts,LV180,Fibroblastic disorders
62,Cells - Cultured fibroblasts,LV180,Palmar fascial fibromatosis [Dupuytren]
63,Cells - Cultured fibroblasts,LV180,3mm weak meridian (right)
64,Cells - Cultured fibroblasts,LV180,3mm strong meridian (left)
65,Cells - Cultured fibroblasts,LV180,3mm strong meridian (right)
66,Cells - Cultured fibroblasts,LV180,3mm weak meridian (left)
67,Cells - Cultured fibroblasts,LV180,6mm strong meridian (right)
68,Cells - Cultured fibroblasts,LV180,6mm weak meridian (right)
69,Cells - Cultured fibroblasts,LV180,6mm strong meridian (left)
70,Cells - Cultured fibroblasts,LV180,6mm weak meridian (left)
71,Cells - Cultured fibroblasts,LV336,"Hair colour (natural, before greying): Light brown"
72,Cells - Cultured fibroblasts,LV336,"Hair colour (natural, before greying): Blonde"
73,Cells - Cultured fibroblasts,LV336,"Hair colour (natural, before greying): Black"
74,Cells - Cultured fibroblasts,LV91,"Non-cancer illness code, self-reported: multiple sclerosis"
75,Cells - Cultured fibroblasts,LV91,Mouth/teeth dental problems: Mouth ulcers
76,Cells - Cultured fibroblasts,LV91,"Blood clot, DVT, bronchitis, emphysema, asthma, rhinitis, eczema, allergy diagnosed by doctor: Hayfever, allergic rhinitis or eczema"
77,Cells - Cultured fibroblasts,LV91,Monocyte percentage
78,Cells - Cultured fibroblasts,LV91,Demyelenating diseases of the central nervous system
79,Cells - Cultured fibroblasts,LV91,Diagnoses - main ICD10: G35 Multiple sclerosis
80,Cells - Cultured fibroblasts,LV91,Rheumatoid arthritis
81,Cells - Cultured fibroblasts,LV91,Diagnoses - main ICD10: M06 Other rheumatoid arthritis
82,Cells - Cultured fibroblasts,LV91,Adult-onset Still disease
83,Cells - Cultured fibroblasts,LV91,"Non-cancer illness code, self-reported: rheumatoid arthritis"
84,Cells - Cultured fibroblasts,LV91,Other/unspecified rheumatoid arthritis
85,Cells - Cultured fibroblasts,LV91,Other/unspecified seropositiverheumatoid arthritis
86,Cells - Cultured fibroblasts,LV91,Monocyte count
87,Cells - Cultured fibroblasts,LV91,Seropositive rheumatoid arthritis
88,Cells - Cultured fibroblasts,LV91,"Blood clot, DVT, bronchitis, emphysema, asthma, rhinitis, eczema, allergy diagnosed by doctor: None of the above"
89,Cells - Cultured fibroblasts,LV91,Diagnoses - main ICD10: M05 Seropositive rheumatoid arthritis
90,Cells - Cultured fibroblasts,LV91,Doctor diagnosed hayfever or allergic rhinitis
91,Cells - Cultured fibroblasts,LV91,Diagnoses - main ICD10: K51 Ulcerative colitis
92,Cells - Cultured fibroblasts,LV91,Suggestive for eosinophilic asthma
93,Cells - Cultured fibroblasts,LV91,#Polyarthropathies
94,Cells - Cultured fibroblasts,LV91,"Non-cancer illness code, self-reported: ulcerative colitis"
95,Cells - Cultured fibroblasts,LV91,Diagnoses - main ICD10: J33 Nasal polyp
96,Cells - Cultured fibroblasts,LV91,"Non-cancer illness code, self-reported: hypothyroidism/myxoedema"
97,Cells - EBV-transformed lymphocytes,LV123,"Pulse rate, automated reading"
98,Cells - EBV-transformed lymphocytes,LV123,Pulse rate
99,Cells - EBV-transformed lymphocytes,LV123,QRS duration
100,Cells - EBV-transformed lymphocytes,LV116,"Blood clot, DVT, bronchitis, emphysema, asthma, rhinitis, eczema, allergy diagnosed by doctor: Blood clot in the leg (DVT)"
101,Cells - EBV-transformed lymphocytes,LV116,"Non-cancer illness code, self-reported: deep venous thrombosis (dvt)"
102,Cells - EBV-transformed lymphocytes,LV116,Diagnoses - main ICD10: I80 Phlebitis and thrombophlebitis
103,Cells - EBV-transformed lymphocytes,LV116,DVT of lower extremities
104,Cells - EBV-transformed lymphocytes,LV244,Number of cigarettes currently smoked daily (current cigarette smokers)
105,Cells - EBV-transformed lymphocytes,LV406,Number of cigarettes previously smoked daily
106,Esophagus - Mucosa,LV8,Heel broadband ultrasound attenuation (left)
107,Esophagus - Mucosa,LV8,Heel broadband ultrasound attenuation (right)
108,Esophagus - Mucosa,LV8,Fractured/broken bones in last 5 years
109,Esophagus - Mucosa,LV8,Primary_lymphoid and hematopoietic malignant neoplasms
110,Heart - Atrial Appendage,LV282,Job SOC coding: Medical secretaries
111,Heart - Atrial Appendage,LV282,"Non-cancer illness code, self-reported: gout"
112,Heart - Atrial Appendage,LV139,"Cancer code, self-reported: multiple myeloma"
113,Heart - Left Ventricle,LV248,"Blood clot, DVT, bronchitis, emphysema, asthma, rhinitis, eczema, allergy diagnosed by doctor: None of the above"
114,Heart - Left Ventricle,LV248,"Blood clot, DVT, bronchitis, emphysema, asthma, rhinitis, eczema, allergy diagnosed by doctor: Hayfever, allergic rhinitis or eczema"
115,Heart - Left Ventricle,LV248,Age asthma diagnosed
116,Heart - Left Ventricle,LV248,Mouth/teeth dental problems: Mouth ulcers
117,Heart - Left Ventricle,LV363,Basophill percentage
118,Heart - Left Ventricle,LV363,Eosinophill count
119,Heart - Left Ventricle,LV363,Lymphocyte count
120,Heart - Left Ventricle,LV363,Eosinophill percentage
121,Heart - Left Ventricle,LV363,"Medication for cholesterol, blood pressure or diabetes: Blood pressure medication"
122,Heart - Left Ventricle,LV363,Basophill count
123,Heart - Left Ventricle,LV44,Diagnoses - main ICD10: K40 Inguinal hernia
124,Liver,LV50,"Non-cancer illness code, self-reported: gout"
125,Liver,LV21,"Non-cancer illness code, self-reported: high cholesterol"
126,Liver,LV21,"Non-cancer illness code, self-reported: cholelithiasis/gall stones"
127,Liver,LV21,"Medication for cholesterol, blood pressure or diabetes: Cholesterol lowering medication"
128,Liver,LV21,Diagnoses - main ICD10: K80 Cholelithiasis
129,Liver,LV21,"Medication for cholesterol, blood pressure, diabetes, or take exogenous hormones: Cholesterol lowering medication"
130,Liver,LV21,"Disorders of gallbladder, biliary tract and pancreas"
131,Liver,LV366,3mm weak meridian (right)
132,Liver,LV366,3mm strong meridian (right)
133,Liver,LV366,3mm strong meridian (left)
134,Liver,LV366,3mm weak meridian (left)
135,Liver,LV366,Heel broadband ultrasound attenuation (right)
136,Liver,LV366,Heel broadband ultrasound attenuation (left)
137,Liver,LV366,6mm strong meridian (right)
138,Liver,LV366,6mm strong meridian (left)
139,Liver,LV366,6mm weak meridian (left)
140,Liver,LV366,6mm weak meridian (right)
141,Liver,LV366,Diagnoses - main ICD10: M72 Fibroblastic disorders
142,Liver,LV366,Fibroblastic disorders
143,Liver,LV366,Palmar fascial fibromatosis [Dupuytren]
144,Liver,LV366,Age started wearing glasses or contact lenses
145,Liver,LV314,Illnesses of mother: Alzheimer's disease/dementia
146,Liver,LV314,"Non-cancer illness code, self-reported: high cholesterol"
147,Lung,LV26,Mouth/teeth dental problems: Mouth ulcers
148,Lung,LV26,"Diagnoses - main ICD10: R60 Oedema, not elsewhere classified"
149,Minor Salivary Gland,LV58,Diagnoses - main ICD10: E83 Disorders of mineral metabolism
150,Minor Salivary Gland,LV58,Lymphocyte percentage
151,Minor Salivary Gland,LV58,Neutrophill percentage
152,Minor Salivary Gland,LV324,"Non-cancer illness code, self-reported: malabsorption/coeliac disease"
153,Minor Salivary Gland,LV324,"Non-cancer illness code, self-reported: sarcoidosis"
154,Minor Salivary Gland,LV324,"Never eat eggs, dairy, wheat, sugar: Wheat products"
155,Minor Salivary Gland,LV324,Coeliac disease
156,Minor Salivary Gland,LV324,Diagnoses - main ICD10: K90 Intestinal malabsorption
157,Minor Salivary Gland,LV324,"Non-cancer illness code, self-reported: hyperthyroidism/thyrotoxicosis"
158,Minor Salivary Gland,LV324,"Blood clot, DVT, bronchitis, emphysema, asthma, rhinitis, eczema, allergy diagnosed by doctor: Asthma"
159,Minor Salivary Gland,LV324,"Non-cancer illness code, self-reported: asthma"
160,Minor Salivary Gland,LV324,Bread type: Other type of bread
161,Minor Salivary Gland,LV324,Other diseases of the digestive system
162,Minor Salivary Gland,LV324,Doctor diagnosed sarcoidosis
163,Minor Salivary Gland,LV324,"Non-cancer illness code, self-reported: systemic lupus erythematosis/sle"
164,Minor Salivary Gland,LV324,Eosinophill count
165,Minor Salivary Gland,LV324,"Medication for cholesterol, blood pressure, diabetes, or take exogenous hormones: Insulin"
166,Minor Salivary Gland,LV324,Type of special diet followed: Gluten-free
167,Minor Salivary Gland,LV324,Diagnoses - main ICD10: R31 Unspecified haematuria
168,Minor Salivary Gland,LV324,"Non-cancer illness code, self-reported: hypothyroidism/myxoedema"
169,Minor Salivary Gland,LV324,"Medication for cholesterol, blood pressure or diabetes: Insulin"
170,Minor Salivary Gland,LV324,Started insulin within one year diagnosis of diabetes
171,Minor Salivary Gland,LV324,"Blood clot, DVT, bronchitis, emphysema, asthma, rhinitis, eczema, allergy diagnosed by doctor: None of the above"
172,Minor Salivary Gland,LV324,"Cereal type: Other (e.g. Cornflakes, Frosties)"
173,Minor Salivary Gland,LV324,"Non-cancer illness code, self-reported: type 1 diabetes"
174,Minor Salivary Gland,LV324,"Non-cancer illness code, self-reported: adrenocortical insufficiency/addison's disease"
175,Minor Salivary Gland,LV324,Doctor diagnosed asthma
176,Minor Salivary Gland,LV324,Age diabetes diagnosed
177,Minor Salivary Gland,LV324,White blood cell (leukocyte) count
178,Minor Salivary Gland,LV324,Lymphocyte count
179,Minor Salivary Gland,LV324,"Blood clot, DVT, bronchitis, emphysema, asthma, rhinitis, eczema, allergy diagnosed by doctor: Hayfever, allergic rhinitis or eczema"
180,Minor Salivary Gland,LV324,Type 1 diabetes
181,Minor Salivary Gland,LV324,Diagnoses - main ICD10: E10 Insulin-dependent diabetes mellitus
182,Minor Salivary Gland,LV324,Doctor diagnosed hayfever or allergic rhinitis
183,Minor Salivary Gland,LV324,"Non-cancer illness code, self-reported: psoriasis"
184,Minor Salivary Gland,LV324,Type 1 diabetes with ophthalmic complications
185,Minor Salivary Gland,LV324,Unclassified diabetic retinopathy
186,Minor Salivary Gland,LV324,"Non-cancer illness code, self-reported: sjogren's syndrome/sicca syndrome"
187,Minor Salivary Gland,LV324,Diabetic ketoacidosis
188,Minor Salivary Gland,LV324,"Non-cancer illness code, self-reported: hayfever/allergic rhinitis"
189,Minor Salivary Gland,LV324,Eosinophill percentage
190,Minor Salivary Gland,LV324,Other serious medical condition/disability diagnosed by doctor
191,Minor Salivary Gland,LV324,Type 1 diabetes with ketoacidosis
192,Minor Salivary Gland,LV324,Illnesses of siblings: Diabetes
193,Minor Salivary Gland,LV324,Diagnoses - main ICD10: E05 Thyrotoxicosis [hyperthyroidism]
194,Minor Salivary Gland,LV324,Thyrotoxicosis
195,Minor Salivary Gland,LV324,Thyrotoxicosis with diffuse goitr
196,Minor Salivary Gland,LV324,Diagnoses - main ICD10: N40 Hyperplasia of prostate
197,Minor Salivary Gland,LV324,Diseases of the blood and blood-forming organs and certain disorders involving the immune mechanism
198,Minor Salivary Gland,LV324,"Endocrine, nutritional and metabolic diseases"
199,Minor Salivary Gland,LV324,"Long-standing illness, disability or infirmity"
200,Minor Salivary Gland,LV324,"Non-cancer illness code, self-reported: polymyalgia rheumatica"
201,Minor Salivary Gland,LV324,"Never eat eggs, dairy, wheat, sugar: I eat all of the above"
202,Minor Salivary Gland,LV324,Why stopped smoking: Health precaution
203,Minor Salivary Gland,LV324,Eye problems/disorders: Diabetes related eye disease
204,Minor Salivary Gland,LV324,Mouth/teeth dental problems: Dentures
205,Minor Salivary Gland,LV324,"Non-cancer illness code, self-reported: psoriatic arthropathy"
206,Minor Salivary Gland,LV324,Other and unspecified anaemias
207,Minor Salivary Gland,LV324,Other anaemias
208,Minor Salivary Gland,LV324,Diagnoses - main ICD10: D64 Other anaemias
209,Minor Salivary Gland,LV324,"Non-cancer illness code, self-reported: ulcerative colitis"
210,Minor Salivary Gland,LV324,"Non-cancer illness code, self-reported: multiple sclerosis"
211,Minor Salivary Gland,LV324,"Seen a psychiatrist for nerves, anxiety, tension or depression"
212,Minor Salivary Gland,LV324,Lymphomas
213,Minor Salivary Gland,LV324,Diagnoses - main ICD10: K51 Ulcerative colitis
214,Minor Salivary Gland,LV324,Diabetes diagnosed by doctor
215,Minor Salivary Gland,LV324,Diagnoses - main ICD10: G35 Multiple sclerosis
216,Minor Salivary Gland,LV324,Neutrophill count
217,Minor Salivary Gland,LV324,"Medication for pain relief, constipation, heartburn: None of the above"
218,Minor Salivary Gland,LV324,"Non-cancer illness code, self-reported: ankylosing spondylitis"
219,Minor Salivary Gland,LV324,Demyelenating diseases of the central nervous system
220,Minor Salivary Gland,LV324,Wheeze or whistling in the chest in last year
221,Minor Salivary Gland,LV324,Haemoglobin concentration
222,Minor Salivary Gland,LV324,Why stopped smoking: None of the above
223,Minor Salivary Gland,LV324,Taking other prescription medications
224,Minor Salivary Gland,LV324,"Ulcerative colitis, NAS"
225,Minor Salivary Gland,LV324,Type 1 diabetes without complications
226,Minor Salivary Gland,LV324,Hot drink temperature
227,Minor Salivary Gland,LV324,Number of fluid intelligence questions attempted within time limit
228,Minor Salivary Gland,LV324,"Non-cancer illness code, self-reported: rheumatoid arthritis"
229,Minor Salivary Gland,LV324,Diagnoses - main ICD10: E11 Non-insulin-dependent diabetes mellitus
230,Minor Salivary Gland,LV324,Psoriasis
231,Minor Salivary Gland,LV324,Diagnoses - main ICD10: L40 Psoriasis
232,Minor Salivary Gland,LV324,Diagnoses - main ICD10: C82 Follicular [nodular] non-Hodgkin's lymphoma
233,Minor Salivary Gland,LV324,Age hayfever or allergic rhinitis diagnosed by doctor
234,Minor Salivary Gland,LV324,Diagnoses - main ICD10: J33 Nasal polyp
235,Minor Salivary Gland,LV324,"Diagnoses - main ICD10: A63 Other predominantly sexually transmitted diseases, not elsewhere classified"
236,Minor Salivary Gland,LV324,"Diastolic blood pressure, automated reading"
237,Minor Salivary Gland,LV324,Follicular lymphoma
238,Minor Salivary Gland,LV324,"Medication for pain relief, constipation, heartburn: Paracetamol"
239,Minor Salivary Gland,LV324,Adult-onset Still disease
240,Minor Salivary Gland,LV324,Suggestive for eosinophilic asthma
241,Minor Salivary Gland,LV324,Diagnoses - main ICD10: M06 Other rheumatoid arthritis
242,Minor Salivary Gland,LV324,Other/unspecified rheumatoid arthritis
243,Minor Salivary Gland,LV324,Diseases of the genitourinary system
244,Minor Salivary Gland,LV324,Rheumatoid arthritis
245,Minor Salivary Gland,LV324,Used an inhaler for chest within last hour
246,Minor Salivary Gland,LV324,Type 2 diabetes
247,Minor Salivary Gland,LV324,Monocyte count
248,Minor Salivary Gland,LV324,"Major dietary changes in the last 5 years: Yes, because of illness"
249,Minor Salivary Gland,LV324,Oily fish intake
250,Minor Salivary Gland,LV324,Mouth/teeth dental problems: Mouth ulcers
251,Minor Salivary Gland,LV324,"COPD, early/later onset"
252,Minor Salivary Gland,LV324,Diabetic hypoglycemia
253,Minor Salivary Gland,LV324,Diagnoses - main ICD10: E14 Unspecified diabetes mellitus
254,Minor Salivary Gland,LV324,"Non-cancer illness code, self-reported: diabetes"

In [82]:
# pct=40%  FDR<0.01  seen_lvs=False
_tpt = top_lvs_at_pct(40)
_df  = trait_table(_tpt, fdr_thresh=0.01, use_seen_lvs=False)
print(f'pct=40%  FDR<0.01  seen_lvs=False  ->  {len(_df)} rows, {_df["Tissue"].nunique()} tissues, {_df["LV"].nunique()} LVs')
_df[['Tissue', 'LV', 'phenotype']]

pct=40%  FDR<0.01  seen_lvs=False  ->  535 rows, 25 tissues, 52 LVs

,Tissue,LV,phenotype
0,Adipose - Subcutaneous,LV378,"Blood clot, DVT, bronchitis, emphysema, asthma, rhinitis, eczema, allergy diagnosed by doctor: Hayfever, allergic rhinitis or eczema"
1,Adipose - Subcutaneous,LV378,Facial ageing
2,Adipose - Subcutaneous,LV378,"Age hay fever, rhinitis or eczema diagnosed"
3,Adipose - Subcutaneous,LV378,"Blood clot, DVT, bronchitis, emphysema, asthma, rhinitis, eczema, allergy diagnosed by doctor: None of the above"
4,Adipose - Visceral (Omentum),LV376,Heel broadband ultrasound attenuation (right)
5,Adipose - Visceral (Omentum),LV376,Heel broadband ultrasound attenuation (left)
6,Adipose - Visceral (Omentum),LV376,"Heel bone mineral density (BMD) T-score, automated (right)"
7,Adipose - Visceral (Omentum),LV376,"Heel quantitative ultrasound index (QUI), direct entry (right)"
8,Adipose - Visceral (Omentum),LV376,Heel bone mineral density (BMD) (right)
9,Adipose - Visceral (Omentum),LV376,Heel bone mineral density (BMD) (left)
10,Adipose - Visceral (Omentum),LV376,"Heel bone mineral density (BMD) T-score, automated (left)"
11,Adipose - Visceral (Omentum),LV376,"Heel quantitative ultrasound index (QUI), direct entry (left)"
12,Adipose - Visceral (Omentum),LV376,Heel bone mineral density (BMD)
13,Adipose - Visceral (Omentum),LV376,"Heel quantitative ultrasound index (QUI), direct entry"
14,Adipose - Visceral (Omentum),LV376,"Heel bone mineral density (BMD) T-score, automated"
15,Adipose - Visceral (Omentum),LV376,"Heel Broadband ultrasound attenuation, direct entry"
16,Adipose - Visceral (Omentum),LV376,Fractured/broken bones in last 5 years
17,Adipose - Visceral (Omentum),LV376,Diagnoses - main ICD10: N81 Female genital prolapse
18,Adipose - Visceral (Omentum),LV376,Palmar fascial fibromatosis [Dupuytren]
19,Adipose - Visceral (Omentum),LV106,"Disorders of gallbladder, biliary tract and pancreas"
20,Adipose - Visceral (Omentum),LV106,malignant neoplasm of male genital organs
21,Adipose - Visceral (Omentum),LV106,Malignant neoplasm of prostate
22,Adipose - Visceral (Omentum),LV106,Diagnoses - main ICD10: K80 Cholelithiasis
23,Adrenal Gland,LV3,Basophill percentage
24,Adrenal Gland,LV183,Mouth/teeth dental problems: Mouth ulcers
25,Adrenal Gland,LV183,Basophill count
26,Adrenal Gland,LV183,"Non-cancer illness code, self-reported: ulcerative colitis"
27,Adrenal Gland,LV183,Diagnoses - main ICD10: D61 Other aplastic anaemias
28,Artery - Aorta,LV145,"Hair colour (natural, before greying): Light brown"
29,Artery - Aorta,LV84,Venous thromboembolism
30,Artery - Aorta,LV84,DVT of lower extremities and pulmonary embolism
31,Artery - Aorta,LV84,DVT of lower extremities
32,Artery - Aorta,LV84,Illnesses of mother: Alzheimer's disease/dementia
33,Artery - Aorta,LV84,"Non-cancer illness code, self-reported: deep venous thrombosis (dvt)"
34,Artery - Aorta,LV84,"Blood clot, DVT, bronchitis, emphysema, asthma, rhinitis, eczema, allergy diagnosed by doctor: Blood clot in the leg (DVT)"
35,Artery - Aorta,LV84,Diagnoses - main ICD10: I80 Phlebitis and thrombophlebitis
36,Artery - Aorta,LV84,Palmar fascial fibromatosis [Dupuytren]
37,Artery - Aorta,LV84,"Blood clot, DVT, bronchitis, emphysema, asthma, rhinitis, eczema, allergy diagnosed by doctor: Blood clot in the lung"
38,Artery - Coronary,LV247,Eye problems/disorders: Glaucoma
39,Artery - Coronary,LV102,Felt loved as a child
40,Artery - Coronary,LV102,Yogurt/ice-cream consumers
41,Artery - Coronary,LV106,"Disorders of gallbladder, biliary tract and pancreas"
42,Artery - Coronary,LV106,malignant neoplasm of male genital organs
43,Artery - Coronary,LV106,Malignant neoplasm of prostate
44,Artery - Coronary,LV106,Diagnoses - main ICD10: K80 Cholelithiasis
45,Artery - Coronary,LV84,Venous thromboembolism
46,Artery - Coronary,LV84,DVT of lower extremities and pulmonary embolism
47,Artery - Coronary,LV84,DVT of lower extremities
48,Artery - Coronary,LV84,Illnesses of mother: Alzheimer's disease/dementia
49,Artery - Coronary,LV84,"Non-cancer illness code, self-reported: deep venous thrombosis (dvt)"
50,Artery - Coronary,LV84,"Blood clot, DVT, bronchitis, emphysema, asthma, rhinitis, eczema, allergy diagnosed by doctor: Blood clot in the leg (DVT)"
51,Artery - Coronary,LV84,Diagnoses - main ICD10: I80 Phlebitis and thrombophlebitis
52,Artery - Coronary,LV84,Palmar fascial fibromatosis [Dupuytren]
53,Artery - Coronary,LV84,"Blood clot, DVT, bronchitis, emphysema, asthma, rhinitis, eczema, allergy diagnosed by doctor: Blood clot in the lung"
54,Artery - Tibial,LV397,Illnesses of mother: Diabetes
55,Artery - Tibial,LV397,"Non-cancer illness code, self-reported: diabetes"
56,Artery - Tibial,LV397,Illnesses of father: Diabetes
57,Artery - Tibial,LV397,Diabetes diagnosed by doctor
58,Artery - Tibial,LV397,"Non-cancer illness code, self-reported: type 2 diabetes"
59,Artery - Tibial,LV397,"Non-cancer illness code, self-reported: gout"
60,Artery - Tibial,LV102,Felt loved as a child
61,Artery - Tibial,LV102,Yogurt/ice-cream consumers
62,Artery - Tibial,LV84,Venous thromboembolism
63,Artery - Tibial,LV84,DVT of lower extremities and pulmonary embolism
64,Artery - Tibial,LV84,DVT of lower extremities
65,Artery - Tibial,LV84,Illnesses of mother: Alzheimer's disease/dementia
66,Artery - Tibial,LV84,"Non-cancer illness code, self-reported: deep venous thrombosis (dvt)"
67,Artery - Tibial,LV84,"Blood clot, DVT, bronchitis, emphysema, asthma, rhinitis, eczema, allergy diagnosed by doctor: Blood clot in the leg (DVT)"
68,Artery - Tibial,LV84,Diagnoses - main ICD10: I80 Phlebitis and thrombophlebitis
69,Artery - Tibial,LV84,Palmar fascial fibromatosis [Dupuytren]
70,Artery - Tibial,LV84,"Blood clot, DVT, bronchitis, emphysema, asthma, rhinitis, eczema, allergy diagnosed by doctor: Blood clot in the lung"
71,Artery - Tibial,LV113,"Non-cancer illness code, self-reported: gout"
72,Artery - Tibial,LV113,Other malignant neoplasms of skin
73,Artery - Tibial,LV113,Diagnoses - main ICD10: C44 Other malignant neoplasms of skin
74,Cells - Cultured fibroblasts,LV111,"Non-cancer illness code, self-reported: rheumatoid arthritis"
75,Cells - Cultured fibroblasts,LV111,Rheumatoid arthritis
76,Cells - Cultured fibroblasts,LV111,Other/unspecified seropositiverheumatoid arthritis
77,Cells - Cultured fibroblasts,LV111,Diagnoses - main ICD10: M06 Other rheumatoid arthritis
78,Cells - Cultured fibroblasts,LV111,Other/unspecified rheumatoid arthritis
79,Cells - Cultured fibroblasts,LV111,Adult-onset Still disease
80,Cells - Cultured fibroblasts,LV111,Diagnoses - main ICD10: M05 Seropositive rheumatoid arthritis
81,Cells - Cultured fibroblasts,LV111,Seropositive rheumatoid arthritis
82,Cells - Cultured fibroblasts,LV111,"Non-cancer illness code, self-reported: multiple sclerosis"
83,Cells - Cultured fibroblasts,LV111,#Polyarthropathies
84,Cells - Cultured fibroblasts,LV180,Diagnoses - main ICD10: M72 Fibroblastic disorders
85,Cells - Cultured fibroblasts,LV180,Fibroblastic disorders
86,Cells - Cultured fibroblasts,LV180,Palmar fascial fibromatosis [Dupuytren]
87,Cells - Cultured fibroblasts,LV180,3mm weak meridian (right)
88,Cells - Cultured fibroblasts,LV180,3mm strong meridian (left)
89,Cells - Cultured fibroblasts,LV180,3mm strong meridian (right)
90,Cells - Cultured fibroblasts,LV180,3mm weak meridian (left)
91,Cells - Cultured fibroblasts,LV180,6mm strong meridian (right)
92,Cells - Cultured fibroblasts,LV180,6mm weak meridian (right)
93,Cells - Cultured fibroblasts,LV180,6mm strong meridian (left)
94,Cells - Cultured fibroblasts,LV180,6mm weak meridian (left)
95,Cells - Cultured fibroblasts,LV336,"Hair colour (natural, before greying): Light brown"
96,Cells - Cultured fibroblasts,LV336,"Hair colour (natural, before greying): Blonde"
97,Cells - Cultured fibroblasts,LV336,"Hair colour (natural, before greying): Black"
98,Cells - Cultured fibroblasts,LV84,Venous thromboembolism
99,Cells - Cultured fibroblasts,LV84,DVT of lower extremities and pulmonary embolism
100,Cells - Cultured fibroblasts,LV84,DVT of lower extremities
101,Cells - Cultured fibroblasts,LV84,Illnesses of mother: Alzheimer's disease/dementia
102,Cells - Cultured fibroblasts,LV84,"Non-cancer illness code, self-reported: deep venous thrombosis (dvt)"
103,Cells - Cultured fibroblasts,LV84,"Blood clot, DVT, bronchitis, emphysema, asthma, rhinitis, eczema, allergy diagnosed by doctor: Blood clot in the leg (DVT)"
104,Cells - Cultured fibroblasts,LV84,Diagnoses - main ICD10: I80 Phlebitis and thrombophlebitis
105,Cells - Cultured fibroblasts,LV84,Palmar fascial fibromatosis [Dupuytren]
106,Cells - Cultured fibroblasts,LV84,"Blood clot, DVT, bronchitis, emphysema, asthma, rhinitis, eczema, allergy diagnosed by doctor: Blood clot in the lung"
107,Cells - Cultured fibroblasts,LV91,"Non-cancer illness code, self-reported: multiple sclerosis"
108,Cells - Cultured fibroblasts,LV91,Mouth/teeth dental problems: Mouth ulcers
109,Cells - Cultured fibroblasts,LV91,"Blood clot, DVT, bronchitis, emphysema, asthma, rhinitis, eczema, allergy diagnosed by doctor: Hayfever, allergic rhinitis or eczema"
110,Cells - Cultured fibroblasts,LV91,Monocyte percentage
111,Cells - Cultured fibroblasts,LV91,Demyelenating diseases of the central nervous system
112,Cells - Cultured fibroblasts,LV91,Diagnoses - main ICD10: G35 Multiple sclerosis
113,Cells - Cultured fibroblasts,LV91,Rheumatoid arthritis
114,Cells - Cultured fibroblasts,LV91,Diagnoses - main ICD10: M06 Other rheumatoid arthritis
115,Cells - Cultured fibroblasts,LV91,Adult-onset Still disease
116,Cells - Cultured fibroblasts,LV91,"Non-cancer illness code, self-reported: rheumatoid arthritis"
117,Cells - Cultured fibroblasts,LV91,Other/unspecified rheumatoid arthritis
118,Cells - Cultured fibroblasts,LV91,Other/unspecified seropositiverheumatoid arthritis
119,Cells - Cultured fibroblasts,LV91,Monocyte count
120,Cells - Cultured fibroblasts,LV91,Seropositive rheumatoid arthritis
121,Cells - Cultured fibroblasts,LV91,"Blood clot, DVT, bronchitis, emphysema, asthma, rhinitis, eczema, allergy diagnosed by doctor: None of the above"
122,Cells - Cultured fibroblasts,LV91,Diagnoses - main ICD10: M05 Seropositive rheumatoid arthritis
123,Cells - Cultured fibroblasts,LV91,Doctor diagnosed hayfever or allergic rhinitis
124,Cells - Cultured fibroblasts,LV91,Diagnoses - main ICD10: K51 Ulcerative colitis
125,Cells - Cultured fibroblasts,LV91,Suggestive for eosinophilic asthma
126,Cells - Cultured fibroblasts,LV91,#Polyarthropathies
127,Cells - Cultured fibroblasts,LV91,"Non-cancer illness code, self-reported: ulcerative colitis"
128,Cells - Cultured fibroblasts,LV91,Diagnoses - main ICD10: J33 Nasal polyp
129,Cells - Cultured fibroblasts,LV91,"Non-cancer illness code, self-reported: hypothyroidism/myxoedema"
130,Cells - EBV-transformed lymphocytes,LV123,"Pulse rate, automated reading"
131,Cells - EBV-transformed lymphocytes,LV123,Pulse rate
132,Cells - EBV-transformed lymphocytes,LV123,QRS duration
133,Cells - EBV-transformed lymphocytes,LV116,"Blood clot, DVT, bronchitis, emphysema, asthma, rhinitis, eczema, allergy diagnosed by doctor: Blood clot in the leg (DVT)"
134,Cells - EBV-transformed lymphocytes,LV116,"Non-cancer illness code, self-reported: deep venous thrombosis (dvt)"
135,Cells - EBV-transformed lymphocytes,LV116,Diagnoses - main ICD10: I80 Phlebitis and thrombophlebitis
136,Cells - EBV-transformed lymphocytes,LV116,DVT of lower extremities
137,Cells - EBV-transformed lymphocytes,LV244,Number of cigarettes currently smoked daily (current cigarette smokers)
138,Cells - EBV-transformed lymphocytes,LV406,Number of cigarettes previously smoked daily
139,Esophagus - Mucosa,LV84,Venous thromboembolism
140,Esophagus - Mucosa,LV84,DVT of lower extremities and pulmonary embolism
141,Esophagus - Mucosa,LV84,DVT of lower extremities
142,Esophagus - Mucosa,LV84,Illnesses of mother: Alzheimer's disease/dementia
143,Esophagus - Mucosa,LV84,"Non-cancer illness code, self-reported: deep venous thrombosis (dvt)"
144,Esophagus - Mucosa,LV84,"Blood clot, DVT, bronchitis, emphysema, asthma, rhinitis, eczema, allergy diagnosed by doctor: Blood clot in the leg (DVT)"
145,Esophagus - Mucosa,LV84,Diagnoses - main ICD10: I80 Phlebitis and thrombophlebitis
146,Esophagus - Mucosa,LV84,Palmar fascial fibromatosis [Dupuytren]
147,Esophagus - Mucosa,LV84,"Blood clot, DVT, bronchitis, emphysema, asthma, rhinitis, eczema, allergy diagnosed by doctor: Blood clot in the lung"
148,Esophagus - Mucosa,LV8,Heel broadband ultrasound attenuation (left)
149,Esophagus - Mucosa,LV8,Heel broadband ultrasound attenuation (right)
150,Esophagus - Mucosa,LV8,Fractured/broken bones in last 5 years
151,Esophagus - Mucosa,LV8,Primary_lymphoid and hematopoietic malignant neoplasms
152,Esophagus - Mucosa,LV397,Illnesses of mother: Diabetes
153,Esophagus - Mucosa,LV397,"Non-cancer illness code, self-reported: diabetes"
154,Esophagus - Mucosa,LV397,Illnesses of father: Diabetes
155,Esophagus - Mucosa,LV397,Diabetes diagnosed by doctor
156,Esophagus - Mucosa,LV397,"Non-cancer illness code, self-reported: type 2 diabetes"
157,Esophagus - Mucosa,LV397,"Non-cancer illness code, self-reported: gout"
158,Heart - Atrial Appendage,LV282,Job SOC coding: Medical secretaries
159,Heart - Atrial Appendage,LV282,"Non-cancer illness code, self-reported: gout"
160,Heart - Atrial Appendage,LV139,"Cancer code, self-reported: multiple myeloma"
161,Heart - Left Ventricle,LV248,"Blood clot, DVT, bronchitis, emphysema, asthma, rhinitis, eczema, allergy diagnosed by doctor: None of the above"
162,Heart - Left Ventricle,LV248,"Blood clot, DVT, bronchitis, emphysema, asthma, rhinitis, eczema, allergy diagnosed by doctor: Hayfever, allergic rhinitis or eczema"
163,Heart - Left Ventricle,LV248,Age asthma diagnosed
164,Heart - Left Ventricle,LV248,Mouth/teeth dental problems: Mouth ulcers
165,Heart - Left Ventricle,LV363,Basophill percentage
166,Heart - Left Ventricle,LV363,Eosinophill count
167,Heart - Left Ventricle,LV363,Lymphocyte count
168,Heart - Left Ventricle,LV363,Eosinophill percentage
169,Heart - Left Ventricle,LV363,"Medication for cholesterol, blood pressure or diabetes: Blood pressure medication"
170,Heart - Left Ventricle,LV363,Basophill count
171,Heart - Left Ventricle,LV44,Diagnoses - main ICD10: K40 Inguinal hernia
172,Liver,LV50,"Non-cancer illness code, self-reported: gout"
173,Liver,LV21,"Non-cancer illness code, self-reported: high cholesterol"
174,Liver,LV21,"Non-cancer illness code, self-reported: cholelithiasis/gall stones"
175,Liver,LV21,"Medication for cholesterol, blood pressure or diabetes: Cholesterol lowering medication"
176,Liver,LV21,Diagnoses - main ICD10: K80 Cholelithiasis
177,Liver,LV21,"Medication for cholesterol, blood pressure, diabetes, or take exogenous hormones: Cholesterol lowering medication"
178,Liver,LV21,"Disorders of gallbladder, biliary tract and pancreas"
179,Liver,LV123,"Pulse rate, automated reading"
180,Liver,LV123,Pulse rate
181,Liver,LV123,QRS duration
182,Liver,LV366,3mm weak meridian (right)
183,Liver,LV366,3mm strong meridian (right)
184,Liver,LV366,3mm strong meridian (left)
185,Liver,LV366,3mm weak meridian (left)
186,Liver,LV366,Heel broadband ultrasound attenuation (right)
187,Liver,LV366,Heel broadband ultrasound attenuation (left)
188,Liver,LV366,6mm strong meridian (right)
189,Liver,LV366,6mm strong meridian (left)
190,Liver,LV366,6mm weak meridian (left)
191,Liver,LV366,6mm weak meridian (right)
192,Liver,LV366,Diagnoses - main ICD10: M72 Fibroblastic disorders
193,Liver,LV366,Fibroblastic disorders
194,Liver,LV366,Palmar fascial fibromatosis [Dupuytren]
195,Liver,LV366,Age started wearing glasses or contact lenses
196,Liver,LV314,Illnesses of mother: Alzheimer's disease/dementia
197,Liver,LV314,"Non-cancer illness code, self-reported: high cholesterol"
198,Lung,LV26,Mouth/teeth dental problems: Mouth ulcers
199,Lung,LV26,"Diagnoses - main ICD10: R60 Oedema, not elsewhere classified"
200,Minor Salivary Gland,LV58,Diagnoses - main ICD10: E83 Disorders of mineral metabolism
201,Minor Salivary Gland,LV58,Lymphocyte percentage
202,Minor Salivary Gland,LV58,Neutrophill percentage
203,Minor Salivary Gland,LV324,"Non-cancer illness code, self-reported: malabsorption/coeliac disease"
204,Minor Salivary Gland,LV324,"Non-cancer illness code, self-reported: sarcoidosis"
205,Minor Salivary Gland,LV324,"Never eat eggs, dairy, wheat, sugar: Wheat products"
206,Minor Salivary Gland,LV324,Coeliac disease
207,Minor Salivary Gland,LV324,Diagnoses - main ICD10: K90 Intestinal malabsorption
208,Minor Salivary Gland,LV324,"Non-cancer illness code, self-reported: hyperthyroidism/thyrotoxicosis"
209,Minor Salivary Gland,LV324,"Blood clot, DVT, bronchitis, emphysema, asthma, rhinitis, eczema, allergy diagnosed by doctor: Asthma"
210,Minor Salivary Gland,LV324,"Non-cancer illness code, self-reported: asthma"
211,Minor Salivary Gland,LV324,Bread type: Other type of bread
212,Minor Salivary Gland,LV324,Other diseases of the digestive system
213,Minor Salivary Gland,LV324,Doctor diagnosed sarcoidosis
214,Minor Salivary Gland,LV324,"Non-cancer illness code, self-reported: systemic lupus erythematosis/sle"
215,Minor Salivary Gland,LV324,Eosinophill count
216,Minor Salivary Gland,LV324,"Medication for cholesterol, blood pressure, diabetes, or take exogenous hormones: Insulin"
217,Minor Salivary Gland,LV324,Type of special diet followed: Gluten-free
218,Minor Salivary Gland,LV324,Diagnoses - main ICD10: R31 Unspecified haematuria
219,Minor Salivary Gland,LV324,"Non-cancer illness code, self-reported: hypothyroidism/myxoedema"
220,Minor Salivary Gland,LV324,"Medication for cholesterol, blood pressure or diabetes: Insulin"
221,Minor Salivary Gland,LV324,Started insulin within one year diagnosis of diabetes
222,Minor Salivary Gland,LV324,"Blood clot, DVT, bronchitis, emphysema, asthma, rhinitis, eczema, allergy diagnosed by doctor: None of the above"
223,Minor Salivary Gland,LV324,"Cereal type: Other (e.g. Cornflakes, Frosties)"
224,Minor Salivary Gland,LV324,"Non-cancer illness code, self-reported: type 1 diabetes"
225,Minor Salivary Gland,LV324,"Non-cancer illness code, self-reported: adrenocortical insufficiency/addison's disease"
226,Minor Salivary Gland,LV324,Doctor diagnosed asthma
227,Minor Salivary Gland,LV324,Age diabetes diagnosed
228,Minor Salivary Gland,LV324,White blood cell (leukocyte) count
229,Minor Salivary Gland,LV324,Lymphocyte count
230,Minor Salivary Gland,LV324,"Blood clot, DVT, bronchitis, emphysema, asthma, rhinitis, eczema, allergy diagnosed by doctor: Hayfever, allergic rhinitis or eczema"
231,Minor Salivary Gland,LV324,Type 1 diabetes
232,Minor Salivary Gland,LV324,Diagnoses - main ICD10: E10 Insulin-dependent diabetes mellitus
233,Minor Salivary Gland,LV324,Doctor diagnosed hayfever or allergic rhinitis
234,Minor Salivary Gland,LV324,"Non-cancer illness code, self-reported: psoriasis"
235,Minor Salivary Gland,LV324,Type 1 diabetes with ophthalmic complications
236,Minor Salivary Gland,LV324,Unclassified diabetic retinopathy
237,Minor Salivary Gland,LV324,"Non-cancer illness code, self-reported: sjogren's syndrome/sicca syndrome"
238,Minor Salivary Gland,LV324,Diabetic ketoacidosis
239,Minor Salivary Gland,LV324,"Non-cancer illness code, self-reported: hayfever/allergic rhinitis"
240,Minor Salivary Gland,LV324,Eosinophill percentage
241,Minor Salivary Gland,LV324,Other serious medical condition/disability diagnosed by doctor
242,Minor Salivary Gland,LV324,Type 1 diabetes with ketoacidosis
243,Minor Salivary Gland,LV324,Illnesses of siblings: Diabetes
244,Minor Salivary Gland,LV324,Diagnoses - main ICD10: E05 Thyrotoxicosis [hyperthyroidism]
245,Minor Salivary Gland,LV324,Thyrotoxicosis
246,Minor Salivary Gland,LV324,Thyrotoxicosis with diffuse goitr
247,Minor Salivary Gland,LV324,Diagnoses - main ICD10: N40 Hyperplasia of prostate
248,Minor Salivary Gland,LV324,Diseases of the blood and blood-forming organs and certain disorders involving the immune mechanism

In [83]:
# pct=40%  FDR<0.05  seen_lvs=True
_tpt = top_lvs_at_pct(40)
_df  = trait_table(_tpt, fdr_thresh=0.05, use_seen_lvs=True)
print(f'pct=40%  FDR<0.05  seen_lvs=True  ->  {len(_df)} rows, {_df["Tissue"].nunique()} tissues, {_df["LV"].nunique()} LVs')
_df[['Tissue', 'LV', 'phenotype']]

pct=40%  FDR<0.05  seen_lvs=True  ->  515 rows, 24 tissues, 80 LVs

,Tissue,LV,phenotype
0,Adipose - Subcutaneous,LV263,Sum of road length of major roads within 100m
1,Adipose - Subcutaneous,LV378,"Blood clot, DVT, bronchitis, emphysema, asthma, rhinitis, eczema, allergy diagnosed by doctor: Hayfever, allergic rhinitis or eczema"
2,Adipose - Subcutaneous,LV378,Facial ageing
3,Adipose - Subcutaneous,LV378,"Age hay fever, rhinitis or eczema diagnosed"
4,Adipose - Subcutaneous,LV378,"Blood clot, DVT, bronchitis, emphysema, asthma, rhinitis, eczema, allergy diagnosed by doctor: None of the above"
5,Adipose - Subcutaneous,LV378,"Hair colour (natural, before greying): Light brown"
6,Adipose - Subcutaneous,LV378,"Hair colour (natural, before greying): Black"
7,Adipose - Subcutaneous,LV90,"Non-cancer illness code, self-reported: polycythaemia vera"
8,Adipose - Subcutaneous,LV230,Type of fat/oil used in cooking: Vegetable oil
9,Adipose - Visceral (Omentum),LV376,Heel broadband ultrasound attenuation (right)
10,Adipose - Visceral (Omentum),LV376,Heel broadband ultrasound attenuation (left)
11,Adipose - Visceral (Omentum),LV376,"Heel quantitative ultrasound index (QUI), direct entry (right)"
12,Adipose - Visceral (Omentum),LV376,"Heel bone mineral density (BMD) T-score, automated (right)"
13,Adipose - Visceral (Omentum),LV376,Heel bone mineral density (BMD) (right)
14,Adipose - Visceral (Omentum),LV376,Heel bone mineral density (BMD) (left)
15,Adipose - Visceral (Omentum),LV376,"Heel bone mineral density (BMD) T-score, automated (left)"
16,Adipose - Visceral (Omentum),LV376,"Heel quantitative ultrasound index (QUI), direct entry (left)"
17,Adipose - Visceral (Omentum),LV376,Heel bone mineral density (BMD)
18,Adipose - Visceral (Omentum),LV376,"Heel quantitative ultrasound index (QUI), direct entry"
19,Adipose - Visceral (Omentum),LV376,"Heel bone mineral density (BMD) T-score, automated"
20,Adipose - Visceral (Omentum),LV376,"Heel Broadband ultrasound attenuation, direct entry"
21,Adipose - Visceral (Omentum),LV376,Fractured/broken bones in last 5 years
22,Adipose - Visceral (Omentum),LV376,Diagnoses - main ICD10: N81 Female genital prolapse
23,Adipose - Visceral (Omentum),LV376,Palmar fascial fibromatosis [Dupuytren]
24,Adipose - Visceral (Omentum),LV376,Fibroblastic disorders
25,Adipose - Visceral (Omentum),LV376,Diagnoses - main ICD10: M72 Fibroblastic disorders
26,Adipose - Visceral (Omentum),LV376,"Hair colour (natural, before greying): Light brown"
27,Adipose - Visceral (Omentum),LV376,Facial ageing
28,Adipose - Visceral (Omentum),LV83,"Hair colour (natural, before greying): Light brown"
29,Adipose - Visceral (Omentum),LV57,"Heel bone mineral density (BMD) T-score, automated (left)"
30,Adipose - Visceral (Omentum),LV57,"Heel quantitative ultrasound index (QUI), direct entry (left)"
31,Adipose - Visceral (Omentum),LV57,Heel bone mineral density (BMD) (left)
32,Adipose - Visceral (Omentum),LV106,"Disorders of gallbladder, biliary tract and pancreas"
33,Adipose - Visceral (Omentum),LV106,malignant neoplasm of male genital organs
34,Adipose - Visceral (Omentum),LV106,Malignant neoplasm of prostate
35,Adipose - Visceral (Omentum),LV106,Diagnoses - main ICD10: K80 Cholelithiasis
36,Adrenal Gland,LV3,Basophill percentage
37,Adrenal Gland,LV3,Basophill count
38,Adrenal Gland,LV3,Diagnoses - main ICD10: C44 Other malignant neoplasms of skin
39,Adrenal Gland,LV3,"Cancer code, self-reported: basal cell carcinoma"
40,Adrenal Gland,LV158,"Medication for cholesterol, blood pressure or diabetes: Blood pressure medication"
41,Adrenal Gland,LV158,"Disorders of gallbladder, biliary tract and pancreas"
42,Adrenal Gland,LV158,"Job SOC coding: Property, housing and land managers"
43,Adrenal Gland,LV158,"Non-cancer illness code, self-reported: hypertension"
44,Adrenal Gland,LV183,Mouth/teeth dental problems: Mouth ulcers
45,Adrenal Gland,LV183,Basophill count
46,Adrenal Gland,LV183,"Non-cancer illness code, self-reported: ulcerative colitis"
47,Adrenal Gland,LV183,Diagnoses - main ICD10: D61 Other aplastic anaemias
48,Adrenal Gland,LV183,Basophill percentage
49,Artery - Aorta,LV145,"Hair colour (natural, before greying): Light brown"
50,Artery - Aorta,LV145,"Hair colour (natural, before greying): Black"
51,Artery - Aorta,LV145,"Hair colour (natural, before greying): Blonde"
52,Artery - Aorta,LV37,Other viral diseases
53,Artery - Aorta,LV40,"Heel bone mineral density (BMD) T-score, automated (left)"
54,Artery - Aorta,LV40,"Heel quantitative ultrasound index (QUI), direct entry (left)"
55,Artery - Aorta,LV40,Heel bone mineral density (BMD) (left)
56,Artery - Aorta,LV40,Heel bone mineral density (BMD)
57,Artery - Aorta,LV84,Venous thromboembolism
58,Artery - Aorta,LV84,DVT of lower extremities and pulmonary embolism
59,Artery - Aorta,LV84,DVT of lower extremities
60,Artery - Aorta,LV84,Illnesses of mother: Alzheimer's disease/dementia
61,Artery - Aorta,LV84,"Non-cancer illness code, self-reported: deep venous thrombosis (dvt)"
62,Artery - Aorta,LV84,"Blood clot, DVT, bronchitis, emphysema, asthma, rhinitis, eczema, allergy diagnosed by doctor: Blood clot in the leg (DVT)"
63,Artery - Aorta,LV84,Diagnoses - main ICD10: I80 Phlebitis and thrombophlebitis
64,Artery - Aorta,LV84,Palmar fascial fibromatosis [Dupuytren]
65,Artery - Aorta,LV84,"Blood clot, DVT, bronchitis, emphysema, asthma, rhinitis, eczema, allergy diagnosed by doctor: Blood clot in the lung"
66,Artery - Aorta,LV84,Fibroblastic disorders
67,Artery - Aorta,LV84,"Non-cancer illness code, self-reported: pulmonary embolism +/- dvt"
68,Artery - Aorta,LV84,Diagnoses - main ICD10: M72 Fibroblastic disorders
69,Artery - Aorta,LV84,Other ILD-related CVD-co-morbidities
70,Artery - Aorta,LV84,Haemoglobin concentration
71,Artery - Aorta,LV84,Haematocrit percentage
72,Artery - Coronary,LV247,Eye problems/disorders: Glaucoma
73,Artery - Coronary,LV102,Felt loved as a child
74,Artery - Coronary,LV102,Yogurt/ice-cream consumers
75,Artery - Coronary,LV102,Diagnoses - main ICD10: I84 Haemorrhoids
76,Artery - Coronary,LV59,Interpolated Age of participant when cancer first diagnosed
77,Artery - Coronary,LV99,Monocyte count
78,Artery - Tibial,LV397,Illnesses of mother: Diabetes
79,Artery - Tibial,LV397,"Non-cancer illness code, self-reported: diabetes"
80,Artery - Tibial,LV397,Illnesses of father: Diabetes
81,Artery - Tibial,LV397,Diabetes diagnosed by doctor
82,Artery - Tibial,LV397,"Non-cancer illness code, self-reported: type 2 diabetes"
83,Artery - Tibial,LV397,"Non-cancer illness code, self-reported: gout"
84,Artery - Tibial,LV113,"Non-cancer illness code, self-reported: gout"
85,Artery - Tibial,LV113,Other malignant neoplasms of skin
86,Artery - Tibial,LV113,Diagnoses - main ICD10: C44 Other malignant neoplasms of skin
87,Artery - Tibial,LV113,Coronary atherosclerosis
88,Artery - Tibial,LV113,Diagnoses - main ICD10: I25 Chronic ischaemic heart disease
89,Cells - Cultured fibroblasts,LV111,"Non-cancer illness code, self-reported: rheumatoid arthritis"
90,Cells - Cultured fibroblasts,LV111,Rheumatoid arthritis
91,Cells - Cultured fibroblasts,LV111,Other/unspecified seropositiverheumatoid arthritis
92,Cells - Cultured fibroblasts,LV111,Diagnoses - main ICD10: M06 Other rheumatoid arthritis
93,Cells - Cultured fibroblasts,LV111,Other/unspecified rheumatoid arthritis
94,Cells - Cultured fibroblasts,LV111,Adult-onset Still disease
95,Cells - Cultured fibroblasts,LV111,Diagnoses - main ICD10: M05 Seropositive rheumatoid arthritis
96,Cells - Cultured fibroblasts,LV111,Seropositive rheumatoid arthritis
97,Cells - Cultured fibroblasts,LV111,"Non-cancer illness code, self-reported: multiple sclerosis"
98,Cells - Cultured fibroblasts,LV111,#Polyarthropathies
99,Cells - Cultured fibroblasts,LV111,"Non-cancer illness code, self-reported: polymyalgia rheumatica"
100,Cells - Cultured fibroblasts,LV111,Demyelenating diseases of the central nervous system
101,Cells - Cultured fibroblasts,LV111,Non-accidental death in close genetic family
102,Cells - Cultured fibroblasts,LV180,Diagnoses - main ICD10: M72 Fibroblastic disorders
103,Cells - Cultured fibroblasts,LV180,Fibroblastic disorders
104,Cells - Cultured fibroblasts,LV180,Palmar fascial fibromatosis [Dupuytren]
105,Cells - Cultured fibroblasts,LV180,3mm weak meridian (right)
106,Cells - Cultured fibroblasts,LV180,3mm strong meridian (left)
107,Cells - Cultured fibroblasts,LV180,3mm strong meridian (right)
108,Cells - Cultured fibroblasts,LV180,3mm weak meridian (left)
109,Cells - Cultured fibroblasts,LV180,6mm strong meridian (right)
110,Cells - Cultured fibroblasts,LV180,6mm weak meridian (right)
111,Cells - Cultured fibroblasts,LV180,6mm strong meridian (left)
112,Cells - Cultured fibroblasts,LV180,6mm weak meridian (left)
113,Cells - Cultured fibroblasts,LV336,"Hair colour (natural, before greying): Light brown"
114,Cells - Cultured fibroblasts,LV336,"Hair colour (natural, before greying): Blonde"
115,Cells - Cultured fibroblasts,LV336,"Hair colour (natural, before greying): Black"
116,Cells - Cultured fibroblasts,LV91,"Non-cancer illness code, self-reported: multiple sclerosis"
117,Cells - Cultured fibroblasts,LV91,Mouth/teeth dental problems: Mouth ulcers
118,Cells - Cultured fibroblasts,LV91,"Blood clot, DVT, bronchitis, emphysema, asthma, rhinitis, eczema, allergy diagnosed by doctor: Hayfever, allergic rhinitis or eczema"
119,Cells - Cultured fibroblasts,LV91,Monocyte percentage
120,Cells - Cultured fibroblasts,LV91,Demyelenating diseases of the central nervous system
121,Cells - Cultured fibroblasts,LV91,Diagnoses - main ICD10: G35 Multiple sclerosis
122,Cells - Cultured fibroblasts,LV91,Rheumatoid arthritis
123,Cells - Cultured fibroblasts,LV91,Diagnoses - main ICD10: M06 Other rheumatoid arthritis
124,Cells - Cultured fibroblasts,LV91,Adult-onset Still disease
125,Cells - Cultured fibroblasts,LV91,"Non-cancer illness code, self-reported: rheumatoid arthritis"
126,Cells - Cultured fibroblasts,LV91,Other/unspecified rheumatoid arthritis
127,Cells - Cultured fibroblasts,LV91,Other/unspecified seropositiverheumatoid arthritis
128,Cells - Cultured fibroblasts,LV91,Monocyte count
129,Cells - Cultured fibroblasts,LV91,Seropositive rheumatoid arthritis
130,Cells - Cultured fibroblasts,LV91,"Blood clot, DVT, bronchitis, emphysema, asthma, rhinitis, eczema, allergy diagnosed by doctor: None of the above"
131,Cells - Cultured fibroblasts,LV91,Diagnoses - main ICD10: M05 Seropositive rheumatoid arthritis
132,Cells - Cultured fibroblasts,LV91,Doctor diagnosed hayfever or allergic rhinitis
133,Cells - Cultured fibroblasts,LV91,Diagnoses - main ICD10: K51 Ulcerative colitis
134,Cells - Cultured fibroblasts,LV91,Suggestive for eosinophilic asthma
135,Cells - Cultured fibroblasts,LV91,#Polyarthropathies
136,Cells - Cultured fibroblasts,LV91,"Non-cancer illness code, self-reported: ulcerative colitis"
137,Cells - Cultured fibroblasts,LV91,Diagnoses - main ICD10: J33 Nasal polyp
138,Cells - Cultured fibroblasts,LV91,"Non-cancer illness code, self-reported: hypothyroidism/myxoedema"
139,Cells - Cultured fibroblasts,LV91,"Age hay fever, rhinitis or eczema diagnosed"
140,Cells - Cultured fibroblasts,LV91,"Ulcerative colitis, NAS"
141,Cells - Cultured fibroblasts,LV91,Age hayfever or allergic rhinitis diagnosed by doctor
142,Cells - Cultured fibroblasts,LV91,"Non-cancer illness code, self-reported: hyperthyroidism/thyrotoxicosis"
143,Cells - Cultured fibroblasts,LV91,Thyrotoxicosis
144,Cells - Cultured fibroblasts,LV91,Diagnoses - main ICD10: E05 Thyrotoxicosis [hyperthyroidism]
145,Cells - Cultured fibroblasts,LV91,Vitamin and mineral supplements: Folic acid or Folate (Vit B9)
146,Cells - Cultured fibroblasts,LV91,Diagnoses - main ICD10: M45 Ankylosing spondylitis
147,Cells - EBV-transformed lymphocytes,LV123,"Pulse rate, automated reading"
148,Cells - EBV-transformed lymphocytes,LV123,Pulse rate
149,Cells - EBV-transformed lymphocytes,LV123,QRS duration
150,Cells - EBV-transformed lymphocytes,LV116,"Blood clot, DVT, bronchitis, emphysema, asthma, rhinitis, eczema, allergy diagnosed by doctor: Blood clot in the leg (DVT)"
151,Cells - EBV-transformed lymphocytes,LV116,"Non-cancer illness code, self-reported: deep venous thrombosis (dvt)"
152,Cells - EBV-transformed lymphocytes,LV116,Diagnoses - main ICD10: I80 Phlebitis and thrombophlebitis
153,Cells - EBV-transformed lymphocytes,LV116,DVT of lower extremities
154,Cells - EBV-transformed lymphocytes,LV116,Venous thromboembolism
155,Cells - EBV-transformed lymphocytes,LV116,"Non-cancer illness code, self-reported: clotting disorder/excessive bleeding"
156,Cells - EBV-transformed lymphocytes,LV244,Number of cigarettes currently smoked daily (current cigarette smokers)
157,Cells - EBV-transformed lymphocytes,LV244,Difficulty not smoking for 1 day
158,Cells - EBV-transformed lymphocytes,LV12,Reason former drinker stopped drinking alcohol: Financial reasons
159,Cells - EBV-transformed lymphocytes,LV406,Number of cigarettes previously smoked daily
160,Cells - EBV-transformed lymphocytes,LV406,Number of cigarettes currently smoked daily (current cigarette smokers)
161,Cells - EBV-transformed lymphocytes,LV406,Palmar fascial fibromatosis [Dupuytren]
162,Esophagus - Mucosa,LV8,Heel broadband ultrasound attenuation (left)
163,Esophagus - Mucosa,LV8,Heel broadband ultrasound attenuation (right)
164,Esophagus - Mucosa,LV8,Fractured/broken bones in last 5 years
165,Esophagus - Mucosa,LV8,Primary_lymphoid and hematopoietic malignant neoplasms
166,Esophagus - Mucosa,LV8,Diagnoses - main ICD10: Q82 Other congenital malformations of skin
167,Esophagus - Mucosa,LV8,"Job SOC coding: Hairdressers, barbers"
168,Esophagus - Mucosa,LV8,"Cancer code, self-reported: rodent ulcer"
169,Esophagus - Mucosa,LV8,Fractured bone site(s): Wrist
170,Esophagus - Mucosa,LV138,Diagnoses - main ICD10: C44 Other malignant neoplasms of skin
171,Esophagus - Mucosa,LV138,"Non-cancer illness code, self-reported: renal failure requiring dialysis"
172,Heart - Atrial Appendage,LV282,Job SOC coding: Medical secretaries
173,Heart - Atrial Appendage,LV282,"Non-cancer illness code, self-reported: gout"
174,Heart - Atrial Appendage,LV282,Diagnoses - main ICD10: F10 Mental and behavioural disorders due to use of alcohol
175,Heart - Atrial Appendage,LV139,"Cancer code, self-reported: multiple myeloma"
176,Heart - Left Ventricle,LV137,"Diagnoses - main ICD10: A63 Other predominantly sexually transmitted diseases, not elsewhere classified"
177,Heart - Left Ventricle,LV248,"Blood clot, DVT, bronchitis, emphysema, asthma, rhinitis, eczema, allergy diagnosed by doctor: None of the above"
178,Heart - Left Ventricle,LV248,"Blood clot, DVT, bronchitis, emphysema, asthma, rhinitis, eczema, allergy diagnosed by doctor: Hayfever, allergic rhinitis or eczema"
179,Heart - Left Ventricle,LV248,Age asthma diagnosed
180,Heart - Left Ventricle,LV248,Mouth/teeth dental problems: Mouth ulcers
181,Heart - Left Ventricle,LV248,Eosinophill percentage
182,Heart - Left Ventricle,LV248,"Non-cancer illness code, self-reported: hayfever/allergic rhinitis"
183,Heart - Left Ventricle,LV363,Basophill percentage
184,Heart - Left Ventricle,LV363,Eosinophill count
185,Heart - Left Ventricle,LV363,Lymphocyte count
186,Heart - Left Ventricle,LV363,Eosinophill percentage
187,Heart - Left Ventricle,LV363,"Medication for cholesterol, blood pressure or diabetes: Blood pressure medication"
188,Heart - Left Ventricle,LV363,Basophill count
189,Heart - Left Ventricle,LV363,"Medication for cholesterol, blood pressure or diabetes: None of the above"
190,Heart - Left Ventricle,LV363,Illnesses of siblings: High blood pressure
191,Heart - Left Ventricle,LV363,Lymphocyte percentage
192,Heart - Left Ventricle,LV363,Vascular/heart problems diagnosed by doctor: None of the above
193,Heart - Left Ventricle,LV363,"Non-cancer illness code, self-reported: subarachnoid haemorrhage"
194,Heart - Left Ventricle,LV363,Illnesses of mother: High blood pressure
195,Heart - Left Ventricle,LV363,Red blood cell (erythrocyte) count
196,Heart - Left Ventricle,LV363,FI5 : family relationship calculation
197,Heart - Left Ventricle,LV44,Diagnoses - main ICD10: K40 Inguinal hernia
198,Heart - Left Ventricle,LV161,Haematocrit percentage
199,Heart - Left Ventricle,LV385,Home area population density - urban or rural: Scotland - Other Urban Area
200,Heart - Left Ventricle,LV32,Medial epicondylitis
201,Heart - Left Ventricle,LV32,Type of fat/oil used in cooking: Normal fat olive spread
202,Heart - Left Ventricle,LV32,Diagnoses - main ICD10: S56 Injury of muscle and tendon at forearm level
203,Heart - Left Ventricle,LV227,Palmar fascial fibromatosis [Dupuytren]
204,Liver,LV50,"Non-cancer illness code, self-reported: gout"
205,Liver,LV50,Interpolated Age of participant when cancer first diagnosed
206,Liver,LV229,Other deformity of hallux (acquired)
207,Liver,LV21,"Non-cancer illness code, self-reported: high cholesterol"
208,Liver,LV21,"Non-cancer illness code, self-reported: cholelithiasis/gall stones"
209,Liver,LV21,"Medication for cholesterol, blood pressure or diabetes: Cholesterol lowering medication"
210,Liver,LV21,Diagnoses - main ICD10: K80 Cholelithiasis
211,Liver,LV21,"Medication for cholesterol, blood pressure, diabetes, or take exogenous hormones: Cholesterol lowering medication"
212,Liver,LV21,"Disorders of gallbladder, biliary tract and pancreas"
213,Liver,LV35,"Worked with paints, thinners or glues: Sometimes"
214,Liver,LV366,3mm weak meridian (right)
215,Liver,LV366,3mm strong meridian (right)
216,Liver,LV366,3mm strong meridian (left)
217,Liver,LV366,3mm weak meridian (left)
218,Liver,LV366,Heel broadband ultrasound attenuation (right)
219,Liver,LV366,Heel broadband ultrasound attenuation (left)
220,Liver,LV366,6mm strong meridian (right)
221,Liver,LV366,6mm strong meridian (left)
222,Liver,LV366,6mm weak meridian (left)
223,Liver,LV366,6mm weak meridian (right)
224,Liver,LV366,Diagnoses - main ICD10: M72 Fibroblastic disorders
225,Liver,LV366,Fibroblastic disorders
226,Liver,LV366,Palmar fascial fibromatosis [Dupuytren]
227,Liver,LV366,Age started wearing glasses or contact lenses
228,Liver,LV366,Fractured/broken bones in last 5 years
229,Liver,LV366,Reason for glasses/contact lenses: For a 'lazy' eye or an eye with poor vision since childhood (called 'amblyopia')
230,Liver,LV314,Illnesses of mother: Alzheimer's disease/dementia
231,Liver,LV314,"Non-cancer illness code, self-reported: high cholesterol"
232,Lung,LV208,Diagnoses - main ICD10: L27 Dermatitis due to substances taken internally
233,Lung,LV26,Mouth/teeth dental problems: Mouth ulcers
234,Lung,LV26,"Diagnoses - main ICD10: R60 Oedema, not elsewhere classified"
235,Minor Salivary Gland,LV58,Diagnoses - main ICD10: E83 Disorders of mineral metabolism
236,Minor Salivary Gland,LV58,Lymphocyte percentage
237,Minor Salivary Gland,LV58,Neutrophill percentage
238,Minor Salivary Gland,LV58,Trigger finger
239,Minor Salivary Gland,LV58,Mean corpuscular haemoglobin
240,Minor Salivary Gland,LV324,"Non-cancer illness code, self-reported: malabsorption/coeliac disease"
241,Minor Salivary Gland,LV324,"Non-cancer illness code, self-reported: sarcoidosis"
242,Minor Salivary Gland,LV324,"Never eat eggs, dairy, wheat, sugar: Wheat products"
243,Minor Salivary Gland,LV324,Coeliac disease
244,Minor Salivary Gland,LV324,Diagnoses - main ICD10: K90 Intestinal malabsorption
245,Minor Salivary Gland,LV324,"Non-cancer illness code, self-reported: hyperthyroidism/thyrotoxicosis"
246,Minor Salivary Gland,LV324,"Blood clot, DVT, bronchitis, emphysema, asthma, rhinitis, eczema, allergy diagnosed by doctor: Asthma"
247,Minor Salivary Gland,LV324,"Non-cancer illness code, self-reported: asthma"
248,Minor Salivary Gland,LV324,Bread type: Other type of bread
249,Minor Salivary Gland,LV324,Other diseases of the digestive system
250,Minor Salivary Gland,LV324,Doctor diagnosed sarcoidosis
251,Minor Salivary Gland,LV324,"Non-cancer illness code, self-reported: systemic lupus erythematosis/sle"
252,Minor Salivary Gland,LV324,Eosinophill count

In [84]:
# pct=40%  FDR<0.05  seen_lvs=False
_tpt = top_lvs_at_pct(40)
_df  = trait_table(_tpt, fdr_thresh=0.05, use_seen_lvs=False)
print(f'pct=40%  FDR<0.05  seen_lvs=False  ->  {len(_df)} rows, {_df["Tissue"].nunique()} tissues, {_df["LV"].nunique()} LVs')
_df[['Tissue', 'LV', 'phenotype']]

pct=40%  FDR<0.05  seen_lvs=False  ->  789 rows, 25 tissues, 80 LVs

,Tissue,LV,phenotype
0,Adipose - Subcutaneous,LV263,Sum of road length of major roads within 100m
1,Adipose - Subcutaneous,LV378,"Blood clot, DVT, bronchitis, emphysema, asthma, rhinitis, eczema, allergy diagnosed by doctor: Hayfever, allergic rhinitis or eczema"
2,Adipose - Subcutaneous,LV378,Facial ageing
3,Adipose - Subcutaneous,LV378,"Age hay fever, rhinitis or eczema diagnosed"
4,Adipose - Subcutaneous,LV378,"Blood clot, DVT, bronchitis, emphysema, asthma, rhinitis, eczema, allergy diagnosed by doctor: None of the above"
5,Adipose - Subcutaneous,LV378,"Hair colour (natural, before greying): Light brown"
6,Adipose - Subcutaneous,LV378,"Hair colour (natural, before greying): Black"
7,Adipose - Subcutaneous,LV90,"Non-cancer illness code, self-reported: polycythaemia vera"
8,Adipose - Subcutaneous,LV230,Type of fat/oil used in cooking: Vegetable oil
9,Adipose - Visceral (Omentum),LV263,Sum of road length of major roads within 100m
10,Adipose - Visceral (Omentum),LV376,Heel broadband ultrasound attenuation (right)
11,Adipose - Visceral (Omentum),LV376,Heel broadband ultrasound attenuation (left)
12,Adipose - Visceral (Omentum),LV376,"Heel quantitative ultrasound index (QUI), direct entry (right)"
13,Adipose - Visceral (Omentum),LV376,"Heel bone mineral density (BMD) T-score, automated (right)"
14,Adipose - Visceral (Omentum),LV376,Heel bone mineral density (BMD) (right)
15,Adipose - Visceral (Omentum),LV376,Heel bone mineral density (BMD) (left)
16,Adipose - Visceral (Omentum),LV376,"Heel bone mineral density (BMD) T-score, automated (left)"
17,Adipose - Visceral (Omentum),LV376,"Heel quantitative ultrasound index (QUI), direct entry (left)"
18,Adipose - Visceral (Omentum),LV376,Heel bone mineral density (BMD)
19,Adipose - Visceral (Omentum),LV376,"Heel quantitative ultrasound index (QUI), direct entry"
20,Adipose - Visceral (Omentum),LV376,"Heel bone mineral density (BMD) T-score, automated"
21,Adipose - Visceral (Omentum),LV376,"Heel Broadband ultrasound attenuation, direct entry"
22,Adipose - Visceral (Omentum),LV376,Fractured/broken bones in last 5 years
23,Adipose - Visceral (Omentum),LV376,Diagnoses - main ICD10: N81 Female genital prolapse
24,Adipose - Visceral (Omentum),LV376,Palmar fascial fibromatosis [Dupuytren]
25,Adipose - Visceral (Omentum),LV376,Fibroblastic disorders
26,Adipose - Visceral (Omentum),LV376,Diagnoses - main ICD10: M72 Fibroblastic disorders
27,Adipose - Visceral (Omentum),LV376,"Hair colour (natural, before greying): Light brown"
28,Adipose - Visceral (Omentum),LV376,Facial ageing
29,Adipose - Visceral (Omentum),LV83,"Hair colour (natural, before greying): Light brown"
30,Adipose - Visceral (Omentum),LV57,"Heel bone mineral density (BMD) T-score, automated (left)"
31,Adipose - Visceral (Omentum),LV57,"Heel quantitative ultrasound index (QUI), direct entry (left)"
32,Adipose - Visceral (Omentum),LV57,Heel bone mineral density (BMD) (left)
33,Adipose - Visceral (Omentum),LV106,"Disorders of gallbladder, biliary tract and pancreas"
34,Adipose - Visceral (Omentum),LV106,malignant neoplasm of male genital organs
35,Adipose - Visceral (Omentum),LV106,Malignant neoplasm of prostate
36,Adipose - Visceral (Omentum),LV106,Diagnoses - main ICD10: K80 Cholelithiasis
37,Adipose - Visceral (Omentum),LV230,Type of fat/oil used in cooking: Vegetable oil
38,Adrenal Gland,LV83,"Hair colour (natural, before greying): Light brown"
39,Adrenal Gland,LV3,Basophill percentage
40,Adrenal Gland,LV3,Basophill count
41,Adrenal Gland,LV3,Diagnoses - main ICD10: C44 Other malignant neoplasms of skin
42,Adrenal Gland,LV3,"Cancer code, self-reported: basal cell carcinoma"
43,Adrenal Gland,LV158,"Medication for cholesterol, blood pressure or diabetes: Blood pressure medication"
44,Adrenal Gland,LV158,"Disorders of gallbladder, biliary tract and pancreas"
45,Adrenal Gland,LV158,"Job SOC coding: Property, housing and land managers"
46,Adrenal Gland,LV158,"Non-cancer illness code, self-reported: hypertension"
47,Adrenal Gland,LV183,Mouth/teeth dental problems: Mouth ulcers
48,Adrenal Gland,LV183,Basophill count
49,Adrenal Gland,LV183,"Non-cancer illness code, self-reported: ulcerative colitis"
50,Adrenal Gland,LV183,Diagnoses - main ICD10: D61 Other aplastic anaemias
51,Adrenal Gland,LV183,Basophill percentage
52,Artery - Aorta,LV145,"Hair colour (natural, before greying): Light brown"
53,Artery - Aorta,LV145,"Hair colour (natural, before greying): Black"
54,Artery - Aorta,LV145,"Hair colour (natural, before greying): Blonde"
55,Artery - Aorta,LV90,"Non-cancer illness code, self-reported: polycythaemia vera"
56,Artery - Aorta,LV37,Other viral diseases
57,Artery - Aorta,LV40,"Heel bone mineral density (BMD) T-score, automated (left)"
58,Artery - Aorta,LV40,"Heel quantitative ultrasound index (QUI), direct entry (left)"
59,Artery - Aorta,LV40,Heel bone mineral density (BMD) (left)
60,Artery - Aorta,LV40,Heel bone mineral density (BMD)
61,Artery - Aorta,LV84,Venous thromboembolism
62,Artery - Aorta,LV84,DVT of lower extremities and pulmonary embolism
63,Artery - Aorta,LV84,DVT of lower extremities
64,Artery - Aorta,LV84,Illnesses of mother: Alzheimer's disease/dementia
65,Artery - Aorta,LV84,"Non-cancer illness code, self-reported: deep venous thrombosis (dvt)"
66,Artery - Aorta,LV84,"Blood clot, DVT, bronchitis, emphysema, asthma, rhinitis, eczema, allergy diagnosed by doctor: Blood clot in the leg (DVT)"
67,Artery - Aorta,LV84,Diagnoses - main ICD10: I80 Phlebitis and thrombophlebitis
68,Artery - Aorta,LV84,Palmar fascial fibromatosis [Dupuytren]
69,Artery - Aorta,LV84,"Blood clot, DVT, bronchitis, emphysema, asthma, rhinitis, eczema, allergy diagnosed by doctor: Blood clot in the lung"
70,Artery - Aorta,LV84,Fibroblastic disorders
71,Artery - Aorta,LV84,"Non-cancer illness code, self-reported: pulmonary embolism +/- dvt"
72,Artery - Aorta,LV84,Diagnoses - main ICD10: M72 Fibroblastic disorders
73,Artery - Aorta,LV84,Other ILD-related CVD-co-morbidities
74,Artery - Aorta,LV84,Haemoglobin concentration
75,Artery - Aorta,LV84,Haematocrit percentage
76,Artery - Coronary,LV40,"Heel bone mineral density (BMD) T-score, automated (left)"
77,Artery - Coronary,LV40,"Heel quantitative ultrasound index (QUI), direct entry (left)"
78,Artery - Coronary,LV40,Heel bone mineral density (BMD) (left)
79,Artery - Coronary,LV40,Heel bone mineral density (BMD)
80,Artery - Coronary,LV247,Eye problems/disorders: Glaucoma
81,Artery - Coronary,LV102,Felt loved as a child
82,Artery - Coronary,LV102,Yogurt/ice-cream consumers
83,Artery - Coronary,LV102,Diagnoses - main ICD10: I84 Haemorrhoids
84,Artery - Coronary,LV59,Interpolated Age of participant when cancer first diagnosed
85,Artery - Coronary,LV99,Monocyte count
86,Artery - Coronary,LV106,"Disorders of gallbladder, biliary tract and pancreas"
87,Artery - Coronary,LV106,malignant neoplasm of male genital organs
88,Artery - Coronary,LV106,Malignant neoplasm of prostate
89,Artery - Coronary,LV106,Diagnoses - main ICD10: K80 Cholelithiasis
90,Artery - Coronary,LV84,Venous thromboembolism
91,Artery - Coronary,LV84,DVT of lower extremities and pulmonary embolism
92,Artery - Coronary,LV84,DVT of lower extremities
93,Artery - Coronary,LV84,Illnesses of mother: Alzheimer's disease/dementia
94,Artery - Coronary,LV84,"Non-cancer illness code, self-reported: deep venous thrombosis (dvt)"
95,Artery - Coronary,LV84,"Blood clot, DVT, bronchitis, emphysema, asthma, rhinitis, eczema, allergy diagnosed by doctor: Blood clot in the leg (DVT)"
96,Artery - Coronary,LV84,Diagnoses - main ICD10: I80 Phlebitis and thrombophlebitis
97,Artery - Coronary,LV84,Palmar fascial fibromatosis [Dupuytren]
98,Artery - Coronary,LV84,"Blood clot, DVT, bronchitis, emphysema, asthma, rhinitis, eczema, allergy diagnosed by doctor: Blood clot in the lung"
99,Artery - Coronary,LV84,Fibroblastic disorders
100,Artery - Coronary,LV84,"Non-cancer illness code, self-reported: pulmonary embolism +/- dvt"
101,Artery - Coronary,LV84,Diagnoses - main ICD10: M72 Fibroblastic disorders
102,Artery - Coronary,LV84,Other ILD-related CVD-co-morbidities
103,Artery - Coronary,LV84,Haemoglobin concentration
104,Artery - Coronary,LV84,Haematocrit percentage
105,Artery - Tibial,LV90,"Non-cancer illness code, self-reported: polycythaemia vera"
106,Artery - Tibial,LV397,Illnesses of mother: Diabetes
107,Artery - Tibial,LV397,"Non-cancer illness code, self-reported: diabetes"
108,Artery - Tibial,LV397,Illnesses of father: Diabetes
109,Artery - Tibial,LV397,Diabetes diagnosed by doctor
110,Artery - Tibial,LV397,"Non-cancer illness code, self-reported: type 2 diabetes"
111,Artery - Tibial,LV397,"Non-cancer illness code, self-reported: gout"
112,Artery - Tibial,LV102,Felt loved as a child
113,Artery - Tibial,LV102,Yogurt/ice-cream consumers
114,Artery - Tibial,LV102,Diagnoses - main ICD10: I84 Haemorrhoids
115,Artery - Tibial,LV84,Venous thromboembolism
116,Artery - Tibial,LV84,DVT of lower extremities and pulmonary embolism
117,Artery - Tibial,LV84,DVT of lower extremities
118,Artery - Tibial,LV84,Illnesses of mother: Alzheimer's disease/dementia
119,Artery - Tibial,LV84,"Non-cancer illness code, self-reported: deep venous thrombosis (dvt)"
120,Artery - Tibial,LV84,"Blood clot, DVT, bronchitis, emphysema, asthma, rhinitis, eczema, allergy diagnosed by doctor: Blood clot in the leg (DVT)"
121,Artery - Tibial,LV84,Diagnoses - main ICD10: I80 Phlebitis and thrombophlebitis
122,Artery - Tibial,LV84,Palmar fascial fibromatosis [Dupuytren]
123,Artery - Tibial,LV84,"Blood clot, DVT, bronchitis, emphysema, asthma, rhinitis, eczema, allergy diagnosed by doctor: Blood clot in the lung"
124,Artery - Tibial,LV84,Fibroblastic disorders
125,Artery - Tibial,LV84,"Non-cancer illness code, self-reported: pulmonary embolism +/- dvt"
126,Artery - Tibial,LV84,Diagnoses - main ICD10: M72 Fibroblastic disorders
127,Artery - Tibial,LV84,Other ILD-related CVD-co-morbidities
128,Artery - Tibial,LV84,Haemoglobin concentration
129,Artery - Tibial,LV84,Haematocrit percentage
130,Artery - Tibial,LV113,"Non-cancer illness code, self-reported: gout"
131,Artery - Tibial,LV113,Other malignant neoplasms of skin
132,Artery - Tibial,LV113,Diagnoses - main ICD10: C44 Other malignant neoplasms of skin
133,Artery - Tibial,LV113,Coronary atherosclerosis
134,Artery - Tibial,LV113,Diagnoses - main ICD10: I25 Chronic ischaemic heart disease
135,Cells - Cultured fibroblasts,LV111,"Non-cancer illness code, self-reported: rheumatoid arthritis"
136,Cells - Cultured fibroblasts,LV111,Rheumatoid arthritis
137,Cells - Cultured fibroblasts,LV111,Other/unspecified seropositiverheumatoid arthritis
138,Cells - Cultured fibroblasts,LV111,Diagnoses - main ICD10: M06 Other rheumatoid arthritis
139,Cells - Cultured fibroblasts,LV111,Other/unspecified rheumatoid arthritis
140,Cells - Cultured fibroblasts,LV111,Adult-onset Still disease
141,Cells - Cultured fibroblasts,LV111,Diagnoses - main ICD10: M05 Seropositive rheumatoid arthritis
142,Cells - Cultured fibroblasts,LV111,Seropositive rheumatoid arthritis
143,Cells - Cultured fibroblasts,LV111,"Non-cancer illness code, self-reported: multiple sclerosis"
144,Cells - Cultured fibroblasts,LV111,#Polyarthropathies
145,Cells - Cultured fibroblasts,LV111,"Non-cancer illness code, self-reported: polymyalgia rheumatica"
146,Cells - Cultured fibroblasts,LV111,Demyelenating diseases of the central nervous system
147,Cells - Cultured fibroblasts,LV111,Non-accidental death in close genetic family
148,Cells - Cultured fibroblasts,LV180,Diagnoses - main ICD10: M72 Fibroblastic disorders
149,Cells - Cultured fibroblasts,LV180,Fibroblastic disorders
150,Cells - Cultured fibroblasts,LV180,Palmar fascial fibromatosis [Dupuytren]
151,Cells - Cultured fibroblasts,LV180,3mm weak meridian (right)
152,Cells - Cultured fibroblasts,LV180,3mm strong meridian (left)
153,Cells - Cultured fibroblasts,LV180,3mm strong meridian (right)
154,Cells - Cultured fibroblasts,LV180,3mm weak meridian (left)
155,Cells - Cultured fibroblasts,LV180,6mm strong meridian (right)
156,Cells - Cultured fibroblasts,LV180,6mm weak meridian (right)
157,Cells - Cultured fibroblasts,LV180,6mm strong meridian (left)
158,Cells - Cultured fibroblasts,LV180,6mm weak meridian (left)
159,Cells - Cultured fibroblasts,LV336,"Hair colour (natural, before greying): Light brown"
160,Cells - Cultured fibroblasts,LV336,"Hair colour (natural, before greying): Blonde"
161,Cells - Cultured fibroblasts,LV336,"Hair colour (natural, before greying): Black"
162,Cells - Cultured fibroblasts,LV84,Venous thromboembolism
163,Cells - Cultured fibroblasts,LV84,DVT of lower extremities and pulmonary embolism
164,Cells - Cultured fibroblasts,LV84,DVT of lower extremities
165,Cells - Cultured fibroblasts,LV84,Illnesses of mother: Alzheimer's disease/dementia
166,Cells - Cultured fibroblasts,LV84,"Non-cancer illness code, self-reported: deep venous thrombosis (dvt)"
167,Cells - Cultured fibroblasts,LV84,"Blood clot, DVT, bronchitis, emphysema, asthma, rhinitis, eczema, allergy diagnosed by doctor: Blood clot in the leg (DVT)"
168,Cells - Cultured fibroblasts,LV84,Diagnoses - main ICD10: I80 Phlebitis and thrombophlebitis
169,Cells - Cultured fibroblasts,LV84,Palmar fascial fibromatosis [Dupuytren]
170,Cells - Cultured fibroblasts,LV84,"Blood clot, DVT, bronchitis, emphysema, asthma, rhinitis, eczema, allergy diagnosed by doctor: Blood clot in the lung"
171,Cells - Cultured fibroblasts,LV84,Fibroblastic disorders
172,Cells - Cultured fibroblasts,LV84,"Non-cancer illness code, self-reported: pulmonary embolism +/- dvt"
173,Cells - Cultured fibroblasts,LV84,Diagnoses - main ICD10: M72 Fibroblastic disorders
174,Cells - Cultured fibroblasts,LV84,Other ILD-related CVD-co-morbidities
175,Cells - Cultured fibroblasts,LV84,Haemoglobin concentration
176,Cells - Cultured fibroblasts,LV84,Haematocrit percentage
177,Cells - Cultured fibroblasts,LV91,"Non-cancer illness code, self-reported: multiple sclerosis"
178,Cells - Cultured fibroblasts,LV91,Mouth/teeth dental problems: Mouth ulcers
179,Cells - Cultured fibroblasts,LV91,"Blood clot, DVT, bronchitis, emphysema, asthma, rhinitis, eczema, allergy diagnosed by doctor: Hayfever, allergic rhinitis or eczema"
180,Cells - Cultured fibroblasts,LV91,Monocyte percentage
181,Cells - Cultured fibroblasts,LV91,Demyelenating diseases of the central nervous system
182,Cells - Cultured fibroblasts,LV91,Diagnoses - main ICD10: G35 Multiple sclerosis
183,Cells - Cultured fibroblasts,LV91,Rheumatoid arthritis
184,Cells - Cultured fibroblasts,LV91,Diagnoses - main ICD10: M06 Other rheumatoid arthritis
185,Cells - Cultured fibroblasts,LV91,Adult-onset Still disease
186,Cells - Cultured fibroblasts,LV91,"Non-cancer illness code, self-reported: rheumatoid arthritis"
187,Cells - Cultured fibroblasts,LV91,Other/unspecified rheumatoid arthritis
188,Cells - Cultured fibroblasts,LV91,Other/unspecified seropositiverheumatoid arthritis
189,Cells - Cultured fibroblasts,LV91,Monocyte count
190,Cells - Cultured fibroblasts,LV91,Seropositive rheumatoid arthritis
191,Cells - Cultured fibroblasts,LV91,"Blood clot, DVT, bronchitis, emphysema, asthma, rhinitis, eczema, allergy diagnosed by doctor: None of the above"
192,Cells - Cultured fibroblasts,LV91,Diagnoses - main ICD10: M05 Seropositive rheumatoid arthritis
193,Cells - Cultured fibroblasts,LV91,Doctor diagnosed hayfever or allergic rhinitis
194,Cells - Cultured fibroblasts,LV91,Diagnoses - main ICD10: K51 Ulcerative colitis
195,Cells - Cultured fibroblasts,LV91,Suggestive for eosinophilic asthma
196,Cells - Cultured fibroblasts,LV91,#Polyarthropathies
197,Cells - Cultured fibroblasts,LV91,"Non-cancer illness code, self-reported: ulcerative colitis"
198,Cells - Cultured fibroblasts,LV91,Diagnoses - main ICD10: J33 Nasal polyp
199,Cells - Cultured fibroblasts,LV91,"Non-cancer illness code, self-reported: hypothyroidism/myxoedema"
200,Cells - Cultured fibroblasts,LV91,"Age hay fever, rhinitis or eczema diagnosed"
201,Cells - Cultured fibroblasts,LV91,"Ulcerative colitis, NAS"
202,Cells - Cultured fibroblasts,LV91,Age hayfever or allergic rhinitis diagnosed by doctor
203,Cells - Cultured fibroblasts,LV91,"Non-cancer illness code, self-reported: hyperthyroidism/thyrotoxicosis"
204,Cells - Cultured fibroblasts,LV91,Thyrotoxicosis
205,Cells - Cultured fibroblasts,LV91,Diagnoses - main ICD10: E05 Thyrotoxicosis [hyperthyroidism]
206,Cells - Cultured fibroblasts,LV91,Vitamin and mineral supplements: Folic acid or Folate (Vit B9)
207,Cells - Cultured fibroblasts,LV91,Diagnoses - main ICD10: M45 Ankylosing spondylitis
208,Cells - EBV-transformed lymphocytes,LV123,"Pulse rate, automated reading"
209,Cells - EBV-transformed lymphocytes,LV123,Pulse rate
210,Cells - EBV-transformed lymphocytes,LV123,QRS duration
211,Cells - EBV-transformed lymphocytes,LV116,"Blood clot, DVT, bronchitis, emphysema, asthma, rhinitis, eczema, allergy diagnosed by doctor: Blood clot in the leg (DVT)"
212,Cells - EBV-transformed lymphocytes,LV116,"Non-cancer illness code, self-reported: deep venous thrombosis (dvt)"
213,Cells - EBV-transformed lymphocytes,LV116,Diagnoses - main ICD10: I80 Phlebitis and thrombophlebitis
214,Cells - EBV-transformed lymphocytes,LV116,DVT of lower extremities
215,Cells - EBV-transformed lymphocytes,LV116,Venous thromboembolism
216,Cells - EBV-transformed lymphocytes,LV116,"Non-cancer illness code, self-reported: clotting disorder/excessive bleeding"
217,Cells - EBV-transformed lymphocytes,LV244,Number of cigarettes currently smoked daily (current cigarette smokers)
218,Cells - EBV-transformed lymphocytes,LV244,Difficulty not smoking for 1 day
219,Cells - EBV-transformed lymphocytes,LV12,Reason former drinker stopped drinking alcohol: Financial reasons
220,Cells - EBV-transformed lymphocytes,LV406,Number of cigarettes previously smoked daily
221,Cells - EBV-transformed lymphocytes,LV406,Number of cigarettes currently smoked daily (current cigarette smokers)
222,Cells - EBV-transformed lymphocytes,LV406,Palmar fascial fibromatosis [Dupuytren]
223,Esophagus - Mucosa,LV84,Venous thromboembolism
224,Esophagus - Mucosa,LV84,DVT of lower extremities and pulmonary embolism
225,Esophagus - Mucosa,LV84,DVT of lower extremities
226,Esophagus - Mucosa,LV84,Illnesses of mother: Alzheimer's disease/dementia
227,Esophagus - Mucosa,LV84,"Non-cancer illness code, self-reported: deep venous thrombosis (dvt)"
228,Esophagus - Mucosa,LV84,"Blood clot, DVT, bronchitis, emphysema, asthma, rhinitis, eczema, allergy diagnosed by doctor: Blood clot in the leg (DVT)"
229,Esophagus - Mucosa,LV84,Diagnoses - main ICD10: I80 Phlebitis and thrombophlebitis
230,Esophagus - Mucosa,LV84,Palmar fascial fibromatosis [Dupuytren]
231,Esophagus - Mucosa,LV84,"Blood clot, DVT, bronchitis, emphysema, asthma, rhinitis, eczema, allergy diagnosed by doctor: Blood clot in the lung"
232,Esophagus - Mucosa,LV84,Fibroblastic disorders
233,Esophagus - Mucosa,LV84,"Non-cancer illness code, self-reported: pulmonary embolism +/- dvt"
234,Esophagus - Mucosa,LV84,Diagnoses - main ICD10: M72 Fibroblastic disorders
235,Esophagus - Mucosa,LV84,Other ILD-related CVD-co-morbidities
236,Esophagus - Mucosa,LV84,Haemoglobin concentration
237,Esophagus - Mucosa,LV84,Haematocrit percentage
238,Esophagus - Mucosa,LV8,Heel broadband ultrasound attenuation (left)
239,Esophagus - Mucosa,LV8,Heel broadband ultrasound attenuation (right)
240,Esophagus - Mucosa,LV8,Fractured/broken bones in last 5 years
241,Esophagus - Mucosa,LV8,Primary_lymphoid and hematopoietic malignant neoplasms
242,Esophagus - Mucosa,LV8,Diagnoses - main ICD10: Q82 Other congenital malformations of skin
243,Esophagus - Mucosa,LV8,"Job SOC coding: Hairdressers, barbers"
244,Esophagus - Mucosa,LV8,"Cancer code, self-reported: rodent ulcer"
245,Esophagus - Mucosa,LV8,Fractured bone site(s): Wrist
246,Esophagus - Mucosa,LV397,Illnesses of mother: Diabetes
247,Esophagus - Mucosa,LV397,"Non-cancer illness code, self-reported: diabetes"
248,Esophagus - Mucosa,LV397,Illnesses of father: Diabetes

In [85]:
# pct=50%  FDR<0.01  seen_lvs=True
_tpt = top_lvs_at_pct(50)
_df  = trait_table(_tpt, fdr_thresh=0.01, use_seen_lvs=True)
print(f'pct=50%  FDR<0.01  seen_lvs=True  ->  {len(_df)} rows, {_df["Tissue"].nunique()} tissues, {_df["LV"].nunique()} LVs')
_df[['Tissue', 'LV', 'phenotype']]

pct=50%  FDR<0.01  seen_lvs=True  ->  461 rows, 22 tissues, 74 LVs

,Tissue,LV,phenotype
0,Adipose - Subcutaneous,LV378,"Blood clot, DVT, bronchitis, emphysema, asthma, rhinitis, eczema, allergy diagnosed by doctor: Hayfever, allergic rhinitis or eczema"
1,Adipose - Subcutaneous,LV378,Facial ageing
2,Adipose - Subcutaneous,LV378,"Age hay fever, rhinitis or eczema diagnosed"
3,Adipose - Subcutaneous,LV378,"Blood clot, DVT, bronchitis, emphysema, asthma, rhinitis, eczema, allergy diagnosed by doctor: None of the above"
4,Adipose - Subcutaneous,LV145,"Hair colour (natural, before greying): Light brown"
5,Adipose - Subcutaneous,LV111,"Non-cancer illness code, self-reported: rheumatoid arthritis"
6,Adipose - Subcutaneous,LV111,Rheumatoid arthritis
7,Adipose - Subcutaneous,LV111,Other/unspecified seropositiverheumatoid arthritis
8,Adipose - Subcutaneous,LV111,Diagnoses - main ICD10: M06 Other rheumatoid arthritis
9,Adipose - Subcutaneous,LV111,Other/unspecified rheumatoid arthritis
10,Adipose - Subcutaneous,LV111,Adult-onset Still disease
11,Adipose - Subcutaneous,LV111,Diagnoses - main ICD10: M05 Seropositive rheumatoid arthritis
12,Adipose - Subcutaneous,LV111,Seropositive rheumatoid arthritis
13,Adipose - Subcutaneous,LV111,"Non-cancer illness code, self-reported: multiple sclerosis"
14,Adipose - Subcutaneous,LV111,#Polyarthropathies
15,Adipose - Subcutaneous,LV93,High light scatter reticulocyte percentage
16,Adipose - Subcutaneous,LV93,"Non-cancer illness code, self-reported: eczema/dermatitis"
17,Adipose - Subcutaneous,LV93,Reticulocyte percentage
18,Adipose - Subcutaneous,LV93,Reticulocyte count
19,Adipose - Visceral (Omentum),LV376,Heel broadband ultrasound attenuation (right)
20,Adipose - Visceral (Omentum),LV376,Heel broadband ultrasound attenuation (left)
21,Adipose - Visceral (Omentum),LV376,"Heel bone mineral density (BMD) T-score, automated (right)"
22,Adipose - Visceral (Omentum),LV376,"Heel quantitative ultrasound index (QUI), direct entry (right)"
23,Adipose - Visceral (Omentum),LV376,Heel bone mineral density (BMD) (right)
24,Adipose - Visceral (Omentum),LV376,Heel bone mineral density (BMD) (left)
25,Adipose - Visceral (Omentum),LV376,"Heel bone mineral density (BMD) T-score, automated (left)"
26,Adipose - Visceral (Omentum),LV376,"Heel quantitative ultrasound index (QUI), direct entry (left)"
27,Adipose - Visceral (Omentum),LV376,Heel bone mineral density (BMD)
28,Adipose - Visceral (Omentum),LV376,"Heel quantitative ultrasound index (QUI), direct entry"
29,Adipose - Visceral (Omentum),LV376,"Heel bone mineral density (BMD) T-score, automated"
30,Adipose - Visceral (Omentum),LV376,"Heel Broadband ultrasound attenuation, direct entry"
31,Adipose - Visceral (Omentum),LV376,Fractured/broken bones in last 5 years
32,Adipose - Visceral (Omentum),LV376,Diagnoses - main ICD10: N81 Female genital prolapse
33,Adipose - Visceral (Omentum),LV376,Palmar fascial fibromatosis [Dupuytren]
34,Adipose - Visceral (Omentum),LV106,"Disorders of gallbladder, biliary tract and pancreas"
35,Adipose - Visceral (Omentum),LV106,malignant neoplasm of male genital organs
36,Adipose - Visceral (Omentum),LV106,Malignant neoplasm of prostate
37,Adipose - Visceral (Omentum),LV106,Diagnoses - main ICD10: K80 Cholelithiasis
38,Adipose - Visceral (Omentum),LV293,Illnesses of mother: Alzheimer's disease/dementia
39,Adipose - Visceral (Omentum),LV203,malignant neoplasm of male genital organs
40,Adipose - Visceral (Omentum),LV203,Malignant neoplasm of prostate
41,Adipose - Visceral (Omentum),LV203,Mouth/teeth dental problems: Mouth ulcers
42,Adipose - Visceral (Omentum),LV203,Diagnoses - main ICD10: C50 Malignant neoplasm of breast
43,Adipose - Visceral (Omentum),LV329,Which eye(s) affected by myopia (short sight): Both eyes
44,Adrenal Gland,LV3,Basophill percentage
45,Adrenal Gland,LV183,Mouth/teeth dental problems: Mouth ulcers
46,Adrenal Gland,LV183,Basophill count
47,Adrenal Gland,LV183,"Non-cancer illness code, self-reported: ulcerative colitis"
48,Adrenal Gland,LV183,Diagnoses - main ICD10: D61 Other aplastic anaemias
49,Artery - Aorta,LV84,Venous thromboembolism
50,Artery - Aorta,LV84,DVT of lower extremities and pulmonary embolism
51,Artery - Aorta,LV84,DVT of lower extremities
52,Artery - Aorta,LV84,Illnesses of mother: Alzheimer's disease/dementia
53,Artery - Aorta,LV84,"Non-cancer illness code, self-reported: deep venous thrombosis (dvt)"
54,Artery - Aorta,LV84,"Blood clot, DVT, bronchitis, emphysema, asthma, rhinitis, eczema, allergy diagnosed by doctor: Blood clot in the leg (DVT)"
55,Artery - Aorta,LV84,Diagnoses - main ICD10: I80 Phlebitis and thrombophlebitis
56,Artery - Aorta,LV84,Palmar fascial fibromatosis [Dupuytren]
57,Artery - Aorta,LV84,"Blood clot, DVT, bronchitis, emphysema, asthma, rhinitis, eczema, allergy diagnosed by doctor: Blood clot in the lung"
58,Artery - Coronary,LV247,Eye problems/disorders: Glaucoma
59,Artery - Coronary,LV102,Felt loved as a child
60,Artery - Coronary,LV102,Yogurt/ice-cream consumers
61,Artery - Coronary,LV139,"Cancer code, self-reported: multiple myeloma"
62,Artery - Tibial,LV397,Illnesses of mother: Diabetes
63,Artery - Tibial,LV397,"Non-cancer illness code, self-reported: diabetes"
64,Artery - Tibial,LV397,Illnesses of father: Diabetes
65,Artery - Tibial,LV397,Diabetes diagnosed by doctor
66,Artery - Tibial,LV397,"Non-cancer illness code, self-reported: type 2 diabetes"
67,Artery - Tibial,LV397,"Non-cancer illness code, self-reported: gout"
68,Artery - Tibial,LV113,"Non-cancer illness code, self-reported: gout"
69,Artery - Tibial,LV113,Other malignant neoplasms of skin
70,Artery - Tibial,LV113,Diagnoses - main ICD10: C44 Other malignant neoplasms of skin
71,Artery - Tibial,LV87,Spherical power (right)
72,Artery - Tibial,LV87,Spherical power (left)
73,Cells - Cultured fibroblasts,LV180,Diagnoses - main ICD10: M72 Fibroblastic disorders
74,Cells - Cultured fibroblasts,LV180,Fibroblastic disorders
75,Cells - Cultured fibroblasts,LV180,Palmar fascial fibromatosis [Dupuytren]
76,Cells - Cultured fibroblasts,LV180,3mm weak meridian (right)
77,Cells - Cultured fibroblasts,LV180,3mm strong meridian (left)
78,Cells - Cultured fibroblasts,LV180,3mm strong meridian (right)
79,Cells - Cultured fibroblasts,LV180,3mm weak meridian (left)
80,Cells - Cultured fibroblasts,LV180,6mm strong meridian (right)
81,Cells - Cultured fibroblasts,LV180,6mm weak meridian (right)
82,Cells - Cultured fibroblasts,LV180,6mm strong meridian (left)
83,Cells - Cultured fibroblasts,LV180,6mm weak meridian (left)
84,Cells - Cultured fibroblasts,LV336,"Hair colour (natural, before greying): Light brown"
85,Cells - Cultured fibroblasts,LV336,"Hair colour (natural, before greying): Blonde"
86,Cells - Cultured fibroblasts,LV336,"Hair colour (natural, before greying): Black"
87,Cells - Cultured fibroblasts,LV91,"Non-cancer illness code, self-reported: multiple sclerosis"
88,Cells - Cultured fibroblasts,LV91,Mouth/teeth dental problems: Mouth ulcers
89,Cells - Cultured fibroblasts,LV91,"Blood clot, DVT, bronchitis, emphysema, asthma, rhinitis, eczema, allergy diagnosed by doctor: Hayfever, allergic rhinitis or eczema"
90,Cells - Cultured fibroblasts,LV91,Monocyte percentage
91,Cells - Cultured fibroblasts,LV91,Demyelenating diseases of the central nervous system
92,Cells - Cultured fibroblasts,LV91,Diagnoses - main ICD10: G35 Multiple sclerosis
93,Cells - Cultured fibroblasts,LV91,Rheumatoid arthritis
94,Cells - Cultured fibroblasts,LV91,Diagnoses - main ICD10: M06 Other rheumatoid arthritis
95,Cells - Cultured fibroblasts,LV91,Adult-onset Still disease
96,Cells - Cultured fibroblasts,LV91,"Non-cancer illness code, self-reported: rheumatoid arthritis"
97,Cells - Cultured fibroblasts,LV91,Other/unspecified rheumatoid arthritis
98,Cells - Cultured fibroblasts,LV91,Other/unspecified seropositiverheumatoid arthritis
99,Cells - Cultured fibroblasts,LV91,Monocyte count
100,Cells - Cultured fibroblasts,LV91,Seropositive rheumatoid arthritis
101,Cells - Cultured fibroblasts,LV91,"Blood clot, DVT, bronchitis, emphysema, asthma, rhinitis, eczema, allergy diagnosed by doctor: None of the above"
102,Cells - Cultured fibroblasts,LV91,Diagnoses - main ICD10: M05 Seropositive rheumatoid arthritis
103,Cells - Cultured fibroblasts,LV91,Doctor diagnosed hayfever or allergic rhinitis
104,Cells - Cultured fibroblasts,LV91,Diagnoses - main ICD10: K51 Ulcerative colitis
105,Cells - Cultured fibroblasts,LV91,Suggestive for eosinophilic asthma
106,Cells - Cultured fibroblasts,LV91,#Polyarthropathies
107,Cells - Cultured fibroblasts,LV91,"Non-cancer illness code, self-reported: ulcerative colitis"
108,Cells - Cultured fibroblasts,LV91,Diagnoses - main ICD10: J33 Nasal polyp
109,Cells - Cultured fibroblasts,LV91,"Non-cancer illness code, self-reported: hypothyroidism/myxoedema"
110,Cells - Cultured fibroblasts,LV109,All anxiety disorders
111,Cells - Cultured fibroblasts,LV109,Anxiety (asthma-related co-morbidities)
112,Cells - Cultured fibroblasts,LV5,Mouth/teeth dental problems: Mouth ulcers
113,Cells - EBV-transformed lymphocytes,LV123,"Pulse rate, automated reading"
114,Cells - EBV-transformed lymphocytes,LV123,Pulse rate
115,Cells - EBV-transformed lymphocytes,LV123,QRS duration
116,Cells - EBV-transformed lymphocytes,LV116,"Blood clot, DVT, bronchitis, emphysema, asthma, rhinitis, eczema, allergy diagnosed by doctor: Blood clot in the leg (DVT)"
117,Cells - EBV-transformed lymphocytes,LV116,"Non-cancer illness code, self-reported: deep venous thrombosis (dvt)"
118,Cells - EBV-transformed lymphocytes,LV116,Diagnoses - main ICD10: I80 Phlebitis and thrombophlebitis
119,Cells - EBV-transformed lymphocytes,LV116,DVT of lower extremities
120,Cells - EBV-transformed lymphocytes,LV244,Number of cigarettes currently smoked daily (current cigarette smokers)
121,Cells - EBV-transformed lymphocytes,LV406,Number of cigarettes previously smoked daily
122,Cells - EBV-transformed lymphocytes,LV340,"Diagnoses - main ICD10: F05 Delirium, not induced by alcohol and other psychoactive substances"
123,Cells - EBV-transformed lymphocytes,LV1,"Non-cancer illness code, self-reported: deep venous thrombosis (dvt)"
124,Cells - EBV-transformed lymphocytes,LV1,"Blood clot, DVT, bronchitis, emphysema, asthma, rhinitis, eczema, allergy diagnosed by doctor: Blood clot in the leg (DVT)"
125,Cells - EBV-transformed lymphocytes,LV1,Diagnoses - main ICD10: I80 Phlebitis and thrombophlebitis
126,Cells - EBV-transformed lymphocytes,LV1,"Non-cancer illness code, self-reported: clotting disorder/excessive bleeding"
127,Cells - EBV-transformed lymphocytes,LV1,DVT of lower extremities
128,Cells - EBV-transformed lymphocytes,LV375,"Worked with paints, thinners or glues: Often"
129,Esophagus - Mucosa,LV8,Heel broadband ultrasound attenuation (left)
130,Esophagus - Mucosa,LV8,Heel broadband ultrasound attenuation (right)
131,Esophagus - Mucosa,LV8,Fractured/broken bones in last 5 years
132,Esophagus - Mucosa,LV8,Primary_lymphoid and hematopoietic malignant neoplasms
133,Esophagus - Mucosa,LV62,Waist circumference
134,Esophagus - Mucosa,LV132,Mouth/teeth dental problems: Mouth ulcers
135,Esophagus - Mucosa,LV132,Diagnoses - main ICD10: I20 Angina pectoris
136,Heart - Atrial Appendage,LV282,Job SOC coding: Medical secretaries
137,Heart - Atrial Appendage,LV282,"Non-cancer illness code, self-reported: gout"
138,Heart - Atrial Appendage,LV18,Number of cigarettes previously smoked daily
139,Heart - Left Ventricle,LV248,"Blood clot, DVT, bronchitis, emphysema, asthma, rhinitis, eczema, allergy diagnosed by doctor: None of the above"
140,Heart - Left Ventricle,LV248,"Blood clot, DVT, bronchitis, emphysema, asthma, rhinitis, eczema, allergy diagnosed by doctor: Hayfever, allergic rhinitis or eczema"
141,Heart - Left Ventricle,LV248,Age asthma diagnosed
142,Heart - Left Ventricle,LV248,Mouth/teeth dental problems: Mouth ulcers
143,Heart - Left Ventricle,LV363,Basophill percentage
144,Heart - Left Ventricle,LV363,Eosinophill count
145,Heart - Left Ventricle,LV363,Lymphocyte count
146,Heart - Left Ventricle,LV363,Eosinophill percentage
147,Heart - Left Ventricle,LV363,"Medication for cholesterol, blood pressure or diabetes: Blood pressure medication"
148,Heart - Left Ventricle,LV363,Basophill count
149,Heart - Left Ventricle,LV44,Diagnoses - main ICD10: K40 Inguinal hernia
150,Heart - Left Ventricle,LV24,"Malignant neoplasm, without specification of site"
151,Heart - Left Ventricle,LV365,"Heel bone mineral density (BMD) T-score, automated (left)"
152,Heart - Left Ventricle,LV365,"Heel quantitative ultrasound index (QUI), direct entry (left)"
153,Heart - Left Ventricle,LV365,Heel bone mineral density (BMD) (left)
154,Heart - Left Ventricle,LV365,Heel bone mineral density (BMD)
155,Heart - Left Ventricle,LV365,"Heel quantitative ultrasound index (QUI), direct entry (right)"
156,Heart - Left Ventricle,LV365,"Heel bone mineral density (BMD) T-score, automated (right)"
157,Heart - Left Ventricle,LV365,"Heel quantitative ultrasound index (QUI), direct entry"
158,Heart - Left Ventricle,LV365,"Heel bone mineral density (BMD) T-score, automated"
159,Liver,LV50,"Non-cancer illness code, self-reported: gout"
160,Liver,LV21,"Non-cancer illness code, self-reported: high cholesterol"
161,Liver,LV21,"Non-cancer illness code, self-reported: cholelithiasis/gall stones"
162,Liver,LV21,"Medication for cholesterol, blood pressure or diabetes: Cholesterol lowering medication"
163,Liver,LV21,Diagnoses - main ICD10: K80 Cholelithiasis
164,Liver,LV21,"Medication for cholesterol, blood pressure, diabetes, or take exogenous hormones: Cholesterol lowering medication"
165,Liver,LV21,"Disorders of gallbladder, biliary tract and pancreas"
166,Liver,LV366,3mm weak meridian (right)
167,Liver,LV366,3mm strong meridian (right)
168,Liver,LV366,3mm strong meridian (left)
169,Liver,LV366,3mm weak meridian (left)
170,Liver,LV366,Heel broadband ultrasound attenuation (right)
171,Liver,LV366,Heel broadband ultrasound attenuation (left)
172,Liver,LV366,6mm strong meridian (right)
173,Liver,LV366,6mm strong meridian (left)
174,Liver,LV366,6mm weak meridian (left)
175,Liver,LV366,6mm weak meridian (right)
176,Liver,LV366,Diagnoses - main ICD10: M72 Fibroblastic disorders
177,Liver,LV366,Fibroblastic disorders
178,Liver,LV366,Palmar fascial fibromatosis [Dupuytren]
179,Liver,LV366,Age started wearing glasses or contact lenses
180,Liver,LV314,Illnesses of mother: Alzheimer's disease/dementia
181,Liver,LV314,"Non-cancer illness code, self-reported: high cholesterol"
182,Liver,LV108,"Non-cancer illness code, self-reported: eye trauma"
183,Liver,LV121,3mm strong meridian (left)
184,Liver,LV121,3mm strong meridian (right)
185,Liver,LV121,3mm weak meridian (right)
186,Liver,LV121,3mm weak meridian (left)
187,Liver,LV121,6mm strong meridian (left)
188,Liver,LV121,6mm strong meridian (right)
189,Liver,LV121,6mm weak meridian (left)
190,Liver,LV121,6mm weak meridian (right)
191,Liver,LV121,Diagnoses - main ICD10: M72 Fibroblastic disorders
192,Liver,LV121,Palmar fascial fibromatosis [Dupuytren]
193,Liver,LV121,Fibroblastic disorders
194,Lung,LV26,Mouth/teeth dental problems: Mouth ulcers
195,Lung,LV26,"Diagnoses - main ICD10: R60 Oedema, not elsewhere classified"
196,Lung,LV191,Basophill percentage
197,Lung,LV369,Mouth/teeth dental problems: Mouth ulcers
198,Lung,LV369,Lymphocyte percentage
199,Lung,LV369,Neutrophill percentage
200,Lung,LV369,Eosinophill percentage
201,Lung,LV239,Corneal resistance factor (right)
202,Lung,LV239,Hernia
203,Lung,LV239,Corneal resistance factor (left)
204,Lung,LV239,Diagnoses - main ICD10: K40 Inguinal hernia
205,Minor Salivary Gland,LV58,Diagnoses - main ICD10: E83 Disorders of mineral metabolism
206,Minor Salivary Gland,LV58,Lymphocyte percentage
207,Minor Salivary Gland,LV58,Neutrophill percentage
208,Minor Salivary Gland,LV324,"Non-cancer illness code, self-reported: malabsorption/coeliac disease"
209,Minor Salivary Gland,LV324,"Non-cancer illness code, self-reported: sarcoidosis"
210,Minor Salivary Gland,LV324,"Never eat eggs, dairy, wheat, sugar: Wheat products"
211,Minor Salivary Gland,LV324,Coeliac disease
212,Minor Salivary Gland,LV324,Diagnoses - main ICD10: K90 Intestinal malabsorption
213,Minor Salivary Gland,LV324,"Non-cancer illness code, self-reported: hyperthyroidism/thyrotoxicosis"
214,Minor Salivary Gland,LV324,"Blood clot, DVT, bronchitis, emphysema, asthma, rhinitis, eczema, allergy diagnosed by doctor: Asthma"
215,Minor Salivary Gland,LV324,"Non-cancer illness code, self-reported: asthma"
216,Minor Salivary Gland,LV324,Bread type: Other type of bread
217,Minor Salivary Gland,LV324,Other diseases of the digestive system
218,Minor Salivary Gland,LV324,Doctor diagnosed sarcoidosis
219,Minor Salivary Gland,LV324,"Non-cancer illness code, self-reported: systemic lupus erythematosis/sle"
220,Minor Salivary Gland,LV324,Eosinophill count
221,Minor Salivary Gland,LV324,"Medication for cholesterol, blood pressure, diabetes, or take exogenous hormones: Insulin"
222,Minor Salivary Gland,LV324,Type of special diet followed: Gluten-free
223,Minor Salivary Gland,LV324,Diagnoses - main ICD10: R31 Unspecified haematuria
224,Minor Salivary Gland,LV324,"Non-cancer illness code, self-reported: hypothyroidism/myxoedema"
225,Minor Salivary Gland,LV324,"Medication for cholesterol, blood pressure or diabetes: Insulin"
226,Minor Salivary Gland,LV324,Started insulin within one year diagnosis of diabetes
227,Minor Salivary Gland,LV324,"Blood clot, DVT, bronchitis, emphysema, asthma, rhinitis, eczema, allergy diagnosed by doctor: None of the above"
228,Minor Salivary Gland,LV324,"Cereal type: Other (e.g. Cornflakes, Frosties)"
229,Minor Salivary Gland,LV324,"Non-cancer illness code, self-reported: type 1 diabetes"
230,Minor Salivary Gland,LV324,"Non-cancer illness code, self-reported: adrenocortical insufficiency/addison's disease"
231,Minor Salivary Gland,LV324,Doctor diagnosed asthma
232,Minor Salivary Gland,LV324,Age diabetes diagnosed
233,Minor Salivary Gland,LV324,White blood cell (leukocyte) count
234,Minor Salivary Gland,LV324,Lymphocyte count
235,Minor Salivary Gland,LV324,"Blood clot, DVT, bronchitis, emphysema, asthma, rhinitis, eczema, allergy diagnosed by doctor: Hayfever, allergic rhinitis or eczema"
236,Minor Salivary Gland,LV324,Type 1 diabetes
237,Minor Salivary Gland,LV324,Diagnoses - main ICD10: E10 Insulin-dependent diabetes mellitus
238,Minor Salivary Gland,LV324,Doctor diagnosed hayfever or allergic rhinitis
239,Minor Salivary Gland,LV324,"Non-cancer illness code, self-reported: psoriasis"
240,Minor Salivary Gland,LV324,Type 1 diabetes with ophthalmic complications
241,Minor Salivary Gland,LV324,Unclassified diabetic retinopathy
242,Minor Salivary Gland,LV324,"Non-cancer illness code, self-reported: sjogren's syndrome/sicca syndrome"
243,Minor Salivary Gland,LV324,Diabetic ketoacidosis
244,Minor Salivary Gland,LV324,"Non-cancer illness code, self-reported: hayfever/allergic rhinitis"
245,Minor Salivary Gland,LV324,Eosinophill percentage
246,Minor Salivary Gland,LV324,Other serious medical condition/disability diagnosed by doctor
247,Minor Salivary Gland,LV324,Type 1 diabetes with ketoacidosis
248,Minor Salivary Gland,LV324,Illnesses of siblings: Diabetes
249,Minor Salivary Gland,LV324,Diagnoses - main ICD10: E05 Thyrotoxicosis [hyperthyroidism]
250,Minor Salivary Gland,LV324,Thyrotoxicosis
251,Minor Salivary Gland,LV324,Thyrotoxicosis with diffuse goitr
252,Minor Salivary Gland,LV324,Diagnoses - main ICD10: N40 Hyperplasia of prostate
253,Minor Salivary Gland,LV324,Diseases of the blood and blood-forming organs and certain disorders involving the immune mechanism
254,Minor Salivary Gland,LV324,"Endocrine, nutritional and metabolic diseases"
255,Minor Salivary Gland,LV324,"Long-standing illness, disability or infirmity"
256,Minor Salivary Gland,LV324,"Non-cancer illness code, self-reported: polymyalgia rheumatica"
257,Minor Salivary Gland,LV324,"Never eat eggs, dairy, wheat, sugar: I eat all of the above"

In [86]:
# pct=50%  FDR<0.01  seen_lvs=False
_tpt = top_lvs_at_pct(50)
_df  = trait_table(_tpt, fdr_thresh=0.01, use_seen_lvs=False)
print(f'pct=50%  FDR<0.01  seen_lvs=False  ->  {len(_df)} rows, {_df["Tissue"].nunique()} tissues, {_df["LV"].nunique()} LVs')
_df[['Tissue', 'LV', 'phenotype']]

pct=50%  FDR<0.01  seen_lvs=False  ->  875 rows, 25 tissues, 74 LVs

,Tissue,LV,phenotype
0,Adipose - Subcutaneous,LV378,"Blood clot, DVT, bronchitis, emphysema, asthma, rhinitis, eczema, allergy diagnosed by doctor: Hayfever, allergic rhinitis or eczema"
1,Adipose - Subcutaneous,LV378,Facial ageing
2,Adipose - Subcutaneous,LV378,"Age hay fever, rhinitis or eczema diagnosed"
3,Adipose - Subcutaneous,LV378,"Blood clot, DVT, bronchitis, emphysema, asthma, rhinitis, eczema, allergy diagnosed by doctor: None of the above"
4,Adipose - Subcutaneous,LV145,"Hair colour (natural, before greying): Light brown"
5,Adipose - Subcutaneous,LV111,"Non-cancer illness code, self-reported: rheumatoid arthritis"
6,Adipose - Subcutaneous,LV111,Rheumatoid arthritis
7,Adipose - Subcutaneous,LV111,Other/unspecified seropositiverheumatoid arthritis
8,Adipose - Subcutaneous,LV111,Diagnoses - main ICD10: M06 Other rheumatoid arthritis
9,Adipose - Subcutaneous,LV111,Other/unspecified rheumatoid arthritis
10,Adipose - Subcutaneous,LV111,Adult-onset Still disease
11,Adipose - Subcutaneous,LV111,Diagnoses - main ICD10: M05 Seropositive rheumatoid arthritis
12,Adipose - Subcutaneous,LV111,Seropositive rheumatoid arthritis
13,Adipose - Subcutaneous,LV111,"Non-cancer illness code, self-reported: multiple sclerosis"
14,Adipose - Subcutaneous,LV111,#Polyarthropathies
15,Adipose - Subcutaneous,LV93,High light scatter reticulocyte percentage
16,Adipose - Subcutaneous,LV93,"Non-cancer illness code, self-reported: eczema/dermatitis"
17,Adipose - Subcutaneous,LV93,Reticulocyte percentage
18,Adipose - Subcutaneous,LV93,Reticulocyte count
19,Adipose - Visceral (Omentum),LV376,Heel broadband ultrasound attenuation (right)
20,Adipose - Visceral (Omentum),LV376,Heel broadband ultrasound attenuation (left)
21,Adipose - Visceral (Omentum),LV376,"Heel bone mineral density (BMD) T-score, automated (right)"
22,Adipose - Visceral (Omentum),LV376,"Heel quantitative ultrasound index (QUI), direct entry (right)"
23,Adipose - Visceral (Omentum),LV376,Heel bone mineral density (BMD) (right)
24,Adipose - Visceral (Omentum),LV376,Heel bone mineral density (BMD) (left)
25,Adipose - Visceral (Omentum),LV376,"Heel bone mineral density (BMD) T-score, automated (left)"
26,Adipose - Visceral (Omentum),LV376,"Heel quantitative ultrasound index (QUI), direct entry (left)"
27,Adipose - Visceral (Omentum),LV376,Heel bone mineral density (BMD)
28,Adipose - Visceral (Omentum),LV376,"Heel quantitative ultrasound index (QUI), direct entry"
29,Adipose - Visceral (Omentum),LV376,"Heel bone mineral density (BMD) T-score, automated"
30,Adipose - Visceral (Omentum),LV376,"Heel Broadband ultrasound attenuation, direct entry"
31,Adipose - Visceral (Omentum),LV376,Fractured/broken bones in last 5 years
32,Adipose - Visceral (Omentum),LV376,Diagnoses - main ICD10: N81 Female genital prolapse
33,Adipose - Visceral (Omentum),LV376,Palmar fascial fibromatosis [Dupuytren]
34,Adipose - Visceral (Omentum),LV106,"Disorders of gallbladder, biliary tract and pancreas"
35,Adipose - Visceral (Omentum),LV106,malignant neoplasm of male genital organs
36,Adipose - Visceral (Omentum),LV106,Malignant neoplasm of prostate
37,Adipose - Visceral (Omentum),LV106,Diagnoses - main ICD10: K80 Cholelithiasis
38,Adipose - Visceral (Omentum),LV293,Illnesses of mother: Alzheimer's disease/dementia
39,Adipose - Visceral (Omentum),LV203,malignant neoplasm of male genital organs
40,Adipose - Visceral (Omentum),LV203,Malignant neoplasm of prostate
41,Adipose - Visceral (Omentum),LV203,Mouth/teeth dental problems: Mouth ulcers
42,Adipose - Visceral (Omentum),LV203,Diagnoses - main ICD10: C50 Malignant neoplasm of breast
43,Adipose - Visceral (Omentum),LV329,Which eye(s) affected by myopia (short sight): Both eyes
44,Adipose - Visceral (Omentum),LV378,"Blood clot, DVT, bronchitis, emphysema, asthma, rhinitis, eczema, allergy diagnosed by doctor: Hayfever, allergic rhinitis or eczema"
45,Adipose - Visceral (Omentum),LV378,Facial ageing
46,Adipose - Visceral (Omentum),LV378,"Age hay fever, rhinitis or eczema diagnosed"
47,Adipose - Visceral (Omentum),LV378,"Blood clot, DVT, bronchitis, emphysema, asthma, rhinitis, eczema, allergy diagnosed by doctor: None of the above"
48,Adrenal Gland,LV3,Basophill percentage
49,Adrenal Gland,LV183,Mouth/teeth dental problems: Mouth ulcers
50,Adrenal Gland,LV183,Basophill count
51,Adrenal Gland,LV183,"Non-cancer illness code, self-reported: ulcerative colitis"
52,Adrenal Gland,LV183,Diagnoses - main ICD10: D61 Other aplastic anaemias
53,Artery - Aorta,LV145,"Hair colour (natural, before greying): Light brown"
54,Artery - Aorta,LV84,Venous thromboembolism
55,Artery - Aorta,LV84,DVT of lower extremities and pulmonary embolism
56,Artery - Aorta,LV84,DVT of lower extremities
57,Artery - Aorta,LV84,Illnesses of mother: Alzheimer's disease/dementia
58,Artery - Aorta,LV84,"Non-cancer illness code, self-reported: deep venous thrombosis (dvt)"
59,Artery - Aorta,LV84,"Blood clot, DVT, bronchitis, emphysema, asthma, rhinitis, eczema, allergy diagnosed by doctor: Blood clot in the leg (DVT)"
60,Artery - Aorta,LV84,Diagnoses - main ICD10: I80 Phlebitis and thrombophlebitis
61,Artery - Aorta,LV84,Palmar fascial fibromatosis [Dupuytren]
62,Artery - Aorta,LV84,"Blood clot, DVT, bronchitis, emphysema, asthma, rhinitis, eczema, allergy diagnosed by doctor: Blood clot in the lung"
63,Artery - Coronary,LV247,Eye problems/disorders: Glaucoma
64,Artery - Coronary,LV102,Felt loved as a child
65,Artery - Coronary,LV102,Yogurt/ice-cream consumers
66,Artery - Coronary,LV106,"Disorders of gallbladder, biliary tract and pancreas"
67,Artery - Coronary,LV106,malignant neoplasm of male genital organs
68,Artery - Coronary,LV106,Malignant neoplasm of prostate
69,Artery - Coronary,LV106,Diagnoses - main ICD10: K80 Cholelithiasis
70,Artery - Coronary,LV84,Venous thromboembolism
71,Artery - Coronary,LV84,DVT of lower extremities and pulmonary embolism
72,Artery - Coronary,LV84,DVT of lower extremities
73,Artery - Coronary,LV84,Illnesses of mother: Alzheimer's disease/dementia
74,Artery - Coronary,LV84,"Non-cancer illness code, self-reported: deep venous thrombosis (dvt)"
75,Artery - Coronary,LV84,"Blood clot, DVT, bronchitis, emphysema, asthma, rhinitis, eczema, allergy diagnosed by doctor: Blood clot in the leg (DVT)"
76,Artery - Coronary,LV84,Diagnoses - main ICD10: I80 Phlebitis and thrombophlebitis
77,Artery - Coronary,LV84,Palmar fascial fibromatosis [Dupuytren]
78,Artery - Coronary,LV84,"Blood clot, DVT, bronchitis, emphysema, asthma, rhinitis, eczema, allergy diagnosed by doctor: Blood clot in the lung"
79,Artery - Coronary,LV203,malignant neoplasm of male genital organs
80,Artery - Coronary,LV203,Malignant neoplasm of prostate
81,Artery - Coronary,LV203,Mouth/teeth dental problems: Mouth ulcers
82,Artery - Coronary,LV203,Diagnoses - main ICD10: C50 Malignant neoplasm of breast
83,Artery - Coronary,LV139,"Cancer code, self-reported: multiple myeloma"
84,Artery - Tibial,LV397,Illnesses of mother: Diabetes
85,Artery - Tibial,LV397,"Non-cancer illness code, self-reported: diabetes"
86,Artery - Tibial,LV397,Illnesses of father: Diabetes
87,Artery - Tibial,LV397,Diabetes diagnosed by doctor
88,Artery - Tibial,LV397,"Non-cancer illness code, self-reported: type 2 diabetes"
89,Artery - Tibial,LV397,"Non-cancer illness code, self-reported: gout"
90,Artery - Tibial,LV102,Felt loved as a child
91,Artery - Tibial,LV102,Yogurt/ice-cream consumers
92,Artery - Tibial,LV84,Venous thromboembolism
93,Artery - Tibial,LV84,DVT of lower extremities and pulmonary embolism
94,Artery - Tibial,LV84,DVT of lower extremities
95,Artery - Tibial,LV84,Illnesses of mother: Alzheimer's disease/dementia
96,Artery - Tibial,LV84,"Non-cancer illness code, self-reported: deep venous thrombosis (dvt)"
97,Artery - Tibial,LV84,"Blood clot, DVT, bronchitis, emphysema, asthma, rhinitis, eczema, allergy diagnosed by doctor: Blood clot in the leg (DVT)"
98,Artery - Tibial,LV84,Diagnoses - main ICD10: I80 Phlebitis and thrombophlebitis
99,Artery - Tibial,LV84,Palmar fascial fibromatosis [Dupuytren]
100,Artery - Tibial,LV84,"Blood clot, DVT, bronchitis, emphysema, asthma, rhinitis, eczema, allergy diagnosed by doctor: Blood clot in the lung"
101,Artery - Tibial,LV113,"Non-cancer illness code, self-reported: gout"
102,Artery - Tibial,LV113,Other malignant neoplasms of skin
103,Artery - Tibial,LV113,Diagnoses - main ICD10: C44 Other malignant neoplasms of skin
104,Artery - Tibial,LV139,"Cancer code, self-reported: multiple myeloma"
105,Artery - Tibial,LV87,Spherical power (right)
106,Artery - Tibial,LV87,Spherical power (left)
107,Artery - Tibial,LV93,High light scatter reticulocyte percentage
108,Artery - Tibial,LV93,"Non-cancer illness code, self-reported: eczema/dermatitis"
109,Artery - Tibial,LV93,Reticulocyte percentage
110,Artery - Tibial,LV93,Reticulocyte count
111,Artery - Tibial,LV203,malignant neoplasm of male genital organs
112,Artery - Tibial,LV203,Malignant neoplasm of prostate
113,Artery - Tibial,LV203,Mouth/teeth dental problems: Mouth ulcers
114,Artery - Tibial,LV203,Diagnoses - main ICD10: C50 Malignant neoplasm of breast
115,Cells - Cultured fibroblasts,LV111,"Non-cancer illness code, self-reported: rheumatoid arthritis"
116,Cells - Cultured fibroblasts,LV111,Rheumatoid arthritis
117,Cells - Cultured fibroblasts,LV111,Other/unspecified seropositiverheumatoid arthritis
118,Cells - Cultured fibroblasts,LV111,Diagnoses - main ICD10: M06 Other rheumatoid arthritis
119,Cells - Cultured fibroblasts,LV111,Other/unspecified rheumatoid arthritis
120,Cells - Cultured fibroblasts,LV111,Adult-onset Still disease
121,Cells - Cultured fibroblasts,LV111,Diagnoses - main ICD10: M05 Seropositive rheumatoid arthritis
122,Cells - Cultured fibroblasts,LV111,Seropositive rheumatoid arthritis
123,Cells - Cultured fibroblasts,LV111,"Non-cancer illness code, self-reported: multiple sclerosis"
124,Cells - Cultured fibroblasts,LV111,#Polyarthropathies
125,Cells - Cultured fibroblasts,LV180,Diagnoses - main ICD10: M72 Fibroblastic disorders
126,Cells - Cultured fibroblasts,LV180,Fibroblastic disorders
127,Cells - Cultured fibroblasts,LV180,Palmar fascial fibromatosis [Dupuytren]
128,Cells - Cultured fibroblasts,LV180,3mm weak meridian (right)
129,Cells - Cultured fibroblasts,LV180,3mm strong meridian (left)
130,Cells - Cultured fibroblasts,LV180,3mm strong meridian (right)
131,Cells - Cultured fibroblasts,LV180,3mm weak meridian (left)
132,Cells - Cultured fibroblasts,LV180,6mm strong meridian (right)
133,Cells - Cultured fibroblasts,LV180,6mm weak meridian (right)
134,Cells - Cultured fibroblasts,LV180,6mm strong meridian (left)
135,Cells - Cultured fibroblasts,LV180,6mm weak meridian (left)
136,Cells - Cultured fibroblasts,LV336,"Hair colour (natural, before greying): Light brown"
137,Cells - Cultured fibroblasts,LV336,"Hair colour (natural, before greying): Blonde"
138,Cells - Cultured fibroblasts,LV336,"Hair colour (natural, before greying): Black"
139,Cells - Cultured fibroblasts,LV84,Venous thromboembolism
140,Cells - Cultured fibroblasts,LV84,DVT of lower extremities and pulmonary embolism
141,Cells - Cultured fibroblasts,LV84,DVT of lower extremities
142,Cells - Cultured fibroblasts,LV84,Illnesses of mother: Alzheimer's disease/dementia
143,Cells - Cultured fibroblasts,LV84,"Non-cancer illness code, self-reported: deep venous thrombosis (dvt)"
144,Cells - Cultured fibroblasts,LV84,"Blood clot, DVT, bronchitis, emphysema, asthma, rhinitis, eczema, allergy diagnosed by doctor: Blood clot in the leg (DVT)"
145,Cells - Cultured fibroblasts,LV84,Diagnoses - main ICD10: I80 Phlebitis and thrombophlebitis
146,Cells - Cultured fibroblasts,LV84,Palmar fascial fibromatosis [Dupuytren]
147,Cells - Cultured fibroblasts,LV84,"Blood clot, DVT, bronchitis, emphysema, asthma, rhinitis, eczema, allergy diagnosed by doctor: Blood clot in the lung"
148,Cells - Cultured fibroblasts,LV91,"Non-cancer illness code, self-reported: multiple sclerosis"
149,Cells - Cultured fibroblasts,LV91,Mouth/teeth dental problems: Mouth ulcers
150,Cells - Cultured fibroblasts,LV91,"Blood clot, DVT, bronchitis, emphysema, asthma, rhinitis, eczema, allergy diagnosed by doctor: Hayfever, allergic rhinitis or eczema"
151,Cells - Cultured fibroblasts,LV91,Monocyte percentage
152,Cells - Cultured fibroblasts,LV91,Demyelenating diseases of the central nervous system
153,Cells - Cultured fibroblasts,LV91,Diagnoses - main ICD10: G35 Multiple sclerosis
154,Cells - Cultured fibroblasts,LV91,Rheumatoid arthritis
155,Cells - Cultured fibroblasts,LV91,Diagnoses - main ICD10: M06 Other rheumatoid arthritis
156,Cells - Cultured fibroblasts,LV91,Adult-onset Still disease
157,Cells - Cultured fibroblasts,LV91,"Non-cancer illness code, self-reported: rheumatoid arthritis"
158,Cells - Cultured fibroblasts,LV91,Other/unspecified rheumatoid arthritis
159,Cells - Cultured fibroblasts,LV91,Other/unspecified seropositiverheumatoid arthritis
160,Cells - Cultured fibroblasts,LV91,Monocyte count
161,Cells - Cultured fibroblasts,LV91,Seropositive rheumatoid arthritis
162,Cells - Cultured fibroblasts,LV91,"Blood clot, DVT, bronchitis, emphysema, asthma, rhinitis, eczema, allergy diagnosed by doctor: None of the above"
163,Cells - Cultured fibroblasts,LV91,Diagnoses - main ICD10: M05 Seropositive rheumatoid arthritis
164,Cells - Cultured fibroblasts,LV91,Doctor diagnosed hayfever or allergic rhinitis
165,Cells - Cultured fibroblasts,LV91,Diagnoses - main ICD10: K51 Ulcerative colitis
166,Cells - Cultured fibroblasts,LV91,Suggestive for eosinophilic asthma
167,Cells - Cultured fibroblasts,LV91,#Polyarthropathies
168,Cells - Cultured fibroblasts,LV91,"Non-cancer illness code, self-reported: ulcerative colitis"
169,Cells - Cultured fibroblasts,LV91,Diagnoses - main ICD10: J33 Nasal polyp
170,Cells - Cultured fibroblasts,LV91,"Non-cancer illness code, self-reported: hypothyroidism/myxoedema"
171,Cells - Cultured fibroblasts,LV109,All anxiety disorders
172,Cells - Cultured fibroblasts,LV109,Anxiety (asthma-related co-morbidities)
173,Cells - Cultured fibroblasts,LV5,Mouth/teeth dental problems: Mouth ulcers
174,Cells - EBV-transformed lymphocytes,LV123,"Pulse rate, automated reading"
175,Cells - EBV-transformed lymphocytes,LV123,Pulse rate
176,Cells - EBV-transformed lymphocytes,LV123,QRS duration
177,Cells - EBV-transformed lymphocytes,LV116,"Blood clot, DVT, bronchitis, emphysema, asthma, rhinitis, eczema, allergy diagnosed by doctor: Blood clot in the leg (DVT)"
178,Cells - EBV-transformed lymphocytes,LV116,"Non-cancer illness code, self-reported: deep venous thrombosis (dvt)"
179,Cells - EBV-transformed lymphocytes,LV116,Diagnoses - main ICD10: I80 Phlebitis and thrombophlebitis
180,Cells - EBV-transformed lymphocytes,LV116,DVT of lower extremities
181,Cells - EBV-transformed lymphocytes,LV244,Number of cigarettes currently smoked daily (current cigarette smokers)
182,Cells - EBV-transformed lymphocytes,LV406,Number of cigarettes previously smoked daily
183,Cells - EBV-transformed lymphocytes,LV145,"Hair colour (natural, before greying): Light brown"
184,Cells - EBV-transformed lymphocytes,LV340,"Diagnoses - main ICD10: F05 Delirium, not induced by alcohol and other psychoactive substances"
185,Cells - EBV-transformed lymphocytes,LV1,"Non-cancer illness code, self-reported: deep venous thrombosis (dvt)"
186,Cells - EBV-transformed lymphocytes,LV1,"Blood clot, DVT, bronchitis, emphysema, asthma, rhinitis, eczema, allergy diagnosed by doctor: Blood clot in the leg (DVT)"
187,Cells - EBV-transformed lymphocytes,LV1,Diagnoses - main ICD10: I80 Phlebitis and thrombophlebitis
188,Cells - EBV-transformed lymphocytes,LV1,"Non-cancer illness code, self-reported: clotting disorder/excessive bleeding"
189,Cells - EBV-transformed lymphocytes,LV1,DVT of lower extremities
190,Cells - EBV-transformed lymphocytes,LV375,"Worked with paints, thinners or glues: Often"
191,Esophagus - Mucosa,LV84,Venous thromboembolism
192,Esophagus - Mucosa,LV84,DVT of lower extremities and pulmonary embolism
193,Esophagus - Mucosa,LV84,DVT of lower extremities
194,Esophagus - Mucosa,LV84,Illnesses of mother: Alzheimer's disease/dementia
195,Esophagus - Mucosa,LV84,"Non-cancer illness code, self-reported: deep venous thrombosis (dvt)"
196,Esophagus - Mucosa,LV84,"Blood clot, DVT, bronchitis, emphysema, asthma, rhinitis, eczema, allergy diagnosed by doctor: Blood clot in the leg (DVT)"
197,Esophagus - Mucosa,LV84,Diagnoses - main ICD10: I80 Phlebitis and thrombophlebitis
198,Esophagus - Mucosa,LV84,Palmar fascial fibromatosis [Dupuytren]
199,Esophagus - Mucosa,LV84,"Blood clot, DVT, bronchitis, emphysema, asthma, rhinitis, eczema, allergy diagnosed by doctor: Blood clot in the lung"
200,Esophagus - Mucosa,LV8,Heel broadband ultrasound attenuation (left)
201,Esophagus - Mucosa,LV8,Heel broadband ultrasound attenuation (right)
202,Esophagus - Mucosa,LV8,Fractured/broken bones in last 5 years
203,Esophagus - Mucosa,LV8,Primary_lymphoid and hematopoietic malignant neoplasms
204,Esophagus - Mucosa,LV397,Illnesses of mother: Diabetes
205,Esophagus - Mucosa,LV397,"Non-cancer illness code, self-reported: diabetes"
206,Esophagus - Mucosa,LV397,Illnesses of father: Diabetes
207,Esophagus - Mucosa,LV397,Diabetes diagnosed by doctor
208,Esophagus - Mucosa,LV397,"Non-cancer illness code, self-reported: type 2 diabetes"
209,Esophagus - Mucosa,LV397,"Non-cancer illness code, self-reported: gout"
210,Esophagus - Mucosa,LV62,Waist circumference
211,Esophagus - Mucosa,LV132,Mouth/teeth dental problems: Mouth ulcers
212,Esophagus - Mucosa,LV132,Diagnoses - main ICD10: I20 Angina pectoris
213,Heart - Atrial Appendage,LV282,Job SOC coding: Medical secretaries
214,Heart - Atrial Appendage,LV282,"Non-cancer illness code, self-reported: gout"
215,Heart - Atrial Appendage,LV139,"Cancer code, self-reported: multiple myeloma"
216,Heart - Atrial Appendage,LV18,Number of cigarettes previously smoked daily
217,Heart - Atrial Appendage,LV145,"Hair colour (natural, before greying): Light brown"
218,Heart - Left Ventricle,LV248,"Blood clot, DVT, bronchitis, emphysema, asthma, rhinitis, eczema, allergy diagnosed by doctor: None of the above"
219,Heart - Left Ventricle,LV248,"Blood clot, DVT, bronchitis, emphysema, asthma, rhinitis, eczema, allergy diagnosed by doctor: Hayfever, allergic rhinitis or eczema"
220,Heart - Left Ventricle,LV248,Age asthma diagnosed
221,Heart - Left Ventricle,LV248,Mouth/teeth dental problems: Mouth ulcers
222,Heart - Left Ventricle,LV363,Basophill percentage
223,Heart - Left Ventricle,LV363,Eosinophill count
224,Heart - Left Ventricle,LV363,Lymphocyte count
225,Heart - Left Ventricle,LV363,Eosinophill percentage
226,Heart - Left Ventricle,LV363,"Medication for cholesterol, blood pressure or diabetes: Blood pressure medication"
227,Heart - Left Ventricle,LV363,Basophill count
228,Heart - Left Ventricle,LV44,Diagnoses - main ICD10: K40 Inguinal hernia
229,Heart - Left Ventricle,LV24,"Malignant neoplasm, without specification of site"
230,Heart - Left Ventricle,LV365,"Heel bone mineral density (BMD) T-score, automated (left)"
231,Heart - Left Ventricle,LV365,"Heel quantitative ultrasound index (QUI), direct entry (left)"
232,Heart - Left Ventricle,LV365,Heel bone mineral density (BMD) (left)
233,Heart - Left Ventricle,LV365,Heel bone mineral density (BMD)
234,Heart - Left Ventricle,LV365,"Heel quantitative ultrasound index (QUI), direct entry (right)"
235,Heart - Left Ventricle,LV365,"Heel bone mineral density (BMD) T-score, automated (right)"
236,Heart - Left Ventricle,LV365,"Heel quantitative ultrasound index (QUI), direct entry"
237,Heart - Left Ventricle,LV365,"Heel bone mineral density (BMD) T-score, automated"
238,Heart - Left Ventricle,LV203,malignant neoplasm of male genital organs
239,Heart - Left Ventricle,LV203,Malignant neoplasm of prostate
240,Heart - Left Ventricle,LV203,Mouth/teeth dental problems: Mouth ulcers
241,Heart - Left Ventricle,LV203,Diagnoses - main ICD10: C50 Malignant neoplasm of breast

In [87]:
# pct=50%  FDR<0.05  seen_lvs=True
_tpt = top_lvs_at_pct(50)
_df  = trait_table(_tpt, fdr_thresh=0.05, use_seen_lvs=True)
print(f'pct=50%  FDR<0.05  seen_lvs=True  ->  {len(_df)} rows, {_df["Tissue"].nunique()} tissues, {_df["LV"].nunique()} LVs')
_df[['Tissue', 'LV', 'phenotype']]

pct=50%  FDR<0.05  seen_lvs=True  ->  686 rows, 24 tissues, 111 LVs

,Tissue,LV,phenotype
0,Adipose - Subcutaneous,LV263,Sum of road length of major roads within 100m
1,Adipose - Subcutaneous,LV378,"Blood clot, DVT, bronchitis, emphysema, asthma, rhinitis, eczema, allergy diagnosed by doctor: Hayfever, allergic rhinitis or eczema"
2,Adipose - Subcutaneous,LV378,Facial ageing
3,Adipose - Subcutaneous,LV378,"Age hay fever, rhinitis or eczema diagnosed"
4,Adipose - Subcutaneous,LV378,"Blood clot, DVT, bronchitis, emphysema, asthma, rhinitis, eczema, allergy diagnosed by doctor: None of the above"
5,Adipose - Subcutaneous,LV378,"Hair colour (natural, before greying): Light brown"
6,Adipose - Subcutaneous,LV378,"Hair colour (natural, before greying): Black"
7,Adipose - Subcutaneous,LV90,"Non-cancer illness code, self-reported: polycythaemia vera"
8,Adipose - Subcutaneous,LV230,Type of fat/oil used in cooking: Vegetable oil
9,Adipose - Subcutaneous,LV145,"Hair colour (natural, before greying): Light brown"
10,Adipose - Subcutaneous,LV145,"Hair colour (natural, before greying): Black"
11,Adipose - Subcutaneous,LV145,"Hair colour (natural, before greying): Blonde"
12,Adipose - Subcutaneous,LV111,"Non-cancer illness code, self-reported: rheumatoid arthritis"
13,Adipose - Subcutaneous,LV111,Rheumatoid arthritis
14,Adipose - Subcutaneous,LV111,Other/unspecified seropositiverheumatoid arthritis
15,Adipose - Subcutaneous,LV111,Diagnoses - main ICD10: M06 Other rheumatoid arthritis
16,Adipose - Subcutaneous,LV111,Other/unspecified rheumatoid arthritis
17,Adipose - Subcutaneous,LV111,Adult-onset Still disease
18,Adipose - Subcutaneous,LV111,Diagnoses - main ICD10: M05 Seropositive rheumatoid arthritis
19,Adipose - Subcutaneous,LV111,Seropositive rheumatoid arthritis
20,Adipose - Subcutaneous,LV111,"Non-cancer illness code, self-reported: multiple sclerosis"
21,Adipose - Subcutaneous,LV111,#Polyarthropathies
22,Adipose - Subcutaneous,LV111,"Non-cancer illness code, self-reported: polymyalgia rheumatica"
23,Adipose - Subcutaneous,LV111,Demyelenating diseases of the central nervous system
24,Adipose - Subcutaneous,LV111,Non-accidental death in close genetic family
25,Adipose - Subcutaneous,LV93,High light scatter reticulocyte percentage
26,Adipose - Subcutaneous,LV93,"Non-cancer illness code, self-reported: eczema/dermatitis"
27,Adipose - Subcutaneous,LV93,Reticulocyte percentage
28,Adipose - Subcutaneous,LV93,Reticulocyte count
29,Adipose - Subcutaneous,LV93,"Non-cancer illness code, self-reported: psoriasis"
30,Adipose - Subcutaneous,LV93,Diagnoses - main ICD10: S72 Fracture of femur
31,Adipose - Subcutaneous,LV246,Felt loved as a child
32,Adipose - Visceral (Omentum),LV376,Heel broadband ultrasound attenuation (right)
33,Adipose - Visceral (Omentum),LV376,Heel broadband ultrasound attenuation (left)
34,Adipose - Visceral (Omentum),LV376,"Heel quantitative ultrasound index (QUI), direct entry (right)"
35,Adipose - Visceral (Omentum),LV376,"Heel bone mineral density (BMD) T-score, automated (right)"
36,Adipose - Visceral (Omentum),LV376,Heel bone mineral density (BMD) (right)
37,Adipose - Visceral (Omentum),LV376,Heel bone mineral density (BMD) (left)
38,Adipose - Visceral (Omentum),LV376,"Heel bone mineral density (BMD) T-score, automated (left)"
39,Adipose - Visceral (Omentum),LV376,"Heel quantitative ultrasound index (QUI), direct entry (left)"
40,Adipose - Visceral (Omentum),LV376,Heel bone mineral density (BMD)
41,Adipose - Visceral (Omentum),LV376,"Heel quantitative ultrasound index (QUI), direct entry"
42,Adipose - Visceral (Omentum),LV376,"Heel bone mineral density (BMD) T-score, automated"
43,Adipose - Visceral (Omentum),LV376,"Heel Broadband ultrasound attenuation, direct entry"
44,Adipose - Visceral (Omentum),LV376,Fractured/broken bones in last 5 years
45,Adipose - Visceral (Omentum),LV376,Diagnoses - main ICD10: N81 Female genital prolapse
46,Adipose - Visceral (Omentum),LV376,Palmar fascial fibromatosis [Dupuytren]
47,Adipose - Visceral (Omentum),LV376,Fibroblastic disorders
48,Adipose - Visceral (Omentum),LV376,Diagnoses - main ICD10: M72 Fibroblastic disorders
49,Adipose - Visceral (Omentum),LV376,"Hair colour (natural, before greying): Light brown"
50,Adipose - Visceral (Omentum),LV376,Facial ageing
51,Adipose - Visceral (Omentum),LV83,"Hair colour (natural, before greying): Light brown"
52,Adipose - Visceral (Omentum),LV57,"Heel bone mineral density (BMD) T-score, automated (left)"
53,Adipose - Visceral (Omentum),LV57,"Heel quantitative ultrasound index (QUI), direct entry (left)"
54,Adipose - Visceral (Omentum),LV57,Heel bone mineral density (BMD) (left)
55,Adipose - Visceral (Omentum),LV106,"Disorders of gallbladder, biliary tract and pancreas"
56,Adipose - Visceral (Omentum),LV106,malignant neoplasm of male genital organs
57,Adipose - Visceral (Omentum),LV106,Malignant neoplasm of prostate
58,Adipose - Visceral (Omentum),LV106,Diagnoses - main ICD10: K80 Cholelithiasis
59,Adipose - Visceral (Omentum),LV2,Plays computer games
60,Adipose - Visceral (Omentum),LV293,Illnesses of mother: Alzheimer's disease/dementia
61,Adipose - Visceral (Omentum),LV203,malignant neoplasm of male genital organs
62,Adipose - Visceral (Omentum),LV203,Malignant neoplasm of prostate
63,Adipose - Visceral (Omentum),LV203,Mouth/teeth dental problems: Mouth ulcers
64,Adipose - Visceral (Omentum),LV203,Diagnoses - main ICD10: C50 Malignant neoplasm of breast
65,Adipose - Visceral (Omentum),LV203,"Non-cancer illness code, self-reported: scarlet fever / scarlatina"
66,Adipose - Visceral (Omentum),LV203,"Mental health problems ever diagnosed by a professional: Mania, hypomania, bipolar or manic-depression"
67,Adipose - Visceral (Omentum),LV203,Diagnoses - main ICD10: C61 Malignant neoplasm of prostate
68,Adipose - Visceral (Omentum),LV203,Ever self-harmed
69,Adipose - Visceral (Omentum),LV329,Which eye(s) affected by myopia (short sight): Both eyes
70,Adrenal Gland,LV3,Basophill percentage
71,Adrenal Gland,LV3,Basophill count
72,Adrenal Gland,LV3,Diagnoses - main ICD10: C44 Other malignant neoplasms of skin
73,Adrenal Gland,LV3,"Cancer code, self-reported: basal cell carcinoma"
74,Adrenal Gland,LV158,"Medication for cholesterol, blood pressure or diabetes: Blood pressure medication"
75,Adrenal Gland,LV158,"Disorders of gallbladder, biliary tract and pancreas"
76,Adrenal Gland,LV158,"Job SOC coding: Property, housing and land managers"
77,Adrenal Gland,LV158,"Non-cancer illness code, self-reported: hypertension"
78,Adrenal Gland,LV183,Mouth/teeth dental problems: Mouth ulcers
79,Adrenal Gland,LV183,Basophill count
80,Adrenal Gland,LV183,"Non-cancer illness code, self-reported: ulcerative colitis"
81,Adrenal Gland,LV183,Diagnoses - main ICD10: D61 Other aplastic anaemias
82,Adrenal Gland,LV183,Basophill percentage
83,Adrenal Gland,LV131,Neck/shoulder pain for 3+ months
84,Artery - Aorta,LV37,Other viral diseases
85,Artery - Aorta,LV40,"Heel bone mineral density (BMD) T-score, automated (left)"
86,Artery - Aorta,LV40,"Heel quantitative ultrasound index (QUI), direct entry (left)"
87,Artery - Aorta,LV40,Heel bone mineral density (BMD) (left)
88,Artery - Aorta,LV40,Heel bone mineral density (BMD)
89,Artery - Aorta,LV84,Venous thromboembolism
90,Artery - Aorta,LV84,DVT of lower extremities and pulmonary embolism
91,Artery - Aorta,LV84,DVT of lower extremities
92,Artery - Aorta,LV84,Illnesses of mother: Alzheimer's disease/dementia
93,Artery - Aorta,LV84,"Non-cancer illness code, self-reported: deep venous thrombosis (dvt)"
94,Artery - Aorta,LV84,"Blood clot, DVT, bronchitis, emphysema, asthma, rhinitis, eczema, allergy diagnosed by doctor: Blood clot in the leg (DVT)"
95,Artery - Aorta,LV84,Diagnoses - main ICD10: I80 Phlebitis and thrombophlebitis
96,Artery - Aorta,LV84,Palmar fascial fibromatosis [Dupuytren]
97,Artery - Aorta,LV84,"Blood clot, DVT, bronchitis, emphysema, asthma, rhinitis, eczema, allergy diagnosed by doctor: Blood clot in the lung"
98,Artery - Aorta,LV84,Fibroblastic disorders
99,Artery - Aorta,LV84,"Non-cancer illness code, self-reported: pulmonary embolism +/- dvt"
100,Artery - Aorta,LV84,Diagnoses - main ICD10: M72 Fibroblastic disorders
101,Artery - Aorta,LV84,Other ILD-related CVD-co-morbidities
102,Artery - Aorta,LV84,Haemoglobin concentration
103,Artery - Aorta,LV84,Haematocrit percentage
104,Artery - Coronary,LV247,Eye problems/disorders: Glaucoma
105,Artery - Coronary,LV102,Felt loved as a child
106,Artery - Coronary,LV102,Yogurt/ice-cream consumers
107,Artery - Coronary,LV102,Diagnoses - main ICD10: I84 Haemorrhoids
108,Artery - Coronary,LV59,Interpolated Age of participant when cancer first diagnosed
109,Artery - Coronary,LV99,Monocyte count
110,Artery - Coronary,LV139,"Cancer code, self-reported: multiple myeloma"
111,Artery - Tibial,LV397,Illnesses of mother: Diabetes
112,Artery - Tibial,LV397,"Non-cancer illness code, self-reported: diabetes"
113,Artery - Tibial,LV397,Illnesses of father: Diabetes
114,Artery - Tibial,LV397,Diabetes diagnosed by doctor
115,Artery - Tibial,LV397,"Non-cancer illness code, self-reported: type 2 diabetes"
116,Artery - Tibial,LV397,"Non-cancer illness code, self-reported: gout"
117,Artery - Tibial,LV113,"Non-cancer illness code, self-reported: gout"
118,Artery - Tibial,LV113,Other malignant neoplasms of skin
119,Artery - Tibial,LV113,Diagnoses - main ICD10: C44 Other malignant neoplasms of skin
120,Artery - Tibial,LV113,Coronary atherosclerosis
121,Artery - Tibial,LV113,Diagnoses - main ICD10: I25 Chronic ischaemic heart disease
122,Artery - Tibial,LV87,Spherical power (right)
123,Artery - Tibial,LV87,Spherical power (left)
124,Artery - Tibial,LV87,Type of fat/oil used in cooking: Olive oil
125,Cells - Cultured fibroblasts,LV180,Diagnoses - main ICD10: M72 Fibroblastic disorders
126,Cells - Cultured fibroblasts,LV180,Fibroblastic disorders
127,Cells - Cultured fibroblasts,LV180,Palmar fascial fibromatosis [Dupuytren]
128,Cells - Cultured fibroblasts,LV180,3mm weak meridian (right)
129,Cells - Cultured fibroblasts,LV180,3mm strong meridian (left)
130,Cells - Cultured fibroblasts,LV180,3mm strong meridian (right)
131,Cells - Cultured fibroblasts,LV180,3mm weak meridian (left)
132,Cells - Cultured fibroblasts,LV180,6mm strong meridian (right)
133,Cells - Cultured fibroblasts,LV180,6mm weak meridian (right)
134,Cells - Cultured fibroblasts,LV180,6mm strong meridian (left)
135,Cells - Cultured fibroblasts,LV180,6mm weak meridian (left)
136,Cells - Cultured fibroblasts,LV336,"Hair colour (natural, before greying): Light brown"
137,Cells - Cultured fibroblasts,LV336,"Hair colour (natural, before greying): Blonde"
138,Cells - Cultured fibroblasts,LV336,"Hair colour (natural, before greying): Black"
139,Cells - Cultured fibroblasts,LV91,"Non-cancer illness code, self-reported: multiple sclerosis"
140,Cells - Cultured fibroblasts,LV91,Mouth/teeth dental problems: Mouth ulcers
141,Cells - Cultured fibroblasts,LV91,"Blood clot, DVT, bronchitis, emphysema, asthma, rhinitis, eczema, allergy diagnosed by doctor: Hayfever, allergic rhinitis or eczema"
142,Cells - Cultured fibroblasts,LV91,Monocyte percentage
143,Cells - Cultured fibroblasts,LV91,Demyelenating diseases of the central nervous system
144,Cells - Cultured fibroblasts,LV91,Diagnoses - main ICD10: G35 Multiple sclerosis
145,Cells - Cultured fibroblasts,LV91,Rheumatoid arthritis
146,Cells - Cultured fibroblasts,LV91,Diagnoses - main ICD10: M06 Other rheumatoid arthritis
147,Cells - Cultured fibroblasts,LV91,Adult-onset Still disease
148,Cells - Cultured fibroblasts,LV91,"Non-cancer illness code, self-reported: rheumatoid arthritis"
149,Cells - Cultured fibroblasts,LV91,Other/unspecified rheumatoid arthritis
150,Cells - Cultured fibroblasts,LV91,Other/unspecified seropositiverheumatoid arthritis
151,Cells - Cultured fibroblasts,LV91,Monocyte count
152,Cells - Cultured fibroblasts,LV91,Seropositive rheumatoid arthritis
153,Cells - Cultured fibroblasts,LV91,"Blood clot, DVT, bronchitis, emphysema, asthma, rhinitis, eczema, allergy diagnosed by doctor: None of the above"
154,Cells - Cultured fibroblasts,LV91,Diagnoses - main ICD10: M05 Seropositive rheumatoid arthritis
155,Cells - Cultured fibroblasts,LV91,Doctor diagnosed hayfever or allergic rhinitis
156,Cells - Cultured fibroblasts,LV91,Diagnoses - main ICD10: K51 Ulcerative colitis
157,Cells - Cultured fibroblasts,LV91,Suggestive for eosinophilic asthma
158,Cells - Cultured fibroblasts,LV91,#Polyarthropathies
159,Cells - Cultured fibroblasts,LV91,"Non-cancer illness code, self-reported: ulcerative colitis"
160,Cells - Cultured fibroblasts,LV91,Diagnoses - main ICD10: J33 Nasal polyp
161,Cells - Cultured fibroblasts,LV91,"Non-cancer illness code, self-reported: hypothyroidism/myxoedema"
162,Cells - Cultured fibroblasts,LV91,"Age hay fever, rhinitis or eczema diagnosed"
163,Cells - Cultured fibroblasts,LV91,"Ulcerative colitis, NAS"
164,Cells - Cultured fibroblasts,LV91,Age hayfever or allergic rhinitis diagnosed by doctor
165,Cells - Cultured fibroblasts,LV91,"Non-cancer illness code, self-reported: hyperthyroidism/thyrotoxicosis"
166,Cells - Cultured fibroblasts,LV91,Thyrotoxicosis
167,Cells - Cultured fibroblasts,LV91,Diagnoses - main ICD10: E05 Thyrotoxicosis [hyperthyroidism]
168,Cells - Cultured fibroblasts,LV91,Vitamin and mineral supplements: Folic acid or Folate (Vit B9)
169,Cells - Cultured fibroblasts,LV91,Diagnoses - main ICD10: M45 Ankylosing spondylitis
170,Cells - Cultured fibroblasts,LV109,All anxiety disorders
171,Cells - Cultured fibroblasts,LV109,Anxiety (asthma-related co-morbidities)
172,Cells - Cultured fibroblasts,LV109,Diagnoses - main ICD10: F41 Other anxiety disorders
173,Cells - Cultured fibroblasts,LV5,Mouth/teeth dental problems: Mouth ulcers
174,Cells - Cultured fibroblasts,LV5,"Non-cancer illness code, self-reported: eczema/dermatitis"
175,Cells - EBV-transformed lymphocytes,LV123,"Pulse rate, automated reading"
176,Cells - EBV-transformed lymphocytes,LV123,Pulse rate
177,Cells - EBV-transformed lymphocytes,LV123,QRS duration
178,Cells - EBV-transformed lymphocytes,LV116,"Blood clot, DVT, bronchitis, emphysema, asthma, rhinitis, eczema, allergy diagnosed by doctor: Blood clot in the leg (DVT)"
179,Cells - EBV-transformed lymphocytes,LV116,"Non-cancer illness code, self-reported: deep venous thrombosis (dvt)"
180,Cells - EBV-transformed lymphocytes,LV116,Diagnoses - main ICD10: I80 Phlebitis and thrombophlebitis
181,Cells - EBV-transformed lymphocytes,LV116,DVT of lower extremities
182,Cells - EBV-transformed lymphocytes,LV116,Venous thromboembolism
183,Cells - EBV-transformed lymphocytes,LV116,"Non-cancer illness code, self-reported: clotting disorder/excessive bleeding"
184,Cells - EBV-transformed lymphocytes,LV244,Number of cigarettes currently smoked daily (current cigarette smokers)
185,Cells - EBV-transformed lymphocytes,LV244,Difficulty not smoking for 1 day
186,Cells - EBV-transformed lymphocytes,LV12,Reason former drinker stopped drinking alcohol: Financial reasons
187,Cells - EBV-transformed lymphocytes,LV406,Number of cigarettes previously smoked daily
188,Cells - EBV-transformed lymphocytes,LV406,Number of cigarettes currently smoked daily (current cigarette smokers)
189,Cells - EBV-transformed lymphocytes,LV406,Palmar fascial fibromatosis [Dupuytren]
190,Cells - EBV-transformed lymphocytes,LV340,"Diagnoses - main ICD10: F05 Delirium, not induced by alcohol and other psychoactive substances"
191,Cells - EBV-transformed lymphocytes,LV340,Diagnoses - main ICD10: H65 Nonsuppurative otitis media
192,Cells - EBV-transformed lymphocytes,LV55,"Medication for cholesterol, blood pressure, diabetes, or take exogenous hormones: Blood pressure medication"
193,Cells - EBV-transformed lymphocytes,LV1,"Non-cancer illness code, self-reported: deep venous thrombosis (dvt)"
194,Cells - EBV-transformed lymphocytes,LV1,"Blood clot, DVT, bronchitis, emphysema, asthma, rhinitis, eczema, allergy diagnosed by doctor: Blood clot in the leg (DVT)"
195,Cells - EBV-transformed lymphocytes,LV1,Diagnoses - main ICD10: I80 Phlebitis and thrombophlebitis
196,Cells - EBV-transformed lymphocytes,LV1,"Non-cancer illness code, self-reported: clotting disorder/excessive bleeding"
197,Cells - EBV-transformed lymphocytes,LV1,DVT of lower extremities
198,Cells - EBV-transformed lymphocytes,LV1,Venous thromboembolism
199,Cells - EBV-transformed lymphocytes,LV1,DVT of lower extremities and pulmonary embolism
200,Cells - EBV-transformed lymphocytes,LV1,Particulate matter air pollution (pm10); 2010
201,Cells - EBV-transformed lymphocytes,LV375,"Worked with paints, thinners or glues: Often"
202,Cells - EBV-transformed lymphocytes,LV375,Malignant neoplasm of breast
203,Esophagus - Mucosa,LV8,Heel broadband ultrasound attenuation (left)
204,Esophagus - Mucosa,LV8,Heel broadband ultrasound attenuation (right)
205,Esophagus - Mucosa,LV8,Fractured/broken bones in last 5 years
206,Esophagus - Mucosa,LV8,Primary_lymphoid and hematopoietic malignant neoplasms
207,Esophagus - Mucosa,LV8,Diagnoses - main ICD10: Q82 Other congenital malformations of skin
208,Esophagus - Mucosa,LV8,"Job SOC coding: Hairdressers, barbers"
209,Esophagus - Mucosa,LV8,"Cancer code, self-reported: rodent ulcer"
210,Esophagus - Mucosa,LV8,Fractured bone site(s): Wrist
211,Esophagus - Mucosa,LV138,Diagnoses - main ICD10: C44 Other malignant neoplasms of skin
212,Esophagus - Mucosa,LV138,"Non-cancer illness code, self-reported: renal failure requiring dialysis"
213,Esophagus - Mucosa,LV62,Waist circumference
214,Esophagus - Mucosa,LV62,Diagnoses - main ICD10: R26 Abnormalities of gait and mobility
215,Esophagus - Mucosa,LV62,Arm fat percentage (right)
216,Esophagus - Mucosa,LV62,Arm fat percentage (left)
217,Esophagus - Mucosa,LV62,Arm fat mass (left)
218,Esophagus - Mucosa,LV62,Arm fat mass (right)
219,Esophagus - Mucosa,LV62,Manifestations of mania or irritability: My thoughts were racing
220,Esophagus - Mucosa,LV62,Body fat percentage
221,Esophagus - Mucosa,LV132,Mouth/teeth dental problems: Mouth ulcers
222,Esophagus - Mucosa,LV132,Diagnoses - main ICD10: I20 Angina pectoris
223,Heart - Atrial Appendage,LV282,Job SOC coding: Medical secretaries
224,Heart - Atrial Appendage,LV282,"Non-cancer illness code, self-reported: gout"
225,Heart - Atrial Appendage,LV282,Diagnoses - main ICD10: F10 Mental and behavioural disorders due to use of alcohol
226,Heart - Atrial Appendage,LV18,Number of cigarettes previously smoked daily
227,Heart - Atrial Appendage,LV18,"Intra-ocular pressure, corneal-compensated (left)"
228,Heart - Atrial Appendage,LV137,"Diagnoses - main ICD10: A63 Other predominantly sexually transmitted diseases, not elsewhere classified"
229,Heart - Atrial Appendage,LV78,Diagnoses - main ICD10: R21 Rash and other nonspecific skin eruption
230,Heart - Left Ventricle,LV248,"Blood clot, DVT, bronchitis, emphysema, asthma, rhinitis, eczema, allergy diagnosed by doctor: None of the above"
231,Heart - Left Ventricle,LV248,"Blood clot, DVT, bronchitis, emphysema, asthma, rhinitis, eczema, allergy diagnosed by doctor: Hayfever, allergic rhinitis or eczema"
232,Heart - Left Ventricle,LV248,Age asthma diagnosed
233,Heart - Left Ventricle,LV248,Mouth/teeth dental problems: Mouth ulcers
234,Heart - Left Ventricle,LV248,Eosinophill percentage
235,Heart - Left Ventricle,LV248,"Non-cancer illness code, self-reported: hayfever/allergic rhinitis"
236,Heart - Left Ventricle,LV363,Basophill percentage
237,Heart - Left Ventricle,LV363,Eosinophill count
238,Heart - Left Ventricle,LV363,Lymphocyte count
239,Heart - Left Ventricle,LV363,Eosinophill percentage
240,Heart - Left Ventricle,LV363,"Medication for cholesterol, blood pressure or diabetes: Blood pressure medication"
241,Heart - Left Ventricle,LV363,Basophill count
242,Heart - Left Ventricle,LV363,"Medication for cholesterol, blood pressure or diabetes: None of the above"
243,Heart - Left Ventricle,LV363,Illnesses of siblings: High blood pressure
244,Heart - Left Ventricle,LV363,Lymphocyte percentage

In [88]:
# pct=50%  FDR<0.05  seen_lvs=False
_tpt = top_lvs_at_pct(50)
_df  = trait_table(_tpt, fdr_thresh=0.05, use_seen_lvs=False)
print(f'pct=50%  FDR<0.05  seen_lvs=False  ->  {len(_df)} rows, {_df["Tissue"].nunique()} tissues, {_df["LV"].nunique()} LVs')
_df[['Tissue', 'LV', 'phenotype']]

pct=50%  FDR<0.05  seen_lvs=False  ->  1287 rows, 25 tissues, 111 LVs

,Tissue,LV,phenotype
0,Adipose - Subcutaneous,LV263,Sum of road length of major roads within 100m
1,Adipose - Subcutaneous,LV378,"Blood clot, DVT, bronchitis, emphysema, asthma, rhinitis, eczema, allergy diagnosed by doctor: Hayfever, allergic rhinitis or eczema"
2,Adipose - Subcutaneous,LV378,Facial ageing
3,Adipose - Subcutaneous,LV378,"Age hay fever, rhinitis or eczema diagnosed"
4,Adipose - Subcutaneous,LV378,"Blood clot, DVT, bronchitis, emphysema, asthma, rhinitis, eczema, allergy diagnosed by doctor: None of the above"
5,Adipose - Subcutaneous,LV378,"Hair colour (natural, before greying): Light brown"
6,Adipose - Subcutaneous,LV378,"Hair colour (natural, before greying): Black"
7,Adipose - Subcutaneous,LV90,"Non-cancer illness code, self-reported: polycythaemia vera"
8,Adipose - Subcutaneous,LV230,Type of fat/oil used in cooking: Vegetable oil
9,Adipose - Subcutaneous,LV145,"Hair colour (natural, before greying): Light brown"
10,Adipose - Subcutaneous,LV145,"Hair colour (natural, before greying): Black"
11,Adipose - Subcutaneous,LV145,"Hair colour (natural, before greying): Blonde"
12,Adipose - Subcutaneous,LV111,"Non-cancer illness code, self-reported: rheumatoid arthritis"
13,Adipose - Subcutaneous,LV111,Rheumatoid arthritis
14,Adipose - Subcutaneous,LV111,Other/unspecified seropositiverheumatoid arthritis
15,Adipose - Subcutaneous,LV111,Diagnoses - main ICD10: M06 Other rheumatoid arthritis
16,Adipose - Subcutaneous,LV111,Other/unspecified rheumatoid arthritis
17,Adipose - Subcutaneous,LV111,Adult-onset Still disease
18,Adipose - Subcutaneous,LV111,Diagnoses - main ICD10: M05 Seropositive rheumatoid arthritis
19,Adipose - Subcutaneous,LV111,Seropositive rheumatoid arthritis
20,Adipose - Subcutaneous,LV111,"Non-cancer illness code, self-reported: multiple sclerosis"
21,Adipose - Subcutaneous,LV111,#Polyarthropathies
22,Adipose - Subcutaneous,LV111,"Non-cancer illness code, self-reported: polymyalgia rheumatica"
23,Adipose - Subcutaneous,LV111,Demyelenating diseases of the central nervous system
24,Adipose - Subcutaneous,LV111,Non-accidental death in close genetic family
25,Adipose - Subcutaneous,LV93,High light scatter reticulocyte percentage
26,Adipose - Subcutaneous,LV93,"Non-cancer illness code, self-reported: eczema/dermatitis"
27,Adipose - Subcutaneous,LV93,Reticulocyte percentage
28,Adipose - Subcutaneous,LV93,Reticulocyte count
29,Adipose - Subcutaneous,LV93,"Non-cancer illness code, self-reported: psoriasis"
30,Adipose - Subcutaneous,LV93,Diagnoses - main ICD10: S72 Fracture of femur
31,Adipose - Subcutaneous,LV246,Felt loved as a child
32,Adipose - Visceral (Omentum),LV263,Sum of road length of major roads within 100m
33,Adipose - Visceral (Omentum),LV376,Heel broadband ultrasound attenuation (right)
34,Adipose - Visceral (Omentum),LV376,Heel broadband ultrasound attenuation (left)
35,Adipose - Visceral (Omentum),LV376,"Heel quantitative ultrasound index (QUI), direct entry (right)"
36,Adipose - Visceral (Omentum),LV376,"Heel bone mineral density (BMD) T-score, automated (right)"
37,Adipose - Visceral (Omentum),LV376,Heel bone mineral density (BMD) (right)
38,Adipose - Visceral (Omentum),LV376,Heel bone mineral density (BMD) (left)
39,Adipose - Visceral (Omentum),LV376,"Heel bone mineral density (BMD) T-score, automated (left)"
40,Adipose - Visceral (Omentum),LV376,"Heel quantitative ultrasound index (QUI), direct entry (left)"
41,Adipose - Visceral (Omentum),LV376,Heel bone mineral density (BMD)
42,Adipose - Visceral (Omentum),LV376,"Heel quantitative ultrasound index (QUI), direct entry"
43,Adipose - Visceral (Omentum),LV376,"Heel bone mineral density (BMD) T-score, automated"
44,Adipose - Visceral (Omentum),LV376,"Heel Broadband ultrasound attenuation, direct entry"
45,Adipose - Visceral (Omentum),LV376,Fractured/broken bones in last 5 years
46,Adipose - Visceral (Omentum),LV376,Diagnoses - main ICD10: N81 Female genital prolapse
47,Adipose - Visceral (Omentum),LV376,Palmar fascial fibromatosis [Dupuytren]
48,Adipose - Visceral (Omentum),LV376,Fibroblastic disorders
49,Adipose - Visceral (Omentum),LV376,Diagnoses - main ICD10: M72 Fibroblastic disorders
50,Adipose - Visceral (Omentum),LV376,"Hair colour (natural, before greying): Light brown"
51,Adipose - Visceral (Omentum),LV376,Facial ageing
52,Adipose - Visceral (Omentum),LV83,"Hair colour (natural, before greying): Light brown"
53,Adipose - Visceral (Omentum),LV57,"Heel bone mineral density (BMD) T-score, automated (left)"
54,Adipose - Visceral (Omentum),LV57,"Heel quantitative ultrasound index (QUI), direct entry (left)"
55,Adipose - Visceral (Omentum),LV57,Heel bone mineral density (BMD) (left)
56,Adipose - Visceral (Omentum),LV106,"Disorders of gallbladder, biliary tract and pancreas"
57,Adipose - Visceral (Omentum),LV106,malignant neoplasm of male genital organs
58,Adipose - Visceral (Omentum),LV106,Malignant neoplasm of prostate
59,Adipose - Visceral (Omentum),LV106,Diagnoses - main ICD10: K80 Cholelithiasis
60,Adipose - Visceral (Omentum),LV230,Type of fat/oil used in cooking: Vegetable oil
61,Adipose - Visceral (Omentum),LV2,Plays computer games
62,Adipose - Visceral (Omentum),LV293,Illnesses of mother: Alzheimer's disease/dementia
63,Adipose - Visceral (Omentum),LV203,malignant neoplasm of male genital organs
64,Adipose - Visceral (Omentum),LV203,Malignant neoplasm of prostate
65,Adipose - Visceral (Omentum),LV203,Mouth/teeth dental problems: Mouth ulcers
66,Adipose - Visceral (Omentum),LV203,Diagnoses - main ICD10: C50 Malignant neoplasm of breast
67,Adipose - Visceral (Omentum),LV203,"Non-cancer illness code, self-reported: scarlet fever / scarlatina"
68,Adipose - Visceral (Omentum),LV203,"Mental health problems ever diagnosed by a professional: Mania, hypomania, bipolar or manic-depression"
69,Adipose - Visceral (Omentum),LV203,Diagnoses - main ICD10: C61 Malignant neoplasm of prostate
70,Adipose - Visceral (Omentum),LV203,Ever self-harmed
71,Adipose - Visceral (Omentum),LV329,Which eye(s) affected by myopia (short sight): Both eyes
72,Adipose - Visceral (Omentum),LV90,"Non-cancer illness code, self-reported: polycythaemia vera"
73,Adipose - Visceral (Omentum),LV378,"Blood clot, DVT, bronchitis, emphysema, asthma, rhinitis, eczema, allergy diagnosed by doctor: Hayfever, allergic rhinitis or eczema"
74,Adipose - Visceral (Omentum),LV378,Facial ageing
75,Adipose - Visceral (Omentum),LV378,"Age hay fever, rhinitis or eczema diagnosed"
76,Adipose - Visceral (Omentum),LV378,"Blood clot, DVT, bronchitis, emphysema, asthma, rhinitis, eczema, allergy diagnosed by doctor: None of the above"
77,Adipose - Visceral (Omentum),LV378,"Hair colour (natural, before greying): Light brown"
78,Adipose - Visceral (Omentum),LV378,"Hair colour (natural, before greying): Black"
79,Adrenal Gland,LV83,"Hair colour (natural, before greying): Light brown"
80,Adrenal Gland,LV3,Basophill percentage
81,Adrenal Gland,LV3,Basophill count
82,Adrenal Gland,LV3,Diagnoses - main ICD10: C44 Other malignant neoplasms of skin
83,Adrenal Gland,LV3,"Cancer code, self-reported: basal cell carcinoma"
84,Adrenal Gland,LV158,"Medication for cholesterol, blood pressure or diabetes: Blood pressure medication"
85,Adrenal Gland,LV158,"Disorders of gallbladder, biliary tract and pancreas"
86,Adrenal Gland,LV158,"Job SOC coding: Property, housing and land managers"
87,Adrenal Gland,LV158,"Non-cancer illness code, self-reported: hypertension"
88,Adrenal Gland,LV183,Mouth/teeth dental problems: Mouth ulcers
89,Adrenal Gland,LV183,Basophill count
90,Adrenal Gland,LV183,"Non-cancer illness code, self-reported: ulcerative colitis"
91,Adrenal Gland,LV183,Diagnoses - main ICD10: D61 Other aplastic anaemias
92,Adrenal Gland,LV183,Basophill percentage
93,Adrenal Gland,LV131,Neck/shoulder pain for 3+ months
94,Artery - Aorta,LV145,"Hair colour (natural, before greying): Light brown"
95,Artery - Aorta,LV145,"Hair colour (natural, before greying): Black"
96,Artery - Aorta,LV145,"Hair colour (natural, before greying): Blonde"
97,Artery - Aorta,LV90,"Non-cancer illness code, self-reported: polycythaemia vera"
98,Artery - Aorta,LV37,Other viral diseases
99,Artery - Aorta,LV40,"Heel bone mineral density (BMD) T-score, automated (left)"
100,Artery - Aorta,LV40,"Heel quantitative ultrasound index (QUI), direct entry (left)"
101,Artery - Aorta,LV40,Heel bone mineral density (BMD) (left)
102,Artery - Aorta,LV40,Heel bone mineral density (BMD)
103,Artery - Aorta,LV84,Venous thromboembolism
104,Artery - Aorta,LV84,DVT of lower extremities and pulmonary embolism
105,Artery - Aorta,LV84,DVT of lower extremities
106,Artery - Aorta,LV84,Illnesses of mother: Alzheimer's disease/dementia
107,Artery - Aorta,LV84,"Non-cancer illness code, self-reported: deep venous thrombosis (dvt)"
108,Artery - Aorta,LV84,"Blood clot, DVT, bronchitis, emphysema, asthma, rhinitis, eczema, allergy diagnosed by doctor: Blood clot in the leg (DVT)"
109,Artery - Aorta,LV84,Diagnoses - main ICD10: I80 Phlebitis and thrombophlebitis
110,Artery - Aorta,LV84,Palmar fascial fibromatosis [Dupuytren]
111,Artery - Aorta,LV84,"Blood clot, DVT, bronchitis, emphysema, asthma, rhinitis, eczema, allergy diagnosed by doctor: Blood clot in the lung"
112,Artery - Aorta,LV84,Fibroblastic disorders
113,Artery - Aorta,LV84,"Non-cancer illness code, self-reported: pulmonary embolism +/- dvt"
114,Artery - Aorta,LV84,Diagnoses - main ICD10: M72 Fibroblastic disorders
115,Artery - Aorta,LV84,Other ILD-related CVD-co-morbidities
116,Artery - Aorta,LV84,Haemoglobin concentration
117,Artery - Aorta,LV84,Haematocrit percentage
118,Artery - Aorta,LV131,Neck/shoulder pain for 3+ months
119,Artery - Coronary,LV40,"Heel bone mineral density (BMD) T-score, automated (left)"
120,Artery - Coronary,LV40,"Heel quantitative ultrasound index (QUI), direct entry (left)"
121,Artery - Coronary,LV40,Heel bone mineral density (BMD) (left)
122,Artery - Coronary,LV40,Heel bone mineral density (BMD)
123,Artery - Coronary,LV247,Eye problems/disorders: Glaucoma
124,Artery - Coronary,LV102,Felt loved as a child
125,Artery - Coronary,LV102,Yogurt/ice-cream consumers
126,Artery - Coronary,LV102,Diagnoses - main ICD10: I84 Haemorrhoids
127,Artery - Coronary,LV59,Interpolated Age of participant when cancer first diagnosed
128,Artery - Coronary,LV99,Monocyte count
129,Artery - Coronary,LV106,"Disorders of gallbladder, biliary tract and pancreas"
130,Artery - Coronary,LV106,malignant neoplasm of male genital organs
131,Artery - Coronary,LV106,Malignant neoplasm of prostate
132,Artery - Coronary,LV106,Diagnoses - main ICD10: K80 Cholelithiasis
133,Artery - Coronary,LV84,Venous thromboembolism
134,Artery - Coronary,LV84,DVT of lower extremities and pulmonary embolism
135,Artery - Coronary,LV84,DVT of lower extremities
136,Artery - Coronary,LV84,Illnesses of mother: Alzheimer's disease/dementia
137,Artery - Coronary,LV84,"Non-cancer illness code, self-reported: deep venous thrombosis (dvt)"
138,Artery - Coronary,LV84,"Blood clot, DVT, bronchitis, emphysema, asthma, rhinitis, eczema, allergy diagnosed by doctor: Blood clot in the leg (DVT)"
139,Artery - Coronary,LV84,Diagnoses - main ICD10: I80 Phlebitis and thrombophlebitis
140,Artery - Coronary,LV84,Palmar fascial fibromatosis [Dupuytren]
141,Artery - Coronary,LV84,"Blood clot, DVT, bronchitis, emphysema, asthma, rhinitis, eczema, allergy diagnosed by doctor: Blood clot in the lung"
142,Artery - Coronary,LV84,Fibroblastic disorders
143,Artery - Coronary,LV84,"Non-cancer illness code, self-reported: pulmonary embolism +/- dvt"
144,Artery - Coronary,LV84,Diagnoses - main ICD10: M72 Fibroblastic disorders
145,Artery - Coronary,LV84,Other ILD-related CVD-co-morbidities
146,Artery - Coronary,LV84,Haemoglobin concentration
147,Artery - Coronary,LV84,Haematocrit percentage
148,Artery - Coronary,LV90,"Non-cancer illness code, self-reported: polycythaemia vera"
149,Artery - Coronary,LV203,malignant neoplasm of male genital organs
150,Artery - Coronary,LV203,Malignant neoplasm of prostate
151,Artery - Coronary,LV203,Mouth/teeth dental problems: Mouth ulcers
152,Artery - Coronary,LV203,Diagnoses - main ICD10: C50 Malignant neoplasm of breast
153,Artery - Coronary,LV203,"Non-cancer illness code, self-reported: scarlet fever / scarlatina"
154,Artery - Coronary,LV203,"Mental health problems ever diagnosed by a professional: Mania, hypomania, bipolar or manic-depression"
155,Artery - Coronary,LV203,Diagnoses - main ICD10: C61 Malignant neoplasm of prostate
156,Artery - Coronary,LV203,Ever self-harmed
157,Artery - Coronary,LV131,Neck/shoulder pain for 3+ months
158,Artery - Coronary,LV139,"Cancer code, self-reported: multiple myeloma"
159,Artery - Tibial,LV90,"Non-cancer illness code, self-reported: polycythaemia vera"
160,Artery - Tibial,LV397,Illnesses of mother: Diabetes
161,Artery - Tibial,LV397,"Non-cancer illness code, self-reported: diabetes"
162,Artery - Tibial,LV397,Illnesses of father: Diabetes
163,Artery - Tibial,LV397,Diabetes diagnosed by doctor
164,Artery - Tibial,LV397,"Non-cancer illness code, self-reported: type 2 diabetes"
165,Artery - Tibial,LV397,"Non-cancer illness code, self-reported: gout"
166,Artery - Tibial,LV102,Felt loved as a child
167,Artery - Tibial,LV102,Yogurt/ice-cream consumers
168,Artery - Tibial,LV102,Diagnoses - main ICD10: I84 Haemorrhoids
169,Artery - Tibial,LV84,Venous thromboembolism
170,Artery - Tibial,LV84,DVT of lower extremities and pulmonary embolism
171,Artery - Tibial,LV84,DVT of lower extremities
172,Artery - Tibial,LV84,Illnesses of mother: Alzheimer's disease/dementia
173,Artery - Tibial,LV84,"Non-cancer illness code, self-reported: deep venous thrombosis (dvt)"
174,Artery - Tibial,LV84,"Blood clot, DVT, bronchitis, emphysema, asthma, rhinitis, eczema, allergy diagnosed by doctor: Blood clot in the leg (DVT)"
175,Artery - Tibial,LV84,Diagnoses - main ICD10: I80 Phlebitis and thrombophlebitis
176,Artery - Tibial,LV84,Palmar fascial fibromatosis [Dupuytren]
177,Artery - Tibial,LV84,"Blood clot, DVT, bronchitis, emphysema, asthma, rhinitis, eczema, allergy diagnosed by doctor: Blood clot in the lung"
178,Artery - Tibial,LV84,Fibroblastic disorders
179,Artery - Tibial,LV84,"Non-cancer illness code, self-reported: pulmonary embolism +/- dvt"
180,Artery - Tibial,LV84,Diagnoses - main ICD10: M72 Fibroblastic disorders
181,Artery - Tibial,LV84,Other ILD-related CVD-co-morbidities
182,Artery - Tibial,LV84,Haemoglobin concentration
183,Artery - Tibial,LV84,Haematocrit percentage
184,Artery - Tibial,LV113,"Non-cancer illness code, self-reported: gout"
185,Artery - Tibial,LV113,Other malignant neoplasms of skin
186,Artery - Tibial,LV113,Diagnoses - main ICD10: C44 Other malignant neoplasms of skin
187,Artery - Tibial,LV113,Coronary atherosclerosis
188,Artery - Tibial,LV113,Diagnoses - main ICD10: I25 Chronic ischaemic heart disease
189,Artery - Tibial,LV139,"Cancer code, self-reported: multiple myeloma"
190,Artery - Tibial,LV87,Spherical power (right)
191,Artery - Tibial,LV87,Spherical power (left)
192,Artery - Tibial,LV87,Type of fat/oil used in cooking: Olive oil
193,Artery - Tibial,LV93,High light scatter reticulocyte percentage
194,Artery - Tibial,LV93,"Non-cancer illness code, self-reported: eczema/dermatitis"
195,Artery - Tibial,LV93,Reticulocyte percentage
196,Artery - Tibial,LV93,Reticulocyte count
197,Artery - Tibial,LV93,"Non-cancer illness code, self-reported: psoriasis"
198,Artery - Tibial,LV93,Diagnoses - main ICD10: S72 Fracture of femur
199,Artery - Tibial,LV203,malignant neoplasm of male genital organs
200,Artery - Tibial,LV203,Malignant neoplasm of prostate
201,Artery - Tibial,LV203,Mouth/teeth dental problems: Mouth ulcers
202,Artery - Tibial,LV203,Diagnoses - main ICD10: C50 Malignant neoplasm of breast
203,Artery - Tibial,LV203,"Non-cancer illness code, self-reported: scarlet fever / scarlatina"
204,Artery - Tibial,LV203,"Mental health problems ever diagnosed by a professional: Mania, hypomania, bipolar or manic-depression"
205,Artery - Tibial,LV203,Diagnoses - main ICD10: C61 Malignant neoplasm of prostate
206,Artery - Tibial,LV203,Ever self-harmed
207,Cells - Cultured fibroblasts,LV111,"Non-cancer illness code, self-reported: rheumatoid arthritis"
208,Cells - Cultured fibroblasts,LV111,Rheumatoid arthritis
209,Cells - Cultured fibroblasts,LV111,Other/unspecified seropositiverheumatoid arthritis
210,Cells - Cultured fibroblasts,LV111,Diagnoses - main ICD10: M06 Other rheumatoid arthritis
211,Cells - Cultured fibroblasts,LV111,Other/unspecified rheumatoid arthritis
212,Cells - Cultured fibroblasts,LV111,Adult-onset Still disease
213,Cells - Cultured fibroblasts,LV111,Diagnoses - main ICD10: M05 Seropositive rheumatoid arthritis
214,Cells - Cultured fibroblasts,LV111,Seropositive rheumatoid arthritis
215,Cells - Cultured fibroblasts,LV111,"Non-cancer illness code, self-reported: multiple sclerosis"
216,Cells - Cultured fibroblasts,LV111,#Polyarthropathies
217,Cells - Cultured fibroblasts,LV111,"Non-cancer illness code, self-reported: polymyalgia rheumatica"
218,Cells - Cultured fibroblasts,LV111,Demyelenating diseases of the central nervous system
219,Cells - Cultured fibroblasts,LV111,Non-accidental death in close genetic family
220,Cells - Cultured fibroblasts,LV180,Diagnoses - main ICD10: M72 Fibroblastic disorders
221,Cells - Cultured fibroblasts,LV180,Fibroblastic disorders
222,Cells - Cultured fibroblasts,LV180,Palmar fascial fibromatosis [Dupuytren]
223,Cells - Cultured fibroblasts,LV180,3mm weak meridian (right)
224,Cells - Cultured fibroblasts,LV180,3mm strong meridian (left)
225,Cells - Cultured fibroblasts,LV180,3mm strong meridian (right)
226,Cells - Cultured fibroblasts,LV180,3mm weak meridian (left)
227,Cells - Cultured fibroblasts,LV180,6mm strong meridian (right)
228,Cells - Cultured fibroblasts,LV180,6mm weak meridian (right)
229,Cells - Cultured fibroblasts,LV180,6mm strong meridian (left)
230,Cells - Cultured fibroblasts,LV180,6mm weak meridian (left)
231,Cells - Cultured fibroblasts,LV336,"Hair colour (natural, before greying): Light brown"
232,Cells - Cultured fibroblasts,LV336,"Hair colour (natural, before greying): Blonde"
233,Cells - Cultured fibroblasts,LV336,"Hair colour (natural, before greying): Black"
234,Cells - Cultured fibroblasts,LV84,Venous thromboembolism
235,Cells - Cultured fibroblasts,LV84,DVT of lower extremities and pulmonary embolism
236,Cells - Cultured fibroblasts,LV84,DVT of lower extremities
237,Cells - Cultured fibroblasts,LV84,Illnesses of mother: Alzheimer's disease/dementia
238,Cells - Cultured fibroblasts,LV84,"Non-cancer illness code, self-reported: deep venous thrombosis (dvt)"
239,Cells - Cultured fibroblasts,LV84,"Blood clot, DVT, bronchitis, emphysema, asthma, rhinitis, eczema, allergy diagnosed by doctor: Blood clot in the leg (DVT)"
240,Cells - Cultured fibroblasts,LV84,Diagnoses - main ICD10: I80 Phlebitis and thrombophlebitis
241,Cells - Cultured fibroblasts,LV84,Palmar fascial fibromatosis [Dupuytren]
242,Cells - Cultured fibroblasts,LV84,"Blood clot, DVT, bronchitis, emphysema, asthma, rhinitis, eczema, allergy diagnosed by doctor: Blood clot in the lung"
243,Cells - Cultured fibroblasts,LV84,Fibroblastic disorders
244,Cells - Cultured fibroblasts,LV84,"Non-cancer illness code, self-reported: pulmonary embolism +/- dvt"
245,Cells - Cultured fibroblasts,LV84,Diagnoses - main ICD10: M72 Fibroblastic disorders
246,Cells - Cultured fibroblasts,LV84,Other ILD-related CVD-co-morbidities
247,Cells - Cultured fibroblasts,LV84,Haemoglobin concentration
248,Cells - Cultured fibroblasts,LV84,Haematocrit percentage
249,Cells - Cultured fibroblasts,LV91,"Non-cancer illness code, self-reported: multiple sclerosis"
250,Cells - Cultured fibroblasts,LV91,Mouth/teeth dental problems: Mouth ulcers
251,Cells - Cultured fibroblasts,LV91,"Blood clot, DVT, bronchitis, emphysema, asthma, rhinitis, eczema, allergy diagnosed by doctor: Hayfever, allergic rhinitis or eczema"
252,Cells - Cultured fibroblasts,LV91,Monocyte percentage

# Pathways

Each cell: `(cumulative %, AUC threshold, FDR threshold, seen_lvs)`.

In [89]:
# pct=40%  FDR<0.05  AUC>0.7  seen_lvs=True
_tpt = top_lvs_at_pct(40)
_df  = pathway_table(_tpt, fdr_thresh=0.05, auc_thresh=0.7, use_seen_lvs=True)
print(f'pct=40%  FDR<0.05  AUC>0.7  seen_lvs=True  ->  {len(_df)} rows, {_df["Tissue"].nunique()} tissues, {_df["LV"].nunique()} LVs')
_df[['Tissue', 'LV', 'pathway']]

pct=40%  FDR<0.05  AUC>0.7  seen_lvs=True  ->  37 rows, 13 tissues, 17 LVs

,Tissue,LV,pathway
0,Adipose - Visceral (Omentum),LV57,BP_Mitochondrial ATP Synthesis Coupled Electron Transport (GO:0042775)
1,Adipose - Visceral (Omentum),LV57,BP_Aerobic Electron Transport Chain (GO:0019646)
2,Adipose - Visceral (Omentum),LV57,BP_Aerobic Respiration (GO:0009060)
3,Adrenal Gland,LV3,BP_Negative Regulation of T Cell Mediated Immunity (GO:0002710)
4,Artery - Aorta,LV145,BP_Skeletal Muscle Contraction (GO:0003009)
5,Artery - Coronary,LV99,BP_Dopaminergic Neuron Differentiation (GO:0071542)
6,Artery - Tibial,LV81,BP_Epidermis Development (GO:0008544)
7,Cells - EBV-transformed lymphocytes,LV123,BP_Reverse Cholesterol Transport (GO:0043691)
8,Cells - EBV-transformed lymphocytes,LV116,BP_Cilium Movement (GO:0003341)
9,Cells - EBV-transformed lymphocytes,LV244,BP_Mitochondrial Gene Expression (GO:0140053)
10,Cells - EBV-transformed lymphocytes,LV244,BP_Aerobic Electron Transport Chain (GO:0019646)
11,Heart - Left Ventricle,LV161,BP_Establishment of Chromosome Localization (GO:0051303)
12,Heart - Left Ventricle,LV161,BP_Positive Regulation of G2/M Transition of Mitotic Cell Cycle (GO:0010971)
13,Liver,LV35,BP_Immune Response-Regulating Cell Surface Receptor Signaling Pathway (GO:0002768)
14,Minor Salivary Gland,LV250,BP_Dendritic Cell Differentiation (GO:0097028)
15,Muscle - Skeletal,LV160,BP_Cholesterol Biosynthetic Process (GO:0006695)
16,Muscle - Skeletal,LV121,BP_Synaptic Vesicle Exocytosis (GO:0016079)
17,Muscle - Skeletal,LV121,BP_Neurotransmitter Secretion (GO:0007269)
18,Ovary,LV23,BP_Translation (GO:0006412)
19,Ovary,LV23,BP_Cytoplasmic Translation (GO:0002181)
20,Ovary,LV23,BP_Mitochondrial Translation (GO:0032543)
21,Ovary,LV23,BP_Cytoplasmic Translational Initiation (GO:0002183)
22,Ovary,LV23,BP_Ribosomal Small Subunit Assembly (GO:0000028)
23,Ovary,LV236,BP_Epidermis Development (GO:0008544)
24,Ovary,LV236,BP_Skin Development (GO:0043588)
25,Ovary,LV236,BP_Intermediate Filament Organization (GO:0045109)
26,Ovary,LV236,BP_Keratinocyte Differentiation (GO:0030216)
27,Spleen,LV51,BP_Axoneme Assembly (GO:0035082)
28,Spleen,LV51,BP_Cilium Movement (GO:0003341)
29,Spleen,LV51,BP_Cilium-Dependent Cell Motility (GO:0060285)
30,Spleen,LV51,BP_Axonemal Dynein Complex Assembly (GO:0070286)
31,Testis,LV164,BP_Cilium Movement (GO:0003341)
32,Testis,LV164,BP_Axoneme Assembly (GO:0035082)
33,Testis,LV164,BP_Axonemal Dynein Complex Assembly (GO:0070286)
34,Testis,LV164,BP_Cilium-Dependent Cell Motility (GO:0060285)
35,Testis,LV164,BP_Epithelial Cilium Movement Involved in Extracellular Fluid Movement (GO:0003351)
36,Testis,LV164,BP_Motile Cilium Assembly (GO:0044458)

In [90]:
# pct=40%  FDR<0.05  AUC>0.7  seen_lvs=False
_tpt = top_lvs_at_pct(40)
_df  = pathway_table(_tpt, fdr_thresh=0.05, auc_thresh=0.7, use_seen_lvs=False)
print(f'pct=40%  FDR<0.05  AUC>0.7  seen_lvs=False  ->  {len(_df)} rows, {_df["Tissue"].nunique()} tissues, {_df["LV"].nunique()} LVs')
_df[['Tissue', 'LV', 'pathway']]

pct=40%  FDR<0.05  AUC>0.7  seen_lvs=False  ->  48 rows, 14 tissues, 17 LVs

,Tissue,LV,pathway
0,Adipose - Visceral (Omentum),LV57,BP_Mitochondrial ATP Synthesis Coupled Electron Transport (GO:0042775)
1,Adipose - Visceral (Omentum),LV57,BP_Aerobic Electron Transport Chain (GO:0019646)
2,Adipose - Visceral (Omentum),LV57,BP_Aerobic Respiration (GO:0009060)
3,Adrenal Gland,LV3,BP_Negative Regulation of T Cell Mediated Immunity (GO:0002710)
4,Artery - Aorta,LV145,BP_Skeletal Muscle Contraction (GO:0003009)
5,Artery - Coronary,LV99,BP_Dopaminergic Neuron Differentiation (GO:0071542)
6,Artery - Tibial,LV81,BP_Epidermis Development (GO:0008544)
7,Cells - EBV-transformed lymphocytes,LV123,BP_Reverse Cholesterol Transport (GO:0043691)
8,Cells - EBV-transformed lymphocytes,LV116,BP_Cilium Movement (GO:0003341)
9,Cells - EBV-transformed lymphocytes,LV244,BP_Mitochondrial Gene Expression (GO:0140053)
10,Cells - EBV-transformed lymphocytes,LV244,BP_Aerobic Electron Transport Chain (GO:0019646)
11,Heart - Left Ventricle,LV161,BP_Establishment of Chromosome Localization (GO:0051303)
12,Heart - Left Ventricle,LV161,BP_Positive Regulation of G2/M Transition of Mitotic Cell Cycle (GO:0010971)
13,Liver,LV123,BP_Reverse Cholesterol Transport (GO:0043691)
14,Liver,LV35,BP_Immune Response-Regulating Cell Surface Receptor Signaling Pathway (GO:0002768)
15,Minor Salivary Gland,LV250,BP_Dendritic Cell Differentiation (GO:0097028)
16,Minor Salivary Gland,LV99,BP_Dopaminergic Neuron Differentiation (GO:0071542)
17,Muscle - Skeletal,LV160,BP_Cholesterol Biosynthetic Process (GO:0006695)
18,Muscle - Skeletal,LV121,BP_Synaptic Vesicle Exocytosis (GO:0016079)
19,Muscle - Skeletal,LV121,BP_Neurotransmitter Secretion (GO:0007269)
20,Ovary,LV23,BP_Translation (GO:0006412)
21,Ovary,LV23,BP_Cytoplasmic Translation (GO:0002181)
22,Ovary,LV23,BP_Mitochondrial Translation (GO:0032543)
23,Ovary,LV23,BP_Cytoplasmic Translational Initiation (GO:0002183)
24,Ovary,LV23,BP_Ribosomal Small Subunit Assembly (GO:0000028)
25,Ovary,LV3,BP_Negative Regulation of T Cell Mediated Immunity (GO:0002710)
26,Ovary,LV236,BP_Epidermis Development (GO:0008544)
27,Ovary,LV236,BP_Skin Development (GO:0043588)
28,Ovary,LV236,BP_Intermediate Filament Organization (GO:0045109)
29,Ovary,LV236,BP_Keratinocyte Differentiation (GO:0030216)
30,Spleen,LV123,BP_Reverse Cholesterol Transport (GO:0043691)
31,Spleen,LV51,BP_Axoneme Assembly (GO:0035082)
32,Spleen,LV51,BP_Cilium Movement (GO:0003341)
33,Spleen,LV51,BP_Cilium-Dependent Cell Motility (GO:0060285)
34,Spleen,LV51,BP_Axonemal Dynein Complex Assembly (GO:0070286)
35,Testis,LV164,BP_Cilium Movement (GO:0003341)
36,Testis,LV164,BP_Axoneme Assembly (GO:0035082)
37,Testis,LV164,BP_Axonemal Dynein Complex Assembly (GO:0070286)
38,Testis,LV164,BP_Cilium-Dependent Cell Motility (GO:0060285)
39,Testis,LV164,BP_Epithelial Cilium Movement Involved in Extracellular Fluid Movement (GO:0003351)
40,Testis,LV164,BP_Motile Cilium Assembly (GO:0044458)
41,Testis,LV123,BP_Reverse Cholesterol Transport (GO:0043691)
42,Thyroid,LV164,BP_Cilium Movement (GO:0003341)
43,Thyroid,LV164,BP_Axoneme Assembly (GO:0035082)
44,Thyroid,LV164,BP_Axonemal Dynein Complex Assembly (GO:0070286)
45,Thyroid,LV164,BP_Cilium-Dependent Cell Motility (GO:0060285)
46,Thyroid,LV164,BP_Epithelial Cilium Movement Involved in Extracellular Fluid Movement (GO:0003351)
47,Thyroid,LV164,BP_Motile Cilium Assembly (GO:0044458)

In [91]:
# pct=40%  FDR<0.1  AUC>0.6  seen_lvs=True
_tpt = top_lvs_at_pct(40)
_df  = pathway_table(_tpt, fdr_thresh=0.1, auc_thresh=0.6, use_seen_lvs=True)
print(f'pct=40%  FDR<0.1  AUC>0.6  seen_lvs=True  ->  {len(_df)} rows, {_df["Tissue"].nunique()} tissues, {_df["LV"].nunique()} LVs')
_df[['Tissue', 'LV', 'pathway']]

pct=40%  FDR<0.1  AUC>0.6  seen_lvs=True  ->  100 rows, 19 tissues, 36 LVs

,Tissue,LV,pathway
0,Adipose - Subcutaneous,LV263,BP_Positive Regulation of Lipid Catabolic Process (GO:0050996)
1,Adipose - Subcutaneous,LV263,BP_Regulation of Fatty Acid Beta-Oxidation (GO:0031998)
2,Adipose - Subcutaneous,LV263,BP_Positive Regulation of Fatty Acid Oxidation (GO:0046321)
3,Adipose - Visceral (Omentum),LV83,BP_Skeletal Muscle Contraction (GO:0003009)
4,Adipose - Visceral (Omentum),LV83,BP_Actin-Myosin Filament Sliding (GO:0033275)
5,Adipose - Visceral (Omentum),LV57,BP_Mitochondrial ATP Synthesis Coupled Electron Transport (GO:0042775)
6,Adipose - Visceral (Omentum),LV57,BP_Aerobic Electron Transport Chain (GO:0019646)
7,Adipose - Visceral (Omentum),LV57,BP_Aerobic Respiration (GO:0009060)
8,Adipose - Visceral (Omentum),LV57,"BP_Mitochondrial Electron Transport, Ubiquinol to Cytochrome C (GO:0006122)"
9,Adipose - Visceral (Omentum),LV106,BP_Endosome Transport via Multivesicular Body Sorting Pathway (GO:0032509)
10,Adrenal Gland,LV3,BP_Negative Regulation of T Cell Mediated Immunity (GO:0002710)
11,Adrenal Gland,LV183,BP_Positive Regulation of Synaptic Vesicle Fusion to Presynaptic Active Zone Membrane (GO:0031632)
12,Artery - Aorta,LV145,BP_Skeletal Muscle Contraction (GO:0003009)
13,Artery - Aorta,LV145,BP_Embryonic Skeletal System Morphogenesis (GO:0048704)
14,Artery - Aorta,LV40,BP_Quinone Biosynthetic Process (GO:1901663)
15,Artery - Coronary,LV247,BP_Cotranslational Protein Targeting to Membrane (GO:0006613)
16,Artery - Coronary,LV99,BP_Dopaminergic Neuron Differentiation (GO:0071542)
17,Artery - Coronary,LV99,BP_Branching Involved in Blood Vessel Morphogenesis (GO:0001569)
18,Artery - Tibial,LV81,BP_Epidermis Development (GO:0008544)
19,Artery - Tibial,LV81,BP_Intermediate Filament Organization (GO:0045109)
20,Artery - Tibial,LV81,BP_Peptide Cross-Linking (GO:0018149)
21,Artery - Tibial,LV81,BP_Negative Regulation of Vascular Permeability (GO:0043116)
22,Cells - Cultured fibroblasts,LV111,BP_Antigen Processing and Presentation of Endogenous Peptide Antigen (GO:0002483)
23,Cells - Cultured fibroblasts,LV111,BP_Ag Processing and Presentation of Endogenous Pep Ag via MHC Cls I via ER Pway (GO:0002484)
24,Cells - Cultured fibroblasts,LV111,BP_Antigen Processing and Presentation of Endogenous Peptide Antigen via MHC Class Ib (GO:0002476)
25,Cells - Cultured fibroblasts,LV111,"BP_Ag Processing and Presentation of Endogenous Pep Ag via MHC Cls I via ER Pway, TAP-ind (GO:0002486)"
26,Cells - Cultured fibroblasts,LV91,BP_MHC Class II Protein Complex Assembly (GO:0002399)
27,Cells - Cultured fibroblasts,LV91,BP_Interleukin-10-Mediated Signaling Pathway (GO:0140105)
28,Cells - Cultured fibroblasts,LV91,BP_Peptide Antigen Assembly With MHC Class II Protein Complex (GO:0002503)
29,Cells - Cultured fibroblasts,LV91,BP_Antigen Processing and Presentation of Exogenous Peptide Antigen (GO:0002478)
30,Cells - EBV-transformed lymphocytes,LV123,BP_Reverse Cholesterol Transport (GO:0043691)
31,Cells - EBV-transformed lymphocytes,LV123,BP_Fatty Acid Beta-Oxidation (GO:0006635)
32,Cells - EBV-transformed lymphocytes,LV123,BP_Fatty Acid Beta-Oxidation Using acyl-CoA Oxidase (GO:0033540)
33,Cells - EBV-transformed lymphocytes,LV123,BP_Positive Regulation of Fatty Acid Metabolic Process (GO:0045923)
34,Cells - EBV-transformed lymphocytes,LV116,BP_Cilium Movement (GO:0003341)
35,Cells - EBV-transformed lymphocytes,LV116,BP_Axoneme Assembly (GO:0035082)
36,Cells - EBV-transformed lymphocytes,LV116,BP_Homologous Chromosome Pairing at Meiosis (GO:0007129)
37,Cells - EBV-transformed lymphocytes,LV244,BP_Mitochondrial Gene Expression (GO:0140053)
38,Cells - EBV-transformed lymphocytes,LV244,BP_Aerobic Electron Transport Chain (GO:0019646)
39,Cells - EBV-transformed lymphocytes,LV244,BP_Mitochondrial Cytochrome C Oxidase Assembly (GO:0033617)
40,Cells - EBV-transformed lymphocytes,LV244,"BP_Mitochondrial Electron Transport, Ubiquinol to Cytochrome C (GO:0006122)"
41,Cells - EBV-transformed lymphocytes,LV244,"BP_Mitochondrial Electron Transport, NADH to Ubiquinone (GO:0006120)"
42,Cells - EBV-transformed lymphocytes,LV244,"BP_Mitochondrial Electron Transport, Cytochrome C to Oxygen (GO:0006123)"
43,Heart - Atrial Appendage,LV139,BP_Branching Involved in Blood Vessel Morphogenesis (GO:0001569)
44,Heart - Left Ventricle,LV161,BP_Establishment of Chromosome Localization (GO:0051303)
45,Heart - Left Ventricle,LV161,BP_Positive Regulation of G2/M Transition of Mitotic Cell Cycle (GO:0010971)
46,Heart - Left Ventricle,LV161,BP_DNA Strand Elongation Involved in DNA Replication (GO:0006271)
47,Heart - Left Ventricle,LV161,BP_DNA Strand Elongation (GO:0022616)
48,Heart - Left Ventricle,LV161,BP_Regulation of DNA-templated DNA Replication Initiation (GO:0030174)
49,Heart - Left Ventricle,LV161,BP_Positive Regulation of Mitotic Cell Cycle Spindle Assembly Checkpoint (GO:0090267)
50,Heart - Left Ventricle,LV161,BP_Positive Regulation of Cell Cycle G2/M Phase Transition (GO:1902751)
51,Liver,LV229,BP_Negative Regulation of Smooth Muscle Cell Differentiation (GO:0051151)
52,Liver,LV21,BP_Cellular Response to Zinc Ion (GO:0071294)
53,Liver,LV21,BP_Low-Density Lipoprotein Particle Remodeling (GO:0034374)
54,Liver,LV35,BP_Immune Response-Regulating Cell Surface Receptor Signaling Pathway (GO:0002768)
55,Lung,LV208,BP_Late Endosome to Vacuole Transport via Multivesicular Body Sorting Pathway (GO:0032511)
56,Lung,LV208,BP_Pexophagy (GO:0000425)
57,Minor Salivary Gland,LV250,BP_Dendritic Cell Differentiation (GO:0097028)
58,Minor Salivary Gland,LV250,BP_Dendritic Cell Chemotaxis (GO:0002407)
59,Muscle - Skeletal,LV160,BP_Cholesterol Biosynthetic Process (GO:0006695)
60,Muscle - Skeletal,LV160,BP_Sterol Biosynthetic Process (GO:0016126)
61,Muscle - Skeletal,LV160,BP_Secondary Alcohol Biosynthetic Process (GO:1902653)
62,Muscle - Skeletal,LV121,BP_Synaptic Vesicle Exocytosis (GO:0016079)
63,Muscle - Skeletal,LV121,BP_Neurotransmitter Secretion (GO:0007269)
64,Nerve - Tibial,LV128,BP_Catecholamine Biosynthetic Process (GO:0042423)
65,Ovary,LV46,BP_Response to Glucocorticoid (GO:0051384)
66,Ovary,LV23,BP_Translation (GO:0006412)
67,Ovary,LV23,BP_Cytoplasmic Translation (GO:0002181)
68,Ovary,LV23,BP_Mitochondrial Translation (GO:0032543)
69,Ovary,LV23,BP_Cytoplasmic Translational Initiation (GO:0002183)
70,Ovary,LV23,BP_Ribosomal Small Subunit Assembly (GO:0000028)
71,Ovary,LV23,BP_U2-type Prespliceosome Assembly (GO:1903241)
72,Ovary,LV23,BP_Formation of Cytoplasmic Translation Initiation Complex (GO:0001732)
73,Ovary,LV236,BP_Epidermis Development (GO:0008544)
74,Ovary,LV236,BP_Skin Development (GO:0043588)
75,Ovary,LV236,BP_Intermediate Filament Organization (GO:0045109)
76,Ovary,LV236,BP_Keratinocyte Differentiation (GO:0030216)
77,Spleen,LV55,BP_Positive Regulation of Signaling Receptor Activity (GO:2000273)
78,Spleen,LV55,BP_Basement Membrane Organization (GO:0071711)
79,Spleen,LV51,BP_Axoneme Assembly (GO:0035082)
80,Spleen,LV51,BP_Cilium Movement (GO:0003341)
81,Spleen,LV51,BP_Cilium-Dependent Cell Motility (GO:0060285)
82,Spleen,LV51,BP_Axonemal Dynein Complex Assembly (GO:0070286)
83,Spleen,LV51,BP_Intraciliary Anterograde Transport (GO:0035720)
84,Spleen,LV51,BP_Intraciliary Retrograde Transport (GO:0035721)
85,Spleen,LV51,BP_Motile Cilium Assembly (GO:0044458)
86,Testis,LV69,BP_Male Gamete Generation (GO:0048232)
87,Testis,LV69,BP_Transposable Element Silencing by Heterochromatin Formation (GO:0141005)
88,Testis,LV69,BP_piRNA Processing (GO:0034587)
89,Testis,LV164,BP_Cilium Movement (GO:0003341)
90,Testis,LV164,BP_Axoneme Assembly (GO:0035082)
91,Testis,LV164,BP_Axonemal Dynein Complex Assembly (GO:0070286)
92,Testis,LV164,BP_Cilium-Dependent Cell Motility (GO:0060285)
93,Testis,LV164,BP_Epithelial Cilium Movement Involved in Extracellular Fluid Movement (GO:0003351)
94,Testis,LV164,BP_Motile Cilium Assembly (GO:0044458)
95,Whole Blood,LV238,BP_Calcium-Dependent Activation of Synaptic Vesicle Fusion (GO:0099502)
96,Whole Blood,LV238,BP_Positive Regulation of Calcium Ion-Dependent Exocytosis (GO:0045956)
97,Whole Blood,LV238,BP_Positive Regulation of Synaptic Vesicle Fusion to Presynaptic Active Zone Membrane (GO:0031632)
98,Whole Blood,LV93,BP_Positive Regulation of Ruffle Assembly (GO:1900029)
99,Whole Blood,LV155,BP_Tertiary Alcohol Metabolic Process (GO:1902644)

In [92]:
# pct=40%  FDR<0.1  AUC>0.6  seen_lvs=False
_tpt = top_lvs_at_pct(40)
_df  = pathway_table(_tpt, fdr_thresh=0.1, auc_thresh=0.6, use_seen_lvs=False)
print(f'pct=40%  FDR<0.1  AUC>0.6  seen_lvs=False  ->  {len(_df)} rows, {_df["Tissue"].nunique()} tissues, {_df["LV"].nunique()} LVs')
_df[['Tissue', 'LV', 'pathway']]

pct=40%  FDR<0.1  AUC>0.6  seen_lvs=False  ->  133 rows, 23 tissues, 36 LVs

,Tissue,LV,pathway
0,Adipose - Subcutaneous,LV263,BP_Positive Regulation of Lipid Catabolic Process (GO:0050996)
1,Adipose - Subcutaneous,LV263,BP_Regulation of Fatty Acid Beta-Oxidation (GO:0031998)
2,Adipose - Subcutaneous,LV263,BP_Positive Regulation of Fatty Acid Oxidation (GO:0046321)
3,Adipose - Visceral (Omentum),LV263,BP_Positive Regulation of Lipid Catabolic Process (GO:0050996)
4,Adipose - Visceral (Omentum),LV263,BP_Regulation of Fatty Acid Beta-Oxidation (GO:0031998)
5,Adipose - Visceral (Omentum),LV263,BP_Positive Regulation of Fatty Acid Oxidation (GO:0046321)
6,Adipose - Visceral (Omentum),LV83,BP_Skeletal Muscle Contraction (GO:0003009)
7,Adipose - Visceral (Omentum),LV83,BP_Actin-Myosin Filament Sliding (GO:0033275)
8,Adipose - Visceral (Omentum),LV57,BP_Mitochondrial ATP Synthesis Coupled Electron Transport (GO:0042775)
9,Adipose - Visceral (Omentum),LV57,BP_Aerobic Electron Transport Chain (GO:0019646)
10,Adipose - Visceral (Omentum),LV57,BP_Aerobic Respiration (GO:0009060)
11,Adipose - Visceral (Omentum),LV57,"BP_Mitochondrial Electron Transport, Ubiquinol to Cytochrome C (GO:0006122)"
12,Adipose - Visceral (Omentum),LV106,BP_Endosome Transport via Multivesicular Body Sorting Pathway (GO:0032509)
13,Adrenal Gland,LV83,BP_Skeletal Muscle Contraction (GO:0003009)
14,Adrenal Gland,LV83,BP_Actin-Myosin Filament Sliding (GO:0033275)
15,Adrenal Gland,LV3,BP_Negative Regulation of T Cell Mediated Immunity (GO:0002710)
16,Adrenal Gland,LV183,BP_Positive Regulation of Synaptic Vesicle Fusion to Presynaptic Active Zone Membrane (GO:0031632)
17,Artery - Aorta,LV145,BP_Skeletal Muscle Contraction (GO:0003009)
18,Artery - Aorta,LV145,BP_Embryonic Skeletal System Morphogenesis (GO:0048704)
19,Artery - Aorta,LV40,BP_Quinone Biosynthetic Process (GO:1901663)
20,Artery - Coronary,LV40,BP_Quinone Biosynthetic Process (GO:1901663)
21,Artery - Coronary,LV247,BP_Cotranslational Protein Targeting to Membrane (GO:0006613)
22,Artery - Coronary,LV99,BP_Dopaminergic Neuron Differentiation (GO:0071542)
23,Artery - Coronary,LV99,BP_Branching Involved in Blood Vessel Morphogenesis (GO:0001569)
24,Artery - Coronary,LV106,BP_Endosome Transport via Multivesicular Body Sorting Pathway (GO:0032509)
25,Artery - Tibial,LV81,BP_Epidermis Development (GO:0008544)
26,Artery - Tibial,LV81,BP_Intermediate Filament Organization (GO:0045109)
27,Artery - Tibial,LV81,BP_Peptide Cross-Linking (GO:0018149)
28,Artery - Tibial,LV81,BP_Negative Regulation of Vascular Permeability (GO:0043116)
29,Cells - Cultured fibroblasts,LV111,BP_Antigen Processing and Presentation of Endogenous Peptide Antigen (GO:0002483)
30,Cells - Cultured fibroblasts,LV111,BP_Ag Processing and Presentation of Endogenous Pep Ag via MHC Cls I via ER Pway (GO:0002484)
31,Cells - Cultured fibroblasts,LV111,BP_Antigen Processing and Presentation of Endogenous Peptide Antigen via MHC Class Ib (GO:0002476)
32,Cells - Cultured fibroblasts,LV111,"BP_Ag Processing and Presentation of Endogenous Pep Ag via MHC Cls I via ER Pway, TAP-ind (GO:0002486)"
33,Cells - Cultured fibroblasts,LV91,BP_MHC Class II Protein Complex Assembly (GO:0002399)
34,Cells - Cultured fibroblasts,LV91,BP_Interleukin-10-Mediated Signaling Pathway (GO:0140105)
35,Cells - Cultured fibroblasts,LV91,BP_Peptide Antigen Assembly With MHC Class II Protein Complex (GO:0002503)
36,Cells - Cultured fibroblasts,LV91,BP_Antigen Processing and Presentation of Exogenous Peptide Antigen (GO:0002478)
37,Cells - EBV-transformed lymphocytes,LV123,BP_Reverse Cholesterol Transport (GO:0043691)
38,Cells - EBV-transformed lymphocytes,LV123,BP_Fatty Acid Beta-Oxidation (GO:0006635)
39,Cells - EBV-transformed lymphocytes,LV123,BP_Fatty Acid Beta-Oxidation Using acyl-CoA Oxidase (GO:0033540)
40,Cells - EBV-transformed lymphocytes,LV123,BP_Positive Regulation of Fatty Acid Metabolic Process (GO:0045923)
41,Cells - EBV-transformed lymphocytes,LV116,BP_Cilium Movement (GO:0003341)
42,Cells - EBV-transformed lymphocytes,LV116,BP_Axoneme Assembly (GO:0035082)
43,Cells - EBV-transformed lymphocytes,LV116,BP_Homologous Chromosome Pairing at Meiosis (GO:0007129)
44,Cells - EBV-transformed lymphocytes,LV244,BP_Mitochondrial Gene Expression (GO:0140053)
45,Cells - EBV-transformed lymphocytes,LV244,BP_Aerobic Electron Transport Chain (GO:0019646)
46,Cells - EBV-transformed lymphocytes,LV244,BP_Mitochondrial Cytochrome C Oxidase Assembly (GO:0033617)
47,Cells - EBV-transformed lymphocytes,LV244,"BP_Mitochondrial Electron Transport, Ubiquinol to Cytochrome C (GO:0006122)"
48,Cells - EBV-transformed lymphocytes,LV244,"BP_Mitochondrial Electron Transport, NADH to Ubiquinone (GO:0006120)"
49,Cells - EBV-transformed lymphocytes,LV244,"BP_Mitochondrial Electron Transport, Cytochrome C to Oxygen (GO:0006123)"
50,Heart - Atrial Appendage,LV139,BP_Branching Involved in Blood Vessel Morphogenesis (GO:0001569)
51,Heart - Left Ventricle,LV161,BP_Establishment of Chromosome Localization (GO:0051303)
52,Heart - Left Ventricle,LV161,BP_Positive Regulation of G2/M Transition of Mitotic Cell Cycle (GO:0010971)
53,Heart - Left Ventricle,LV161,BP_DNA Strand Elongation Involved in DNA Replication (GO:0006271)
54,Heart - Left Ventricle,LV161,BP_DNA Strand Elongation (GO:0022616)
55,Heart - Left Ventricle,LV161,BP_Regulation of DNA-templated DNA Replication Initiation (GO:0030174)
56,Heart - Left Ventricle,LV161,BP_Positive Regulation of Mitotic Cell Cycle Spindle Assembly Checkpoint (GO:0090267)
57,Heart - Left Ventricle,LV161,BP_Positive Regulation of Cell Cycle G2/M Phase Transition (GO:1902751)
58,Liver,LV229,BP_Negative Regulation of Smooth Muscle Cell Differentiation (GO:0051151)
59,Liver,LV21,BP_Cellular Response to Zinc Ion (GO:0071294)
60,Liver,LV21,BP_Low-Density Lipoprotein Particle Remodeling (GO:0034374)
61,Liver,LV123,BP_Reverse Cholesterol Transport (GO:0043691)
62,Liver,LV123,BP_Fatty Acid Beta-Oxidation (GO:0006635)
63,Liver,LV123,BP_Fatty Acid Beta-Oxidation Using acyl-CoA Oxidase (GO:0033540)
64,Liver,LV123,BP_Positive Regulation of Fatty Acid Metabolic Process (GO:0045923)
65,Liver,LV35,BP_Immune Response-Regulating Cell Surface Receptor Signaling Pathway (GO:0002768)
66,Lung,LV208,BP_Late Endosome to Vacuole Transport via Multivesicular Body Sorting Pathway (GO:0032511)
67,Lung,LV208,BP_Pexophagy (GO:0000425)
68,Minor Salivary Gland,LV250,BP_Dendritic Cell Differentiation (GO:0097028)
69,Minor Salivary Gland,LV250,BP_Dendritic Cell Chemotaxis (GO:0002407)
70,Minor Salivary Gland,LV99,BP_Dopaminergic Neuron Differentiation (GO:0071542)
71,Minor Salivary Gland,LV99,BP_Branching Involved in Blood Vessel Morphogenesis (GO:0001569)
72,Muscle - Skeletal,LV160,BP_Cholesterol Biosynthetic Process (GO:0006695)
73,Muscle - Skeletal,LV160,BP_Sterol Biosynthetic Process (GO:0016126)
74,Muscle - Skeletal,LV160,BP_Secondary Alcohol Biosynthetic Process (GO:1902653)
75,Muscle - Skeletal,LV121,BP_Synaptic Vesicle Exocytosis (GO:0016079)
76,Muscle - Skeletal,LV121,BP_Neurotransmitter Secretion (GO:0007269)
77,Nerve - Tibial,LV128,BP_Catecholamine Biosynthetic Process (GO:0042423)
78,Ovary,LV46,BP_Response to Glucocorticoid (GO:0051384)
79,Ovary,LV23,BP_Translation (GO:0006412)
80,Ovary,LV23,BP_Cytoplasmic Translation (GO:0002181)
81,Ovary,LV23,BP_Mitochondrial Translation (GO:0032543)
82,Ovary,LV23,BP_Cytoplasmic Translational Initiation (GO:0002183)
83,Ovary,LV23,BP_Ribosomal Small Subunit Assembly (GO:0000028)
84,Ovary,LV23,BP_U2-type Prespliceosome Assembly (GO:1903241)
85,Ovary,LV23,BP_Formation of Cytoplasmic Translation Initiation Complex (GO:0001732)
86,Ovary,LV3,BP_Negative Regulation of T Cell Mediated Immunity (GO:0002710)
87,Ovary,LV236,BP_Epidermis Development (GO:0008544)
88,Ovary,LV236,BP_Skin Development (GO:0043588)
89,Ovary,LV236,BP_Intermediate Filament Organization (GO:0045109)
90,Ovary,LV236,BP_Keratinocyte Differentiation (GO:0030216)
91,Pancreas,LV229,BP_Negative Regulation of Smooth Muscle Cell Differentiation (GO:0051151)
92,Pituitary,LV21,BP_Cellular Response to Zinc Ion (GO:0071294)
93,Pituitary,LV21,BP_Low-Density Lipoprotein Particle Remodeling (GO:0034374)
94,Prostate,LV83,BP_Skeletal Muscle Contraction (GO:0003009)
95,Prostate,LV83,BP_Actin-Myosin Filament Sliding (GO:0033275)
96,Spleen,LV123,BP_Reverse Cholesterol Transport (GO:0043691)
97,Spleen,LV123,BP_Fatty Acid Beta-Oxidation (GO:0006635)
98,Spleen,LV123,BP_Fatty Acid Beta-Oxidation Using acyl-CoA Oxidase (GO:0033540)
99,Spleen,LV123,BP_Positive Regulation of Fatty Acid Metabolic Process (GO:0045923)
100,Spleen,LV55,BP_Positive Regulation of Signaling Receptor Activity (GO:2000273)
101,Spleen,LV55,BP_Basement Membrane Organization (GO:0071711)
102,Spleen,LV51,BP_Axoneme Assembly (GO:0035082)
103,Spleen,LV51,BP_Cilium Movement (GO:0003341)
104,Spleen,LV51,BP_Cilium-Dependent Cell Motility (GO:0060285)
105,Spleen,LV51,BP_Axonemal Dynein Complex Assembly (GO:0070286)
106,Spleen,LV51,BP_Intraciliary Anterograde Transport (GO:0035720)
107,Spleen,LV51,BP_Intraciliary Retrograde Transport (GO:0035721)
108,Spleen,LV51,BP_Motile Cilium Assembly (GO:0044458)
109,Testis,LV69,BP_Male Gamete Generation (GO:0048232)
110,Testis,LV69,BP_Transposable Element Silencing by Heterochromatin Formation (GO:0141005)
111,Testis,LV69,BP_piRNA Processing (GO:0034587)
112,Testis,LV164,BP_Cilium Movement (GO:0003341)
113,Testis,LV164,BP_Axoneme Assembly (GO:0035082)
114,Testis,LV164,BP_Axonemal Dynein Complex Assembly (GO:0070286)
115,Testis,LV164,BP_Cilium-Dependent Cell Motility (GO:0060285)
116,Testis,LV164,BP_Epithelial Cilium Movement Involved in Extracellular Fluid Movement (GO:0003351)
117,Testis,LV164,BP_Motile Cilium Assembly (GO:0044458)
118,Testis,LV123,BP_Reverse Cholesterol Transport (GO:0043691)
119,Testis,LV123,BP_Fatty Acid Beta-Oxidation (GO:0006635)
120,Testis,LV123,BP_Fatty Acid Beta-Oxidation Using acyl-CoA Oxidase (GO:0033540)
121,Testis,LV123,BP_Positive Regulation of Fatty Acid Metabolic Process (GO:0045923)
122,Thyroid,LV164,BP_Cilium Movement (GO:0003341)
123,Thyroid,LV164,BP_Axoneme Assembly (GO:0035082)
124,Thyroid,LV164,BP_Axonemal Dynein Complex Assembly (GO:0070286)
125,Thyroid,LV164,BP_Cilium-Dependent Cell Motility (GO:0060285)
126,Thyroid,LV164,BP_Epithelial Cilium Movement Involved in Extracellular Fluid Movement (GO:0003351)
127,Thyroid,LV164,BP_Motile Cilium Assembly (GO:0044458)
128,Whole Blood,LV238,BP_Calcium-Dependent Activation of Synaptic Vesicle Fusion (GO:0099502)
129,Whole Blood,LV238,BP_Positive Regulation of Calcium Ion-Dependent Exocytosis (GO:0045956)
130,Whole Blood,LV238,BP_Positive Regulation of Synaptic Vesicle Fusion to Presynaptic Active Zone Membrane (GO:0031632)
131,Whole Blood,LV93,BP_Positive Regulation of Ruffle Assembly (GO:1900029)
132,Whole Blood,LV155,BP_Tertiary Alcohol Metabolic Process (GO:1902644)

In [93]:
# pct=50%  FDR<0.05  AUC>0.7  seen_lvs=True
_tpt = top_lvs_at_pct(50)
_df  = pathway_table(_tpt, fdr_thresh=0.05, auc_thresh=0.7, use_seen_lvs=True)
print(f'pct=50%  FDR<0.05  AUC>0.7  seen_lvs=True  ->  {len(_df)} rows, {_df["Tissue"].nunique()} tissues, {_df["LV"].nunique()} LVs')
_df[['Tissue', 'LV', 'pathway']]

pct=50%  FDR<0.05  AUC>0.7  seen_lvs=True  ->  47 rows, 14 tissues, 21 LVs

,Tissue,LV,pathway
0,Adipose - Subcutaneous,LV145,BP_Skeletal Muscle Contraction (GO:0003009)
1,Adipose - Visceral (Omentum),LV57,BP_Mitochondrial ATP Synthesis Coupled Electron Transport (GO:0042775)
2,Adipose - Visceral (Omentum),LV57,BP_Aerobic Electron Transport Chain (GO:0019646)
3,Adipose - Visceral (Omentum),LV57,BP_Aerobic Respiration (GO:0009060)
4,Adipose - Visceral (Omentum),LV2,BP_Regulation of Calcium Ion-Dependent Exocytosis (GO:0017158)
5,Adrenal Gland,LV3,BP_Negative Regulation of T Cell Mediated Immunity (GO:0002710)
6,Artery - Aorta,LV81,BP_Epidermis Development (GO:0008544)
7,Artery - Coronary,LV99,BP_Dopaminergic Neuron Differentiation (GO:0071542)
8,Cells - EBV-transformed lymphocytes,LV123,BP_Reverse Cholesterol Transport (GO:0043691)
9,Cells - EBV-transformed lymphocytes,LV116,BP_Cilium Movement (GO:0003341)
10,Cells - EBV-transformed lymphocytes,LV244,BP_Mitochondrial Gene Expression (GO:0140053)
11,Cells - EBV-transformed lymphocytes,LV244,BP_Aerobic Electron Transport Chain (GO:0019646)
12,Heart - Left Ventricle,LV161,BP_Establishment of Chromosome Localization (GO:0051303)
13,Heart - Left Ventricle,LV161,BP_Positive Regulation of G2/M Transition of Mitotic Cell Cycle (GO:0010971)
14,Liver,LV35,BP_Immune Response-Regulating Cell Surface Receptor Signaling Pathway (GO:0002768)
15,Liver,LV121,BP_Synaptic Vesicle Exocytosis (GO:0016079)
16,Liver,LV121,BP_Neurotransmitter Secretion (GO:0007269)
17,Minor Salivary Gland,LV250,BP_Dendritic Cell Differentiation (GO:0097028)
18,Muscle - Skeletal,LV160,BP_Cholesterol Biosynthetic Process (GO:0006695)
19,Muscle - Skeletal,LV22,BP_Synaptic Membrane Adhesion (GO:0099560)
20,Ovary,LV23,BP_Translation (GO:0006412)
21,Ovary,LV23,BP_Cytoplasmic Translation (GO:0002181)
22,Ovary,LV23,BP_Mitochondrial Translation (GO:0032543)
23,Ovary,LV23,BP_Cytoplasmic Translational Initiation (GO:0002183)
24,Ovary,LV23,BP_Ribosomal Small Subunit Assembly (GO:0000028)
25,Ovary,LV236,BP_Epidermis Development (GO:0008544)
26,Ovary,LV236,BP_Skin Development (GO:0043588)
27,Ovary,LV236,BP_Intermediate Filament Organization (GO:0045109)
28,Ovary,LV236,BP_Keratinocyte Differentiation (GO:0030216)
29,Ovary,LV110,BP_Eosinophil Chemotaxis (GO:0048245)
30,Ovary,LV110,BP_Eosinophil Migration (GO:0072677)
31,Ovary,LV110,BP_Reverse Cholesterol Transport (GO:0043691)
32,Pancreas,LV60,BP_Mitochondrial ATP Synthesis Coupled Electron Transport (GO:0042775)
33,Pancreas,LV60,BP_Aerobic Electron Transport Chain (GO:0019646)
34,Pancreas,LV60,BP_Oxidative Phosphorylation (GO:0006119)
35,Pancreas,LV60,BP_Proton Motive Force-Driven Mitochondrial ATP Synthesis (GO:0042776)
36,Pancreas,LV60,BP_Proton Motive Force-Driven ATP Synthesis (GO:0015986)
37,Pituitary,LV164,BP_Cilium Movement (GO:0003341)
38,Pituitary,LV164,BP_Axoneme Assembly (GO:0035082)
39,Pituitary,LV164,BP_Axonemal Dynein Complex Assembly (GO:0070286)
40,Pituitary,LV164,BP_Cilium-Dependent Cell Motility (GO:0060285)
41,Pituitary,LV164,BP_Epithelial Cilium Movement Involved in Extracellular Fluid Movement (GO:0003351)
42,Pituitary,LV164,BP_Motile Cilium Assembly (GO:0044458)
43,Spleen,LV51,BP_Axoneme Assembly (GO:0035082)
44,Spleen,LV51,BP_Cilium Movement (GO:0003341)
45,Spleen,LV51,BP_Cilium-Dependent Cell Motility (GO:0060285)
46,Spleen,LV51,BP_Axonemal Dynein Complex Assembly (GO:0070286)

In [94]:
# pct=50%  FDR<0.05  AUC>0.7  seen_lvs=False
_tpt = top_lvs_at_pct(50)
_df  = pathway_table(_tpt, fdr_thresh=0.05, auc_thresh=0.7, use_seen_lvs=False)
print(f'pct=50%  FDR<0.05  AUC>0.7  seen_lvs=False  ->  {len(_df)} rows, {_df["Tissue"].nunique()} tissues, {_df["LV"].nunique()} LVs')
_df[['Tissue', 'LV', 'pathway']]

pct=50%  FDR<0.05  AUC>0.7  seen_lvs=False  ->  86 rows, 21 tissues, 21 LVs

,Tissue,LV,pathway
0,Adipose - Subcutaneous,LV145,BP_Skeletal Muscle Contraction (GO:0003009)
1,Adipose - Visceral (Omentum),LV57,BP_Mitochondrial ATP Synthesis Coupled Electron Transport (GO:0042775)
2,Adipose - Visceral (Omentum),LV57,BP_Aerobic Electron Transport Chain (GO:0019646)
3,Adipose - Visceral (Omentum),LV57,BP_Aerobic Respiration (GO:0009060)
4,Adipose - Visceral (Omentum),LV2,BP_Regulation of Calcium Ion-Dependent Exocytosis (GO:0017158)
5,Adrenal Gland,LV3,BP_Negative Regulation of T Cell Mediated Immunity (GO:0002710)
6,Artery - Aorta,LV145,BP_Skeletal Muscle Contraction (GO:0003009)
7,Artery - Aorta,LV81,BP_Epidermis Development (GO:0008544)
8,Artery - Coronary,LV99,BP_Dopaminergic Neuron Differentiation (GO:0071542)
9,Artery - Tibial,LV81,BP_Epidermis Development (GO:0008544)
10,Cells - EBV-transformed lymphocytes,LV123,BP_Reverse Cholesterol Transport (GO:0043691)
11,Cells - EBV-transformed lymphocytes,LV116,BP_Cilium Movement (GO:0003341)
12,Cells - EBV-transformed lymphocytes,LV244,BP_Mitochondrial Gene Expression (GO:0140053)
13,Cells - EBV-transformed lymphocytes,LV244,BP_Aerobic Electron Transport Chain (GO:0019646)
14,Cells - EBV-transformed lymphocytes,LV145,BP_Skeletal Muscle Contraction (GO:0003009)
15,Esophagus - Mucosa,LV81,BP_Epidermis Development (GO:0008544)
16,Heart - Atrial Appendage,LV145,BP_Skeletal Muscle Contraction (GO:0003009)
17,Heart - Left Ventricle,LV161,BP_Establishment of Chromosome Localization (GO:0051303)
18,Heart - Left Ventricle,LV161,BP_Positive Regulation of G2/M Transition of Mitotic Cell Cycle (GO:0010971)
19,Heart - Left Ventricle,LV81,BP_Epidermis Development (GO:0008544)
20,Liver,LV123,BP_Reverse Cholesterol Transport (GO:0043691)
21,Liver,LV35,BP_Immune Response-Regulating Cell Surface Receptor Signaling Pathway (GO:0002768)
22,Liver,LV116,BP_Cilium Movement (GO:0003341)
23,Liver,LV121,BP_Synaptic Vesicle Exocytosis (GO:0016079)
24,Liver,LV121,BP_Neurotransmitter Secretion (GO:0007269)
25,Minor Salivary Gland,LV250,BP_Dendritic Cell Differentiation (GO:0097028)
26,Minor Salivary Gland,LV99,BP_Dopaminergic Neuron Differentiation (GO:0071542)
27,Muscle - Skeletal,LV160,BP_Cholesterol Biosynthetic Process (GO:0006695)
28,Muscle - Skeletal,LV121,BP_Synaptic Vesicle Exocytosis (GO:0016079)
29,Muscle - Skeletal,LV121,BP_Neurotransmitter Secretion (GO:0007269)
30,Muscle - Skeletal,LV22,BP_Synaptic Membrane Adhesion (GO:0099560)
31,Ovary,LV23,BP_Translation (GO:0006412)
32,Ovary,LV23,BP_Cytoplasmic Translation (GO:0002181)
33,Ovary,LV23,BP_Mitochondrial Translation (GO:0032543)
34,Ovary,LV23,BP_Cytoplasmic Translational Initiation (GO:0002183)
35,Ovary,LV23,BP_Ribosomal Small Subunit Assembly (GO:0000028)
36,Ovary,LV3,BP_Negative Regulation of T Cell Mediated Immunity (GO:0002710)
37,Ovary,LV236,BP_Epidermis Development (GO:0008544)
38,Ovary,LV236,BP_Skin Development (GO:0043588)
39,Ovary,LV236,BP_Intermediate Filament Organization (GO:0045109)
40,Ovary,LV236,BP_Keratinocyte Differentiation (GO:0030216)
41,Ovary,LV110,BP_Eosinophil Chemotaxis (GO:0048245)
42,Ovary,LV110,BP_Eosinophil Migration (GO:0072677)
43,Ovary,LV110,BP_Reverse Cholesterol Transport (GO:0043691)
44,Pancreas,LV60,BP_Mitochondrial ATP Synthesis Coupled Electron Transport (GO:0042775)
45,Pancreas,LV60,BP_Aerobic Electron Transport Chain (GO:0019646)
46,Pancreas,LV60,BP_Oxidative Phosphorylation (GO:0006119)
47,Pancreas,LV60,BP_Proton Motive Force-Driven Mitochondrial ATP Synthesis (GO:0042776)
48,Pancreas,LV60,BP_Proton Motive Force-Driven ATP Synthesis (GO:0015986)
49,Pituitary,LV145,BP_Skeletal Muscle Contraction (GO:0003009)
50,Pituitary,LV164,BP_Cilium Movement (GO:0003341)
51,Pituitary,LV164,BP_Axoneme Assembly (GO:0035082)
52,Pituitary,LV164,BP_Axonemal Dynein Complex Assembly (GO:0070286)
53,Pituitary,LV164,BP_Cilium-Dependent Cell Motility (GO:0060285)
54,Pituitary,LV164,BP_Epithelial Cilium Movement Involved in Extracellular Fluid Movement (GO:0003351)
55,Pituitary,LV164,BP_Motile Cilium Assembly (GO:0044458)
56,Pituitary,LV2,BP_Regulation of Calcium Ion-Dependent Exocytosis (GO:0017158)
57,Prostate,LV3,BP_Negative Regulation of T Cell Mediated Immunity (GO:0002710)
58,Spleen,LV123,BP_Reverse Cholesterol Transport (GO:0043691)
59,Spleen,LV51,BP_Axoneme Assembly (GO:0035082)
60,Spleen,LV51,BP_Cilium Movement (GO:0003341)
61,Spleen,LV51,BP_Cilium-Dependent Cell Motility (GO:0060285)
62,Spleen,LV51,BP_Axonemal Dynein Complex Assembly (GO:0070286)
63,Spleen,LV250,BP_Dendritic Cell Differentiation (GO:0097028)
64,Spleen,LV81,BP_Epidermis Development (GO:0008544)
65,Testis,LV164,BP_Cilium Movement (GO:0003341)
66,Testis,LV164,BP_Axoneme Assembly (GO:0035082)
67,Testis,LV164,BP_Axonemal Dynein Complex Assembly (GO:0070286)
68,Testis,LV164,BP_Cilium-Dependent Cell Motility (GO:0060285)
69,Testis,LV164,BP_Epithelial Cilium Movement Involved in Extracellular Fluid Movement (GO:0003351)
70,Testis,LV164,BP_Motile Cilium Assembly (GO:0044458)
71,Testis,LV123,BP_Reverse Cholesterol Transport (GO:0043691)
72,Thyroid,LV164,BP_Cilium Movement (GO:0003341)
73,Thyroid,LV164,BP_Axoneme Assembly (GO:0035082)
74,Thyroid,LV164,BP_Axonemal Dynein Complex Assembly (GO:0070286)
75,Thyroid,LV164,BP_Cilium-Dependent Cell Motility (GO:0060285)
76,Thyroid,LV164,BP_Epithelial Cilium Movement Involved in Extracellular Fluid Movement (GO:0003351)
77,Thyroid,LV164,BP_Motile Cilium Assembly (GO:0044458)
78,Thyroid,LV57,BP_Mitochondrial ATP Synthesis Coupled Electron Transport (GO:0042775)
79,Thyroid,LV57,BP_Aerobic Electron Transport Chain (GO:0019646)
80,Thyroid,LV57,BP_Aerobic Respiration (GO:0009060)
81,Whole Blood,LV60,BP_Mitochondrial ATP Synthesis Coupled Electron Transport (GO:0042775)
82,Whole Blood,LV60,BP_Aerobic Electron Transport Chain (GO:0019646)
83,Whole Blood,LV60,BP_Oxidative Phosphorylation (GO:0006119)
84,Whole Blood,LV60,BP_Proton Motive Force-Driven Mitochondrial ATP Synthesis (GO:0042776)
85,Whole Blood,LV60,BP_Proton Motive Force-Driven ATP Synthesis (GO:0015986)

In [95]:
# pct=50%  FDR<0.1  AUC>0.6  seen_lvs=True
_tpt = top_lvs_at_pct(50)
_df  = pathway_table(_tpt, fdr_thresh=0.1, auc_thresh=0.6, use_seen_lvs=True)
print(f'pct=50%  FDR<0.1  AUC>0.6  seen_lvs=True  ->  {len(_df)} rows, {_df["Tissue"].nunique()} tissues, {_df["LV"].nunique()} LVs')
_df[['Tissue', 'LV', 'pathway']]

pct=50%  FDR<0.1  AUC>0.6  seen_lvs=True  ->  134 rows, 22 tissues, 47 LVs

,Tissue,LV,pathway
0,Adipose - Subcutaneous,LV263,BP_Positive Regulation of Lipid Catabolic Process (GO:0050996)
1,Adipose - Subcutaneous,LV263,BP_Regulation of Fatty Acid Beta-Oxidation (GO:0031998)
2,Adipose - Subcutaneous,LV263,BP_Positive Regulation of Fatty Acid Oxidation (GO:0046321)
3,Adipose - Subcutaneous,LV145,BP_Skeletal Muscle Contraction (GO:0003009)
4,Adipose - Subcutaneous,LV145,BP_Embryonic Skeletal System Morphogenesis (GO:0048704)
5,Adipose - Subcutaneous,LV111,BP_Antigen Processing and Presentation of Endogenous Peptide Antigen (GO:0002483)
6,Adipose - Subcutaneous,LV111,BP_Ag Processing and Presentation of Endogenous Pep Ag via MHC Cls I via ER Pway (GO:0002484)
7,Adipose - Subcutaneous,LV111,BP_Antigen Processing and Presentation of Endogenous Peptide Antigen via MHC Class Ib (GO:0002476)
8,Adipose - Subcutaneous,LV111,"BP_Ag Processing and Presentation of Endogenous Pep Ag via MHC Cls I via ER Pway, TAP-ind (GO:0002486)"
9,Adipose - Subcutaneous,LV93,BP_Positive Regulation of Ruffle Assembly (GO:1900029)
10,Adipose - Visceral (Omentum),LV83,BP_Skeletal Muscle Contraction (GO:0003009)
11,Adipose - Visceral (Omentum),LV83,BP_Actin-Myosin Filament Sliding (GO:0033275)
12,Adipose - Visceral (Omentum),LV57,BP_Mitochondrial ATP Synthesis Coupled Electron Transport (GO:0042775)
13,Adipose - Visceral (Omentum),LV57,BP_Aerobic Electron Transport Chain (GO:0019646)
14,Adipose - Visceral (Omentum),LV57,BP_Aerobic Respiration (GO:0009060)
15,Adipose - Visceral (Omentum),LV57,"BP_Mitochondrial Electron Transport, Ubiquinol to Cytochrome C (GO:0006122)"
16,Adipose - Visceral (Omentum),LV106,BP_Endosome Transport via Multivesicular Body Sorting Pathway (GO:0032509)
17,Adipose - Visceral (Omentum),LV2,BP_Regulation of Calcium Ion-Dependent Exocytosis (GO:0017158)
18,Adipose - Visceral (Omentum),LV2,BP_Positive Regulation of Synaptic Vesicle Fusion to Presynaptic Active Zone Membrane (GO:0031632)
19,Adipose - Visceral (Omentum),LV2,BP_Positive Regulation of Calcium Ion-Dependent Exocytosis (GO:0045956)
20,Adipose - Visceral (Omentum),LV2,BP_Regulation of Short-Term Neuronal Synaptic Plasticity (GO:0048172)
21,Adrenal Gland,LV3,BP_Negative Regulation of T Cell Mediated Immunity (GO:0002710)
22,Adrenal Gland,LV183,BP_Positive Regulation of Synaptic Vesicle Fusion to Presynaptic Active Zone Membrane (GO:0031632)
23,Adrenal Gland,LV131,BP_DNA Strand Elongation Involved in DNA Replication (GO:0006271)
24,Adrenal Gland,LV131,BP_Mitotic DNA Replication (GO:1902969)
25,Adrenal Gland,LV131,BP_Regulation of DNA-templated DNA Replication (GO:0090329)
26,Artery - Aorta,LV40,BP_Quinone Biosynthetic Process (GO:1901663)
27,Artery - Aorta,LV81,BP_Epidermis Development (GO:0008544)
28,Artery - Aorta,LV81,BP_Intermediate Filament Organization (GO:0045109)
29,Artery - Aorta,LV81,BP_Peptide Cross-Linking (GO:0018149)
30,Artery - Aorta,LV81,BP_Negative Regulation of Vascular Permeability (GO:0043116)
31,Artery - Coronary,LV247,BP_Cotranslational Protein Targeting to Membrane (GO:0006613)
32,Artery - Coronary,LV99,BP_Dopaminergic Neuron Differentiation (GO:0071542)
33,Artery - Coronary,LV99,BP_Branching Involved in Blood Vessel Morphogenesis (GO:0001569)
34,Artery - Coronary,LV139,BP_Branching Involved in Blood Vessel Morphogenesis (GO:0001569)
35,Artery - Tibial,LV87,BP_Negative Regulation of calcineurin-NFAT Signaling Cascade (GO:0070885)
36,Cells - Cultured fibroblasts,LV91,BP_MHC Class II Protein Complex Assembly (GO:0002399)
37,Cells - Cultured fibroblasts,LV91,BP_Interleukin-10-Mediated Signaling Pathway (GO:0140105)
38,Cells - Cultured fibroblasts,LV91,BP_Peptide Antigen Assembly With MHC Class II Protein Complex (GO:0002503)
39,Cells - Cultured fibroblasts,LV91,BP_Antigen Processing and Presentation of Exogenous Peptide Antigen (GO:0002478)
40,Cells - EBV-transformed lymphocytes,LV123,BP_Reverse Cholesterol Transport (GO:0043691)
41,Cells - EBV-transformed lymphocytes,LV123,BP_Fatty Acid Beta-Oxidation (GO:0006635)
42,Cells - EBV-transformed lymphocytes,LV123,BP_Fatty Acid Beta-Oxidation Using acyl-CoA Oxidase (GO:0033540)
43,Cells - EBV-transformed lymphocytes,LV123,BP_Positive Regulation of Fatty Acid Metabolic Process (GO:0045923)
44,Cells - EBV-transformed lymphocytes,LV116,BP_Cilium Movement (GO:0003341)
45,Cells - EBV-transformed lymphocytes,LV116,BP_Axoneme Assembly (GO:0035082)
46,Cells - EBV-transformed lymphocytes,LV116,BP_Homologous Chromosome Pairing at Meiosis (GO:0007129)
47,Cells - EBV-transformed lymphocytes,LV244,BP_Mitochondrial Gene Expression (GO:0140053)
48,Cells - EBV-transformed lymphocytes,LV244,BP_Aerobic Electron Transport Chain (GO:0019646)
49,Cells - EBV-transformed lymphocytes,LV244,BP_Mitochondrial Cytochrome C Oxidase Assembly (GO:0033617)
50,Cells - EBV-transformed lymphocytes,LV244,"BP_Mitochondrial Electron Transport, Ubiquinol to Cytochrome C (GO:0006122)"
51,Cells - EBV-transformed lymphocytes,LV244,"BP_Mitochondrial Electron Transport, NADH to Ubiquinone (GO:0006120)"
52,Cells - EBV-transformed lymphocytes,LV244,"BP_Mitochondrial Electron Transport, Cytochrome C to Oxygen (GO:0006123)"
53,Cells - EBV-transformed lymphocytes,LV55,BP_Positive Regulation of Signaling Receptor Activity (GO:2000273)
54,Cells - EBV-transformed lymphocytes,LV55,BP_Basement Membrane Organization (GO:0071711)
55,Heart - Atrial Appendage,LV18,BP_Regulation of Neurotransmitter Receptor Activity (GO:0099601)
56,Heart - Atrial Appendage,LV18,BP_Regulation of AMPA Receptor Activity (GO:2000311)
57,Heart - Atrial Appendage,LV18,BP_Regulation of Short-Term Neuronal Synaptic Plasticity (GO:0048172)
58,Heart - Atrial Appendage,LV18,BP_Endosomal Lumen Acidification (GO:0048388)
59,Heart - Left Ventricle,LV161,BP_Establishment of Chromosome Localization (GO:0051303)
60,Heart - Left Ventricle,LV161,BP_Positive Regulation of G2/M Transition of Mitotic Cell Cycle (GO:0010971)
61,Heart - Left Ventricle,LV161,BP_DNA Strand Elongation Involved in DNA Replication (GO:0006271)
62,Heart - Left Ventricle,LV161,BP_DNA Strand Elongation (GO:0022616)
63,Heart - Left Ventricle,LV161,BP_Regulation of DNA-templated DNA Replication Initiation (GO:0030174)
64,Heart - Left Ventricle,LV161,BP_Positive Regulation of Mitotic Cell Cycle Spindle Assembly Checkpoint (GO:0090267)
65,Heart - Left Ventricle,LV161,BP_Positive Regulation of Cell Cycle G2/M Phase Transition (GO:1902751)
66,Heart - Left Ventricle,LV76,BP_Positive Regulation of Cell Morphogenesis (GO:0010770)
67,Liver,LV229,BP_Negative Regulation of Smooth Muscle Cell Differentiation (GO:0051151)
68,Liver,LV21,BP_Cellular Response to Zinc Ion (GO:0071294)
69,Liver,LV21,BP_Low-Density Lipoprotein Particle Remodeling (GO:0034374)
70,Liver,LV35,BP_Immune Response-Regulating Cell Surface Receptor Signaling Pathway (GO:0002768)
71,Liver,LV121,BP_Synaptic Vesicle Exocytosis (GO:0016079)
72,Liver,LV121,BP_Neurotransmitter Secretion (GO:0007269)
73,Lung,LV208,BP_Late Endosome to Vacuole Transport via Multivesicular Body Sorting Pathway (GO:0032511)
74,Lung,LV208,BP_Pexophagy (GO:0000425)
75,Minor Salivary Gland,LV250,BP_Dendritic Cell Differentiation (GO:0097028)
76,Minor Salivary Gland,LV250,BP_Dendritic Cell Chemotaxis (GO:0002407)
77,Muscle - Skeletal,LV160,BP_Cholesterol Biosynthetic Process (GO:0006695)
78,Muscle - Skeletal,LV160,BP_Sterol Biosynthetic Process (GO:0016126)
79,Muscle - Skeletal,LV160,BP_Secondary Alcohol Biosynthetic Process (GO:1902653)
80,Muscle - Skeletal,LV22,BP_Synaptic Membrane Adhesion (GO:0099560)
81,Nerve - Tibial,LV128,BP_Catecholamine Biosynthetic Process (GO:0042423)
82,Ovary,LV46,BP_Response to Glucocorticoid (GO:0051384)
83,Ovary,LV23,BP_Translation (GO:0006412)
84,Ovary,LV23,BP_Cytoplasmic Translation (GO:0002181)
85,Ovary,LV23,BP_Mitochondrial Translation (GO:0032543)
86,Ovary,LV23,BP_Cytoplasmic Translational Initiation (GO:0002183)
87,Ovary,LV23,BP_Ribosomal Small Subunit Assembly (GO:0000028)
88,Ovary,LV23,BP_U2-type Prespliceosome Assembly (GO:1903241)
89,Ovary,LV23,BP_Formation of Cytoplasmic Translation Initiation Complex (GO:0001732)
90,Ovary,LV236,BP_Epidermis Development (GO:0008544)
91,Ovary,LV236,BP_Skin Development (GO:0043588)
92,Ovary,LV236,BP_Intermediate Filament Organization (GO:0045109)
93,Ovary,LV236,BP_Keratinocyte Differentiation (GO:0030216)
94,Ovary,LV266,BP_Regulation of B Cell Receptor Signaling Pathway (GO:0050855)
95,Ovary,LV266,BP_B Cell Receptor Signaling Pathway (GO:0050853)
96,Ovary,LV266,BP_Peptide Antigen Assembly With MHC Class II Protein Complex (GO:0002503)
97,Ovary,LV266,BP_MHC Class II Protein Complex Assembly (GO:0002399)
98,Ovary,LV266,BP_Mature B Cell Differentiation Involved in Immune Response (GO:0002313)
99,Ovary,LV110,BP_Eosinophil Chemotaxis (GO:0048245)
100,Ovary,LV110,BP_Eosinophil Migration (GO:0072677)
101,Ovary,LV110,BP_Reverse Cholesterol Transport (GO:0043691)
102,Ovary,LV110,BP_Low-Density Lipoprotein Particle Remodeling (GO:0034374)
103,Ovary,LV110,BP_High-Density Lipoprotein Particle Remodeling (GO:0034375)
104,Pancreas,LV60,BP_Mitochondrial ATP Synthesis Coupled Electron Transport (GO:0042775)
105,Pancreas,LV60,BP_Aerobic Electron Transport Chain (GO:0019646)
106,Pancreas,LV60,BP_Oxidative Phosphorylation (GO:0006119)
107,Pancreas,LV60,BP_Proton Motive Force-Driven Mitochondrial ATP Synthesis (GO:0042776)
108,Pancreas,LV60,BP_Proton Motive Force-Driven ATP Synthesis (GO:0015986)
109,Pancreas,LV60,"BP_Mitochondrial Electron Transport, Ubiquinol to Cytochrome C (GO:0006122)"
110,Pancreas,LV60,BP_Mitochondrial RNA Processing (GO:0000963)
111,Pancreas,LV60,BP_Respiratory Electron Transport Chain (GO:0022904)
112,Pituitary,LV164,BP_Cilium Movement (GO:0003341)
113,Pituitary,LV164,BP_Axoneme Assembly (GO:0035082)
114,Pituitary,LV164,BP_Axonemal Dynein Complex Assembly (GO:0070286)
115,Pituitary,LV164,BP_Cilium-Dependent Cell Motility (GO:0060285)
116,Pituitary,LV164,BP_Epithelial Cilium Movement Involved in Extracellular Fluid Movement (GO:0003351)
117,Pituitary,LV164,BP_Motile Cilium Assembly (GO:0044458)
118,Prostate,LV38,BP_Xenobiotic Transport (GO:0042908)
119,Spleen,LV51,BP_Axoneme Assembly (GO:0035082)
120,Spleen,LV51,BP_Cilium Movement (GO:0003341)
121,Spleen,LV51,BP_Cilium-Dependent Cell Motility (GO:0060285)
122,Spleen,LV51,BP_Axonemal Dynein Complex Assembly (GO:0070286)
123,Spleen,LV51,BP_Intraciliary Anterograde Transport (GO:0035720)
124,Spleen,LV51,BP_Intraciliary Retrograde Transport (GO:0035721)
125,Spleen,LV51,BP_Motile Cilium Assembly (GO:0044458)
126,Testis,LV69,BP_Male Gamete Generation (GO:0048232)
127,Testis,LV69,BP_Transposable Element Silencing by Heterochromatin Formation (GO:0141005)
128,Testis,LV69,BP_piRNA Processing (GO:0034587)
129,Testis,LV269,BP_Regulation of Cardiac Muscle Cell Apoptotic Process (GO:0010665)
130,Whole Blood,LV238,BP_Calcium-Dependent Activation of Synaptic Vesicle Fusion (GO:0099502)
131,Whole Blood,LV238,BP_Positive Regulation of Calcium Ion-Dependent Exocytosis (GO:0045956)
132,Whole Blood,LV238,BP_Positive Regulation of Synaptic Vesicle Fusion to Presynaptic Active Zone Membrane (GO:0031632)
133,Whole Blood,LV155,BP_Tertiary Alcohol Metabolic Process (GO:1902644)

In [96]:
# pct=50%  FDR<0.1  AUC>0.6  seen_lvs=False
_tpt = top_lvs_at_pct(50)
_df  = pathway_table(_tpt, fdr_thresh=0.1, auc_thresh=0.6, use_seen_lvs=False)
print(f'pct=50%  FDR<0.1  AUC>0.6  seen_lvs=False  ->  {len(_df)} rows, {_df["Tissue"].nunique()} tissues, {_df["LV"].nunique()} LVs')
_df[['Tissue', 'LV', 'pathway']]

pct=50%  FDR<0.1  AUC>0.6  seen_lvs=False  ->  256 rows, 25 tissues, 47 LVs

,Tissue,LV,pathway
0,Adipose - Subcutaneous,LV263,BP_Positive Regulation of Lipid Catabolic Process (GO:0050996)
1,Adipose - Subcutaneous,LV263,BP_Regulation of Fatty Acid Beta-Oxidation (GO:0031998)
2,Adipose - Subcutaneous,LV263,BP_Positive Regulation of Fatty Acid Oxidation (GO:0046321)
3,Adipose - Subcutaneous,LV145,BP_Skeletal Muscle Contraction (GO:0003009)
4,Adipose - Subcutaneous,LV145,BP_Embryonic Skeletal System Morphogenesis (GO:0048704)
5,Adipose - Subcutaneous,LV111,BP_Antigen Processing and Presentation of Endogenous Peptide Antigen (GO:0002483)
6,Adipose - Subcutaneous,LV111,BP_Ag Processing and Presentation of Endogenous Pep Ag via MHC Cls I via ER Pway (GO:0002484)
7,Adipose - Subcutaneous,LV111,BP_Antigen Processing and Presentation of Endogenous Peptide Antigen via MHC Class Ib (GO:0002476)
8,Adipose - Subcutaneous,LV111,"BP_Ag Processing and Presentation of Endogenous Pep Ag via MHC Cls I via ER Pway, TAP-ind (GO:0002486)"
9,Adipose - Subcutaneous,LV93,BP_Positive Regulation of Ruffle Assembly (GO:1900029)
10,Adipose - Visceral (Omentum),LV263,BP_Positive Regulation of Lipid Catabolic Process (GO:0050996)
11,Adipose - Visceral (Omentum),LV263,BP_Regulation of Fatty Acid Beta-Oxidation (GO:0031998)
12,Adipose - Visceral (Omentum),LV263,BP_Positive Regulation of Fatty Acid Oxidation (GO:0046321)
13,Adipose - Visceral (Omentum),LV83,BP_Skeletal Muscle Contraction (GO:0003009)
14,Adipose - Visceral (Omentum),LV83,BP_Actin-Myosin Filament Sliding (GO:0033275)
15,Adipose - Visceral (Omentum),LV57,BP_Mitochondrial ATP Synthesis Coupled Electron Transport (GO:0042775)
16,Adipose - Visceral (Omentum),LV57,BP_Aerobic Electron Transport Chain (GO:0019646)
17,Adipose - Visceral (Omentum),LV57,BP_Aerobic Respiration (GO:0009060)
18,Adipose - Visceral (Omentum),LV57,"BP_Mitochondrial Electron Transport, Ubiquinol to Cytochrome C (GO:0006122)"
19,Adipose - Visceral (Omentum),LV106,BP_Endosome Transport via Multivesicular Body Sorting Pathway (GO:0032509)
20,Adipose - Visceral (Omentum),LV2,BP_Regulation of Calcium Ion-Dependent Exocytosis (GO:0017158)
21,Adipose - Visceral (Omentum),LV2,BP_Positive Regulation of Synaptic Vesicle Fusion to Presynaptic Active Zone Membrane (GO:0031632)
22,Adipose - Visceral (Omentum),LV2,BP_Positive Regulation of Calcium Ion-Dependent Exocytosis (GO:0045956)
23,Adipose - Visceral (Omentum),LV2,BP_Regulation of Short-Term Neuronal Synaptic Plasticity (GO:0048172)
24,Adrenal Gland,LV83,BP_Skeletal Muscle Contraction (GO:0003009)
25,Adrenal Gland,LV83,BP_Actin-Myosin Filament Sliding (GO:0033275)
26,Adrenal Gland,LV3,BP_Negative Regulation of T Cell Mediated Immunity (GO:0002710)
27,Adrenal Gland,LV183,BP_Positive Regulation of Synaptic Vesicle Fusion to Presynaptic Active Zone Membrane (GO:0031632)
28,Adrenal Gland,LV131,BP_DNA Strand Elongation Involved in DNA Replication (GO:0006271)
29,Adrenal Gland,LV131,BP_Mitotic DNA Replication (GO:1902969)
30,Adrenal Gland,LV131,BP_Regulation of DNA-templated DNA Replication (GO:0090329)
31,Artery - Aorta,LV145,BP_Skeletal Muscle Contraction (GO:0003009)
32,Artery - Aorta,LV145,BP_Embryonic Skeletal System Morphogenesis (GO:0048704)
33,Artery - Aorta,LV40,BP_Quinone Biosynthetic Process (GO:1901663)
34,Artery - Aorta,LV81,BP_Epidermis Development (GO:0008544)
35,Artery - Aorta,LV81,BP_Intermediate Filament Organization (GO:0045109)
36,Artery - Aorta,LV81,BP_Peptide Cross-Linking (GO:0018149)
37,Artery - Aorta,LV81,BP_Negative Regulation of Vascular Permeability (GO:0043116)
38,Artery - Aorta,LV131,BP_DNA Strand Elongation Involved in DNA Replication (GO:0006271)
39,Artery - Aorta,LV131,BP_Mitotic DNA Replication (GO:1902969)
40,Artery - Aorta,LV131,BP_Regulation of DNA-templated DNA Replication (GO:0090329)
41,Artery - Coronary,LV40,BP_Quinone Biosynthetic Process (GO:1901663)
42,Artery - Coronary,LV247,BP_Cotranslational Protein Targeting to Membrane (GO:0006613)
43,Artery - Coronary,LV99,BP_Dopaminergic Neuron Differentiation (GO:0071542)
44,Artery - Coronary,LV99,BP_Branching Involved in Blood Vessel Morphogenesis (GO:0001569)
45,Artery - Coronary,LV106,BP_Endosome Transport via Multivesicular Body Sorting Pathway (GO:0032509)
46,Artery - Coronary,LV131,BP_DNA Strand Elongation Involved in DNA Replication (GO:0006271)
47,Artery - Coronary,LV131,BP_Mitotic DNA Replication (GO:1902969)
48,Artery - Coronary,LV131,BP_Regulation of DNA-templated DNA Replication (GO:0090329)
49,Artery - Coronary,LV139,BP_Branching Involved in Blood Vessel Morphogenesis (GO:0001569)
50,Artery - Tibial,LV81,BP_Epidermis Development (GO:0008544)
51,Artery - Tibial,LV81,BP_Intermediate Filament Organization (GO:0045109)
52,Artery - Tibial,LV81,BP_Peptide Cross-Linking (GO:0018149)
53,Artery - Tibial,LV81,BP_Negative Regulation of Vascular Permeability (GO:0043116)
54,Artery - Tibial,LV139,BP_Branching Involved in Blood Vessel Morphogenesis (GO:0001569)
55,Artery - Tibial,LV87,BP_Negative Regulation of calcineurin-NFAT Signaling Cascade (GO:0070885)
56,Artery - Tibial,LV93,BP_Positive Regulation of Ruffle Assembly (GO:1900029)
57,Cells - Cultured fibroblasts,LV111,BP_Antigen Processing and Presentation of Endogenous Peptide Antigen (GO:0002483)
58,Cells - Cultured fibroblasts,LV111,BP_Ag Processing and Presentation of Endogenous Pep Ag via MHC Cls I via ER Pway (GO:0002484)
59,Cells - Cultured fibroblasts,LV111,BP_Antigen Processing and Presentation of Endogenous Peptide Antigen via MHC Class Ib (GO:0002476)
60,Cells - Cultured fibroblasts,LV111,"BP_Ag Processing and Presentation of Endogenous Pep Ag via MHC Cls I via ER Pway, TAP-ind (GO:0002486)"
61,Cells - Cultured fibroblasts,LV91,BP_MHC Class II Protein Complex Assembly (GO:0002399)
62,Cells - Cultured fibroblasts,LV91,BP_Interleukin-10-Mediated Signaling Pathway (GO:0140105)
63,Cells - Cultured fibroblasts,LV91,BP_Peptide Antigen Assembly With MHC Class II Protein Complex (GO:0002503)
64,Cells - Cultured fibroblasts,LV91,BP_Antigen Processing and Presentation of Exogenous Peptide Antigen (GO:0002478)
65,Cells - EBV-transformed lymphocytes,LV123,BP_Reverse Cholesterol Transport (GO:0043691)
66,Cells - EBV-transformed lymphocytes,LV123,BP_Fatty Acid Beta-Oxidation (GO:0006635)
67,Cells - EBV-transformed lymphocytes,LV123,BP_Fatty Acid Beta-Oxidation Using acyl-CoA Oxidase (GO:0033540)
68,Cells - EBV-transformed lymphocytes,LV123,BP_Positive Regulation of Fatty Acid Metabolic Process (GO:0045923)
69,Cells - EBV-transformed lymphocytes,LV116,BP_Cilium Movement (GO:0003341)
70,Cells - EBV-transformed lymphocytes,LV116,BP_Axoneme Assembly (GO:0035082)
71,Cells - EBV-transformed lymphocytes,LV116,BP_Homologous Chromosome Pairing at Meiosis (GO:0007129)
72,Cells - EBV-transformed lymphocytes,LV244,BP_Mitochondrial Gene Expression (GO:0140053)
73,Cells - EBV-transformed lymphocytes,LV244,BP_Aerobic Electron Transport Chain (GO:0019646)
74,Cells - EBV-transformed lymphocytes,LV244,BP_Mitochondrial Cytochrome C Oxidase Assembly (GO:0033617)
75,Cells - EBV-transformed lymphocytes,LV244,"BP_Mitochondrial Electron Transport, Ubiquinol to Cytochrome C (GO:0006122)"
76,Cells - EBV-transformed lymphocytes,LV244,"BP_Mitochondrial Electron Transport, NADH to Ubiquinone (GO:0006120)"
77,Cells - EBV-transformed lymphocytes,LV244,"BP_Mitochondrial Electron Transport, Cytochrome C to Oxygen (GO:0006123)"
78,Cells - EBV-transformed lymphocytes,LV145,BP_Skeletal Muscle Contraction (GO:0003009)
79,Cells - EBV-transformed lymphocytes,LV145,BP_Embryonic Skeletal System Morphogenesis (GO:0048704)
80,Cells - EBV-transformed lymphocytes,LV55,BP_Positive Regulation of Signaling Receptor Activity (GO:2000273)
81,Cells - EBV-transformed lymphocytes,LV55,BP_Basement Membrane Organization (GO:0071711)
82,Esophagus - Mucosa,LV81,BP_Epidermis Development (GO:0008544)
83,Esophagus - Mucosa,LV81,BP_Intermediate Filament Organization (GO:0045109)
84,Esophagus - Mucosa,LV81,BP_Peptide Cross-Linking (GO:0018149)
85,Esophagus - Mucosa,LV81,BP_Negative Regulation of Vascular Permeability (GO:0043116)
86,Heart - Atrial Appendage,LV139,BP_Branching Involved in Blood Vessel Morphogenesis (GO:0001569)
87,Heart - Atrial Appendage,LV18,BP_Regulation of Neurotransmitter Receptor Activity (GO:0099601)
88,Heart - Atrial Appendage,LV18,BP_Regulation of AMPA Receptor Activity (GO:2000311)
89,Heart - Atrial Appendage,LV18,BP_Regulation of Short-Term Neuronal Synaptic Plasticity (GO:0048172)
90,Heart - Atrial Appendage,LV18,BP_Endosomal Lumen Acidification (GO:0048388)
91,Heart - Atrial Appendage,LV145,BP_Skeletal Muscle Contraction (GO:0003009)
92,Heart - Atrial Appendage,LV145,BP_Embryonic Skeletal System Morphogenesis (GO:0048704)
93,Heart - Atrial Appendage,LV131,BP_DNA Strand Elongation Involved in DNA Replication (GO:0006271)
94,Heart - Atrial Appendage,LV131,BP_Mitotic DNA Replication (GO:1902969)
95,Heart - Atrial Appendage,LV131,BP_Regulation of DNA-templated DNA Replication (GO:0090329)
96,Heart - Left Ventricle,LV161,BP_Establishment of Chromosome Localization (GO:0051303)
97,Heart - Left Ventricle,LV161,BP_Positive Regulation of G2/M Transition of Mitotic Cell Cycle (GO:0010971)
98,Heart - Left Ventricle,LV161,BP_DNA Strand Elongation Involved in DNA Replication (GO:0006271)
99,Heart - Left Ventricle,LV161,BP_DNA Strand Elongation (GO:0022616)
100,Heart - Left Ventricle,LV161,BP_Regulation of DNA-templated DNA Replication Initiation (GO:0030174)
101,Heart - Left Ventricle,LV161,BP_Positive Regulation of Mitotic Cell Cycle Spindle Assembly Checkpoint (GO:0090267)
102,Heart - Left Ventricle,LV161,BP_Positive Regulation of Cell Cycle G2/M Phase Transition (GO:1902751)
103,Heart - Left Ventricle,LV76,BP_Positive Regulation of Cell Morphogenesis (GO:0010770)
104,Heart - Left Ventricle,LV81,BP_Epidermis Development (GO:0008544)
105,Heart - Left Ventricle,LV81,BP_Intermediate Filament Organization (GO:0045109)
106,Heart - Left Ventricle,LV81,BP_Peptide Cross-Linking (GO:0018149)
107,Heart - Left Ventricle,LV81,BP_Negative Regulation of Vascular Permeability (GO:0043116)
108,Liver,LV229,BP_Negative Regulation of Smooth Muscle Cell Differentiation (GO:0051151)
109,Liver,LV21,BP_Cellular Response to Zinc Ion (GO:0071294)
110,Liver,LV21,BP_Low-Density Lipoprotein Particle Remodeling (GO:0034374)
111,Liver,LV123,BP_Reverse Cholesterol Transport (GO:0043691)
112,Liver,LV123,BP_Fatty Acid Beta-Oxidation (GO:0006635)
113,Liver,LV123,BP_Fatty Acid Beta-Oxidation Using acyl-CoA Oxidase (GO:0033540)
114,Liver,LV123,BP_Positive Regulation of Fatty Acid Metabolic Process (GO:0045923)
115,Liver,LV35,BP_Immune Response-Regulating Cell Surface Receptor Signaling Pathway (GO:0002768)
116,Liver,LV116,BP_Cilium Movement (GO:0003341)
117,Liver,LV116,BP_Axoneme Assembly (GO:0035082)
118,Liver,LV116,BP_Homologous Chromosome Pairing at Meiosis (GO:0007129)
119,Liver,LV121,BP_Synaptic Vesicle Exocytosis (GO:0016079)
120,Liver,LV121,BP_Neurotransmitter Secretion (GO:0007269)
121,Lung,LV208,BP_Late Endosome to Vacuole Transport via Multivesicular Body Sorting Pathway (GO:0032511)
122,Lung,LV208,BP_Pexophagy (GO:0000425)
123,Minor Salivary Gland,LV250,BP_Dendritic Cell Differentiation (GO:0097028)
124,Minor Salivary Gland,LV250,BP_Dendritic Cell Chemotaxis (GO:0002407)
125,Minor Salivary Gland,LV99,BP_Dopaminergic Neuron Differentiation (GO:0071542)
126,Minor Salivary Gland,LV99,BP_Branching Involved in Blood Vessel Morphogenesis (GO:0001569)
127,Minor Salivary Gland,LV93,BP_Positive Regulation of Ruffle Assembly (GO:1900029)
128,Muscle - Skeletal,LV160,BP_Cholesterol Biosynthetic Process (GO:0006695)
129,Muscle - Skeletal,LV160,BP_Sterol Biosynthetic Process (GO:0016126)
130,Muscle - Skeletal,LV160,BP_Secondary Alcohol Biosynthetic Process (GO:1902653)
131,Muscle - Skeletal,LV121,BP_Synaptic Vesicle Exocytosis (GO:0016079)
132,Muscle - Skeletal,LV121,BP_Neurotransmitter Secretion (GO:0007269)
133,Muscle - Skeletal,LV76,BP_Positive Regulation of Cell Morphogenesis (GO:0010770)
134,Muscle - Skeletal,LV22,BP_Synaptic Membrane Adhesion (GO:0099560)
135,Nerve - Tibial,LV128,BP_Catecholamine Biosynthetic Process (GO:0042423)
136,Nerve - Tibial,LV183,BP_Positive Regulation of Synaptic Vesicle Fusion to Presynaptic Active Zone Membrane (GO:0031632)
137,Ovary,LV46,BP_Response to Glucocorticoid (GO:0051384)
138,Ovary,LV23,BP_Translation (GO:0006412)
139,Ovary,LV23,BP_Cytoplasmic Translation (GO:0002181)
140,Ovary,LV23,BP_Mitochondrial Translation (GO:0032543)
141,Ovary,LV23,BP_Cytoplasmic Translational Initiation (GO:0002183)
142,Ovary,LV23,BP_Ribosomal Small Subunit Assembly (GO:0000028)
143,Ovary,LV23,BP_U2-type Prespliceosome Assembly (GO:1903241)
144,Ovary,LV23,BP_Formation of Cytoplasmic Translation Initiation Complex (GO:0001732)
145,Ovary,LV3,BP_Negative Regulation of T Cell Mediated Immunity (GO:0002710)
146,Ovary,LV236,BP_Epidermis Development (GO:0008544)
147,Ovary,LV236,BP_Skin Development (GO:0043588)
148,Ovary,LV236,BP_Intermediate Filament Organization (GO:0045109)
149,Ovary,LV236,BP_Keratinocyte Differentiation (GO:0030216)
150,Ovary,LV266,BP_Regulation of B Cell Receptor Signaling Pathway (GO:0050855)
151,Ovary,LV266,BP_B Cell Receptor Signaling Pathway (GO:0050853)
152,Ovary,LV266,BP_Peptide Antigen Assembly With MHC Class II Protein Complex (GO:0002503)
153,Ovary,LV266,BP_MHC Class II Protein Complex Assembly (GO:0002399)
154,Ovary,LV266,BP_Mature B Cell Differentiation Involved in Immune Response (GO:0002313)
155,Ovary,LV110,BP_Eosinophil Chemotaxis (GO:0048245)
156,Ovary,LV110,BP_Eosinophil Migration (GO:0072677)
157,Ovary,LV110,BP_Reverse Cholesterol Transport (GO:0043691)
158,Ovary,LV110,BP_Low-Density Lipoprotein Particle Remodeling (GO:0034374)
159,Ovary,LV110,BP_High-Density Lipoprotein Particle Remodeling (GO:0034375)
160,Pancreas,LV229,BP_Negative Regulation of Smooth Muscle Cell Differentiation (GO:0051151)
161,Pancreas,LV60,BP_Mitochondrial ATP Synthesis Coupled Electron Transport (GO:0042775)
162,Pancreas,LV60,BP_Aerobic Electron Transport Chain (GO:0019646)
163,Pancreas,LV60,BP_Oxidative Phosphorylation (GO:0006119)
164,Pancreas,LV60,BP_Proton Motive Force-Driven Mitochondrial ATP Synthesis (GO:0042776)
165,Pancreas,LV60,BP_Proton Motive Force-Driven ATP Synthesis (GO:0015986)
166,Pancreas,LV60,"BP_Mitochondrial Electron Transport, Ubiquinol to Cytochrome C (GO:0006122)"
167,Pancreas,LV60,BP_Mitochondrial RNA Processing (GO:0000963)
168,Pancreas,LV60,BP_Respiratory Electron Transport Chain (GO:0022904)
169,Pituitary,LV21,BP_Cellular Response to Zinc Ion (GO:0071294)
170,Pituitary,LV21,BP_Low-Density Lipoprotein Particle Remodeling (GO:0034374)
171,Pituitary,LV145,BP_Skeletal Muscle Contraction (GO:0003009)
172,Pituitary,LV145,BP_Embryonic Skeletal System Morphogenesis (GO:0048704)
173,Pituitary,LV164,BP_Cilium Movement (GO:0003341)
174,Pituitary,LV164,BP_Axoneme Assembly (GO:0035082)
175,Pituitary,LV164,BP_Axonemal Dynein Complex Assembly (GO:0070286)
176,Pituitary,LV164,BP_Cilium-Dependent Cell Motility (GO:0060285)
177,Pituitary,LV164,BP_Epithelial Cilium Movement Involved in Extracellular Fluid Movement (GO:0003351)
178,Pituitary,LV164,BP_Motile Cilium Assembly (GO:0044458)
179,Pituitary,LV2,BP_Regulation of Calcium Ion-Dependent Exocytosis (GO:0017158)
180,Pituitary,LV2,BP_Positive Regulation of Synaptic Vesicle Fusion to Presynaptic Active Zone Membrane (GO:0031632)
181,Pituitary,LV2,BP_Positive Regulation of Calcium Ion-Dependent Exocytosis (GO:0045956)
182,Pituitary,LV2,BP_Regulation of Short-Term Neuronal Synaptic Plasticity (GO:0048172)
183,Prostate,LV83,BP_Skeletal Muscle Contraction (GO:0003009)
184,Prostate,LV83,BP_Actin-Myosin Filament Sliding (GO:0033275)
185,Prostate,LV38,BP_Xenobiotic Transport (GO:0042908)
186,Prostate,LV3,BP_Negative Regulation of T Cell Mediated Immunity (GO:0002710)
187,Spleen,LV123,BP_Reverse Cholesterol Transport (GO:0043691)
188,Spleen,LV123,BP_Fatty Acid Beta-Oxidation (GO:0006635)
189,Spleen,LV123,BP_Fatty Acid Beta-Oxidation Using acyl-CoA Oxidase (GO:0033540)
190,Spleen,LV123,BP_Positive Regulation of Fatty Acid Metabolic Process (GO:0045923)
191,Spleen,LV55,BP_Positive Regulation of Signaling Receptor Activity (GO:2000273)
192,Spleen,LV55,BP_Basement Membrane Organization (GO:0071711)
193,Spleen,LV51,BP_Axoneme Assembly (GO:0035082)
194,Spleen,LV51,BP_Cilium Movement (GO:0003341)
195,Spleen,LV51,BP_Cilium-Dependent Cell Motility (GO:0060285)
196,Spleen,LV51,BP_Axonemal Dynein Complex Assembly (GO:0070286)
197,Spleen,LV51,BP_Intraciliary Anterograde Transport (GO:0035720)
198,Spleen,LV51,BP_Intraciliary Retrograde Transport (GO:0035721)
199,Spleen,LV51,BP_Motile Cilium Assembly (GO:0044458)
200,Spleen,LV250,BP_Dendritic Cell Differentiation (GO:0097028)
201,Spleen,LV250,BP_Dendritic Cell Chemotaxis (GO:0002407)
202,Spleen,LV81,BP_Epidermis Development (GO:0008544)
203,Spleen,LV81,BP_Intermediate Filament Organization (GO:0045109)
204,Spleen,LV81,BP_Peptide Cross-Linking (GO:0018149)
205,Spleen,LV81,BP_Negative Regulation of Vascular Permeability (GO:0043116)
206,Spleen,LV183,BP_Positive Regulation of Synaptic Vesicle Fusion to Presynaptic Active Zone Membrane (GO:0031632)
207,Spleen,LV266,BP_Regulation of B Cell Receptor Signaling Pathway (GO:0050855)
208,Spleen,LV266,BP_B Cell Receptor Signaling Pathway (GO:0050853)
209,Spleen,LV266,BP_Peptide Antigen Assembly With MHC Class II Protein Complex (GO:0002503)
210,Spleen,LV266,BP_MHC Class II Protein Complex Assembly (GO:0002399)
211,Spleen,LV266,BP_Mature B Cell Differentiation Involved in Immune Response (GO:0002313)
212,Stomach,LV208,BP_Late Endosome to Vacuole Transport via Multivesicular Body Sorting Pathway (GO:0032511)
213,Stomach,LV208,BP_Pexophagy (GO:0000425)
214,Testis,LV69,BP_Male Gamete Generation (GO:0048232)
215,Testis,LV69,BP_Transposable Element Silencing by Heterochromatin Formation (GO:0141005)
216,Testis,LV69,BP_piRNA Processing (GO:0034587)
217,Testis,LV164,BP_Cilium Movement (GO:0003341)
218,Testis,LV164,BP_Axoneme Assembly (GO:0035082)
219,Testis,LV164,BP_Axonemal Dynein Complex Assembly (GO:0070286)
220,Testis,LV164,BP_Cilium-Dependent Cell Motility (GO:0060285)
221,Testis,LV164,BP_Epithelial Cilium Movement Involved in Extracellular Fluid Movement (GO:0003351)
222,Testis,LV164,BP_Motile Cilium Assembly (GO:0044458)
223,Testis,LV123,BP_Reverse Cholesterol Transport (GO:0043691)
224,Testis,LV123,BP_Fatty Acid Beta-Oxidation (GO:0006635)
225,Testis,LV123,BP_Fatty Acid Beta-Oxidation Using acyl-CoA Oxidase (GO:0033540)
226,Testis,LV123,BP_Positive Regulation of Fatty Acid Metabolic Process (GO:0045923)
227,Testis,LV266,BP_Regulation of B Cell Receptor Signaling Pathway (GO:0050855)
228,Testis,LV266,BP_B Cell Receptor Signaling Pathway (GO:0050853)
229,Testis,LV266,BP_Peptide Antigen Assembly With MHC Class II Protein Complex (GO:0002503)
230,Testis,LV266,BP_MHC Class II Protein Complex Assembly (GO:0002399)
231,Testis,LV266,BP_Mature B Cell Differentiation Involved in Immune Response (GO:0002313)
232,Testis,LV269,BP_Regulation of Cardiac Muscle Cell Apoptotic Process (GO:0010665)
233,Thyroid,LV164,BP_Cilium Movement (GO:0003341)
234,Thyroid,LV164,BP_Axoneme Assembly (GO:0035082)
235,Thyroid,LV164,BP_Axonemal Dynein Complex Assembly (GO:0070286)
236,Thyroid,LV164,BP_Cilium-Dependent Cell Motility (GO:0060285)
237,Thyroid,LV164,BP_Epithelial Cilium Movement Involved in Extracellular Fluid Movement (GO:0003351)
238,Thyroid,LV164,BP_Motile Cilium Assembly (GO:0044458)
239,Thyroid,LV57,BP_Mitochondrial ATP Synthesis Coupled Electron Transport (GO:0042775)
240,Thyroid,LV57,BP_Aerobic Electron Transport Chain (GO:0019646)
241,Thyroid,LV57,BP_Aerobic Respiration (GO:0009060)
242,Thyroid,LV57,"BP_Mitochondrial Electron Transport, Ubiquinol to Cytochrome C (GO:0006122)"
243,Whole Blood,LV238,BP_Calcium-Dependent Activation of Synaptic Vesicle Fusion (GO:0099502)
244,Whole Blood,LV238,BP_Positive Regulation of Calcium Ion-Dependent Exocytosis (GO:0045956)