In [1]:

######## snakemake preamble start (automatically inserted, do not edit) ########
library(methods)
Snakemake <- setClass(
    "Snakemake",
    slots = c(
        input = "list",
        output = "list",
        params = "list",
        wildcards = "list",
        threads = "numeric",
        log = "list",
        resources = "list",
        config = "list",
        rule = "character",
        bench_iteration = "numeric",
        scriptdir = "character",
        source = "function"
    )
)
snakemake <- Snakemake(
    input = list('output/03_model_biology/01_gtex/01_LV_importance_rf_true_labels/gtex_feature_importance_true_labels_binary_shap', '/home/msubirana/Documents/pivlab/clamp-analyses/nbs/03_model_biology/01_gtex/03_global_alignment.ipynb', "shap_dir" = 'output/03_model_biology/01_gtex/01_LV_importance_rf_true_labels/gtex_feature_importance_true_labels_binary_shap', "notebook" = '/home/msubirana/Documents/pivlab/clamp-analyses/nbs/03_model_biology/01_gtex/03_global_alignment.ipynb'),
    output = list('output/03_model_biology/01_gtex/07_global_alignment_rf_true_labels/gtex_global_alignment_grouped_summary.csv', 'output/03_model_biology/01_gtex/07_global_alignment_rf_true_labels/cumulative20/gtex_global_alignment_summary.csv', 'output/03_model_biology/01_gtex/07_global_alignment_rf_true_labels/notebook.complete', "grouped_summary" = 'output/03_model_biology/01_gtex/07_global_alignment_rf_true_labels/gtex_global_alignment_grouped_summary.csv', "subtissue_summary" = 'output/03_model_biology/01_gtex/07_global_alignment_rf_true_labels/cumulative20/gtex_global_alignment_summary.csv', "complete" = 'output/03_model_biology/01_gtex/07_global_alignment_rf_true_labels/notebook.complete'),
    params = list(),
    wildcards = list(),
    threads = 1,
    log = list('/home/msubirana/Documents/pivlab/clamp-analyses/nbs/03_model_biology/01_gtex/03_global_alignment.executed.ipynb', "notebook" = '/home/msubirana/Documents/pivlab/clamp-analyses/nbs/03_model_biology/01_gtex/03_global_alignment.executed.ipynb'),
    resources = list('tmpdir', "tmpdir" = '/tmp'),
    config = list("datasets" = list("Brain_Mathys2023" = list("build_pseudobulk" = FALSE, "pseudobulk_dir" = 'data/pseudobulk/Brain_Mathys2023', "kind" = 'matrix_market', "raw" = 'data/pseudobulk/raw/Brain_Mathys2023/ad430_matrix.mtx.gz', "features" = 'data/pseudobulk/raw/Brain_Mathys2023/ad430_features.tsv.gz', "barcodes" = 'data/pseudobulk/raw/Brain_Mathys2023/ad430_barcodes.tsv.gz', "metadata" = 'data/pseudobulk/raw/Brain_Mathys2023/meta.tsv', "cell_id_col" = 'cellName', "sample_col" = 'Individual', "sample_transform" = 'identity', "truth_v0_col" = 'Major_Cell_Type', "truth_v1_col" = 'Cell_Type', "raw_cell_type_col" = 'Major_Cell_Type', "projection_label_col" = 'Major_Cell_Type', "cohort_manifest" = 'data/pseudobulk/Brain_Mathys2023/patient_info.csv'), "Brain_Xiong2023" = list("build_pseudobulk" = FALSE, "pseudobulk_dir" = 'data/pseudobulk/Brain_Xiong2023', "kind" = 'matrix_market', "raw" = 'data/pseudobulk/raw/Brain_Xiong2023/matrix.mtx.gz', "features" = 'data/pseudobulk/raw/Brain_Xiong2023/features.tsv.gz', "barcodes" = 'data/pseudobulk/raw/Brain_Xiong2023/barcodes.tsv.gz', "metadata" = 'data/pseudobulk/raw/Brain_Xiong2023/meta.tsv', "cell_id_col" = 'cellId', "sample_col" = 'Individual', "sample_transform" = 'hyphen_to_underscore', "truth_v0_col" = 'Celltype', "truth_v1_col" = 'Subcelltype', "raw_cell_type_col" = 'Celltype', "projection_label_col" = 'Celltype', "cohort_manifest" = 'data/pseudobulk/Brain_Xiong2023/patient_info.csv'), "Heart_Datar2026" = list("build_pseudobulk" = TRUE, "kind" = 'h5ad', "raw" = 'data/pseudobulk/Heart_Datar2026/HeartMap_V1.0_raw_counts.h5ad', "matrix" = 'X', "sample_col" = 'donor_id', "sample_transform" = 'identity', "truth_v0_col" = 'cell_type__ontology_label', "raw_cell_type_col" = 'cell_type__ontology_label', "projection_label_col" = 'cell_type__ontology_label', "min_cells" = 400, "exclude" = list("cell_type__ontology_label" = c('cell')), "truth_v0_map" = list("adipocyte" = 'Adipocyte', "regular atrial cardiac myocyte" = 'AtrialCM', "endocardial cell" = 'Endocardial', "cardiac endothelial cell" = 'Endothelial', "mesothelial cell of epicardium" = 'Epicardial', "fibroblast of cardiac tissue" = 'Fibroblast', "endothelial cell of lymphatic vessel" = 'LymphaticEndothelial', "lymphocyte" = 'Lymphocyte', "macrophage" = 'Macrophage', "mast cell" = 'Mast', "cardiac neuron" = 'Neuronal', "pericyte" = 'Pericyte', "vascular associated smooth muscle cell" = 'VSMC', "regular ventricular cardiac myocyte" = 'VentricularCM'), "projection_label_map" = list("adipocyte" = 'Adipocyte', "regular atrial cardiac myocyte" = 'AtrialCM', "endocardial cell" = 'Endocardial', "cardiac endothelial cell" = 'Endothelial', "mesothelial cell of epicardium" = 'Epicardial', "fibroblast of cardiac tissue" = 'Fibroblast', "endothelial cell of lymphatic vessel" = 'LymphaticEndothelial', "lymphocyte" = 'Lymphocyte', "macrophage" = 'Macrophage', "mast cell" = 'Mast', "cardiac neuron" = 'Neuronal', "pericyte" = 'Pericyte', "vascular associated smooth muscle cell" = 'VSMC', "regular ventricular cardiac myocyte" = 'VentricularCM')), "PBMC_1k1k" = list("build_pseudobulk" = FALSE, "pseudobulk_dir" = 'data/pseudobulk/PBMC_1k1k', "kind" = 'h5ad', "raw" = 'data/pseudobulk/raw/PBMC_1k1k/PBMC_1k1k_raw.h5ad', "matrix" = 'X', "sample_col" = 'donor_id', "sample_transform" = 'sample_prefix_hyphen_to_underscore', "truth_v0_col" = 'predicted.celltype.l2', "raw_cell_type_col" = 'predicted.celltype.l2', "projection_label_col" = 'predicted.celltype.l2', "cohort_manifest" = 'data/pseudobulk/PBMC_1k1k/patient_info.csv', "truth_v0_map" = list("CD4 CTL" = 'CD4_T', "CD4 Naive" = 'CD4_T', "CD4 Proliferating" = 'CD4_T', "CD4 TCM" = 'CD4_T', "CD4 TEM" = 'CD4_T', "Treg" = 'CD4_T', "CD8 Naive" = 'CD8_T', "CD8 Proliferating" = 'CD8_T', "CD8 TCM" = 'CD8_T', "CD8 TEM" = 'CD8_T', "gdT" = 'gd_T', "B intermediate" = 'B_cell', "B memory" = 'B_cell', "B naive" = 'B_cell', "Plasmablast" = 'Plasma_B', "CD14 Mono" = 'CD14_Mono', "CD16 Mono" = 'CD16_Mono', "cDC1" = 'DC', "cDC2" = 'DC', "ASDC" = 'DC', "NK" = 'NK', "NK Proliferating" = 'NK', "NK_CD56bright" = 'NK'), "projection_label_map" = list("CD4 CTL" = 'CD4_T', "CD4 Naive" = 'CD4_T', "CD4 Proliferating" = 'CD4_T', "CD4 TCM" = 'CD4_T', "CD4 TEM" = 'CD4_T', "Treg" = 'CD4_T', "CD8 Naive" = 'CD8_T', "CD8 Proliferating" = 'CD8_T', "CD8 TCM" = 'CD8_T', "CD8 TEM" = 'CD8_T', "gdT" = 'gd_T', "B intermediate" = 'B_cell', "B memory" = 'B_cell', "B naive" = 'B_cell', "Plasmablast" = 'Plasma_B', "CD14 Mono" = 'CD14_Mono', "CD16 Mono" = 'CD16_Mono', "cDC1" = 'DC', "cDC2" = 'DC', "ASDC" = 'DC', "NK" = 'NK', "NK Proliferating" = 'NK', "NK_CD56bright" = 'NK')), "PBMC_Perez2022" = list("build_pseudobulk" = FALSE, "pseudobulk_dir" = 'data/pseudobulk/PBMC_Perez2022', "kind" = 'h5ad', "raw" = 'data/pseudobulk/raw/PBMC_Perez2022/PBMC_Perez2022_raw.h5ad', "matrix" = 'raw.X', "sample_col" = 'ind_cov', "sample_transform" = 'sample_prefix_hyphen_to_underscore', "truth_v0_col" = 'cell_type', "raw_cell_type_col" = 'cell_type', "projection_label_col" = 'cell_type', "cohort_manifest" = 'data/pseudobulk/PBMC_Perez2022/patient_info.csv', "truth_v0_map" = list("B cell" = 'B_cell', "plasmablast" = 'B_cell', "classical monocyte" = 'Myeloid', "non-classical monocyte" = 'Myeloid', "conventional dendritic cell" = 'Myeloid', "plasmacytoid dendritic cell" = 'Myeloid', "progenitor cell" = 'Myeloid', "natural killer cell" = 'NK', "CD4-positive, alpha-beta T cell" = 'T_cell', "CD8-positive, alpha-beta T cell" = 'T_cell', "lymphocyte" = 'T_cell'), "projection_label_map" = list("B cell" = 'B_cell', "plasmablast" = 'B_cell', "classical monocyte" = 'Myeloid', "non-classical monocyte" = 'Myeloid', "conventional dendritic cell" = 'Myeloid', "plasmacytoid dendritic cell" = 'Myeloid', "progenitor cell" = 'Myeloid', "natural killer cell" = 'NK', "CD4-positive, alpha-beta T cell" = 'T_cell', "CD8-positive, alpha-beta T cell" = 'T_cell', "lymphocyte" = 'T_cell')), "Lung_Sikkema2023" = list("build_pseudobulk" = TRUE, "kind" = 'h5ad', "raw" = 'data/pseudobulk/Lung_Sikkema2023/lung_HLCA.h5ad', "matrix" = 'raw.X', "sample_col" = 'donor_id', "sample_transform" = 'identity', "truth_v0_col" = 'ann_level_2', "truth_v1_col" = 'ann_finest_level', "raw_cell_type_col" = 'ann_level_3', "projection_label_col" = 'ann_level_2', "min_cells" = 400)), "methods" = list("CLAMPbase" = 'CLAMPbase/B.csv', "CLAMPfull" = 'CLAMPfull/B.csv', "PLIER" = 'PLIER/B.csv', "PCA" = 'PCA/B.csv', "NMF" = 'NMF/B.csv', "ICA" = 'ICA/B.csv', "Flashier" = 'flashier/B.csv', "MOFA-FLEX" = 'MOFA_FLEX_PRIOR/B.csv', "GSSig" = 'GSS/B.csv', "CoGAPS" = 'CoGAPS/B.csv'), "paths" = list("production" = 'output/01_model_building/00_pseudobulk', "biology" = 'output/03_model_biology/00_pseudobulk', "model_notebooks" = 'nbs/01_model_building/00_pseudobulk', "biology_notebooks" = 'nbs/03_model_biology/00_pseudobulk', "panels" = 'output/99_panels', "panels_notebooks" = 'nbs/99_panels'), "references" = list("go_bp_url" = 'https://maayanlab.cloud/Enrichr/geneSetLibrary?mode=text&libraryName=GO_Biological_Process_2025', "go_bp_file" = 'data/pathways/GO_Biological_Process_2025.gmt', "go_bp_sha256" = '0fc02458765cfce6c9348dce9f7a9397c6caf7c09ba318f468135d7ac60342ee', "cell_marker_file" = 'data/pathways/Cell_marker_Human.xlsx', "allen_brain_gmt_file" = 'data/pathways/Allen_Brain_Atlas_10x_scRNA_2021.gmt', "azimuth_file" = 'data/pathways/Azimuth_2023.txt', "gtex_tissues_pathmat" = 'data/archs4/GTEx_Tissues_pathMat.rds', "brain_datasets" = c('Brain_Mathys2023', 'Brain_Xiong2023')), "preprocess" = list("mean_cutoff" = 0.5, "var_cutoff" = 0.1, "seed" = 123), "module_recovery" = list("top_gene_fraction" = 0.01, "retry_gene_fraction" = 0.03, "fdr_threshold" = 0.05, "top_terms" = 3), "clamp" = list("max_iter" = 500, "seed" = 123), "grouped_cv" = list("n_folds" = 5, "group_col" = 'sample', "split_seed" = 42, "min_train_lv_cor" = 0.5, "bootstrap_seed" = 123, "bootstrap_replicates" = 10000), "flashier" = list("backfit_maxiter" = 20), "cogaps" = list("n_iterations" = 5000, "n_threads" = 4, "seed" = 123), "mofa_flex" = list("max_epochs" = 1000, "seed" = 123), "projection" = list("chunk_cells" = 20000, "chunk_nnz" = 20000000, "top_fraction" = 0.01), "cell_type_analysis" = list("excluded_targets" = list("Brain_Mathys2023" = c('Vas'), "Brain_Xiong2023" = c('Vas'), "Lung_Sikkema2023" = c('Hematopoietic stem cells', 'Mesothelium', 'Smooth muscle'))), "gtex" = list("raw_url" = 'https://storage.googleapis.com/adult-gtex/bulk-gex/v8/rna-seq/GTEx_Analysis_2017-06-05_v8_RNASeQCv1.1.9_gene_tpm.gct.gz', "raw_gz" = 'data/gtex/GTEx_Analysis_2017-06-05_v8_RNASeQCv1.1.9_gene_tpm.gct.gz', "metadata" = 'data/gtex/GTEx_Analysis_v8_Annotations_SampleAttributesDS.txt', "xcell_scores" = 'data/gtex/GTEx_Analysis_v8_xCell_scores_7_celltypes.txt', "paths" = list("production" = 'output/01_model_building/01_gtex', "biology" = 'output/03_model_biology/01_gtex', "model_notebooks" = 'nbs/01_model_building/01_gtex', "biology_notebooks" = 'nbs/03_model_biology/01_gtex'), "raw_data" = list("chunk_size" = 100, "n_cores" = 1), "preprocess" = list("mean_cutoff" = 0.5, "var_cutoff" = 0.1, "seed" = 123), "clamp" = list("max_iter" = 500, "seed" = 123), "flashier" = list("backfit_maxiter" = 20), "mofa_flex_prior" = list("min_fraction" = 0.4, "min_count" = 40, "max_count" = 200, "similarity_threshold" = 0.8, "max_epochs" = 1000, "seed" = 123), "cogaps" = list("n_iterations" = 5000, "n_threads" = 4, "seed" = 123, "timeout_days" = 7), "gss" = list("d_cluster" = 4, "seed" = 123), "kmeans_clustering" = list("min_samples" = 50, "ari_min_samples" = 1, "n_clusters" = 54, "base_seed" = 10000, "n_reps_per_k" = 50, "gene_fractions" = c(1.0, 0.75, 0.5, 0.25, 0.1, 0.05, 0.01)), "lv_importance" = list("global_seed" = 42, "min_rf_accuracy" = 0.9), "subtissue_inference" = list("n_folds" = 5, "global_seed" = 42, "min_rf_accuracy" = 0.85, "min_subtissue_samples" = 20, "n_jobs_per_fold" = 8, "anatomical_spec" = 'workflow/config/gtex_anatomical_subtissues.tsv', "permutation_repeats" = 1000, "bootstrap_repeats" = 1000, "evaluation_jobs" = 8, "tissues" = c('Adipose Tissue', 'Blood', 'Blood Vessel', 'Brain', 'Colon', 'Esophagus', 'Heart', 'Kidney', 'Skin'))), "runtime_benchmark" = list("seeds" = c(123, 456, 789), "threads" = 4, "methods" = c('CLAMPfull', 'CLAMPbase', 'PLIER', 'CoGAPS', 'Flashier', 'NMF', 'PCA', 'ICA', 'GSSig', 'MOFA-FLEX'), "output_root" = 'output/02_model_performance/00_pseudobulk/00_computational_timing', "notebook" = 'nbs/02_model_performance/00_pseudobulk/00_computational_timing.ipynb'), "runtime_benchmark_gtex" = list("dataset" = 'GTEx', "seeds" = c(123, 456, 789), "threads" = 4, "methods" = c('CLAMPfull', 'CLAMPbase', 'PLIER', 'Flashier', 'NMF', 'PCA', 'ICA', 'GSSig', 'MOFA-FLEX'), "excluded_methods" = list("CoGAPS" = 'rule cogaps_gtex was run to the end of its hard wall-clock budget (gtex.cogaps.timeout_days = 7) and killed without converging; the evidence is on disk at output/01_model_building/01_gtex/CoGAPS/NOT_CONVERGED.txt. CoGAPS therefore has no finite GTEx runtime to report\n'), "cogaps_evidence" = 'output/01_model_building/01_gtex/CoGAPS/NOT_CONVERGED.txt', "output_root" = 'output/02_model_performance/01_gtex/00_computational_timing', "notebook" = 'nbs/02_model_performance/01_gtex/00_computational_timing.ipynb'), "donor_bulk" = list("datasets" = c('Brain_Mathys2023', 'Brain_Xiong2023', 'Heart_Datar2026', 'PBMC_1k1k', 'PBMC_Perez2022', 'Lung_Sikkema2023'), "paths" = list("production" = 'output/01_model_building/00_pseudobulk/donor_bulk', "biology" = 'output/03_model_biology/00_pseudobulk/06_donor_bulk_recovery', "model_notebooks" = 'nbs/01_model_building/00_pseudobulk', "biology_notebooks" = 'nbs/03_model_biology/00_pseudobulk'), "aggregation" = list("chunk_cells" = 20000, "chunk_nnz" = 20000000, "sample_cells" = 60000, "minimum_per_type" = 250, "seed" = 123), "umap" = list("target_sum" = 10000, "n_hvg" = 2000, "n_pcs" = 50, "n_neighbors" = 30, "min_dist" = 0.3, "seed" = 123), "projection" = list("chunk_cells" = 20000, "chunk_nnz" = 20000000, "duplicate_gene_policy" = 'sum')), "archs4" = list("raw_url" = 'https://s3.dev.maayanlab.cloud/archs4/files/human_gene_v2.5.h5', "raw_h5" = 'data/archs4/human_gene_v2.5.h5', "gene_lengths" = 'data/archs4/gene_lengths.rds', "ensembl_version" = 107, "paths" = list("production" = 'output/01_model_building/02_archs4', "biology" = 'output/03_model_biology/02_archs4', "model_notebooks" = 'nbs/01_model_building/02_archs4', "biology_notebooks" = 'nbs/03_model_biology/02_archs4'), "raw_data" = list("block_size" = 100, "n_cores" = 10), "preprocess" = list("mean_cutoff" = 0.5, "var_cutoff" = 0.1, "single_cell_probability_max" = 0.5, "seed" = 123), "svd" = list("n_cores" = 30, "seed" = 123), "clamp" = list("k_multiplier" = 2, "multiplier" = 100, "max_iter" = 5000, "seed" = 123), "prior" = list("gmts" = list("HALL" = 'data/pathways/h.all.v2026.1.Hs.symbols.gmt', "REACTOME" = 'data/pathways/c2.cp.reactome.v2026.1.Hs.symbols.gmt', "GOCC" = 'data/pathways/c5.go.cc.v2026.1.Hs.symbols.gmt', "C8" = 'data/pathways/c8.all.v2026.1.Hs.symbols.gmt')), "final_model" = list("dir" = 'output/01_model_building/02_archs4/01_final_model', "seeds" = c(1, 2, 3), "reference_seed" = 1, "leaf" = 'seed{seed}', "model_name" = 'CLAMPfull'), "coverage" = list("prior_gmt" = 'data/pathways/go_bp.Hs.symbols.gmt', "model_root" = 'output/01_model_building/02_archs4/02_coverage_study/models', "ora_root" = 'output/01_model_building/02_archs4/02_coverage_study/ora', "assignments" = 'output/03_model_biology/02_archs4/00_coverage/assignments', "seeds" = c(1, 2, 3), "rng_seeds" = c(123, 124, 125), "levels" = list("1" = '00_bp_coverage_study_01', "5" = '01_bp_coverage_study_05', "10" = '02_bp_coverage_study_10', "25" = '03_bp_coverage_study_25', "50" = '04_bp_coverage_study_50', "75" = '05_bp_coverage_study_75', "100" = '06_bp_coverage_study_100'), "input_root" = 'output/01_model_building/02_archs4/02_coverage_study', "model_name" = 'CLAMPfull_bp', "resources" = list("1" = list("mem_mb" = 32000, "runtime" = 5760), "5" = list("mem_mb" = 64000, "runtime" = 8640), "10" = list("mem_mb" = 96000, "runtime" = 14400), "25" = list("mem_mb" = 224000, "runtime" = 24000), "50" = list("mem_mb" = 192000, "runtime" = 36000), "75" = list("mem_mb" = 288000, "runtime" = 48000), "100" = list("mem_mb" = 320000, "runtime" = 54000)), "comparators" = list("gtex" = list("label" = 'GTEx', "fbm_rds" = 'output/01_model_building/01_gtex/gtex_fbm_filt.rds', "genes_rds" = 'output/01_model_building/01_gtex/gtex_genes.rds', "samples_rds" = 'output/01_model_building/01_gtex/gtex_samples.rds', "svd" = 'output/01_model_building/01_gtex/gtex_svdRes.rds', "k" = 'output/01_model_building/01_gtex/CLAMP_K_gtex.rds', "base" = 'output/01_model_building/01_gtex/CLAMPbase.rds', "base_z" = 'output/01_model_building/01_gtex/CLAMPbase/Z.csv', "max_iter" = 500), "recount2" = list("label" = 'recount2', "fbm_rds" = 'output/01_model_building/03_recount2/00_recount2/recount2_fbm_filt.rds', "genes_rds" = 'output/01_model_building/03_recount2/00_recount2/recount2_genes.rds', "samples_rds" = 'output/01_model_building/03_recount2/00_recount2/recount2_samples.rds', "svd" = 'output/01_model_building/03_recount2/00_recount2/recount2_svdRes.rds', "k" = 'output/01_model_building/03_recount2/00_recount2/CLAMP_K_recount2.rds', "base" = 'output/01_model_building/03_recount2/00_recount2/CLAMPbase.rds', "base_z" = 'output/01_model_building/03_recount2/00_recount2/CLAMPbase/Z.csv', "max_iter" = 500)), "colors" = list("model" = list("CLAMPfull" = '#0072B2', "CLAMPbase" = '#777777'), "dataset" = list("ARCHS4" = '#0072B2', "GTEx" = '#E69F00', "recount2" = '#009E73')), "routing" = list("remote_min_free_cpus" = 2, "remote_min_free_mem_mb" = 16000, "remote_max_ora_jobs" = 8, "local_total_mem_mb" = 96000, "retries" = 2, "retry_mem_factors" = c(1.0, 1.5, 2.0), "retry_mem_cap_mb" = 800000)), "ora" = list("databases" = list("reactome" = list("type" = 'gmt', "path" = 'data/pathways/c2.cp.reactome.v2026.1.Hs.symbols.gmt', "label" = 'Reactome'), "canonical" = list("type" = 'gmt', "path" = 'data/pathways/c2.cp.v2026.1.Hs.symbols.gmt', "exclude_term_regex" = '^REACTOME_', "label" = 'Canonical non-Reactome'), "cellmarker" = list("type" = 'cellmarker_xlsx', "path" = 'data/pathways/Cell_marker_Human.xlsx', "sheet" = 'human', "term_column" = 'cell_name', "gene_column" = 'Symbol', "label" = 'CellMarker')), "top_pct" = 0.01, "min_size" = 10, "max_size" = 500, "pvalue_cutoff" = 0.05, "qvalue_cutoff" = 0.2, "fdr" = c(0.05), "resources" = list("mem_mb" = 8000, "runtime" = 5760)))),
    rule = 'global_alignment_rf_true_labels_gtex',
    bench_iteration = as.numeric(NA),
    scriptdir = '/home/msubirana/Documents/pivlab/clamp-analyses/nbs/03_model_biology/01_gtex',
    source = function(...){
        wd <- getwd()
        setwd(snakemake@scriptdir)
        source(...)
        setwd(wd)
    }
)
setwd('/home/msubirana/Documents/pivlab/clamp-analyses');

######## snakemake preamble end #########

# GTEx global alignment

The SHAP results driving this analysis come from the `lv_importance_rf_true_labels_gtex` rule (`scripts/gtex/lv_importance_true_labels.py`). For each GTEx tissue, this notebook tests whether the selected SHAP latent variables recover the true tissue via over-representation analysis (ORA) against the GTEx tissue gene-set database, both for the single highest-ranked LV per tissue (top1) and for the smallest set of top-ranked LVs needed to reach `CUMULATIVE_PCT`% of cumulative SHAP per tissue (cumulative20), the same criterion used in `01_LV_importance.ipynb` and `02_b_matrix.ipynb`. Per-LV ORA follows the retry-with-fallback approach from `00_pseudobulk/02_disentangle.ipynb`: it tests the top `TOP_GENE_PCT` (1%) gene loadings first, and if nothing clears FDR < `FDR_THRESH` (5%), retries once at `TOP_GENE_PCT_FALLBACK` (3%) before giving up on that LV.

💡 **Environment:** `clamp-analyses`

## Libraries

In [2]:
library(here)
library(dplyr)
library(tidyr)
library(stringr)
library(Matrix)
library(clusterProfiler)
library(ggplot2)

here() starts at /home/msubirana/Documents/pivlab/clamp-analyses

Attaching package: ‘dplyr’

The following objects are masked from ‘package:stats’:

    filter, lag

The following objects are masked from ‘package:base’:

    intersect, setdiff, setequal, union

Attaching package: ‘Matrix’

The following objects are masked from ‘package:tidyr’:

    expand, pack, unpack

clusterProfiler v4.14.0 Learn more at https://yulab-smu.top/contribution-knowledge-mining/

Please cite:

Guangchuang Yu, Li-Gen Wang, Yanyan Han and Qing-Yu He.
clusterProfiler: an R package for comparing biological themes among
gene clusters. OMICS: A Journal of Integrative Biology. 2012,
16(5):284-287

Attaching package: ‘clusterProfiler’

The following object is masked from ‘package:stats’:

    filter

## Settings

In [3]:
SHAP_DIR <- here('output', '03_model_biology', '01_gtex',
                 '01_LV_importance_rf_true_labels',
                 'gtex_feature_importance_true_labels_binary_shap')
OUT_DIR  <- here('output', '03_model_biology', '01_gtex', '07_global_alignment_rf_true_labels')
dir.create(OUT_DIR, recursive = TRUE, showWarnings = FALSE)

CLAMP_RDS      <- here('output', '01_model_building', '01_gtex', 'CLAMPfull.rds')
GTEX_TISSUE_DB <- here('data', 'archs4', 'GTEx_Tissues_pathMat.rds')

N_LVS_PER_TISSUE <- 1L
CUMULATIVE_PCT   <- 20  # same threshold as 02_b_matrix.ipynb
TOP_GENE_PCT     <- 0.01
TOP_GENE_PCT_FALLBACK <- 0.03  # retried once for LVs with zero significant hits at TOP_GENE_PCT
FDR_THRESH       <- 0.05

In [4]:
shap_all <- read.delim(file.path(SHAP_DIR, 'all_shap_positive.tsv'),
                       stringsAsFactors = FALSE, check.names = FALSE)

selected_lvs_top1 <- shap_all %>%
    dplyr::arrange(Tissue, Rank) %>%
    dplyr::group_by(Tissue) %>%
    dplyr::slice_head(n = N_LVS_PER_TISSUE) %>%
    dplyr::ungroup() %>%
    dplyr::rename(LV = Feature) %>%
    dplyr::select(Tissue, LV, Rank, Mean_SHAP_Tissue, Cumulative_SHAP, Cumulative_Percent)

selected_lvs_cum <- shap_all %>%
    dplyr::arrange(Tissue, Rank) %>%
    dplyr::group_by(Tissue) %>%
    dplyr::mutate(
        reaches_thresh = Cumulative_Percent >= CUMULATIVE_PCT,
        cutoff_rank = if (any(reaches_thresh)) min(Rank[reaches_thresh]) else max(Rank)
    ) %>%
    dplyr::filter(Rank <= cutoff_rank) %>%
    dplyr::ungroup() %>%
    dplyr::rename(LV = Feature) %>%
    dplyr::select(Tissue, LV, Rank, Mean_SHAP_Tissue, Cumulative_SHAP, Cumulative_Percent)

selections <- list(top1 = selected_lvs_top1, cumulative20 = selected_lvs_cum)

cat('Tissues:', dplyr::n_distinct(selected_lvs_top1$Tissue), '\n')
for (nm in names(selections)) {
    cat(sprintf('  [%s] selected LV/tissue rows: %d, unique LVs: %d\n',
                nm, nrow(selections[[nm]]), dplyr::n_distinct(selections[[nm]]$LV)))
}

dplyr::bind_rows(lapply(names(selections), function(nm) {
    selections[[nm]] %>%
        dplyr::count(Tissue, name = 'n_selected_lvs') %>%
        dplyr::mutate(analysis = nm)
})) %>%
    tidyr::pivot_wider(names_from = analysis, values_from = n_selected_lvs) %>%
    dplyr::arrange(Tissue)

Tissues: 49

  [top1] selected LV/tissue rows: 49, unique LVs: 42
  [cumulative20] selected LV/tissue rows: 162, unique LVs: 101

   Tissue                                    top1 cumulative20
1  Adipose - Subcutaneous                    1    3
2  Adipose - Visceral (Omentum)              1    4
3  Adrenal Gland                             1    1
4  Artery - Aorta                            1    2
5  Artery - Coronary                         1    2
6  Artery - Tibial                           1    4
7  Brain - Amygdala                          1    3
8  Brain - Anterior cingulate cortex (BA24)  1    6
9  Brain - Caudate (basal ganglia)           1    5
10 Brain - Cerebellar Hemisphere             1    7
11 Brain - Cerebellum                        1    6
12 Brain - Cortex                            1    3
13 Brain - Frontal Cortex (BA9)              1    5
14 Brain - Hippocampus                       1    4
15 Brain - Hypothalamus                      1    4
16 Brain - Nucleus accumbens (basal ganglia) 1    4
17 Brain - Putamen (basal ganglia)           1    5
18 Brain - Spinal cord (cervical c-1)        1    3
19 Brain - Substantia nigra                  1    3
20 Breast - Mammary Tissue                   1    4
21 Cells - Cultured fibroblasts              1    2
22 Cells - EBV-transformed lymphocytes       1    3
23 Colon - Sigmoid                           1    2
24 Colon - Transverse                        1    4
25 Esophagus - Gastroesophageal Junction     1    4
26 Esophagus - Mucosa                        1    3
27 Esophagus - Muscularis                    1    3
28 Heart - Atrial Appendage                  1    2
29 Heart - Left Ventricle                    1    5
30 Kidney - Cortex                           1    2
31 Liver                                     1    3
32 Lung                                      1    1
33 Minor Salivary Gland                      1    3
34 Muscle - Skeletal                         1    3
35 Nerve - Tibial                            1    1
36 Ovary                                     1    4
37 Pancreas                                  1    2
38 Pituitary                                 1    4
39 Prostate                                  1    3
40 Skin - Not Sun Exposed (Suprapubic)       1    4
41 Skin - Sun Exposed (Lower leg)            1    3
42 Small Intestine - Terminal Ileum          1    3
43 Spleen                                    1    3
44 Stomach                                   1    3
45 Testis                                    1    3
46 Thyroid                                   1    1
47 Uterus                                    1    3
48 Vagina                                    1    3
49 Whole Blood                               1    4

In [5]:
clamp <- readRDS(CLAMP_RDS)
Z_full <- as.matrix(clamp$Z)
rm(clamp)

all_selected_lvs <- unique(unlist(lapply(selections, function(df) df$LV)))
selected_unique_lvs <- intersect(all_selected_lvs, colnames(Z_full))
missing_lvs <- setdiff(all_selected_lvs, colnames(Z_full))
if (length(missing_lvs) > 0) warning('Missing LVs in Z: ', paste(missing_lvs, collapse = ', '))

Z <- Z_full[, selected_unique_lvs, drop = FALSE]
rm(Z_full)
universe_genes <- rownames(Z)
n_top_genes          <- max(1L, ceiling(TOP_GENE_PCT * nrow(Z)))
n_top_genes_fallback  <- max(1L, ceiling(TOP_GENE_PCT_FALLBACK * nrow(Z)))

cat('Z:', nrow(Z), 'genes x', ncol(Z), 'unique LVs (union across analyses)\n')
cat('Top genes per LV:', n_top_genes, '(primary), ', n_top_genes_fallback, '(fallback)\n')

Z: 21613 genes x 101 unique LVs (union across analyses)

Top genes per LV: 217 (primary),  649 (fallback)

In [6]:
gtex_mat <- readRDS(GTEX_TISSUE_DB)
term_names <- unname(colnames(gtex_mat))

parse_gtex_tissue <- function(x) {
    x <- sub('^GTEx_Tissues_', '', x)
    x <- sub(' (Male|Female) [0-9]+-[0-9]+ Up$', '', x)
    x
}

normalize_text <- function(x) {
    x <- tolower(x)
    x <- gsub('[^a-z0-9]+', ' ', x)
    stringr::str_squish(x)
}

term2gene <- lapply(seq_along(term_names), function(i) {
    rownames(gtex_mat)[gtex_mat[, i] != 0]
})
names(term2gene) <- term_names

term2gene_df <- do.call(rbind, lapply(names(term2gene), function(term) {
    data.frame(term = term, gene = term2gene[[term]], stringsAsFactors = FALSE)
}))

term_map <- data.frame(
    term = term_names,
    parsed_tissue = parse_gtex_tissue(term_names),
    normalized_tissue = normalize_text(parse_gtex_tissue(term_names)),
    stringsAsFactors = FALSE
)

tissue_check <- dplyr::bind_rows(selections) %>%
    dplyr::distinct(Tissue) %>%
    dplyr::mutate(
        normalized_tissue = normalize_text(Tissue),
        matched_in_gtex_db = normalized_tissue %in% term_map$normalized_tissue,
        n_db_sets = vapply(normalized_tissue, function(x) sum(term_map$normalized_tissue == x, na.rm = TRUE), integer(1))
    )

cat('GTEx tissue gene sets:', length(term2gene), '\n')
stopifnot(all(tissue_check$matched_in_gtex_db))
tissue_check

GTEx tissue gene sets: 511

                                      Tissue
adipose subcutaneous                  Adipose - Subcutaneous
adipose visceral omentum              Adipose - Visceral (Omentum)
adrenal gland                         Adrenal Gland
artery aorta                          Artery - Aorta
artery coronary                       Artery - Coronary
artery tibial                         Artery - Tibial
brain amygdala                        Brain - Amygdala
brain anterior cingulate cortex ba24  Brain - Anterior cingulate cortex (BA24)
brain caudate basal ganglia           Brain - Caudate (basal ganglia)
brain cerebellar hemisphere           Brain - Cerebellar Hemisphere
brain cerebellum                      Brain - Cerebellum
brain cortex                          Brain - Cortex
brain frontal cortex ba9              Brain - Frontal Cortex (BA9)
brain hippocampus                     Brain - Hippocampus
brain hypothalamus                    Brain - Hypothalamus
brain nucleus accumbens basal ganglia Brain - Nucleus accumbens (basal ganglia)
brain putamen basal ganglia           Brain - Putamen (basal ganglia)
brain spinal cord cervical c 1        Brain - Spinal cord (cervical c-1)
brain substantia nigra                Brain - Substantia nigra
breast mammary tissue                 Breast - Mammary Tissue
cells cultured fibroblasts            Cells - Cultured fibroblasts
cells ebv transformed lymphocytes     Cells - EBV-transformed lymphocytes
colon sigmoid                         Colon - Sigmoid
colon transverse                      Colon - Transverse
esophagus gastroesophageal junction   Esophagus - Gastroesophageal Junction
esophagus mucosa                      Esophagus - Mucosa
esophagus muscularis                  Esophagus - Muscularis
heart atrial appendage                Heart - Atrial Appendage
heart left ventricle                  Heart - Left Ventricle
kidney cortex                         Kidney - Cortex
liver                                 Liver
lung                                  Lung
minor salivary gland                  Minor Salivary Gland
muscle skeletal                       Muscle - Skeletal
nerve tibial                          Nerve - Tibial
ovary                                 Ovary
pancreas                              Pancreas
pituitary                             Pituitary
prostate                              Prostate
skin not sun exposed suprapubic       Skin - Not Sun Exposed (Suprapubic)
skin sun exposed lower leg            Skin - Sun Exposed (Lower leg)
small intestine terminal ileum        Small Intestine - Terminal Ileum
spleen                                Spleen
stomach                               Stomach
testis                                Testis
thyroid                               Thyroid
uterus                                Uterus
vagina                                Vagina
whole blood                           Whole Blood
                                      normalized_tissue
adipose subcutaneous                  adipose subcutaneous
adipose visceral omentum              adipose visceral omentum
adrenal gland                         adrenal gland
artery aorta                          artery aorta
artery coronary                       artery coronary
artery tibial                         artery tibial
brain amygdala                        brain amygdala
brain anterior cingulate cortex ba24  brain anterior cingulate cortex ba24
brain caudate basal ganglia           brain caudate basal ganglia
brain cerebellar hemisphere           brain cerebellar hemisphere
brain cerebellum                      brain cerebellum
brain cortex                          brain cortex
brain frontal cortex ba9              brain frontal cortex ba9
brain hippocampus                     brain hippocampus
brain hypothalamus                    brain hypothalamus
brain nucleus accumbens basal ganglia brain nucleus accumbens basal ganglia
brain putamen basal ganglia           brain putamen basal ganglia
brain spinal cord cervical c 1        brain spinal cord cervical c 1
brain substantia nigra                brain substantia nigra
breast mammary tissue                 breast mammary tissue
cells cultured fibroblasts            cells cultured fibroblasts
cells ebv transformed lymphocytes     cells ebv transformed lymphocytes
colon sigmoid                         colon sigmoid
colon transverse                      colon transverse
esophagus gastroesophageal junction   esophagus gastroesophageal junction
esophagus mucosa                      esophagus mucosa
esophagus muscularis                  esophagus muscularis
heart atrial appendage                heart atrial appendage
heart left ventricle                  heart left ventricle
kidney cortex                         kidney cortex
liver                                 liver
lung                                  lung
minor salivary gland                  minor salivary gland
muscle skeletal                       muscle skeletal
nerve tibial                          nerve tibial
ovary                                 ovary
pancreas                              pancreas
pituitary                             pituitary
prostate                              prostate
skin not sun exposed suprapubic       skin not sun exposed suprapubic
skin sun exposed lower leg            skin sun exposed lower leg
small intestine terminal ileum        small intestine terminal ileum
spleen                                spleen
stomach                               stomach
testis                                testis
thyroid                               thyroid
uterus                                uterus
vagina                                vagina
whole blood                           whole blood
                                      matched_in_gtex_db n_db_sets
adipose subcutaneous                  TRUE               12
adipose visceral omentum              TRUE               12
adrenal gland                         TRUE               11
artery aorta                          TRUE               12
artery coronary                       TRUE               11
artery tibial                         TRUE               12
brain amygdala                        TRUE                8
brain anterior cingulate cortex ba24  TRUE                9
brain caudate basal ganglia           TRUE               10
brain cerebellar hemisphere           TRUE               10
brain cerebellum                      TRUE               10
brain cortex                          TRUE               11
brain frontal cortex ba9              TRUE                8
brain hippocampus                     TRUE               10
brain hypothalamus                    TRUE               10
brain nucleus accumbens basal ganglia TRUE               11
brain putamen basal ganglia           TRUE                9
brain spinal cord cervical c 1        TRUE                8
brain substantia nigra                TRUE                8
breast mammary tissue                 TRUE               12
cells cultured fibroblasts            TRUE               12
cells ebv transformed lymphocytes     TRUE                9
colon sigmoid                         TRUE               12
colon transverse                      TRUE               11
esophagus gastroesophageal junction   TRUE               12
esophagus mucosa                      TRUE               12
esophagus muscularis                  TRUE               12
heart atrial appendage                TRUE               12
heart left ventricle                  TRUE               12
kidney cortex                         TRUE                7
liver                                 TRUE               11
lung                                  TRUE               12
minor salivary gland                  TRUE               10
muscle skeletal                       TRUE               12
nerve tibial                          TRUE               12
ovary                                 TRUE                6
pancreas                              TRUE               11
pituitary                             TRUE               11
prostate                              TRUE                6
skin not sun exposed suprapubic       TRUE               12
skin sun exposed lower leg            TRUE               12
small intestine terminal ileum        TRUE               11
spleen                                TRUE               11
stomach                               TRUE               11
testis                                TRUE                6
thyroid                               TRUE               12
uterus                                TRUE                5
vagina                                TRUE                6
whole blood                           TRUE               12

In [7]:
# ORA per selected LV against the GTEx tissue gene-set database -- top 1%
# gene loadings (TOP_GENE_PCT) tested via clusterProfiler::enricher(). If
# NOTHING clears FDR < FDR_THRESH at 1%, retries once at
# TOP_GENE_PCT_FALLBACK (3%) before giving up on that LV -- same
# retry-with-fallback used for module-level marker recovery in
# 00_pseudobulk/02_disentangle.ipynb.
run_gtex_tissue_ora <- function(genes, universe) {
    res <- tryCatch(
        clusterProfiler::enricher(
            gene          = genes,
            universe      = universe,
            TERM2GENE     = term2gene_df,
            pAdjustMethod = 'BH',
            pvalueCutoff  = 1,
            qvalueCutoff  = 1,
            minGSSize     = 10,
            maxGSSize     = 500
        ),
        error = function(e) NULL
    )
    if (is.null(res)) return(NULL)
    df <- as.data.frame(res)
    if (nrow(df) == 0) return(NULL)
    df
}

get_top_genes <- function(lv, pct) {
    vals    <- Z[, lv]
    n_genes <- max(1L, ceiling(pct * length(vals)))
    universe_genes[order(vals, decreasing = TRUE)[seq_len(n_genes)]]
}

run_lv_ora_with_fallback <- function(lv) {
    df       <- run_gtex_tissue_ora(get_top_genes(lv, TOP_GENE_PCT), universe_genes)
    sig      <- if (!is.null(df)) df[df$p.adjust < FDR_THRESH, ] else df
    pct_used <- TOP_GENE_PCT

    if (is.null(sig) || nrow(sig) == 0) {
        df       <- run_gtex_tissue_ora(get_top_genes(lv, TOP_GENE_PCT_FALLBACK), universe_genes)
        pct_used <- TOP_GENE_PCT_FALLBACK
    }
    if (is.null(df)) return(NULL)
    df$top_gene_pct_used <- pct_used
    df
}

ora_list <- lapply(colnames(Z), function(lv) {
    df <- run_lv_ora_with_fallback(lv)
    if (is.null(df)) return(NULL)
    df$LV <- lv
    df
})

ora_all <- do.call(rbind, Filter(Negate(is.null), ora_list))
if (is.null(ora_all)) {
    ora_all <- data.frame()
} else {
    rownames(ora_all) <- NULL
    ora_all <- ora_all %>%
        dplyr::left_join(term_map, by = c('ID' = 'term')) %>%
        dplyr::select(LV, ID, Description, parsed_tissue, normalized_tissue,
                      GeneRatio, BgRatio, pvalue, p.adjust, qvalue, geneID, Count,
                      top_gene_pct_used)
}

write.csv(ora_all, file.path(OUT_DIR, 'gtex_tissue_ora_per_lv.csv'), row.names = FALSE)
cat('ORA rows:', nrow(ora_all), '\n')
cat('LVs retried at fallback pct:',
    dplyr::n_distinct(ora_all$LV[ora_all$top_gene_pct_used == TOP_GENE_PCT_FALLBACK]),
    '/', dplyr::n_distinct(ora_all$LV), '\n')
head(ora_all)

ORA rows: 26037

LVs retried at fallback pct: 0 / 101

  LV    ID
1 LV106 GTEx_Tissues_Fallopian Tube Female 50-59 Up
2 LV106 GTEx_Tissues_Uterus Female 60-69 Up
3 LV106 GTEx_Tissues_Fallopian Tube Female 40-49 Up
4 LV106 GTEx_Tissues_Uterus Female 50-59 Up
5 LV106 GTEx_Tissues_Uterus Female 30-39 Up
6 LV106 GTEx_Tissues_Uterus Female 40-49 Up
  Description                                 parsed_tissue  normalized_tissue
1 GTEx_Tissues_Fallopian Tube Female 50-59 Up Fallopian Tube fallopian tube
2 GTEx_Tissues_Uterus Female 60-69 Up         Uterus         uterus
3 GTEx_Tissues_Fallopian Tube Female 40-49 Up Fallopian Tube fallopian tube
4 GTEx_Tissues_Uterus Female 50-59 Up         Uterus         uterus
5 GTEx_Tissues_Uterus Female 30-39 Up         Uterus         uterus
6 GTEx_Tissues_Uterus Female 40-49 Up         Uterus         uterus
  GeneRatio BgRatio pvalue       p.adjust     qvalue
1 13/111    64/6121 6.825497e-11 2.573212e-08 2.457179e-08
2 13/111    86/6121 3.245673e-09 6.118094e-07 5.842212e-07
3 9/111     57/6121 6.655141e-07 8.363294e-05 7.986169e-05
4 10/111    89/6121 3.921839e-06 3.625863e-04 3.462363e-04
5 10/111    91/6121 4.808837e-06 3.625863e-04 3.462363e-04
6 10/111    93/6121 5.864898e-06 3.685111e-04 3.518939e-04
  geneID
1 HOXC4/HOXD3/HOXD4/HOXC5/HOXC6/HOXA3/EMX2/HOXA6/OSR2/ATP8B4/CDHR3/HOXA5/PLXDC1
2 HOXD3/HOXD4/HOXA11/HOXA10/EMX2/HOXD9/HOXA6/HOXD8/OSR2/ATP8B4/TRPC4/LCN10/PLXDC1
3 HOXC5/HOXA3/EMX2/HOXA6/OSR2/ATP8B4/HOXA2/HOXA5/LCN10
4 HOXD3/HOXD4/HOXA11/HOXA10/EMX2/HOXD9/HOXA6/OSR2/ATP8B4/TRPC4
5 HOXD3/HOXD4/HOXA11/HOXA10/EMX2/HOXD9/HOXA6/OSR2/ITGA11/TRPC4
6 HOXD3/HOXD4/HOXA11/HOXA10/EMX2/HOXD9/HOXA6/OSR2/TRPC4/LCN6
  Count top_gene_pct_used
1 13    0.01
2 13    0.01
3  9    0.01
4 10    0.01
5 10    0.01
6 10    0.01

In [8]:
run_alignment_summary <- function(selected_lvs, ora_all, out_dir) {
    dir.create(out_dir, recursive = TRUE, showWarnings = FALSE)
    sig_ora <- ora_all %>% dplyr::filter(LV %in% selected_lvs$LV, p.adjust < FDR_THRESH)

    detail <- selected_lvs %>%
        dplyr::rowwise() %>%
        dplyr::mutate(
            normalized_true_tissue = normalize_text(Tissue),
            n_sig_terms = sum(sig_ora$LV == LV),
            n_true_terms = sum(sig_ora$LV == LV & sig_ora$normalized_tissue == normalized_true_tissue),
            tissue_correct = n_true_terms > 0,
            best_any_padj = {
                x <- sig_ora$p.adjust[sig_ora$LV == LV]
                if (length(x) == 0) NA_real_ else min(x, na.rm = TRUE)
            },
            best_true_padj = {
                x <- sig_ora$p.adjust[sig_ora$LV == LV & sig_ora$normalized_tissue == normalized_true_tissue]
                if (length(x) == 0) NA_real_ else min(x, na.rm = TRUE)
            },
            matched_terms = paste(sig_ora$ID[sig_ora$LV == LV & sig_ora$normalized_tissue == normalized_true_tissue], collapse = ' | ')
        ) %>%
        dplyr::ungroup()

    tissue_summary <- detail %>%
        dplyr::group_by(Tissue) %>%
        dplyr::summarise(
            n_selected_lvs = dplyr::n(),
            tissue_correct = any(tissue_correct),
            correct_lvs = paste(LV[tissue_correct], collapse = ';'),
            best_true_padj = if (all(is.na(best_true_padj))) NA_real_ else min(best_true_padj, na.rm = TRUE),
            .groups = 'drop'
        ) %>%
        dplyr::mutate(correct_score = as.integer(tissue_correct))

    final_pct_tissue_correct <- 100 * mean(tissue_summary$tissue_correct)
    final_summary <- data.frame(
        n_tissues = nrow(tissue_summary),
        n_tissues_correct = sum(tissue_summary$tissue_correct),
        pct_tissue_correct = final_pct_tissue_correct,
        stringsAsFactors = FALSE
    )

    write.csv(detail, file.path(out_dir, 'gtex_global_alignment_detail.csv'), row.names = FALSE)
    write.csv(tissue_summary, file.path(out_dir, 'gtex_global_alignment_summary.csv'), row.names = FALSE)
    write.csv(final_summary, file.path(out_dir, 'gtex_global_alignment_final_pct.csv'), row.names = FALSE)

    list(detail = detail, tissue_summary = tissue_summary, final_summary = final_summary)
}

results <- lapply(names(selections), function(nm) {
    run_alignment_summary(selections[[nm]], ora_all, file.path(OUT_DIR, nm))
})
names(results) <- names(selections)

dplyr::bind_rows(lapply(names(results), function(nm) {
    results[[nm]]$final_summary %>% dplyr::mutate(analysis = nm, .before = 1)
}))

  analysis     n_tissues n_tissues_correct pct_tissue_correct
1 top1         49        44                 89.79592
2 cumulative20 49        49                100.00000

In [9]:
cat('--- top1 ---\n')
results$top1$tissue_summary %>% dplyr::arrange(Tissue)

cat('--- cumulative20 ---\n')
results$cumulative20$tissue_summary %>% dplyr::arrange(Tissue)

--- top1 ---

   Tissue                                    n_selected_lvs tissue_correct
1  Adipose - Subcutaneous                    1              FALSE
2  Adipose - Visceral (Omentum)              1               TRUE
3  Adrenal Gland                             1               TRUE
4  Artery - Aorta                            1               TRUE
5  Artery - Coronary                         1               TRUE
6  Artery - Tibial                           1               TRUE
7  Brain - Amygdala                          1               TRUE
8  Brain - Anterior cingulate cortex (BA24)  1               TRUE
9  Brain - Caudate (basal ganglia)           1               TRUE
10 Brain - Cerebellar Hemisphere             1               TRUE
11 Brain - Cerebellum                        1               TRUE
12 Brain - Cortex                            1               TRUE
13 Brain - Frontal Cortex (BA9)              1               TRUE
14 Brain - Hippocampus                       1               TRUE
15 Brain - Hypothalamus                      1               TRUE
16 Brain - Nucleus accumbens (basal ganglia) 1               TRUE
17 Brain - Putamen (basal ganglia)           1              FALSE
18 Brain - Spinal cord (cervical c-1)        1               TRUE
19 Brain - Substantia nigra                  1              FALSE
20 Breast - Mammary Tissue                   1               TRUE
21 Cells - Cultured fibroblasts              1               TRUE
22 Cells - EBV-transformed lymphocytes       1              FALSE
23 Colon - Sigmoid                           1               TRUE
24 Colon - Transverse                        1               TRUE
25 Esophagus - Gastroesophageal Junction     1               TRUE
26 Esophagus - Mucosa                        1               TRUE
27 Esophagus - Muscularis                    1               TRUE
28 Heart - Atrial Appendage                  1               TRUE
29 Heart - Left Ventricle                    1              FALSE
30 Kidney - Cortex                           1               TRUE
31 Liver                                     1               TRUE
32 Lung                                      1               TRUE
33 Minor Salivary Gland                      1               TRUE
34 Muscle - Skeletal                         1               TRUE
35 Nerve - Tibial                            1               TRUE
36 Ovary                                     1               TRUE
37 Pancreas                                  1               TRUE
38 Pituitary                                 1               TRUE
39 Prostate                                  1               TRUE
40 Skin - Not Sun Exposed (Suprapubic)       1               TRUE
41 Skin - Sun Exposed (Lower leg)            1               TRUE
42 Small Intestine - Terminal Ileum          1               TRUE
43 Spleen                                    1               TRUE
44 Stomach                                   1               TRUE
45 Testis                                    1               TRUE
46 Thyroid                                   1               TRUE
47 Uterus                                    1               TRUE
48 Vagina                                    1               TRUE
49 Whole Blood                               1               TRUE
   correct_lvs best_true_padj correct_score
1                         NA  0
2  LV220        1.578545e-34  1
3  LV183        4.049995e-86  1
4  LV399        2.801338e-27  1
5  LV483        1.133172e-10  1
6  LV90         1.292037e-10  1
7  LV136        5.078782e-14  1
8  LV121        4.572279e-52  1
9  LV259        5.644900e-05  1
10 LV389        1.156880e-52  1
11 LV389        5.234408e-48  1
12 LV22         1.984337e-15  1
13 LV22         1.216221e-21  1
14 LV121        4.731045e-63  1
15 LV184        8.726080e-37  1
16 LV494        8.894362e-17  1
17                        NA  0
18 LV496        6.485822e-44  1
19                        NA  0
20 LV554        3.574186e-07  1
21 LV570        1.346694e-38  1
22                        NA  0
23 LV11         8.485414e-32  1
24 LV11         4.494335e-18  1
25 LV182        4.575973e-13  1
26 LV84         7.432571e-99  1
27 LV313        2.802516e-19  1
28 LV282        4.128281e-32  1
29                        NA  0
30 LV229        1.481039e-37  1
31 LV21         4.043843e-68  1
32 LV322        3.759660e-58  1
33 LV58         6.307500e-59  1
34 LV397        5.312434e-81  1
35 LV329        6.721358e-76  1
36 LV32         5.430985e-54  1
37 LV450       2.841630e-104  1
38 LV62         9.893213e-61  1
39 LV152        2.172376e-28  1
40 LV546        1.638498e-83  1
41 LV546       2.215627e-115  1
42 LV452        1.751672e-49  1
43 LV55         1.247383e-43  1
44 LV103        1.663809e-14  1
45 LV299        7.600774e-37  1
46 LV246        1.135523e-89  1
47 LV48         8.653333e-65  1
48 LV80         2.827458e-38  1
49 LV90         3.793304e-07  1

--- cumulative20 ---

   Tissue                                    n_selected_lvs tissue_correct
1  Adipose - Subcutaneous                    3              TRUE
2  Adipose - Visceral (Omentum)              4              TRUE
3  Adrenal Gland                             1              TRUE
4  Artery - Aorta                            2              TRUE
5  Artery - Coronary                         2              TRUE
6  Artery - Tibial                           4              TRUE
7  Brain - Amygdala                          3              TRUE
8  Brain - Anterior cingulate cortex (BA24)  6              TRUE
9  Brain - Caudate (basal ganglia)           5              TRUE
10 Brain - Cerebellar Hemisphere             7              TRUE
11 Brain - Cerebellum                        6              TRUE
12 Brain - Cortex                            3              TRUE
13 Brain - Frontal Cortex (BA9)              5              TRUE
14 Brain - Hippocampus                       4              TRUE
15 Brain - Hypothalamus                      4              TRUE
16 Brain - Nucleus accumbens (basal ganglia) 4              TRUE
17 Brain - Putamen (basal ganglia)           5              TRUE
18 Brain - Spinal cord (cervical c-1)        3              TRUE
19 Brain - Substantia nigra                  3              TRUE
20 Breast - Mammary Tissue                   4              TRUE
21 Cells - Cultured fibroblasts              2              TRUE
22 Cells - EBV-transformed lymphocytes       3              TRUE
23 Colon - Sigmoid                           2              TRUE
24 Colon - Transverse                        4              TRUE
25 Esophagus - Gastroesophageal Junction     4              TRUE
26 Esophagus - Mucosa                        3              TRUE
27 Esophagus - Muscularis                    3              TRUE
28 Heart - Atrial Appendage                  2              TRUE
29 Heart - Left Ventricle                    5              TRUE
30 Kidney - Cortex                           2              TRUE
31 Liver                                     3              TRUE
32 Lung                                      1              TRUE
33 Minor Salivary Gland                      3              TRUE
34 Muscle - Skeletal                         3              TRUE
35 Nerve - Tibial                            1              TRUE
36 Ovary                                     4              TRUE
37 Pancreas                                  2              TRUE
38 Pituitary                                 4              TRUE
39 Prostate                                  3              TRUE
40 Skin - Not Sun Exposed (Suprapubic)       4              TRUE
41 Skin - Sun Exposed (Lower leg)            3              TRUE
42 Small Intestine - Terminal Ileum          3              TRUE
43 Spleen                                    3              TRUE
44 Stomach                                   3              TRUE
45 Testis                                    3              TRUE
46 Thyroid                                   1              TRUE
47 Uterus                                    3              TRUE
48 Vagina                                    3              TRUE
49 Whole Blood                               4              TRUE
   correct_lvs                            best_true_padj correct_score
1  LV106;LV220;LV520                       6.756594e-61  1
2  LV220;LV376;LV232;LV151                 1.578545e-34  1
3  LV183                                   4.049995e-86  1
4  LV399;LV145                             2.801338e-27  1
5  LV483;LV99                              1.133172e-10  1
6  LV90;LV387;LV137;LV106                  7.636601e-30  1
7  LV136;LV121;LV347                       1.013570e-41  1
8  LV121;LV2;LV22;LV47;LV164;LV251         4.572279e-52  1
9  LV259;LV34;LV328;LV230;LV54             3.340111e-59  1
10 LV389;LV445;LV347;LV62;LV2;LV230;LV368  1.156880e-52  1
11 LV389;LV230;LV213;LV19;LV2;LV164        5.234408e-48  1
12 LV22;LV2;LV121                          1.222369e-27  1
13 LV22;LV2;LV164;LV295;LV121              4.116273e-46  1
14 LV121;LV251;LV34;LV417                  1.446959e-63  1
15 LV184;LV34;LV155;LV277                  8.726080e-37  1
16 LV494;LV54;LV328;LV119                  8.894362e-17  1
17 LV164;LV34;LV259;LV230;LV328            8.005690e-61  1
18 LV496;LV257;LV29                        1.598806e-50  1
19 LV6;LV257;LV368                         4.259450e-17  1
20 LV554;LV31;LV505;LV220                  9.636064e-40  1
21 LV570;LV91                              1.346694e-38  1
22 LV142;LV105;LV21                        1.124981e-23  1
23 LV11;LV105                              5.794298e-34  1
24 LV11;LV237;LV562;LV105                  5.765299e-66  1
25 LV182;LV105;LV18;LV142                  1.960983e-28  1
26 LV84;LV81;LV546                         7.432571e-99  1
27 LV313;LV42;LV18                         2.449964e-21  1
28 LV282;LV420                             1.680917e-62  1
29 LV554;LV505;LV483;LV93;LV317            2.406288e-65  1
30 LV229;LV50                              4.136059e-78  1
31 LV21;LV471;LV310                        4.043843e-68  1
32 LV322                                   3.759660e-58  1
33 LV58;LV138;LV513                        1.687891e-69  1
34 LV397;LV68;LV547                        5.312434e-81  1
35 LV329                                   6.721358e-76  1
36 LV32;LV277;LV217;LV183                  5.430985e-54  1
37 LV450;LV117                            2.841630e-104  1
38 LV62;LV155;LV217;LV230                  9.893213e-61  1
39 LV152;LV559;LV38                        8.553147e-70  1
40 LV546;LV31;LV137;LV554                  1.638498e-83  1
41 LV546;LV31;LV266                       2.215627e-115  1
42 LV452;LV562;LV532                       1.751672e-49  1
43 LV55;LV18;LV26                          1.247383e-43  1
44 LV103;LV227;LV36                        6.067611e-86  1
45 LV299;LV116;LV277                       7.600774e-37  1
46 LV246                                   1.135523e-89  1
47 LV48;LV217;LV277                        8.653333e-65  1
48 LV80;LV569;LV414                        2.827458e-38  1
49 LV90;LV137;LV546;LV74                   3.793304e-07  1

In [10]:
detail_cols <- c('Tissue', 'LV', 'Rank', 'Mean_SHAP_Tissue', 'Cumulative_Percent',
                 'tissue_correct', 'n_sig_terms', 'n_true_terms',
                 'best_true_padj', 'matched_terms')

cat('--- top1 ---\n')
results$top1$detail %>% dplyr::select(dplyr::all_of(detail_cols)) %>% dplyr::arrange(Tissue, Rank)

cat('--- cumulative20 ---\n')
results$cumulative20$detail %>% dplyr::select(dplyr::all_of(detail_cols)) %>% dplyr::arrange(Tissue, Rank)

--- top1 ---

   Tissue                                    LV    Rank Mean_SHAP_Tissue
1  Adipose - Subcutaneous                    LV106 1    0.08297700
2  Adipose - Visceral (Omentum)              LV220 1    0.08320094
3  Adrenal Gland                             LV183 1    0.21479493
4  Artery - Aorta                            LV399 1    0.12070728
5  Artery - Coronary                         LV483 1    0.13880456
6  Artery - Tibial                           LV90  1    0.07482360
7  Brain - Amygdala                          LV136 1    0.10087884
8  Brain - Anterior cingulate cortex (BA24)  LV121 1    0.05415220
9  Brain - Caudate (basal ganglia)           LV259 1    0.05524183
10 Brain - Cerebellar Hemisphere             LV389 1    0.04959234
11 Brain - Cerebellum                        LV389 1    0.07632043
12 Brain - Cortex                            LV22  1    0.09476937
13 Brain - Frontal Cortex (BA9)              LV22  1    0.06703621
14 Brain - Hippocampus                       LV121 1    0.07189402
15 Brain - Hypothalamus                      LV184 1    0.09962887
16 Brain - Nucleus accumbens (basal ganglia) LV494 1    0.08317726
17 Brain - Putamen (basal ganglia)           LV164 1    0.05082445
18 Brain - Spinal cord (cervical c-1)        LV496 1    0.11037311
19 Brain - Substantia nigra                  LV6   1    0.06709828
20 Breast - Mammary Tissue                   LV554 1    0.07930464
21 Cells - Cultured fibroblasts              LV570 1    0.12334459
22 Cells - EBV-transformed lymphocytes       LV142 1    0.08833621
23 Colon - Sigmoid                           LV11  1    0.12646564
24 Colon - Transverse                        LV11  1    0.06231253
25 Esophagus - Gastroesophageal Junction     LV182 1    0.05654706
26 Esophagus - Mucosa                        LV84  1    0.12202082
27 Esophagus - Muscularis                    LV313 1    0.07554639
28 Heart - Atrial Appendage                  LV282 1    0.13358499
29 Heart - Left Ventricle                    LV554 1    0.05088358
30 Kidney - Cortex                           LV229 1    0.14802262
31 Liver                                     LV21  1    0.08686550
32 Lung                                      LV322 1    0.21779324
33 Minor Salivary Gland                      LV58  1    0.07666463
34 Muscle - Skeletal                         LV397 1    0.07619992
35 Nerve - Tibial                            LV329 1    0.19729517
36 Ovary                                     LV32  1    0.07240775
37 Pancreas                                  LV450 1    0.13427418
38 Pituitary                                 LV62  1    0.09903649
39 Prostate                                  LV152 1    0.07383411
40 Skin - Not Sun Exposed (Suprapubic)       LV546 1    0.08968989
41 Skin - Sun Exposed (Lower leg)            LV546 1    0.10785720
42 Small Intestine - Terminal Ileum          LV452 1    0.10781809
43 Spleen                                    LV55  1    0.14066651
44 Stomach                                   LV103 1    0.10647289
45 Testis                                    LV299 1    0.11971299
46 Thyroid                                   LV246 1    0.23580972
47 Uterus                                    LV48  1    0.13179926
48 Vagina                                    LV80  1    0.07775978
49 Whole Blood                               LV90  1    0.05518846
   Cumulative_Percent tissue_correct n_sig_terms n_true_terms best_true_padj
1   9.240699          FALSE           8           0                      NA
2   9.253505           TRUE          33          12            1.578545e-34
3  22.414026           TRUE          20          11            4.049995e-86
4  12.812897           TRUE          21          12            2.801338e-27
5  15.127286           TRUE          32          10            1.133172e-10
6   7.958792           TRUE          46          12            1.292037e-10
7  11.161219           TRUE          42           7            5.078782e-14
8   6.101230           TRUE          64           9            4.572279e-52
9   6.170261           TRUE          60          10            5.644900e-05
10  5.390098           TRUE          20          10            1.156880e-52
11  8.129564           TRUE          20          10            5.234408e-48
12 10.284313           TRUE          25          11            1.984337e-15
13  7.559230           TRUE          25           8            1.216221e-21
14  8.107549           TRUE          64          10            4.731045e-63
15 11.249658           TRUE          39           9            8.726080e-37
16  9.418685           TRUE          45          11            8.894362e-17
17  5.691996          FALSE           5           0                      NA
18 11.888041           TRUE          10           8            6.485822e-44
19  7.551413          FALSE           4           0                      NA
20  9.129516           TRUE          45          11            3.574186e-07
21 12.799972           TRUE          12          12            1.346694e-38
22  8.873437          FALSE          45           0                      NA
23 14.593568           TRUE          28          12            8.485414e-32
24  7.332645           TRUE          28           3            4.494335e-18
25  6.498955           TRUE          48          11            4.575973e-13
26 12.675062           TRUE          22          12            7.432571e-99
27  8.242933           TRUE          27          12            2.802516e-19
28 13.961931           TRUE          36          12            4.128281e-32
29  5.313542          FALSE          45           0                      NA
30 15.920953           TRUE          17           7            1.481039e-37
31  8.897821           TRUE          21          11            4.043843e-68
32 22.993935           TRUE          20          12            3.759660e-58
33  8.284253           TRUE          30          10            6.307500e-59
34  7.969565           TRUE          31          12            5.312434e-81
35 20.845029           TRUE          28          12            6.721358e-76
36  7.561745           TRUE          15           6            5.430985e-54
37 14.085786           TRUE          27          11           2.841630e-104
38 10.138808           TRUE          11          11            9.893213e-61
39  7.891366           TRUE           9           6            2.172376e-28
40 10.371886           TRUE          36          12            1.638498e-83
41 12.365092           TRUE          36          12           2.215627e-115
42 11.888243           TRUE          54          10            1.751672e-49
43 14.558135           TRUE          24          11            1.247383e-43
44 11.615583           TRUE          23          11            1.663809e-14
45 12.228708           TRUE           6           6            7.600774e-37
46 26.467839           TRUE          13          12            1.135523e-89
47 14.378007           TRUE          12           5            8.653333e-65
48  8.815584           TRUE          47           6            2.827458e-38
49  5.822433           TRUE          46          11            3.793304e-07
   matched_terms
1
2  GTEx_Tissues_Adipose - Visceral (Omentum) Male 40-49 Up | GTEx_Tissues_Adipose - Visceral (Omentum) Male 50-59 Up | GTEx_Tissues_Adipose - Visceral (Omentum) Female 50-59 Up | GTEx_Tissues_Adipose - Visceral (Omentum) Female 20-29 Up | GTEx_Tissues_Adipose - Visceral (Omentum) Female 30-39 Up | GTEx_Tissues_Adipose - Visceral (Omentum) Male 30-39 Up | GTEx_Tissues_Adipose - Visceral (Omentum) Female 40-49 Up | GTEx_Tissues_Adipose - Visceral (Omentum) Male 60-69 Up | GTEx_Tissues_Adipose - Visceral (Omentum) Female 70-79 Up | GTEx_Tissues_Adipose - Visceral (Omentum) Male 70-79 Up | GTEx_Tissues_Adipose - Visceral (Omentum) Female 60-69 Up | GTEx_Tissues_Adipose - Visceral (Omentum) Male 20-29 Up
3  GTEx_Tissues_Adrenal Gland Male 20-29 Up | GTEx_Tissues_Adrenal Gland Male 50-59 Up | GTEx_Tissues_Adrenal Gland Female 50-59 Up | GTEx_Tissues_Adrenal Gland Male 40-49 Up | GTEx_Tissues_Adrenal Gland Male 60-69 Up | GTEx_Tissues_Adrenal Gland Female 40-49 Up | GTEx_Tissues_Adrenal Gland Male 30-39 Up | GTEx_Tissues_Adrenal Gland Female 30-39 Up | GTEx_Tissues_Adrenal Gland Female 20-29 Up | GTEx_Tissues_Adrenal Gland Female 60-69 Up | GTEx_Tissues_Adrenal Gland Male 70-79 Up
4  GTEx_Tissues_Artery - Aorta Female 60-69 Up | GTEx_Tissues_Artery - Aorta Male 70-79 Up | GTEx_Tissues_Artery - Aorta Male 40-49 Up | GTEx_Tissues_Artery - Aorta Male 30-39 Up | GTEx_Tissues_Artery - Aorta Male 60-69 Up | GTEx_Tissues_Artery - Aorta Male 50-59 Up | GTEx_Tissues_Artery - Aorta Female 50-59 Up | GTEx_Tissues_Artery - Aorta Female 30-39 Up | GTEx_Tissues_Artery - Aorta Female 40-49 Up | GTEx_Tissues_Artery - Aorta Female 20-29 Up | GTEx_Tissues_Artery - Aorta Female 70-79 Up | GTEx_Tissues_Artery - Aorta Male 20-29 Up
5  GTEx_Tissues_Artery - Coronary Male 50-59 Up | GTEx_Tissues_Artery - Coronary Male 60-69 Up | GTEx_Tissues_Artery - Coronary Male 40-49 Up | GTEx_Tissues_Artery - Coronary Female 60-69 Up | GTEx_Tissues_Artery - Coronary Female 50-59 Up | GTEx_Tissues_Artery - Coronary Female 20-29 Up | GTEx_Tissues_Artery - Coronary Female 40-49 Up | GTEx_Tissues_Artery - Coronary Male 70-79 Up | GTEx_Tissues_Artery - Coronary Male 20-29 Up | GTEx_Tissues_Artery - Coronary Male 30-39 Up
6  GTEx_Tissues_Artery - Tibial Female 50-59 Up | GTEx_Tissues_Artery - Tibial Male 40-49 Up | GTEx_Tissues_Artery - Tibial Male 50-59 Up | GTEx_Tissues_Artery - Tibial Female 60-69 Up | GTEx_Tissues_Artery - Tibial Female 70-79 Up | GTEx_Tissues_Artery - Tibial Male 60-69 Up | GTEx_Tissues_Artery - Tibial Female 40-49 Up | GTEx_Tissues_Artery - Tibial Male 70-79 Up | GTEx_Tissues_Artery - Tibial Male 30-39 Up | GTEx_Tissues_Artery - Tibial Female 30-39 Up | GTEx_Tissues_Artery - Tibial Male 20-29 Up | GTEx_Tissues_Artery - Tibial Female 20-29 Up
7  GTEx_Tissues_Brain - Amygdala Female 40-49 Up | GTEx_Tissues_Brain - Amygdala Male 40-49 Up | GTEx_Tissues_Brain - Amygdala Female 60-69 Up | GTEx_Tissues_Brain - Amygdala Male 20-29 Up | GTEx_Tissues_Brain - Amygdala Male 50-59 Up | GTEx_Tissues_Brain - Amygdala Male 60-69 Up | GTEx_Tissues_Brain - Amygdala Male 70-79 Up
8  GTEx_Tissues_Brain - Anterior Cingulate Cortex (BA24) Male 50-59 Up | GTEx_Tissues_Brain - Anterior Cingulate Cortex (BA24) Male 70-79 Up | GTEx_Tissues_Brain - Anterior Cingulate Cortex (BA24) Male 60-69 Up | GTEx_Tissues_Brain - Anterior Cingulate Cortex (BA24) Female 50-59 Up | GTEx_Tissues_Brain - Anterior Cingulate Cortex (BA24) Female 20-29 Up | GTEx_Tissues_Brain - Anterior Cingulate Cortex (BA24) Male 40-49 Up | GTEx_Tissues_Brain - Anterior Cingulate Cortex (BA24) Female 40-49 Up | GTEx_Tissues_Brain - Anterior Cingulate Cortex (BA24) Female 60-69 Up | GTEx_Tissues_Brain - Anterior Cingulate Cortex (BA24) Male 30-39 Up
9  GTEx_Tissues_Brain - Caudate (Basal Ganglia) Female 20-29 Up | GTEx_Tissues_Brain - Caudate (Basal Ganglia) Male 50-59 Up | GTEx_Tissues_Brain - Caudate (Basal Ganglia) Male 40-49 Up | GTEx_Tissues_Brain - Caudate (Basal Ganglia) Female 70-79 Up | GTEx_Tissues_Brain - Caudate (Basal Ganglia) Male 30-39 Up | GTEx_Tissues_Brain - Caudate (Basal Ganglia) Female 50-59 Up | GTEx_Tissues_Brain - Caudate (Basal Ganglia) Female 60-69 Up | GTEx_Tissues_Brain - Caudate (Basal Ganglia) Female 40-49 Up | GTEx_Tissues_Brain - Caudate (Basal Ganglia) Male 70-79 Up | GTEx_Tissues_Brain - Caudate (Basal Ganglia) Male 60-69 Up
10 GTEx_Tissues_Brain - Cerebellar Hemisphere Male 70-79 Up | GTEx_Tissues_Brain - Cerebellar Hemisphere Male 60-69 Up | GTEx_Tissues_Brain - Cerebellar Hemisphere Female 60-69 Up | GTEx_Tissues_Brain - Cerebellar Hemisphere Male 50-59 Up | GTEx_Tissues_Brain - Cerebellar Hemisphere Male 40-49 Up | GTEx_Tissues_Brain - Cerebellar Hemisphere Female 40-49 Up | GTEx_Tissues_Brain - Cerebellar Hemisphere Female 50-59 Up | GTEx_Tissues_Brain - Cerebellar Hemisphere Female 20-29 Up | GTEx_Tissues_Brain - Cerebellar Hemisphere Male 30-39 Up | GTEx_Tissues_Brain - Cerebellar Hemisphere Male 20-29 Up
11 GTEx_Tissues_Brain - Cerebellum Female 30-39 Up | GTEx_Tissues_Brain - Cerebellum Male 50-59 Up | GTEx_Tissues_Brain - Cerebellum Male 40-49 Up | GTEx_Tissues_Brain - Cerebellum Male 20-29 Up | GTEx_Tissues_Brain - Cerebellum Male 60-69 Up | GTEx_Tissues_Brain - Cerebellum Female 40-49 Up | GTEx_Tissues_Brain - Cerebellum Male 70-79 Up | GTEx_Tissues_Brain - Cerebellum Male 30-39 Up | GTEx_Tissues_Brain - Cerebellum Female 50-59 Up | GTEx_Tissues_Brain - Cerebellum Female 60-69 Up
12 GTEx_Tissues_Brain - Cortex Male 30-39 Up | GTEx_Tissues_Brain - Cortex Male 40-49 Up | GTEx_Tissues_Brain - Cortex Female 20-29 Up | GTEx_Tissues_Brain - Cortex Male 50-59 Up | GTEx_Tissues_Brain - Cortex Female 50-59 Up | GTEx_Tissues_Brain - Cortex Male 20-29 Up | GTEx_Tissues_Brain - Cortex Female 60-69 Up | GTEx_Tissues_Brain - Cortex Male 70-79 Up | GTEx_Tissues_Brain - Cortex Male 60-69 Up | GTEx_Tissues_Brain - Cortex Female 40-49 Up | GTEx_Tissues_Brain - Cortex Female 70-79 Up
13 GTEx_Tissues_Brain - Frontal Cortex (BA9) Male 40-49 Up | GTEx_Tissues_Brain - Frontal Cortex (BA9) Male 60-69 Up | GTEx_Tissues_Brain - Frontal Cortex (BA9) Female 50-59 Up | GTEx_Tissues_Brain - Frontal Cortex (BA9) Male 50-59 Up | GTEx_Tissues_Brain - Frontal Cortex (BA9) Male 70-79 Up | GTEx_Tissues_Brain - Frontal Cortex (BA9) Female 40-49 Up | GTEx_Tissues_Brain - Frontal Cortex (BA9) Female 60-69 Up | GTEx_Tissues_Brain - Frontal Cortex (BA9) Male 20-29 Up
14 GTEx_Tissues_Brain - Hippocampus Male 30-39 Up | GTEx_Tissues_Brain - Hippocampus Female 50-59 Up | GTEx_Tissues_Brain - Hippocampus Male 50-59 Up | GTEx_Tissues_Brain - Hippocampus Female 40-49 Up | GTEx_Tissues_Brain - Hippocampus Male 40-49 Up | GTEx_Tissues_Brain - Hippocampus Male 20-29 Up | GTEx_Tissues_Brain - Hippocampus Male 60-69 Up | GTEx_Tissues_Brain - Hippocampus Female 70-79 Up | GTEx_Tissues_Brain - Hippocampus Male 70-79 Up | GTEx_Tissues_Brain - Hippocampus Female 60-69 Up
15 GTEx_Tissues_Brain - Hypothalamus Male 50-59 Up | GTEx_Tissues_Brain - Hypothalamus Male 60-69 Up | GTEx_Tissues_Brain - Hypothalamus Male 40-49 Up | GTEx_Tissues_Brain - Hypothalamus Female 60-69 Up | GTEx_Tissues_Brain - Hypothalamus Male 70-79 Up | GTEx_Tissues_Brain - Hypothalamus Female 50-59 Up | GTEx_Tissues_Brain - Hypothalamus Male 30-39 Up | GTEx_Tissues_Brain - Hypothalamus Female 40-49 Up | GTEx_Tissues_Brain - Hypothalamus Male 20-29 Up
16 GTEx_Tissues_Brain - Nucleus Accumbens (Basal Ganglia) Male 50-59 Up | GTEx_Tissues_Brain - Nucleus Accumbens (Basal Ganglia) Female 40-49 Up | GTEx_Tissues_Brain - Nucleus Accumbens (Basal Ganglia) Male 60-69 Up | GTEx_Tissues_Brain - Nucleus Accumbens (Basal Ganglia) Female 50-59 Up | GTEx_Tissues_Brain - Nucleus Accumbens (Basal Ganglia) Male 70-79 Up | GTEx_Tissues_Brain - Nucleus Accumbens (Basal Ganglia) Male 40-49 Up | GTEx_Tissues_Brain - Nucleus Accumbens (Basal Ganglia) Female 60-69 Up | GTEx_Tissues_Brain - Nucleus Accumbens (Basal Ganglia) Female 70-79 Up | GTEx_Tissues_Brain - Nucleus Accumbens (Basal Ganglia) Male 30-39 Up | GTEx_Tissues_Brain - Nucleus Accumbens (Basal Ganglia) Female 20-29 Up | GTEx_Tissues_Brain - Nucleus Accumbens (Basal Ganglia) Male 20-29 Up
17
18 GTEx_Tissues_Brain - Spinal Cord (Cervical C-1) Male 20-29 Up | GTEx_Tissues_Brain - Spinal Cord (Cervical C-1) Male 70-79 Up | GTEx_Tissues_Brain - Spinal Cord (Cervical C-1) Male 50-59 Up | GTEx_Tissues_Brain - Spinal Cord (Cervical C-1) Female 50-59 Up | GTEx_Tissues_Brain - Spinal Cord (Cervical C-1) Female 40-49 Up | GTEx_Tissues_Brain - Spinal Cord (Cervical C-1) Male 60-69 Up | GTEx_Tissues_Brain - Spinal Cord (Cervical C-1) Female 60-69 Up | GTEx_Tissues_Brain - Spinal Cord (Cervical C-1) Male 40-49 Up
19
20 GTEx_Tissues_Breast - Mammary Tissue Male 30-39 Up | GTEx_Tissues_Breast - Mammary Tissue Male 70-79 Up | GTEx_Tissues_Breast - Mammary Tissue Male 40-49 Up | GTEx_Tissues_Breast - Mammary Tissue Female 30-39 Up | GTEx_Tissues_Breast - Mammary Tissue Male 50-59 Up | GTEx_Tissues_Breast - Mammary Tissue Male 60-69 Up | GTEx_Tissues_Breast - Mammary Tissue Female 50-59 Up | GTEx_Tissues_Breast - Mammary Tissue Female 60-69 Up | GTEx_Tissues_Breast - Mammary Tissue Female 20-29 Up | GTEx_Tissues_Breast - Mammary Tissue Female 40-49 Up | GTEx_Tissues_Breast - Mammary Tissue Male 20-29 Up
21 GTEx_Tissues_Cells - Cultured Fibroblasts Male 50-59 Up | GTEx_Tissues_Cells - Cultured Fibroblasts Male 60-69 Up | GTEx_Tissues_Cells - Cultured Fibroblasts Female 40-49 Up | GTEx_Tissues_Cells - Cultured Fibroblasts Female 50-59 Up | GTEx_Tissues_Cells - Cultured Fibroblasts Male 20-29 Up | GTEx_Tissues_Cells - Cultured Fibroblasts Female 60-69 Up | GTEx_Tissues_Cells - Cultured Fibroblasts Male 40-49 Up | GTEx_Tissues_Cells - Cultured Fibroblasts Female 30-39 Up | GTEx_Tissues_Cells - Cultured Fibroblasts Male 70-79 Up | GTEx_Tissues_Cells - Cultured Fibroblasts Male 30-39 Up | GTEx_Tissues_Cells - Cultured Fibroblasts Female 20-29 Up | GTEx_Tissues_Cells - Cultured Fibroblasts Female 70-79 Up
22
23 GTEx_Tissues_Colon - Sigmoid Female 40-49 Up | GTEx_Tissues_Colon - Sigmoid Male 40-49 Up | GTEx_Tissues_Colon - Sigmoid Male 50-59 Up | GTEx_Tissues_Colon - Sigmoid Female 50-59 Up | GTEx_Tissues_Colon - Sigmoid Female 60-69 Up | GTEx_Tissues_Colon - Sigmoid Male 30-39 Up | GTEx_Tissues_Colon - Sigmoid Male 20-29 Up | GTEx_Tissues_Colon - Sigmoid Female 20-29 Up | GTEx_Tissues_Colon - Sigmoid Female 30-39 Up | GTEx_Tissues_Colon - Sigmoid Male 60-69 Up | GTEx_Tissues_Colon - Sigmoid Female 70-79 Up | GTEx_Tissues_Colon - Sigmoid Male 70-79 Up
24 GTEx_Tissues_Colon - Transverse Male 70-79 Up | GTEx_Tissues_Colon - Transverse Female 60-69 Up | GTEx_Tissues_Colon - Transverse Male 60-69 Up
25 GTEx_Tissues_Esophagus - Gastroesophageal Junction Male 30-39 Up | GTEx_Tissues_Esophagus - Gastroesophageal Junction Male 60-69 Up | GTEx_Tissues_Esophagus - Gastroesophageal Junction Female 30-39 Up | GTEx_Tissues_Esophagus - Gastroesophageal Junction Male 20-29 Up | GTEx_Tissues_Esophagus - Gastroesophageal Junction Female 50-59 Up | GTEx_Tissues_Esophagus - Gastroesophageal Junction Female 60-69 Up | GTEx_Tissues_Esophagus - Gastroesophageal Junction Male 40-49 Up | GTEx_Tissues_Esophagus - Gastroesophageal Junction Male 50-59 Up | GTEx_Tissues_Esophagus - Gastroesophageal Junction Female 20-29 Up | GTEx_Tissues_Esophagus - Gastroesophageal Junction Female 40-49 Up | GTEx_Tissues_Esophagus - Gastroesophageal Junction Male 70-79 Up
26 GTEx_Tissues_Esophagus - Mucosa Male 40-49 Up | GTEx_Tissues_Esophagus - Mucosa Male 30-39 Up | GTEx_Tissues_Esophagus - Mucosa Male 50-59 Up | GTEx_Tissues_Esophagus - Mucosa Male 20-29 Up | GTEx_Tissues_Esophagus - Mucosa Female 40-49 Up | GTEx_Tissues_Esophagus - Mucosa Female 50-59 Up | GTEx_Tissues_Esophagus - Mucosa Female 20-29 Up | GTEx_Tissues_Esophagus - Mucosa Female 30-39 Up | GTEx_Tissues_Esophagus - Mucosa Female 60-69 Up | GTEx_Tissues_Esophagus - Mucosa Male 60-69 Up | GTEx_Tissues_Esophagus - Mucosa Female 70-79 Up | GTEx_Tissues_Esophagus - Mucosa Male 70-79 Up
27 GTEx_Tissues_Esophagus - Muscularis Male 30-39 Up | GTEx_Tissues_Esophagus - Muscularis Female 20-29 Up | GTEx_Tissues_Esophagus - Muscularis Male 40-49 Up | GTEx_Tissues_Esophagus - Muscularis Male 50-59 Up | GTEx_Tissues_Esophagus - Muscularis Female 40-49 Up | GTEx_Tissues_Esophagus - Muscularis Male 20-29 Up | GTEx_Tissues_Esophagus - Muscularis Female 50-59 Up | GTEx_Tissues_Esophagus - Muscularis Male 60-69 Up | GTEx_Tissues_Esophagus - Muscularis Female 30-39 Up | GTEx_Tissues_Esophagus - Muscularis Female 60-69 Up | GTEx_Tissues_Esophagus - Muscularis Female 70-79 Up | GTEx_Tissues_Esophagus - Muscularis Male 70-79 Up

--- cumulative20 ---

    Tissue                                   LV    Rank Mean_SHAP_Tissue
1   Adipose - Subcutaneous                   LV106 1    0.08297700
2   Adipose - Subcutaneous                   LV220 2    0.07691917
3   Adipose - Subcutaneous                   LV520 3    0.04706092
4   Adipose - Visceral (Omentum)             LV220 1    0.08320094
5   Adipose - Visceral (Omentum)             LV376 2    0.04557763
6   Adipose - Visceral (Omentum)             LV232 3    0.04163666
7   Adipose - Visceral (Omentum)             LV151 4    0.03354934
8   Adrenal Gland                            LV183 1    0.21479493
9   Artery - Aorta                           LV399 1    0.12070728
10  Artery - Aorta                           LV145 2    0.09965764
11  Artery - Coronary                        LV483 1    0.13880456
12  Artery - Coronary                        LV99  2    0.05013709
13  Artery - Tibial                          LV90  1    0.07482360
14  Artery - Tibial                          LV387 2    0.05132921
15  Artery - Tibial                          LV137 3    0.04920071
16  Artery - Tibial                          LV106 4    0.04688259
17  Brain - Amygdala                         LV136 1    0.10087884
18  Brain - Amygdala                         LV121 2    0.06225702
19  Brain - Amygdala                         LV347 3    0.02698447
20  Brain - Anterior cingulate cortex (BA24) LV121 1    0.05415220
21  Brain - Anterior cingulate cortex (BA24) LV2   2    0.03911948
22  Brain - Anterior cingulate cortex (BA24) LV22  3    0.02939107
23  Brain - Anterior cingulate cortex (BA24) LV47  4    0.02579608
24  Brain - Anterior cingulate cortex (BA24) LV164 5    0.02529928
25  Brain - Anterior cingulate cortex (BA24) LV251 6    0.02456051
26  Brain - Caudate (basal ganglia)          LV259 1    0.05524183
27  Brain - Caudate (basal ganglia)          LV34  2    0.04852975
28  Brain - Caudate (basal ganglia)          LV328 3    0.03882455
29  Brain - Caudate (basal ganglia)          LV230 4    0.02545007
30  Brain - Caudate (basal ganglia)          LV54  5    0.02466452
⋮   ⋮                                        ⋮     ⋮    ⋮
133 Skin - Not Sun Exposed (Suprapubic)      LV546 1    0.08968989
134 Skin - Not Sun Exposed (Suprapubic)      LV31  2    0.05305145
135 Skin - Not Sun Exposed (Suprapubic)      LV137 3    0.02679481
136 Skin - Not Sun Exposed (Suprapubic)      LV554 4    0.02661508
137 Skin - Sun Exposed (Lower leg)           LV546 1    0.10785720
138 Skin - Sun Exposed (Lower leg)           LV31  2    0.04735425
139 Skin - Sun Exposed (Lower leg)           LV266 3    0.02845800
140 Small Intestine - Terminal Ileum         LV452 1    0.10781809
141 Small Intestine - Terminal Ileum         LV562 2    0.07204195
142 Small Intestine - Terminal Ileum         LV532 3    0.02630525
143 Spleen                                   LV55  1    0.14066651
144 Spleen                                   LV18  2    0.04938652
145 Spleen                                   LV26  3    0.03959041
146 Stomach                                  LV103 1    0.10647289
147 Stomach                                  LV227 2    0.06633933
148 Stomach                                  LV36  3    0.06435745
149 Testis                                   LV299 1    0.11971299
150 Testis                                   LV116 2    0.04922428
151 Testis                                   LV277 3    0.04439913
152 Thyroid                                  LV246 1    0.23580972
153 Uterus                                   LV48  1    0.13179926
154 Uterus                                   LV217 2    0.05006159
155 Uterus                                   LV277 3    0.04407404
156 Vagina                                   LV80  1    0.07775978
157 Vagina                                   LV569 2    0.05789355
158 Vagina                                   LV414 3    0.04891201
159 Whole Blood                              LV90  1    0.05518846
160 Whole Blood                              LV137 2    0.05442572
161 Whole Blood                              LV546 3    0.05095805
162 Whole Blood                              LV74  4    0.04518730
    Cumulative_Percent tissue_correct n_sig_terms n_true_terms best_true_padj
1    9.240699          FALSE           8           0                     NA
2   17.806771           TRUE          33          12           6.756594e-61
3   23.047690          FALSE          27           0                     NA
4    9.253505           TRUE          33          12           1.578545e-34
5   14.322593           TRUE          20          10           4.556777e-06
6   18.953372          FALSE          28           0                     NA
7   22.684688           TRUE          13           4           1.065384e-06
8   22.414026           TRUE          20          11           4.049995e-86
9   12.812897           TRUE          21          12           2.801338e-27
10  23.391406           TRUE          36          11           1.288162e-09
11  15.127286           TRUE          32          10           1.133172e-10
12  20.591358          FALSE          29           0                     NA
13   7.958792           TRUE          46          12           1.292037e-10
14  13.418547           TRUE          65          12           7.636601e-30
15  18.651899           TRUE          58          11           5.345505e-07
16  23.638678          FALSE           8           0                     NA
17  11.161219           TRUE          42           7           5.078782e-14
18  18.049326           TRUE          64           8           1.013570e-41
19  21.034884          FALSE          19           0                     NA
20   6.101230           TRUE          64           9           4.572279e-52
21  10.508751           TRUE          69           9           3.818212e-38
22  13.820189          FALSE          25           0                     NA
23  16.726587          FALSE           4           0                     NA
24  19.577011          FALSE           5           0                     NA
25  22.344199           TRUE          43           9           1.455523e-07
26   6.170261           TRUE          60          10           5.644900e-05
27  11.590813           TRUE          31          10           3.340111e-59
28  15.927338           TRUE          28           6           1.972279e-03
29  18.769996           TRUE          80           8           1.534481e-23
30  21.524910           TRUE          32           6           6.809304e-10
⋮   ⋮                  ⋮              ⋮           ⋮            ⋮
133 10.371886           TRUE          36          12            1.638498e-83
134 16.506843           TRUE          29           7            1.232367e-06
135 19.605440          FALSE          58           0                      NA
136 22.683251          FALSE          45           0                      NA
137 12.365092           TRUE          36          12           2.215627e-115
138 17.793934           TRUE          29           1            3.431776e-02
139 21.056449          FALSE           6           0                      NA
140 11.888243           TRUE          54          10            1.751672e-49
141 19.831736          FALSE          32           0                      NA
142 22.732206          FALSE          26           0                      NA
143 14.558135           TRUE          24          11            1.247383e-43
144 19.669342          FALSE          29           0                      NA
145 23.766711          FALSE          12           0                      NA
146 11.615583           TRUE          23          11            1.663809e-14
147 18.852825           TRUE          12          11            6.067611e-86
148 25.873854           TRUE          30          11            8.097398e-75
149 12.228708           TRUE           6           6            7.600774e-37
150 17.256979          FALSE           3           0                      NA
151 21.792359          FALSE          19           0                      NA
152 26.467839           TRUE          13          12            1.135523e-89
153 14.378007           TRUE          12           5            8.653333e-65
154 19.839235           TRUE          33           5            8.730105e-13
155 24.647281           TRUE          19           5            1.019442e-19
156  8.815584           TRUE          47           6            2.827458e-38
157 15.378944           TRUE          21           6            1.262972e-23
158 20.924073          FALSE           2           0                      NA
159  5.822433           TRUE          46          11            3.793304e-07
160 11.564396          FALSE          58           0                      NA
161 16.940517          FALSE          36           0                      NA
162 21.707817          FALSE           1           0                      NA
    matched_terms
1
2   GTEx_Tissues_Adipose - Subcutaneous Male 20-29 Up | GTEx_Tissues_Adipose - Subcutaneous Female 60-69 Up | GTEx_Tissues_Adipose - Subcutaneous Female 50-59 Up | GTEx_Tissues_Adipose - Subcutaneous Female 40-49 Up | GTEx_Tissues_Adipose - Subcutaneous Male 30-39 Up | GTEx_Tissues_Adipose - Subcutaneous Female 30-39 Up | GTEx_Tissues_Adipose - Subcutaneous Male 40-49 Up | GTEx_Tissues_Adipose - Subcutaneous Female 20-29 Up | GTEx_Tissues_Adipose - Subcutaneous Male 50-59 Up | GTEx_Tissues_Adipose - Subcutaneous Male 70-79 Up | GTEx_Tissues_Adipose - Subcutaneous Female 70-79 Up | GTEx_Tissues_Adipose - Subcutaneous Male 60-69 Up
3
4   GTEx_Tissues_Adipose - Visceral (Omentum) Male 40-49 Up | GTEx_Tissues_Adipose - Visceral (Omentum) Male 50-59 Up | GTEx_Tissues_Adipose - Visceral (Omentum) Female 50-59 Up | GTEx_Tissues_Adipose - Visceral (Omentum) Female 20-29 Up | GTEx_Tissues_Adipose - Visceral (Omentum) Female 30-39 Up | GTEx_Tissues_Adipose - Visceral (Omentum) Male 30-39 Up | GTEx_Tissues_Adipose - Visceral (Omentum) Female 40-49 Up | GTEx_Tissues_Adipose - Visceral (Omentum) Male 60-69 Up | GTEx_Tissues_Adipose - Visceral (Omentum) Female 70-79 Up | GTEx_Tissues_Adipose - Visceral (Omentum) Male 70-79 Up | GTEx_Tissues_Adipose - Visceral (Omentum) Female 60-69 Up | GTEx_Tissues_Adipose - Visceral (Omentum) Male 20-29 Up
5   GTEx_Tissues_Adipose - Visceral (Omentum) Male 70-79 Up | GTEx_Tissues_Adipose - Visceral (Omentum) Female 60-69 Up | GTEx_Tissues_Adipose - Visceral (Omentum) Male 60-69 Up | GTEx_Tissues_Adipose - Visceral (Omentum) Male 50-59 Up | GTEx_Tissues_Adipose - Visceral (Omentum) Female 50-59 Up | GTEx_Tissues_Adipose - Visceral (Omentum) Female 70-79 Up | GTEx_Tissues_Adipose - Visceral (Omentum) Female 40-49 Up | GTEx_Tissues_Adipose - Visceral (Omentum) Female 30-39 Up | GTEx_Tissues_Adipose - Visceral (Omentum) Male 20-29 Up | GTEx_Tissues_Adipose - Visceral (Omentum) Male 30-39 Up
6
7   GTEx_Tissues_Adipose - Visceral (Omentum) Male 60-69 Up | GTEx_Tissues_Adipose - Visceral (Omentum) Male 70-79 Up | GTEx_Tissues_Adipose - Visceral (Omentum) Male 40-49 Up | GTEx_Tissues_Adipose - Visceral (Omentum) Male 50-59 Up
8   GTEx_Tissues_Adrenal Gland Male 20-29 Up | GTEx_Tissues_Adrenal Gland Male 50-59 Up | GTEx_Tissues_Adrenal Gland Female 50-59 Up | GTEx_Tissues_Adrenal Gland Male 40-49 Up | GTEx_Tissues_Adrenal Gland Male 60-69 Up | GTEx_Tissues_Adrenal Gland Female 40-49 Up | GTEx_Tissues_Adrenal Gland Male 30-39 Up | GTEx_Tissues_Adrenal Gland Female 30-39 Up | GTEx_Tissues_Adrenal Gland Female 20-29 Up | GTEx_Tissues_Adrenal Gland Female 60-69 Up | GTEx_Tissues_Adrenal Gland Male 70-79 Up
9   GTEx_Tissues_Artery - Aorta Female 60-69 Up | GTEx_Tissues_Artery - Aorta Male 70-79 Up | GTEx_Tissues_Artery - Aorta Male 40-49 Up | GTEx_Tissues_Artery - Aorta Male 30-39 Up | GTEx_Tissues_Artery - Aorta Male 60-69 Up | GTEx_Tissues_Artery - Aorta Male 50-59 Up | GTEx_Tissues_Artery - Aorta Female 50-59 Up | GTEx_Tissues_Artery - Aorta Female 30-39 Up | GTEx_Tissues_Artery - Aorta Female 40-49 Up | GTEx_Tissues_Artery - Aorta Female 20-29 Up | GTEx_Tissues_Artery - Aorta Female 70-79 Up | GTEx_Tissues_Artery - Aorta Male 20-29 Up
10  GTEx_Tissues_Artery - Aorta Female 20-29 Up | GTEx_Tissues_Artery - Aorta Male 20-29 Up | GTEx_Tissues_Artery - Aorta Male 70-79 Up | GTEx_Tissues_Artery - Aorta Female 30-39 Up | GTEx_Tissues_Artery - Aorta Male 40-49 Up | GTEx_Tissues_Artery - Aorta Male 30-39 Up | GTEx_Tissues_Artery - Aorta Female 50-59 Up | GTEx_Tissues_Artery - Aorta Female 40-49 Up | GTEx_Tissues_Artery - Aorta Female 60-69 Up | GTEx_Tissues_Artery - Aorta Male 60-69 Up | GTEx_Tissues_Artery - Aorta Male 50-59 Up
11  GTEx_Tissues_Artery - Coronary Male 50-59 Up | GTEx_Tissues_Artery - Coronary Male 60-69 Up | GTEx_Tissues_Artery - Coronary Male 40-49 Up | GTEx_Tissues_Artery - Coronary Female 60-69 Up | GTEx_Tissues_Artery - Coronary Female 50-59 Up | GTEx_Tissues_Artery - Coronary Female 20-29 Up | GTEx_Tissues_Artery - Coronary Female 40-49 Up | GTEx_Tissues_Artery - Coronary Male 70-79 Up | GTEx_Tissues_Artery - Coronary Male 20-29 Up | GTEx_Tissues_Artery - Coronary Male 30-39 Up
12
13  GTEx_Tissues_Artery - Tibial Female 50-59 Up | GTEx_Tissues_Artery - Tibial Male 40-49 Up | GTEx_Tissues_Artery - Tibial Male 50-59 Up | GTEx_Tissues_Artery - Tibial Female 60-69 Up | GTEx_Tissues_Artery - Tibial Female 70-79 Up | GTEx_Tissues_Artery - Tibial Male 60-69 Up | GTEx_Tissues_Artery - Tibial Female 40-49 Up | GTEx_Tissues_Artery - Tibial Male 70-79 Up | GTEx_Tissues_Artery - Tibial Male 30-39 Up | GTEx_Tissues_Artery - Tibial Female 30-39 Up | GTEx_Tissues_Artery - Tibial Male 20-29 Up | GTEx_Tissues_Artery - Tibial Female 20-29 Up
14  GTEx_Tissues_Artery - Tibial Male 60-69 Up | GTEx_Tissues_Artery - Tibial Male 50-59 Up | GTEx_Tissues_Artery - Tibial Female 60-69 Up | GTEx_Tissues_Artery - Tibial Female 70-79 Up | GTEx_Tissues_Artery - Tibial Female 50-59 Up | GTEx_Tissues_Artery - Tibial Female 20-29 Up | GTEx_Tissues_Artery - Tibial Male 30-39 Up | GTEx_Tissues_Artery - Tibial Male 40-49 Up | GTEx_Tissues_Artery - Tibial Male 70-79 Up | GTEx_Tissues_Artery - Tibial Female 40-49 Up | GTEx_Tissues_Artery - Tibial Female 30-39 Up | GTEx_Tissues_Artery - Tibial Male 20-29 Up
15  GTEx_Tissues_Artery - Tibial Male 20-29 Up | GTEx_Tissues_Artery - Tibial Female 40-49 Up | GTEx_Tissues_Artery - Tibial Female 20-29 Up | GTEx_Tissues_Artery - Tibial Male 50-59 Up | GTEx_Tissues_Artery - Tibial Female 30-39 Up | GTEx_Tissues_Artery - Tibial Female 50-59 Up | GTEx_Tissues_Artery - Tibial Male 30-39 Up | GTEx_Tissues_Artery - Tibial Male 40-49 Up | GTEx_Tissues_Artery - Tibial Male 60-69 Up | GTEx_Tissues_Artery - Tibial Female 60-69 Up | GTEx_Tissues_Artery - Tibial Female 70-79 Up
16
17  GTEx_Tissues_Brain - Amygdala Female 40-49 Up | GTEx_Tissues_Brain - Amygdala Male 40-49 Up | GTEx_Tissues_Brain - Amygdala Female 60-69 Up | GTEx_Tissues_Brain - Amygdala Male 20-29 Up | GTEx_Tissues_Brain - Amygdala Male 50-59 Up | GTEx_Tissues_Brain - Amygdala Male 60-69 Up | GTEx_Tissues_Brain - Amygdala Male 70-79 Up
18  GTEx_Tissues_Brain - Amygdala Male 40-49 Up | GTEx_Tissues_Brain - Amygdala Female 40-49 Up | GTEx_Tissues_Brain - Amygdala Male 50-59 Up | GTEx_Tissues_Brain - Amygdala Male 60-69 Up | GTEx_Tissues_Brain - Amygdala Male 20-29 Up | GTEx_Tissues_Brain - Amygdala Female 60-69 Up | GTEx_Tissues_Brain - Amygdala Male 70-79 Up | GTEx_Tissues_Brain - Amygdala Female 50-59 Up
19
20  GTEx_Tissues_Brain - Anterior Cingulate Cortex (BA24) Male 50-59 Up | GTEx_Tissues_Brain - Anterior Cingulate Cortex (BA24) Male 70-79 Up | GTEx_Tissues_Brain - Anterior Cingulate Cortex (BA24) Male 60-69 Up | GTEx_Tissues_Brain - Anterior Cingulate Cortex (BA24) Female 50-59 Up | GTEx_Tissues_Brain - Anterior Cingulate Cortex (BA24) Female 20-29 Up | GTEx_Tissues_Brain - Anterior Cingulate Cortex (BA24) Male 40-49 Up | GTEx_Tissues_Brain - Anterior Cingulate Cortex (BA24) Female 40-49 Up | GTEx_Tissues_Brain - Anterior Cingulate Cortex (BA24) Female 60-69 Up | GTEx_Tissues_Brain - Anterior Cingulate Cortex (BA24) Male 30-39 Up
21  GTEx_Tissues_Brain - Anterior Cingulate Cortex (BA24) Female 50-59 Up | GTEx_Tissues_Brain - Anterior Cingulate Cortex (BA24) Female 40-49 Up | GTEx_Tissues_Brain - Anterior Cingulate Cortex (BA24) Female 20-29 Up | GTEx_Tissues_Brain - Anterior Cingulate Cortex (BA24) Male 50-59 Up | GTEx_Tissues_Brain - Anterior Cingulate Cortex (BA24) Male 60-69 Up | GTEx_Tissues_Brain - Anterior Cingulate Cortex (BA24) Male 40-49 Up | GTEx_Tissues_Brain - Anterior Cingulate Cortex (BA24) Male 70-79 Up | GTEx_Tissues_Brain - Anterior Cingulate Cortex (BA24) Male 30-39 Up | GTEx_Tissues_Brain - Anterior Cingulate Cortex (BA24) Female 60-69 Up
22
23
24
25  GTEx_Tissues_Brain - Anterior Cingulate Cortex (BA24) Male 50-59 Up | GTEx_Tissues_Brain - Anterior Cingulate Cortex (BA24) Female 50-59 Up | GTEx_Tissues_Brain - Anterior Cingulate Cortex (BA24) Female 40-49 Up | GTEx_Tissues_Brain - Anterior Cingulate Cortex (BA24) Male 60-69 Up | GTEx_Tissues_Brain - Anterior Cingulate Cortex (BA24) Male 70-79 Up | GTEx_Tissues_Brain - Anterior Cingulate Cortex (BA24) Female 20-29 Up | GTEx_Tissues_Brain - Anterior Cingulate Cortex (BA24) Male 40-49 Up | GTEx_Tissues_Brain - Anterior Cingulate Cortex (BA24) Female 60-69 Up | GTEx_Tissues_Brain - Anterior Cingulate Cortex (BA24) Male 30-39 Up
26  GTEx_Tissues_Brain - Caudate (Basal Ganglia) Female 20-29 Up | GTEx_Tissues_Brain - Caudate (Basal Ganglia) Male 50-59 Up | GTEx_Tissues_Brain - Caudate (Basal Ganglia) Male 40-49 Up | GTEx_Tissues_Brain - Caudate (Basal Ganglia) Female 70-79 Up | GTEx_Tissues_Brain - Caudate (Basal Ganglia) Male 30-39 Up | GTEx_Tissues_Brain - Caudate (Basal Ganglia) Female 50-59 Up | GTEx_Tissues_Brain - Caudate (Basal Ganglia) Female 60-69 Up | GTEx_Tissues_Brain - Caudate (Basal Ganglia) Female 40-49 Up | GTEx_Tissues_Brain - Caudate (Basal Ganglia) Male 70-79 Up | GTEx_Tissues_Brain - Caudate (Basal Ganglia) Male 60-69 Up
27  GTEx_Tissues_Brain - Caudate (Basal Ganglia) Male 30-39 Up | GTEx_Tissues_Brain - Caudate (Basal Ganglia) Male 50-59 Up | GTEx_Tissues_Brain - Caudate (Basal Ganglia) Female 20-29 Up | GTEx_Tissues_Brain - Caudate (Basal Ganglia) Male 40-49 Up | GTEx_Tissues_Brain - Caudate (Basal Ganglia) Male 60-69 Up | GTEx_Tissues_Brain - Caudate (Basal Ganglia) Male 70-79 Up | GTEx_Tissues_Brain - Caudate (Basal Ganglia) Female 40-49 Up | GTEx_Tissues_Brain - Caudate (Basal Ganglia) Female 50-59 Up | GTEx_Tissues_Brain - Caudate (Basal Ganglia) Female 60-69 Up | GTEx_Tissues_Brain - Caudate (Basal Ganglia) Female 70-79 Up
28  GTEx_Tissues_Brain - Caudate (Basal Ganglia) Male 50-59 Up | GTEx_Tissues_Brain - Caudate (Basal Ganglia) Male 60-69 Up | GTEx_Tissues_Brain - Caudate (Basal Ganglia) Male 40-49 Up | GTEx_Tissues_Brain - Caudate (Basal Ganglia) Male 30-39 Up | GTEx_Tissues_Brain - Caudate (Basal Ganglia) Female 20-29 Up | GTEx_Tissues_Brain - Caudate (Basal Ganglia) Female 50-59 Up
29  GTEx_Tissues_Brain - Caudate (Basal Ganglia) Female 60-69 Up | GTEx_Tissues_Brain - Caudate (Basal Ganglia) Female 50-59 Up | GTEx_Tissues_Brain - Caudate (Basal Ganglia) Female 70-79 Up | GTEx_Tissues_Brain - Caudate (Basal Ganglia) Male 60-69 Up | GTEx_Tissues_Brain - Caudate (Basal Ganglia) Female 40-49 Up | GTEx_Tissues_Brain - Caudate (Basal Ganglia) Male 70-79 Up | GTEx_Tissues_Brain - Caudate (Basal Ganglia) Male 40-49 Up | GTEx_Tissues_Brain - Caudate (Basal Ganglia) Male 50-59 Up
30  GTEx_Tissues_Brain - Caudate (Basal Ganglia) Female 70-79 Up | GTEx_Tissues_Brain - Caudate (Basal Ganglia) Female 60-69 Up | GTEx_Tissues_Brain - Caudate (Basal Ganglia) Female 50-59 Up | GTEx_Tissues_Brain - Caudate (Basal Ganglia) Female 40-49 Up | GTEx_Tissues_Brain - Caudate (Basal Ganglia) Male 70-79 Up | GTEx_Tissues_Brain - Caudate (Basal Ganglia) Male 60-69 Up
⋮   ⋮

In [11]:
# Per-LV correctness within the cumulative20 selection (not just "any LV correct")
per_lv_summary <- results$cumulative20$detail %>%
    dplyr::group_by(Tissue) %>%
    dplyr::summarise(
        n_lvs = dplyr::n(),
        n_correct = sum(tissue_correct),
        pct_correct = 100 * n_correct / n_lvs,
        .groups = "drop"
    ) %>%
    dplyr::arrange(pct_correct)

print(per_lv_summary, n = Inf)

total_lvs <- sum(per_lv_summary$n_lvs)
total_correct <- sum(per_lv_summary$n_correct)
cat(sprintf(
    "\nOverall: %d/%d LV-tissue rows correct (%.1f%%) across cumulative20 selection\n",
    total_correct, total_lvs, 100 * total_correct / total_lvs
))
cat(sprintf("Tissues at 100%% LV concordance: %d/%d\n",
            sum(per_lv_summary$pct_correct == 100), nrow(per_lv_summary)))

write.csv(per_lv_summary, file.path(OUT_DIR, "cumulative20", "gtex_global_alignment_per_lv_pct.csv"), row.names = FALSE)

# A tibble: 49 × 4
   Tissue                                    n_lvs n_correct pct_correct
   <chr>                                     <int>     <int>       <dbl>
 1 Whole Blood                                   4         1        25
 2 Adipose - Subcutaneous                        3         1        33.3
 3 Brain - Substantia nigra                      3         1        33.3
 4 Cells - EBV-transformed lymphocytes           3         1        33.3
 5 Small Intestine - Terminal Ileum              3         1        33.3
 6 Spleen                                        3         1        33.3
 7 Testis                                        3         1        33.3
 8 Artery - Coronary                             2         1        50
 9 Brain - Anterior cingulate cortex (BA24)      6         3        50
10 Brain - Cerebellum                            6         3        50
11 Brain - Hypothalamus                          4         2        50
12 Cells - Cultured fibroblasts                  2         1        50
13 Skin - Not Sun Exposed (Suprapubic)           4         2        50
14 Brain - Cerebellar Hemisphere                 7         4        57.1
15 Brain - Frontal Cortex (BA9)                  5         3        60
16 Heart - Left Ventricle                        5         3        60
17 Brain - Amygdala                              3         2        66.7
18 Esophagus - Mucosa                            3         2        66.7
19 Muscle - Skeletal                             3         2        66.7
20 Skin - Sun Exposed (Lower leg)                3         2        66.7
21 Vagina                                        3         2        66.7
22 Adipose - Visceral (Omentum)                  4         3        75
23 Artery - Tibial                               4         3        75
24 Brain - Hippocampus                           4         3        75
25 Brain - Nucleus accumbens (basal ganglia)     4         3        75
26 Breast - Mammary Tissue                       4         3        75
27 Pituitary                                     4         3        75
28 Brain - Putamen (basal ganglia)               5         4        80
29 Adrenal Gland                                 1         1       100
30 Artery - Aorta                                2         2       100
31 Brain - Caudate (basal ganglia)               5         5       100
32 Brain - Cortex                                3         3       100
33 Brain - Spinal cord (cervical c-1)            3         3       100
34 Colon - Sigmoid                               2         2       100
35 Colon - Transverse                            4         4       100
36 Esophagus - Gastroesophageal Junction         4         4       100
37 Esophagus - Muscularis                        3         3       100
38 Heart - Atrial Appendage                      2         2       100
39 Kidney - Cortex                               2         2       100
40 Liver                                         3         3       100
41 Lung                                          1         1       100
42 Minor Salivary Gland                          3         3       100
43 Nerve - Tibial                                1         1       100
44 Ovary                                         4         4       100
45 Pancreas                                      2         2       100
46 Prostate                                      3         3       100
47 Stomach                                       3         3       100
48 Thyroid                                       1         1       100
49 Uterus                                        3         3       100

Overall: 116/162 LV-tissue rows correct (71.6%) across cumulative20 selection

Tissues at 100% LV concordance: 21/49

In [12]:
# Tissue-group-level gene (Z matrix) recovery -- the companion to
# 02_b_matrix.ipynb's grouped B-matrix heatmap (Panel G in supp1.ipynb).
# Subtissues are merged into their parent anatomical tissue with the same
# convention used there (Cells - * kept separate; everything else grouped
# on the text before " - "), and a group counts as recovered if ANY member
# subtissue's cumulative20-selected LVs were significantly ORA-enriched
# for the true tissue.
get_heatmap_group <- function(name) {
    if (startsWith(name, "Cells - ")) return(name)
    parts <- strsplit(name, " - ")[[1]]
    if (length(parts) > 1) trimws(parts[1]) else name
}

grouped_summary <- results$cumulative20$tissue_summary %>%
    dplyr::mutate(Tissue_Group = vapply(Tissue, get_heatmap_group, character(1))) %>%
    dplyr::group_by(Tissue_Group) %>%
    dplyr::summarise(
        n_subtissues = dplyr::n(),
        tissue_correct = any(tissue_correct),
        best_true_padj = if (all(is.na(best_true_padj))) NA_real_ else min(best_true_padj, na.rm = TRUE),
        .groups = "drop"
    ) %>%
    dplyr::arrange(Tissue_Group)

n_grp_correct <- sum(grouped_summary$tissue_correct)
n_grp_total   <- nrow(grouped_summary)
cat(sprintf("Gene-level (Z matrix) tissue-group recovery: %d/%d (%.1f%%)\n",
            n_grp_correct, n_grp_total, 100 * n_grp_correct / n_grp_total))

write.csv(grouped_summary, file.path(OUT_DIR, "gtex_global_alignment_grouped_summary.csv"), row.names = FALSE)
grouped_summary

Gene-level (Z matrix) tissue-group recovery: 29/29 (100.0%)

                                      Tissue_Group
Adipose - Subcutaneous                Adipose
Adrenal Gland                         Adrenal Gland
Artery - Aorta                        Artery
Brain - Amygdala                      Brain
Breast - Mammary Tissue               Breast
Cells - Cultured fibroblasts          Cells - Cultured fibroblasts
Cells - EBV-transformed lymphocytes   Cells - EBV-transformed lymphocytes
Colon - Sigmoid                       Colon
Esophagus - Gastroesophageal Junction Esophagus
Heart - Atrial Appendage              Heart
Kidney - Cortex                       Kidney
Liver                                 Liver
Lung                                  Lung
Minor Salivary Gland                  Minor Salivary Gland
Muscle - Skeletal                     Muscle
Nerve - Tibial                        Nerve
Ovary                                 Ovary
Pancreas                              Pancreas
Pituitary                             Pituitary
Prostate                              Prostate
Skin - Not Sun Exposed (Suprapubic)   Skin
Small Intestine - Terminal Ileum      Small Intestine
Spleen                                Spleen
Stomach                               Stomach
Testis                                Testis
Thyroid                               Thyroid
Uterus                                Uterus
Vagina                                Vagina
Whole Blood                           Whole Blood
                                      n_subtissues tissue_correct
Adipose - Subcutaneous                 2           TRUE
Adrenal Gland                          1           TRUE
Artery - Aorta                         3           TRUE
Brain - Amygdala                      13           TRUE
Breast - Mammary Tissue                1           TRUE
Cells - Cultured fibroblasts           1           TRUE
Cells - EBV-transformed lymphocytes    1           TRUE
Colon - Sigmoid                        2           TRUE
Esophagus - Gastroesophageal Junction  3           TRUE
Heart - Atrial Appendage               2           TRUE
Kidney - Cortex                        1           TRUE
Liver                                  1           TRUE
Lung                                   1           TRUE
Minor Salivary Gland                   1           TRUE
Muscle - Skeletal                      1           TRUE
Nerve - Tibial                         1           TRUE
Ovary                                  1           TRUE
Pancreas                               1           TRUE
Pituitary                              1           TRUE
Prostate                               1           TRUE
Skin - Not Sun Exposed (Suprapubic)    2           TRUE
Small Intestine - Terminal Ileum       1           TRUE
Spleen                                 1           TRUE
Stomach                                1           TRUE
Testis                                 1           TRUE
Thyroid                                1           TRUE
Uterus                                 1           TRUE
Vagina                                 1           TRUE
Whole Blood                            1           TRUE
                                      best_true_padj
Adipose - Subcutaneous                 6.756594e-61
Adrenal Gland                          4.049995e-86
Artery - Aorta                         7.636601e-30
Brain - Amygdala                       1.446959e-63
Breast - Mammary Tissue                9.636064e-40
Cells - Cultured fibroblasts           1.346694e-38
Cells - EBV-transformed lymphocytes    1.124981e-23
Colon - Sigmoid                        5.765299e-66
Esophagus - Gastroesophageal Junction  7.432571e-99
Heart - Atrial Appendage               2.406288e-65
Kidney - Cortex                        4.136059e-78
Liver                                  4.043843e-68
Lung                                   3.759660e-58
Minor Salivary Gland                   1.687891e-69
Muscle - Skeletal                      5.312434e-81
Nerve - Tibial                         6.721358e-76
Ovary                                  5.430985e-54
Pancreas                              2.841630e-104
Pituitary                              9.893213e-61
Prostate                               8.553147e-70
Skin - Not Sun Exposed (Suprapubic)   2.215627e-115
Small Intestine - Terminal Ileum       1.751672e-49
Spleen                                 1.247383e-43
Stomach                                6.067611e-86
Testis                                 7.600774e-37
Thyroid                                1.135523e-89
Uterus                                 8.653333e-65
Vagina                                 2.827458e-38
Whole Blood                            3.793304e-07

## Summary of results

In [13]:
stopifnot(file.exists(file.path(OUT_DIR, 'gtex_tissue_ora_per_lv.csv')))

for (nm in names(selections)) {
    out_dir <- file.path(OUT_DIR, nm)
    expected_rows <- nrow(selections[[nm]])
    stopifnot(nrow(results[[nm]]$detail) == expected_rows)
    stopifnot(nrow(results[[nm]]$tissue_summary) == dplyr::n_distinct(shap_all$Tissue))
    stopifnot(file.exists(file.path(out_dir, 'gtex_global_alignment_detail.csv')))
    stopifnot(file.exists(file.path(out_dir, 'gtex_global_alignment_summary.csv')))
    stopifnot(file.exists(file.path(out_dir, 'gtex_global_alignment_final_pct.csv')))
    cat(sprintf(
        '[%s] Checks passed. Denominator = %d tissues and %d selected LV/tissue rows. Final %% tissue correct = %.2f\n',
        nm, nrow(results[[nm]]$tissue_summary), nrow(results[[nm]]$detail),
        results[[nm]]$final_summary$pct_tissue_correct
    ))
}

[top1] Checks passed. Denominator = 49 tissues and 49 selected LV/tissue rows. Final % tissue correct = 89.80
[cumulative20] Checks passed. Denominator = 49 tissues and 162 selected LV/tissue rows. Final % tissue correct = 100.00