# GTEx global alignment

Take the highest-ranked SHAP LV per GTEx tissue and test whether it recovers the true tissue by ORA against the GTEx tissue gene-set database.

In [ ]:
library(here)
library(dplyr)
library(tidyr)
library(stringr)
library(Matrix)
library(clusterProfiler)


SHAP_DIR <- here('output', '03_model_biology', '01_gtex',
                 '01_LV_importance_kmeans', 'gtex_feature_importance_kmeans_binary_shap')
OUT_DIR  <- here('output', '03_model_biology', '01_gtex', '07_global_alignment')
dir.create(OUT_DIR, recursive = TRUE, showWarnings = FALSE)

CLAMP_RDS      <- here('output', '01_model_building', '02_gtex', '01_CLAMP', 'CLAMPfull.rds')
GTEX_TISSUE_DB <- here('data', 'archs4', 'GTEx_Tissues_pathMat.rds')

N_LVS_PER_TISSUE <- 1L
TOP_GENE_PCT     <- 0.01
FDR_THRESH       <- 0.05

In [ ]:
shap_all <- read.delim(file.path(SHAP_DIR, 'all_shap_positive.tsv'),
                       stringsAsFactors = FALSE, check.names = FALSE)

selected_lvs <- shap_all %>%
    dplyr::arrange(Tissue, Rank) %>%
    dplyr::group_by(Tissue) %>%
    dplyr::slice_head(n = N_LVS_PER_TISSUE) %>%
    dplyr::ungroup() %>%
    dplyr::rename(LV = Feature) %>%
    dplyr::select(Tissue, LV, Rank, Mean_SHAP_Tissue, Cumulative_SHAP, Cumulative_Percent)

cat('Tissues:', dplyr::n_distinct(selected_lvs$Tissue), '\n')
cat('Selected LV/tissue rows:', nrow(selected_lvs), '\n')

Tissues: 23
Selected LV/tissue rows: 23

   Tissue                              n_selected_lvs
1  Adrenal Gland                       1
2  Artery - Tibial                     1
3  Cells - Cultured fibroblasts        1
4  Cells - EBV-transformed lymphocytes 1
5  Colon - Transverse                  1
6  Esophagus - Mucosa                  1
7  Heart - Atrial Appendage            1
8  Heart - Left Ventricle              1
9  Kidney - Cortex                     1
10 Liver                               1
11 Lung                                1
12 Muscle - Skeletal                   1
13 Nerve - Tibial                      1
14 Ovary                               1
15 Pancreas                            1
16 Pituitary                           1
17 Prostate                            1
18 Small Intestine - Terminal Ileum    1
19 Stomach                             1
20 Testis                              1
21 Thyroid                             1
22 Vagina                              1
23 Whole Blood                         1

In [ ]:
clamp <- readRDS(CLAMP_RDS)
Z <- as.matrix(clamp$Z)
rm(clamp)

selected_unique_lvs <- intersect(unique(selected_lvs$LV), colnames(Z))
missing_lvs <- setdiff(unique(selected_lvs$LV), colnames(Z))
if (length(missing_lvs) > 0) warning('Missing LVs in Z: ', paste(missing_lvs, collapse = ', '))

Z <- Z[, selected_unique_lvs, drop = FALSE]
universe_genes <- rownames(Z)
n_top_genes <- max(1L, ceiling(TOP_GENE_PCT * nrow(Z)))

cat('Z:', nrow(Z), 'genes x', ncol(Z), 'selected unique LVs\n')
cat('Top genes per LV:', n_top_genes, '\n')

Z: 21613 genes x 21 selected unique LVs
Top genes per LV: 217

In [ ]:
gtex_mat <- readRDS(GTEX_TISSUE_DB)
term_names <- unname(colnames(gtex_mat))

parse_gtex_tissue <- function(x) {
    x <- sub('^GTEx_Tissues_', '', x)
    x <- sub(' (Male|Female) [0-9]+-[0-9]+ Up$', '', x)
    x
}

normalize_text <- function(x) {
    x <- tolower(x)
    x <- gsub('[^a-z0-9]+', ' ', x)
    stringr::str_squish(x)
}

term2gene <- lapply(seq_along(term_names), function(i) {
    rownames(gtex_mat)[gtex_mat[, i] != 0]
})
names(term2gene) <- term_names

term2gene_df <- do.call(rbind, lapply(names(term2gene), function(term) {
    data.frame(term = term, gene = term2gene[[term]], stringsAsFactors = FALSE)
}))

term_map <- data.frame(
    term = term_names,
    parsed_tissue = parse_gtex_tissue(term_names),
    normalized_tissue = normalize_text(parse_gtex_tissue(term_names)),
    stringsAsFactors = FALSE
)

tissue_check <- selected_lvs %>%
    dplyr::distinct(Tissue) %>%
    dplyr::mutate(
        normalized_tissue = normalize_text(Tissue),
        matched_in_gtex_db = normalized_tissue %in% term_map$normalized_tissue,
        n_db_sets = vapply(normalized_tissue, function(x) sum(term_map$normalized_tissue == x), integer(1))
    )

cat('GTEx tissue gene sets:', length(term2gene), '\n')
stopifnot(all(tissue_check$matched_in_gtex_db))
tissue_check

GTEx tissue gene sets: 511

                                  Tissue
adrenal gland                     Adrenal Gland
artery tibial                     Artery - Tibial
cells cultured fibroblasts        Cells - Cultured fibroblasts
cells ebv transformed lymphocytes Cells - EBV-transformed lymphocytes
colon transverse                  Colon - Transverse
esophagus mucosa                  Esophagus - Mucosa
heart atrial appendage            Heart - Atrial Appendage
heart left ventricle              Heart - Left Ventricle
kidney cortex                     Kidney - Cortex
liver                             Liver
lung                              Lung
muscle skeletal                   Muscle - Skeletal
nerve tibial                      Nerve - Tibial
ovary                             Ovary
pancreas                          Pancreas
pituitary                         Pituitary
prostate                          Prostate
small intestine terminal ileum    Small Intestine - Terminal Ileum
stomach                           Stomach
testis                            Testis
thyroid                           Thyroid
vagina                            Vagina
whole blood                       Whole Blood
                                  normalized_tissue
adrenal gland                     adrenal gland
artery tibial                     artery tibial
cells cultured fibroblasts        cells cultured fibroblasts
cells ebv transformed lymphocytes cells ebv transformed lymphocytes
colon transverse                  colon transverse
esophagus mucosa                  esophagus mucosa
heart atrial appendage            heart atrial appendage
heart left ventricle              heart left ventricle
kidney cortex                     kidney cortex
liver                             liver
lung                              lung
muscle skeletal                   muscle skeletal
nerve tibial                      nerve tibial
ovary                             ovary
pancreas                          pancreas
pituitary                         pituitary
prostate                          prostate
small intestine terminal ileum    small intestine terminal ileum
stomach                           stomach
testis                            testis
thyroid                           thyroid
vagina                            vagina
whole blood                       whole blood
                                  matched_in_gtex_db n_db_sets
adrenal gland                     TRUE               11
artery tibial                     TRUE               12
cells cultured fibroblasts        TRUE               12
cells ebv transformed lymphocytes TRUE                9
colon transverse                  TRUE               11
esophagus mucosa                  TRUE               12
heart atrial appendage            TRUE               12
heart left ventricle              TRUE               12
kidney cortex                     TRUE                7
liver                             TRUE               11
lung                              TRUE               12
muscle skeletal                   TRUE               12
nerve tibial                      TRUE               12
ovary                             TRUE                6
pancreas                          TRUE               11
pituitary                         TRUE               11
prostate                          TRUE                6
small intestine terminal ileum    TRUE               11
stomach                           TRUE               11
testis                            TRUE                6
thyroid                           TRUE               12
vagina                            TRUE                6
whole blood                       TRUE               12

In [ ]:
run_gtex_tissue_ora <- function(genes, universe) {
    res <- tryCatch(
        clusterProfiler::enricher(
            gene          = genes,
            universe      = universe,
            TERM2GENE     = term2gene_df,
            pAdjustMethod = 'BH',
            pvalueCutoff  = 1,
            qvalueCutoff  = 1,
            minGSSize     = 10,
            maxGSSize     = 500
        ),
        error = function(e) NULL
    )
    if (is.null(res)) return(NULL)
    df <- as.data.frame(res)
    if (nrow(df) == 0) return(NULL)
    df
}

top_genes_per_lv <- lapply(colnames(Z), function(lv) {
    vals <- Z[, lv]
    universe_genes[order(vals, decreasing = TRUE)[seq_len(n_top_genes)]]
})
names(top_genes_per_lv) <- colnames(Z)

ora_list <- lapply(names(top_genes_per_lv), function(lv) {
    df <- run_gtex_tissue_ora(top_genes_per_lv[[lv]], universe_genes)
    if (is.null(df)) return(NULL)
    df$LV <- lv
    df
})

ora_all <- do.call(rbind, Filter(Negate(is.null), ora_list))
if (is.null(ora_all)) {
    ora_all <- data.frame()
} else {
    rownames(ora_all) <- NULL
    ora_all <- ora_all %>%
        dplyr::left_join(term_map, by = c('ID' = 'term')) %>%
        dplyr::select(LV, ID, Description, parsed_tissue, normalized_tissue,
                      GeneRatio, BgRatio, pvalue, p.adjust, qvalue, geneID, Count)
}

write.csv(ora_all, file.path(OUT_DIR, 'gtex_tissue_ora_per_lv.csv'), row.names = FALSE)
cat('ORA rows:', nrow(ora_all), '\n')
head(ora_all)

ORA rows: 5007

  LV    ID
1 LV183 GTEx_Tissues_Adrenal Gland Male 40-49 Up
2 LV183 GTEx_Tissues_Adrenal Gland Male 50-59 Up
3 LV183 GTEx_Tissues_Adrenal Gland Male 20-29 Up
4 LV183 GTEx_Tissues_Adrenal Gland Female 20-29 Up
5 LV183 GTEx_Tissues_Adrenal Gland Female 60-69 Up
6 LV183 GTEx_Tissues_Adrenal Gland Male 60-69 Up
  Description                                parsed_tissue normalized_tissue
1 GTEx_Tissues_Adrenal Gland Male 40-49 Up   Adrenal Gland adrenal gland
2 GTEx_Tissues_Adrenal Gland Male 50-59 Up   Adrenal Gland adrenal gland
3 GTEx_Tissues_Adrenal Gland Male 20-29 Up   Adrenal Gland adrenal gland
4 GTEx_Tissues_Adrenal Gland Female 20-29 Up Adrenal Gland adrenal gland
5 GTEx_Tissues_Adrenal Gland Female 60-69 Up Adrenal Gland adrenal gland
6 GTEx_Tissues_Adrenal Gland Male 60-69 Up   Adrenal Gland adrenal gland
  GeneRatio BgRatio pvalue       p.adjust     qvalue
1 52/137    92/6121 2.918975e-65 8.202318e-63 8.202318e-63
2 52/137    93/6121 6.529532e-65 9.173993e-63 9.173993e-63
3 51/137    91/6121 1.157211e-63 1.083921e-61 1.083921e-61
4 50/137    91/6121 9.840988e-62 5.530635e-60 5.530635e-60
5 50/137    91/6121 9.840988e-62 5.530635e-60 5.530635e-60
6 50/137    92/6121 2.125165e-61 9.952854e-60 9.952854e-60
  geneID
1 CYP11B1/CYP17A1/CYP21A2/AS3MT/FAM166B/DBH/AMHR2/STAR/FAM43B/CYB561A3/FDXR/SNTB1/AADAC/IFITM10/KLHL4/SERPINA5/GSTA3/RMDN2/CYP11A1/FDX1/AKAP7/ABCB1/KCNK3/RGN/SLC16A9/RDX/KCNN2/MGARP/AKR1B1/ADGRV1/ASB4/ABCC3/NR5A1/KCNJ5/FNDC4/GSTA1/PORCN/SLC8B1/ALAS1/CYB5B/MCOLN3/KCTD14/KLHDC8B/DEXI/SEMA6A/MRAP/GALM/SREBF1/EPHX1/DLK1/C4B/C2CD2
2 CYP11B1/CYP17A1/CYP21A2/AS3MT/FAM166B/AMHR2/STAR/FAM43B/CYB561A3/FDXR/SNTB1/AADAC/IFITM10/KLHL4/SERPINA5/GSTA3/RMDN2/CYP11A1/FDX1/AKAP7/ABCB1/KCNK3/RGN/SLC16A9/RDX/KCNN2/MGARP/AKR1B1/ADGRV1/ASB4/ABCC3/NR5A1/KCNJ5/FNDC4/GSTA1/PORCN/SLC8B1/ALAS1/CYB5B/MCOLN3/KCTD14/DEXI/SEMA6A/MRAP/GALM/SREBF1/MRPL33/EPHX1/DLK1/C4B/ZSWIM5/C2CD2
3 CYP11B1/CYP17A1/CYP21A2/AS3MT/FAM166B/AMHR2/STAR/FAM43B/CYB561A3/FDXR/SNTB1/AADAC/IFITM10/KLHL4/SERPINA5/GSTA3/RMDN2/CYP11A1/FDX1/AKAP7/ABCB1/KCNK3/RGN/SLC16A9/RDX/KCNN2/MGARP/AKR1B1/ADGRV1/ASB4/ABCC3/NR5A1/KCNJ5/FNDC4/PORCN/SLC8B1/ALAS1/CYB5B/KLHDC8B/SLC37A2/ZNF117/SEMA6A/MRAP/GALM/TXN2/SREBF1/MRPL33/EPHX1/C4B/ZSWIM5/C2CD2
4 CYP11B1/CYP17A1/CYP21A2/AS3MT/FAM166B/AMHR2/STAR/CYB561A3/FDXR/SNTB1/AADAC/KLHL4/SERPINA5/GSTA3/RMDN2/CYP11A1/FDX1/AKAP7/ABCB1/KCNK3/RGN/SLC16A9/CYSLTR2/RDX/KCNN2/MGARP/AKR1B1/ADGRV1/ASB4/ABCC3/NR5A1/KCNJ5/GSTA1/PORCN/SLC8B1/ALAS1/CYB5B/ACSF2/KLHDC8B/DEXI/MRAP/GALM/SREBF1/MRPL33/SLC46A1/EPHX1/DLK1/ZSWIM5/C2CD2/INHA
5 CYP11B1/CYP17A1/CYP21A2/AS3MT/FAM166B/DBH/AMHR2/STAR/TH/CYB561A3/FDXR/SNTB1/AADAC/IFITM10/KLHL4/SERPINA5/GSTA3/RMDN2/CYP11A1/FDX1/AKAP7/ABCB1/KCNK3/RGN/SLC16A9/RDX/KCNN2/MGARP/NXPH1/AKR1B1/ASB4/ABCC3/NR5A1/KCNJ5/GSTA1/PORCN/SLC8B1/ALAS1/CYB5B/MCOLN3/KLHDC8B/DEXI/SEMA6A/MRAP/GALM/SREBF1/EPHX1/DLK1/ZSWIM5/C2CD2
6 CYP11B1/CYP17A1/CYP21A2/AS3MT/FAM166B/AMHR2/STAR/FAM43B/CYB561A3/FDXR/SNTB1/AADAC/IFITM10/KLHL4/GSTA3/RMDN2/CYP11A1/FDX1/AKAP7/ABCB1/KCNK3/RGN/SLC16A9/RDX/KCNN2/MGARP/NXPH1/AKR1B1/ADGRV1/ASB4/ABCC3/NR5A1/KCNJ5/FNDC4/GSTA1/PORCN/SLC8B1/ALAS1/CYB5B/MCOLN3/KLHDC8B/DEXI/SEMA6A/MRAP/GALM/SREBF1/EPHX1/DLK1/C4B/C2CD2
  Count
1 52
2 52
3 51
4 50
5 50
6 50

In [ ]:
sig_ora <- ora_all %>% dplyr::filter(p.adjust < FDR_THRESH)

detail <- selected_lvs %>%
    dplyr::rowwise() %>%
    dplyr::mutate(
        normalized_true_tissue = normalize_text(Tissue),
        n_sig_terms = sum(sig_ora$LV == LV),
        n_true_terms = sum(sig_ora$LV == LV & sig_ora$normalized_tissue == normalized_true_tissue),
        tissue_correct = n_true_terms > 0,
        best_any_padj = {
            x <- sig_ora$p.adjust[sig_ora$LV == LV]
            if (length(x) == 0) NA_real_ else min(x, na.rm = TRUE)
        },
        best_true_padj = {
            x <- sig_ora$p.adjust[sig_ora$LV == LV & sig_ora$normalized_tissue == normalized_true_tissue]
            if (length(x) == 0) NA_real_ else min(x, na.rm = TRUE)
        },
        matched_terms = paste(sig_ora$ID[sig_ora$LV == LV & sig_ora$normalized_tissue == normalized_true_tissue], collapse = ' | ')
    ) %>%
    dplyr::ungroup()

tissue_summary <- detail %>%
    dplyr::group_by(Tissue) %>%
    dplyr::summarise(
        n_selected_lvs = dplyr::n(),
        tissue_correct = any(tissue_correct),
        correct_lvs = paste(LV[tissue_correct], collapse = ';'),
        best_true_padj = if (all(is.na(best_true_padj))) NA_real_ else min(best_true_padj, na.rm = TRUE),
        .groups = 'drop'
    ) %>%
    dplyr::mutate(correct_score = as.integer(tissue_correct))

final_pct_tissue_correct <- 100 * mean(tissue_summary$tissue_correct)
final_summary <- data.frame(
    n_tissues = nrow(tissue_summary),
    n_tissues_correct = sum(tissue_summary$tissue_correct),
    pct_tissue_correct = final_pct_tissue_correct,
    stringsAsFactors = FALSE
)

write.csv(detail, file.path(OUT_DIR, 'gtex_global_alignment_detail.csv'), row.names = FALSE)
write.csv(tissue_summary, file.path(OUT_DIR, 'gtex_global_alignment_summary.csv'), row.names = FALSE)
write.csv(final_summary, file.path(OUT_DIR, 'gtex_global_alignment_final_pct.csv'), row.names = FALSE)

final_summary

  n_tissues n_tissues_correct pct_tissue_correct
1 23        21                91.30435

In [ ]:
tissue_summary %>%
    dplyr::arrange(Tissue)

   Tissue                              n_selected_lvs tissue_correct
1  Adrenal Gland                       1               TRUE
2  Artery - Tibial                     1               TRUE
3  Cells - Cultured fibroblasts        1               TRUE
4  Cells - EBV-transformed lymphocytes 1              FALSE
5  Colon - Transverse                  1               TRUE
6  Esophagus - Mucosa                  1               TRUE
7  Heart - Atrial Appendage            1               TRUE
8  Heart - Left Ventricle              1               TRUE
9  Kidney - Cortex                     1               TRUE
10 Liver                               1               TRUE
11 Lung                                1               TRUE
12 Muscle - Skeletal                   1               TRUE
13 Nerve - Tibial                      1               TRUE
14 Ovary                               1               TRUE
15 Pancreas                            1               TRUE
16 Pituitary                           1               TRUE
17 Prostate                            1               TRUE
18 Small Intestine - Terminal Ileum    1               TRUE
19 Stomach                             1               TRUE
20 Testis                              1               TRUE
21 Thyroid                             1               TRUE
22 Vagina                              1               TRUE
23 Whole Blood                         1              FALSE
   correct_lvs best_true_padj correct_score
1  LV183        8.202318e-63  1
2  LV563        3.743852e-05  1
3  LV546        8.440805e-59  1
4                         NA  0
5  LV562        1.194764e-43  1
6  LV84         2.870356e-82  1
7  LV420        2.313830e-62  1
8  LV505        1.936986e-78  1
9  LV229        7.554957e-44  1
10 LV21         3.218226e-60  1
11 LV26         4.239296e-43  1
12 LV137       3.982113e-102  1
13 LV329        3.772609e-73  1
14 LV330        2.350335e-19  1
15 LV450       6.131498e-100  1
16 LV105        4.177685e-31  1
17 LV174        1.770945e-08  1
18 LV452        5.068922e-61  1
19 LV227        7.782182e-75  1
20 LV299        1.372607e-44  1
21 LV246        3.902118e-77  1
22 LV80         1.655981e-51  1
23                        NA  0

In [ ]:
detail %>%
    dplyr::select(Tissue, LV, Rank, Mean_SHAP_Tissue, Cumulative_Percent,
                  tissue_correct, n_sig_terms, n_true_terms,
                  best_true_padj, matched_terms) %>%
    dplyr::arrange(Tissue, Rank)

   Tissue                              LV    Rank Mean_SHAP_Tissue
1  Adrenal Gland                       LV183 1    0.13753360
2  Artery - Tibial                     LV563 1    0.08563937
3  Cells - Cultured fibroblasts        LV546 1    0.11603051
4  Cells - EBV-transformed lymphocytes LV21  1    0.06096849
5  Colon - Transverse                  LV562 1    0.10610394
6  Esophagus - Mucosa                  LV84  1    0.13713745
7  Heart - Atrial Appendage            LV420 1    0.16581111
8  Heart - Left Ventricle              LV505 1    0.07538633
9  Kidney - Cortex                     LV229 1    0.15278041
10 Liver                               LV21  1    0.11317176
11 Lung                                LV26  1    0.15010394
12 Muscle - Skeletal                   LV137 1    0.14181925
13 Nerve - Tibial                      LV329 1    0.18907503
14 Ovary                               LV330 1    0.10650393
15 Pancreas                            LV450 1    0.11582342
16 Pituitary                           LV105 1    0.06718318
17 Prostate                            LV174 1    0.09906634
18 Small Intestine - Terminal Ileum    LV452 1    0.09925545
19 Stomach                             LV227 1    0.15247398
20 Testis                              LV299 1    0.12242106
21 Thyroid                             LV246 1    0.18365128
22 Vagina                              LV80  1    0.13772870
23 Whole Blood                         LV546 1    0.09567099
   Cumulative_Percent tissue_correct n_sig_terms n_true_terms best_true_padj
1  14.365823           TRUE          11          11            8.202318e-63
2   9.142689           TRUE          14          11            3.743852e-05
3  12.029419           TRUE          12          12            8.440805e-59
4   6.129557          FALSE          14           0                      NA
5  11.353268           TRUE          26          10            1.194764e-43
6  14.194683           TRUE          20          12            2.870356e-82
7  17.256570           TRUE          36          12            2.313830e-62
8   7.857362           TRUE          24          12            1.936986e-78
9  16.221166           TRUE          23           7            7.554957e-44
10 11.562922           TRUE          14          11            3.218226e-60
11 15.754183           TRUE          12          12            4.239296e-43
12 14.903882           TRUE          21          12           3.982113e-102
13 20.078495           TRUE          20          12            3.772609e-73
14 10.902846           TRUE          35           6            2.350335e-19
15 12.108141           TRUE          21          11           6.131498e-100
16  6.869564           TRUE          38          11            4.177685e-31
17 10.561153           TRUE          27           6            1.770945e-08
18 10.721531           TRUE          59          10            5.068922e-61
19 16.044456           TRUE          12          11            7.782182e-75
20 12.534167           TRUE           6           6            1.372607e-44
21 20.730621           TRUE          13          12            3.902118e-77
22 15.233942           TRUE          51           6            1.655981e-51
23 10.107371          FALSE          12           0                      NA
   matched_terms
1  GTEx_Tissues_Adrenal Gland Male 40-49 Up | GTEx_Tissues_Adrenal Gland Male 50-59 Up | GTEx_Tissues_Adrenal Gland Male 20-29 Up | GTEx_Tissues_Adrenal Gland Female 20-29 Up | GTEx_Tissues_Adrenal Gland Female 60-69 Up | GTEx_Tissues_Adrenal Gland Male 60-69 Up | GTEx_Tissues_Adrenal Gland Female 40-49 Up | GTEx_Tissues_Adrenal Gland Male 30-39 Up | GTEx_Tissues_Adrenal Gland Female 30-39 Up | GTEx_Tissues_Adrenal Gland Female 50-59 Up | GTEx_Tissues_Adrenal Gland Male 70-79 Up
2  GTEx_Tissues_Artery - Tibial Female 30-39 Up | GTEx_Tissues_Artery - Tibial Male 20-29 Up | GTEx_Tissues_Artery - Tibial Female 40-49 Up | GTEx_Tissues_Artery - Tibial Male 40-49 Up | GTEx_Tissues_Artery - Tibial Female 20-29 Up | GTEx_Tissues_Artery - Tibial Male 30-39 Up | GTEx_Tissues_Artery - Tibial Female 70-79 Up | GTEx_Tissues_Artery - Tibial Male 60-69 Up | GTEx_Tissues_Artery - Tibial Male 50-59 Up | GTEx_Tissues_Artery - Tibial Male 70-79 Up | GTEx_Tissues_Artery - Tibial Female 50-59 Up
3  GTEx_Tissues_Cells - Cultured Fibroblasts Female 40-49 Up | GTEx_Tissues_Cells - Cultured Fibroblasts Male 50-59 Up | GTEx_Tissues_Cells - Cultured Fibroblasts Male 60-69 Up | GTEx_Tissues_Cells - Cultured Fibroblasts Male 40-49 Up | GTEx_Tissues_Cells - Cultured Fibroblasts Female 50-59 Up | GTEx_Tissues_Cells - Cultured Fibroblasts Male 20-29 Up | GTEx_Tissues_Cells - Cultured Fibroblasts Female 60-69 Up | GTEx_Tissues_Cells - Cultured Fibroblasts Male 30-39 Up | GTEx_Tissues_Cells - Cultured Fibroblasts Male 70-79 Up | GTEx_Tissues_Cells - Cultured Fibroblasts Female 30-39 Up | GTEx_Tissues_Cells - Cultured Fibroblasts Female 20-29 Up | GTEx_Tissues_Cells - Cultured Fibroblasts Female 70-79 Up
4
5  GTEx_Tissues_Colon - Transverse Female 20-29 Up | GTEx_Tissues_Colon - Transverse Female 50-59 Up | GTEx_Tissues_Colon - Transverse Male 40-49 Up | GTEx_Tissues_Colon - Transverse Male 30-39 Up | GTEx_Tissues_Colon - Transverse Male 20-29 Up | GTEx_Tissues_Colon - Transverse Female 30-39 Up | GTEx_Tissues_Colon - Transverse Male 50-59 Up | GTEx_Tissues_Colon - Transverse Female 40-49 Up | GTEx_Tissues_Colon - Transverse Female 60-69 Up | GTEx_Tissues_Colon - Transverse Male 60-69 Up
6  GTEx_Tissues_Esophagus - Mucosa Male 40-49 Up | GTEx_Tissues_Esophagus - Mucosa Male 30-39 Up | GTEx_Tissues_Esophagus - Mucosa Male 50-59 Up | GTEx_Tissues_Esophagus - Mucosa Female 40-49 Up | GTEx_Tissues_Esophagus - Mucosa Male 20-29 Up | GTEx_Tissues_Esophagus - Mucosa Female 50-59 Up | GTEx_Tissues_Esophagus - Mucosa Female 20-29 Up | GTEx_Tissues_Esophagus - Mucosa Female 30-39 Up | GTEx_Tissues_Esophagus - Mucosa Female 60-69 Up | GTEx_Tissues_Esophagus - Mucosa Male 60-69 Up | GTEx_Tissues_Esophagus - Mucosa Female 70-79 Up | GTEx_Tissues_Esophagus - Mucosa Male 70-79 Up
7  GTEx_Tissues_Heart - Atrial Appendage Male 70-79 Up | GTEx_Tissues_Heart - Atrial Appendage Male 40-49 Up | GTEx_Tissues_Heart - Atrial Appendage Female 40-49 Up | GTEx_Tissues_Heart - Atrial Appendage Female 60-69 Up | GTEx_Tissues_Heart - Atrial Appendage Male 20-29 Up | GTEx_Tissues_Heart - Atrial Appendage Male 50-59 Up | GTEx_Tissues_Heart - Atrial Appendage Male 60-69 Up | GTEx_Tissues_Heart - Atrial Appendage Female 50-59 Up | GTEx_Tissues_Heart - Atrial Appendage Female 70-79 Up | GTEx_Tissues_Heart - Atrial Appendage Female 30-39 Up | GTEx_Tissues_Heart - Atrial Appendage Male 30-39 Up | GTEx_Tissues_Heart - Atrial Appendage Female 20-29 Up
8  GTEx_Tissues_Heart - Left Ventricle Female 50-59 Up | GTEx_Tissues_Heart - Left Ventricle Female 40-49 Up | GTEx_Tissues_Heart - Left Ventricle Female 60-69 Up | GTEx_Tissues_Heart - Left Ventricle Male 40-49 Up | GTEx_Tissues_Heart - Left Ventricle Female 30-39 Up | GTEx_Tissues_Heart - Left Ventricle Male 30-39 Up | GTEx_Tissues_Heart - Left Ventricle Male 50-59 Up | GTEx_Tissues_Heart - Left Ventricle Male 60-69 Up | GTEx_Tissues_Heart - Left Ventricle Female 20-29 Up | GTEx_Tissues_Heart - Left Ventricle Male 20-29 Up | GTEx_Tissues_Heart - Left Ventricle Female 70-79 Up | GTEx_Tissues_Heart - Left Ventricle Male 70-79 Up
9  GTEx_Tissues_Kidney - Cortex Female 50-59 Up | GTEx_Tissues_Kidney - Cortex Female 60-69 Up | GTEx_Tissues_Kidney - Cortex Male 70-79 Up | GTEx_Tissues_Kidney - Cortex Male 30-39 Up | GTEx_Tissues_Kidney - Cortex Male 60-69 Up | GTEx_Tissues_Kidney - Cortex Male 50-59 Up | GTEx_Tissues_Kidney - Cortex Male 40-49 Up
10 GTEx_Tissues_Liver Female 20-29 Up | GTEx_Tissues_Liver Male 50-59 Up | GTEx_Tissues_Liver Male 70-79 Up | GTEx_Tissues_Liver Female 60-69 Up | GTEx_Tissues_Liver Male 30-39 Up | GTEx_Tissues_Liver Female 50-59 Up | GTEx_Tissues_Liver Female 40-49 Up | GTEx_Tissues_Liver Male 40-49 Up | GTEx_Tissues_Liver Male 60-69 Up | GTEx_Tissues_Liver Female 30-39 Up | GTEx_Tissues_Liver Male 20-29 Up
11 GTEx_Tissues_Lung Female 50-59 Up | GTEx_Tissues_Lung Male 50-59 Up | GTEx_Tissues_Lung Male 30-39 Up | GTEx_Tissues_Lung Female 60-69 Up | GTEx_Tissues_Lung Male 40-49 Up | GTEx_Tissues_Lung Female 40-49 Up | GTEx_Tissues_Lung Female 20-29 Up | GTEx_Tissues_Lung Female 30-39 Up | GTEx_Tissues_Lung Female 70-79 Up | GTEx_Tissues_Lung Male 60-69 Up | GTEx_Tissues_Lung Male 20-29 Up | GTEx_Tissues_Lung Male 70-79 Up
12 GTEx_Tissues_Muscle - Skeletal Male 60-69 Up | GTEx_Tissues_Muscle - Skeletal Male 50-59 Up | GTEx_Tissues_Muscle - Skeletal Female 50-59 Up | GTEx_Tissues_Muscle - Skeletal Male 40-49 Up | GTEx_Tissues_Muscle - Skeletal Male 30-39 Up | GTEx_Tissues_Muscle - Skeletal Female 40-49 Up | GTEx_Tissues_Muscle - Skeletal Female 60-69 Up | GTEx_Tissues_Muscle - Skeletal Female 20-29 Up | GTEx_Tissues_Muscle - Skeletal Male 20-29 Up | GTEx_Tissues_Muscle - Skeletal Female 70-79 Up | GTEx_Tissues_Muscle - Skeletal Male 70-79 Up | GTEx_Tissues_Muscle - Skeletal Female 30-39 Up
13 GTEx_Tissues_Nerve - Tibial Male 50-59 Up | GTEx_Tissues_Nerve - Tibial Female 60-69 Up | GTEx_Tissues_Nerve - Tibial Female 50-59 Up | GTEx_Tissues_Nerve - Tibial Male 30-39 Up | GTEx_Tissues_Nerve - Tibial Male 60-69 Up | GTEx_Tissues_Nerve - Tibial Female 40-49 Up | GTEx_Tissues_Nerve - Tibial Male 20-29 Up | GTEx_Tissues_Nerve - Tibial Male 40-49 Up | GTEx_Tissues_Nerve - Tibial Male 70-79 Up | GTEx_Tissues_Nerve - Tibial Female 30-39 Up | GTEx_Tissues_Nerve - Tibial Female 20-29 Up | GTEx_Tissues_Nerve - Tibial Female 70-79 Up
14 GTEx_Tissues_Ovary Female 30-39 Up | GTEx_Tissues_Ovary Female 40-49 Up | GTEx_Tissues_Ovary Female 50-59 Up | GTEx_Tissues_Ovary Female 20-29 Up | GTEx_Tissues_Ovary Female 60-69 Up | GTEx_Tissues_Ovary Female 70-79 Up
15 GTEx_Tissues_Pancreas Male 40-49 Up | GTEx_Tissues_Pancreas Female 50-59 Up | GTEx_Tissues_Pancreas Male 60-69 Up | GTEx_Tissues_Pancreas Female 20-29 Up | GTEx_Tissues_Pancreas Female 40-49 Up | GTEx_Tissues_Pancreas Male 30-39 Up | GTEx_Tissues_Pancreas Female 60-69 Up | GTEx_Tissues_Pancreas Male 50-59 Up | GTEx_Tissues_Pancreas Female 30-39 Up | GTEx_Tissues_Pancreas Male 20-29 Up | GTEx_Tissues_Pancreas Male 70-79 Up
16 GTEx_Tissues_Pituitary Female 50-59 Up | GTEx_Tissues_Pituitary Male 50-59 Up | GTEx_Tissues_Pituitary Male 60-69 Up | GTEx_Tissues_Pituitary Male 70-79 Up | GTEx_Tissues_Pituitary Male 40-49 Up | GTEx_Tissues_Pituitary Female 60-69 Up | GTEx_Tissues_Pituitary Female 40-49 Up | GTEx_Tissues_Pituitary Male 20-29 Up | GTEx_Tissues_Pituitary Male 30-39 Up | GTEx_Tissues_Pituitary Female 20-29 Up | GTEx_Tissues_Pituitary Female 70-79 Up
17 GTEx_Tissues_Prostate Male 70-79 Up | GTEx_Tissues_Prostate Male 50-59 Up | GTEx_Tissues_Prostate Male 20-29 Up | GTEx_Tissues_Prostate Male 60-69 Up | GTEx_Tissues_Prostate Male 40-49 Up | GTEx_Tissues_Prostate Male 30-39 Up
18 GTEx_Tissues_Small Intestine - Terminal Ileum Male 50-59 Up | GTEx_Tissues_Small Intestine - Terminal Ileum Female 60-69 Up | GTEx_Tissues_Small Intestine - Terminal Ileum Male 60-69 Up | GTEx_Tissues_Small Intestine - Terminal Ileum Male 30-39 Up | GTEx_Tissues_Small Intestine - Terminal Ileum Male 40-49 Up | GTEx_Tissues_Small Intestine - Terminal Ileum Female 50-59 Up | GTEx_Tissues_Small Intestine - Terminal Ileum Female 30-39 Up | GTEx_Tissues_Small Intestine - Terminal Ileum Male 20-29 Up | GTEx_Tissues_Small Intestine - Terminal Ileum Female 40-49 Up | GTEx_Tissues_Small Intestine - Terminal Ileum Female 20-29 Up
19 GTEx_Tissues_Stomach Male 60-69 Up | GTEx_Tissues_Stomach Male 40-49 Up | GTEx_Tissues_Stomach Male 30-39 Up | GTEx_Tissues_Stomach Female 60-69 Up | GTEx_Tissues_Stomach Male 50-59 Up | GTEx_Tissues_Stomach Female 50-59 Up | GTEx_Tissues_Stomach Female 30-39 Up | GTEx_Tissues_Stomach Female 20-29 Up | GTEx_Tissues_Stomach Female 40-49 Up | GTEx_Tissues_Stomach Male 20-29 Up | GTEx_Tissues_Stomach Male 70-79 Up
20 GTEx_Tissues_Testis Male 60-69 Up | GTEx_Tissues_Testis Male 30-39 Up | GTEx_Tissues_Testis Male 20-29 Up | GTEx_Tissues_Testis Male 50-59 Up | GTEx_Tissues_Testis Male 40-49 Up | GTEx_Tissues_Testis Male 70-79 Up
21 GTEx_Tissues_Thyroid Male 30-39 Up | GTEx_Tissues_Thyroid Male 40-49 Up | GTEx_Tissues_Thyroid Male 20-29 Up | GTEx_Tissues_Thyroid Female 20-29 Up | GTEx_Tissues_Thyroid Female 40-49 Up | GTEx_Tissues_Thyroid Male 50-59 Up | GTEx_Tissues_Thyroid Male 60-69 Up | GTEx_Tissues_Thyroid Female 50-59 Up | GTEx_Tissues_Thyroid Female 30-39 Up | GTEx_Tissues_Thyroid Female 60-69 Up | GTEx_Tissues_Thyroid Female 70-79 Up | GTEx_Tissues_Thyroid Male 70-79 Up
22 GTEx_Tissues_Vagina Female 40-49 Up | GTEx_Tissues_Vagina Female 50-59 Up | GTEx_Tissues_Vagina Female 20-29 Up | GTEx_Tissues_Vagina Female 30-39 Up | GTEx_Tissues_Vagina Female 60-69 Up | GTEx_Tissues_Vagina Female 70-79 Up
23

In [27]:
expected_rows <- N_LVS_PER_TISSUE * dplyr::n_distinct(shap_all$Tissue)
stopifnot(nrow(detail) == expected_rows)
stopifnot(nrow(tissue_summary) == dplyr::n_distinct(shap_all$Tissue))
stopifnot(file.exists(file.path(OUT_DIR, 'gtex_tissue_ora_per_lv.csv')))
stopifnot(file.exists(file.path(OUT_DIR, 'gtex_global_alignment_detail.csv')))
stopifnot(file.exists(file.path(OUT_DIR, 'gtex_global_alignment_summary.csv')))
stopifnot(file.exists(file.path(OUT_DIR, 'gtex_global_alignment_final_pct.csv')))
cat('Checks passed. Denominator =', nrow(tissue_summary), 'tissues and', nrow(detail), 'selected LV/tissue rows.\n')
cat('Final % tissue correct =', sprintf('%.2f', final_pct_tissue_correct), '\n')

Checks passed. Denominator = 23 tissues and 23 selected LV/tissue rows.
Final % tissue correct = 91.30