# GTEx model with different priors

## Load libraries

In [4]:
library(bigstatsr)
library(data.table)
library(dplyr)
library(rsvd)
library(glmnet)
library(Matrix)
library(knitr)
library(here)
library(CLAMP)

source(here("config.R"))

## Output directory

In [5]:
output_data_dir <- config$GTEx$DATASET_FOLDER
dir.create(output_data_dir, showWarnings = FALSE, recursive = TRUE)

# GTEx model with different priors

In [27]:
options(repr.matrix.max.rows = Inf)

# List all saved models, omitting "prior_PLIER" and "all"
rds_files <- list.files(output_data_dir, pattern = "^gtex_.*_CLAMP\\.rds$", full.names = TRUE)
rds_files <- rds_files[!grepl("prior_PLIER|all", rds_files)]

summaries <- list()

for (file in rds_files) {
  prior_name <- sub("^gtex_(.*)_CLAMP\\.rds$", "\\1", basename(file))
  message("Reading summary for: ", prior_name)

  res <- readRDS(file)
  if (!is.null(res$summary)) {
    summaries[[prior_name]] <- res$summary %>%
      dplyr::filter(FDR < 0.05 & AUC > 0.7)
  }
}

# Combine into one data frame with prior name column
all_summaries <- dplyr::bind_rows(
  lapply(names(summaries), function(p) {
    dplyr::mutate(summaries[[p]], prior = p)
  })
)

Reading summary for: CellMarker_2024

Reading summary for: Chromosome_Location

Reading summary for: GO_Biological_Process_2025

Reading summary for: GTEx_Tissues_V8_2023

Reading summary for: GWAS_Catalog_2025

Reading summary for: Human_Gene_Atlas

Reading summary for: KEGG_2021_Human

Reading summary for: LINCS_L1000_CRISPR_KO_Consensus_Sigs

Reading summary for: Metabolomics_Workbench_Metabolites_2022

Reading summary for: OMIM_Disease

Reading summary for: Proteomics_Drug_Atlas_2023

Reading summary for: TF_Perturbations_Followed_by_Expression

Reading summary for: UK_Biobank_GWAS_v1

In [28]:
all_summaries %>%
    dplyr::mutate(pathway_prior = paste0(prior, '_', pathway)) %>%
    dplyr::select(LV, pathway_prior) %>%
    dplyr::group_by(LV) %>%
    dplyr::summarise(pathway_prior = paste(pathway_prior, collapse = ', '), .groups = "drop") %>%
    dplyr::arrange(as.numeric(gsub("[^0-9]", "", LV)))

    LV
1   LV1
2   LV2
3   LV3
4   LV4
5   LV5
6   LV6
7   LV7
8   LV8
9   LV9
10  LV10
11  LV11
12  LV12
13  LV13
14  LV14
15  LV15
16  LV16
17  LV17
18  LV18
19  LV19
20  LV20
21  LV21
22  LV22
23  LV23
24  LV24
25  LV25
26  LV26
27  LV27
28  LV28
29  LV29
30  LV30
31  LV31
32  LV32
33  LV34
34  LV35
35  LV36
36  LV37
37  LV38
38  LV39
39  LV40
40  LV41
41  LV42
42  LV43
43  LV44
44  LV46
45  LV47
46  LV48
47  LV50
48  LV51
49  LV52
50  LV54
51  LV55
52  LV56
53  LV57
54  LV59
55  LV60
56  LV61
57  LV62
58  LV63
59  LV64
60  LV65
61  LV67
62  LV68
63  LV69
64  LV70
65  LV71
66  LV73
67  LV74
68  LV75
69  LV76
70  LV78
71  LV79
72  LV80
73  LV81
74  LV82
75  LV83
76  LV84
77  LV85
78  LV86
79  LV87
80  LV88
81  LV89
82  LV90
83  LV91
84  LV93
85  LV94
86  LV95
87  LV96
88  LV98
89  LV99
90  LV100
91  LV101
92  LV103
93  LV104
94  LV105
95  LV106
96  LV107
97  LV108
98  LV109
99  LV110
100 LV111
101 LV112
102 LV113
103 LV114
104 LV115
105 LV116
106 LV117
107 LV118
108 LV119
109 LV120
110 LV121
111 LV122
112 LV123
113 LV124
114 LV126
115 LV127
116 LV128
117 LV129
118 LV130
119 LV131
120 LV132
121 LV133
122 LV134
123 LV135
124 LV136
125 LV137
126 LV138
127 LV139
128 LV140
129 LV141
130 LV142
131 LV143
132 LV144
133 LV145
134 LV146
135 LV147
136 LV149
137 LV151
138 LV152
139 LV153
140 LV155
141 LV158
142 LV160
143 LV161
144 LV162
145 LV163
146 LV164
147 LV166
148 LV170
149 LV171
150 LV172
151 LV173
152 LV174
153 LV175
154 LV176
155 LV177
156 LV179
157 LV180
158 LV181
159 LV182
160 LV183
161 LV184
162 LV186
163 LV187
164 LV188
165 LV190
166 LV191
167 LV194
168 LV195
169 LV196
170 LV197
171 LV198
172 LV199
173 LV200
174 LV201
175 LV202
176 LV203
177 LV204
178 LV206
179 LV207
180 LV209
181 LV211
182 LV212
183 LV213
184 LV214
185 LV215
186 LV216
187 LV217
188 LV218
189 LV219
190 LV220
191 LV221
192 LV224
193 LV225
194 LV226
195 LV227
196 LV228
197 LV229
198 LV230
199 LV231
200 LV232
201 LV233
202 LV236
203 LV238
204 LV239
205 LV240
206 LV242
207 LV243
208 LV244
209 LV246
210 LV247
211 LV248
212 LV249
213 LV250
214 LV251
215 LV252
216 LV253
217 LV254
218 LV256
219 LV257
220 LV258
221 LV259
222 LV262
223 LV263
224 LV264
225 LV266
226 LV267
227 LV268
228 LV269
229 LV270
230 LV271
231 LV272
232 LV274
233 LV275
234 LV277
235 LV279
236 LV280
237 LV282
238 LV284
239 LV285
240 LV286
241 LV287
242 LV289
243 LV290
244 LV291
245 LV292
246 LV293
247 LV295
248 LV297
249 LV298
250 LV299
251 LV300
252 LV301
253 LV303
254 LV304
255 LV305
256 LV306
257 LV307
258 LV309
259 LV310
260 LV311
261 LV312
262 LV313
263 LV314
264 LV317
265 LV318
266 LV319
267 LV320
268 LV322
269 LV323
270 LV324
271 LV328
272 LV329
273 LV330
274 LV333
275 LV334
276 LV336
277 LV337
278 LV338
279 LV340
280 LV341
281 LV342
282 LV343
283 LV344
284 LV345
285 LV346
286 LV349
287 LV350
288 LV351
289 LV352
290 LV354
291 LV356
292 LV358
293 LV360
294 LV361
295 LV362
296 LV363
297 LV365
298 LV366
299 LV369
300 LV370
301 LV371
302 LV374
303 LV375
304 LV376
305 LV378
306 LV379
307 LV380
308 LV381
309 LV382
310 LV383
311 LV385
312 LV386
313 LV389
314 LV390
315 LV391
316 LV392
317 LV393
318 LV394
319 LV396
320 LV397
321 LV398
322 LV399
323 LV402
324 LV404
325 LV406
326 LV409
327 LV410
328 LV411
    pathway_prior
1   Human_Gene_Atlas_UterusCorpus, TF_Perturbations_Followed_by_Expression_MAF OE MACROPHAGE HUMAN GSE98368 RNASEQ DOWN
2   GO_Biological_Process_2025_Synaptic Vesicle Cycle (GO:0099504), GTEx_Tissues_V8_2023_Brain - Frontal Cortex (BA9) Male 50-59 Up, GTEx_Tissues_V8_2023_Brain - Frontal Cortex (BA9) Female 60-69 Up, GTEx_Tissues_V8_2023_Brain - Anterior Cingulate Cortex (BA24) Female 50-59 Up, GTEx_Tissues_V8_2023_Brain - Frontal Cortex (BA9) Male 20-29 Up, GTEx_Tissues_V8_2023_Brain - Frontal Cortex (BA9) Male 70-79 Up, GTEx_Tissues_V8_2023_Brain - Frontal Cortex (BA9) Female 40-49 Up, GTEx_Tissues_V8_2023_Brain - Frontal Cortex (BA9) Female 50-59 Up, GTEx_Tissues_V8_2023_Brain - Frontal Cortex (BA9) Male 40-49 Up, GTEx_Tissues_V8_2023_Brain - Anterior Cingulate Cortex (BA24) Female 20-29 Up, Human_Gene_Atlas_Cerebellum, Human_Gene_Atlas_Thalamus, Human_Gene_Atlas_Wholebrain, Human_Gene_Atlas_Fetalbrain, Human_Gene_Atlas_OccipitalLobe, Human_Gene_Atlas_Amygdala, Human_Gene_Atlas_PrefrontalCortex, KEGG_2021_Human_GABAergic synapse, KEGG_2021_Human_Insulin secretion, KEGG_2021_Human_Nicotine addiction, KEGG_2021_Human_Synaptic vesicle cycle, OMIM_Disease_epilepsy, TF_Perturbations_Followed_by_Expression_HIVEP2 KO MOUSE GSE41307 CREEDSID GENE 3094 UP, TF_Perturbations_Followed_by_Expression_NFIA DEFICIENCY MOUSE GSE4623 CREEDSID GENE 667 DOWN, TF_Perturbations_Followed_by_Expression_MEF2A KD MOUSE GSE47150 CREEDSID GENE 957 DOWN, TF_Perturbations_Followed_by_Expression_MECP2 KD MOUSE GSE47150 CREEDSID GENE 951 DOWN, TF_Perturbations_Followed_by_Expression_MEF2D KD MOUSE GSE47150 CREEDSID GENE 956 DOWN
3   CellMarker_2024_Neutrophil Kidney Human, CellMarker_2024_Neutrophil Peripheral Blood Human, CellMarker_2024_Neutrophil Stomach Human, GTEx_Tissues_V8_2023_Whole Blood Female 50-59 Up, GTEx_Tissues_V8_2023_Whole Blood Male 50-59 Up, GTEx_Tissues_V8_2023_Whole Blood Female 20-29 Up, GTEx_Tissues_V8_2023_Whole Blood Male 30-39 Up, GTEx_Tissues_V8_2023_Whole Blood Female 30-39 Up, GTEx_Tissues_V8_2023_Whole Blood Male 20-29 Up, GTEx_Tissues_V8_2023_Whole Blood Female 40-49 Up, Human_Gene_Atlas_CD33+ Myeloid, Human_Gene_Atlas_Bonemarrow, Human_Gene_Atlas_WholeBlood, TF_Perturbations_Followed_by_Expression_EZH2 SHRNA PROE HUMAN GSE59089 RNASEQ UP
4   CellMarker_2024_Fibroblast Undefined Mouse, GTEx_Tissues_V8_2023_Adipose - Subcutaneous Male 50-59 Up, GTEx_Tissues_V8_2023_Adipose - Subcutaneous Male 60-69 Up, GTEx_Tissues_V8_2023_Adipose - Subcutaneous Male 40-49 Up, GTEx_Tissues_V8_2023_Cells - Cultured Fibroblasts Male 30-39 Up, GTEx_Tissues_V8_2023_Adipose - Subcutaneous Female 50-59 Up, GTEx_Tissues_V8_2023_Breast - Mammary Tissue Male 70-79 Up, GTEx_Tissues_V8_2023_Cervix - Ectocervix Female 40-49 Up, GTEx_Tissues_V8_2023_Cervix - Endocervix Female 40-49 Up, Human_Gene_Atlas_Adipocyte, Human_Gene_Atlas_Uterus, KEGG_2021_Human_Glycosaminoglycan biosynthesis, KEGG_2021_Human_Malaria, LINCS_L1000_CRISPR_KO_Consensus_Sigs_PDE4D Down, LINCS_L1000_CRISPR_KO_Consensus_Sigs_RGS7 Down, TF_Perturbations_Followed_by_Expression_FLI1 KD HUMAN GSE27524 CREEDSID GENE 1599 UP, TF_Perturbations_Followed_by_Expression_FLI1 KD HUMAN GSE27524 CREEDSID GENE 1596 UP, TF_Perturbations_Followed_by_Expression_FLI1 KD HUMAN GSE27524 CREEDSID GENE 1597 UP, TF_Perturbations_Followed_by_Expression_SRF KO MOUSE GSE34545 CREEDSID GENE 2884 UP, TF_Perturbations_Followed_by_Expression_FLI1 KD HUMAN GSE27524 CREEDSID GENE 1607 UP, TF_Perturbations_Followed_by_Expression_ARX SIRNA BCD HUMAN GSE73433 RNASEQ UP, TF_Perturbations_Followed_by_Expression_REST SHRNA C2 HUMAN GSE90068 PBMPA RNASEQ DOWN
5   CellMarker_2024_Basal Cell Bladder Human, CellMarker_2024_Basal Cell Lung Human, CellMarker_2024_Keratinocyte Skin Human, GO_Biological_Process_2025_Intermediate Filament Organization (GO:0045109), GO_Biological_Process_2025_Keratinocyte Differentiation (GO:0030216), GO_Biological_Process_2025_Peptide Cross-Linking (GO:0018149), GTEx_Tissues_V8_2023_Esophagus - Mucosa Male 50-59 Up, GTEx_Tissues_V8_2023_Esophagus - Mucosa Female 60-69 Up, GTEx_Tissues_V8_2023_Esophagus - Mucosa Female 20-29 Up, GTEx_Tissues_V8_2023_Esophagus - Mucosa Male 30-39 Up, GTEx_Tissues_V8_2023_Esophagus - Mucosa Male 20-29 Up, GTEx_Tissues_V8_2023_Esophagus - Mucosa Female 40-49 Up, GTEx_Tissues_V8_2023_Esophagus - Mucosa Male 40-49 Up, GTEx_Tissues_V8_2023_Esophagus - Mucosa Female 70-79 Up, Human_Gene_Atlas_Tongue, TF_Perturbations_Followed_by_Expression_OVOL1 KO MOUSE GSE55072 CREEDSID GENE 2617 UP
6   GTEx_Tissues_V8_2023_Testis Male 50-59 Up, GTEx_Tissues_V8_2023_Testis Male 60-69 Up, GTEx_Tissues_V8_2023_Testis Male 30-39 Up, GTEx_Tissues_V8_2023_Testis Male 20-29 Up, GTEx_Tissues_V8_2023_Testis Male 40-49 Up, GTEx_Tissues_V8_2023_Testis Male 70-79 Up, Human_Gene_Atlas_Testis, Human_Gene_Atlas_TestisLeydigCell, Human_Gene_Atlas_TestisIntersitial, Human_Gene_Atlas_TestisGermCell, TF_Perturbations_Followed_by_Expression_DMRT1 KO MOUSE GSE27261 CREEDSID GENE 2740 DOWN
7   GTEx_Tissues_V8_2023_Muscle - Skeletal Male 50-59 Up, GTEx_Tissues_V8_2023_Muscle - Skeletal Female 20-29 Up
8   CellMarker_2024_Basal Cell Bladder Human, CellMarker_2024_Basal Cell Lung Human, GO_Biological_Process_2025_Keratinocyte Differentiation (GO:0030216), GO_Biological_Process_2025_Peptide Cross-Linking (GO:0018149), GTEx_Tissues_V8_2023_Skin - Sun Exposed (Lower Leg) Female 60-69 Up, GTEx_Tissues_V8_2023_Skin - Sun Exposed (Lower Leg) Female 50-59 Up, GTEx_Tissues_V8_2023_Skin - Sun Exposed (Lower Leg) Male 50-59 Up, GTEx_Tissues_V8_2023_Skin - Sun Exposed (Lower Leg) Male 40-49 Up, GTEx_Tissues_V8_2023_Skin - Sun Exposed (Lower Leg) Male 30-39 Up, GTEx_Tissues_V8_2023_Skin - Sun Exposed (Lower Leg) Male 20-29 Up, GTEx_Tissues_V8_2023_Skin - Sun Exposed (Lower Leg) Male 70-79 Up, GTEx_Tissues_V8_2023_Skin - Sun Exposed (Lower Leg) Female 70-79 Up, Human_Gene_Atlas_Tongue, Human_Gene_Atlas_Skin, LINCS_L1000_CRISPR_KO_Consensus_Sigs_KRAS-2A Down
9   GTEx_Tissues_V8_2023_Adipose - Visceral (Omentum) Male 50-59 Up, GTEx_Tissues_V8_2023_Lung Male 60-69 Up, GTEx_Tissues_V8_2023_Adipose - Visceral (Omentum) Male 60-69 Up, GTEx_Tissues_V8_2023_Lung Female 60-69 Up, GTEx_Tissues_V8_2023_Adipose - Visceral (Omentum) Male 40-49 Up, GTEx_Tissues_V8_2023_Breast - Mammary Tissue Male 70-79 Up, GTEx_Tissues_V8_2023_Lung Male 70-79 Up, GTEx_Tissues_V8_2023_Lung Female 70-79 Up, Human_Gene_Atlas_Lung, LINCS_L1000_CRISPR_KO_Consensus_Sigs_SLC12A5 Down, TF_Perturbations_Followed_by_Expression_POU5F1 KD HUMAN GSE21135 CREEDSID GENE 1328 UP, TF_Perturbations_Followed_by_Expression_EZH2 SHRNA HUVEC HUMAN GSE71164 SHEARSTRESS RNASEQ DOWN
10  GO_Biological_Process_2025_Aerobic Electron Transport Chain (GO:0019646), GO_Biological_Process_2025_Aerobic Respiration (GO:0009060), GO_Biological_Process_2025_Cellular Respiration (GO:0045333), GO_Biological_Process_2025_Mitochondrial ATP Synthesis Coupled Electron Transport (GO:0042775), GO_Biological_Process_2025_Proton Motive Force-Driven ATP Synthesis (GO:0015986), GO_Biological_Process_2025_Proton Motive Force-Driven Mitochondrial ATP Synthesis (GO:0042776), KEGG_2021_Human_Diabetic cardiomyopathy, KEGG_2021_Human_Huntington disease, KEGG_2021_Human_Non-alcoholic fatty liver disease, KEGG_2021_Human_Oxidative phosphorylation, KEGG_2021_Human_Parkinson disease, KEGG_2021_Human_Prion disease, KEGG_2021_Human_Proteasome, Proteomics_Drug_Atlas_2023_Desipramine Down, Proteomics_Drug_Atlas_2023_Guanfacine Down, TF_Perturbations_Followed_by_Expression_MYOD1 MUT MOUSE GSE6487 CREEDSID GENE 1178 UP, TF_Perturbations_Followed_by_Expression_RELA KD HUMAN GSE1676 CREEDSID GENE 1787 UP, TF_Perturbations_Followed_by_Expression_SON KD HUMAN GSE26888 CREEDSID GENE 62 UP, TF_Perturbations_Followed_by_Expression_SOX10 KO MOUSE GSE12007 CREEDSID GENE 284 UP, TF_Perturbations_Followed_by_Expression_NFKB1 INACTIVATION HUMAN GSE20667 CREEDSID GENE 2576 DOWN, TF_Perturbations_Followed_by_Expression_FOXP1 KD HUMAN GSE51382 CREEDSID GENE 2764 DOWN, TF_Perturbations_Followed_by_Expression_SOX4 KD HUMAN GSE4225 CREEDSID GENE 64 DOWN, TF_Perturbations_Followed_by_Expression_SON KD HUMAN GSE26888 CREEDSID GENE 890 DOWN, TF_Perturbations_Followed_by_Expression_NEUROG3 OE MOUSE GSE3653 CREEDSID GENE 1658 DOWN
11  CellMarker_2024_Enterocyte Large Intestine Human, CellMarker_2024_Epithelial Cell Colon Human, CellMarker_2024_Goblet Cell Large Intestine Human, CellMarker_2024_LGR5+ Stem Cell Large Intestine Human, GTEx_Tissues_V8_2023_Colon - Transverse Male 50-59 Up, GTEx_Tissues_V8_2023_Colon - Transverse Female 60-69 Up, GTEx_Tissues_V8_2023_Colon - Transverse Female 20-29 Up, GTEx_Tissues_V8_2023_Colon - Transverse Male 30-39 Up, GTEx_Tissues_V8_2023_Colon - Transverse Female 50-59 Up, GTEx_Tissues_V8_2023_Colon - Transverse Male 20-29 Up, GTEx_Tissues_V8_2023_Colon - Transverse Male 40-49 Up, GTEx_Tissues_V8_2023_Colon - Transverse Female 30-39 Up, GTEx_Tissues_V8_2023_Colon - Transverse Female 40-49 Up, Human_Gene_Atlas_colon, Human_Gene_Atlas_Pancreas, LINCS_L1000_CRISPR_KO_Consensus_Sigs_POPDC3 Up, LINCS_L1000_CRISPR_KO_Consensus_Sigs_ABCC9 Down, TF_Perturbations_Followed_by_Expression_TCF4 KD HUMAN GSE18560 CREEDSID GENE 1275 UP
12  CellMarker_2024_Cycling Basal Cell Trachea Mouse, CellMarker_2024_FOXN4+ Cell Lung Human, CellMarker_2024_Fibroblast Lung Mouse, CellMarker_2024_Neural Progenitor Cell Embryonic Prefrontal Cortex Human, GTEx_Tissues_V8_2023_Cells - EBV-transformed Lymphocytes Female 40-49 Up, GTEx_Tissues_V8_2023_Cells - Cultured Fibroblasts Female 70-79 Up, Human_Gene_Atlas_CD105+ Endothelial, Human_Gene_Atlas_Leukemialymphoblastic(MOLT-4), KEGG_2021_Human_Cell cycle, KEGG_2021_Human_DNA replication, KEGG_2021_Human_Homologous recombination, KEGG_2021_Human_Mismatch repair, LINCS_L1000_CRISPR_KO_Consensus_Sigs_PIP4K2C Up, LINCS_L1000_CRISPR_KO_Consensus_Sigs_CDK4 Down, LINCS_L1000_CRISPR_KO_Consensus_Sigs_CDK6 Down, LINCS_L1000_CRISPR_KO_Consensus_Sigs_CDK7 Down, LINCS_L1000_CRISPR_KO_Consensus_Sigs_DTL Down, LINCS_L1000_CRISPR_KO_Consensus_Sigs_TOP2A Down, LINCS_L1000_CRISPR_KO_Consensus_Sigs_XPO1 Down, Proteomics_Drug_Atlas_2023_UNC2250 Down, Proteomics_Drug_Atlas_2023_MI-773 Down, Proteomics_Drug_Atlas_2023_AZD4547 Down, Proteomics_Drug_Atlas_2023_Palbociclib Down, Proteomics_Drug_Atlas_2023_GR79236 Up, Proteomics_Drug_Atlas_2023_PDE-9i Up, Proteomics_Drug_Atlas_2023_Ribociclib Down, Proteomics_Drug_Atlas_2023_Nutlin3a Down, Proteomics_Drug_Atlas_2023_Idasanutlin Down, TF_Perturbations_Followed_by_Expression_ZNF750 KD HUMAN GSE38039 CREEDSID GENE 204 UP, TF_Perturbations_Followed_by_Expression_FLI1 KD HUMAN GSE27524 CREEDSID GENE 1599 DOWN, TF_Perturbations_Followed_by_Expression_FLI1 KD HUMAN GSE27524 CREEDSID GENE 1596 DOWN, TF_Perturbations_Followed_by_Expression_ZNF750 KD HUMAN GSE38039 CREEDSID GENE 2704 DOWN, TF_Perturbations_Followed_by_Expression_FLI1 KD HUMAN GSE27524 CREEDSID GENE 1597 DOWN, TF_Perturbations_Followed_by_Expression_TFAP2C KD HUMAN GSE15481 CREEDSID GENE 2968 DOWN, TF_Perturbations_Followed_by_Expression_TFAP2C SIRNA HUMAN GSE15481 CREEDSID GENE 2893 DOWN, TF_Perturbations_Followed_by_Expression_MYB KD HUMAN GSE49286 CREEDSID GENE 1842 DOWN, TF_Perturbations_Followed_by_Expression_FOXA1 KD HUMAN GSE25315 CREEDSID GENE 2164 DOWN, TF_Perturbations_Followed_by_Expression_FLI1 KD HUMAN GSE27524 CREEDSID GENE 1594 DOWN
13  CellMarker_2024_Pluripotent Stem Cell Skeletal Muscle Human, GTEx_Tissues_V8_2023_Heart - Atrial Appendage Male 60-69 Up, GTEx_Tissues_V8_2023_Heart - Atrial Appendage Male 40-49 Up, GTEx_Tissues_V8_2023_Heart - Atrial Appendage Female 50-59 Up, GTEx_Tissues_V8_2023_Heart - Atrial Appendage Female 40-49 Up, GTEx_Tissues_V8_2023_Heart - Atrial Appendage Male 70-79 Up, GTEx_Tissues_V8_2023_Heart - Left Ventricle Male 70-79 Up, GTEx_Tissues_V8_2023_Heart - Atrial Appendage Female 70-79 Up, TF_Perturbations_Followed_by_Expression_ZNF503 SHRNA H1 HUMAN GSE69618 DAY6 RNASEQ DOWN
14  CellMarker_2024_Meiotic Prophase Fetal Germ Cell Fetal Gonad Human, CellMarker_2024_Morula Cell (Blastomere) Embryo Human, CellMarker_2024_Oocyte Embryo Human, Human_Gene_Atlas_721 B lymphoblasts, KEGG_2021_Human_Basal transcription factors, KEGG_2021_Human_Ubiquitin mediated proteolysis, KEGG_2021_Human_mRNA surveillance pathway, LINCS_L1000_CRISPR_KO_Consensus_Sigs_IL11 Up, LINCS_L1000_CRISPR_KO_Consensus_Sigs_GUCY2D Down, LINCS_L1000_CRISPR_KO_Consensus_Sigs_MEOX1 Down, LINCS_L1000_CRISPR_KO_Consensus_Sigs_SDF2 Down, TF_Perturbations_Followed_by_Expression_HSF1 KD HUMAN GSE3697 CREEDSID GENE 778 UP, TF_Perturbations_Followed_by_Expression_HSF1 KD HUMAN GSE3697 CREEDSID GENE 780 UP, TF_Perturbations_Followed_by_Expression_SOX11 DEPLETION HUMAN GSE34763 CREEDSID GENE 353 UP, TF_Perturbations_Followed_by_Expression_POU4F1 KO MOUSE GSE19997 CREEDSID GENE 2108 UP, TF_Perturbations_Followed_by_Expression_TCF3 KO MOUSE GSE19923 CREEDSID GENE 2167 UP, TF_Perturbations_Followed_by_Expression_MYC OE MCF7 HUMAN GSE101738 RNASEQ UP, TF_Perturbations_Followed_by_Expression_SNAI1 KO MOUSE GSE53107 CREEDSID GENE 1448 DOWN, TF_Perturbations_Followed_by_Expression_CHD1 KD 22RV1 HUMAN GSE84610 RNASEQ DOWN, TF_Perturbations_Followed_by_Expression_CHD1 KO 22RV1 HUMAN GSE84610 RNASEQ DOWN
15  Chromosome_Location_chr19p13, Chromosome_Location_chr9q34, Chromosome_Location_chr11q13, Chromosome_Location_chr17q25, Chromosome_Location_chr16p13, Human_Gene_Atlas_Liver, Human_Gene_Atlas_Heart, Human_Gene_Atlas_Lymphoma burkitts(Raji), LINCS_L1000_CRISPR_KO_Consensus_Sigs_RBM10 Up, LINCS_L1000_CRISPR_KO_Consensus_Sigs_MDM4 Down, LINCS_L1000_CRISPR_KO_Consensus_Sigs_MPV17 Down, LINCS_L1000_CRISPR_KO_Consensus_Sigs_VAMP5 Down, Proteomics_Drug_Atlas_2023_PHA 767491 Up, TF_Perturbations_Followed_by_Expression_SNAI1 KO MOUSE GSE53107 CREEDSID GENE 1448 UP, TF_Perturbations_Followed_by_Expression_SETDB1 KD THP1 HUMAN GSE103409 SGRNA6DAY4 RNASEQ UP, TF_Perturbations_Followed_by_Expression_SETDB1 KD THP1 HUMAN GSE103409 SGRNA9DAY7 RNASEQ UP, TF_Perturbations_Followed_by_Expression_NFE2L2 KO MOUSE GSE18344 CREEDSID GENE 1258 DOWN, TF_Perturbations_Followed_by_Expression_NFE2L2 KO MOUSE GSE18344 CREEDSID GENE 1260 DOWN, TF_Perturbations_Followed_by_Expression_NFE2L2 KO MOUSE GSE18344 CREEDSID GENE 1259 DOWN, TF_Perturbations_Followed_by_Expression_MEIS2 KD KASUMI1 HUMAN GSE81328 RNASEQ DOWN, TF_Perturbations_Followed_by_Expression_MYCN SHRNA IMR575 HUMAN GSE80397 12HR RNASEQ DOWN
16  CellMarker_2024_Neural Stem Cell Brain Human, GO_Biological_Process_2025_Peripheral Nervous System Development (GO:0007422), GTEx_Tissues_V8_2023_Nerve - Tibial Male 50-59 Up, GTEx_Tissues_V8_2023_Nerve - Tibial Male 60-69 Up, GTEx_Tissues_V8_2023_Nerve - Tibial Female 60-69 Up, GTEx_Tissues_V8_2023_Nerve - Tibial Female 50-59 Up, GTEx_Tissues_V8_2023_Nerve - Tibial Male 70-79 Up, GTEx_Tissues_V8_2023_Nerve - Tibial Female 70-79 Up, TF_Perturbations_Followed_by_Expression_HNF1A OE LNCAP HUMAN GSE85556 RNASEQ UP

In [8]:
summ_all_summaries  <- all_summaries %>%
    dplyr::mutate(pathway_prior = paste0(prior, '_', pathway)) %>%
    dplyr::select(LV, pathway_prior) %>%
    dplyr::group_by(LV) %>%
    dplyr::summarise(pathway_prior = paste(pathway_prior, collapse = ', '), .groups = "drop") %>%
    dplyr::arrange(as.numeric(gsub("[^0-9]", "", LV)))

saveRDS(summ_all_summaries, file = file.path(output_data_dir, "all_summaries.rds"))

In [23]:
options(repr.matrix.max.rows = Inf)

gtex_fullRes_full <- readRDS(file.path(output_data_dir, "gtex_all_CLAMP.rds"))

gtex_fullRes_full_summ  <- gtex_fullRes_full$summary  %>% 
dplyr::filter(FDR < 0.05 & AUC > 0.7)  %>% 
dplyr::group_by(LV) %>% 
dplyr::summarise(pathway_prior = paste(pathway, collapse = ', '), .groups = "drop") %>%
dplyr::arrange(as.numeric(gsub("[^0-9]", "", LV)))

gtex_fullRes_full_summ

    LV
1   LV1
2   LV2
3   LV3
4   LV4
5   LV5
6   LV6
7   LV7
8   LV8
9   LV9
10  LV10
11  LV11
12  LV12
13  LV13
14  LV14
15  LV15
16  LV16
17  LV17
18  LV18
19  LV19
20  LV20
21  LV21
22  LV22
23  LV23
24  LV24
25  LV25
26  LV26
27  LV27
28  LV28
29  LV29
30  LV30
31  LV31
32  LV32
33  LV34
34  LV35
35  LV36
36  LV37
37  LV38
38  LV39
39  LV40
40  LV42
41  LV43
42  LV44
43  LV46
44  LV48
45  LV50
46  LV51
47  LV52
48  LV54
49  LV55
50  LV57
51  LV59
52  LV60
53  LV63
54  LV64
55  LV65
56  LV67
57  LV68
58  LV69
59  LV70
60  LV71
61  LV73
62  LV74
63  LV76
64  LV78
65  LV79
66  LV80
67  LV81
68  LV82
69  LV84
70  LV87
71  LV88
72  LV89
73  LV90
74  LV91
75  LV93
76  LV94
77  LV95
78  LV96
79  LV97
80  LV98
81  LV101
82  LV103
83  LV104
84  LV105
85  LV106
86  LV107
87  LV109
88  LV110
89  LV111
90  LV112
91  LV113
92  LV114
93  LV115
94  LV116
95  LV117
96  LV118
97  LV120
98  LV121
99  LV122
100 LV123
101 LV124
102 LV127
103 LV128
104 LV129
105 LV130
106 LV132
107 LV133
108 LV134
109 LV135
110 LV136
111 LV137
112 LV138
113 LV139
114 LV141
115 LV142
116 LV143
117 LV144
118 LV145
119 LV149
120 LV151
121 LV152
122 LV153
123 LV154
124 LV155
125 LV158
126 LV160
127 LV161
128 LV162
129 LV163
130 LV164
131 LV166
132 LV170
133 LV171
134 LV173
135 LV174
136 LV175
137 LV176
138 LV177
139 LV180
140 LV181
141 LV182
142 LV183
143 LV184
144 LV186
145 LV187
146 LV188
147 LV189
148 LV190
149 LV191
150 LV194
151 LV196
152 LV198
153 LV199
154 LV200
155 LV201
156 LV204
157 LV207
158 LV209
159 LV212
160 LV213
161 LV214
162 LV215
163 LV216
164 LV217
165 LV218
166 LV219
167 LV220
168 LV221
169 LV225
170 LV226
171 LV227
172 LV230
173 LV231
174 LV232
175 LV233
176 LV236
177 LV238
178 LV239
179 LV240
180 LV241
181 LV242
182 LV243
183 LV244
184 LV246
185 LV247
186 LV248
187 LV250
188 LV251
189 LV252
190 LV254
191 LV255
192 LV256
193 LV257
194 LV258
195 LV259
196 LV260
197 LV263
198 LV264
199 LV266
200 LV269
201 LV272
202 LV274
203 LV276
204 LV279
205 LV280
206 LV284
207 LV286
208 LV287
209 LV289
210 LV290
211 LV291
212 LV292
213 LV293
214 LV295
215 LV296
216 LV297
217 LV298
218 LV299
219 LV300
220 LV301
221 LV302
222 LV304
223 LV305
224 LV306
225 LV307
226 LV308
227 LV309
228 LV310
229 LV311
230 LV312
231 LV313
232 LV314
233 LV315
234 LV316
235 LV317
236 LV318
237 LV319
238 LV320
239 LV321
240 LV324
241 LV325
242 LV327
243 LV328
244 LV329
245 LV330
246 LV333
247 LV335
248 LV336
249 LV338
250 LV339
251 LV340
252 LV341
253 LV342
254 LV343
255 LV344
256 LV345
257 LV346
258 LV349
259 LV350
260 LV351
261 LV352
262 LV357
263 LV360
264 LV362
265 LV363
266 LV366
267 LV370
268 LV371
269 LV375
270 LV376
271 LV378
272 LV379
273 LV380
274 LV381
275 LV382
276 LV383
277 LV384
278 LV385
279 LV386
280 LV389
281 LV391
282 LV393
283 LV397
284 LV398
285 LV401
286 LV402
287 LV406
288 LV409
289 LV410
290 LV411
    pathway_prior
1   BP_C4-dicarboxylate Transport (GO:0015740), CellMarker_Neutrophil Nasal Polyp Human
2   GTEx_Tissues_Brain - Frontal Cortex (BA9) Male 60-69 Up, GTEx_Tissues_Brain - Frontal Cortex (BA9) Female 60-69 Up, GTEx_Tissues_Brain - Cortex Male 30-39 Up, GTEx_Tissues_Brain - Frontal Cortex (BA9) Male 20-29 Up, GTEx_Tissues_Brain - Frontal Cortex (BA9) Male 70-79 Up, GTEx_Tissues_Brain - Frontal Cortex (BA9) Female 50-59 Up, GTEx_Tissues_Brain - Frontal Cortex (BA9) Male 40-49 Up, GTEx_Tissues_Brain - Anterior Cingulate Cortex (BA24) Female 20-29 Up
3   GTEx_Tissues_Whole Blood Female 50-59 Up, GTEx_Tissues_Whole Blood Male 50-59 Up, GTEx_Tissues_Whole Blood Female 20-29 Up, GTEx_Tissues_Whole Blood Male 30-39 Up, GTEx_Tissues_Whole Blood Female 30-39 Up, GTEx_Tissues_Whole Blood Male 20-29 Up, GTEx_Tissues_Whole Blood Female 40-49 Up, CellMarker_Neutrophil Soft Tissue Human, CellMarker_Neutrophil Stomach Human
4   CellMarker_Endothelial Cell Aorta Mouse, CellMarker_Endothelial Cell Blood Mouse, CellMarker_Fibroblast Muscle Mouse, CellMarker_Fibroblast Skin Mouse, CellMarker_Fibroblast Undefined Mouse
5   GTEx_Tissues_Esophagus - Mucosa Male 50-59 Up, GTEx_Tissues_Esophagus - Mucosa Male 60-69 Up, GTEx_Tissues_Esophagus - Mucosa Female 60-69 Up, GTEx_Tissues_Esophagus - Mucosa Female 20-29 Up, GTEx_Tissues_Esophagus - Mucosa Male 30-39 Up, GTEx_Tissues_Esophagus - Mucosa Female 50-59 Up, GTEx_Tissues_Esophagus - Mucosa Male 20-29 Up, GTEx_Tissues_Esophagus - Mucosa Male 40-49 Up, GTEx_Tissues_Esophagus - Mucosa Female 70-79 Up
6   BP_Male Gamete Generation (GO:0048232), BP_piRNA Processing (GO:0034587), GTEx_Tissues_Testis Male 50-59 Up, GTEx_Tissues_Testis Male 60-69 Up, GTEx_Tissues_Testis Male 30-39 Up, GTEx_Tissues_Testis Male 20-29 Up, GTEx_Tissues_Testis Male 40-49 Up, GTEx_Tissues_Testis Male 70-79 Up
7   GTEx_Tissues_Muscle - Skeletal Female 60-69 Up, GTEx_Tissues_Muscle - Skeletal Male 60-69 Up, GTEx_Tissues_Muscle - Skeletal Female 70-79 Up
8   GTEx_Tissues_Skin - Sun Exposed (Lower Leg) Male 60-69 Up, GTEx_Tissues_Skin - Sun Exposed (Lower Leg) Female 60-69 Up, GTEx_Tissues_Skin - Sun Exposed (Lower Leg) Female 50-59 Up, GTEx_Tissues_Skin - Sun Exposed (Lower Leg) Male 40-49 Up, GTEx_Tissues_Skin - Sun Exposed (Lower Leg) Male 30-39 Up, GTEx_Tissues_Skin - Sun Exposed (Lower Leg) Male 20-29 Up, GTEx_Tissues_Skin - Sun Exposed (Lower Leg) Female 40-49 Up, GTEx_Tissues_Skin - Sun Exposed (Lower Leg) Male 70-79 Up, CellMarker_Basal Cell Bladder Human
9   BP_Branching Involved in Blood Vessel Morphogenesis (GO:0001569), CellMarker_Arterial Cell Embryo Mouse, CellMarker_Endothelial Cell Artery Human, CellMarker_Endothelial Cell Breast Human, CellMarker_Endothelial Cell Fetal Kidney Human, CellMarker_Endothelial Cell Muscle Mouse, CellMarker_Endothelial Cell Stomach Human
10  KEGG_Oxidative phosphorylation, BP_Aerobic Electron Transport Chain (GO:0019646), BP_Cellular Respiration (GO:0045333), BP_Mitochondrial ATP Synthesis Coupled Electron Transport (GO:0042775)
11  GTEx_Tissues_Colon - Transverse Male 50-59 Up, GTEx_Tissues_Colon - Transverse Female 20-29 Up, GTEx_Tissues_Colon - Transverse Male 30-39 Up, GTEx_Tissues_Colon - Transverse Female 50-59 Up, GTEx_Tissues_Colon - Transverse Male 20-29 Up, GTEx_Tissues_Colon - Transverse Male 40-49 Up, GTEx_Tissues_Colon - Transverse Female 30-39 Up, GTEx_Tissues_Colon - Transverse Female 40-49 Up, CellMarker_Goblet Cell Large Intestine Human
12  KEGG_DNA replication, BP_DNA Strand Elongation Involved in DNA Replication (GO:0006271), BP_Positive Regulation of Spindle Checkpoint (GO:0090232), Proteomics_Drug_Atlas_GR79236 Up, Proteomics_Drug_Atlas_Nutlin3a Down, Proteomics_Drug_Atlas_Idasanutlin Down, CellMarker_Cycling Basal Cell Trachea Mouse
13  GTEx_Tissues_Heart - Atrial Appendage Male 60-69 Up, GTEx_Tissues_Heart - Atrial Appendage Male 20-29 Up, GTEx_Tissues_Heart - Atrial Appendage Female 40-49 Up, GTEx_Tissues_Heart - Atrial Appendage Male 70-79 Up, GTEx_Tissues_Heart - Left Ventricle Male 70-79 Up
14  BP_Mitotic Sister Chromatid Cohesion (GO:0007064), BP_Nuclear Pore Organization (GO:0006999), TF_Perturbations_SNAI1 KO MOUSE GSE53107 CREEDSID GENE 1448 DOWN, TF_Perturbations_CHD1 KD 22RV1 HUMAN GSE84610 RNASEQ DOWN
15  GWAS_Catalog_Bipolar Ii Disorder, BP_Reg of Mt Outer Membrane Permeabilization Inv in Apoptotic Sgnlng Pway (GO:1901028), TF_Perturbations_MYCN SHRNA IMR575 HUMAN GSE80397 12HR RNASEQ DOWN
16  GTEx_Tissues_Nerve - Tibial Male 50-59 Up, GTEx_Tissues_Nerve - Tibial Male 60-69 Up, GTEx_Tissues_Nerve - Tibial Male 40-49 Up, GTEx_Tissues_Nerve - Tibial Female 60-69 Up, GTEx_Tissues_Nerve - Tibial Male 30-39 Up, GTEx_Tissues_Nerve - Tibial Male 70-79 Up, GTEx_Tissues_Nerve - Tibial Female 70-79 Up
17  GTEx_Tissues_Heart - Left Ventricle Male 60-69 Up, GTEx_Tissues_Heart - Left Ventricle Female 60-69 Up, GTEx_Tissues_Heart - Left Ventricle Male 50-59 Up, GTEx_Tissues_Heart - Left Ventricle Male 30-39 Up, GTEx_Tissues_Heart - Left Ventricle Female 40-49 Up, GTEx_Tissues_Heart - Left Ventricle Female 30-39 Up, GTEx_Tissues_Heart - Left Ventricle Male 70-79 Up, GTEx_Tissues_Heart - Left Ventricle Female 70-79 Up
18  BP_Neuron Cell-Cell Adhesion (GO:0007158), GTEx_Tissues_Colon - Transverse Male 60-69 Up, GTEx_Tissues_Esophagus - Gastroesophageal Junction Male 60-69 Up, GTEx_Tissues_Colon - Sigmoid Male 60-69 Up, GTEx_Tissues_Colon - Transverse Male 70-79 Up
19  GTEx_Tissues_Cells - Cultured Fibroblasts Male 60-69 Up, GTEx_Tissues_Cells - Cultured Fibroblasts Female 50-59 Up, GTEx_Tissues_Cells - Cultured Fibroblasts Female 30-39 Up, GTEx_Tissues_Cells - Cultured Fibroblasts Female 40-49 Up
20  GTEx_Tissues_Adrenal Gland Male 50-59 Up, GTEx_Tissues_Adrenal Gland Male 60-69 Up, GTEx_Tissues_Adrenal Gland Female 60-69 Up, GTEx_Tissues_Adrenal Gland Male 30-39 Up, GTEx_Tissues_Adrenal Gland Female 50-59 Up, GTEx_Tissues_Adrenal Gland Male 20-29 Up, GTEx_Tissues_Adrenal Gland Female 40-49 Up, GTEx_Tissues_Adrenal Gland Male 40-49 Up, GTEx_Tissues_Adrenal Gland Female 30-39 Up
21  GTEx_Tissues_Liver Male 60-69 Up, GTEx_Tissues_Liver Male 50-59 Up, GTEx_Tissues_Liver Male 30-39 Up, GTEx_Tissues_Liver Female 60-69 Up, GTEx_Tissues_Liver Female 50-59 Up, GTEx_Tissues_Liver Male 40-49 Up, GTEx_Tissues_Liver Female 40-49 Up, GTEx_Tissues_Liver Female 20-29 Up, GTEx_Tissues_Liver Female 30-39 Up
22  GTEx_Tissues_Brain - Frontal Cortex (BA9) Female 40-49 Up
23  KEGG_Ribosome, BP_Cytoplasmic Translation (GO:0002181), BP_Cytoplasmic Translational Initiation (GO:0002183), BP_Formation of Cytoplasmic Translation Initiation Complex (GO:0001732), TF_Perturbations_MYCN OE MOUSE GSE6077 CREEDSID GENE 40 UP, TF_Perturbations_ADNP DEFICIENCY MOUSE GSE4068 CREEDSID GENE 718 DOWN, TF_Perturbations_EZH2 SHRNA PROE HUMAN GSE59089 RNASEQ DOWN, TF_Perturbations_IRX6 SIRNA MCF7 HUMAN GSE79586 RNASEQ DOWN, TF_Perturbations_ZMAT4 SIRNA MCF7 HUMAN GSE79586 RNASEQ DOWN
24  GTEx_Tissues_Pituitary Female 60-69 Up, GTEx_Tissues_Pituitary Female 50-59 Up, GTEx_Tissues_Pituitary Male 60-69 Up, GTEx_Tissues_Pituitary Male 40-49 Up, GTEx_Tissues_Pituitary Male 30-39 Up, GTEx_Tissues_Pituitary Female 20-29 Up
25  GTEx_Tissues_Pancreas Female 60-69 Up, GTEx_Tissues_Pancreas Male 30-39 Up, GTEx_Tissues_Pancreas Female 50-59 Up, GTEx_Tissues_Pancreas Male 20-29 Up, GTEx_Tissues_Pancreas Female 40-49 Up, GTEx_Tissues_Pancreas Female 30-39 Up, GTEx_Tissues_Pancreas Female 20-29 Up
26  GTEx_Tissues_Lung Male 50-59 Up, GTEx_Tissues_Lung Male 60-69 Up, GTEx_Tissues_Lung Female 60-69 Up, GTEx_Tissues_Lung Male 30-39 Up, GTEx_Tissues_Lung Female 50-59 Up, GTEx_Tissues_Lung Male 40-49 Up, GTEx_Tissues_Lung Female 40-49 Up, GTEx_Tissues_Lung Female 20-29 Up, GTEx_Tissues_Lung Male 70-79 Up, GTEx_Tissues_Lung Female 70-79 Up
27  BP_Mitochondrial ATP Synthesis Coupled Electron Transport (GO:0042775), BP_Mitochondrial Electron Transport, NADH to Ubiquinone (GO:0006120), BP_Mitochondrial Electron Transport, Cytochrome C to Oxygen (GO:0006123), BP_Mitochondrial Electron Transport, Ubiquinol to Cytochrome C (GO:0006122), BP_Mitochondrial Translation (GO:0032543), BP_Oxidative Phosphorylation (GO:0006119), BP_Proton Motive Force-Driven ATP Synthesis (GO:0015986), BP_Proton Motive Force-Driven Mitochondrial ATP Synthesis (GO:0042776)
28  BP_Amino Acid Metabolic Process (GO:0006520), BP_Branched-Chain Amino Acid Catabolic Process (GO:0009083), BP_Monocarboxylic Acid Catabolic Process (GO:0072329), Metabolomics_Workbench_(S)-Methylmalonate Semialdehyde
29  GTEx_Tissues_Brain - Spinal Cord (Cervical C-1) Male 50-59 Up, GTEx_Tissues_Brain - Hippocampus Male 40-49 Up, GTEx_Tissues_Brain - Spinal Cord (Cervical C-1) Female 60-69 Up, GTEx_Tissues_Brain - Spinal Cord (Cervical C-1) Male 60-69 Up, GTEx_Tissues_Brain - Spinal Cord (Cervical C-1) Female 50-59 Up, GTEx_Tissues_Brain - Hippocampus Male 70-79 Up, GTEx_Tissues_Brain - Substantia Nigra Male 40-49 Up, GTEx_Tissues_Brain - Spinal Cord (Cervical C-1) Male 40-49 Up, GTEx_Tissues_Brain - Hippocampus Female 70-79 Up
30  BP_Endonucleolytic Clvg of Tricistronic rRNA Trnscpt (GO:0000479), BP_Maturation of 5.8S rRNA (GO:0000460), BP_Maturation of SSU-rRNA Frm Tricistronic rRNA Trnscpt (GO:0000462), BP_Mitochondrial Ribosome Assembly (GO:0061668), BP_tRNA Aminoacylation for Protein Translation (GO:0006418)
31  GTEx_Tissues_Breast - Mammary Tissue Female 60-69 Up, GTEx_Tissues_Breast - Mammary Tissue Female 20-29 Up, GTEx_Tissues_Breast - Mammary Tissue Female 50-59 Up, GTEx_Tissues_Breast - Mammary Tissue Female 40-49 Up, CellMarker_Epithelial Cell Breast Mouse, CellMarker_Epithelial Cell Ovary Human, CellMarker_Luminal Cell Breast Mouse
32  CellMarker_Intestinal Cell Epithelium Human
33  GTEx_Tissues_Brain - Nucleus Accumbens (Basal Ganglia) Male 50-59 Up, GTEx_Tissues_Brain - Nucleus Accumbens (Basal Ganglia) Male 20-29 Up, GTEx_Tissues_Brain - Nucleus Accumbens (Basal Ganglia) Male 70-79 Up, GTEx_Tissues_Brain - Nucleus Accumbens (Basal Ganglia) Female 40-49 Up, GTEx_Tissues_Brain - Nucleus Accumbens (Basal Ganglia) Female 50-59 Up, GTEx_Tissues_Brain - Caudate (Basal Ganglia) Female 20-29 Up, GTEx_Tissues_Brain - Nucleus Accumbens (Basal Ganglia) Male 30-39 Up, GTEx_Tissues_Brain - Putamen (Basal Ganglia) Male 30-39 Up
34  CellMarker_Epithelial Cell Ovary Human
35  GTEx_Tissues_Stomach Male 50-59 Up, GTEx_Tissues_Stomach Male 60-69 Up, GTEx_Tissues_Stomach Female 60-69 Up, GTEx_Tissues_Stomach Female 20-29 Up, GTEx_Tissues_Stomach Male 30-39 Up, GTEx_Tissues_Stomach Male 20-29 Up, GTEx_Tissues_Stomach Female 40-49 Up, GTEx_Tissues_Stomach Male 40-49 Up, GTEx_Tissues_Stomach Female 30-39 Up
36  GTEx_Tissues_Cells - Cultured Fibroblasts Male 60-69 Up, GTEx_Tissues_Cells - Cultured Fibroblasts Female 50-59 Up, GTEx_Tissues_Cells - Cultured Fibroblasts Male 40-49 Up, GTEx_Tissues_Cells - Cultured Fibroblasts Male 20-29 Up, GTEx_Tissues_Cells - Cultured Fibroblasts Male 70-79 Up, CellMarker_M1 Macrophage Peripheral Blood Human, CellMarker_T Cell Soft Tissue Human
37  GTEx_Tissues_Prostate Male 50-59 Up, GTEx_Tissues_Prostate Male 60-69 Up, GTEx_Tissues_Prostate Male 30-39 Up, GTEx_Tissues_Prostate Male 20-29 Up, GTEx_Tissues_Prostate Male 40-49 Up, GTEx_Tissues_Prostate Male 70-79 Up, Human_Gene_Atlas_Prostate
38  GWAS_Catalog_Airway Responsiveness In Chronic Obstructive Pulmonary Disease, BP_Regulation of TORC2 Signaling (GO:1903939), BP_Regulation of Telomere Capping (GO:1904353)
39  GTEx_Tissues_Cervix - Ectocervix Female 40-49 Up, GTEx_Tissues_Fallopian Tube Female 40-49 Up, CellMarker_Fibroblast Skin Mouse, CellMarker_PROCR+ Progenitor Cell Small Intestine Human
40  GTEx_Tissues_Esophagus - Muscularis Male 50-59 Up, GTEx_Tissues_Esophagus - Gastroesophageal Junction Male 60-69 Up, GTEx_Tissues_Esophagus - Muscularis Male 20-29 Up, GTEx_Tissues_Esophagus - Muscularis Female 30-39 Up
41  CellMarker_Monocyte-derived Dendritic Cell Undefined Human
42  GTEx_Tissues_Brain - Putamen (Basal Ganglia) Male 50-59 Up, GTEx_Tissues_Brain - Caudate (Basal Ganglia) Male 60-69 Up, GTEx_Tissues_Brain - Caudate (Basal Ganglia) Female 60-69 Up, GTEx_Tissues_Brain - Amygdala Female 50-59 Up, GTEx_Tissues_Brain - Substantia Nigra Male 70-79 Up, GTEx_Tissues_Brain - Caudate (Basal Ganglia) Male 70-79 Up, GTEx_Tissues_Brain - Putamen (Basal Ganglia) Female 40-49 Up, GTEx_Tissues_Brain - Caudate (Basal Ganglia) Female 50-59 Up, GTEx_Tissues_Brain - Caudate (Basal Ganglia) Female 70-79 Up
43  CellMarker_Homeostatic Chondrocyte Articular Cartilage Human
44  GTEx_Tissues_Uterus Female 60-69 Up, GTEx_Tissues_Uterus Female 50-59 Up, GTEx_Tissues_Uterus Female 20-29 Up, GTEx_Tissues_Uterus Female 30-39 Up, GTEx_Tissues_Uterus Female 40-49 Up
45  GTEx_Tissues_Kidney - Cortex Female 60-69 Up, GTEx_Tissues_Kidney - Cortex Female 50-59 Up, GTEx_Tissues_Kidney - Cortex Male 50-59 Up, GTEx_Tissues_Kidney - Cortex Male 40-49 Up, GTEx_Tissues_Kidney - Cortex Male 30-39 Up, GTEx_Tissues_Kidney - Cortex Male 70-79 Up, Human_Gene_Atlas_Kidney, CellMarker_Nephron Epithelial Cell Kidney Human
46  BP_Axonemal Dynein Complex Assembly (GO:0070286), BP_Axoneme Assembly (GO:0035082), BP_Cilium Movement (GO:0003341), BP_Intraciliary Anterograde Transport (GO:0035720), BP_Motile Cilium Assembly (GO:0044458), CellMarker_Ciliated Cell Lung Human, CellMarker_Ciliated Cell Lung Mouse
47  Human_Gene_Atlas_CD71+ EarlyErythroid, OMIM_Disease_blood, TF_Perturbations_U2AF1 OE BFUE HUMAN GSE94153 RNASEQ UP
48  GTEx_Tissues_Testis Male 60-69 Up, CellMarker_Epithelial Cell Stomach Human
49  CellMarker_Endothelial Cell Fetal Kidney Human
50  GTEx_Tissues_Breast - Mammary Tissue Female 60-69 Up, GTEx_Tissues_Breast - Mammary Tissue Female 50-59 Up, GTEx_Tissues_Breast - Mammary Tissue Female 40-49 Up, CellMarker_Epithelial Cell Breast Mouse, CellMarker_Luminal Cell Bladder Human
51  GTEx_Tissues_Testis Male 30-39 Up
52  BP_Aerobic Electron Transport Chain (GO:0019646), BP_Mitochondrial ATP Synthesis Coupled Electron Transport (GO:0042775), BP_Mitochondrial Electron Transport, Ubiquinol to Cytochrome C (GO:0006122), BP_Oxidative Phosphorylation (GO:0006119), BP_Proton Motive Force-Driven ATP Synthesis (GO:0015986), BP_Respiratory Electron Transport Chain (GO:0022904)
53  KEGG_Herpes simplex virus 1 infection
54  KEGG_Glycosaminoglycan biosynthesis, BP_Heparan Sulfate Proteoglycan Biosynthetic Process (GO:0015012), BP_Protein Localization to Phagophore Assembly Site (GO:0034497)
55  GTEx_Tissues_Small Intestine - Terminal Ileum Male 50-59 Up, GTEx_Tissues_Small Intestine - Terminal Ileum Male 60-69 Up, GTEx_Tissues_Small Intestine - Terminal Ileum Female 60-69 Up, GTEx_Tissues_Small Intestine - Terminal Ileum Male 30-39 Up, GTEx_Tissues_Small Intestine - Terminal Ileum Female 50-59 Up, GTEx_Tissues_Small Intestine - Terminal Ileum Female 30-39 Up, GTEx_Tissues_Small Intestine - Terminal Ileum Male 40-49 Up, CellMarker_Enterocyte Small Intestine Mouse
56  BP_Regulation of Telomerase RNA Localization to Cajal Body (GO:1904872), BP_snRNA Metabolic Process (GO:0016073)
57  GWAS_Catalog_Sum Of Carotid Plaque Area, GTEx_Tissues_Adipose - Visceral (Omentum) Female 60-69 Up, GTEx_Tissues_Adipose - Visceral (Omentum) Male 70-79 Up
58  GTEx_Tissues_Testis Male 40-49 Up, GTEx_Tissues_Testis Male 70-79 Up, Chromosome_Location_chrxq28, Chromosome_Location_chrxq22
59  KEGG_Spliceosome, BP_RNA Splicing (GO:0008380), BP_Alternative mRNA Splicing, via Spliceosome (GO:0000380), BP_mRNA Cis Splicing, via Spliceosome (GO:0045292), BP_mRNA Splice Site Recognition (GO:0006376)
60  BP_Growth Hormone Receptor Signaling Pathway via JAK-STAT (GO:0060397), GTEx_Tissues_Whole Blood Female 60-69 Up, GTEx_Tissues_Whole Blood Female 50-59 Up, GTEx_Tissues_Whole Blood Male 50-59 Up, GTEx_Tissues_Whole Blood Male 40-49 Up, GTEx_Tissues_Whole Blood Female 40-49 Up
61  BP_Regulation of Cell Cycle Checkpoint (GO:1901976), BP_Suppression of Viral Release by Host (GO:0044790)
62  BP_Cilium-Dependent Cell Motility (GO:0060285), GTEx_Tissues_Testis Male 60-69 Up, Human_Gene_Atlas_Testis, Human_Gene_Atlas_TestisIntersitial, Human_Gene_Atlas_TestisSeminiferousTubule, TF_Perturbations_DMRT1 KO MOUSE GSE27261 CREEDSID GENE 2740 DOWN
63  GTEx_Tissues_Muscle - Skeletal Male 30-39 Up, GTEx_Tissues_Muscle - Skeletal Female 30-39 Up, GTEx_Tissues_Muscle - Skeletal Female 40-49 Up, GTEx_Tissues_Muscle - Skeletal Male 70-79 Up, GTEx_Tissues_Muscle - Skeletal Female 70-79 Up
64  GTEx_Tissues_Muscle - Skeletal Female 60-69 Up, GTEx_Tissues_Muscle - Skeletal Female 20-29 Up, GTEx_Tissues_Muscle - Skeletal Female 30-39 Up
65  CellMarker_Macrophage Blood Human, CellMarker_Microglial Cell Cortex Mouse, CellMarker_Neutrophil Nasal Polyp Human
66  GTEx_Tissues_Vagina Female 60-69 Up, GTEx_Tissues_Skin - Not Sun Exposed (Suprapubic) Male 50-59 Up, GTEx_Tissues_Vagina Female 50-59 Up, GTEx_Tissues_Skin - Sun Exposed (Lower Leg) Male 40-49 Up, GTEx_Tissues_Vagina Female 20-29 Up, GTEx_Tissues_Vagina Female 30-39 Up, GTEx_Tissues_Vagina Female 40-49 Up, GTEx_Tissues_Skin - Not Sun Exposed (Suprapubic) Female 40-49 Up