In [2]:
library(here)

here() starts at /home/msubirana/Documents/pivlab/clamp-analyses

In [3]:
archs4 <- readRDS(here('output/01_model_building/04_archs4/06_bp_coverage_rshall/06_bp_coverage_hall_rs_100/CLAMPfull_hall.rds'))

In [4]:
gtex <- readRDS(here('output/01_model_building/02_gtex/10_CLAMP_hall/CLAMPfull_hall.rds'))

In [5]:
archs4_summary <- data.frame(as.matrix(archs4$summary))

In [6]:
head(archs4_summary)

             pathway
REACTOME78   REACTOME_REACTOME_ALPHA_LINOLENIC_OMEGA3_AND_LINOLEIC_OMEGA6_ACID_METABOLISM
REACTOME167  REACTOME_REACTOME_BIOTIN_TRANSPORT_AND_METABOLISM
REACTOME914  REACTOME_REACTOME_MITOCHONDRIAL_TRNA_AMINOACYLATION
REACTOME1643 REACTOME_REACTOME_SYNTHESIS_OF_PIPS_AT_THE_EARLY_ENDOSOME_MEMBRANE
REACTOME1646 REACTOME_REACTOME_SYNTHESIS_OF_PIPS_AT_THE_LATE_ENDOSOME_MEMBRANE
GOCC46       GOCC_GOCC_ATAC_COMPLEX
             LV  AUC       p_value      FDR          npos nneg
REACTOME78   LV1 0.5749425 3.560962e-01 6.131557e-01   2  18274
REACTOME167  LV1 0.5986921 3.135387e-01 5.784549e-01   2  18274
REACTOME914  LV1 0.7719574 2.914851e-02 1.163108e-01   4  18274
REACTOME1643 LV1 0.6192769 2.360180e-01 5.101467e-01   3  18274
REACTOME1646 LV1 0.7110375 1.494073e-01 3.690964e-01   2  18274
GOCC46       LV1 0.3395945 7.851862e-01 9.233279e-01   2  18274

In [9]:
unique(archs4_summary$pathway)

   [1] "REACTOME_REACTOME_ALPHA_LINOLENIC_OMEGA3_AND_LINOLEIC_OMEGA6_ACID_METABOLISM"
   [2] "REACTOME_REACTOME_BIOTIN_TRANSPORT_AND_METABOLISM"
   [3] "REACTOME_REACTOME_MITOCHONDRIAL_TRNA_AMINOACYLATION"
   [4] "REACTOME_REACTOME_SYNTHESIS_OF_PIPS_AT_THE_EARLY_ENDOSOME_MEMBRANE"
   [5] "REACTOME_REACTOME_SYNTHESIS_OF_PIPS_AT_THE_LATE_ENDOSOME_MEMBRANE"
   [6] "GOCC_GOCC_ATAC_COMPLEX"
   [7] "GOCC_GOCC_GOLGI_TRANSPORT_COMPLEX"
   [8] "GOCC_GOCC_MICROBODY_LUMEN"
   [9] "GOCC_GOCC_NUCLEAR_PORE_NUCLEAR_BASKET"
  [10] "GOCC_GOCC_NUCLEAR_PORE_OUTER_RING"
  [11] "REACTOME_REACTOME_FERTILIZATION"
  [12] "REACTOME_REACTOME_OLFACTORY_SIGNALING_PATHWAY"
  [13] "REACTOME_REACTOME_POU5F1_OCT4_SOX2_NANOG_ACTIVATE_GENES_RELATED_TO_PROLIFERATION"
  [14] "REACTOME_REACTOME_THE_ACTIVATION_OF_ARYLSULFATASES"
  [15] "REACTOME_REACTOME_TRIGLYCERIDE_BIOSYNTHESIS"
  [16] "REACTOME_REACTOME_XENOBIOTICS"
  [17] "GOCC_GOCC_MKS_COMPLEX"
  [18] "GOCC_GOCC_STEREOCILIUM_TIP"
  [19] "C8_AIZARANI_LIVER_C30_HEPATOCYTES_4"
  [20] "C8_GAO_LARGE_INTESTINE_ADULT_CG_GOBLET_CELL_SUBTYPE_2"
  [21] "REACTOME_REACTOME_LGI_ADAM_INTERACTIONS"
  [22] "REACTOME_REACTOME_MECP2_REGULATES_NEURONAL_RECEPTORS_AND_CHANNELS"
  [23] "GOCC_GOCC_GLIAL_CELL_PROJECTION"
  [24] "GOCC_GOCC_SODIUM_CHANNEL_COMPLEX"
  [25] "GOCC_GOCC_VOLTAGE_GATED_SODIUM_CHANNEL_COMPLEX"
  [26] "C8_DESCARTES_FETAL_HEART_SATB2_LRRC7_POSITIVE_CELLS"
  [27] "C8_DESCARTES_FETAL_SPLEEN_VASCULAR_ENDOTHELIAL_CELLS"
  [28] "C8_FAN_EMBRYONIC_CTX_BIG_GROUPS_EXCITATORY_NEURON"
  [29] "REACTOME_REACTOME_MITOCHONDRIAL_TRANSLATION_ELONGATION"
  [30] "GOCC_GOCC_MITOCHONDRIAL_LARGE_RIBOSOMAL_SUBUNIT"
  [31] "GOCC_GOCC_MITOCHONDRIAL_SMALL_RIBOSOMAL_SUBUNIT"
  [32] "GOCC_GOCC_NUCLEAR_EXOSOME_RNASE_COMPLEX"
  [33] "GOCC_GOCC_NUCLEOLAR_EXOSOME_RNASE_COMPLEX"
  [34] "GOCC_GOCC_ORGANELLAR_RIBOSOME"
  [35] "GOCC_GOCC_RIBONUCLEASE_MRP_COMPLEX"
  [36] "GOCC_GOCC_RIBONUCLEASE_P_COMPLEX"
  [37] "GOCC_GOCC_U4_U6_SNRNP"
  [38] "REACTOME_REACTOME_DEVELOPMENTAL_LINEAGE_OF_PANCREATIC_ACINAR_CELLS"
  [39] "REACTOME_REACTOME_ERYTHROCYTES_TAKE_UP_CARBON_DIOXIDE_AND_RELEASE_OXYGEN"
  [40] "REACTOME_REACTOME_GERM_LAYER_FORMATION_AT_GASTRULATION"
  [41] "REACTOME_REACTOME_REVERSIBLE_HYDRATION_OF_CARBON_DIOXIDE"
  [42] "C8_BUSSLINGER_DUODENAL_BCHE_CELLS"
  [43] "C8_BUSSLINGER_DUODENAL_GOBLET_CELLS"
  [44] "C8_BUSSLINGER_GASTRIC_IMMATURE_PIT_CELLS"
  [45] "C8_BUSSLINGER_GASTRIC_MATURE_PIT_CELLS"
  [46] "C8_BUSSLINGER_GASTRIC_METALLOTHIONEIN_CELLS"
  [47] "C8_DURANTE_ADULT_OLFACTORY_NEUROEPITHELIUM_SUSTENTACULAR_CELLS"
  [48] "C8_CUI_DEVELOPING_HEART_C3_FIBROBLAST_LIKE_CELL"
  [49] "C8_CUI_DEVELOPING_HEART_COMPACT_VENTRICULAR_CARDIOMYOCYTE"
  [50] "C8_CUI_DEVELOPING_HEART_SMOOTH_MUSCLE_CELL"
  [51] "C8_DESCARTES_FETAL_STOMACH_STROMAL_CELLS"
  [52] "C8_DESCARTES_MAIN_FETAL_STROMAL_CELLS"
  [53] "C8_DURANTE_ADULT_OLFACTORY_NEUROEPITHELIUM_FIBROBLASTS_STROMAL_CELLS"
  [54] "C8_DURANTE_ADULT_OLFACTORY_NEUROEPITHELIUM_VASCULAR_SMOOTH_MUSCLE_CELLS"
  [55] "C8_FAN_OVARY_CL6_PUTATIVE_EARLY_ATRETIC_FOLLICLE_THECAL_CELL_2"
  [56] "C8_JONES_OVARY_STROMAL"
  [57] "C8_RUBENSTEIN_SKELETAL_MUSCLE_FAP_CELLS"
  [58] "REACTOME_REACTOME_DOPAMINE_NEUROTRANSMITTER_RELEASE_CYCLE"
  [59] "REACTOME_REACTOME_DS_GAG_BIOSYNTHESIS"
  [60] "GOCC_GOCC_DENDRITE_MEMBRANE"
  [61] "GOCC_GOCC_DENDRITIC_SPINE_MEMBRANE"
  [62] "C8_BUSSLINGER_DUODENAL_K_CELLS"
  [63] "C8_DESCARTES_MAIN_FETAL_ISLET_ENDOCRINE_CELLS"
  [64] "REACTOME_REACTOME_MITOTIC_TELOPHASE_CYTOKINESIS"
  [65] "REACTOME_REACTOME_RMTS_METHYLATE_HISTONE_ARGININES"
  [66] "GOCC_GOCC_EMC_COMPLEX"
  [67] "GOCC_GOCC_EUKARYOTIC_TRANSLATION_INITIATION_FACTOR_4F_COMPLEX"
  [68] "GOCC_GOCC_EXON_EXON_JUNCTION_COMPLEX"
  [69] "GOCC_GOCC_INNER_KINETOCHORE"
  [70] "GOCC_GOCC_PRERIBOSOME_SMALL_SUBUNIT_PRECURSOR"
  [71] "GOCC_GOCC_RNA_POLYMERASE_III_TRANSCRIPTION_REGULATOR_COMPLEX"
  [72] "GOCC_GOCC_SMN_COMPLEX"
  [73] "REACTOME_REACTOME_CYTOCHROME_C_MEDIATED_APOPTOTIC_RESPONSE"
  [74] "REACTOME_REACTOME_MASTL_FACILITATES_MITOTIC_PROGRESSION"
  [75] "REACTOME_REACTOME_PROTEIN_LIPOYLATION"
  [76] "REACTOME_REACTOME_TRANSCRIPTION_OF_E2F_TARGETS_UNDER_NEGATIVE_CONTROL_BY_P107_RBL1_AND_P130_RBL2_IN_COMPLEX_WITH_HDAC1"
  [77] "GOCC_GOCC_ASTER"
  [78] "GOCC_GOCC_FAR_SIN_STRIPAK_COMPLEX"
  [79] "GOCC_GOCC_TRANSCRIPTION_FACTOR_TFIIH_HOLO_COMPLEX"
  [80] "C8_GAUTAM_EYE_IRIS_CILIARY_BODY_RIBOSOMAL_GENES_HIGH_FIBROBLASTS"
  [81] "REACTOME_REACTOME_ABORTIVE_ELONGATION_OF_HIV_1_TRANSCRIPT_IN_THE_ABSENCE_OF_TAT"
  [82] "REACTOME_REACTOME_CYTOSOLIC_IRON_SULFUR_CLUSTER_ASSEMBLY"
  [83] "REACTOME_REACTOME_DEGRADATION_OF_CYSTEINE_AND_HOMOCYSTEINE"
  [84] "REACTOME_REACTOME_NUCLEOTIDE_SALVAGE"
  [85] "REACTOME_REACTOME_PYRIMIDINE_SALVAGE"
  [86] "REACTOME_REACTOME_UBIQUINOL_BIOSYNTHESIS"
  [87] "GOCC_GOCC_INO80_COMPLEX"
  [88] "GOCC_GOCC_PROTEASOME_CORE_COMPLEX_BETA_SUBUNIT_COMPLEX"
  [89] "GOCC_GOCC_PROTON_TRANSPORTING_V_TYPE_ATPASE_V0_DOMAIN"
  [90] "GOCC_GOCC_TRAPPII_PROTEIN_COMPLEX"
  [91] "REACTOME_REACTOME_ASPIRIN_ADME"
  [92] "REACTOME_REACTOME_PEROXISOMAL_LIPID_METABOLISM"
  [93] "REACTOME_REACTOME_PLASMA_LIPOPROTEIN_ASSEMBLY"
  [94] "C8_AIZARANI_LIVER_C11_HEPATOCYTES_1"
  [95] "C8_AIZARANI_LIVER_C14_HEPATOCYTES_2"
  [96] "C8_AIZARANI_LIVER_C17_HEPATOCYTES_3"
  [97] "C8_DESCARTES_FETAL_LIVER_HEPATOBLASTS"
  [98] "C8_DESCARTES_FETAL_PLACENTA_AFP_ALB_POSITIVE_CELLS"
  [99] "C8_DESCARTES_FETAL_SPLEEN_AFP_ALB_POSITIVE_CELLS"
 [100] "C8_DESCARTES_MAIN_FETAL_HEPATOBLASTS"
 [101] "C8_AIZARANI_LIVER_C18_NK_NKT_CELLS_5"
 [102] "C8_AIZARANI_LIVER_C23_KUPFFER_CELLS_3"
 [103] "C8_CUI_DEVELOPING_HEART_C8_MACROPHAGE"
 [104] "C8_DURANTE_ADULT_OLFACTORY_NEUROEPITHELIUM_DENDRITIC_CELLS"
 [105] "C8_HAY_BONE_MARROW_NEUTROPHIL"
 [106] "C8_HE_LIM_SUN_FETAL_LUNG_C2_MYELOCYTE_LIKE_CELL"
 [107] "C8_HE_LIM_SUN_FETAL_LUNG_C2_NEUTROPHIL_CELL"
 [108] "C8_HE_LIM_SUN_FETAL_LUNG_C2_NON_CLASSICAL_MONOCYTE"
 [109] "C8_HE_LIM_SUN_FETAL_LUNG_C2_S100A12_HI_CLASSICAL_MONOCYTE"
 [110] "C8_TRAVAGLINI_LUNG_CLASSICAL_MONOCYTE_CELL"
 [111] "REACTOME_REACTOME_ERKS_ARE_INACTIVATED"
 [112] "REACTOME_REACTOME_SUMOYLATION_OF_TRANSCRIPTION_FACTORS"
 [113] "REACTOME_REACTOME_TP53_REGULATES_TRANSCRIPTION_OF_GENES_INVOLVED_IN_G2_CELL_CYCLE_ARREST"
 [114] "GOCC_GOCC_CYTOPLASMIC_UBIQUITIN_LIGASE_COMPLEX"
 [115] "GOCC_GOCC_DYNACTIN_COMPLEX"
 [116] "GOCC_GOCC_GID_COMPLEX"
 [117] "GOCC_GOCC_NUCLEOLAR_RIBONUCLEASE_P_COMPLEX"
 [118] "GOCC_GOCC_RNA_N6_METHYLADENOSINE_METHYLTRANSFERASE_COMPLEX"
 [119] "REACTOME_REACTOME_APOPTOTIC_CLEAVAGE_OF_CELL_ADHESION_PROTEINS"
 [120] "REACTOME_REACTOME_MITOCHONDRIAL_MRNA_MODIFICATION"
 [121] "REACTOME_REACTOME_PENTOSE_PHOSPHATE_PATHWAY"
 [122] "GOCC_GOCC_CMG_COMPLEX"
 [123] "GOCC_GOCC_DNA_REPLICATION_PREINITIATION_COMPLEX"
 [124] "GOCC_GOCC_TIM23_MITOCHONDRIAL_IMPORT_INNER_MEMBRANE_TRANSLOCASE_COMPLEX"
 [125] "REACTOME_REACTOME_CHOLESTEROL_BIOSYNTHESIS_VIA_DESMOSTEROL_BLOCH_PATHWAY"
 [126] "REACTOME_REACTOME_CONDENSATION_OF_PROMETAPHASE_CHROMOSOMES"
 [127] "REACTOME_REACTOME_NPAS4_REGULATES_EXPRESSION_OF_TARGET_GENES"
 [128] "REACTOME_REACTOME_RESPONSE_TO_METAL_IONS"
 [129] "GOCC_GOCC_LOW_DENSITY_LIPOPROTEIN_PARTICLE"
 [130] "GOCC_GOCC_NUCLEOTIDE_ACTIVATED_PROTEIN_KINASE_COMPLEX"
 [131] "C8_DESCARTES_FETAL_PANCREAS_ACINAR_CELLS"
 [132] "C8_FAN_EMBRYONIC_CTX_NSC_1"
 [133] "C8_TRAVAGLINI_LUNG_CAPILLARY_CELL"
 [134] "C8_DESCARTES_FETAL_ADRENAL_MYELOID_CELLS"
 [135] "C8_DESCARTES_FETAL_HEART_MYELOID_CELLS"
 [136] "C8_DESCARTES_FETAL_INTESTINE_MYELOID_CELLS"
 [137] "C8_DESCARTES_FETAL_LUNG_MYELOID_CELLS"
 [138] "C8_DESCARTES_FETAL_PANCREAS_MYELOID_CELLS"
 [139] "C8_DESCARTES_FETAL_PLACENTA_MYELOID_CELLS"
 [140] "C8_DESCARTES_FETAL_SPLEEN_MYELOID_CELLS"
 [141] "C8_DESCARTES_MAIN_FETAL_MYELOID_CELLS"
 [142] "C8_FAN_EMBRYONIC_CTX_MICROGLIA_3"
 [143] "C8_DESCARTES_FETAL_HEART_LYMPHOID_CELLS"
 [144] "C8_DESCARTES_FETAL_INTESTINE_LYMPHOID_CELLS"
 [145] "C8_DESCARTES_FETAL_KIDNEY_LYMPHOID_CELLS"
 [146] "C8_DESCARTES_FETAL_LUNG_LYMPHOID_CELLS"
 [147] "C8_DESCARTES_FETAL_PANCREAS_LYMPHOID_CELLS"
 [148] "C8_DESCARTES_FETAL_SPLEEN_LYMPHOID_CELLS"
 [149] "C8_DESCARTES_FETAL_STOMACH_LYMPHOID_CELLS"
 [150] "C8_HE_LIM_SUN_FETAL_LUNG_C4_CD4_T_CELL"
 [151] "REACTOME_REACTOME_BINDING_AND_UPTAKE_OF_LIGANDS_BY_SCAVENGER_RECEPTORS"
 [152] "REACTOME_REACTOME_CD22_MEDIATED_BCR_REGULATION"
 [153] "REACTOME_REACTOME_CREATION_OF_C4_AND_C2_ACTIVATORS"
 [154] "REACTOME_REACTOME_ROLE_OF_LAT2_NTAL_LAB_ON_CALCIUM_MOBILIZATION"
 [155] "REACTOME_REACTOME_SCAVENGING_OF_HEME_FROM_PLASMA"
 [156] "GOCC_GOCC_IMMUNOGLOBULIN_COMPLEX"
 [157] "C8_HAY_BONE_MARROW_PLATELET"
 [158] "REACTOME_REACTOME_FORMATION_OF_FIBRIN_CLOT_CLOTTING_CASCADE"
 [159] "REACTOME_REACTOME_INTRINSIC_PATHWAY_OF_FIBRIN_CLOT_FORMATION"
 [160] "REACTOME_REACTOME_P38MAPK_EVENTS"
 [161] "REACTOME_REACTOME_SYNTHESIS_OF_BILE_ACIDS_AND_BILE_SALTS_VIA_24_HYDROXYCHOLESTEROL"
 [162] "GOCC_GOCC_PORE_COMPLEX"
 [163] "C8_ZHONG_PFC_C3_UNKNOWN_INP"
 [164] "REACTOME_REACTOME_STRIATED_MUSCLE_CONTRACTION"
 [165] "GOCC_GOCC_A_BAND"
 [166] "GOCC_GOCC_M_BAND"
 [167] "GOCC_GOCC_STRIATED_MUSCLE_THIN_FILAMENT"
 [168] "C8_CUI_DEVELOPING_HEART_C2_CARDIOMYOCYTE"
 [169] "C8_DESCARTES_FETAL_EYE_SKELETAL_MUSCLE_CELLS"
 [170] "C8_DESCARTES_MAIN_FETAL_SKELETAL_MUSCLE_CELLS"
 [171] "REACTOME_REACTOME_SYNTHESIS_OF_PE"
 [172] "GOCC_GOCC_CD40_RECEPTOR_COMPLEX"
 [173] "GOCC_GOCC_PARASPECKLES"
 [174] "GOCC_GOCC_PHAGOPHORE_ASSEMBLY_SITE_MEMBRANE"
 [175] "GOCC_GOCC_RNAI_EFFECTOR_COMPLEX"
 [176] "GOCC_GOCC_TRANSCRIPTION_EXPORT_COMPLEX"
 [177] "GOCC_GOCC_TUMOR_NECROSIS_FACTOR_RECEPTOR_SUPERFAMILY_COMPLEX"
 [178] "GOCC_GOCC_AXONEMAL_DOUBLET_MICROTUBULE"
 [179] "GOCC_GOCC_AXONEMAL_MICROTUBULE"
 [180] "GOCC_GOCC_RADIAL_SPOKE"
 [181] "C8_DESCARTES_FETAL_LUNG_CILIATED_EPITHELIAL_CELLS"
 [182] "C8_DESCARTES_FETAL_STOMACH_CILIATED_EPITHELIAL_CELLS"
 [183] "C8_DESCARTES_MAIN_FETAL_CILIATED_EPITHELIAL_CELLS"
 [184] "C8_DURANTE_ADULT_OLFACTORY_NEUROEPITHELIUM_RESPIRATORY_CILIATED_CELLS"
 [185] "C8_GAO_ESOPHAGUS_25W_C1_CILIATED_EPITHELIAL_CELLS"
 [186] "REACTOME_REACTOME_DEFECTIVE_EXT2_CAUSES_EXOSTOSES_2"
 [187] "REACTOME_REACTOME_DEFECTS_OF_CONTACT_ACTIVATION_SYSTEM_CAS_AND_KALLIKREIN_KININ_SYSTEM_KKS"
 [188] "REACTOME_REACTOME_LYSOSPHINGOLIPID_AND_LPA_RECEPTORS"
 [189] "REACTOME_REACTOME_RUNX3_REGULATES_P14_ARF"
 [190] "REACTOME_REACTOME_VOLTAGE_GATED_POTASSIUM_CHANNELS"
 [191] "GOCC_GOCC_IGG_IMMUNOGLOBULIN_COMPLEX"
 [192] "GOCC_GOCC_PLATELET_DENSE_TUBULAR_NETWORK"
 [193] "C8_HE_LIM_SUN_FETAL_LUNG_C4_NKT2_CELL"
 [194] "REACTOME_REACTOME_ACTIVATION_OF_AMPK_DOWNSTREAM_OF_NMDARS"
 [195] "REACTOME_REACTOME_ALK_MUTANTS_BIND_TKIS"
 [196] "REACTOME_REACTOME_TRANSPORT_OF_CONNEXONS_TO_THE_PLASMA_MEMBRANE"
 [197] "C8_CUI_DEVELOPING_HEART_CARDIAC_FIBROBLASTS"
 [198] "C8_DESCARTES_MAIN_FETAL_CARDIOMYOCYTES"
 [199] "C8_DESCARTES_FETAL_ADRENAL_MEGAKARYOCYTES"
 [200] "C8_DESCARTES_FETAL_LIVER_MEGAKARYOCYTES"
 [201] "C8_DESCARTES_FETAL_LUNG_MEGAKARYOCYTES"
 [202] "C8_DESCARTES_MAIN_FETAL_MEGAKARYOCYTES"
 [203] "C8_HE_LIM_SUN_FETAL_LUNG_C2_MEGAKARYOCYTE"
 [204] "C8_TRAVAGLINI_LUNG_PLATELET_MEGAKARYOCYTE_CELL"
 [205] "REACTOME_REACTOME_ACTIVATED_PKN1_STIMULATES_TRANSCRIPTION_OF_AR_ANDROGEN_RECEPTOR_REGULATED_GENES_KLK2_AND_KLK3"
 [206] "REACTOME_REACTOME_ASSEMBLY_OF_THE_ORC_COMPLEX_AT_THE_ORIGIN_OF_REPLICATION"
 [207] "REACTOME_REACTOME_CHROMATIN_MODIFICATIONS_DURING_THE_MATERNAL_TO_ZYGOTIC_TRANSITION_MZT"
 [208] "REACTOME_REACTOME_RECYCLING_OF_BILE_ACIDS_AND_SALTS"
 [209] "REACTOME_REACTOME_GLUTATHIONE_SYNTHESIS_AND_RECYCLING"
 [210] "REACTOME_REACTOME_TYPE_I_HEMIDESMOSOME_ASSEMBLY"
 [211] "GOCC_GOCC_KERATIN_FILAMENT"
 [212] "C8_DESCARTES_FETAL_KIDNEY_URETERIC_BUD_CELLS"
 [213] "C8_DESCARTES_FETAL_STOMACH_SQUAMOUS_EPITHELIAL_CELLS"
 [214] "C8_DURANTE_ADULT_OLFACTORY_NEUROEPITHELIUM_OLFACTORY_HORIZONTAL_BASAL_CELLS"
 [215] "C8_DURANTE_ADULT_OLFACTORY_NEUROEPITHELIUM_RESPIRATORY_HORIZONTAL_BASAL_CELLS"
 [216] "REACTOME_REACTOME_PHOSPHOLIPASE_C_MEDIATED_CASCADE_FGFR2"
 [217] "REACTOME_REACTOME_PI3K_EVENTS_IN_ERBB2_SIGNALING"
 [218] "REACTOME_REACTOME_PI_3K_CASCADE_FGFR2"
 [219] "REACTOME_REACTOME_PI_3K_CASCADE_FGFR4"
 [220] "REACTOME_REACTOME_SIGNALING_BY_LEPTIN"
 [221] "REACTOME_REACTOME_STAT3_NUCLEAR_EVENTS_DOWNSTREAM_OF_ALK_SIGNALING"
 [222] "GOCC_GOCC_BCL_2_FAMILY_PROTEIN_COMPLEX"
 [223] "GOCC_GOCC_MISMATCH_REPAIR_COMPLEX"
 [224] "GOCC_GOCC_IMMUNOGLOBULIN_COMPLEX_CIRCULATING"
 [225] "GOCC_GOCC_MHC_CLASS_II_PROTEIN_COMPLEX"
 [226] "C8_AIZARANI_LIVER_C34_MHC_II_POS_B_CELLS"
 [227] "C8_AIZARANI_LIVER_C38_RESIDENT_B_CELLS_3"
 [228] "C8_DURANTE_ADULT_OLFACTORY_NEUROEPITHELIUM_B_CELLS"
 [229] "C8_FAN_EMBRYONIC_CTX_BRAIN_B_CELL"
 [230] "C8_HAY_BONE_MARROW_FOLLICULAR_B_CELL"
 [231] "C8_HE_LIM_SUN_FETAL_LUNG_C5_CD5_NEG_MATURE_B_CELL"
 [232] "C8_TRAVAGLINI_LUNG_B_CELL"
 [233] "C8_DESCARTES_FETAL_EYE_STROMAL_CELLS"
 [234] "C8_DESCARTES_FETAL_INTESTINE_STROMAL_CELLS"
 [235] "C8_DESCARTES_FETAL_MUSCLE_STROMAL_CELLS"
 [236] "REACTOME_REACTOME_DEVELOPMENTAL_LINEAGE_OF_MAMMARY_STEM_CELLS"
 [237] "REACTOME_REACTOME_DIFFERENTIATION_OF_KERATINOCYTES_IN_INTERFOLLICULAR_EPIDERMIS_IN_MAMMALIAN_SKIN"
 [238] "REACTOME_REACTOME_KERATINIZATION"
 [239] "GOCC_GOCC_CORNIFIED_ENVELOPE"
 [240] "C8_BUSSLINGER_ESOPHAGEAL_LATE_SUPRABASAL_CELLS"
 [241] "REACTOME_REACTOME_CARNITINE_SHUTTLE"
 [242] "REACTOME_REACTOME_ERYTHROPOIETIN_ACTIVATES_RAS"
 [243] "REACTOME_REACTOME_NEGATIVE_REGULATION_OF_NMDA_RECEPTOR_MEDIATED_NEURONAL_TRANSMISSION"
 [244] "GOCC_GOCC_ENDOPLASMIC_RETICULUM_PLASMA_MEMBRANE_CONTACT_SITE"
 [245] "GOCC_GOCC_EXTRINSIC_COMPONENT_OF_POSTSYNAPTIC_MEMBRANE"
 [246] "C8_DESCARTES_FETAL_CEREBELLUM_SLC24A4_PEX5L_POSITIVE_CELLS"
 [247] "C8_DESCARTES_FETAL_STOMACH_VASCULAR_ENDOTHELIAL_CELLS"
 [248] "C8_DESCARTES_MAIN_FETAL_MESOTHELIAL_CELLS"
 [249] "REACTOME_REACTOME_DEFENSINS"
 [250] "REACTOME_REACTOME_METABOLISM_OF_ANGIOTENSINOGEN_TO_ANGIOTENSINS"
 [251] "REACTOME_REACTOME_TP53_REGULATES_TRANSCRIPTION_OF_GENES_INVOLVED_IN_G1_CELL_CYCLE_ARREST"
 [252] "C8_HAY_BONE_MARROW_CD34_POS_EO_B_MAST"
 [253] "C8_HAY_BONE_MARROW_CD34_POS_GRAN"
 [254] "C8_HE_LIM_SUN_FETAL_LUNG_C2_GMP_CELL"
 [255] "C8_HE_LIM_SUN_FETAL_LUNG_C2_PROMYELOCYTE_LIKE_CELL"
 [256] "C8_CUI_DEVELOPING_HEART_CORONARY_VASCULAR_ENDOTHELIAL_CELL"
 [257] "C8_DESCARTES_FETAL_EYE_VASCULAR_ENDOTHELIAL_CELLS"
 [258] "C8_DESCARTES_FETAL_INTESTINE_VASCULAR_ENDOTHELIAL_CELLS"
 [259] "C8_DESCARTES_FETAL_KIDNEY_VASCULAR_ENDOTHELIAL_CELLS"
 [260] "C8_DESCARTES_FETAL_PANCREAS_VASCULAR_ENDOTHELIAL_CELLS"
 [261] "C8_DESCARTES_MAIN_FETAL_VASCULAR_ENDOTHELIAL_CELLS"
 [262] "C8_DURANTE_ADULT_OLFACTORY_NEUROEPITHELIUM_PERICYTES"
 [263] "REACTOME_REACTOME_ERYTHROPOIETIN_ACTIVATES_PHOSPHOINOSITIDE_3_KINASE_PI3K"
 [264] "REACTOME_REACTOME_NFE2L2_REGULATING_TUMORIGENIC_GENES"
 [265] "C8_TRAVAGLINI_LUNG_NEUTROPHIL_CELL"
 [266] "REACTOME_REACTOME_ASSEMBLY_OF_ACTIVE_LPL_AND_LIPC_LIPASE_COMPLEXES"
 [267] "C8_DESCARTES_FETAL_ADRENAL_SCHWANN_CELLS"
 [268] "C8_DESCARTES_FETAL_HEART_SCHWANN_CELLS"
 [269] "C8_DESCARTES_FETAL_INTESTINE_ENS_GLIA"
 [270] "C8_DESCARTES_MAIN_FETAL_ENS_GLIA"
 [271] "C8_DESCARTES_MAIN_FETAL_SCHWANN_CELLS"
 [272] "C8_DURANTE_ADULT_OLFACTORY_NEUROEPITHELIUM_OLFACTORY_ENSHEATHING_GLIA"
 [273] "C8_ZHONG_PFC_MAJOR_TYPES_OPC"
 [274] "HALL_HALLMARK_ANDROGEN_RESPONSE"
 [275] "REACTOME_REACTOME_REGULATION_OF_GENE_EXPRESSION_IN_BETA_CELLS"
 [276] "C8_DESCARTES_FETAL_ADRENAL_ERYTHROBLASTS"
 [277] "C8_DESCARTES_FETAL_LIVER_ERYTHROBLASTS"
 [278] "C8_DESCARTES_FETAL_PANCREAS_ERYTHROBLASTS"
 [279] "C8_HE_LIM_SUN_FETAL_LUNG_C3_DEFINITIVE_ERYTHROCYTE"
 [280] "C8_HE_LIM_SUN_FETAL_LUNG_C3_DEFINITIVE_RETICULOCYTE"
 [281] "C8_HE_LIM_SUN_FETAL_LUNG_C3_HMOX1_POS_PRIMITIVE_ERYTHROBLAST"
 [282] "REACTOME_REACTOME_ANTIGEN_ACTIVATES_B_CELL_RECEPTOR_BCR_LEADING_TO_GENERATION_OF_SECOND_MESSENGERS"
 [283] "REACTOME_REACTOME_FCGR_ACTIVATION"
 [284] "REACTOME_REACTOME_EUKARYOTIC_TRANSLATION_ELONGATION"
 [285] "REACTOME_REACTOME_EUKARYOTIC_TRANSLATION_INITIATION"
 [286] "REACTOME_REACTOME_NONSENSE_MEDIATED_DECAY_NMD"
 [287] "REACTOME_REACTOME_RESPONSE_OF_EIF2AK4_GCN2_TO_AMINO_ACID_DEFICIENCY"
 [288] "REACTOME_REACTOME_SARS_COV_1_MODULATES_HOST_TRANSLATION_MACHINERY"
 [289] "REACTOME_REACTOME_SRP_DEPENDENT_COTRANSLATIONAL_PROTEIN_TARGETING_TO_MEMBRANE"
 [290] "GOCC_GOCC_CYTOSOLIC_LARGE_RIBOSOMAL_SUBUNIT"
 [291] "C8_MANNO_MIDBRAIN_NEUROTYPES_BASAL"
 [292] "HALL_HALLMARK_ESTROGEN_RESPONSE_EARLY"
 [293] "HALL_HALLMARK_ESTROGEN_RESPONSE_LATE"
 [294] "REACTOME_REACTOME_AMINE_LIGAND_BINDING_RECEPTORS"
 [295] "REACTOME_REACTOME_METABOLISM_OF_NITRIC_OXIDE_NOS3_ACTIVATION_AND_REGULATION"
 [296] "REACTOME_REACTOME_RIBAVIRIN_ADME"
 [297] "REACTOME_REACTOME_BASE_EXCISION_REPAIR_AP_SITE_FORMATION"
 [298] "REACTOME_REACTOME_DNA_METHYLATION"
 [299] "REACTOME_REACTOME_INHIBITION_OF_DNA_RECOMBINATION_AT_TELOMERE"
 [300] "GOCC_GOCC_CHROMOSOME_CENTROMERIC_CORE_DOMAIN"
 [301] "REACTOME_REACTOME_RA_BIOSYNTHESIS_PATHWAY"
 [302] "REACTOME_REACTOME_TIE2_SIGNALING"
 [303] "GOCC_GOCC_CATENIN_COMPLEX"
 [304] "GOCC_GOCC_MICROVILLUS_MEMBRANE"
 [305] "C8_DESCARTES_FETAL_CEREBELLUM_PURKINJE_NEURONS"
 [306] "C8_DESCARTES_FETAL_CEREBELLUM_UNIPOLAR_BRUSH_CELLS"
 [307] "C8_DESCARTES_FETAL_CEREBRUM_SKOR2_NPSR1_POSITIVE_CELLS"
 [308] "REACTOME_REACTOME_PROLACTIN_RECEPTOR_SIGNALING"
 [309] "REACTOME_REACTOME_REGULATION_OF_CDH11_FUNCTION"
 [310] "REACTOME_REACTOME_TRYPTOPHAN_CATABOLISM"
 [311] "C8_DESCARTES_FETAL_ADRENAL_CSH1_CSH2_POSITIVE_CELLS"
 [312] "C8_DESCARTES_FETAL_PLACENTA_SYNCYTIOTROPHOBLASTS_AND_VILLOUS_CYTOTROPHOBLASTS"
 [313] "C8_DESCARTES_FETAL_PLACENTA_TROPHOBLAST_GIANT_CELLS"
 [314] "C8_DESCARTES_MAIN_FETAL_EXTRAVILLOUS_TROPHOBLASTS"
 [315] "C8_DESCARTES_MAIN_FETAL_SYNCYTIOTROPHOBLASTS_AND_VILLOUS_CYTOTROPHOBLASTS"
 [316] "C8_DESCARTES_MAIN_FETAL_TROPHOBLAST_GIANT_CELLS"
 [317] "REACTOME_REACTOME_ERBB2_ACTIVATES_PTK6_SIGNALING"
 [318] "REACTOME_REACTOME_FGFR1C_LIGAND_BINDING_AND_ACTIVATION"
 [319] "REACTOME_REACTOME_GLYCOGEN_BREAKDOWN_GLYCOGENOLYSIS"
 [320] "REACTOME_REACTOME_NF_KB_IS_ACTIVATED_AND_SIGNALS_SURVIVAL"
 [321] "GOCC_GOCC_POSTSYNAPTIC_SPECIALIZATION_INTRACELLULAR_COMPONENT"
 [322] "GOCC_GOCC_SOLID_PHASE_OF_BASEMENT_MEMBRANE"
 [323] "GOCC_GOCC_X_CHROMOSOME"
 [324] "GOCC_GOCC_APICOLATERAL_PLASMA_MEMBRANE"
 [325] "C8_DESCARTES_MAIN_FETAL_NEUROENDOCRINE_CELLS"
 [326] "REACTOME_REACTOME_COHESIN_LOADING_ONTO_CHROMATIN"
 [327] "REACTOME_REACTOME_ESTABLISHMENT_OF_SISTER_CHROMATID_COHESION"
 [328] "REACTOME_REACTOME_HDR_THROUGH_MMEJ_ALT_NHEJ"
 [329] "GOCC_GOCC_CENTRIOLAR_SUBDISTAL_APPENDAGE"
 [330] "GOCC_GOCC_COHESIN_COMPLEX"
 [331] "GOCC_GOCC_ISWI_TYPE_COMPLEX"
 [332] "GOCC_GOCC_PRERIBOSOME_LARGE_SUBUNIT_PRECURSOR"
 [333] "C8_MENON_FETAL_KIDNEY_0_CAP_MESENCHYME_CELLS"
 [334] "REACTOME_REACTOME_ABC_TRANSPORTERS_IN_LIPID_HOMEOSTASIS"
 [335] "REACTOME_REACTOME_ADENYLATE_CYCLASE_INHIBITORY_PATHWAY"
 [336] "REACTOME_REACTOME_FOXO_MEDIATED_TRANSCRIPTION_OF_CELL_DEATH_GENES"
 [337] "REACTOME_REACTOME_PKA_ACTIVATION_IN_GLUCAGON_SIGNALLING"
 [338] "REACTOME_REACTOME_REGULATION_OF_FOXO_TRANSCRIPTIONAL_ACTIVITY_BY_ACETYLATION"
 [339] "REACTOME_REACTOME_RUNX3_REGULATES_NOTCH_SIGNALING"
 [340] "REACTOME_REACTOME_SEMA3A_PLEXIN_REPULSION_SIGNALING_BY_INHIBITING_INTEGRIN_ADHESION"
 [341] "REACTOME_REACTOME_SIGNALLING_TO_RAS"
 [342] "REACTOME_REACTOME_TRAF3_DEPENDENT_IRF_ACTIVATION_PATHWAY"
 [343] "REACTOME_REACTOME_VEGFR2_MEDIATED_CELL_PROLIFERATION"
 [344] "C8_DESCARTES_MAIN_FETAL_ASTROCYTES"
 [345] "C8_FAN_EMBRYONIC_CTX_ASTROCYTE_1"
 [346] "C8_FAN_EMBRYONIC_CTX_ASTROCYTE_2"
 [347] "C8_FAN_EMBRYONIC_CTX_BIG_GROUPS_GLIAL"
 [348] "C8_MANNO_MIDBRAIN_NEUROTYPES_HRGL2A"
 [349] "C8_MANNO_MIDBRAIN_NEUROTYPES_HRGL2B"
 [350] "C8_MANNO_MIDBRAIN_NEUROTYPES_HRGL2C"
 [351] "C8_ZHONG_PFC_C9_ORG_OTHER"
 [352] "C8_ZHONG_PFC_MAJOR_TYPES_ASTROCYTES"
 [353] "REACTOME_REACTOME_NUCLEOTIDE_BIOSYNTHESIS"
 [354] "REACTOME_REACTOME_TRNA_MODIFICATION_IN_THE_MITOCHONDRION"
 [355] "GOCC_GOCC_90S_PRERIBOSOME"
 [356] "GOCC_GOCC_AMINOACYL_TRNA_SYNTHETASE_MULTIENZYME_COMPLEX"
 [357] "GOCC_GOCC_GEMINI_OF_CAJAL_BODIES"

In [7]:
gtex_summary <- data.frame(as.matrix(gtex$summary))

In [8]:
head(gtex_summary)

             pathway
REACTOME392  REACTOME_REACTOME_DISEASES_ASSOCIATED_WITH_SURFACTANT_METABOLISM
REACTOME1202 REACTOME_REACTOME_PURINE_SALVAGE
REACTOME814  REACTOME_REACTOME_LGI_ADAM_INTERACTIONS
REACTOME982  REACTOME_REACTOME_NEUROTOXICITY_OF_CLOSTRIDIUM_TOXINS
REACTOME1005 REACTOME_REACTOME_NOREPINEPHRINE_NEUROTRANSMITTER_RELEASE_CYCLE
REACTOME1161 REACTOME_REACTOME_PRESYNAPTIC_DEPOLARIZATION_AND_CALCIUM_CHANNEL_OPENING
             LV  AUC       p_value      FDR          npos nneg
REACTOME392  LV1 0.7913482 5.621963e-02 1.704579e-01   2  21591
REACTOME1202 LV1 0.4740285 5.562904e-01 7.614863e-01   2  21591
REACTOME814  LV2 0.9560856 1.015200e-02 4.782339e-02   2  21485
REACTOME982  LV2 0.9833139 6.961762e-03 3.587588e-02   2  21485
REACTOME1005 LV2 0.6759289 1.364694e-01 3.228949e-01   3  21485
REACTOME1161 LV2 0.5937165 3.167475e-01 5.637208e-01   2  21485

In [10]:
unique(gtex_summary$pathway)

   [1] "REACTOME_REACTOME_DISEASES_ASSOCIATED_WITH_SURFACTANT_METABOLISM"
   [2] "REACTOME_REACTOME_PURINE_SALVAGE"
   [3] "REACTOME_REACTOME_LGI_ADAM_INTERACTIONS"
   [4] "REACTOME_REACTOME_NEUROTOXICITY_OF_CLOSTRIDIUM_TOXINS"
   [5] "REACTOME_REACTOME_NOREPINEPHRINE_NEUROTRANSMITTER_RELEASE_CYCLE"
   [6] "REACTOME_REACTOME_PRESYNAPTIC_DEPOLARIZATION_AND_CALCIUM_CHANNEL_OPENING"
   [7] "REACTOME_REACTOME_SYNAPTIC_ADHESION_LIKE_MOLECULES"
   [8] "REACTOME_REACTOME_TRAFFICKING_OF_GLUR2_CONTAINING_AMPA_RECEPTORS"
   [9] "REACTOME_REACTOME_WNT5A_DEPENDENT_INTERNALIZATION_OF_FZD4"
  [10] "GOCC_GOCC_AMPA_GLUTAMATE_RECEPTOR_COMPLEX"
  [11] "GOCC_GOCC_NEUROFILAMENT"
  [12] "GOCC_GOCC_PARALLEL_FIBER_TO_PURKINJE_CELL_SYNAPSE"
  [13] "REACTOME_REACTOME_CHK1_CHK2_CDS1_MEDIATED_INACTIVATION_OF_CYCLIN_B_CDK1_COMPLEX"
  [14] "REACTOME_REACTOME_ERCC6_CSB_AND_EHMT2_G9A_POSITIVELY_REGULATE_RRNA_EXPRESSION"
  [15] "REACTOME_REACTOME_FOLDING_OF_ACTIN_BY_CCT_TRIC"
  [16] "REACTOME_REACTOME_GLUCONEOGENESIS"
  [17] "REACTOME_REACTOME_P75NTR_REGULATES_AXONOGENESIS"
  [18] "REACTOME_REACTOME_PENTOSE_PHOSPHATE_PATHWAY"
  [19] "REACTOME_REACTOME_RHOBTB3_ATPASE_CYCLE"
  [20] "REACTOME_REACTOME_SUMOYLATION_OF_TRANSCRIPTION_FACTORS"
  [21] "REACTOME_REACTOME_TP53_REGULATES_TRANSCRIPTION_OF_GENES_INVOLVED_IN_G1_CELL_CYCLE_ARREST"
  [22] "REACTOME_REACTOME_TRANSCRIPTIONAL_REGULATION_OF_TESTIS_DIFFERENTIATION"
  [23] "GOCC_GOCC_PROTEIN_COMPLEX_INVOLVED_IN_CELL_MATRIX_ADHESION"
  [24] "C8_CUI_DEVELOPING_HEART_C3_FIBROBLAST_LIKE_CELL"
  [25] "C8_CUI_DEVELOPING_HEART_SMOOTH_MUSCLE_CELL"
  [26] "C8_DESCARTES_FETAL_EYE_STROMAL_CELLS"
  [27] "C8_DESCARTES_FETAL_INTESTINE_STROMAL_CELLS"
  [28] "C8_DESCARTES_MAIN_FETAL_STROMAL_CELLS"
  [29] "C8_DURANTE_ADULT_OLFACTORY_NEUROEPITHELIUM_FIBROBLASTS_STROMAL_CELLS"
  [30] "C8_GAO_LARGE_INTESTINE_24W_C1_DCLK1POS_PROGENITOR"
  [31] "REACTOME_REACTOME_FORMATION_OF_THE_CORNIFIED_ENVELOPE"
  [32] "REACTOME_REACTOME_THYROXINE_BIOSYNTHESIS"
  [33] "C8_BUSSLINGER_ESOPHAGEAL_LATE_SUPRABASAL_CELLS"
  [34] "C8_DESCARTES_FETAL_LUNG_SQUAMOUS_EPITHELIAL_CELLS"
  [35] "C8_DESCARTES_FETAL_STOMACH_SQUAMOUS_EPITHELIAL_CELLS"
  [36] "C8_DESCARTES_MAIN_FETAL_SQUAMOUS_EPITHELIAL_CELLS"
  [37] "C8_DURANTE_ADULT_OLFACTORY_NEUROEPITHELIUM_RESPIRATORY_COLUMNAR_CELLS"
  [38] "REACTOME_REACTOME_ACTIVATED_NTRK2_SIGNALS_THROUGH_FRS2_AND_FRS3"
  [39] "REACTOME_REACTOME_CONSTITUTIVE_SIGNALING_BY_OVEREXPRESSED_ERBB2"
  [40] "REACTOME_REACTOME_NOTCH2_INTRACELLULAR_DOMAIN_REGULATES_TRANSCRIPTION"
  [41] "REACTOME_REACTOME_PYRIMIDINE_CATABOLISM"
  [42] "REACTOME_REACTOME_SIGNALING_BY_BMP"
  [43] "REACTOME_REACTOME_SIGNALING_BY_LTK"
  [44] "REACTOME_REACTOME_SIGNAL_ATTENUATION"
  [45] "REACTOME_REACTOME_TRAF3_DEPENDENT_IRF_ACTIVATION_PATHWAY"
  [46] "GOCC_GOCC_APICAL_DENDRITE"
  [47] "REACTOME_REACTOME_APOPTOTIC_CLEAVAGE_OF_CELL_ADHESION_PROTEINS"
  [48] "REACTOME_REACTOME_DIFFERENTIATION_OF_KERATINOCYTES_IN_INTERFOLLICULAR_EPIDERMIS_IN_MAMMALIAN_SKIN"
  [49] "REACTOME_REACTOME_KERATINIZATION"
  [50] "REACTOME_REACTOME_TYPE_I_HEMIDESMOSOME_ASSEMBLY"
  [51] "GOCC_GOCC_INTRACILIARY_TRANSPORT_PARTICLE_B"
  [52] "GOCC_GOCC_LAMININ_COMPLEX"
  [53] "C8_HAY_BONE_MARROW_CD34_POS_ERP_EARLY"
  [54] "C8_CUI_DEVELOPING_HEART_CORONARY_VASCULAR_ENDOTHELIAL_CELL"
  [55] "C8_DESCARTES_FETAL_ADRENAL_VASCULAR_ENDOTHELIAL_CELLS"
  [56] "C8_DESCARTES_FETAL_HEART_VASCULAR_ENDOTHELIAL_CELLS"
  [57] "C8_DESCARTES_FETAL_KIDNEY_VASCULAR_ENDOTHELIAL_CELLS"
  [58] "C8_DESCARTES_FETAL_LUNG_VASCULAR_ENDOTHELIAL_CELLS"
  [59] "C8_DESCARTES_FETAL_MUSCLE_VASCULAR_ENDOTHELIAL_CELLS"
  [60] "C8_DESCARTES_FETAL_PANCREAS_VASCULAR_ENDOTHELIAL_CELLS"
  [61] "C8_DESCARTES_FETAL_STOMACH_VASCULAR_ENDOTHELIAL_CELLS"
  [62] "C8_RUBENSTEIN_SKELETAL_MUSCLE_ENDOTHELIAL_CELLS"
  [63] "REACTOME_REACTOME_ANTIGEN_PROCESSING_UB_ATP_INDEPENDENT_PROTEASOMAL_DEGRADATION"
  [64] "REACTOME_REACTOME_NEGATIVE_REGULATION_OF_NOTCH4_SIGNALING"
  [65] "REACTOME_REACTOME_PROTEASOME_ASSEMBLY"
  [66] "REACTOME_REACTOME_REGULATION_OF_ORNITHINE_DECARBOXYLASE_ODC"
  [67] "GOCC_GOCC_COPI_VESICLE_COAT"
  [68] "GOCC_GOCC_PROTEASOME_ACCESSORY_COMPLEX"
  [69] "GOCC_GOCC_PROTEASOME_CORE_COMPLEX_BETA_SUBUNIT_COMPLEX"
  [70] "REACTOME_REACTOME_ACETYLCHOLINE_REGULATES_INSULIN_SECRETION"
  [71] "REACTOME_REACTOME_CGMP_EFFECTS"
  [72] "REACTOME_REACTOME_GOLGI_CISTERNAE_PERICENTRIOLAR_STACK_REORGANIZATION"
  [73] "REACTOME_REACTOME_MET_ACTIVATES_RAP1_AND_RAC1"
  [74] "REACTOME_REACTOME_PI3K_EVENTS_IN_ERBB4_SIGNALING"
  [75] "REACTOME_REACTOME_RETINOID_CYCLE_DISEASE_EVENTS"
  [76] "REACTOME_REACTOME_SHC1_EVENTS_IN_ERBB4_SIGNALING"
  [77] "C8_DESCARTES_FETAL_CEREBELLUM_INHIBITORY_INTERNEURONS"
  [78] "C8_DESCARTES_MAIN_FETAL_GANGLION_CELLS"
  [79] "C8_ZHONG_PFC_C3_PROX1_CCK_POS_INTERNEURON"
  [80] "REACTOME_REACTOME_ACTIVATION_OF_THE_PRE_REPLICATIVE_COMPLEX"
  [81] "REACTOME_REACTOME_DEFECTIVE_PYROPTOSIS"
  [82] "REACTOME_REACTOME_DNA_STRAND_ELONGATION"
  [83] "REACTOME_REACTOME_POLYMERASE_SWITCHING"
  [84] "REACTOME_REACTOME_UNWINDING_OF_DNA"
  [85] "GOCC_GOCC_INNER_KINETOCHORE"
  [86] "REACTOME_REACTOME_CLEC7A_DECTIN_1_INDUCES_NFAT_ACTIVATION"
  [87] "REACTOME_REACTOME_METABOLISM_OF_FOLATE_AND_PTERINES"
  [88] "REACTOME_REACTOME_PHOSPHORYLATION_OF_CLOCK_ACETYLATION_OF_BMAL1_ARNTL_AT_TARGET_GENE_PROMOTERS"
  [89] "REACTOME_REACTOME_REGULATION_BY_C_FLIP"
  [90] "REACTOME_REACTOME_SEMA3A_PLEXIN_REPULSION_SIGNALING_BY_INHIBITING_INTEGRIN_ADHESION"
  [91] "GOCC_GOCC_PLATELET_ALPHA_GRANULE_MEMBRANE"
  [92] "C8_AIZARANI_LIVER_C20_LSECS_3"
  [93] "C8_LAKE_ADULT_KIDNEY_C25_ENDOTHELIAL_CELLS_UNASSIGNED"
  [94] "C8_TRAVAGLINI_LUNG_VEIN_CELL"
  [95] "REACTOME_REACTOME_ALK_MUTANTS_BIND_TKIS"
  [96] "REACTOME_REACTOME_CARGO_CONCENTRATION_IN_THE_ER"
  [97] "REACTOME_REACTOME_CHOLESTEROL_BIOSYNTHESIS_VIA_DESMOSTEROL_BLOCH_PATHWAY"
  [98] "REACTOME_REACTOME_ERBB2_ACTIVATES_PTK6_SIGNALING"
  [99] "REACTOME_REACTOME_MITOCHONDRIAL_FATTY_ACID_BETA_OXIDATION_OF_SATURATED_FATTY_ACIDS"
 [100] "REACTOME_REACTOME_PEROXISOMAL_PROTEIN_IMPORT"
 [101] "GOCC_GOCC_COPI_COATED_VESICLE_MEMBRANE"
 [102] "GOCC_GOCC_MICROBODY_LUMEN"
 [103] "REACTOME_REACTOME_MITOCHONDRIAL_TRANSLATION_ELONGATION"
 [104] "GOCC_GOCC_IRON_SULFUR_CLUSTER_ASSEMBLY_COMPLEX"
 [105] "GOCC_GOCC_MITOCHONDRIAL_LARGE_RIBOSOMAL_SUBUNIT"
 [106] "GOCC_GOCC_MITOCHONDRIAL_SMALL_RIBOSOMAL_SUBUNIT"
 [107] "GOCC_GOCC_ORGANELLAR_RIBOSOME"
 [108] "GOCC_GOCC_PRERIBOSOME_LARGE_SUBUNIT_PRECURSOR"
 [109] "GOCC_GOCC_PROTEASOME_CORE_COMPLEX"
 [110] "GOCC_GOCC_RIBONUCLEASE_P_COMPLEX"
 [111] "GOCC_GOCC_TIM23_MITOCHONDRIAL_IMPORT_INNER_MEMBRANE_TRANSLOCASE_COMPLEX"
 [112] "REACTOME_REACTOME_REGULATION_OF_IFNG_SIGNALING"
 [113] "GOCC_GOCC_ASTROCYTE_END_FOOT"
 [114] "C8_DESCARTES_FETAL_ADRENAL_SCHWANN_CELLS"
 [115] "C8_DESCARTES_FETAL_HEART_SCHWANN_CELLS"
 [116] "C8_DESCARTES_MAIN_FETAL_SCHWANN_CELLS"
 [117] "C8_DURANTE_ADULT_OLFACTORY_NEUROEPITHELIUM_OLFACTORY_ENSHEATHING_GLIA"
 [118] "C8_FAN_EMBRYONIC_CTX_IN_4_INTERNEURON"
 [119] "REACTOME_REACTOME_STRIATED_MUSCLE_CONTRACTION"
 [120] "GOCC_GOCC_A_BAND"
 [121] "C8_CUI_DEVELOPING_HEART_C2_CARDIOMYOCYTE"
 [122] "C8_CUI_DEVELOPING_HEART_CARDIAC_FIBROBLASTS"
 [123] "C8_DESCARTES_FETAL_CEREBRUM_INHIBITORY_NEURONS"
 [124] "C8_DESCARTES_FETAL_INTESTINE_ENS_GLIA"
 [125] "C8_DESCARTES_FETAL_MUSCLE_SCHWANN_CELLS"
 [126] "C8_DESCARTES_FETAL_PANCREAS_ENS_GLIA"
 [127] "C8_DESCARTES_FETAL_SPLEEN_STROMAL_CELLS"
 [128] "C8_DESCARTES_FETAL_STOMACH_ENS_GLIA"
 [129] "REACTOME_REACTOME_FGFR1_LIGAND_BINDING_AND_ACTIVATION"
 [130] "REACTOME_REACTOME_HDR_THROUGH_MMEJ_ALT_NHEJ"
 [131] "REACTOME_REACTOME_INTERACTIONS_OF_VPR_WITH_HOST_CELLULAR_PROTEINS"
 [132] "REACTOME_REACTOME_KILLING_MECHANISMS"
 [133] "REACTOME_REACTOME_REGULATION_OF_GLUCOKINASE_BY_GLUCOKINASE_REGULATORY_PROTEIN"
 [134] "REACTOME_REACTOME_TETRAHYDROBIOPTERIN_BH4_SYNTHESIS_RECYCLING_SALVAGE_AND_REGULATION"
 [135] "GOCC_GOCC_CHROMOCENTER"
 [136] "GOCC_GOCC_LATERAL_ELEMENT"
 [137] "REACTOME_REACTOME_PI_3K_CASCADE_FGFR2"
 [138] "REACTOME_REACTOME_THE_CRY_PER_KINASE_COMPLEX_REPRESSES_TRANSACTIVATION_BY_THE_BMAL_CLOCK_ARNTL_CLOCK_COMPLEX"
 [139] "REACTOME_REACTOME_XENOBIOTICS"
 [140] "GOCC_GOCC_SPECIALIZED_EXTRACELLULAR_MATRIX"
 [141] "REACTOME_REACTOME_BETA_OXIDATION_OF_VERY_LONG_CHAIN_FATTY_ACIDS"
 [142] "REACTOME_REACTOME_BIOTIN_TRANSPORT_AND_METABOLISM"
 [143] "REACTOME_REACTOME_BRANCHED_CHAIN_AMINO_ACID_CATABOLISM"
 [144] "REACTOME_REACTOME_DISEASES_OF_BRANCHED_CHAIN_AMINO_ACID_CATABOLISM"
 [145] "REACTOME_REACTOME_MITOCHONDRIAL_FATTY_ACID_BETA_OXIDATION"
 [146] "REACTOME_REACTOME_PEROXISOMAL_LIPID_METABOLISM"
 [147] "C8_AIZARANI_LIVER_C11_HEPATOCYTES_1"
 [148] "C8_DESCARTES_MAIN_FETAL_HEPATOBLASTS"
 [149] "REACTOME_REACTOME_MET_RECEPTOR_RECYCLING"
 [150] "REACTOME_REACTOME_SYNTHESIS_SECRETION_AND_INACTIVATION_OF_GLUCAGON_LIKE_PEPTIDE_1_GLP_1"
 [151] "GOCC_GOCC_VOLTAGE_GATED_SODIUM_CHANNEL_COMPLEX"
 [152] "C8_DESCARTES_FETAL_ADRENAL_SYMPATHOBLASTS"
 [153] "C8_FAN_EMBRYONIC_CTX_BIG_GROUPS_INHIBITORY"
 [154] "C8_LAKE_ADULT_KIDNEY_C1_EPITHELIAL_CELLS_UNASSIGNED"
 [155] "C8_ZHONG_PFC_C6_DLX5_GAD1_GAD2_POS_INTERNEURON"
 [156] "C8_ZHONG_PFC_C7_SST_LHX6_POS_PUTATIVE_MIGRATING_INTERNEURON"
 [157] "REACTOME_REACTOME_ACTIVATION_OF_THE_MRNA_UPON_BINDING_OF_THE_CAP_BINDING_COMPLEX_AND_EIFS_AND_SUBSEQUENT_BINDING_TO_43S"
 [158] "REACTOME_REACTOME_EUKARYOTIC_TRANSLATION_ELONGATION"
 [159] "REACTOME_REACTOME_EUKARYOTIC_TRANSLATION_INITIATION"
 [160] "REACTOME_REACTOME_RESPONSE_OF_EIF2AK4_GCN2_TO_AMINO_ACID_DEFICIENCY"
 [161] "REACTOME_REACTOME_SARS_COV_1_MODULATES_HOST_TRANSLATION_MACHINERY"
 [162] "REACTOME_REACTOME_SELENOAMINO_ACID_METABOLISM"
 [163] "REACTOME_REACTOME_SRP_DEPENDENT_COTRANSLATIONAL_PROTEIN_TARGETING_TO_MEMBRANE"
 [164] "GOCC_GOCC_CYTOSOLIC_LARGE_RIBOSOMAL_SUBUNIT"
 [165] "GOCC_GOCC_CYTOSOLIC_SMALL_RIBOSOMAL_SUBUNIT"
 [166] "C8_SU_HO_FOETAL_FEMUR_C0_TRANSITIONING_CELL"
 [167] "GOCC_GOCC_JUXTAPARANODE_REGION_OF_AXON"
 [168] "C8_DESCARTES_FETAL_EYE_PDE11A_FAM19A2_POSITIVE_CELLS"
 [169] "REACTOME_REACTOME_DEFECTIVE_C1GALT1C1_CAUSES_TNPS"
 [170] "REACTOME_REACTOME_DEFECTIVE_GALNT3_CAUSES_HFTC"
 [171] "REACTOME_REACTOME_DEVELOPMENTAL_LINEAGE_OF_PANCREATIC_ACINAR_CELLS"
 [172] "REACTOME_REACTOME_DIGESTION"
 [173] "REACTOME_REACTOME_DISSOLUTION_OF_FIBRIN_CLOT"
 [174] "REACTOME_REACTOME_REGULATION_OF_BETA_CELL_DEVELOPMENT"
 [175] "REACTOME_REACTOME_REGULATION_OF_GENE_EXPRESSION_IN_BETA_CELLS"
 [176] "C8_DESCARTES_FETAL_PANCREAS_ACINAR_CELLS"
 [177] "C8_DESCARTES_MAIN_FETAL_ACINAR_CELLS"
 [178] "C8_DESCARTES_MAIN_FETAL_DUCTAL_CELLS"
 [179] "REACTOME_REACTOME_LYSOSPHINGOLIPID_AND_LPA_RECEPTORS"
 [180] "GOCC_GOCC_CHYLOMICRON"
 [181] "C8_DESCARTES_FETAL_LUNG_STROMAL_CELLS"
 [182] "C8_DESCARTES_MAIN_FETAL_BRONCHIOLAR_AND_ALVEOLAR_EPITHELIAL_CELLS"
 [183] "C8_HE_LIM_SUN_FETAL_LUNG_C3_MID_CAP_CELL"
 [184] "C8_TRAVAGLINI_LUNG_ALVEOLAR_FIBROBLAST_CELL"
 [185] "C8_TRAVAGLINI_LUNG_CAPILLARY_CELL"
 [186] "GOCC_GOCC_LARGE_RIBOSOMAL_SUBUNIT"
 [187] "GOCC_GOCC_RIBOSOMAL_SUBUNIT"
 [188] "GOCC_GOCC_SMALL_RIBOSOMAL_SUBUNIT"
 [189] "GOCC_GOCC_SPERMATOPROTEASOME_COMPLEX"
 [190] "REACTOME_REACTOME_LYSINE_CATABOLISM"
 [191] "REACTOME_REACTOME_SULFUR_AMINO_ACID_METABOLISM"
 [192] "REACTOME_REACTOME_UREA_CYCLE"
 [193] "GOCC_GOCC_MYELIN_SHEATH"
 [194] "C8_DESCARTES_FETAL_CEREBELLUM_OLIGODENDROCYTES"
 [195] "C8_DESCARTES_FETAL_CEREBRUM_OLIGODENDROCYTES"
 [196] "C8_FAN_EMBRYONIC_CTX_OLIG"
 [197] "REACTOME_REACTOME_AMINE_LIGAND_BINDING_RECEPTORS"
 [198] "REACTOME_REACTOME_REGULATION_OF_PTEN_STABILITY_AND_ACTIVITY"
 [199] "REACTOME_REACTOME_ACTIVATION_OF_THE_TFAP2_AP_2_FAMILY_OF_TRANSCRIPTION_FACTORS"
 [200] "REACTOME_REACTOME_DEVELOPMENTAL_LINEAGES_OF_THE_MAMMARY_GLAND"
 [201] "REACTOME_REACTOME_DEVELOPMENTAL_LINEAGE_OF_MAMMARY_GLAND_LUMINAL_EPITHELIAL_CELLS"
 [202] "REACTOME_REACTOME_REVERSIBLE_HYDRATION_OF_CARBON_DIOXIDE"
 [203] "REACTOME_REACTOME_TFAP2_AP_2_FAMILY_REGULATES_TRANSCRIPTION_OF_GROWTH_FACTORS_AND_THEIR_RECEPTORS"
 [204] "GOCC_GOCC_APICOLATERAL_PLASMA_MEMBRANE"
 [205] "C8_DESCARTES_FETAL_CEREBRUM_LIMBIC_SYSTEM_NEURONS"
 [206] "REACTOME_REACTOME_ASPARTATE_AND_ASPARAGINE_METABOLISM"
 [207] "REACTOME_REACTOME_N_GLYCAN_ANTENNAE_ELONGATION"
 [208] "REACTOME_REACTOME_PKA_MEDIATED_PHOSPHORYLATION_OF_CREB"
 [209] "REACTOME_REACTOME_SYNTHESIS_OF_BILE_ACIDS_AND_BILE_SALTS_VIA_24_HYDROXYCHOLESTEROL"
 [210] "GOCC_GOCC_PROTEASOME_STORAGE_GRANULE"
 [211] "REACTOME_REACTOME_ADENYLATE_CYCLASE_ACTIVATING_PATHWAY"
 [212] "REACTOME_REACTOME_EFFECTS_OF_PIP2_HYDROLYSIS"
 [213] "REACTOME_REACTOME_TRAFFICKING_OF_AMPA_RECEPTORS"
 [214] "GOCC_GOCC_NUCLEOLAR_EXOSOME_RNASE_COMPLEX"
 [215] "GOCC_GOCC_POSTSYNAPTIC_CYTOSKELETON"
 [216] "C8_ZHONG_PFC_MAJOR_TYPES_INTERNEURON"
 [217] "REACTOME_REACTOME_CD22_MEDIATED_BCR_REGULATION"
 [218] "REACTOME_REACTOME_CREATION_OF_C4_AND_C2_ACTIVATORS"
 [219] "REACTOME_REACTOME_FCGR_ACTIVATION"
 [220] "REACTOME_REACTOME_ROLE_OF_LAT2_NTAL_LAB_ON_CALCIUM_MOBILIZATION"
 [221] "REACTOME_REACTOME_SCAVENGING_OF_HEME_FROM_PLASMA"
 [222] "GOCC_GOCC_IGA_IMMUNOGLOBULIN_COMPLEX"
 [223] "GOCC_GOCC_IMMUNOGLOBULIN_COMPLEX"
 [224] "GOCC_GOCC_IMMUNOGLOBULIN_COMPLEX_CIRCULATING"
 [225] "C8_BUSSLINGER_GASTRIC_CHIEF_CELLS"
 [226] "C8_BUSSLINGER_GASTRIC_NECK_CELLS"
 [227] "C8_BUSSLINGER_GASTRIC_OXYNTIC_ENTEROCHROMAFFIN_LIKE_CELLS"
 [228] "C8_BUSSLINGER_GASTRIC_PREZYMOGENIC_CELLS"
 [229] "C8_DESCARTES_FETAL_LUNG_NEUROENDOCRINE_CELLS"
 [230] "C8_DESCARTES_FETAL_STOMACH_NEUROENDOCRINE_CELLS"
 [231] "C8_DESCARTES_MAIN_FETAL_GOBLET_CELLS"
 [232] "HALL_HALLMARK_ANDROGEN_RESPONSE"
 [233] "REACTOME_REACTOME_ALPHA_LINOLENIC_OMEGA3_AND_LINOLEIC_OMEGA6_ACID_METABOLISM"
 [234] "REACTOME_REACTOME_GLUTATHIONE_SYNTHESIS_AND_RECYCLING"
 [235] "REACTOME_REACTOME_SERINE_METABOLISM"
 [236] "C8_DURANTE_ADULT_OLFACTORY_NEUROEPITHELIUM_OLFACTORY_MICROVILLAR_CELLS"
 [237] "C8_HE_LIM_SUN_FETAL_LUNG_C4_NKT2_CELL"
 [238] "REACTOME_REACTOME_COHESIN_LOADING_ONTO_CHROMATIN"
 [239] "REACTOME_REACTOME_EXPRESSION_OF_BMAL_ARNTL_CLOCK_AND_NPAS2"
 [240] "REACTOME_REACTOME_FORMATION_OF_THE_POLYBROMO_BAF_PBAF_COMPLEX"
 [241] "REACTOME_REACTOME_HDMS_DEMETHYLATE_HISTONES"
 [242] "REACTOME_REACTOME_SIGNALING_BY_CYTOSOLIC_FGFR1_FUSION_MUTANTS"
 [243] "GOCC_GOCC_BBAF_COMPLEX"
 [244] "GOCC_GOCC_BETA_CATENIN_TCF_COMPLEX"
 [245] "GOCC_GOCC_GID_COMPLEX"
 [246] "GOCC_GOCC_NSL_COMPLEX"
 [247] "REACTOME_REACTOME_ACYL_CHAIN_REMODELLING_OF_PI"
 [248] "C8_DESCARTES_FETAL_CEREBELLUM_SLC24A4_PEX5L_POSITIVE_CELLS"
 [249] "C8_HAY_BONE_MARROW_CD34_POS_MULTILIN"
 [250] "REACTOME_REACTOME_INTERLEUKIN_15_SIGNALING"
 [251] "REACTOME_REACTOME_SIGNALING_BY_ACTIVIN"
 [252] "REACTOME_REACTOME_SYNTHESIS_OF_BILE_ACIDS_AND_BILE_SALTS_VIA_7ALPHA_HYDROXYCHOLESTEROL"
 [253] "GOCC_GOCC_CELL_TRAILING_EDGE"
 [254] "GOCC_GOCC_CYTOLYTIC_GRANULE"
 [255] "GOCC_GOCC_ENDOPLASMIC_RETICULUM_CHAPERONE_COMPLEX"
 [256] "GOCC_GOCC_L_TYPE_VOLTAGE_GATED_CALCIUM_CHANNEL_COMPLEX"
 [257] "GOCC_GOCC_PARASPECKLES"
 [258] "GOCC_GOCC_PHOTORECEPTOR_OUTER_SEGMENT_MEMBRANE"
 [259] "REACTOME_REACTOME_ERYTHROPOIETIN_ACTIVATES_PHOSPHOINOSITIDE_3_KINASE_PI3K"
 [260] "REACTOME_REACTOME_MECP2_REGULATES_NEURONAL_RECEPTORS_AND_CHANNELS"
 [261] "REACTOME_REACTOME_MITOCHONDRIAL_UNFOLDED_PROTEIN_RESPONSE_UPRMT"
 [262] "REACTOME_REACTOME_PI3K_EVENTS_IN_ERBB2_SIGNALING"
 [263] "REACTOME_REACTOME_SIGNALING_BY_FGFR4_IN_DISEASE"
 [264] "GOCC_GOCC_ISWI_TYPE_COMPLEX"
 [265] "REACTOME_REACTOME_KERATAN_SULFATE_DEGRADATION"
 [266] "C8_DESCARTES_FETAL_HEART_STROMAL_CELLS"
 [267] "C8_DESCARTES_FETAL_MUSCLE_STROMAL_CELLS"
 [268] "C8_DESCARTES_FETAL_STOMACH_MESOTHELIAL_CELLS"
 [269] "C8_HE_LIM_SUN_FETAL_LUNG_C0_ADVENTITIAL_FIBROBLAST"
 [270] "C8_RUBENSTEIN_SKELETAL_MUSCLE_FAP_CELLS"
 [271] "C8_TRAVAGLINI_LUNG_ADVENTITIAL_FIBROBLAST_CELL"
 [272] "REACTOME_REACTOME_REGULATION_OF_CDH11_FUNCTION"
 [273] "C8_DESCARTES_MAIN_FETAL_ASTROCYTES"
 [274] "C8_FAN_EMBRYONIC_CTX_ASTROCYTE_1"
 [275] "C8_FAN_EMBRYONIC_CTX_ASTROCYTE_2"
 [276] "C8_FAN_EMBRYONIC_CTX_BIG_GROUPS_GLIAL"
 [277] "C8_HU_FETAL_RETINA_MULLER"
 [278] "C8_ZHONG_PFC_C9_ORG_OTHER"
 [279] "C8_ZHONG_PFC_MAJOR_TYPES_ASTROCYTES"
 [280] "REACTOME_REACTOME_PHASE_4_RESTING_MEMBRANE_POTENTIAL"
 [281] "GOCC_GOCC_BCL_2_FAMILY_PROTEIN_COMPLEX"
 [282] "GOCC_GOCC_U6_SNRNP"
 [283] "HALL_HALLMARK_TNFA_SIGNALING_VIA_NFKB"
 [284] "REACTOME_REACTOME_INTERLEUKIN_10_SIGNALING"
 [285] "REACTOME_REACTOME_NGF_STIMULATED_TRANSCRIPTION"
 [286] "REACTOME_REACTOME_NPAS4_REGULATES_EXPRESSION_OF_TARGET_GENES"
 [287] "REACTOME_REACTOME_TRANSCRIPTIONAL_REGULATION_BY_NPAS4"
 [288] "C8_DURANTE_ADULT_OLFACTORY_NEUROEPITHELIUM_RESPIRATORY_SECRETORY_CELLS"
 [289] "REACTOME_REACTOME_EICOSANOID_LIGAND_BINDING_RECEPTORS"
 [290] "REACTOME_REACTOME_FANCONI_ANEMIA_PATHWAY"
 [291] "REACTOME_REACTOME_REGULATION_OF_CDH1_MRNA_TRANSLATION_BY_MICRORNAS"
 [292] "REACTOME_REACTOME_RORA_B_C_AND_NR1D1_REV_ERBA_REGULATE_GENE_EXPRESSION"
 [293] "GOCC_GOCC_DNA_REPAIR_COMPLEX"
 [294] "GOCC_GOCC_PRESPLICEOSOME"
 [295] "GOCC_GOCC_RNAI_EFFECTOR_COMPLEX"
 [296] "REACTOME_REACTOME_DEVELOPMENTAL_LINEAGE_OF_MAMMARY_GLAND_ALVEOLAR_CELLS"
 [297] "REACTOME_REACTOME_REGULATION_OF_MITF_M_DEPENDENT_GENES_INVOLVED_IN_LYSOSOME_BIOGENESIS_AND_AUTOPHAGY"
 [298] "C8_DESCARTES_FETAL_STOMACH_LYMPHATIC_ENDOTHELIAL_CELLS"
 [299] "REACTOME_REACTOME_GLYOXYLATE_METABOLISM_AND_GLYCINE_DEGRADATION"
 [300] "GOCC_GOCC_PROTON_TRANSPORTING_TWO_SECTOR_ATPASE_COMPLEX"
 [301] "GOCC_GOCC_PROTON_TRANSPORTING_TWO_SECTOR_ATPASE_COMPLEX_CATALYTIC_DOMAIN"
 [302] "GOCC_GOCC_PROTON_TRANSPORTING_V_TYPE_ATPASE_COMPLEX"
 [303] "C8_DESCARTES_MAIN_FETAL_URETERIC_BUD_CELLS"
 [304] "C8_MENON_FETAL_KIDNEY_5_PROXIMAL_TUBULE_CELLS"
 [305] "C8_DESCARTES_FETAL_HEART_ELF3_AGBL2_POSITIVE_CELLS"
 [306] "C8_DESCARTES_FETAL_LUNG_CILIATED_EPITHELIAL_CELLS"
 [307] "C8_DESCARTES_FETAL_STOMACH_CILIATED_EPITHELIAL_CELLS"
 [308] "C8_DESCARTES_MAIN_FETAL_CILIATED_EPITHELIAL_CELLS"
 [309] "HALL_HALLMARK_HEME_METABOLISM"
 [310] "C8_DESCARTES_FETAL_INTESTINE_ERYTHROBLASTS"
 [311] "C8_DESCARTES_FETAL_KIDNEY_ERYTHROBLASTS"
 [312] "C8_DESCARTES_FETAL_PANCREAS_ERYTHROBLASTS"
 [313] "C8_DESCARTES_MAIN_FETAL_ERYTHROBLASTS"
 [314] "C8_HE_LIM_SUN_FETAL_LUNG_C3_DEFINITIVE_RETICULOCYTE"
 [315] "REACTOME_REACTOME_PROCESSING_OF_INTRONLESS_PRE_MRNAS"
 [316] "GOCC_GOCC_RNA_POLYMERASE_III_TRANSCRIPTION_REGULATOR_COMPLEX"
 [317] "REACTOME_REACTOME_GLYCOGEN_BREAKDOWN_GLYCOGENOLYSIS"
 [318] "REACTOME_REACTOME_METALLOTHIONEINS_BIND_METALS"
 [319] "REACTOME_REACTOME_MITOCHONDRIAL_IRON_SULFUR_CLUSTER_BIOGENESIS"
 [320] "REACTOME_REACTOME_RESPONSE_TO_METAL_IONS"
 [321] "GOCC_GOCC_SYNAPSE_ASSOCIATED_EXTRACELLULAR_MATRIX"
 [322] "C8_DESCARTES_FETAL_CEREBRUM_ASTROCYTES"
 [323] "REACTOME_REACTOME_INWARDLY_RECTIFYING_K_CHANNELS"
 [324] "REACTOME_REACTOME_VLDLR_INTERNALISATION_AND_DEGRADATION"
 [325] "REACTOME_REACTOME_WNT5A_DEPENDENT_INTERNALIZATION_OF_FZD2_FZD5_AND_ROR2"
 [326] "C8_DESCARTES_MAIN_FETAL_STC2_TLX1_POSITIVE_CELLS"
 [327] "C8_FAN_EMBRYONIC_CTX_MICROGLIA_3"
 [328] "C8_HE_LIM_SUN_FETAL_LUNG_C2_APOE_POS_M1_MACROPHAGE_CELL"
 [329] "REACTOME_REACTOME_MATURATION_OF_SARS_COV_1_NUCLEOPROTEIN"
 [330] "REACTOME_REACTOME_MITOCHONDRIAL_MRNA_MODIFICATION"
 [331] "REACTOME_REACTOME_RUNX3_REGULATES_P14_ARF"
 [332] "REACTOME_REACTOME_SUMOYLATION_OF_IMMUNE_RESPONSE_PROTEINS"
 [333] "GOCC_GOCC_EXTRINSIC_COMPONENT_OF_POSTSYNAPTIC_MEMBRANE"
 [334] "GOCC_GOCC_NUCLEOLAR_RIBONUCLEASE_P_COMPLEX"
 [335] "C8_HAY_BONE_MARROW_CD34_POS_GRAN"
 [336] "HALL_HALLMARK_ESTROGEN_RESPONSE_EARLY"
 [337] "REACTOME_REACTOME_CARNITINE_SHUTTLE"
 [338] "REACTOME_REACTOME_DEVELOPMENTAL_LINEAGE_OF_MAMMARY_STEM_CELLS"
 [339] "REACTOME_REACTOME_PI_3K_CASCADE_FGFR3"
 [340] "C8_DESCARTES_FETAL_LIVER_HEMATOPOIETIC_STEM_CELLS"
 [341] "REACTOME_REACTOME_FREE_FATTY_ACIDS_REGULATE_INSULIN_SECRETION"
 [342] "C8_BUSSLINGER_DUODENAL_GOBLET_CELLS"
 [343] "C8_DURANTE_ADULT_OLFACTORY_NEUROEPITHELIUM_BOWMANS_GLAND"
 [344] "C8_DURANTE_ADULT_OLFACTORY_NEUROEPITHELIUM_RESPIRATORY_EPITHELIAL_CELLS"
 [345] "C8_TRAVAGLINI_LUNG_SEROUS_CELL"
 [346] "REACTOME_REACTOME_ACYL_CHAIN_REMODELLING_OF_PC"

In [11]:
library(dplyr)

archs4_sig <- archs4_summary %>%
  mutate(
    AUC = as.numeric(AUC),
    FDR = as.numeric(FDR)
  ) %>%
  filter(FDR < 0.05, AUC > 0.7) %>%
  distinct(pathway)

gtex_sig <- gtex_summary %>%
  mutate(
    AUC = as.numeric(AUC),
    FDR = as.numeric(FDR)
  ) %>%
  filter(FDR < 0.05, AUC > 0.7) %>%
  distinct(pathway)

archs4_only_sig_pathways <- archs4_sig %>%
  anti_join(gtex_sig, by = "pathway")

In [13]:
nrow(archs4_only_sig_pathways)

[1] 499

In [14]:
head(archs4_only_sig_pathways)

             pathway
REACTOME1049 REACTOME_REACTOME_OLFACTORY_SIGNALING_PATHWAY
GOCC1071     GOCC_GOCC_VOLTAGE_GATED_SODIUM_CHANNEL_COMPLEX
REACTOME609  REACTOME_REACTOME_GERM_LAYER_FORMATION_AT_GASTRULATION
C832         C8_BUSSLINGER_DUODENAL_BCHE_CELLS
C883         C8_CUI_DEVELOPING_HEART_COMPACT_VENTRICULAR_CARDIOMYOCYTE
C8260        C8_DESCARTES_FETAL_STOMACH_STROMAL_CELLS

In [15]:
print(archs4_only_sig_pathways$pathway)

  [1] "REACTOME_REACTOME_OLFACTORY_SIGNALING_PATHWAY"
  [2] "GOCC_GOCC_VOLTAGE_GATED_SODIUM_CHANNEL_COMPLEX"
  [3] "REACTOME_REACTOME_GERM_LAYER_FORMATION_AT_GASTRULATION"
  [4] "C8_BUSSLINGER_DUODENAL_BCHE_CELLS"
  [5] "C8_CUI_DEVELOPING_HEART_COMPACT_VENTRICULAR_CARDIOMYOCYTE"
  [6] "C8_DESCARTES_FETAL_STOMACH_STROMAL_CELLS"
  [7] "C8_FAN_OVARY_CL6_PUTATIVE_EARLY_ATRETIC_FOLLICLE_THECAL_CELL_2"
  [8] "C8_JONES_OVARY_STROMAL"
  [9] "REACTOME_REACTOME_ASPIRIN_ADME"
 [10] "C8_CUI_DEVELOPING_HEART_C8_MACROPHAGE"
 [11] "C8_HAY_BONE_MARROW_NEUTROPHIL"
 [12] "REACTOME_REACTOME_CONDENSATION_OF_PROMETAPHASE_CHROMOSOMES"
 [13] "REACTOME_REACTOME_NPAS4_REGULATES_EXPRESSION_OF_TARGET_GENES"
 [14] "REACTOME_REACTOME_RESPONSE_TO_METAL_IONS"
 [15] "C8_DESCARTES_FETAL_SPLEEN_MYELOID_CELLS"
 [16] "C8_DESCARTES_FETAL_KIDNEY_LYMPHOID_CELLS"
 [17] "REACTOME_REACTOME_BINDING_AND_UPTAKE_OF_LIGANDS_BY_SCAVENGER_RECEPTORS"
 [18] "REACTOME_REACTOME_FORMATION_OF_FIBRIN_CLOT_CLOTTING_CASCADE"
 [19] "REACTOME_REACTOME_INTRINSIC_PATHWAY_OF_FIBRIN_CLOT_FORMATION"
 [20] "REACTOME_REACTOME_P38MAPK_EVENTS"
 [21] "GOCC_GOCC_STRIATED_MUSCLE_THIN_FILAMENT"
 [22] "GOCC_GOCC_RADIAL_SPOKE"
 [23] "C8_GAO_ESOPHAGUS_25W_C1_CILIATED_EPITHELIAL_CELLS"
 [24] "C8_DESCARTES_MAIN_FETAL_MEGAKARYOCYTES"
 [25] "C8_HE_LIM_SUN_FETAL_LUNG_C2_MEGAKARYOCYTE"
 [26] "REACTOME_REACTOME_PI3K_EVENTS_IN_ERBB2_SIGNALING"
 [27] "REACTOME_REACTOME_PI_3K_CASCADE_FGFR2"
 [28] "REACTOME_REACTOME_PI_3K_CASCADE_FGFR4"
 [29] "REACTOME_REACTOME_SIGNALING_BY_LEPTIN"
 [30] "REACTOME_REACTOME_STAT3_NUCLEAR_EVENTS_DOWNSTREAM_OF_ALK_SIGNALING"
 [31] "C8_FAN_EMBRYONIC_CTX_BRAIN_B_CELL"
 [32] "C8_HAY_BONE_MARROW_CD34_POS_GRAN"
 [33] "C8_HE_LIM_SUN_FETAL_LUNG_C2_GMP_CELL"
 [34] "C8_DESCARTES_MAIN_FETAL_VASCULAR_ENDOTHELIAL_CELLS"
 [35] "C8_ZHONG_PFC_MAJOR_TYPES_OPC"
 [36] "C8_DESCARTES_FETAL_ADRENAL_ERYTHROBLASTS"
 [37] "C8_HE_LIM_SUN_FETAL_LUNG_C3_DEFINITIVE_ERYTHROCYTE"
 [38] "REACTOME_REACTOME_NONSENSE_MEDIATED_DECAY_NMD"
 [39] "C8_MANNO_MIDBRAIN_NEUROTYPES_BASAL"
 [40] "HALL_HALLMARK_ESTROGEN_RESPONSE_LATE"
 [41] "REACTOME_REACTOME_ACTIVATED_PKN1_STIMULATES_TRANSCRIPTION_OF_AR_ANDROGEN_RECEPTOR_REGULATED_GENES_KLK2_AND_KLK3"
 [42] "REACTOME_REACTOME_BASE_EXCISION_REPAIR_AP_SITE_FORMATION"
 [43] "REACTOME_REACTOME_CHROMATIN_MODIFICATIONS_DURING_THE_MATERNAL_TO_ZYGOTIC_TRANSITION_MZT"
 [44] "REACTOME_REACTOME_DNA_METHYLATION"
 [45] "REACTOME_REACTOME_INHIBITION_OF_DNA_RECOMBINATION_AT_TELOMERE"
 [46] "GOCC_GOCC_CHROMOSOME_CENTROMERIC_CORE_DOMAIN"
 [47] "GOCC_GOCC_CATENIN_COMPLEX"
 [48] "C8_DESCARTES_FETAL_ADRENAL_CSH1_CSH2_POSITIVE_CELLS"
 [49] "C8_DESCARTES_FETAL_PLACENTA_SYNCYTIOTROPHOBLASTS_AND_VILLOUS_CYTOTROPHOBLASTS"
 [50] "C8_DESCARTES_FETAL_PLACENTA_TROPHOBLAST_GIANT_CELLS"
 [51] "C8_DESCARTES_MAIN_FETAL_EXTRAVILLOUS_TROPHOBLASTS"
 [52] "C8_DESCARTES_MAIN_FETAL_SYNCYTIOTROPHOBLASTS_AND_VILLOUS_CYTOTROPHOBLASTS"
 [53] "C8_DESCARTES_MAIN_FETAL_TROPHOBLAST_GIANT_CELLS"
 [54] "GOCC_GOCC_ISWI_TYPE_COMPLEX"
 [55] "C8_MENON_FETAL_KIDNEY_0_CAP_MESENCHYME_CELLS"
 [56] "REACTOME_REACTOME_VEGFR2_MEDIATED_CELL_PROLIFERATION"
 [57] "C8_MANNO_MIDBRAIN_NEUROTYPES_HRGL2A"
 [58] "C8_MANNO_MIDBRAIN_NEUROTYPES_HRGL2B"
 [59] "C8_MANNO_MIDBRAIN_NEUROTYPES_HRGL2C"
 [60] "GOCC_GOCC_NUCLEOLAR_EXOSOME_RNASE_COMPLEX"
 [61] "GOCC_GOCC_PRERIBOSOME_LARGE_SUBUNIT_PRECURSOR"
 [62] "GOCC_GOCC_PRERIBOSOME_SMALL_SUBUNIT_PRECURSOR"
 [63] "REACTOME_REACTOME_ASSEMBLY_OF_THE_ORC_COMPLEX_AT_THE_ORIGIN_OF_REPLICATION"
 [64] "REACTOME_REACTOME_CONDENSATION_OF_PROPHASE_CHROMOSOMES"
 [65] "REACTOME_REACTOME_PRC2_METHYLATES_HISTONES_AND_DNA"
 [66] "REACTOME_REACTOME_TRANSCRIPTIONAL_REGULATION_BY_SMALL_RNAS"
 [67] "REACTOME_REACTOME_NOREPINEPHRINE_NEUROTRANSMITTER_RELEASE_CYCLE"
 [68] "REACTOME_REACTOME_ATTACHMENT_AND_ENTRY"
 [69] "REACTOME_REACTOME_ATTACHMENT_OF_BACTERIA_TO_EPITHELIAL_CELLS"
 [70] "REACTOME_REACTOME_ERBB2_REGULATES_CELL_MOTILITY"
 [71] "REACTOME_REACTOME_NFE2L2_REGULATING_TUMORIGENIC_GENES"
 [72] "REACTOME_REACTOME_MITOCHONDRIAL_TRANSLATION"
 [73] "C8_BUSSLINGER_DUODENAL_MX_CELLS"
 [74] "C8_BUSSLINGER_GASTRIC_OXYNTIC_ENTEROCHROMAFFIN_LIKE_CELLS"
 [75] "C8_MURARO_PANCREAS_ALPHA_CELL"
 [76] "C8_VANGURP_PANCREATIC_ALPHA_CELL"
 [77] "C8_HAY_BONE_MARROW_CD34_POS_HSC"
 [78] "C8_HAY_BONE_MARROW_CD34_POS_MULTILIN"
 [79] "C8_HE_LIM_SUN_FETAL_LUNG_C2_HSC_ELP_CELL"
 [80] "C8_HE_LIM_SUN_FETAL_LUNG_C5_LATE_PRO_B_CELL"
 [81] "C8_ZHENG_CORD_BLOOD_C4_PUTATIVE_EARLY_ERYTHROID_COMMITMENT"
 [82] "C8_ZHENG_CORD_BLOOD_C8_PUTATIVE_LYMPHOID_PRIMED_MULTIPOTENT_PROGENITOR_2"
 [83] "REACTOME_REACTOME_INTERFERON_ALPHA_BETA_SIGNALING"
 [84] "REACTOME_REACTOME_FORMATION_OF_ATP_BY_CHEMIOSMOTIC_COUPLING"
 [85] "REACTOME_REACTOME_REGULATION_OF_GENE_EXPRESSION_IN_LATE_STAGE_BRANCHING_MORPHOGENESIS_PANCREATIC_BUD_PRECURSOR_CELLS"
 [86] "C8_DESCARTES_MAIN_FETAL_BIPOLAR_CELLS"
 [87] "C8_MENON_FETAL_KIDNEY_3_STROMAL_CELLS"
 [88] "C8_DESCARTES_FETAL_PLACENTA_IGFBP1_DKK1_POSITIVE_CELLS"
 [89] "C8_DESCARTES_FETAL_PLACENTA_PAEP_MECOM_POSITIVE_CELLS"
 [90] "C8_DESCARTES_MAIN_FETAL_IGFBP1_DKK1_POSITIVE_CELLS"
 [91] "C8_DESCARTES_MAIN_FETAL_PAEP_MECOM_POSITIVE_CELLS"
 [92] "REACTOME_REACTOME_INSULIN_RECEPTOR_RECYCLING"
 [93] "C8_SU_HO_CONV_CENT_CHONDROSARCOMA_LEUKOCYTE_C0_M1_MACROPHAGE"
 [94] "C8_TRAVAGLINI_LUNG_EREG_DENDRITIC_CELL"
 [95] "C8_TRAVAGLINI_LUNG_OLR1_CLASSICAL_MONOCYTE_CELL"
 [96] "REACTOME_REACTOME_SYNTHESIS_OF_PROSTAGLANDINS_PG_AND_THROMBOXANES_TX"
 [97] "C8_DESCARTES_FETAL_LIVER_LYMPHOID_CELLS"
 [98] "C8_TRAVAGLINI_LUNG_CD8_MEMORY_EFFECTOR_T_CELL"
 [99] "C8_HE_LIM_SUN_FETAL_LUNG_C0_LATE_AIRWAY_SMC_CELL"
[100] "C8_HE_LIM_SUN_FETAL_LUNG_C0_MID_AIRWAY_SMC_1_CELL"
[101] "C8_TRAVAGLINI_LUNG_FIBROMYOCYTE_CELL"
[102] "C8_AIZARANI_LIVER_C1_NK_NKT_CELLS_1"
[103] "C8_CUI_DEVELOPING_HEART_C9_B_T_CELL"
[104] "C8_FAN_EMBRYONIC_CTX_BRAIN_NAIVE_LIKE_T_CELL"
[105] "C8_JONES_OVARY_OOCYTE"
[106] "GOCC_GOCC_RIBBON_SYNAPSE"
[107] "C8_DESCARTES_FETAL_EYE_PHOTORECEPTOR_CELLS"
[108] "C8_DESCARTES_MAIN_FETAL_PHOTORECEPTOR_CELLS"
[109] "C8_HU_FETAL_RETINA_BIPOLAR"
[110] "C8_HU_FETAL_RETINA_PHOTORECEPTOR"
[111] "REACTOME_REACTOME_RESOLUTION_OF_D_LOOP_STRUCTURES"
[112] "REACTOME_REACTOME_RESOLUTION_OF_D_LOOP_STRUCTURES_THROUGH_SYNTHESIS_DEPENDENT_STRAND_ANNEALING_SDSA"
[113] "GOCC_GOCC_LATERAL_ELEMENT"
[114] "C8_DESCARTES_MAIN_FETAL_HORIZONTAL_CELLS"
[115] "C8_BUSSLINGER_DUODENAL_EARLY_IMMATURE_ENTEROCYTES"
[116] "C8_GAO_SMALL_INTESTINE_24W_C4_ENTEROCYTE_PROGENITOR_SUBTYPE_2"
[117] "C8_DURANTE_ADULT_OLFACTORY_NEUROEPITHELIUM_PLASMA_CELLS"
[118] "C8_GAO_LARGE_INTESTINE_ADULT_CI_MESENCHYMAL_CELLS"
[119] "C8_HAY_BONE_MARROW_PLASMA_CELL"
[120] "C8_HE_LIM_SUN_FETAL_LUNG_C1_LATE_TIP_CELL"
[121] "C8_DESCARTES_FETAL_MUSCLE_SATELLITE_CELLS"
[122] "C8_DESCARTES_MAIN_FETAL_SATELLITE_CELLS"
[123] "REACTOME_REACTOME_REGULATION_OF_MITF_M_DEPENDENT_GENES_INVOLVED_IN_EXTRACELLULAR_MATRIX_FOCAL_ADHESION_AND_EPITHELIAL_TO_MESENCHYMAL_TRANSITION"
[124] "REACTOME_REACTOME_DIFFERENTIATION_OF_NAIVE_CD_T_CELLS_TO_T_HELPER_1_CELLS_TH1_CELLS"
[125] "REACTOME_REACTOME_INTERLEUKIN_2_SIGNALING"
[126] "C8_HE_LIM_SUN_FETAL_LUNG_C4_ACTIVATED_NK_CELL"
[127] "C8_ZHENG_CORD_BLOOD_C6_HSC_MULTIPOTENT_PROGENITOR"
[128] "GOCC_GOCC_MYELIN_SHEATH"
[129] "C8_ZHONG_PFC_C4_PTGDS_POS_OPC"
[130] "C8_AIZARANI_LIVER_C3_NK_NKT_CELLS_2"
[131] "C8_FAN_OVARY_CL12_T_LYMPHOCYTE_NK_CELL_2"
[132] "C8_FAN_OVARY_CL4_T_LYMPHOCYTE_NK_CELL_1"
[133] "C8_HAY_BONE_MARROW_CD34_POS_PRE_B"
[134] "C8_HAY_BONE_MARROW_CD34_POS_PRE_PC"
[135] "HALL_HALLMARK_MYOGENESIS"
[136] "REACTOME_REACTOME_RESPONSE_OF_EIF2AK1_HRI_TO_HEME_DEFICIENCY"
[137] "GOCC_GOCC_DESMOSOME"
[138] "C8_CUI_DEVELOPING_HEART_C5_VALVAR_CELL"
[139] "C8_ZHENG_CORD_BLOOD_C5_SIMILAR_TO_HSC_C6_PUTATIVE_ALTERED_METABOLIC_STATE"
[140] "GOCC_GOCC_SYMBIONT_CELL_SURFACE"
[141] "C8_DESCARTES_FETAL_LIVER_MYELOID_CELLS"
[142] "GOCC_GOCC_TUMOR_NECROSIS_FACTOR_RECEPTOR_SUPERFAMILY_COMPLEX"
[143] "C8_ZHENG_CORD_BLOOD_C7_PUTATIVE_LYMPHOID_PRIMED_MULTIPOTENT_PROGENITOR_1"
[144] "REACTOME_REACTOME_DISEASES_ASSOCIATED_WITH_GLYCOSAMINOGLYCAN_METABOLISM"
[145] "C8_HE_LIM_SUN_FETAL_LUNG_C0_ASPN_POS_CHONDROCYTE"
[146] "C8_HE_LIM_SUN_FETAL_LUNG_C0_INTERM_CHONDROCYTE"
[147] "C8_HE_LIM_SUN_FETAL_LUNG_C0_RESTING_CHONDROCYTE"
[148] "C8_SU_HO_CONV_CENT_CHONDROSARCOMA_STROMAL_C3_FIBROCARTILAGE_CHONDROCYTE"
[149] "C8_ZHENG_CORD_BLOOD_C3_MEGAKARYOCYTE_ERYTHROID_PROGENITOR"
[150] "C8_HAY_BONE_MARROW_CD34_POS_ERP_EARLY"
[151] "C8_DESCARTES_MAIN_FETAL_NEUROENDOCRINE_CELLS"
[152] "REACTOME_REACTOME_ANTIMICROBIAL_PEPTIDES"
[153] "REACTOME_REACTOME_DEFENSINS"
[154] "REACTOME_REACTOME_SIGNALLING_TO_RAS"
[155] "GOCC_GOCC_NUCLEOTIDE_ACTIVATED_PROTEIN_KINASE_COMPLEX"
[156] "REACTOME_REACTOME_IL_6_TYPE_CYTOKINE_RECEPTOR_LIGAND_INTERACTIONS"
[157] "C8_DESCARTES_FETAL_SPLEEN_ERYTHROBLASTS"
[158] "REACTOME_REACTOME_REGULATION_OF_CDH1_MRNA_TRANSLATION_BY_MICRORNAS"
[159] "REACTOME_REACTOME_O_LINKED_GLYCOSYLATION"
[160] "C8_ZHONG_PFC_C6_DLX5_GAD1_GAD2_POS_INTERNEURON"
[161] "REACTOME_REACTOME_DS_GAG_BIOSYNTHESIS"
[162] "HALL_HALLMARK_P53_PATHWAY"
[163] "REACTOME_REACTOME_HS_GAG_DEGRADATION"
[164] "REACTOME_REACTOME_INTERLEUKIN_15_SIGNALING"
[165] "REACTOME_REACTOME_MATURATION_OF_SARS_COV_2_SPIKE_PROTEIN"
[166] "REACTOME_REACTOME_CONSTITUTIVE_SIGNALING_BY_EGFRVIII"
[167] "REACTOME_REACTOME_ERYTHROPOIETIN_ACTIVATES_PHOSPHOINOSITIDE_3_KINASE_PI3K"
[168] "REACTOME_REACTOME_SIGNALING_BY_ERYTHROPOIETIN"
[169] "REACTOME_REACTOME_SIGNALING_BY_PDGFRA_TRANSMEMBRANE_JUXTAMEMBRANE_AND_KINASE_DOMAIN_MUTANTS"
[170] "GOCC_GOCC_MISMATCH_REPAIR_COMPLEX"
[171] "GOCC_GOCC_HIGH_DENSITY_LIPOPROTEIN_PARTICLE"
[172] "REACTOME_REACTOME_FOXO_MEDIATED_TRANSCRIPTION_OF_CELL_DEATH_GENES"
[173] "REACTOME_REACTOME_NUCLEAR_RECEPTOR_TRANSCRIPTION_PATHWAY"
[174] "REACTOME_REACTOME_REPRESSION_OF_WNT_TARGET_GENES"
[175] "GOCC_GOCC_RESPIRATORY_CHAIN_COMPLEX_IV"
[176] "REACTOME_REACTOME_RECOGNITION_AND_ASSOCIATION_OF_DNA_GLYCOSYLASE_WITH_SITE_CONTAINING_AN_AFFECTED_PURINE"
[177] "REACTOME_REACTOME_REGULATION_OF_ENDOGENOUS_RETROELEMENTS_BY_THE_HUMAN_SILENCING_HUB_HUSH_COMPLEX"
[178] "GOCC_GOCC_SPECIFIC_GRANULE"
[179] "GOCC_GOCC_SPECIFIC_GRANULE_LUMEN"
[180] "GOCC_GOCC_SPECIFIC_GRANULE_MEMBRANE"
[181] "GOCC_GOCC_TERTIARY_GRANULE_MEMBRANE"
[182] "C8_DESCARTES_FETAL_HEART_SATB2_LRRC7_POSITIVE_CELLS"
[183] "REACTOME_REACTOME_IRAK4_DEFICIENCY_TLR2_4"
[184] "REACTOME_REACTOME_REGULATION_OF_TLR_BY_ENDOGENOUS_LIGAND"
[185] "GOCC_GOCC_GATOR2_COMPLEX"
[186] "GOCC_GOCC_SEH1_ASSOCIATED_COMPLEX"
[187] "REACTOME_REACTOME_CYTOSOLIC_TRNA_AMINOACYLATION"
[188] "C8_HAY_BONE_MARROW_MONOCYTE"
[189] "C8_HE_LIM_SUN_FETAL_LUNG_C0_MYOFIBROBLAST_1_CELL"
[190] "GOCC_GOCC_SOLID_PHASE_OF_BASEMENT_MEMBRANE"
[191] "REACTOME_REACTOME_FORMATION_OF_DEFINITIVE_ENDODERM"
[192] "C8_HE_LIM_SUN_FETAL_LUNG_C4_TREG_CELL"
[193] "REACTOME_REACTOME_CARDIOGENESIS"
[194] "C8_HE_LIM_SUN_FETAL_LUNG_C7_MFNG_POS_DBH_POS_NEURON_CELL"
[195] "C8_HAY_BONE_MARROW_DENDRITIC_CELL"
[196] "C8_HE_LIM_SUN_FETAL_LUNG_C2_PDC_CELL"
[197] "C8_TRAVAGLINI_LUNG_PLASMACYTOID_DENDRITIC_CELL"
[198] "REACTOME_REACTOME_GENERATION_OF_SECOND_MESSENGER_MOLECULES"
[199] "HALL_HALLMARK_CHOLESTEROL_HOMEOSTASIS"
[200] "REACTOME_REACTOME_FATTY_ACYL_COA_BIOSYNTHESIS"
[201] "C8_MURARO_PANCREAS_ACINAR_CELL"
[202] "GOCC_GOCC_DENSE_CORE_GRANULE"
[203] "REACTOME_REACTOME_DISEASES_ASSOCIATED_WITH_O_GLYCOSYLATION_OF_PROTEINS"
[204] "REACTOME_REACTOME_GRB2_SOS_PROVIDES_LINKAGE_TO_MAPK_SIGNALING_FOR_INTEGRINS"
[205] "C8_TRAVAGLINI_LUNG_MACROPHAGE_CELL"
[206] "REACTOME_REACTOME_MET_PROMOTES_CELL_MOTILITY"
[207] "REACTOME_REACTOME_PARACETAMOL_ADME"
[208] "C8_ZHONG_PFC_C2_THY1_POS_OPC"
[209] "REACTOME_REACTOME_INFLUENZA_VIRAL_RNA_TRANSCRIPTION_AND_REPLICATION"
[210] "REACTOME_REACTOME_ARACHIDONATE_METABOLISM"
[211] "REACTOME_REACTOME_CYTOCHROME_P450_ARRANGED_BY_SUBSTRATE_TYPE"
[212] "REACTOME_REACTOME_MRNA_CAPPING"
[213] "GOCC_GOCC_TRICARBOXYLIC_ACID_CYCLE_HETEROMERIC_ENZYME_COMPLEX"
[214] "REACTOME_REACTOME_ERCC6_CSB_AND_EHMT2_G9A_POSITIVELY_REGULATE_RRNA_EXPRESSION"
[215] "GOCC_GOCC_CYTOSOLIC_RIBOSOME"
[216] "REACTOME_REACTOME_CS_GAG_BIOSYNTHESIS"
[217] "REACTOME_REACTOME_DEFECTS_OF_CONTACT_ACTIVATION_SYSTEM_CAS_AND_KALLIKREIN_KININ_SYSTEM_KKS"
[218] "REACTOME_REACTOME_SYNTHESIS_OF_BILE_ACIDS_AND_BILE_SALTS_VIA_24_HYDROXYCHOLESTEROL"
[219] "GOCC_GOCC_OUTER_KINETOCHORE"
[220] "C8_HE_LIM_SUN_FETAL_LUNG_C2_PROMONOCYTE_LIKE_CELL"
[221] "C8_ZHONG_PFC_C8_ORG_PROLIFERATING"
[222] "GOCC_GOCC_PROTON_TRANSPORTING_ATP_SYNTHASE_COMPLEX"
[223] "C8_FAN_OVARY_CL10_PUTATIVE_EARLY_ATRESIA_GRANULOSA_CELL"
[224] "GOCC_GOCC_GID_COMPLEX"
[225] "REACTOME_REACTOME_DEVELOPMENTAL_CELL_LINEAGES_OF_THE_INTEGUMENTARY_SYSTEM"
[226] "REACTOME_REACTOME_GAP_JUNCTION_ASSEMBLY"
[227] "REACTOME_REACTOME_POST_CHAPERONIN_TUBULIN_FOLDING_PATHWAY"
[228] "REACTOME_REACTOME_CHEMOKINE_RECEPTORS_BIND_CHEMOKINES"
[229] "REACTOME_REACTOME_DISEASES_OF_IMMUNE_SYSTEM"
[230] "REACTOME_REACTOME_INTERLEUKIN_6_SIGNALING"
[231] "REACTOME_REACTOME_MAPK3_ERK1_ACTIVATION"
[232] "C8_HE_LIM_SUN_FETAL_LUNG_C6_MUC16_POS_CILIATED_CELL"
[233] "REACTOME_REACTOME_NOTCH2_INTRACELLULAR_DOMAIN_REGULATES_TRANSCRIPTION"
[234] "REACTOME_REACTOME_HYALURONAN_DEGRADATION"
[235] "REACTOME_REACTOME_SIGNALING_BY_FLT3_ITD_AND_TKD_MUTANTS"
[236] "C8_DESCARTES_FETAL_STOMACH_ERYTHROBLASTS"
[237] "REACTOME_REACTOME_DOPAMINE_NEUROTRANSMITTER_RELEASE_CYCLE"
[238] "C8_HE_LIM_SUN_FETAL_LUNG_C7_TM4SF4_POS_CHODL_POS_NEURON_CELL"
[239] "C8_MANNO_MIDBRAIN_NEUROTYPES_HOMTN"
[240] "C8_HE_LIM_SUN_FETAL_LUNG_C2_DC2_CELL"
[241] "C8_DESCARTES_MAIN_FETAL_THYMOCYTES"
[242] "C8_HE_LIM_SUN_FETAL_LUNG_C4_ILC3_CELL"
[243] "REACTOME_REACTOME_CONSTITUTIVE_SIGNALING_BY_AKT1_E17K_IN_CANCER"
[244] "REACTOME_REACTOME_REGULATION_OF_IFNA_IFNB_SIGNALING"
[245] "REACTOME_REACTOME_KIDNEY_DEVELOPMENT"
[246] "REACTOME_REACTOME_ASSEMBLY_OF_ACTIVE_LPL_AND_LIPC_LIPASE_COMPLEXES"
[247] "REACTOME_REACTOME_PLASMA_LIPOPROTEIN_REMODELING"
[248] "C8_HE_LIM_SUN_FETAL_LUNG_C0_MYOFIBROBLAST_2_CELL"
[249] "C8_HE_LIM_SUN_FETAL_LUNG_C4_ILC2_CELL"
[250] "C8_TRAVAGLINI_LUNG_BASOPHIL_MAST_2_CELL"
[251] "C8_ZHENG_CORD_BLOOD_C2_PUTATIVE_BASOPHIL_EOSINOPHIL_MAST_CELL_PROGENITOR"
[252] "REACTOME_REACTOME_GP1B_IX_V_ACTIVATION_SIGNALLING"
[253] "C8_DESCARTES_FETAL_PLACENTA_EXTRAVILLOUS_TROPHOBLASTS"
[254] "GOCC_GOCC_CILIARY_BASE"
[255] "GOCC_GOCC_CILIARY_TRANSITION_ZONE"
[256] "GOCC_GOCC_MKS_COMPLEX"
[257] "C8_CUI_DEVELOPING_HEART_RIGHT_VENTRICULAR_CARDIOMYOCYTE"
[258] "GOCC_GOCC_AGGRESOME"
[259] "REACTOME_REACTOME_INTERACTION_BETWEEN_L1_AND_ANKYRINS"
[260] "REACTOME_REACTOME_ENDOSOMAL_VACUOLAR_PATHWAY"
[261] "REACTOME_REACTOME_REPLACEMENT_OF_PROTAMINES_BY_NUCLEOSOMES_IN_THE_MALE_PRONUCLEUS"
[262] "REACTOME_REACTOME_INTERLEUKIN_RECEPTOR_SHC_SIGNALING"
[263] "C8_AIZARANI_LIVER_C10_MVECS_1"
[264] "C8_AIZARANI_LIVER_C29_MVECS_2"
[265] "C8_AIZARANI_LIVER_C32_MVECS_3"
[266] "REACTOME_REACTOME_GROWTH_HORMONE_RECEPTOR_SIGNALING"
[267] "REACTOME_REACTOME_RIP_MEDIATED_NFKB_ACTIVATION_VIA_ZBP1"
[268] "REACTOME_REACTOME_TNF_RECEPTOR_SUPERFAMILY_TNFSF_MEMBERS_MEDIATING_NON_CANONICAL_NF_KB_PATHWAY"
[269] "C8_FAN_EMBRYONIC_CTX_BIG_GROUPS_INHIBITORY"
[270] "C8_HE_LIM_SUN_FETAL_LUNG_C4_ILCP_CELL"
[271] "C8_HE_LIM_SUN_FETAL_LUNG_C4_TH17_CELL"
[272] "REACTOME_REACTOME_ERYTHROCYTES_TAKE_UP_CARBON_DIOXIDE_AND_RELEASE_OXYGEN"
[273] "REACTOME_REACTOME_REGULATION_OF_TP53_ACTIVITY_THROUGH_ASSOCIATION_WITH_CO_FACTORS"
[274] "REACTOME_REACTOME_TP53_REGULATES_TRANSCRIPTION_OF_GENES_INVOLVED_IN_CYTOCHROME_C_RELEASE"
[275] "REACTOME_REACTOME_REGULATION_OF_GENE_EXPRESSION_IN_BETA_CELLS"
[276] "REACTOME_REACTOME_ADP_SIGNALLING_THROUGH_P2Y_PURINOCEPTOR_1"
[277] "REACTOME_REACTOME_COLLAGEN_DEGRADATION"
[278] "REACTOME_REACTOME_GRB2_EVENTS_IN_ERBB2_SIGNALING"
[279] "REACTOME_REACTOME_SHC1_EVENTS_IN_ERBB4_SIGNALING"
[280] "GOCC_GOCC_CALCIUM_CHANNEL_COMPLEX"
[281] "GOCC_GOCC_VOLTAGE_GATED_CALCIUM_CHANNEL_COMPLEX"
[282] "REACTOME_REACTOME_REGULATION_OF_NPAS4_GENE_EXPRESSION"
[283] "REACTOME_REACTOME_ANTIGEN_PRESENTATION_FOLDING_ASSEMBLY_AND_PEPTIDE_LOADING_OF_CLASS_I_MHC"
[284] "C8_BUSSLINGER_GASTRIC_REG3A_POSITIVE_CELLS"
[285] "C8_DESCARTES_MAIN_FETAL_ANTIGEN_PRESENTING_CELLS"
[286] "C8_HE_LIM_SUN_FETAL_LUNG_C2_ADC_1_CELL"
[287] "C8_DESCARTES_FETAL_EYE_CORNEAL_AND_CONJUNCTIVAL_EPITHELIAL_CELLS"
[288] "REACTOME_REACTOME_GENE_AND_PROTEIN_EXPRESSION_BY_JAK_STAT_SIGNALING_AFTER_INTERLEUKIN_12_STIMULATION"
[289] "C8_MENON_FETAL_KIDNEY_10_IMMUNE_CELLS"
[290] "C8_RUBENSTEIN_SKELETAL_MUSCLE_NK_CELLS"
[291] "REACTOME_REACTOME_LONG_TERM_POTENTIATION"
[292] "REACTOME_REACTOME_THE_CRY_PER_KINASE_COMPLEX_REPRESSES_TRANSACTIVATION_BY_THE_BMAL_CLOCK_ARNTL_CLOCK_COMPLEX"
[293] "REACTOME_REACTOME_SIGNALING_BY_HIPPO"
[294] "HALL_HALLMARK_PANCREAS_BETA_CELLS"
[295] "C8_HE_LIM_SUN_FETAL_LUNG_C4_T_ALPHA_BETA_ENTRY_CELL"
[296] "C8_CUI_DEVELOPING_HEART_RIGHT_ATRIAL_CARDIOMYOCYTE"
[297] "REACTOME_REACTOME_SYNTHESIS_OF_SUBSTRATES_IN_N_GLYCAN_BIOSYTHESIS"
[298] "REACTOME_REACTOME_SYNTHESIS_SECRETION_AND_INACTIVATION_OF_GLUCOSE_DEPENDENT_INSULINOTROPIC_POLYPEPTIDE_GIP"
[299] "C8_DESCARTES_FETAL_INTESTINE_CHROMAFFIN_CELLS"
[300] "C8_DESCARTES_FETAL_PANCREAS_ISLET_ENDOCRINE_CELLS"
[301] "C8_MURARO_PANCREAS_BETA_CELL"
[302] "C8_VANGURP_PANCREATIC_BETA_CELL"
[303] "REACTOME_REACTOME_ELEVATION_OF_CYTOSOLIC_CA2_LEVELS"
[304] "GOCC_GOCC_PLATELET_DENSE_GRANULE"
[305] "GOCC_GOCC_PLATELET_DENSE_GRANULE_LUMEN"
[306] "C8_HE_LIM_SUN_FETAL_LUNG_C1_AT1_CELL"
[307] "REACTOME_REACTOME_ACETYLCHOLINE_REGULATES_INSULIN_SECRETION"
[308] "REACTOME_REACTOME_PHOSPHOLIPASE_C_MEDIATED_CASCADE_FGFR2"
[309] "REACTOME_REACTOME_CYTOSOLIC_SULFONATION_OF_SMALL_MOLECULES"
[310] "REACTOME_REACTOME_DEFECTIVE_EXT2_CAUSES_EXOSTOSES_2"
[311] "REACTOME_REACTOME_GLYCOSAMINOGLYCAN_PROTEIN_LINKAGE_REGION_BIOSYNTHESIS"
[312] "REACTOME_REACTOME_UPTAKE_AND_ACTIONS_OF_BACTERIAL_TOXINS"
[313] "REACTOME_REACTOME_HSF1_ACTIVATION"
[314] "REACTOME_REACTOME_MITOCHONDRIAL_UNFOLDED_PROTEIN_RESPONSE_UPRMT"
[315] "C8_DESCARTES_FETAL_LUNG_NEUROENDOCRINE_CELLS"
[316] "C8_HE_LIM_SUN_FETAL_LUNG_C1_GHRL_POS_NEUROENDOCRINE_CELL"
[317] "C8_HE_LIM_SUN_FETAL_LUNG_C1_INTERM_NEUROENDOCRINE_CELL"
[318] "C8_HE_LIM_SUN_FETAL_LUNG_C1_PULMONARY_NEUROENDOCRINE_CELL"
[319] "C8_HE_LIM_SUN_FETAL_LUNG_C1_PULMONARY_NE_PRECURSOR_CELL"
[320] "C8_TRAVAGLINI_LUNG_NEUROENDOCRINE_CELL"
[321] "GOCC_GOCC_CONNEXIN_COMPLEX"
[322] "REACTOME_REACTOME_TRIGLYCERIDE_BIOSYNTHESIS"
[323] "REACTOME_REACTOME_DEVELOPMENTAL_CELL_LINEAGES_OF_THE_EXOCRINE_PANCREAS"
[324] "C8_AIZARANI_LIVER_C24_EPCAM_POS_BILE_DUCT_CELLS_3"
[325] "C8_AIZARANI_LIVER_C39_EPCAM_POS_BILE_DUCT_CELLS_4"
[326] "C8_AIZARANI_LIVER_C4_EPCAM_POS_BILE_DUCT_CELLS_1"
[327] "C8_AIZARANI_LIVER_C7_EPCAM_POS_BILE_DUCT_CELLS_2"
[328] "C8_HE_LIM_SUN_FETAL_LUNG_C2_BASOPHIL_CELL"
[329] "GOCC_GOCC_NODE_OF_RANVIER"
[330] "REACTOME_REACTOME_NOTCH3_ACTIVATION_AND_TRANSMISSION_OF_SIGNAL_TO_THE_NUCLEUS"
[331] "GOCC_GOCC_SCHMIDT_LANTERMAN_INCISURE"
[332] "REACTOME_REACTOME_COLLAGEN_FORMATION"
[333] "REACTOME_REACTOME_REGULATION_BY_C_FLIP"
[334] "C8_AIZARANI_LIVER_C33_STELLATE_CELLS_2"
[335] "C8_HE_LIM_SUN_FETAL_LUNG_C0_VASCULAR_SMC_1_CELL"
[336] "REACTOME_REACTOME_GLYCOSPHINGOLIPID_METABOLISM"
[337] "C8_AIZARANI_LIVER_C25_KUPFFER_CELLS_4"
[338] "C8_AIZARANI_LIVER_C2_KUPFFER_CELLS_1"
[339] "C8_BUSSLINGER_ESOPHAGEAL_DENDRITIC_CELLS"
[340] "REACTOME_REACTOME_REGULATION_OF_MECP2_EXPRESSION_AND_ACTIVITY"
[341] "REACTOME_REACTOME_THE_CANONICAL_RETINOID_CYCLE_IN_RODS_TWILIGHT_VISION"
[342] "REACTOME_REACTOME_GLYCOGEN_METABOLISM"
[343] "C8_HE_LIM_SUN_FETAL_LUNG_C3_VENOUS_ENDOTHELIAL_CELL"
[344] "C8_JONES_OVARY_MAST_CELL"
[345] "REACTOME_REACTOME_ANTIGEN_ACTIVATES_B_CELL_RECEPTOR_BCR_LEADING_TO_GENERATION_OF_SECOND_MESSENGERS"
[346] "REACTOME_REACTOME_FCERI_MEDIATED_CA_2_MOBILIZATION"
[347] "C8_HE_LIM_SUN_FETAL_LUNG_C4_NKT2_CELL"
[348] "GOCC_GOCC_OTHER_ORGANISM_PART"
[349] "REACTOME_REACTOME_REVERSIBLE_HYDRATION_OF_CARBON_DIOXIDE"
[350] "REACTOME_REACTOME_IRE1ALPHA_ACTIVATES_CHAPERONES"
[351] "GOCC_GOCC_GOLGI_MEDIAL_CISTERNA"
[352] "C8_FAN_EMBRYONIC_CTX_EX_2_EXCITATORY_NEURON"