💡 **Environment:** `clamp-analyses`

# Description

Reads the drug-disease prediction HDF5 files from the notebooks 06–09 (gene-based and module-based) and computes final performance measures (AUROC, average precision) against the PharmacotherapyDB gold standard.

Aggregation:
1. Group by (trait, drug, method, tissue) and average ranks across thresholds.
2. Group by (trait, drug, method) and take the max across tissues.

# Modules loading

In [1]:
%load_ext autoreload
%autoreload 2

In [2]:
from pathlib import Path
from collections import defaultdict
from IPython.display import display

import numpy as np
import pandas as pd
from tqdm import tqdm
from sklearn.metrics import roc_auc_score, average_precision_score

from pyprojroot import here

# Settings

In [ ]:
N_TISSUES = 49
N_THRESHOLDS = 5

METHOD_RENAME = {
    'Gene-based':             'gene_based',
    'Module-based (ARCHS4)':  'module_based_archs4',
    'Module-based':           'module_based_archs4',
    'Module-based (GTEx)':    'module_based_gtex',
    'Module-based (recount2)':'module_based_recount2',
}

METHOD_THRESHOLDS = {
    'gene_based': [-1.0, 50.0, 100.0, 250.0, 500.0],
    'module_based_archs4': [-1.0, 5.0, 10.0, 25.0, 50.0],
    'module_based_gtex': [-1.0, 5.0, 10.0, 25.0, 50.0],
    'module_based_recount2': [-1.0, 5.0, 10.0, 25.0, 50.0],
}
EXPECTED_METHODS = tuple(METHOD_THRESHOLDS)
N_PREDICTION_FILES_TOTAL = N_TISSUES * sum(len(v) for v in METHOD_THRESHOLDS.values())

In [ ]:
DATA_DIR = here('data/drug_disease_associations')
display(DATA_DIR)
assert DATA_DIR.exists()

# Collect prediction HDF5 files from all 4 prediction notebooks
PREDICTIONS_DIRS = [
    here('output/03_model_biology/00_archs4/02_drug_disease_associations/06_prediction_single_gene_based') / 'lincs' / 'predictions' / 'dotprod_neg',
    here('output/03_model_biology/00_archs4/02_drug_disease_associations/07_prediction_module_based_archs4') / 'lincs' / 'predictions' / 'dotprod_neg',
    here('output/03_model_biology/00_archs4/02_drug_disease_associations/08_prediction_module_based_gtex') / 'lincs' / 'predictions' / 'dotprod_neg',
    here('output/03_model_biology/00_archs4/02_drug_disease_associations/09_prediction_module_based_recount2') / 'lincs' / 'predictions' / 'dotprod_neg',
]
for d in PREDICTIONS_DIRS:
    display(d)
    assert d.exists(), d

OUTPUT_DIR = here('output/03_model_biology/00_archs4/02_drug_disease_associations/10_prediction_performance') / 'lincs'
OUTPUT_DIR.mkdir(parents=True, exist_ok=True)
(OUTPUT_DIR / 'predictions').mkdir(parents=True, exist_ok=True)
display(OUTPUT_DIR)

PosixPath('/home/msubirana/Documents/pivlab/clamp-analyses/data/drug_disease_associations')

PosixPath('/home/msubirana/Documents/pivlab/clamp-analyses/output/03_model_biology/00_archs4/02_drug_disease_associations/06_prediction_single_gene_based/lincs/predictions/dotprod_neg')

PosixPath('/home/msubirana/Documents/pivlab/clamp-analyses/output/03_model_biology/00_archs4/02_drug_disease_associations/07_prediction_module_based_archs4/lincs/predictions/dotprod_neg')

PosixPath('/home/msubirana/Documents/pivlab/clamp-analyses/output/03_model_biology/00_archs4/02_drug_disease_associations/08_prediction_module_based_gtex/lincs/predictions/dotprod_neg')

PosixPath('/home/msubirana/Documents/pivlab/clamp-analyses/output/03_model_biology/00_archs4/02_drug_disease_associations/09_prediction_module_based_recount2/lincs/predictions/dotprod_neg')

PosixPath('/home/msubirana/Documents/pivlab/clamp-analyses/output/03_model_biology/00_archs4/02_drug_disease_associations/10_prediction_performance/lincs')

# Load PharmacotherapyDB gold standard

In [5]:
gold_standard = pd.read_pickle(DATA_DIR / 'gold_standard.pkl')
display(gold_standard.shape)
display(gold_standard.head())
display(gold_standard['true_class'].value_counts())

(998, 3)

        trait     drug  true_class
0  DOID:10652  DB00843           1
1  DOID:10652  DB00674           1
2  DOID:10652  DB01043           1
3  DOID:10652  DB00989           1
4  DOID:10652  DB00810           0

true_class
1    755
0    243
Name: count, dtype: int64

# Load drug-disease predictions

In [ ]:
current_prediction_files = []
for d in PREDICTIONS_DIRS:
    current_prediction_files.extend(sorted(d.glob('*.h5')))
current_prediction_files.sort()
display(len(current_prediction_files))

980

In [7]:
current_prediction_files[:5]

[PosixPath('/home/msubirana/Documents/pivlab/clamp-analyses/output/03_model_biology/00_archs4/02_drug_disease_associations/06_prediction_single_gene_based/lincs/predictions/dotprod_neg/spredixcan-mashr-zscores-Adipose_Subcutaneous-data-all_genes-prediction_scores.h5'),
 PosixPath('/home/msubirana/Documents/pivlab/clamp-analyses/output/03_model_biology/00_archs4/02_drug_disease_associations/06_prediction_single_gene_based/lincs/predictions/dotprod_neg/spredixcan-mashr-zscores-Adipose_Subcutaneous-data-top_100_genes-prediction_scores.h5'),
 PosixPath('/home/msubirana/Documents/pivlab/clamp-analyses/output/03_model_biology/00_archs4/02_drug_disease_associations/06_prediction_single_gene_based/lincs/predictions/dotprod_neg/spredixcan-mashr-zscores-Adipose_Subcutaneous-data-top_250_genes-prediction_scores.h5'),
 PosixPath('/home/msubirana/Documents/pivlab/clamp-analyses/output/03_model_biology/00_archs4/02_drug_disease_associations/06_prediction_single_gene_based/lincs/predictions/dotprod_neg/spredixcan-mashr-zscores-Adipose_Subcutaneous-data-top_500_genes-prediction_scores.h5'),
 PosixPath('/home/msubirana/Documents/pivlab/clamp-analyses/output/03_model_biology/00_archs4/02_drug_disease_associations/06_prediction_single_gene_based/lincs/predictions/dotprod_neg/spredixcan-mashr-zscores-Adipose_Subcutaneous-data-top_50_genes-prediction_scores.h5')]

In [ ]:
def _get_tissue(data_value):
    """
    Extracts tissue name from the metadata 'data' field.
    Handles raw data and dataset-specific projected suffixes.
    """
    prefix = 'spredixcan-mashr-zscores-'
    assert data_value.startswith(prefix), data_value
    tissue = data_value[len(prefix):]

    for suffix in (
        '-projection-archs4',
        '-projection-gtex',
        '-projection-recount2',
        '-projection',
        '-data',
    ):
        if tissue.endswith(suffix):
            return tissue[:-len(suffix)]

    raise ValueError(f'Cannot extract tissue from metadata data value: {data_value}')

In [ ]:
# Load all prediction files, rank scores, merge with gold standard
predictions = []
skipped_files = []

for f in tqdm(current_prediction_files, ncols=100):
    metadata = pd.read_hdf(f, key='metadata')
    method_name = METHOD_RENAME.get(metadata['method'].values[0], metadata['method'].values[0])
    if method_name not in METHOD_THRESHOLDS:
        skipped_files.append((f.name, method_name))
        continue

    # Load DOID-mapped predictions and rank within the full DOID distribution
    prediction_data = pd.read_hdf(f, key='prediction')
    prediction_data['score'] = prediction_data['score'].rank()

    # Filter to gold-standard pairs
    prediction_data = pd.merge(
        prediction_data, gold_standard, on=['trait', 'drug'], how='inner'
    )
    prediction_data['trait'] = prediction_data['trait'].astype('category')
    prediction_data['drug'] = prediction_data['drug'].astype('category')

    prediction_data = prediction_data.assign(method=method_name)
    prediction_data['method'] = pd.Categorical(
        prediction_data['method'], categories=EXPECTED_METHODS, ordered=True
    )

    prediction_data = prediction_data.assign(n_top_genes=metadata['n_top_genes'].values[0])

    data_value = metadata['data'].values[0]
    prediction_data = prediction_data.assign(data=data_value)
    prediction_data['data'] = prediction_data['data'].astype('category')

    # Extract tissue name from data field
    prediction_data = prediction_data.assign(tissue=_get_tissue(data_value))

    predictions.append(prediction_data)

display(f'Skipped files: {len(skipped_files)}')
if skipped_files:
    display(skipped_files[:10])

  0%|                                                                       | 0/980 [00:00<?, ?it/s]

  0%|                                                               | 1/980 [00:00<03:01,  5.39it/s]

  0%|▏                                                              | 2/980 [00:00<02:43,  5.98it/s]

  0%|▏                                                              | 3/980 [00:00<02:38,  6.17it/s]

  0%|▎                                                              | 4/980 [00:00<02:35,  6.29it/s]

  1%|▎                                                              | 5/980 [00:00<02:32,  6.39it/s]

  1%|▍                                                              | 6/980 [00:00<02:30,  6.46it/s]

  1%|▍                                                              | 7/980 [00:01<02:30,  6.45it/s]

  1%|▌                                                              | 8/980 [00:01<02:29,  6.49it/s]

  1%|▌                                                              | 9/980 [00:01<02:28,  6.55it/s]

  1%|▋                                                             | 10/980 [00:01<02:28,  6.53it/s]

  1%|▋                                                             | 11/980 [00:01<02:27,  6.57it/s]

  1%|▊                                                             | 12/980 [00:01<02:27,  6.58it/s]

  1%|▊                                                             | 13/980 [00:02<02:29,  6.47it/s]

  1%|▉                                                             | 14/980 [00:02<02:29,  6.45it/s]

  2%|▉                                                             | 15/980 [00:02<02:28,  6.48it/s]

  2%|█                                                             | 16/980 [00:02<02:28,  6.50it/s]

  2%|█                                                             | 17/980 [00:02<02:29,  6.46it/s]

  2%|█▏                                                            | 18/980 [00:02<02:29,  6.45it/s]

  2%|█▏                                                            | 19/980 [00:02<02:27,  6.50it/s]

  2%|█▎                                                            | 20/980 [00:03<02:32,  6.32it/s]

  2%|█▎                                                            | 21/980 [00:03<02:30,  6.38it/s]

  2%|█▍                                                            | 22/980 [00:03<02:28,  6.45it/s]

  2%|█▍                                                            | 23/980 [00:03<02:27,  6.49it/s]

  2%|█▌                                                            | 24/980 [00:03<02:27,  6.48it/s]

  3%|█▌                                                            | 25/980 [00:03<02:26,  6.50it/s]

  3%|█▋                                                            | 26/980 [00:04<02:25,  6.54it/s]

  3%|█▋                                                            | 27/980 [00:04<02:26,  6.51it/s]

  3%|█▊                                                            | 28/980 [00:04<02:25,  6.54it/s]

  3%|█▊                                                            | 29/980 [00:04<02:25,  6.54it/s]

  3%|█▉                                                            | 30/980 [00:04<02:24,  6.56it/s]

  3%|█▉                                                            | 31/980 [00:04<02:24,  6.57it/s]

  3%|██                                                            | 32/980 [00:04<02:24,  6.57it/s]

  3%|██                                                            | 33/980 [00:05<02:24,  6.55it/s]

  3%|██▏                                                           | 34/980 [00:05<02:24,  6.53it/s]

  4%|██▏                                                           | 35/980 [00:05<02:28,  6.38it/s]

  4%|██▎                                                           | 36/980 [00:05<02:26,  6.44it/s]

  4%|██▎                                                           | 37/980 [00:05<02:26,  6.42it/s]

  4%|██▍                                                           | 38/980 [00:05<02:30,  6.28it/s]

  4%|██▍                                                           | 39/980 [00:06<02:34,  6.09it/s]

  4%|██▌                                                           | 40/980 [00:06<02:32,  6.15it/s]

  4%|██▌                                                           | 41/980 [00:06<02:29,  6.26it/s]

  4%|██▋                                                           | 42/980 [00:06<02:27,  6.35it/s]

  4%|██▋                                                           | 43/980 [00:06<02:37,  5.95it/s]

  4%|██▊                                                           | 44/980 [00:06<02:32,  6.12it/s]

  5%|██▊                                                           | 45/980 [00:07<02:29,  6.26it/s]

  5%|██▉                                                           | 46/980 [00:07<02:27,  6.31it/s]

  5%|██▉                                                           | 47/980 [00:07<02:26,  6.38it/s]

  5%|███                                                           | 48/980 [00:07<02:24,  6.43it/s]

  5%|███                                                           | 49/980 [00:07<02:23,  6.47it/s]

  5%|███▏                                                          | 50/980 [00:07<02:22,  6.55it/s]

  5%|███▏                                                          | 51/980 [00:07<02:22,  6.54it/s]

  5%|███▎                                                          | 52/980 [00:08<02:21,  6.57it/s]

  5%|███▎                                                          | 53/980 [00:08<02:20,  6.58it/s]

  6%|███▍                                                          | 54/980 [00:08<02:20,  6.59it/s]

  6%|███▍                                                          | 55/980 [00:08<02:22,  6.47it/s]

  6%|███▌                                                          | 56/980 [00:08<02:23,  6.45it/s]

  6%|███▌                                                          | 57/980 [00:08<02:21,  6.50it/s]

  6%|███▋                                                          | 58/980 [00:09<02:20,  6.55it/s]

  6%|███▋                                                          | 59/980 [00:09<02:20,  6.54it/s]

  6%|███▊                                                          | 60/980 [00:09<02:20,  6.55it/s]

  6%|███▊                                                          | 61/980 [00:09<02:20,  6.53it/s]

  6%|███▉                                                          | 62/980 [00:09<02:20,  6.52it/s]

  6%|███▉                                                          | 63/980 [00:09<02:20,  6.53it/s]

  7%|████                                                          | 64/980 [00:09<02:21,  6.47it/s]

  7%|████                                                          | 65/980 [00:10<02:23,  6.37it/s]

  7%|████▏                                                         | 66/980 [00:10<02:22,  6.41it/s]

  7%|████▏                                                         | 67/980 [00:10<02:21,  6.47it/s]

  7%|████▎                                                         | 68/980 [00:10<02:20,  6.51it/s]

  7%|████▎                                                         | 69/980 [00:10<02:19,  6.54it/s]

  7%|████▍                                                         | 70/980 [00:10<02:18,  6.56it/s]

  7%|████▍                                                         | 71/980 [00:11<02:19,  6.51it/s]

  7%|████▌                                                         | 72/980 [00:11<02:22,  6.35it/s]

  7%|████▌                                                         | 73/980 [00:11<02:21,  6.42it/s]

  8%|████▋                                                         | 74/980 [00:11<02:19,  6.48it/s]

  8%|████▋                                                         | 75/980 [00:11<02:20,  6.44it/s]

  8%|████▊                                                         | 76/980 [00:11<02:19,  6.47it/s]

  8%|████▊                                                         | 77/980 [00:11<02:19,  6.47it/s]

  8%|████▉                                                         | 78/980 [00:12<02:19,  6.47it/s]

  8%|████▉                                                         | 79/980 [00:12<02:18,  6.50it/s]

  8%|█████                                                         | 80/980 [00:12<02:17,  6.53it/s]

  8%|█████                                                         | 81/980 [00:12<02:18,  6.50it/s]

  8%|█████▏                                                        | 82/980 [00:12<02:19,  6.44it/s]

  8%|█████▎                                                        | 83/980 [00:12<02:20,  6.40it/s]

  9%|█████▎                                                        | 84/980 [00:13<02:21,  6.33it/s]

  9%|█████▍                                                        | 85/980 [00:13<02:21,  6.31it/s]

  9%|█████▍                                                        | 86/980 [00:13<02:24,  6.20it/s]

  9%|█████▌                                                        | 87/980 [00:13<02:23,  6.23it/s]

  9%|█████▌                                                        | 88/980 [00:13<02:22,  6.24it/s]

  9%|█████▋                                                        | 89/980 [00:13<02:22,  6.26it/s]

  9%|█████▋                                                        | 90/980 [00:14<02:22,  6.26it/s]

  9%|█████▊                                                        | 91/980 [00:14<02:22,  6.25it/s]

  9%|█████▊                                                        | 92/980 [00:14<02:22,  6.25it/s]

  9%|█████▉                                                        | 93/980 [00:14<02:21,  6.26it/s]

 10%|█████▉                                                        | 94/980 [00:14<02:21,  6.28it/s]

 10%|██████                                                        | 95/980 [00:14<02:20,  6.29it/s]

 10%|██████                                                        | 96/980 [00:14<02:21,  6.26it/s]

 10%|██████▏                                                       | 97/980 [00:15<02:20,  6.26it/s]

 10%|██████▏                                                       | 98/980 [00:15<02:20,  6.28it/s]

 10%|██████▎                                                       | 99/980 [00:15<02:21,  6.23it/s]

 10%|██████▏                                                      | 100/980 [00:15<02:22,  6.19it/s]

 10%|██████▎                                                      | 101/980 [00:15<02:21,  6.23it/s]

 10%|██████▎                                                      | 102/980 [00:15<02:20,  6.23it/s]

 11%|██████▍                                                      | 103/980 [00:16<02:22,  6.17it/s]

 11%|██████▍                                                      | 104/980 [00:16<02:21,  6.20it/s]

 11%|██████▌                                                      | 105/980 [00:16<02:20,  6.24it/s]

 11%|██████▌                                                      | 106/980 [00:16<02:19,  6.26it/s]

 11%|██████▋                                                      | 107/980 [00:16<02:18,  6.29it/s]

 11%|██████▋                                                      | 108/980 [00:16<02:18,  6.31it/s]

 11%|██████▊                                                      | 109/980 [00:17<02:18,  6.29it/s]

 11%|██████▊                                                      | 110/980 [00:17<02:20,  6.18it/s]

 11%|██████▉                                                      | 111/980 [00:17<02:28,  5.87it/s]

 11%|██████▉                                                      | 112/980 [00:17<02:25,  5.95it/s]

 12%|███████                                                      | 113/980 [00:17<02:26,  5.91it/s]

 12%|███████                                                      | 114/980 [00:17<02:23,  6.02it/s]

 12%|███████▏                                                     | 115/980 [00:18<02:22,  6.06it/s]

 12%|███████▏                                                     | 116/980 [00:18<02:20,  6.13it/s]

 12%|███████▎                                                     | 117/980 [00:18<02:19,  6.18it/s]

 12%|███████▎                                                     | 118/980 [00:18<02:18,  6.22it/s]

 12%|███████▍                                                     | 119/980 [00:18<02:17,  6.25it/s]

 12%|███████▍                                                     | 120/980 [00:18<02:17,  6.25it/s]

 12%|███████▌                                                     | 121/980 [00:19<02:17,  6.27it/s]

 12%|███████▌                                                     | 122/980 [00:19<02:16,  6.28it/s]

 13%|███████▋                                                     | 123/980 [00:19<02:16,  6.28it/s]

 13%|███████▋                                                     | 124/980 [00:19<02:15,  6.30it/s]

 13%|███████▊                                                     | 125/980 [00:19<02:15,  6.32it/s]

 13%|███████▊                                                     | 126/980 [00:19<02:15,  6.31it/s]

 13%|███████▉                                                     | 127/980 [00:19<02:15,  6.30it/s]

 13%|███████▉                                                     | 128/980 [00:20<02:15,  6.29it/s]

 13%|████████                                                     | 129/980 [00:20<02:15,  6.29it/s]

 13%|████████                                                     | 130/980 [00:20<02:15,  6.29it/s]

 13%|████████▏                                                    | 131/980 [00:20<02:14,  6.33it/s]

 13%|████████▏                                                    | 132/980 [00:20<02:14,  6.30it/s]

 14%|████████▎                                                    | 133/980 [00:20<02:14,  6.31it/s]

 14%|████████▎                                                    | 134/980 [00:21<02:14,  6.31it/s]

 14%|████████▍                                                    | 135/980 [00:21<02:13,  6.33it/s]

 14%|████████▍                                                    | 136/980 [00:21<02:13,  6.33it/s]

 14%|████████▌                                                    | 137/980 [00:21<02:13,  6.33it/s]

 14%|████████▌                                                    | 138/980 [00:21<02:12,  6.36it/s]

 14%|████████▋                                                    | 139/980 [00:21<02:13,  6.32it/s]

 14%|████████▋                                                    | 140/980 [00:22<02:12,  6.32it/s]

 14%|████████▊                                                    | 141/980 [00:22<02:12,  6.32it/s]

 14%|████████▊                                                    | 142/980 [00:22<02:12,  6.32it/s]

 15%|████████▉                                                    | 143/980 [00:22<02:12,  6.33it/s]

 15%|████████▉                                                    | 144/980 [00:22<02:11,  6.35it/s]

 15%|█████████                                                    | 145/980 [00:22<02:10,  6.42it/s]

 15%|█████████                                                    | 146/980 [00:22<02:08,  6.47it/s]

 15%|█████████▏                                                   | 147/980 [00:23<02:07,  6.52it/s]

 15%|█████████▏                                                   | 148/980 [00:23<02:06,  6.55it/s]

 15%|█████████▎                                                   | 149/980 [00:23<02:06,  6.57it/s]

 15%|█████████▎                                                   | 150/980 [00:23<02:05,  6.61it/s]

 15%|█████████▍                                                   | 151/980 [00:23<02:05,  6.62it/s]

 16%|█████████▍                                                   | 152/980 [00:23<02:05,  6.61it/s]

 16%|█████████▌                                                   | 153/980 [00:24<02:05,  6.61it/s]

 16%|█████████▌                                                   | 154/980 [00:24<02:04,  6.62it/s]

 16%|█████████▋                                                   | 155/980 [00:24<02:04,  6.62it/s]

 16%|█████████▋                                                   | 156/980 [00:24<02:04,  6.62it/s]

 16%|█████████▊                                                   | 157/980 [00:24<02:03,  6.65it/s]

 16%|█████████▊                                                   | 158/980 [00:24<02:03,  6.66it/s]

 16%|█████████▉                                                   | 159/980 [00:24<02:04,  6.62it/s]

 16%|█████████▉                                                   | 160/980 [00:25<02:03,  6.63it/s]

 16%|██████████                                                   | 161/980 [00:25<02:03,  6.64it/s]

 17%|██████████                                                   | 162/980 [00:25<02:03,  6.64it/s]

 17%|██████████▏                                                  | 163/980 [00:25<02:03,  6.63it/s]

 17%|██████████▏                                                  | 164/980 [00:25<02:02,  6.65it/s]

 17%|██████████▎                                                  | 165/980 [00:25<02:02,  6.64it/s]

 17%|██████████▎                                                  | 166/980 [00:25<02:03,  6.62it/s]

 17%|██████████▍                                                  | 167/980 [00:26<02:02,  6.62it/s]

 17%|██████████▍                                                  | 168/980 [00:26<02:02,  6.62it/s]

 17%|██████████▌                                                  | 169/980 [00:26<02:02,  6.63it/s]

 17%|██████████▌                                                  | 170/980 [00:26<02:01,  6.65it/s]

 17%|██████████▋                                                  | 171/980 [00:26<02:01,  6.66it/s]

 18%|██████████▋                                                  | 172/980 [00:26<02:01,  6.64it/s]

 18%|██████████▊                                                  | 173/980 [00:27<02:01,  6.66it/s]

 18%|██████████▊                                                  | 174/980 [00:27<02:01,  6.64it/s]

 18%|██████████▉                                                  | 175/980 [00:27<02:01,  6.63it/s]

 18%|██████████▉                                                  | 176/980 [00:27<02:01,  6.63it/s]

 18%|███████████                                                  | 177/980 [00:27<02:01,  6.59it/s]

 18%|███████████                                                  | 178/980 [00:27<02:02,  6.57it/s]

 18%|███████████▏                                                 | 179/980 [00:27<02:02,  6.54it/s]

 18%|███████████▏                                                 | 180/980 [00:28<02:03,  6.47it/s]

 18%|███████████▎                                                 | 181/980 [00:28<02:04,  6.43it/s]

 19%|███████████▎                                                 | 182/980 [00:28<02:04,  6.39it/s]

 19%|███████████▍                                                 | 183/980 [00:28<02:04,  6.40it/s]

 19%|███████████▍                                                 | 184/980 [00:28<02:04,  6.38it/s]

 19%|███████████▌                                                 | 185/980 [00:28<02:04,  6.38it/s]

 19%|███████████▌                                                 | 186/980 [00:29<02:04,  6.37it/s]

 19%|███████████▋                                                 | 187/980 [00:29<02:04,  6.36it/s]

 19%|███████████▋                                                 | 188/980 [00:29<02:04,  6.34it/s]

 19%|███████████▊                                                 | 189/980 [00:29<02:04,  6.34it/s]

 19%|███████████▊                                                 | 190/980 [00:29<02:04,  6.34it/s]

 19%|███████████▉                                                 | 191/980 [00:29<02:04,  6.33it/s]

 20%|███████████▉                                                 | 192/980 [00:29<02:04,  6.32it/s]

 20%|████████████                                                 | 193/980 [00:30<02:04,  6.33it/s]

 20%|████████████                                                 | 194/980 [00:30<02:04,  6.33it/s]

 20%|████████████▏                                                | 195/980 [00:30<02:04,  6.33it/s]

 20%|████████████▏                                                | 196/980 [00:30<02:03,  6.32it/s]

 20%|████████████▎                                                | 197/980 [00:30<02:03,  6.36it/s]

 20%|████████████▎                                                | 198/980 [00:30<02:02,  6.40it/s]

 20%|████████████▍                                                | 199/980 [00:31<02:02,  6.37it/s]

 20%|████████████▍                                                | 200/980 [00:31<02:02,  6.35it/s]

 21%|████████████▌                                                | 201/980 [00:31<02:02,  6.34it/s]

 21%|████████████▌                                                | 202/980 [00:31<02:02,  6.35it/s]

 21%|████████████▋                                                | 203/980 [00:31<02:02,  6.34it/s]

 21%|████████████▋                                                | 204/980 [00:31<02:02,  6.32it/s]

 21%|████████████▊                                                | 205/980 [00:32<02:02,  6.31it/s]

 21%|████████████▊                                                | 206/980 [00:32<02:02,  6.32it/s]

 21%|████████████▉                                                | 207/980 [00:32<02:02,  6.32it/s]

 21%|████████████▉                                                | 208/980 [00:32<02:01,  6.33it/s]

 21%|█████████████                                                | 209/980 [00:32<02:01,  6.33it/s]

 21%|█████████████                                                | 210/980 [00:32<02:01,  6.31it/s]

 22%|█████████████▏                                               | 211/980 [00:32<02:01,  6.35it/s]

 22%|█████████████▏                                               | 212/980 [00:33<01:59,  6.42it/s]

 22%|█████████████▎                                               | 213/980 [00:33<01:58,  6.48it/s]

 22%|█████████████▎                                               | 214/980 [00:33<01:57,  6.52it/s]

 22%|█████████████▍                                               | 215/980 [00:33<01:56,  6.56it/s]

 22%|█████████████▍                                               | 216/980 [00:33<01:56,  6.57it/s]

 22%|█████████████▌                                               | 217/980 [00:33<01:56,  6.58it/s]

 22%|█████████████▌                                               | 218/980 [00:34<01:55,  6.59it/s]

 22%|█████████████▋                                               | 219/980 [00:34<01:55,  6.60it/s]

 22%|█████████████▋                                               | 220/980 [00:34<01:55,  6.60it/s]

 23%|█████████████▊                                               | 221/980 [00:34<01:54,  6.62it/s]

 23%|█████████████▊                                               | 222/980 [00:34<01:54,  6.64it/s]

 23%|█████████████▉                                               | 223/980 [00:34<01:55,  6.53it/s]

 23%|█████████████▉                                               | 224/980 [00:34<01:57,  6.46it/s]

 23%|██████████████                                               | 225/980 [00:35<01:56,  6.50it/s]

 23%|██████████████                                               | 226/980 [00:35<01:55,  6.53it/s]

 23%|██████████████▏                                              | 227/980 [00:35<01:55,  6.55it/s]

 23%|██████████████▏                                              | 228/980 [00:35<01:54,  6.57it/s]

 23%|██████████████▎                                              | 229/980 [00:35<01:54,  6.57it/s]

 23%|██████████████▎                                              | 230/980 [00:35<01:54,  6.57it/s]

 24%|██████████████▍                                              | 231/980 [00:36<01:53,  6.59it/s]

 24%|██████████████▍                                              | 232/980 [00:36<01:53,  6.59it/s]

 24%|██████████████▌                                              | 233/980 [00:36<01:53,  6.55it/s]

 24%|██████████████▌                                              | 234/980 [00:36<01:54,  6.52it/s]

 24%|██████████████▋                                              | 235/980 [00:36<01:53,  6.55it/s]

 24%|██████████████▋                                              | 236/980 [00:36<01:53,  6.58it/s]

 24%|██████████████▊                                              | 237/980 [00:36<01:52,  6.59it/s]

 24%|██████████████▊                                              | 238/980 [00:37<01:52,  6.61it/s]

 24%|██████████████▉                                              | 239/980 [00:37<01:51,  6.62it/s]

 24%|██████████████▉                                              | 240/980 [00:37<01:51,  6.61it/s]

 25%|███████████████                                              | 241/980 [00:37<01:52,  6.60it/s]

 25%|███████████████                                              | 242/980 [00:37<01:53,  6.52it/s]

 25%|███████████████▏                                             | 243/980 [00:37<01:54,  6.45it/s]

 25%|███████████████▏                                             | 244/980 [00:38<01:54,  6.42it/s]

 25%|███████████████▎                                             | 245/980 [00:38<01:55,  6.38it/s]

 25%|███████████████▎                                             | 246/980 [00:38<01:55,  6.35it/s]

 25%|███████████████▎                                             | 247/980 [00:38<01:56,  6.32it/s]

 25%|███████████████▍                                             | 248/980 [00:38<01:55,  6.31it/s]

 25%|███████████████▍                                             | 249/980 [00:38<01:55,  6.31it/s]

 26%|███████████████▌                                             | 250/980 [00:38<01:55,  6.31it/s]

 26%|███████████████▌                                             | 251/980 [00:39<01:55,  6.31it/s]

 26%|███████████████▋                                             | 252/980 [00:39<01:55,  6.29it/s]

 26%|███████████████▋                                             | 253/980 [00:39<01:55,  6.30it/s]

 26%|███████████████▊                                             | 254/980 [00:39<01:54,  6.32it/s]

 26%|███████████████▊                                             | 255/980 [00:39<01:54,  6.32it/s]

 26%|███████████████▉                                             | 256/980 [00:39<01:54,  6.31it/s]

 26%|███████████████▉                                             | 257/980 [00:40<01:54,  6.31it/s]

 26%|████████████████                                             | 258/980 [00:40<01:54,  6.29it/s]

 26%|████████████████                                             | 259/980 [00:40<01:54,  6.27it/s]

 27%|████████████████▏                                            | 260/980 [00:40<01:54,  6.27it/s]

 27%|████████████████▏                                            | 261/980 [00:40<01:54,  6.27it/s]

 27%|████████████████▎                                            | 262/980 [00:40<01:54,  6.28it/s]

 27%|████████████████▎                                            | 263/980 [00:41<01:54,  6.25it/s]

 27%|████████████████▍                                            | 264/980 [00:41<01:54,  6.26it/s]

 27%|████████████████▍                                            | 265/980 [00:41<01:54,  6.26it/s]

 27%|████████████████▌                                            | 266/980 [00:41<01:53,  6.29it/s]

 27%|████████████████▌                                            | 267/980 [00:41<01:53,  6.31it/s]

 27%|████████████████▋                                            | 268/980 [00:41<01:53,  6.26it/s]

 27%|████████████████▋                                            | 269/980 [00:42<01:53,  6.27it/s]

 28%|████████████████▊                                            | 270/980 [00:42<01:53,  6.28it/s]

 28%|████████████████▊                                            | 271/980 [00:42<01:53,  6.25it/s]

 28%|████████████████▉                                            | 272/980 [00:42<01:53,  6.24it/s]

 28%|████████████████▉                                            | 273/980 [00:42<01:52,  6.27it/s]

 28%|█████████████████                                            | 274/980 [00:42<01:53,  6.25it/s]

 28%|█████████████████                                            | 275/980 [00:42<01:53,  6.19it/s]

 28%|█████████████████▏                                           | 276/980 [00:43<01:55,  6.12it/s]

 28%|█████████████████▏                                           | 277/980 [00:43<01:55,  6.11it/s]

 28%|█████████████████▎                                           | 278/980 [00:43<01:55,  6.07it/s]

 28%|█████████████████▎                                           | 279/980 [00:43<01:55,  6.08it/s]

 29%|█████████████████▍                                           | 280/980 [00:43<01:56,  6.02it/s]

 29%|█████████████████▍                                           | 281/980 [00:43<01:54,  6.09it/s]

 29%|█████████████████▌                                           | 282/980 [00:44<01:54,  6.10it/s]

 29%|█████████████████▌                                           | 283/980 [00:44<01:54,  6.10it/s]

 29%|█████████████████▋                                           | 284/980 [00:44<01:54,  6.10it/s]

 29%|█████████████████▋                                           | 285/980 [00:44<01:52,  6.16it/s]

 29%|█████████████████▊                                           | 286/980 [00:44<01:53,  6.11it/s]

 29%|█████████████████▊                                           | 287/980 [00:44<01:57,  5.90it/s]

 29%|█████████████████▉                                           | 288/980 [00:45<01:57,  5.91it/s]

 29%|█████████████████▉                                           | 289/980 [00:45<01:55,  5.99it/s]

 30%|██████████████████                                           | 290/980 [00:45<01:54,  6.03it/s]

 30%|██████████████████                                           | 291/980 [00:45<01:53,  6.07it/s]

 30%|██████████████████▏                                          | 292/980 [00:45<01:52,  6.13it/s]

 30%|██████████████████▏                                          | 293/980 [00:45<01:52,  6.13it/s]

 30%|██████████████████▎                                          | 294/980 [00:46<01:51,  6.13it/s]

 30%|██████████████████▎                                          | 295/980 [00:46<01:51,  6.16it/s]

 30%|██████████████████▍                                          | 296/980 [00:46<01:50,  6.20it/s]

 30%|██████████████████▍                                          | 297/980 [00:46<01:50,  6.21it/s]

 30%|██████████████████▌                                          | 298/980 [00:46<01:49,  6.23it/s]

 31%|██████████████████▌                                          | 299/980 [00:46<01:49,  6.23it/s]

 31%|██████████████████▋                                          | 300/980 [00:47<01:48,  6.28it/s]

 31%|██████████████████▋                                          | 301/980 [00:47<01:48,  6.24it/s]

 31%|██████████████████▊                                          | 302/980 [00:47<01:48,  6.26it/s]

 31%|██████████████████▊                                          | 303/980 [00:47<01:48,  6.24it/s]

 31%|██████████████████▉                                          | 304/980 [00:47<01:48,  6.24it/s]

 31%|██████████████████▉                                          | 305/980 [00:47<01:48,  6.25it/s]

 31%|███████████████████                                          | 306/980 [00:48<01:47,  6.28it/s]

 31%|███████████████████                                          | 307/980 [00:48<01:47,  6.27it/s]

 31%|███████████████████▏                                         | 308/980 [00:48<01:47,  6.26it/s]

 32%|███████████████████▏                                         | 309/980 [00:48<01:45,  6.36it/s]

 32%|███████████████████▎                                         | 310/980 [00:48<01:45,  6.34it/s]

 32%|███████████████████▎                                         | 311/980 [00:48<01:45,  6.33it/s]

 32%|███████████████████▍                                         | 312/980 [00:48<01:45,  6.33it/s]

 32%|███████████████████▍                                         | 313/980 [00:49<01:45,  6.32it/s]

 32%|███████████████████▌                                         | 314/980 [00:49<01:45,  6.29it/s]

 32%|███████████████████▌                                         | 315/980 [00:49<01:46,  6.26it/s]

 32%|███████████████████▋                                         | 316/980 [00:49<01:45,  6.30it/s]

 32%|███████████████████▋                                         | 317/980 [00:49<01:44,  6.34it/s]

 32%|███████████████████▊                                         | 318/980 [00:49<01:43,  6.37it/s]

 33%|███████████████████▊                                         | 319/980 [00:50<01:46,  6.23it/s]

 33%|███████████████████▉                                         | 320/980 [00:50<01:45,  6.26it/s]

 33%|███████████████████▉                                         | 321/980 [00:50<01:43,  6.34it/s]

 33%|████████████████████                                         | 322/980 [00:50<01:44,  6.32it/s]

 33%|████████████████████                                         | 323/980 [00:50<01:42,  6.42it/s]

 33%|████████████████████▏                                        | 324/980 [00:50<01:41,  6.49it/s]

 33%|████████████████████▏                                        | 325/980 [00:51<01:40,  6.51it/s]

 33%|████████████████████▎                                        | 326/980 [00:51<01:40,  6.53it/s]

 33%|████████████████████▎                                        | 327/980 [00:51<01:39,  6.55it/s]

 33%|████████████████████▍                                        | 328/980 [00:51<01:39,  6.56it/s]

 34%|████████████████████▍                                        | 329/980 [00:51<01:38,  6.58it/s]

 34%|████████████████████▌                                        | 330/980 [00:51<01:39,  6.53it/s]

 34%|████████████████████▌                                        | 331/980 [00:51<01:39,  6.49it/s]

 34%|████████████████████▋                                        | 332/980 [00:52<01:39,  6.51it/s]

 34%|████████████████████▋                                        | 333/980 [00:52<01:39,  6.52it/s]

 34%|████████████████████▊                                        | 334/980 [00:52<01:38,  6.53it/s]

 34%|████████████████████▊                                        | 335/980 [00:52<01:38,  6.53it/s]

 34%|████████████████████▉                                        | 336/980 [00:52<01:38,  6.52it/s]

 34%|████████████████████▉                                        | 337/980 [00:52<01:38,  6.54it/s]

 34%|█████████████████████                                        | 338/980 [00:52<01:37,  6.56it/s]

 35%|█████████████████████                                        | 339/980 [00:53<01:37,  6.56it/s]

 35%|█████████████████████▏                                       | 340/980 [00:53<01:37,  6.54it/s]

 35%|█████████████████████▏                                       | 341/980 [00:53<01:37,  6.53it/s]

 35%|█████████████████████▎                                       | 342/980 [00:53<01:37,  6.55it/s]

 35%|█████████████████████▎                                       | 343/980 [00:53<01:37,  6.51it/s]

 35%|█████████████████████▍                                       | 344/980 [00:53<01:37,  6.53it/s]

 35%|█████████████████████▍                                       | 345/980 [00:54<01:37,  6.52it/s]

 35%|█████████████████████▌                                       | 346/980 [00:54<01:38,  6.44it/s]

 35%|█████████████████████▌                                       | 347/980 [00:54<01:37,  6.48it/s]

 36%|█████████████████████▋                                       | 348/980 [00:54<01:37,  6.51it/s]

 36%|█████████████████████▋                                       | 349/980 [00:54<01:36,  6.52it/s]

 36%|█████████████████████▊                                       | 350/980 [00:54<01:36,  6.54it/s]

 36%|█████████████████████▊                                       | 351/980 [00:54<01:35,  6.56it/s]

 36%|█████████████████████▉                                       | 352/980 [00:55<01:35,  6.55it/s]

 36%|█████████████████████▉                                       | 353/980 [00:55<01:35,  6.54it/s]

 36%|██████████████████████                                       | 354/980 [00:55<01:35,  6.57it/s]

 36%|██████████████████████                                       | 355/980 [00:55<01:34,  6.59it/s]

 36%|██████████████████████▏                                      | 356/980 [00:55<01:45,  5.92it/s]

 36%|██████████████████████▏                                      | 357/980 [00:55<01:42,  6.10it/s]

 37%|██████████████████████▎                                      | 358/980 [00:56<01:39,  6.24it/s]

 37%|██████████████████████▎                                      | 359/980 [00:56<01:37,  6.34it/s]

 37%|██████████████████████▍                                      | 360/980 [00:56<01:36,  6.41it/s]

 37%|██████████████████████▍                                      | 361/980 [00:56<01:35,  6.47it/s]

 37%|██████████████████████▌                                      | 362/980 [00:56<01:35,  6.50it/s]

 37%|██████████████████████▌                                      | 363/980 [00:56<01:34,  6.52it/s]

 37%|██████████████████████▋                                      | 364/980 [00:57<01:34,  6.55it/s]

 37%|██████████████████████▋                                      | 365/980 [00:57<01:34,  6.50it/s]

 37%|██████████████████████▊                                      | 366/980 [00:57<01:34,  6.48it/s]

 37%|██████████████████████▊                                      | 367/980 [00:57<01:34,  6.49it/s]

 38%|██████████████████████▉                                      | 368/980 [00:57<01:34,  6.49it/s]

 38%|██████████████████████▉                                      | 369/980 [00:57<01:34,  6.49it/s]

 38%|███████████████████████                                      | 370/980 [00:57<01:34,  6.49it/s]

 38%|███████████████████████                                      | 371/980 [00:58<01:33,  6.50it/s]

 38%|███████████████████████▏                                     | 372/980 [00:58<01:34,  6.47it/s]

 38%|███████████████████████▏                                     | 373/980 [00:58<01:34,  6.45it/s]

 38%|███████████████████████▎                                     | 374/980 [00:58<01:34,  6.43it/s]

 38%|███████████████████████▎                                     | 375/980 [00:58<01:34,  6.44it/s]

 38%|███████████████████████▍                                     | 376/980 [00:58<01:33,  6.43it/s]

 38%|███████████████████████▍                                     | 377/980 [00:59<01:33,  6.47it/s]

 39%|███████████████████████▌                                     | 378/980 [00:59<01:32,  6.51it/s]

 39%|███████████████████████▌                                     | 379/980 [00:59<01:31,  6.56it/s]

 39%|███████████████████████▋                                     | 380/980 [00:59<01:30,  6.63it/s]

 39%|███████████████████████▋                                     | 381/980 [00:59<01:29,  6.67it/s]

 39%|███████████████████████▊                                     | 382/980 [00:59<01:29,  6.70it/s]

 39%|███████████████████████▊                                     | 383/980 [00:59<01:29,  6.68it/s]

 39%|███████████████████████▉                                     | 384/980 [01:00<01:29,  6.62it/s]

 39%|███████████████████████▉                                     | 385/980 [01:00<01:30,  6.60it/s]

 39%|████████████████████████                                     | 386/980 [01:00<01:29,  6.61it/s]

 39%|████████████████████████                                     | 387/980 [01:00<01:30,  6.54it/s]

 40%|████████████████████████▏                                    | 388/980 [01:00<01:30,  6.52it/s]

 40%|████████████████████████▏                                    | 389/980 [01:00<01:30,  6.53it/s]

 40%|████████████████████████▎                                    | 390/980 [01:00<01:30,  6.55it/s]

 40%|████████████████████████▎                                    | 391/980 [01:01<01:29,  6.58it/s]

 40%|████████████████████████▍                                    | 392/980 [01:01<01:29,  6.59it/s]

 40%|████████████████████████▍                                    | 393/980 [01:01<01:30,  6.50it/s]

 40%|████████████████████████▌                                    | 394/980 [01:01<01:29,  6.52it/s]

 40%|████████████████████████▌                                    | 395/980 [01:01<01:29,  6.53it/s]

 40%|████████████████████████▋                                    | 396/980 [01:01<01:29,  6.49it/s]

 41%|████████████████████████▋                                    | 397/980 [01:02<01:29,  6.54it/s]

 41%|████████████████████████▊                                    | 398/980 [01:02<01:28,  6.55it/s]

 41%|████████████████████████▊                                    | 399/980 [01:02<01:29,  6.51it/s]

 41%|████████████████████████▉                                    | 400/980 [01:02<01:29,  6.47it/s]

 41%|████████████████████████▉                                    | 401/980 [01:02<01:30,  6.36it/s]

 41%|█████████████████████████                                    | 402/980 [01:02<01:31,  6.30it/s]

 41%|█████████████████████████                                    | 403/980 [01:03<01:30,  6.35it/s]

 41%|█████████████████████████▏                                   | 404/980 [01:03<01:29,  6.41it/s]

 41%|█████████████████████████▏                                   | 405/980 [01:03<01:29,  6.39it/s]

 41%|█████████████████████████▎                                   | 406/980 [01:03<01:29,  6.39it/s]

 42%|█████████████████████████▎                                   | 407/980 [01:03<01:29,  6.39it/s]

 42%|█████████████████████████▍                                   | 408/980 [01:03<01:29,  6.37it/s]

 42%|█████████████████████████▍                                   | 409/980 [01:03<01:29,  6.37it/s]

 42%|█████████████████████████▌                                   | 410/980 [01:04<01:29,  6.38it/s]

 42%|█████████████████████████▌                                   | 411/980 [01:04<01:29,  6.35it/s]

 42%|█████████████████████████▋                                   | 412/980 [01:04<01:30,  6.31it/s]

 42%|█████████████████████████▋                                   | 413/980 [01:04<01:32,  6.14it/s]

 42%|█████████████████████████▊                                   | 414/980 [01:04<01:31,  6.17it/s]

 42%|█████████████████████████▊                                   | 415/980 [01:04<01:30,  6.23it/s]

 42%|█████████████████████████▉                                   | 416/980 [01:05<01:30,  6.25it/s]

 43%|█████████████████████████▉                                   | 417/980 [01:05<01:29,  6.28it/s]

 43%|██████████████████████████                                   | 418/980 [01:05<01:30,  6.22it/s]

 43%|██████████████████████████                                   | 419/980 [01:05<01:29,  6.24it/s]

 43%|██████████████████████████▏                                  | 420/980 [01:05<01:30,  6.21it/s]

 43%|██████████████████████████▏                                  | 421/980 [01:05<01:32,  6.03it/s]

 43%|██████████████████████████▎                                  | 422/980 [01:06<01:32,  6.05it/s]

 43%|██████████████████████████▎                                  | 423/980 [01:06<01:32,  6.05it/s]

 43%|██████████████████████████▍                                  | 424/980 [01:06<01:31,  6.10it/s]

 43%|██████████████████████████▍                                  | 425/980 [01:06<01:30,  6.12it/s]

 43%|██████████████████████████▌                                  | 426/980 [01:06<01:30,  6.15it/s]

 44%|██████████████████████████▌                                  | 427/980 [01:06<01:29,  6.17it/s]

 44%|██████████████████████████▋                                  | 428/980 [01:07<01:30,  6.11it/s]

 44%|██████████████████████████▋                                  | 429/980 [01:07<01:33,  5.90it/s]

 44%|██████████████████████████▊                                  | 430/980 [01:07<01:32,  5.98it/s]

 44%|██████████████████████████▊                                  | 431/980 [01:07<01:30,  6.06it/s]

 44%|██████████████████████████▉                                  | 432/980 [01:07<01:29,  6.13it/s]

 44%|██████████████████████████▉                                  | 433/980 [01:07<01:28,  6.19it/s]

 44%|███████████████████████████                                  | 434/980 [01:08<01:27,  6.23it/s]

 44%|███████████████████████████                                  | 435/980 [01:08<01:27,  6.24it/s]

 44%|███████████████████████████▏                                 | 436/980 [01:08<01:26,  6.26it/s]

 45%|███████████████████████████▏                                 | 437/980 [01:08<01:26,  6.28it/s]

 45%|███████████████████████████▎                                 | 438/980 [01:08<01:26,  6.26it/s]

 45%|███████████████████████████▎                                 | 439/980 [01:08<01:26,  6.28it/s]

 45%|███████████████████████████▍                                 | 440/980 [01:08<01:26,  6.27it/s]

 45%|███████████████████████████▍                                 | 441/980 [01:09<01:27,  6.14it/s]

 45%|███████████████████████████▌                                 | 442/980 [01:09<01:27,  6.18it/s]

 45%|███████████████████████████▌                                 | 443/980 [01:09<01:26,  6.21it/s]

 45%|███████████████████████████▋                                 | 444/980 [01:09<01:26,  6.21it/s]

 45%|███████████████████████████▋                                 | 445/980 [01:09<01:25,  6.25it/s]

 46%|███████████████████████████▊                                 | 446/980 [01:09<01:25,  6.27it/s]

 46%|███████████████████████████▊                                 | 447/980 [01:10<01:24,  6.29it/s]

 46%|███████████████████████████▉                                 | 448/980 [01:10<01:24,  6.27it/s]

 46%|███████████████████████████▉                                 | 449/980 [01:10<01:24,  6.27it/s]

 46%|████████████████████████████                                 | 450/980 [01:10<01:24,  6.27it/s]

 46%|████████████████████████████                                 | 451/980 [01:10<01:24,  6.26it/s]

 46%|████████████████████████████▏                                | 452/980 [01:10<01:24,  6.26it/s]

 46%|████████████████████████████▏                                | 453/980 [01:11<01:24,  6.22it/s]

 46%|████████████████████████████▎                                | 454/980 [01:11<01:24,  6.23it/s]

 46%|████████████████████████████▎                                | 455/980 [01:11<01:23,  6.28it/s]

 47%|████████████████████████████▍                                | 456/980 [01:11<01:23,  6.31it/s]

 47%|████████████████████████████▍                                | 457/980 [01:11<01:22,  6.31it/s]

 47%|████████████████████████████▌                                | 458/980 [01:11<01:21,  6.42it/s]

 47%|████████████████████████████▌                                | 459/980 [01:11<01:20,  6.50it/s]

 47%|████████████████████████████▋                                | 460/980 [01:12<01:19,  6.53it/s]

 47%|████████████████████████████▋                                | 461/980 [01:12<01:19,  6.57it/s]

 47%|████████████████████████████▊                                | 462/980 [01:12<01:18,  6.59it/s]

 47%|████████████████████████████▊                                | 463/980 [01:12<01:18,  6.60it/s]

 47%|████████████████████████████▉                                | 464/980 [01:12<01:18,  6.61it/s]

 47%|████████████████████████████▉                                | 465/980 [01:12<01:17,  6.62it/s]

 48%|█████████████████████████████                                | 466/980 [01:13<01:17,  6.63it/s]

 48%|█████████████████████████████                                | 467/980 [01:13<01:20,  6.38it/s]

 48%|█████████████████████████████▏                               | 468/980 [01:13<01:20,  6.38it/s]

 48%|█████████████████████████████▏                               | 469/980 [01:13<01:19,  6.43it/s]

 48%|█████████████████████████████▎                               | 470/980 [01:13<01:19,  6.42it/s]

 48%|█████████████████████████████▎                               | 471/980 [01:13<01:18,  6.48it/s]

 48%|█████████████████████████████▍                               | 472/980 [01:13<01:17,  6.54it/s]

 48%|█████████████████████████████▍                               | 473/980 [01:14<01:17,  6.54it/s]

 48%|█████████████████████████████▌                               | 474/980 [01:14<01:17,  6.56it/s]

 48%|█████████████████████████████▌                               | 475/980 [01:14<01:16,  6.58it/s]

 49%|█████████████████████████████▋                               | 476/980 [01:14<01:16,  6.60it/s]

 49%|█████████████████████████████▋                               | 477/980 [01:14<01:16,  6.61it/s]

 49%|█████████████████████████████▊                               | 478/980 [01:14<01:15,  6.62it/s]

 49%|█████████████████████████████▊                               | 479/980 [01:15<01:15,  6.62it/s]

 49%|█████████████████████████████▉                               | 480/980 [01:15<01:15,  6.63it/s]

 49%|█████████████████████████████▉                               | 481/980 [01:15<01:15,  6.64it/s]

 49%|██████████████████████████████                               | 482/980 [01:15<01:14,  6.65it/s]

 49%|██████████████████████████████                               | 483/980 [01:15<01:14,  6.64it/s]

 49%|██████████████████████████████▏                              | 484/980 [01:15<01:14,  6.66it/s]

 49%|██████████████████████████████▏                              | 485/980 [01:15<01:14,  6.66it/s]

 50%|██████████████████████████████▎                              | 486/980 [01:16<01:14,  6.63it/s]

 50%|██████████████████████████████▎                              | 487/980 [01:16<01:14,  6.61it/s]

 50%|██████████████████████████████▍                              | 488/980 [01:16<01:14,  6.61it/s]

 50%|██████████████████████████████▍                              | 489/980 [01:16<01:14,  6.59it/s]

 50%|██████████████████████████████▌                              | 490/980 [01:16<01:14,  6.57it/s]

 50%|██████████████████████████████▌                              | 491/980 [01:16<01:14,  6.58it/s]

 50%|██████████████████████████████▌                              | 492/980 [01:17<01:14,  6.58it/s]

 50%|██████████████████████████████▋                              | 493/980 [01:17<01:13,  6.60it/s]

 50%|██████████████████████████████▋                              | 494/980 [01:17<01:13,  6.62it/s]

 51%|██████████████████████████████▊                              | 495/980 [01:17<01:13,  6.61it/s]

 51%|██████████████████████████████▊                              | 496/980 [01:17<01:13,  6.62it/s]

 51%|██████████████████████████████▉                              | 497/980 [01:17<01:12,  6.62it/s]

 51%|██████████████████████████████▉                              | 498/980 [01:17<01:12,  6.62it/s]

 51%|███████████████████████████████                              | 499/980 [01:18<01:12,  6.63it/s]

 51%|███████████████████████████████                              | 500/980 [01:18<01:12,  6.64it/s]

 51%|███████████████████████████████▏                             | 501/980 [01:18<01:12,  6.64it/s]

 51%|███████████████████████████████▏                             | 502/980 [01:18<01:12,  6.59it/s]

 51%|███████████████████████████████▎                             | 503/980 [01:18<01:12,  6.60it/s]

 51%|███████████████████████████████▎                             | 504/980 [01:18<01:11,  6.61it/s]

 52%|███████████████████████████████▍                             | 505/980 [01:18<01:11,  6.62it/s]

 52%|███████████████████████████████▍                             | 506/980 [01:19<01:11,  6.62it/s]

 52%|███████████████████████████████▌                             | 507/980 [01:19<01:11,  6.63it/s]

 52%|███████████████████████████████▌                             | 508/980 [01:19<01:11,  6.63it/s]

 52%|███████████████████████████████▋                             | 509/980 [01:19<01:11,  6.61it/s]

 52%|███████████████████████████████▋                             | 510/980 [01:19<01:11,  6.59it/s]

 52%|███████████████████████████████▊                             | 511/980 [01:19<01:12,  6.51it/s]

 52%|███████████████████████████████▊                             | 512/980 [01:20<01:11,  6.54it/s]

 52%|███████████████████████████████▉                             | 513/980 [01:20<01:12,  6.47it/s]

 52%|███████████████████████████████▉                             | 514/980 [01:20<01:11,  6.50it/s]

 53%|████████████████████████████████                             | 515/980 [01:20<01:12,  6.45it/s]

 53%|████████████████████████████████                             | 516/980 [01:20<01:11,  6.48it/s]

 53%|████████████████████████████████▏                            | 517/980 [01:20<01:11,  6.50it/s]

 53%|████████████████████████████████▏                            | 518/980 [01:20<01:10,  6.52it/s]

 53%|████████████████████████████████▎                            | 519/980 [01:21<01:10,  6.50it/s]

 53%|████████████████████████████████▎                            | 520/980 [01:21<01:10,  6.53it/s]

 53%|████████████████████████████████▍                            | 521/980 [01:21<01:10,  6.54it/s]

 53%|████████████████████████████████▍                            | 522/980 [01:21<01:09,  6.55it/s]

 53%|████████████████████████████████▌                            | 523/980 [01:21<01:09,  6.53it/s]

 53%|████████████████████████████████▌                            | 524/980 [01:21<01:09,  6.54it/s]

 54%|████████████████████████████████▋                            | 525/980 [01:22<01:09,  6.50it/s]

 54%|████████████████████████████████▋                            | 526/980 [01:22<01:10,  6.42it/s]

 54%|████████████████████████████████▊                            | 527/980 [01:22<01:09,  6.49it/s]

 54%|████████████████████████████████▊                            | 528/980 [01:22<01:09,  6.51it/s]

 54%|████████████████████████████████▉                            | 529/980 [01:22<01:08,  6.59it/s]

 54%|████████████████████████████████▉                            | 530/980 [01:22<01:07,  6.64it/s]

 54%|█████████████████████████████████                            | 531/980 [01:22<01:07,  6.66it/s]

 54%|█████████████████████████████████                            | 532/980 [01:23<01:07,  6.67it/s]

 54%|█████████████████████████████████▏                           | 533/980 [01:23<01:06,  6.69it/s]

 54%|█████████████████████████████████▏                           | 534/980 [01:23<01:06,  6.72it/s]

 55%|█████████████████████████████████▎                           | 535/980 [01:23<01:06,  6.72it/s]

 55%|█████████████████████████████████▎                           | 536/980 [01:23<01:06,  6.72it/s]

 55%|█████████████████████████████████▍                           | 537/980 [01:23<01:06,  6.65it/s]

 55%|█████████████████████████████████▍                           | 538/980 [01:23<01:06,  6.63it/s]

 55%|█████████████████████████████████▌                           | 539/980 [01:24<01:06,  6.64it/s]

 55%|█████████████████████████████████▌                           | 540/980 [01:24<01:06,  6.64it/s]

 55%|█████████████████████████████████▋                           | 541/980 [01:24<01:06,  6.63it/s]

 55%|█████████████████████████████████▋                           | 542/980 [01:24<01:05,  6.65it/s]

 55%|█████████████████████████████████▊                           | 543/980 [01:24<01:06,  6.62it/s]

 56%|█████████████████████████████████▊                           | 544/980 [01:24<01:07,  6.51it/s]

 56%|█████████████████████████████████▉                           | 545/980 [01:25<01:06,  6.55it/s]

 56%|█████████████████████████████████▉                           | 546/980 [01:25<01:06,  6.53it/s]

 56%|██████████████████████████████████                           | 547/980 [01:25<01:06,  6.50it/s]

 56%|██████████████████████████████████                           | 548/980 [01:25<01:06,  6.49it/s]

 56%|██████████████████████████████████▏                          | 549/980 [01:25<01:05,  6.55it/s]

 56%|██████████████████████████████████▏                          | 550/980 [01:25<01:05,  6.54it/s]

 56%|██████████████████████████████████▎                          | 551/980 [01:25<01:06,  6.50it/s]

 56%|██████████████████████████████████▎                          | 552/980 [01:26<01:05,  6.50it/s]

 56%|██████████████████████████████████▍                          | 553/980 [01:26<01:05,  6.51it/s]

 57%|██████████████████████████████████▍                          | 554/980 [01:26<01:04,  6.56it/s]

 57%|██████████████████████████████████▌                          | 555/980 [01:26<01:04,  6.55it/s]

 57%|██████████████████████████████████▌                          | 556/980 [01:26<01:06,  6.40it/s]

 57%|██████████████████████████████████▋                          | 557/980 [01:26<01:05,  6.43it/s]

 57%|██████████████████████████████████▋                          | 558/980 [01:27<01:06,  6.33it/s]

 57%|██████████████████████████████████▊                          | 559/980 [01:27<01:06,  6.37it/s]

 57%|██████████████████████████████████▊                          | 560/980 [01:27<01:05,  6.43it/s]

 57%|██████████████████████████████████▉                          | 561/980 [01:27<01:04,  6.46it/s]

 57%|██████████████████████████████████▉                          | 562/980 [01:27<01:05,  6.34it/s]

 57%|███████████████████████████████████                          | 563/980 [01:27<01:07,  6.21it/s]

 58%|███████████████████████████████████                          | 564/980 [01:28<01:06,  6.24it/s]

 58%|███████████████████████████████████▏                         | 565/980 [01:28<01:05,  6.29it/s]

 58%|███████████████████████████████████▏                         | 566/980 [01:28<01:05,  6.31it/s]

 58%|███████████████████████████████████▎                         | 567/980 [01:28<01:05,  6.33it/s]

 58%|███████████████████████████████████▎                         | 568/980 [01:28<01:04,  6.40it/s]

 58%|███████████████████████████████████▍                         | 569/980 [01:28<01:03,  6.45it/s]

 58%|███████████████████████████████████▍                         | 570/980 [01:28<01:04,  6.37it/s]

 58%|███████████████████████████████████▌                         | 571/980 [01:29<01:04,  6.34it/s]

 58%|███████████████████████████████████▌                         | 572/980 [01:29<01:03,  6.40it/s]

 58%|███████████████████████████████████▋                         | 573/980 [01:29<01:03,  6.44it/s]

 59%|███████████████████████████████████▋                         | 574/980 [01:29<01:03,  6.40it/s]

 59%|███████████████████████████████████▊                         | 575/980 [01:29<01:03,  6.39it/s]

 59%|███████████████████████████████████▊                         | 576/980 [01:29<01:03,  6.34it/s]

 59%|███████████████████████████████████▉                         | 577/980 [01:30<01:03,  6.34it/s]

 59%|███████████████████████████████████▉                         | 578/980 [01:30<01:03,  6.35it/s]

 59%|████████████████████████████████████                         | 579/980 [01:30<01:03,  6.34it/s]

 59%|████████████████████████████████████                         | 580/980 [01:30<01:03,  6.30it/s]

 59%|████████████████████████████████████▏                        | 581/980 [01:30<01:03,  6.29it/s]

 59%|████████████████████████████████████▏                        | 582/980 [01:30<01:02,  6.32it/s]

 59%|████████████████████████████████████▎                        | 583/980 [01:31<01:02,  6.33it/s]

 60%|████████████████████████████████████▎                        | 584/980 [01:31<01:03,  6.21it/s]

 60%|████████████████████████████████████▍                        | 585/980 [01:31<01:03,  6.22it/s]

 60%|████████████████████████████████████▍                        | 586/980 [01:31<01:03,  6.21it/s]

 60%|████████████████████████████████████▌                        | 587/980 [01:31<01:03,  6.20it/s]

 60%|████████████████████████████████████▌                        | 588/980 [01:31<01:03,  6.17it/s]

 60%|████████████████████████████████████▋                        | 589/980 [01:31<01:02,  6.21it/s]

 60%|████████████████████████████████████▋                        | 590/980 [01:32<01:02,  6.24it/s]

 60%|████████████████████████████████████▊                        | 591/980 [01:32<01:02,  6.25it/s]

 60%|████████████████████████████████████▊                        | 592/980 [01:32<01:01,  6.26it/s]

 61%|████████████████████████████████████▉                        | 593/980 [01:32<01:02,  6.21it/s]

 61%|████████████████████████████████████▉                        | 594/980 [01:32<01:02,  6.13it/s]

 61%|█████████████████████████████████████                        | 595/980 [01:32<01:03,  6.09it/s]

 61%|█████████████████████████████████████                        | 596/980 [01:33<01:02,  6.14it/s]

 61%|█████████████████████████████████████▏                       | 597/980 [01:33<01:02,  6.13it/s]

 61%|█████████████████████████████████████▏                       | 598/980 [01:33<01:02,  6.12it/s]

 61%|█████████████████████████████████████▎                       | 599/980 [01:33<01:01,  6.15it/s]

 61%|█████████████████████████████████████▎                       | 600/980 [01:33<01:02,  6.11it/s]

 61%|█████████████████████████████████████▍                       | 601/980 [01:33<01:01,  6.13it/s]

 61%|█████████████████████████████████████▍                       | 602/980 [01:34<01:02,  6.09it/s]

 62%|█████████████████████████████████████▌                       | 603/980 [01:34<01:01,  6.12it/s]

 62%|█████████████████████████████████████▌                       | 604/980 [01:34<01:01,  6.14it/s]

 62%|█████████████████████████████████████▋                       | 605/980 [01:34<01:00,  6.17it/s]

 62%|█████████████████████████████████████▋                       | 606/980 [01:34<01:01,  6.13it/s]

 62%|█████████████████████████████████████▊                       | 607/980 [01:34<01:00,  6.16it/s]

 62%|█████████████████████████████████████▊                       | 608/980 [01:35<01:00,  6.17it/s]

 62%|█████████████████████████████████████▉                       | 609/980 [01:35<00:59,  6.20it/s]

 62%|█████████████████████████████████████▉                       | 610/980 [01:35<01:00,  6.16it/s]

 62%|██████████████████████████████████████                       | 611/980 [01:35<00:59,  6.17it/s]

 62%|██████████████████████████████████████                       | 612/980 [01:35<00:59,  6.18it/s]

 63%|██████████████████████████████████████▏                      | 613/980 [01:35<00:59,  6.18it/s]

 63%|██████████████████████████████████████▏                      | 614/980 [01:36<00:58,  6.23it/s]

 63%|██████████████████████████████████████▎                      | 615/980 [01:36<00:57,  6.35it/s]

 63%|██████████████████████████████████████▎                      | 616/980 [01:36<00:56,  6.39it/s]

 63%|██████████████████████████████████████▍                      | 617/980 [01:36<00:56,  6.44it/s]

 63%|██████████████████████████████████████▍                      | 618/980 [01:36<00:55,  6.48it/s]

 63%|██████████████████████████████████████▌                      | 619/980 [01:36<00:55,  6.51it/s]

 63%|██████████████████████████████████████▌                      | 620/980 [01:36<00:55,  6.50it/s]

 63%|██████████████████████████████████████▋                      | 621/980 [01:37<00:55,  6.51it/s]

 63%|██████████████████████████████████████▋                      | 622/980 [01:37<00:55,  6.49it/s]

 64%|██████████████████████████████████████▊                      | 623/980 [01:37<00:54,  6.52it/s]

 64%|██████████████████████████████████████▊                      | 624/980 [01:37<00:54,  6.54it/s]

 64%|██████████████████████████████████████▉                      | 625/980 [01:37<00:54,  6.57it/s]

 64%|██████████████████████████████████████▉                      | 626/980 [01:37<00:54,  6.46it/s]

 64%|███████████████████████████████████████                      | 627/980 [01:38<00:55,  6.32it/s]

 64%|███████████████████████████████████████                      | 628/980 [01:38<00:56,  6.22it/s]

 64%|███████████████████████████████████████▏                     | 629/980 [01:38<00:57,  6.13it/s]

 64%|███████████████████████████████████████▏                     | 630/980 [01:38<00:56,  6.16it/s]

 64%|███████████████████████████████████████▎                     | 631/980 [01:38<00:56,  6.23it/s]

 64%|███████████████████████████████████████▎                     | 632/980 [01:38<00:57,  6.04it/s]

 65%|███████████████████████████████████████▍                     | 633/980 [01:39<00:56,  6.16it/s]

 65%|███████████████████████████████████████▍                     | 634/980 [01:39<00:55,  6.25it/s]

 65%|███████████████████████████████████████▌                     | 635/980 [01:39<00:54,  6.28it/s]

 65%|███████████████████████████████████████▌                     | 636/980 [01:39<00:55,  6.23it/s]

 65%|███████████████████████████████████████▋                     | 637/980 [01:39<00:56,  6.11it/s]

 65%|███████████████████████████████████████▋                     | 638/980 [01:39<00:56,  6.02it/s]

 65%|███████████████████████████████████████▊                     | 639/980 [01:40<00:57,  5.94it/s]

 65%|███████████████████████████████████████▊                     | 640/980 [01:40<00:56,  5.99it/s]

 65%|███████████████████████████████████████▉                     | 641/980 [01:40<00:56,  6.03it/s]

 66%|███████████████████████████████████████▉                     | 642/980 [01:40<00:56,  6.01it/s]

 66%|████████████████████████████████████████                     | 643/980 [01:40<00:57,  5.90it/s]

 66%|████████████████████████████████████████                     | 644/980 [01:40<00:55,  6.01it/s]

 66%|████████████████████████████████████████▏                    | 645/980 [01:41<00:55,  6.06it/s]

 66%|████████████████████████████████████████▏                    | 646/980 [01:41<00:55,  6.03it/s]

 66%|████████████████████████████████████████▎                    | 647/980 [01:41<00:54,  6.11it/s]

 66%|████████████████████████████████████████▎                    | 648/980 [01:41<00:53,  6.16it/s]

 66%|████████████████████████████████████████▍                    | 649/980 [01:41<00:52,  6.25it/s]

 66%|████████████████████████████████████████▍                    | 650/980 [01:41<00:52,  6.26it/s]

 66%|████████████████████████████████████████▌                    | 651/980 [01:41<00:52,  6.28it/s]

 67%|████████████████████████████████████████▌                    | 652/980 [01:42<00:51,  6.35it/s]

 67%|████████████████████████████████████████▋                    | 653/980 [01:42<00:51,  6.37it/s]

 67%|████████████████████████████████████████▋                    | 654/980 [01:42<00:51,  6.38it/s]

 67%|████████████████████████████████████████▊                    | 655/980 [01:42<00:50,  6.41it/s]

 67%|████████████████████████████████████████▊                    | 656/980 [01:42<00:50,  6.39it/s]

 67%|████████████████████████████████████████▉                    | 657/980 [01:42<00:51,  6.23it/s]

 67%|████████████████████████████████████████▉                    | 658/980 [01:43<00:51,  6.28it/s]

 67%|█████████████████████████████████████████                    | 659/980 [01:43<00:50,  6.32it/s]

 67%|█████████████████████████████████████████                    | 660/980 [01:43<00:50,  6.30it/s]

 67%|█████████████████████████████████████████▏                   | 661/980 [01:43<00:49,  6.38it/s]

 68%|█████████████████████████████████████████▏                   | 662/980 [01:43<00:49,  6.43it/s]

 68%|█████████████████████████████████████████▎                   | 663/980 [01:43<00:49,  6.43it/s]

 68%|█████████████████████████████████████████▎                   | 664/980 [01:44<00:49,  6.36it/s]

 68%|█████████████████████████████████████████▍                   | 665/980 [01:44<00:50,  6.25it/s]

 68%|█████████████████████████████████████████▍                   | 666/980 [01:44<00:50,  6.22it/s]

 68%|█████████████████████████████████████████▌                   | 667/980 [01:44<00:50,  6.26it/s]

 68%|█████████████████████████████████████████▌                   | 668/980 [01:44<00:49,  6.26it/s]

 68%|█████████████████████████████████████████▋                   | 669/980 [01:44<00:50,  6.22it/s]

 68%|█████████████████████████████████████████▋                   | 670/980 [01:44<00:50,  6.14it/s]

 68%|█████████████████████████████████████████▊                   | 671/980 [01:45<00:51,  6.03it/s]

 69%|█████████████████████████████████████████▊                   | 672/980 [01:45<00:51,  5.98it/s]

 69%|█████████████████████████████████████████▉                   | 673/980 [01:45<00:50,  6.07it/s]

 69%|█████████████████████████████████████████▉                   | 674/980 [01:45<00:50,  6.07it/s]

 69%|██████████████████████████████████████████                   | 675/980 [01:45<00:50,  6.01it/s]

 69%|██████████████████████████████████████████                   | 676/980 [01:45<00:49,  6.08it/s]

 69%|██████████████████████████████████████████▏                  | 677/980 [01:46<00:49,  6.16it/s]

 69%|██████████████████████████████████████████▏                  | 678/980 [01:46<00:49,  6.10it/s]

 69%|██████████████████████████████████████████▎                  | 679/980 [01:46<00:49,  6.12it/s]

 69%|██████████████████████████████████████████▎                  | 680/980 [01:46<00:49,  6.05it/s]

 69%|██████████████████████████████████████████▍                  | 681/980 [01:46<00:49,  6.10it/s]

 70%|██████████████████████████████████████████▍                  | 682/980 [01:46<00:48,  6.19it/s]

 70%|██████████████████████████████████████████▌                  | 683/980 [01:47<00:48,  6.10it/s]

 70%|██████████████████████████████████████████▌                  | 684/980 [01:47<00:49,  5.92it/s]

 70%|██████████████████████████████████████████▋                  | 685/980 [01:47<00:49,  5.95it/s]

 70%|██████████████████████████████████████████▋                  | 686/980 [01:47<00:49,  5.92it/s]

 70%|██████████████████████████████████████████▊                  | 687/980 [01:47<00:49,  5.93it/s]

 70%|██████████████████████████████████████████▊                  | 688/980 [01:47<00:48,  6.05it/s]

 70%|██████████████████████████████████████████▉                  | 689/980 [01:48<00:47,  6.15it/s]

 70%|██████████████████████████████████████████▉                  | 690/980 [01:48<00:46,  6.20it/s]

 71%|███████████████████████████████████████████                  | 691/980 [01:48<00:45,  6.32it/s]

 71%|███████████████████████████████████████████                  | 692/980 [01:48<00:45,  6.37it/s]

 71%|███████████████████████████████████████████▏                 | 693/980 [01:48<00:44,  6.43it/s]

 71%|███████████████████████████████████████████▏                 | 694/980 [01:48<00:44,  6.47it/s]

 71%|███████████████████████████████████████████▎                 | 695/980 [01:49<00:44,  6.47it/s]

 71%|███████████████████████████████████████████▎                 | 696/980 [01:49<00:45,  6.29it/s]

 71%|███████████████████████████████████████████▍                 | 697/980 [01:49<00:46,  6.09it/s]

 71%|███████████████████████████████████████████▍                 | 698/980 [01:49<00:45,  6.15it/s]

 71%|███████████████████████████████████████████▌                 | 699/980 [01:49<00:45,  6.20it/s]

 71%|███████████████████████████████████████████▌                 | 700/980 [01:49<00:44,  6.23it/s]

 72%|███████████████████████████████████████████▋                 | 701/980 [01:50<00:44,  6.23it/s]

 72%|███████████████████████████████████████████▋                 | 702/980 [01:50<00:44,  6.29it/s]

 72%|███████████████████████████████████████████▊                 | 703/980 [01:50<00:43,  6.36it/s]

 72%|███████████████████████████████████████████▊                 | 704/980 [01:50<00:43,  6.33it/s]

 72%|███████████████████████████████████████████▉                 | 705/980 [01:50<00:44,  6.25it/s]

 72%|███████████████████████████████████████████▉                 | 706/980 [01:50<00:43,  6.33it/s]

 72%|████████████████████████████████████████████                 | 707/980 [01:50<00:42,  6.35it/s]

 72%|████████████████████████████████████████████                 | 708/980 [01:51<00:42,  6.38it/s]

 72%|████████████████████████████████████████████▏                | 709/980 [01:51<00:42,  6.42it/s]

 72%|████████████████████████████████████████████▏                | 710/980 [01:51<00:42,  6.30it/s]

 73%|████████████████████████████████████████████▎                | 711/980 [01:51<00:43,  6.25it/s]

 73%|████████████████████████████████████████████▎                | 712/980 [01:51<00:42,  6.32it/s]

 73%|████████████████████████████████████████████▍                | 713/980 [01:51<00:41,  6.37it/s]

 73%|████████████████████████████████████████████▍                | 714/980 [01:52<00:41,  6.42it/s]

 73%|████████████████████████████████████████████▌                | 715/980 [01:52<00:41,  6.44it/s]

 73%|████████████████████████████████████████████▌                | 716/980 [01:52<00:40,  6.46it/s]

 73%|████████████████████████████████████████████▋                | 717/980 [01:52<00:46,  5.65it/s]

 73%|████████████████████████████████████████████▋                | 718/980 [01:52<00:44,  5.84it/s]

 73%|████████████████████████████████████████████▊                | 719/980 [01:52<00:44,  5.85it/s]

 73%|████████████████████████████████████████████▊                | 720/980 [01:53<00:44,  5.91it/s]

 74%|████████████████████████████████████████████▉                | 721/980 [01:53<00:43,  5.94it/s]

 74%|████████████████████████████████████████████▉                | 722/980 [01:53<00:42,  6.01it/s]

 74%|█████████████████████████████████████████████                | 723/980 [01:53<00:43,  5.98it/s]

 74%|█████████████████████████████████████████████                | 724/980 [01:53<00:44,  5.76it/s]

 74%|█████████████████████████████████████████████▏               | 725/980 [01:53<00:43,  5.82it/s]

 74%|█████████████████████████████████████████████▏               | 726/980 [01:54<00:42,  5.97it/s]

 74%|█████████████████████████████████████████████▎               | 727/980 [01:54<00:41,  6.08it/s]

 74%|█████████████████████████████████████████████▎               | 728/980 [01:54<00:40,  6.15it/s]

 74%|█████████████████████████████████████████████▍               | 729/980 [01:54<00:40,  6.21it/s]

 74%|█████████████████████████████████████████████▍               | 730/980 [01:54<00:40,  6.22it/s]

 75%|█████████████████████████████████████████████▌               | 731/980 [01:54<00:39,  6.24it/s]

 75%|█████████████████████████████████████████████▌               | 732/980 [01:55<00:39,  6.27it/s]

 75%|█████████████████████████████████████████████▋               | 733/980 [01:55<00:38,  6.35it/s]

 75%|█████████████████████████████████████████████▋               | 734/980 [01:55<00:38,  6.33it/s]

 75%|█████████████████████████████████████████████▊               | 735/980 [01:55<00:38,  6.37it/s]

 75%|█████████████████████████████████████████████▊               | 736/980 [01:55<00:38,  6.32it/s]

 75%|█████████████████████████████████████████████▊               | 737/980 [01:55<00:38,  6.29it/s]

 75%|█████████████████████████████████████████████▉               | 738/980 [01:56<00:38,  6.27it/s]

 75%|█████████████████████████████████████████████▉               | 739/980 [01:56<00:38,  6.25it/s]

 76%|██████████████████████████████████████████████               | 740/980 [01:56<00:38,  6.26it/s]

 76%|██████████████████████████████████████████████               | 741/980 [01:56<00:38,  6.26it/s]

 76%|██████████████████████████████████████████████▏              | 742/980 [01:56<00:38,  6.26it/s]

 76%|██████████████████████████████████████████████▏              | 743/980 [01:56<00:38,  6.22it/s]

 76%|██████████████████████████████████████████████▎              | 744/980 [01:56<00:38,  6.21it/s]

 76%|██████████████████████████████████████████████▎              | 745/980 [01:57<00:37,  6.19it/s]

 76%|██████████████████████████████████████████████▍              | 746/980 [01:57<00:38,  6.07it/s]

 76%|██████████████████████████████████████████████▍              | 747/980 [01:57<00:38,  6.10it/s]

 76%|██████████████████████████████████████████████▌              | 748/980 [01:57<00:38,  6.03it/s]

 76%|██████████████████████████████████████████████▌              | 749/980 [01:57<00:38,  6.07it/s]

 77%|██████████████████████████████████████████████▋              | 750/980 [01:57<00:37,  6.10it/s]

 77%|██████████████████████████████████████████████▋              | 751/980 [01:58<00:38,  5.98it/s]

 77%|██████████████████████████████████████████████▊              | 752/980 [01:58<00:37,  6.04it/s]

 77%|██████████████████████████████████████████████▊              | 753/980 [01:58<00:37,  6.10it/s]

 77%|██████████████████████████████████████████████▉              | 754/980 [01:58<00:36,  6.12it/s]

 77%|██████████████████████████████████████████████▉              | 755/980 [01:58<00:36,  6.13it/s]

 77%|███████████████████████████████████████████████              | 756/980 [01:58<00:36,  6.15it/s]

 77%|███████████████████████████████████████████████              | 757/980 [01:59<00:36,  6.16it/s]

 77%|███████████████████████████████████████████████▏             | 758/980 [01:59<00:35,  6.18it/s]

 77%|███████████████████████████████████████████████▏             | 759/980 [01:59<00:35,  6.20it/s]

 78%|███████████████████████████████████████████████▎             | 760/980 [01:59<00:35,  6.21it/s]

 78%|███████████████████████████████████████████████▎             | 761/980 [01:59<00:35,  6.15it/s]

 78%|███████████████████████████████████████████████▍             | 762/980 [01:59<00:35,  6.06it/s]

 78%|███████████████████████████████████████████████▍             | 763/980 [02:00<00:36,  6.01it/s]

 78%|███████████████████████████████████████████████▌             | 764/980 [02:00<00:36,  6.00it/s]

 78%|███████████████████████████████████████████████▌             | 765/980 [02:00<00:37,  5.77it/s]

 78%|███████████████████████████████████████████████▋             | 766/980 [02:00<00:36,  5.87it/s]

 78%|███████████████████████████████████████████████▋             | 767/980 [02:00<00:35,  5.96it/s]

 78%|███████████████████████████████████████████████▊             | 768/980 [02:00<00:36,  5.87it/s]

 78%|███████████████████████████████████████████████▊             | 769/980 [02:01<00:36,  5.85it/s]

 79%|███████████████████████████████████████████████▉             | 770/980 [02:01<00:35,  5.90it/s]

 79%|███████████████████████████████████████████████▉             | 771/980 [02:01<00:35,  5.96it/s]

 79%|████████████████████████████████████████████████             | 772/980 [02:01<00:34,  6.01it/s]

 79%|████████████████████████████████████████████████             | 773/980 [02:01<00:34,  6.05it/s]

 79%|████████████████████████████████████████████████▏            | 774/980 [02:01<00:34,  5.99it/s]

 79%|████████████████████████████████████████████████▏            | 775/980 [02:02<00:34,  6.00it/s]

 79%|████████████████████████████████████████████████▎            | 776/980 [02:02<00:34,  5.95it/s]

 79%|████████████████████████████████████████████████▎            | 777/980 [02:02<00:33,  5.99it/s]

 79%|████████████████████████████████████████████████▍            | 778/980 [02:02<00:33,  6.05it/s]

 79%|████████████████████████████████████████████████▍            | 779/980 [02:02<00:32,  6.09it/s]

 80%|████████████████████████████████████████████████▌            | 780/980 [02:02<00:32,  6.13it/s]

 80%|████████████████████████████████████████████████▌            | 781/980 [02:03<00:32,  6.18it/s]

 80%|████████████████████████████████████████████████▋            | 782/980 [02:03<00:31,  6.21it/s]

 80%|████████████████████████████████████████████████▋            | 783/980 [02:03<00:31,  6.23it/s]

 80%|████████████████████████████████████████████████▊            | 784/980 [02:03<00:31,  6.22it/s]

 80%|████████████████████████████████████████████████▊            | 785/980 [02:03<00:31,  6.23it/s]

 80%|████████████████████████████████████████████████▉            | 786/980 [02:03<00:31,  6.25it/s]

 80%|████████████████████████████████████████████████▉            | 787/980 [02:04<00:30,  6.26it/s]

 80%|█████████████████████████████████████████████████            | 788/980 [02:04<00:31,  6.13it/s]

 81%|█████████████████████████████████████████████████            | 789/980 [02:04<00:31,  6.13it/s]

 81%|█████████████████████████████████████████████████▏           | 790/980 [02:04<00:30,  6.18it/s]

 81%|█████████████████████████████████████████████████▏           | 791/980 [02:04<00:30,  6.18it/s]

 81%|█████████████████████████████████████████████████▎           | 792/980 [02:04<00:30,  6.18it/s]

 81%|█████████████████████████████████████████████████▎           | 793/980 [02:05<00:30,  6.20it/s]

 81%|█████████████████████████████████████████████████▍           | 794/980 [02:05<00:29,  6.27it/s]

 81%|█████████████████████████████████████████████████▍           | 795/980 [02:05<00:29,  6.34it/s]

 81%|█████████████████████████████████████████████████▌           | 796/980 [02:05<00:28,  6.36it/s]

 81%|█████████████████████████████████████████████████▌           | 797/980 [02:05<00:28,  6.35it/s]

 81%|█████████████████████████████████████████████████▋           | 798/980 [02:05<00:28,  6.29it/s]

 82%|█████████████████████████████████████████████████▋           | 799/980 [02:05<00:28,  6.26it/s]

 82%|█████████████████████████████████████████████████▊           | 800/980 [02:06<00:28,  6.28it/s]

 82%|█████████████████████████████████████████████████▊           | 801/980 [02:06<00:29,  6.07it/s]

 82%|█████████████████████████████████████████████████▉           | 802/980 [02:06<00:28,  6.20it/s]

 82%|█████████████████████████████████████████████████▉           | 803/980 [02:06<00:28,  6.29it/s]

 82%|██████████████████████████████████████████████████           | 804/980 [02:06<00:28,  6.18it/s]

 82%|██████████████████████████████████████████████████           | 805/980 [02:06<00:28,  6.13it/s]

 82%|██████████████████████████████████████████████████▏          | 806/980 [02:07<00:27,  6.23it/s]

 82%|██████████████████████████████████████████████████▏          | 807/980 [02:07<00:28,  6.12it/s]

 82%|██████████████████████████████████████████████████▎          | 808/980 [02:07<00:27,  6.24it/s]

 83%|██████████████████████████████████████████████████▎          | 809/980 [02:07<00:27,  6.30it/s]

 83%|██████████████████████████████████████████████████▍          | 810/980 [02:07<00:26,  6.37it/s]

 83%|██████████████████████████████████████████████████▍          | 811/980 [02:07<00:26,  6.41it/s]

 83%|██████████████████████████████████████████████████▌          | 812/980 [02:08<00:25,  6.46it/s]

 83%|██████████████████████████████████████████████████▌          | 813/980 [02:08<00:25,  6.48it/s]

 83%|██████████████████████████████████████████████████▋          | 814/980 [02:08<00:25,  6.39it/s]

 83%|██████████████████████████████████████████████████▋          | 815/980 [02:08<00:25,  6.41it/s]

 83%|██████████████████████████████████████████████████▊          | 816/980 [02:08<00:25,  6.47it/s]

 83%|██████████████████████████████████████████████████▊          | 817/980 [02:08<00:25,  6.46it/s]

 83%|██████████████████████████████████████████████████▉          | 818/980 [02:08<00:25,  6.47it/s]

 84%|██████████████████████████████████████████████████▉          | 819/980 [02:09<00:24,  6.45it/s]

 84%|███████████████████████████████████████████████████          | 820/980 [02:09<00:24,  6.44it/s]

 84%|███████████████████████████████████████████████████          | 821/980 [02:09<00:24,  6.42it/s]

 84%|███████████████████████████████████████████████████▏         | 822/980 [02:09<00:25,  6.31it/s]

 84%|███████████████████████████████████████████████████▏         | 823/980 [02:09<00:24,  6.32it/s]

 84%|███████████████████████████████████████████████████▎         | 824/980 [02:09<00:24,  6.36it/s]

 84%|███████████████████████████████████████████████████▎         | 825/980 [02:10<00:24,  6.36it/s]

 84%|███████████████████████████████████████████████████▍         | 826/980 [02:10<00:24,  6.36it/s]

 84%|███████████████████████████████████████████████████▍         | 827/980 [02:10<00:24,  6.31it/s]

 84%|███████████████████████████████████████████████████▌         | 828/980 [02:10<00:24,  6.26it/s]

 85%|███████████████████████████████████████████████████▌         | 829/980 [02:10<00:24,  6.25it/s]

 85%|███████████████████████████████████████████████████▋         | 830/980 [02:10<00:23,  6.31it/s]

 85%|███████████████████████████████████████████████████▋         | 831/980 [02:11<00:23,  6.29it/s]

 85%|███████████████████████████████████████████████████▊         | 832/980 [02:11<00:23,  6.34it/s]

 85%|███████████████████████████████████████████████████▊         | 833/980 [02:11<00:23,  6.36it/s]

 85%|███████████████████████████████████████████████████▉         | 834/980 [02:11<00:23,  6.32it/s]

 85%|███████████████████████████████████████████████████▉         | 835/980 [02:11<00:22,  6.37it/s]

 85%|████████████████████████████████████████████████████         | 836/980 [02:11<00:22,  6.37it/s]

 85%|████████████████████████████████████████████████████         | 837/980 [02:11<00:22,  6.38it/s]

 86%|████████████████████████████████████████████████████▏        | 838/980 [02:12<00:22,  6.37it/s]

 86%|████████████████████████████████████████████████████▏        | 839/980 [02:12<00:22,  6.15it/s]

 86%|████████████████████████████████████████████████████▎        | 840/980 [02:12<00:22,  6.21it/s]

 86%|████████████████████████████████████████████████████▎        | 841/980 [02:12<00:22,  6.22it/s]

 86%|████████████████████████████████████████████████████▍        | 842/980 [02:12<00:22,  6.21it/s]

 86%|████████████████████████████████████████████████████▍        | 843/980 [02:12<00:22,  6.17it/s]

 86%|████████████████████████████████████████████████████▌        | 844/980 [02:13<00:22,  6.16it/s]

 86%|████████████████████████████████████████████████████▌        | 845/980 [02:13<00:22,  6.09it/s]

 86%|████████████████████████████████████████████████████▋        | 846/980 [02:13<00:22,  6.06it/s]

 86%|████████████████████████████████████████████████████▋        | 847/980 [02:13<00:21,  6.08it/s]

 87%|████████████████████████████████████████████████████▊        | 848/980 [02:13<00:21,  6.16it/s]

 87%|████████████████████████████████████████████████████▊        | 849/980 [02:13<00:21,  6.23it/s]

 87%|████████████████████████████████████████████████████▉        | 850/980 [02:14<00:21,  6.08it/s]

 87%|████████████████████████████████████████████████████▉        | 851/980 [02:14<00:21,  6.10it/s]

 87%|█████████████████████████████████████████████████████        | 852/980 [02:14<00:20,  6.12it/s]

 87%|█████████████████████████████████████████████████████        | 853/980 [02:14<00:20,  6.08it/s]

 87%|█████████████████████████████████████████████████████▏       | 854/980 [02:14<00:21,  5.97it/s]

 87%|█████████████████████████████████████████████████████▏       | 855/980 [02:14<00:20,  6.15it/s]

 87%|█████████████████████████████████████████████████████▎       | 856/980 [02:15<00:19,  6.25it/s]

 87%|█████████████████████████████████████████████████████▎       | 857/980 [02:15<00:19,  6.34it/s]

 88%|█████████████████████████████████████████████████████▍       | 858/980 [02:15<00:19,  6.39it/s]

 88%|█████████████████████████████████████████████████████▍       | 859/980 [02:15<00:18,  6.43it/s]

 88%|█████████████████████████████████████████████████████▌       | 860/980 [02:15<00:18,  6.47it/s]

 88%|█████████████████████████████████████████████████████▌       | 861/980 [02:15<00:18,  6.48it/s]

 88%|█████████████████████████████████████████████████████▋       | 862/980 [02:16<00:18,  6.44it/s]

 88%|█████████████████████████████████████████████████████▋       | 863/980 [02:16<00:18,  6.43it/s]

 88%|█████████████████████████████████████████████████████▊       | 864/980 [02:16<00:18,  6.22it/s]

 88%|█████████████████████████████████████████████████████▊       | 865/980 [02:16<00:18,  6.23it/s]

 88%|█████████████████████████████████████████████████████▉       | 866/980 [02:16<00:18,  6.29it/s]

 88%|█████████████████████████████████████████████████████▉       | 867/980 [02:16<00:18,  6.24it/s]

 89%|██████████████████████████████████████████████████████       | 868/980 [02:16<00:18,  6.21it/s]

 89%|██████████████████████████████████████████████████████       | 869/980 [02:17<00:17,  6.23it/s]

 89%|██████████████████████████████████████████████████████▏      | 870/980 [02:17<00:17,  6.21it/s]

 89%|██████████████████████████████████████████████████████▏      | 871/980 [02:17<00:17,  6.21it/s]

 89%|██████████████████████████████████████████████████████▎      | 872/980 [02:17<00:17,  6.17it/s]

 89%|██████████████████████████████████████████████████████▎      | 873/980 [02:17<00:17,  5.94it/s]

 89%|██████████████████████████████████████████████████████▍      | 874/980 [02:17<00:17,  6.07it/s]

 89%|██████████████████████████████████████████████████████▍      | 875/980 [02:18<00:17,  6.13it/s]

 89%|██████████████████████████████████████████████████████▌      | 876/980 [02:18<00:16,  6.20it/s]

 89%|██████████████████████████████████████████████████████▌      | 877/980 [02:18<00:16,  6.24it/s]

 90%|██████████████████████████████████████████████████████▋      | 878/980 [02:18<00:16,  6.32it/s]

 90%|██████████████████████████████████████████████████████▋      | 879/980 [02:18<00:16,  6.20it/s]

 90%|██████████████████████████████████████████████████████▊      | 880/980 [02:18<00:15,  6.27it/s]

 90%|██████████████████████████████████████████████████████▊      | 881/980 [02:19<00:15,  6.35it/s]

 90%|██████████████████████████████████████████████████████▉      | 882/980 [02:19<00:15,  6.42it/s]

 90%|██████████████████████████████████████████████████████▉      | 883/980 [02:19<00:15,  6.47it/s]

 90%|███████████████████████████████████████████████████████      | 884/980 [02:19<00:14,  6.51it/s]

 90%|███████████████████████████████████████████████████████      | 885/980 [02:19<00:14,  6.55it/s]

 90%|███████████████████████████████████████████████████████▏     | 886/980 [02:19<00:14,  6.56it/s]

 91%|███████████████████████████████████████████████████████▏     | 887/980 [02:19<00:14,  6.56it/s]

 91%|███████████████████████████████████████████████████████▎     | 888/980 [02:20<00:14,  6.55it/s]

 91%|███████████████████████████████████████████████████████▎     | 889/980 [02:20<00:13,  6.54it/s]

 91%|███████████████████████████████████████████████████████▍     | 890/980 [02:20<00:14,  6.42it/s]

 91%|███████████████████████████████████████████████████████▍     | 891/980 [02:20<00:14,  6.10it/s]

 91%|███████████████████████████████████████████████████████▌     | 892/980 [02:20<00:14,  6.08it/s]

 91%|███████████████████████████████████████████████████████▌     | 893/980 [02:20<00:14,  6.08it/s]

 91%|███████████████████████████████████████████████████████▋     | 894/980 [02:21<00:14,  6.03it/s]

 91%|███████████████████████████████████████████████████████▋     | 895/980 [02:21<00:14,  6.05it/s]

 91%|███████████████████████████████████████████████████████▊     | 896/980 [02:21<00:13,  6.05it/s]

 92%|███████████████████████████████████████████████████████▊     | 897/980 [02:21<00:14,  5.90it/s]

 92%|███████████████████████████████████████████████████████▉     | 898/980 [02:21<00:14,  5.83it/s]

 92%|███████████████████████████████████████████████████████▉     | 899/980 [02:21<00:13,  5.92it/s]

 92%|████████████████████████████████████████████████████████     | 900/980 [02:22<00:13,  5.92it/s]

 92%|████████████████████████████████████████████████████████     | 901/980 [02:22<00:13,  6.01it/s]

 92%|████████████████████████████████████████████████████████▏    | 902/980 [02:22<00:12,  6.05it/s]

 92%|████████████████████████████████████████████████████████▏    | 903/980 [02:22<00:12,  6.01it/s]

 92%|████████████████████████████████████████████████████████▎    | 904/980 [02:22<00:12,  6.04it/s]

 92%|████████████████████████████████████████████████████████▎    | 905/980 [02:22<00:12,  6.02it/s]

 92%|████████████████████████████████████████████████████████▍    | 906/980 [02:23<00:12,  6.01it/s]

 93%|████████████████████████████████████████████████████████▍    | 907/980 [02:23<00:11,  6.08it/s]

 93%|████████████████████████████████████████████████████████▌    | 908/980 [02:23<00:11,  6.12it/s]

 93%|████████████████████████████████████████████████████████▌    | 909/980 [02:23<00:11,  6.09it/s]

 93%|████████████████████████████████████████████████████████▋    | 910/980 [02:23<00:11,  6.03it/s]

 93%|████████████████████████████████████████████████████████▋    | 911/980 [02:23<00:11,  5.99it/s]

 93%|████████████████████████████████████████████████████████▊    | 912/980 [02:24<00:11,  6.03it/s]

 93%|████████████████████████████████████████████████████████▊    | 913/980 [02:24<00:11,  6.04it/s]

 93%|████████████████████████████████████████████████████████▉    | 914/980 [02:24<00:10,  6.01it/s]

 93%|████████████████████████████████████████████████████████▉    | 915/980 [02:24<00:10,  5.94it/s]

 93%|█████████████████████████████████████████████████████████    | 916/980 [02:24<00:10,  5.94it/s]

 94%|█████████████████████████████████████████████████████████    | 917/980 [02:24<00:10,  5.90it/s]

 94%|█████████████████████████████████████████████████████████▏   | 918/980 [02:25<00:10,  5.90it/s]

 94%|█████████████████████████████████████████████████████████▏   | 919/980 [02:25<00:10,  5.76it/s]

 94%|█████████████████████████████████████████████████████████▎   | 920/980 [02:25<00:10,  5.60it/s]

 94%|█████████████████████████████████████████████████████████▎   | 921/980 [02:25<00:10,  5.62it/s]

 94%|█████████████████████████████████████████████████████████▍   | 922/980 [02:25<00:10,  5.60it/s]

 94%|█████████████████████████████████████████████████████████▍   | 923/980 [02:26<00:10,  5.51it/s]

 94%|█████████████████████████████████████████████████████████▌   | 924/980 [02:26<00:09,  5.61it/s]

 94%|█████████████████████████████████████████████████████████▌   | 925/980 [02:26<00:09,  5.59it/s]

 94%|█████████████████████████████████████████████████████████▋   | 926/980 [02:26<00:09,  5.69it/s]

 95%|█████████████████████████████████████████████████████████▋   | 927/980 [02:26<00:09,  5.60it/s]

 95%|█████████████████████████████████████████████████████████▊   | 928/980 [02:26<00:09,  5.70it/s]

 95%|█████████████████████████████████████████████████████████▊   | 929/980 [02:27<00:08,  5.82it/s]

 95%|█████████████████████████████████████████████████████████▉   | 930/980 [02:27<00:08,  5.86it/s]

 95%|█████████████████████████████████████████████████████████▉   | 931/980 [02:27<00:08,  5.83it/s]

 95%|██████████████████████████████████████████████████████████   | 932/980 [02:27<00:08,  5.88it/s]

 95%|██████████████████████████████████████████████████████████   | 933/980 [02:27<00:07,  5.95it/s]

 95%|██████████████████████████████████████████████████████████▏  | 934/980 [02:27<00:07,  5.97it/s]

 95%|██████████████████████████████████████████████████████████▏  | 935/980 [02:28<00:07,  6.01it/s]

 96%|██████████████████████████████████████████████████████████▎  | 936/980 [02:28<00:07,  6.00it/s]

 96%|██████████████████████████████████████████████████████████▎  | 937/980 [02:28<00:07,  6.00it/s]

 96%|██████████████████████████████████████████████████████████▍  | 938/980 [02:28<00:06,  6.05it/s]

 96%|██████████████████████████████████████████████████████████▍  | 939/980 [02:28<00:06,  6.10it/s]

 96%|██████████████████████████████████████████████████████████▌  | 940/980 [02:28<00:06,  6.01it/s]

 96%|██████████████████████████████████████████████████████████▌  | 941/980 [02:29<00:06,  6.08it/s]

 96%|██████████████████████████████████████████████████████████▋  | 942/980 [02:29<00:06,  6.16it/s]

 96%|██████████████████████████████████████████████████████████▋  | 943/980 [02:29<00:05,  6.21it/s]

 96%|██████████████████████████████████████████████████████████▊  | 944/980 [02:29<00:05,  6.24it/s]

 96%|██████████████████████████████████████████████████████████▊  | 945/980 [02:29<00:05,  6.24it/s]

 97%|██████████████████████████████████████████████████████████▉  | 946/980 [02:29<00:05,  6.25it/s]

 97%|██████████████████████████████████████████████████████████▉  | 947/980 [02:30<00:05,  6.08it/s]

 97%|███████████████████████████████████████████████████████████  | 948/980 [02:30<00:05,  6.02it/s]

 97%|███████████████████████████████████████████████████████████  | 949/980 [02:30<00:05,  5.96it/s]

 97%|███████████████████████████████████████████████████████████▏ | 950/980 [02:30<00:04,  6.02it/s]

 97%|███████████████████████████████████████████████████████████▏ | 951/980 [02:30<00:04,  5.93it/s]

 97%|███████████████████████████████████████████████████████████▎ | 952/980 [02:30<00:04,  5.99it/s]

 97%|███████████████████████████████████████████████████████████▎ | 953/980 [02:31<00:04,  6.05it/s]

 97%|███████████████████████████████████████████████████████████▍ | 954/980 [02:31<00:04,  6.13it/s]

 97%|███████████████████████████████████████████████████████████▍ | 955/980 [02:31<00:04,  6.19it/s]

 98%|███████████████████████████████████████████████████████████▌ | 956/980 [02:31<00:03,  6.25it/s]

 98%|███████████████████████████████████████████████████████████▌ | 957/980 [02:31<00:03,  6.30it/s]

 98%|███████████████████████████████████████████████████████████▋ | 958/980 [02:31<00:03,  6.30it/s]

 98%|███████████████████████████████████████████████████████████▋ | 959/980 [02:31<00:03,  6.30it/s]

 98%|███████████████████████████████████████████████████████████▊ | 960/980 [02:32<00:03,  6.30it/s]

 98%|███████████████████████████████████████████████████████████▊ | 961/980 [02:32<00:03,  6.32it/s]

 98%|███████████████████████████████████████████████████████████▉ | 962/980 [02:32<00:02,  6.34it/s]

 98%|███████████████████████████████████████████████████████████▉ | 963/980 [02:32<00:02,  6.25it/s]

 98%|████████████████████████████████████████████████████████████ | 964/980 [02:32<00:02,  6.27it/s]

 98%|████████████████████████████████████████████████████████████ | 965/980 [02:32<00:02,  6.28it/s]

 99%|████████████████████████████████████████████████████████████▏| 966/980 [02:33<00:02,  6.25it/s]

 99%|████████████████████████████████████████████████████████████▏| 967/980 [02:33<00:02,  6.29it/s]

 99%|████████████████████████████████████████████████████████████▎| 968/980 [02:33<00:01,  6.32it/s]

 99%|████████████████████████████████████████████████████████████▎| 969/980 [02:33<00:01,  6.28it/s]

 99%|████████████████████████████████████████████████████████████▍| 970/980 [02:33<00:01,  6.30it/s]

 99%|████████████████████████████████████████████████████████████▍| 971/980 [02:33<00:01,  6.28it/s]

 99%|████████████████████████████████████████████████████████████▌| 972/980 [02:34<00:01,  6.21it/s]

 99%|████████████████████████████████████████████████████████████▌| 973/980 [02:34<00:01,  6.17it/s]

 99%|████████████████████████████████████████████████████████████▋| 974/980 [02:34<00:00,  6.21it/s]

 99%|████████████████████████████████████████████████████████████▋| 975/980 [02:34<00:00,  6.21it/s]

100%|████████████████████████████████████████████████████████████▊| 976/980 [02:34<00:00,  6.22it/s]

100%|████████████████████████████████████████████████████████████▊| 977/980 [02:34<00:00,  6.23it/s]

100%|████████████████████████████████████████████████████████████▉| 978/980 [02:35<00:00,  6.25it/s]

100%|████████████████████████████████████████████████████████████▉| 979/980 [02:35<00:00,  6.25it/s]

100%|█████████████████████████████████████████████████████████████| 980/980 [02:35<00:00,  6.26it/s]

100%|█████████████████████████████████████████████████████████████| 980/980 [02:35<00:00,  6.31it/s]

'Skipped files: 0'

In [10]:
predictions = pd.concat(predictions, ignore_index=True)

In [11]:
display(predictions.shape)
display(predictions.head())

(671300, 8)

,trait,drug,score,true_class,method,n_top_genes,data,tissue
0,DOID:0050741,DB00215,103099.5,1,gene_based,-1.0,spredixcan-mashr-zscores-Adipose_Subcutaneous-...,Adipose_Subcutaneous
1,DOID:0050741,DB00704,355210.0,1,gene_based,-1.0,spredixcan-mashr-zscores-Adipose_Subcutaneous-...,Adipose_Subcutaneous
2,DOID:0050741,DB00822,388169.0,1,gene_based,-1.0,spredixcan-mashr-zscores-Adipose_Subcutaneous-...,Adipose_Subcutaneous
3,DOID:10283,DB00014,80190.0,1,gene_based,-1.0,spredixcan-mashr-zscores-Adipose_Subcutaneous-...,Adipose_Subcutaneous
4,DOID:10283,DB00175,232448.0,0,gene_based,-1.0,spredixcan-mashr-zscores-Adipose_Subcutaneous-...,Adipose_Subcutaneous

## Validation checks

In [ ]:
assert not predictions.isna().any().any()

_method_counts = predictions['method'].value_counts().reindex(EXPECTED_METHODS)
display(_method_counts)

N_PREDICTIONS = predictions[['drug', 'trait']].drop_duplicates().shape[0]
display(f'Unique drug-disease pairs: {N_PREDICTIONS}')

for method_name, thresholds in METHOD_THRESHOLDS.items():
    expected = N_TISSUES * len(thresholds) * N_PREDICTIONS
    actual = int(_method_counts.loc[method_name])
    assert actual == expected, f'{method_name}: expected {expected}, got {actual}'

method
gene_based               167825
module_based_archs4      167825
module_based_gtex        167825
module_based_recount2    167825
Name: count, dtype: int64

'Unique drug-disease pairs: 685'

In [ ]:
_tmp = predictions.groupby(['method', 'n_top_genes'], observed=True).size().rename('n')
display(_tmp)

for method_name, thresholds in METHOD_THRESHOLDS.items():
    method_counts = _tmp.loc[method_name]
    actual_thresholds = sorted(float(x) for x in method_counts.index)
    expected_thresholds = sorted(thresholds)
    assert actual_thresholds == expected_thresholds, (
        f'{method_name}: expected thresholds {expected_thresholds}, got {actual_thresholds}'
    )
    assert np.all(method_counts.values == N_TISSUES * N_PREDICTIONS), method_name

method                 n_top_genes
gene_based             -1.0           33565
                        50.0          33565
                        100.0         33565
                        250.0         33565
                        500.0         33565
module_based_archs4    -1.0           33565
                        5.0           33565
                        10.0          33565
                        25.0          33565
                        50.0          33565
module_based_gtex      -1.0           33565
                        5.0           33565
                        10.0          33565
                        25.0          33565
                        50.0          33565
module_based_recount2  -1.0           33565
                        5.0           33565
                        10.0          33565
                        25.0          33565
                        50.0          33565
Name: n, dtype: int64

## Save raw predictions

In [14]:
output_file = OUTPUT_DIR / 'predictions' / 'predictions_results.pkl'
display(output_file)
predictions.to_pickle(output_file)

PosixPath('/home/msubirana/Documents/pivlab/clamp-analyses/output/03_model_biology/00_archs4/02_drug_disease_associations/10_prediction_performance/lincs/predictions/predictions_results.pkl')

# Aggregate predictions

1. Average ranks across n_top_genes thresholds (per trait, drug, method, tissue).
2. Take maximum across tissues (per trait, drug, method).

This matches the PhenoPlier aggregation exactly.

In [15]:
def _reduce_mean(x):
    return pd.Series({
        'score': x['score'].mean(),
        'true_class': x['true_class'].unique()[0],
    })


def _reduce_max(x):
    return pd.Series({
        'score': x['score'].max(),
        'true_class': x['true_class'].unique()[0],
    })

In [16]:
predictions_avg = (
    # Step 1: average across n_top_genes thresholds
    predictions
    .groupby(['trait', 'drug', 'method', 'tissue'], observed=True)
    .apply(_reduce_mean, include_groups=False)
    .dropna()
    # Step 2: take maximum across tissues
    .groupby(['trait', 'drug', 'method'], observed=True)
    .apply(_reduce_max, include_groups=False)
    .dropna()
    .sort_index()
    .reset_index()
)

In [ ]:
display(predictions_avg.shape)
display(predictions_avg.head())

assert predictions_avg.shape[0] == len(EXPECTED_METHODS) * N_PREDICTIONS
assert predictions_avg.dropna().shape == predictions_avg.shape

(2740, 5)

          trait     drug                 method     score  true_class
0  DOID:0050741  DB00215             gene_based  316134.3         1.0
1  DOID:0050741  DB00215    module_based_archs4  324870.1         1.0
2  DOID:0050741  DB00215      module_based_gtex  349350.5         1.0
3  DOID:0050741  DB00215  module_based_recount2  398655.9         1.0
4  DOID:0050741  DB00704             gene_based  387103.6         1.0

## Save aggregated predictions

In [18]:
output_file = OUTPUT_DIR / 'predictions' / 'predictions_results_aggregated.pkl'
display(output_file)
predictions_avg.to_pickle(output_file)

PosixPath('/home/msubirana/Documents/pivlab/clamp-analyses/output/03_model_biology/00_archs4/02_drug_disease_associations/10_prediction_performance/lincs/predictions/predictions_results_aggregated.pkl')

# ROC performance

In [19]:
# AUROC per method and n_top_genes threshold
predictions.groupby(['method', 'tissue', 'n_top_genes'], observed=True).apply(
    lambda x: roc_auc_score(x['true_class'], x['score']), include_groups=False
).groupby(['method', 'n_top_genes'], observed=True).describe()

                                   count      mean       std       min  \
method                n_top_genes
gene_based            -1.0          49.0  0.549364  0.023679  0.504653
                       50.0         49.0  0.537231  0.023829  0.481431
                       100.0        49.0  0.536558  0.018923  0.487655
                       250.0        49.0  0.538607  0.023377  0.477309
                       500.0        49.0  0.540913  0.022241  0.500984
module_based_archs4   -1.0          49.0  0.547769  0.023010  0.498465
                       5.0          49.0  0.552505  0.029543  0.482164
                       10.0         49.0  0.547163  0.028732  0.486371
                       25.0         49.0  0.549188  0.029233  0.485197
                       50.0         49.0  0.548572  0.028449  0.488242
module_based_gtex     -1.0          49.0  0.523350  0.023830  0.473286
                       5.0          49.0  0.530892  0.028212  0.481198
                       10.0         49.0  0.532638  0.029691  0.474093
                       25.0         49.0  0.526181  0.028313  0.470461
                       50.0         49.0  0.524910  0.028380  0.459455
module_based_recount2 -1.0          49.0  0.536287  0.020948  0.492913
                       5.0          49.0  0.545067  0.026516  0.496509
                       10.0         49.0  0.547962  0.030184  0.488120
                       25.0         49.0  0.546768  0.021301  0.504042
                       50.0         49.0  0.544021  0.021914  0.496851

                                        25%       50%       75%       max
method                n_top_genes
gene_based            -1.0         0.536803  0.550034  0.564318  0.598705
                       50.0        0.522263  0.535861  0.552089  0.607265
                       100.0       0.526958  0.536619  0.550328  0.566788
                       250.0       0.521321  0.539738  0.556467  0.583908
                       500.0       0.523131  0.544030  0.556442  0.598693
module_based_archs4   -1.0         0.532657  0.547845  0.563461  0.591747
                       5.0         0.536619  0.553312  0.567399  0.617305
                       10.0        0.526396  0.547845  0.564758  0.620387
                       25.0        0.529539  0.548493  0.570628  0.633924
                       50.0        0.527545  0.543015  0.569564  0.612022
module_based_gtex     -1.0         0.500116  0.526310  0.542685  0.572462
                       5.0         0.513825  0.526433  0.546145  0.602924
                       10.0        0.512027  0.528573  0.553752  0.597005
                       25.0        0.511061  0.528512  0.539542  0.611142
                       50.0        0.508285  0.523926  0.538209  0.633068
module_based_recount2 -1.0         0.521651  0.534430  0.552040  0.588286
                       5.0         0.522862  0.546121  0.563926  0.600160
                       10.0        0.527399  0.545363  0.567901  0.623016
                       25.0        0.530713  0.544531  0.561639  0.590940
                       50.0        0.527704  0.541645  0.560331  0.596944

In [20]:
# Final AUROC using aggregated predictions
auroc_final = predictions_avg.groupby('method', observed=True).apply(
    lambda x: roc_auc_score(x['true_class'], x['score']), include_groups=False
).rename('AUROC')
display(auroc_final)

method
gene_based               0.583382
module_based_archs4      0.625419
module_based_gtex        0.602484
module_based_recount2    0.612267
Name: AUROC, dtype: float64

These are the final performance measures using AUROC.

# Precision-Recall performance

In [21]:
# Average precision per method and n_top_genes threshold
predictions.groupby(['method', 'tissue', 'n_top_genes'], observed=True).apply(
    lambda x: average_precision_score(x['true_class'], x['score']), include_groups=False
).groupby(['method', 'n_top_genes'], observed=True).describe()

                                   count      mean       std       min  \
method                n_top_genes
gene_based            -1.0          49.0  0.823048  0.012367  0.791177
                       50.0         49.0  0.819142  0.011775  0.793504
                       100.0        49.0  0.819522  0.010505  0.782200
                       250.0        49.0  0.820481  0.012213  0.788298
                       500.0        49.0  0.820813  0.011201  0.801469
module_based_archs4   -1.0          49.0  0.820627  0.013044  0.795488
                       5.0          49.0  0.823120  0.016803  0.778636
                       10.0         49.0  0.821277  0.016539  0.779160
                       25.0         49.0  0.822177  0.016665  0.782468
                       50.0         49.0  0.821530  0.015951  0.788736
module_based_gtex     -1.0          49.0  0.808618  0.013861  0.784565
                       5.0          49.0  0.812254  0.015743  0.774344
                       10.0         49.0  0.814723  0.016438  0.786304
                       25.0         49.0  0.812677  0.015250  0.782873
                       50.0         49.0  0.810747  0.015822  0.769474
module_based_recount2 -1.0          49.0  0.816358  0.011285  0.789425
                       5.0          49.0  0.820513  0.013449  0.794799
                       10.0         49.0  0.824063  0.013886  0.799884
                       25.0         49.0  0.823404  0.012410  0.787397
                       50.0         49.0  0.821123  0.011877  0.798447

                                        25%       50%       75%       max
method                n_top_genes
gene_based            -1.0         0.817139  0.822989  0.828268  0.845962
                       50.0        0.811550  0.818870  0.827690  0.850680
                       100.0       0.812821  0.820163  0.825928  0.837381
                       250.0       0.812494  0.820298  0.829858  0.841266
                       500.0       0.814246  0.819441  0.828770  0.849463
module_based_archs4   -1.0         0.811732  0.820915  0.828317  0.845979
                       5.0         0.813708  0.820906  0.833490  0.857807
                       10.0        0.811535  0.819588  0.832004  0.863404
                       25.0        0.811267  0.820579  0.832461  0.870218
                       50.0        0.809792  0.820001  0.832301  0.858174
module_based_gtex     -1.0         0.799159  0.809267  0.820097  0.835931
                       5.0         0.803583  0.808868  0.823177  0.846560
                       10.0        0.803776  0.815920  0.825037  0.847027
                       25.0        0.804159  0.812994  0.822185  0.856536
                       50.0        0.799408  0.811151  0.821359  0.862883
module_based_recount2 -1.0         0.807714  0.816788  0.825633  0.837674
                       5.0         0.812979  0.821179  0.830449  0.845290
                       10.0        0.816395  0.820898  0.831172  0.860226
                       25.0        0.816626  0.822205  0.830477  0.850402
                       50.0        0.811265  0.820492  0.827575  0.847281

In [22]:
# Final average precision using aggregated predictions
ap_final = predictions_avg.groupby('method', observed=True).apply(
    lambda x: average_precision_score(x['true_class'], x['score']), include_groups=False
).rename('AvgPrecision')
display(ap_final)

method
gene_based               0.844942
module_based_archs4      0.849646
module_based_gtex        0.839313
module_based_recount2    0.845789
Name: AvgPrecision, dtype: float64

These are the final performance measures using average precision.

# Summary

In [23]:
summary = pd.concat([auroc_final, ap_final], axis=1)
display(summary)

                          AUROC  AvgPrecision
method
gene_based             0.583382      0.844942
module_based_archs4    0.625419      0.849646
module_based_gtex      0.602484      0.839313
module_based_recount2  0.612267      0.845789