# GTEx global alignment

Two analyses per GTEx tissue, each testing whether the selected SHAP LV(s) recover the true tissue by ORA against the GTEx tissue gene-set database:

1. **top1**: the single highest-ranked SHAP LV per tissue.
2. **cumulative25**: the top-ranked LVs needed to reach `CUMULATIVE_PCT`% of cumulative SHAP per tissue, the same criterion used in `00_LV_importance_true_labels.ipynb` / `01_LV_importance_true_labels_biology.ipynb`.

In [1]:
library(here)
library(dplyr)
library(tidyr)
library(stringr)
library(Matrix)
library(clusterProfiler)


SHAP_DIR <- here('output', '03_model_biology', '01_gtex',
                 '03_rf_true_labels', '00_LV_importance_true_labels',
                 'gtex_feature_importance_true_labels_binary_shap')
OUT_DIR  <- here('output', '03_model_biology', '01_gtex', '03_rf_true_labels', '02_global_alignment')
dir.create(OUT_DIR, recursive = TRUE, showWarnings = FALSE)

CLAMP_RDS      <- here('output', '01_model_building', '02_gtex', '01_CLAMP', 'CLAMPfull.rds')
GTEX_TISSUE_DB <- here('data', 'archs4', 'GTEx_Tissues_pathMat.rds')

N_LVS_PER_TISSUE <- 1L
CUMULATIVE_PCT   <- 25  # same threshold as 01_LV_importance_true_labels_biology.ipynb
TOP_GENE_PCT     <- 0.01
FDR_THRESH       <- 0.05

here() starts at /home/marc/Documents/pivlab/clamp-analyses

Attaching package: ‘dplyr’

The following objects are masked from ‘package:stats’:

    filter, lag

The following objects are masked from ‘package:base’:

    intersect, setdiff, setequal, union

Attaching package: ‘Matrix’

The following objects are masked from ‘package:tidyr’:

    expand, pack, unpack

clusterProfiler v4.14.0 Learn more at https://yulab-smu.top/contribution-knowledge-mining/

Please cite:

S Xu, E Hu, Y Cai, Z Xie, X Luo, L Zhan, W Tang, Q Wang, B Liu, R Wang,
W Xie, T Wu, L Xie, G Yu. Using clusterProfiler to characterize
multiomics data. Nature Protocols. 2024, 19(11):3292-3320

Attaching package: ‘clusterProfiler’

The following object is masked from ‘package:stats’:

    filter

In [2]:
shap_all <- read.delim(file.path(SHAP_DIR, 'all_shap_positive.tsv'),
                       stringsAsFactors = FALSE, check.names = FALSE)

selected_lvs_top1 <- shap_all %>%
    dplyr::arrange(Tissue, Rank) %>%
    dplyr::group_by(Tissue) %>%
    dplyr::slice_head(n = N_LVS_PER_TISSUE) %>%
    dplyr::ungroup() %>%
    dplyr::rename(LV = Feature) %>%
    dplyr::select(Tissue, LV, Rank, Mean_SHAP_Tissue, Cumulative_SHAP, Cumulative_Percent)

selected_lvs_cum <- shap_all %>%
    dplyr::arrange(Tissue, Rank) %>%
    dplyr::group_by(Tissue) %>%
    dplyr::mutate(
        reaches_thresh = Cumulative_Percent >= CUMULATIVE_PCT,
        cutoff_rank = if (any(reaches_thresh)) min(Rank[reaches_thresh]) else max(Rank)
    ) %>%
    dplyr::filter(Rank <= cutoff_rank) %>%
    dplyr::ungroup() %>%
    dplyr::rename(LV = Feature) %>%
    dplyr::select(Tissue, LV, Rank, Mean_SHAP_Tissue, Cumulative_SHAP, Cumulative_Percent)

selections <- list(top1 = selected_lvs_top1, cumulative25 = selected_lvs_cum)

cat('Tissues:', dplyr::n_distinct(selected_lvs_top1$Tissue), '\n')
for (nm in names(selections)) {
    cat(sprintf('  [%s] selected LV/tissue rows: %d, unique LVs: %d\n',
                nm, nrow(selections[[nm]]), dplyr::n_distinct(selections[[nm]]$LV)))
}

dplyr::bind_rows(lapply(names(selections), function(nm) {
    selections[[nm]] %>%
        dplyr::count(Tissue, name = 'n_selected_lvs') %>%
        dplyr::mutate(analysis = nm)
})) %>%
    tidyr::pivot_wider(names_from = analysis, values_from = n_selected_lvs) %>%
    dplyr::arrange(Tissue)

Tissues: 49

  [top1] selected LV/tissue rows: 49, unique LVs: 41
  [cumulative25] selected LV/tissue rows: 226, unique LVs: 124

   Tissue                                    top1 cumulative25
1  Adipose - Subcutaneous                    1    6
2  Adipose - Visceral (Omentum)              1    5
3  Adrenal Gland                             1    2
4  Artery - Aorta                            1    3
5  Artery - Coronary                         1    4
6  Artery - Tibial                           1    4
7  Brain - Amygdala                          1    4
8  Brain - Anterior cingulate cortex (BA24)  1    6
9  Brain - Caudate (basal ganglia)           1    8
10 Brain - Cerebellar Hemisphere             1    9
11 Brain - Cerebellum                        1    8
12 Brain - Cortex                            1    4
13 Brain - Frontal Cortex (BA9)              1    6
14 Brain - Hippocampus                       1    7
15 Brain - Hypothalamus                      1    5
16 Brain - Nucleus accumbens (basal ganglia) 1    7
17 Brain - Putamen (basal ganglia)           1    9
18 Brain - Spinal cord (cervical c-1)        1    5
19 Brain - Substantia nigra                  1    8
20 Breast - Mammary Tissue                   1    5
21 Cells - Cultured fibroblasts              1    4
22 Cells - EBV-transformed lymphocytes       1    5
23 Colon - Sigmoid                           1    3
24 Colon - Transverse                        1    6
25 Esophagus - Gastroesophageal Junction     1    6
26 Esophagus - Mucosa                        1    3
27 Esophagus - Muscularis                    1    3
28 Heart - Atrial Appendage                  1    3
29 Heart - Left Ventricle                    1    6
30 Kidney - Cortex                           1    3
31 Liver                                     1    4
32 Lung                                      1    2
33 Minor Salivary Gland                      1    3
34 Muscle - Skeletal                         1    3
35 Nerve - Tibial                            1    2
36 Ovary                                     1    4
37 Pancreas                                  1    2
38 Pituitary                                 1    5
39 Prostate                                  1    4
40 Skin - Not Sun Exposed (Suprapubic)       1    5
41 Skin - Sun Exposed (Lower leg)            1    5
42 Small Intestine - Terminal Ileum          1    7
43 Spleen                                    1    3
44 Stomach                                   1    4
45 Testis                                    1    3
46 Thyroid                                   1    1
47 Uterus                                    1    4
48 Vagina                                    1    4
49 Whole Blood                               1    4

In [3]:
clamp <- readRDS(CLAMP_RDS)
Z_full <- as.matrix(clamp$Z)
rm(clamp)

all_selected_lvs <- unique(unlist(lapply(selections, function(df) df$LV)))
selected_unique_lvs <- intersect(all_selected_lvs, colnames(Z_full))
missing_lvs <- setdiff(all_selected_lvs, colnames(Z_full))
if (length(missing_lvs) > 0) warning('Missing LVs in Z: ', paste(missing_lvs, collapse = ', '))

Z <- Z_full[, selected_unique_lvs, drop = FALSE]
rm(Z_full)
universe_genes <- rownames(Z)
n_top_genes <- max(1L, ceiling(TOP_GENE_PCT * nrow(Z)))

cat('Z:', nrow(Z), 'genes x', ncol(Z), 'unique LVs (union across analyses)\n')
cat('Top genes per LV:', n_top_genes, '\n')

Z: 21613 genes x 124 unique LVs (union across analyses)

Top genes per LV: 217

In [4]:
gtex_mat <- readRDS(GTEX_TISSUE_DB)
term_names <- unname(colnames(gtex_mat))

parse_gtex_tissue <- function(x) {
    x <- sub('^GTEx_Tissues_', '', x)
    x <- sub(' (Male|Female) [0-9]+-[0-9]+ Up$', '', x)
    x
}

normalize_text <- function(x) {
    x <- tolower(x)
    x <- gsub('[^a-z0-9]+', ' ', x)
    stringr::str_squish(x)
}

term2gene <- lapply(seq_along(term_names), function(i) {
    rownames(gtex_mat)[gtex_mat[, i] != 0]
})
names(term2gene) <- term_names

term2gene_df <- do.call(rbind, lapply(names(term2gene), function(term) {
    data.frame(term = term, gene = term2gene[[term]], stringsAsFactors = FALSE)
}))

term_map <- data.frame(
    term = term_names,
    parsed_tissue = parse_gtex_tissue(term_names),
    normalized_tissue = normalize_text(parse_gtex_tissue(term_names)),
    stringsAsFactors = FALSE
)

tissue_check <- dplyr::bind_rows(selections) %>%
    dplyr::distinct(Tissue) %>%
    dplyr::mutate(
        normalized_tissue = normalize_text(Tissue),
        matched_in_gtex_db = normalized_tissue %in% term_map$normalized_tissue,
        n_db_sets = vapply(normalized_tissue, function(x) sum(term_map$normalized_tissue == x), integer(1))
    )

cat('GTEx tissue gene sets:', length(term2gene), '\n')
stopifnot(all(tissue_check$matched_in_gtex_db))
tissue_check

GTEx tissue gene sets: 511

                                      Tissue
adipose subcutaneous                  Adipose - Subcutaneous
adipose visceral omentum              Adipose - Visceral (Omentum)
adrenal gland                         Adrenal Gland
artery aorta                          Artery - Aorta
artery coronary                       Artery - Coronary
artery tibial                         Artery - Tibial
brain amygdala                        Brain - Amygdala
brain anterior cingulate cortex ba24  Brain - Anterior cingulate cortex (BA24)
brain caudate basal ganglia           Brain - Caudate (basal ganglia)
brain cerebellar hemisphere           Brain - Cerebellar Hemisphere
brain cerebellum                      Brain - Cerebellum
brain cortex                          Brain - Cortex
brain frontal cortex ba9              Brain - Frontal Cortex (BA9)
brain hippocampus                     Brain - Hippocampus
brain hypothalamus                    Brain - Hypothalamus
brain nucleus accumbens basal ganglia Brain - Nucleus accumbens (basal ganglia)
brain putamen basal ganglia           Brain - Putamen (basal ganglia)
brain spinal cord cervical c 1        Brain - Spinal cord (cervical c-1)
brain substantia nigra                Brain - Substantia nigra
breast mammary tissue                 Breast - Mammary Tissue
cells cultured fibroblasts            Cells - Cultured fibroblasts
cells ebv transformed lymphocytes     Cells - EBV-transformed lymphocytes
colon sigmoid                         Colon - Sigmoid
colon transverse                      Colon - Transverse
esophagus gastroesophageal junction   Esophagus - Gastroesophageal Junction
esophagus mucosa                      Esophagus - Mucosa
esophagus muscularis                  Esophagus - Muscularis
heart atrial appendage                Heart - Atrial Appendage
heart left ventricle                  Heart - Left Ventricle
kidney cortex                         Kidney - Cortex
liver                                 Liver
lung                                  Lung
minor salivary gland                  Minor Salivary Gland
muscle skeletal                       Muscle - Skeletal
nerve tibial                          Nerve - Tibial
ovary                                 Ovary
pancreas                              Pancreas
pituitary                             Pituitary
prostate                              Prostate
skin not sun exposed suprapubic       Skin - Not Sun Exposed (Suprapubic)
skin sun exposed lower leg            Skin - Sun Exposed (Lower leg)
small intestine terminal ileum        Small Intestine - Terminal Ileum
spleen                                Spleen
stomach                               Stomach
testis                                Testis
thyroid                               Thyroid
uterus                                Uterus
vagina                                Vagina
whole blood                           Whole Blood
                                      normalized_tissue
adipose subcutaneous                  adipose subcutaneous
adipose visceral omentum              adipose visceral omentum
adrenal gland                         adrenal gland
artery aorta                          artery aorta
artery coronary                       artery coronary
artery tibial                         artery tibial
brain amygdala                        brain amygdala
brain anterior cingulate cortex ba24  brain anterior cingulate cortex ba24
brain caudate basal ganglia           brain caudate basal ganglia
brain cerebellar hemisphere           brain cerebellar hemisphere
brain cerebellum                      brain cerebellum
brain cortex                          brain cortex
brain frontal cortex ba9              brain frontal cortex ba9
brain hippocampus                     brain hippocampus
brain hypothalamus                    brain hypothalamus
brain nucleus accumbens basal ganglia brain nucleus accumbens basal ganglia
brain putamen basal ganglia           brain putamen basal ganglia
brain spinal cord cervical c 1        brain spinal cord cervical c 1
brain substantia nigra                brain substantia nigra
breast mammary tissue                 breast mammary tissue
cells cultured fibroblasts            cells cultured fibroblasts
cells ebv transformed lymphocytes     cells ebv transformed lymphocytes
colon sigmoid                         colon sigmoid
colon transverse                      colon transverse
esophagus gastroesophageal junction   esophagus gastroesophageal junction
esophagus mucosa                      esophagus mucosa
esophagus muscularis                  esophagus muscularis
heart atrial appendage                heart atrial appendage
heart left ventricle                  heart left ventricle
kidney cortex                         kidney cortex
liver                                 liver
lung                                  lung
minor salivary gland                  minor salivary gland
muscle skeletal                       muscle skeletal
nerve tibial                          nerve tibial
ovary                                 ovary
pancreas                              pancreas
pituitary                             pituitary
prostate                              prostate
skin not sun exposed suprapubic       skin not sun exposed suprapubic
skin sun exposed lower leg            skin sun exposed lower leg
small intestine terminal ileum        small intestine terminal ileum
spleen                                spleen
stomach                               stomach
testis                                testis
thyroid                               thyroid
uterus                                uterus
vagina                                vagina
whole blood                           whole blood
                                      matched_in_gtex_db n_db_sets
adipose subcutaneous                  TRUE               12
adipose visceral omentum              TRUE               12
adrenal gland                         TRUE               11
artery aorta                          TRUE               12
artery coronary                       TRUE               11
artery tibial                         TRUE               12
brain amygdala                        TRUE                8
brain anterior cingulate cortex ba24  TRUE                9
brain caudate basal ganglia           TRUE               10
brain cerebellar hemisphere           TRUE               10
brain cerebellum                      TRUE               10
brain cortex                          TRUE               11
brain frontal cortex ba9              TRUE                8
brain hippocampus                     TRUE               10
brain hypothalamus                    TRUE               10
brain nucleus accumbens basal ganglia TRUE               11
brain putamen basal ganglia           TRUE                9
brain spinal cord cervical c 1        TRUE                8
brain substantia nigra                TRUE                8
breast mammary tissue                 TRUE               12
cells cultured fibroblasts            TRUE               12
cells ebv transformed lymphocytes     TRUE                9
colon sigmoid                         TRUE               12
colon transverse                      TRUE               11
esophagus gastroesophageal junction   TRUE               12
esophagus mucosa                      TRUE               12
esophagus muscularis                  TRUE               12
heart atrial appendage                TRUE               12
heart left ventricle                  TRUE               12
kidney cortex                         TRUE                7
liver                                 TRUE               11
lung                                  TRUE               12
minor salivary gland                  TRUE               10
muscle skeletal                       TRUE               12
nerve tibial                          TRUE               12
ovary                                 TRUE                6
pancreas                              TRUE               11
pituitary                             TRUE               11
prostate                              TRUE                6
skin not sun exposed suprapubic       TRUE               12
skin sun exposed lower leg            TRUE               12
small intestine terminal ileum        TRUE               11
spleen                                TRUE               11
stomach                               TRUE               11
testis                                TRUE                6
thyroid                               TRUE               12
uterus                                TRUE                5
vagina                                TRUE                6
whole blood                           TRUE               12

In [5]:
run_gtex_tissue_ora <- function(genes, universe) {
    res <- tryCatch(
        clusterProfiler::enricher(
            gene          = genes,
            universe      = universe,
            TERM2GENE     = term2gene_df,
            pAdjustMethod = 'BH',
            pvalueCutoff  = 1,
            qvalueCutoff  = 1,
            minGSSize     = 10,
            maxGSSize     = 500
        ),
        error = function(e) NULL
    )
    if (is.null(res)) return(NULL)
    df <- as.data.frame(res)
    if (nrow(df) == 0) return(NULL)
    df
}

top_genes_per_lv <- lapply(colnames(Z), function(lv) {
    vals <- Z[, lv]
    universe_genes[order(vals, decreasing = TRUE)[seq_len(n_top_genes)]]
})
names(top_genes_per_lv) <- colnames(Z)

ora_list <- lapply(names(top_genes_per_lv), function(lv) {
    df <- run_gtex_tissue_ora(top_genes_per_lv[[lv]], universe_genes)
    if (is.null(df)) return(NULL)
    df$LV <- lv
    df
})

ora_all <- do.call(rbind, Filter(Negate(is.null), ora_list))
if (is.null(ora_all)) {
    ora_all <- data.frame()
} else {
    rownames(ora_all) <- NULL
    ora_all <- ora_all %>%
        dplyr::left_join(term_map, by = c('ID' = 'term')) %>%
        dplyr::select(LV, ID, Description, parsed_tissue, normalized_tissue,
                      GeneRatio, BgRatio, pvalue, p.adjust, qvalue, geneID, Count)
}

write.csv(ora_all, file.path(OUT_DIR, 'gtex_tissue_ora_per_lv.csv'), row.names = FALSE)
cat('ORA rows:', nrow(ora_all), '\n')
head(ora_all)

ORA rows: 32823

  LV    ID
1 LV263 GTEx_Tissues_Adipose - Subcutaneous Female 20-29 Up
2 LV263 GTEx_Tissues_Adipose - Subcutaneous Male 20-29 Up
3 LV263 GTEx_Tissues_Adipose - Subcutaneous Female 40-49 Up
4 LV263 GTEx_Tissues_Adipose - Visceral (Omentum) Female 20-29 Up
5 LV263 GTEx_Tissues_Adipose - Visceral (Omentum) Female 40-49 Up
6 LV263 GTEx_Tissues_Adipose - Subcutaneous Female 30-39 Up
  Description
1 GTEx_Tissues_Adipose - Subcutaneous Female 20-29 Up
2 GTEx_Tissues_Adipose - Subcutaneous Male 20-29 Up
3 GTEx_Tissues_Adipose - Subcutaneous Female 40-49 Up
4 GTEx_Tissues_Adipose - Visceral (Omentum) Female 20-29 Up
5 GTEx_Tissues_Adipose - Visceral (Omentum) Female 40-49 Up
6 GTEx_Tissues_Adipose - Subcutaneous Female 30-39 Up
  parsed_tissue                normalized_tissue        GeneRatio BgRatio
1 Adipose - Subcutaneous       adipose subcutaneous     44/155    98/6121
2 Adipose - Subcutaneous       adipose subcutaneous     42/155    99/6121
3 Adipose - Subcutaneous       adipose subcutaneous     41/155    95/6121
4 Adipose - Visceral (Omentum) adipose visceral omentum 40/155    97/6121
5 Adipose - Visceral (Omentum) adipose visceral omentum 32/155    64/6121
6 Adipose - Subcutaneous       adipose subcutaneous     34/155    95/6121
  pvalue       p.adjust     qvalue
1 4.397540e-46 1.319262e-43 1.222053e-43
2 1.274868e-42 1.912302e-40 1.771396e-40
3 5.818140e-42 5.818140e-40 5.389435e-40
4 6.273229e-40 4.704922e-38 4.358243e-38
5 2.756060e-35 1.653636e-33 1.531789e-33
6 2.396600e-31 1.198300e-29 1.110004e-29
  geneID
1 CIDEC/CIDEA/ADIPOQ/PLIN1/LGALS12/GPD1/LEP/GPAM/LIPE/GYG2/LPL/SCD/G0S2/PLIN4/SLC19A3/KLB/AQP7/SLC7A10/PDE3B/FABP4/PPARG/SLC29A4/MEST/ACVR1C/CEBPA/AGPAT2/GPBAR1/LVRN/AKR1C2/PNPLA2/NMB/PRKAR2B/CD36/TMEM132C/ACACB/RETSAT/CD300LG/RDH5/AIFM2/FAH/FAM89A/PECR/ABCD2/RBP7
2 CIDEC/CIDEA/ADIPOQ/PLIN1/LGALS12/GPD1/GPAM/LIPE/LPL/SCD/G0S2/PLIN4/SLC19A3/KLB/PRRT4/AQP7/PDE3B/FABP4/FASN/PPARG/WNT11/MEST/ACVR1C/CEBPA/AGPAT2/LVRN/AKR1C2/TIMP4/PNPLA2/TNMD/MGST1/PRKAR2B/CD36/TMEM132C/ACACB/RETSAT/CD300LG/AIFM2/FAM89A/ELMOD3/DTX1/RBP7
3 CIDEC/CIDEA/ADIPOQ/PLIN1/LGALS12/GPD1/LEP/LIPE/GYG2/LPL/G0S2/PLIN4/SLC19A3/KLB/AQP7/SLC7A10/PDE3B/FABP4/PPARG/SLC29A4/MEST/ACVR1C/CEBPA/AGPAT2/GPBAR1/LVRN/AKR1C2/TIMP4/PNPLA2/TNMD/MGST1/PRKAR2B/CD36/TMEM132C/ACACB/RETSAT/CD300LG/RDH5/AIFM2/FAM89A/ELMOD3
4 CIDEC/CIDEA/ADIPOQ/PLIN1/LGALS12/GPD1/GPAM/LIPE/GYG2/LPL/G0S2/SLC19A3/MRAP/KLB/PRRT4/AQP7/DGAT2/SLC7A10/FASN/PPARG/MEST/AGPAT2/GPBAR1/TIMP4/PNPLA2/NMB/PRKAR2B/TMEM132C/ACSL1/ACACB/RETSAT/RDH5/ALDH1L1/PC/NEURL2/AIFM2/FAH/FAM89A/HAS1/MDFI
5 ADIPOQ/THRSP/LGALS12/GPAM/GYG2/LPL/SCD/PRRT4/AQP7/DGAT2/SLC7A10/FABP4/FASN/PPARG/MEST/AGPAT2/TIMP4/PNPLA2/NMB/PRKAR2B/ITLN1/CD36/PRG4/ELOVL6/ALOX15/AIFM2/UPK3B/FAM89A/HAS1/CD209/MSLN/ME1
6 CIDEC/CIDEA/ADIPOQ/PLIN1/GPD1/LEP/LIPE/GYG2/LPL/PLIN4/SLC19A3/KLB/AQP7/PDE3B/FABP4/PPARG/ACVR1C/AGPAT2/LVRN/TIMP4/PNPLA2/TNMD/PRKAR2B/CD36/TMEM132C/ACACB/RETSAT/CD300LG/RDH5/AIFM2/FAH/ELMOD3/ZNF117/ABCD2
  Count
1 44
2 42
3 41
4 40
5 32
6 34

In [6]:
run_alignment_summary <- function(selected_lvs, ora_all, out_dir) {
    dir.create(out_dir, recursive = TRUE, showWarnings = FALSE)
    sig_ora <- ora_all %>% dplyr::filter(LV %in% selected_lvs$LV, p.adjust < FDR_THRESH)

    detail <- selected_lvs %>%
        dplyr::rowwise() %>%
        dplyr::mutate(
            normalized_true_tissue = normalize_text(Tissue),
            n_sig_terms = sum(sig_ora$LV == LV),
            n_true_terms = sum(sig_ora$LV == LV & sig_ora$normalized_tissue == normalized_true_tissue),
            tissue_correct = n_true_terms > 0,
            best_any_padj = {
                x <- sig_ora$p.adjust[sig_ora$LV == LV]
                if (length(x) == 0) NA_real_ else min(x, na.rm = TRUE)
            },
            best_true_padj = {
                x <- sig_ora$p.adjust[sig_ora$LV == LV & sig_ora$normalized_tissue == normalized_true_tissue]
                if (length(x) == 0) NA_real_ else min(x, na.rm = TRUE)
            },
            matched_terms = paste(sig_ora$ID[sig_ora$LV == LV & sig_ora$normalized_tissue == normalized_true_tissue], collapse = ' | ')
        ) %>%
        dplyr::ungroup()

    tissue_summary <- detail %>%
        dplyr::group_by(Tissue) %>%
        dplyr::summarise(
            n_selected_lvs = dplyr::n(),
            tissue_correct = any(tissue_correct),
            correct_lvs = paste(LV[tissue_correct], collapse = ';'),
            best_true_padj = if (all(is.na(best_true_padj))) NA_real_ else min(best_true_padj, na.rm = TRUE),
            .groups = 'drop'
        ) %>%
        dplyr::mutate(correct_score = as.integer(tissue_correct))

    final_pct_tissue_correct <- 100 * mean(tissue_summary$tissue_correct)
    final_summary <- data.frame(
        n_tissues = nrow(tissue_summary),
        n_tissues_correct = sum(tissue_summary$tissue_correct),
        pct_tissue_correct = final_pct_tissue_correct,
        stringsAsFactors = FALSE
    )

    write.csv(detail, file.path(out_dir, 'gtex_global_alignment_detail.csv'), row.names = FALSE)
    write.csv(tissue_summary, file.path(out_dir, 'gtex_global_alignment_summary.csv'), row.names = FALSE)
    write.csv(final_summary, file.path(out_dir, 'gtex_global_alignment_final_pct.csv'), row.names = FALSE)

    list(detail = detail, tissue_summary = tissue_summary, final_summary = final_summary)
}

results <- lapply(names(selections), function(nm) {
    run_alignment_summary(selections[[nm]], ora_all, file.path(OUT_DIR, nm))
})
names(results) <- names(selections)

dplyr::bind_rows(lapply(names(results), function(nm) {
    results[[nm]]$final_summary %>% dplyr::mutate(analysis = nm, .before = 1)
}))

  analysis     n_tissues n_tissues_correct pct_tissue_correct
1 top1         49        43                 87.7551
2 cumulative25 49        49                100.0000

In [7]:
cat('--- top1 ---\n')
results$top1$tissue_summary %>% dplyr::arrange(Tissue)

cat('--- cumulative25 ---\n')
results$cumulative25$tissue_summary %>% dplyr::arrange(Tissue)

--- top1 ---

   Tissue                                    n_selected_lvs tissue_correct
1  Adipose - Subcutaneous                    1               TRUE
2  Adipose - Visceral (Omentum)              1               TRUE
3  Adrenal Gland                             1               TRUE
4  Artery - Aorta                            1               TRUE
5  Artery - Coronary                         1               TRUE
6  Artery - Tibial                           1               TRUE
7  Brain - Amygdala                          1               TRUE
8  Brain - Anterior cingulate cortex (BA24)  1               TRUE
9  Brain - Caudate (basal ganglia)           1               TRUE
10 Brain - Cerebellar Hemisphere             1               TRUE
11 Brain - Cerebellum                        1               TRUE
12 Brain - Cortex                            1               TRUE
13 Brain - Frontal Cortex (BA9)              1               TRUE
14 Brain - Hippocampus                       1               TRUE
15 Brain - Hypothalamus                      1               TRUE
16 Brain - Nucleus accumbens (basal ganglia) 1               TRUE
17 Brain - Putamen (basal ganglia)           1              FALSE
18 Brain - Spinal cord (cervical c-1)        1               TRUE
19 Brain - Substantia nigra                  1               TRUE
20 Breast - Mammary Tissue                   1               TRUE
21 Cells - Cultured fibroblasts              1               TRUE
22 Cells - EBV-transformed lymphocytes       1              FALSE
23 Colon - Sigmoid                           1               TRUE
24 Colon - Transverse                        1              FALSE
25 Esophagus - Gastroesophageal Junction     1               TRUE
26 Esophagus - Mucosa                        1               TRUE
27 Esophagus - Muscularis                    1              FALSE
28 Heart - Atrial Appendage                  1               TRUE
29 Heart - Left Ventricle                    1               TRUE
30 Kidney - Cortex                           1               TRUE
31 Liver                                     1               TRUE
32 Lung                                      1               TRUE
33 Minor Salivary Gland                      1               TRUE
34 Muscle - Skeletal                         1               TRUE
35 Nerve - Tibial                            1               TRUE
36 Ovary                                     1               TRUE
37 Pancreas                                  1               TRUE
38 Pituitary                                 1              FALSE
39 Prostate                                  1               TRUE
40 Skin - Not Sun Exposed (Suprapubic)       1               TRUE
41 Skin - Sun Exposed (Lower leg)            1               TRUE
42 Small Intestine - Terminal Ileum          1               TRUE
43 Spleen                                    1               TRUE
44 Stomach                                   1               TRUE
45 Testis                                    1               TRUE
46 Thyroid                                   1               TRUE
47 Uterus                                    1               TRUE
48 Vagina                                    1               TRUE
49 Whole Blood                               1              FALSE
   correct_lvs best_true_padj correct_score
1  LV263        1.319262e-43  1
2  LV263        4.704922e-38  1
3  LV183        8.202318e-63  1
4  LV145        4.240123e-11  1
5  LV232        4.098348e-03  1
6  LV563        3.743852e-05  1
7  LV136        6.030062e-16  1
8  LV136        5.723977e-16  1
9  LV34         5.273289e-53  1
10 LV389        9.518569e-53  1
11 LV389        3.059920e-42  1
12 LV22         1.421669e-09  1
13 LV22         5.441160e-15  1
14 LV251        6.000277e-62  1
15 LV184        4.167897e-39  1
16 LV494        1.309771e-20  1
17                        NA  0
18 LV496        2.709827e-45  1
19 LV417        8.520121e-43  1
20 LV460        5.570628e-17  1
21 LV546        8.440805e-59  1
22                        NA  0
23 LV11         1.067369e-31  1
24                        NA  0
25 LV182        5.791689e-14  1
26 LV84         2.870356e-82  1
27                        NA  0
28 LV420        2.313830e-62  1
29 LV505        1.936986e-78  1
30 LV229        7.554957e-44  1
31 LV21         3.218226e-60  1
32 LV26         4.239296e-43  1
33 LV513        1.332381e-42  1
34 LV137       3.982113e-102  1
35 LV329        3.772609e-73  1
36 LV32         9.634315e-55  1
37 LV450       6.131498e-100  1
38                        NA  0
39 LV174        1.770945e-08  1
40 LV397        5.924138e-79  1
41 LV397       1.005622e-104  1
42 LV452        5.068922e-61  1
43 LV55         4.019871e-46  1
44 LV36         3.649967e-74  1
45 LV299        1.372607e-44  1
46 LV246        3.902118e-77  1
47 LV48         7.028383e-60  1
48 LV569        2.309602e-23  1
49                        NA  0

--- cumulative25 ---

   Tissue                                    n_selected_lvs tissue_correct
1  Adipose - Subcutaneous                    6              TRUE
2  Adipose - Visceral (Omentum)              5              TRUE
3  Adrenal Gland                             2              TRUE
4  Artery - Aorta                            3              TRUE
5  Artery - Coronary                         4              TRUE
6  Artery - Tibial                           4              TRUE
7  Brain - Amygdala                          4              TRUE
8  Brain - Anterior cingulate cortex (BA24)  6              TRUE
9  Brain - Caudate (basal ganglia)           8              TRUE
10 Brain - Cerebellar Hemisphere             9              TRUE
11 Brain - Cerebellum                        8              TRUE
12 Brain - Cortex                            4              TRUE
13 Brain - Frontal Cortex (BA9)              6              TRUE
14 Brain - Hippocampus                       7              TRUE
15 Brain - Hypothalamus                      5              TRUE
16 Brain - Nucleus accumbens (basal ganglia) 7              TRUE
17 Brain - Putamen (basal ganglia)           9              TRUE
18 Brain - Spinal cord (cervical c-1)        5              TRUE
19 Brain - Substantia nigra                  8              TRUE
20 Breast - Mammary Tissue                   5              TRUE
21 Cells - Cultured fibroblasts              4              TRUE
22 Cells - EBV-transformed lymphocytes       5              TRUE
23 Colon - Sigmoid                           3              TRUE
24 Colon - Transverse                        6              TRUE
25 Esophagus - Gastroesophageal Junction     6              TRUE
26 Esophagus - Mucosa                        3              TRUE
27 Esophagus - Muscularis                    3              TRUE
28 Heart - Atrial Appendage                  3              TRUE
29 Heart - Left Ventricle                    6              TRUE
30 Kidney - Cortex                           3              TRUE
31 Liver                                     4              TRUE
32 Lung                                      2              TRUE
33 Minor Salivary Gland                      3              TRUE
34 Muscle - Skeletal                         3              TRUE
35 Nerve - Tibial                            2              TRUE
36 Ovary                                     4              TRUE
37 Pancreas                                  2              TRUE
38 Pituitary                                 5              TRUE
39 Prostate                                  4              TRUE
40 Skin - Not Sun Exposed (Suprapubic)       5              TRUE
41 Skin - Sun Exposed (Lower leg)            5              TRUE
42 Small Intestine - Terminal Ileum          7              TRUE
43 Spleen                                    3              TRUE
44 Stomach                                   4              TRUE
45 Testis                                    3              TRUE
46 Thyroid                                   1              TRUE
47 Uterus                                    4              TRUE
48 Vagina                                    4              TRUE
49 Whole Blood                               4              TRUE
   correct_lvs                                         best_true_padj
1  LV263;LV369;LV5;LV460;LV106;LV68                     1.319262e-43
2  LV263;LV460;LV151;LV127;LV106                        4.704922e-38
3  LV183;LV3                                            8.202318e-63
4  LV145;LV531;LV37                                     1.966264e-45
5  LV232;LV106;LV40;LV99                                6.061080e-12
6  LV563;LV90;LV37;LV387                                7.034525e-35
7  LV136;LV121;LV188;LV194                              3.109316e-38
8  LV136;LV24;LV121;LV2;LV85;LV164                      1.650848e-56
9  LV34;LV51;LV44;LV328;LV155;LV230;LV54;LV169          5.273289e-53
10 LV389;LV535;LV505;LV2;LV445;LV123;LV230;LV251;LV155  9.518569e-53
11 LV389;LV230;LV505;LV123;LV98;LV547;LV2;LV445         3.059920e-42
12 LV22;LV2;LV24;LV121                                  9.845530e-32
13 LV22;LV24;LV2;LV164;LV295;LV61                       7.012189e-47
14 LV251;LV121;LV34;LV3;LV329;LV230;LV417               6.000277e-62
15 LV184;LV24;LV34;LV54;LV101                           4.167897e-39
16 LV494;LV328;LV51;LV24;LV453;LV429;LV169              5.063010e-24
17 LV164;LV34;LV230;LV51;LV328;LV155;LV86;LV61;LV169    5.273289e-53
18 LV496;LV417;LV103;LV368;LV329                        2.709827e-45
19 LV417;LV329;LV34;LV3;LV496;LV535;LV5;LV230           8.520121e-43
20 LV460;LV554;LV31;LV208;LV93                          3.714383e-39
21 LV546;LV91;LV363;LV137                               8.440805e-59
22 LV547;LV574;LV21;LV378;LV123                         1.084564e-27
23 LV11;LV322;LV142                                     4.075975e-58
24 LV246;LV452;LV32;LV11;LV25;LV142                     1.286378e-36
25 LV182;LV174;LV142;LV11;LV246;LV57                    2.677078e-43
26 LV84;LV330;LV81                                      2.870356e-82
27 LV11;LV313;LV42                                      9.909614e-26
28 LV420;LV505;LV509                                    1.692963e-64
29 LV505;LV554;LV76;LV9;LV203;LV137                     1.936986e-78
30 LV229;LV50;LV422                                     2.475097e-72
31 LV21;LV59;LV471;LV455                                8.797514e-81
32 LV26;LV208                                           4.239296e-43
33 LV513;LV58;LV99                                      5.033542e-64
34 LV137;LV68;LV535                                    3.982113e-102
35 LV329;LV128                                          3.772609e-73
36 LV32;LV330;LV3;LV110                                 9.634315e-55
37 LV450;LV25                                          6.131498e-100
38 LV322;LV105;LV230;LV164;LV142                        4.177685e-31
39 LV174;LV152;LV559;LV38                               8.802874e-70
40 LV397;LV31;LV48;LV5;LV113                            5.924138e-79
41 LV397;LV31;LV113;LV132;LV48                         1.005622e-104
42 LV452;LV25;LV197;LV277;LV368;LV65;LV395              5.518370e-64
43 LV55;LV26;LV183                                      4.019871e-46
44 LV36;LV227;LV103;LV175                               7.782182e-75
45 LV299;LV84;LV134                                     1.372607e-44
46 LV246                                                3.902118e-77
47 LV48;LV174;LV32;LV324                                7.028383e-60
48 LV569;LV80;LV330;LV414                               1.655981e-51
49 LV546;LV570;LV238;LV93                               5.688445e-81
   correct_score
1  1
2  1
3  1
4  1
5  1
6  1
7  1
8  1
9  1
10 1
11 1
12 1
13 1
14 1
15 1
16 1
17 1
18 1
19 1
20 1
21 1
22 1
23 1
24 1
25 1
26 1
27 1
28 1
29 1
30 1
31 1
32 1
33 1
34 1
35 1
36 1
37 1
38 1
39 1
40 1
41 1
42 1
43 1
44 1
45 1
46 1
47 1
48 1
49 1

In [8]:
detail_cols <- c('Tissue', 'LV', 'Rank', 'Mean_SHAP_Tissue', 'Cumulative_Percent',
                 'tissue_correct', 'n_sig_terms', 'n_true_terms',
                 'best_true_padj', 'matched_terms')

cat('--- top1 ---\n')
results$top1$detail %>% dplyr::select(dplyr::all_of(detail_cols)) %>% dplyr::arrange(Tissue, Rank)

cat('--- cumulative25 ---\n')
results$cumulative25$detail %>% dplyr::select(dplyr::all_of(detail_cols)) %>% dplyr::arrange(Tissue, Rank)

--- top1 ---

   Tissue                                    LV    Rank Mean_SHAP_Tissue
1  Adipose - Subcutaneous                    LV263 1    0.05842972
2  Adipose - Visceral (Omentum)              LV263 1    0.06652897
3  Adrenal Gland                             LV183 1    0.14297289
4  Artery - Aorta                            LV145 1    0.14942737
5  Artery - Coronary                         LV232 1    0.08830223
6  Artery - Tibial                           LV563 1    0.07735856
7  Brain - Amygdala                          LV136 1    0.11450020
8  Brain - Anterior cingulate cortex (BA24)  LV136 1    0.04595210
9  Brain - Caudate (basal ganglia)           LV34  1    0.05161969
10 Brain - Cerebellar Hemisphere             LV389 1    0.04443835
11 Brain - Cerebellum                        LV389 1    0.07681372
12 Brain - Cortex                            LV22  1    0.07801118
13 Brain - Frontal Cortex (BA9)              LV22  1    0.05741928
14 Brain - Hippocampus                       LV251 1    0.06561834
15 Brain - Hypothalamus                      LV184 1    0.10558176
16 Brain - Nucleus accumbens (basal ganglia) LV494 1    0.05084869
17 Brain - Putamen (basal ganglia)           LV164 1    0.04185705
18 Brain - Spinal cord (cervical c-1)        LV496 1    0.10183653
19 Brain - Substantia nigra                  LV417 1    0.04082893
20 Breast - Mammary Tissue                   LV460 1    0.05550369
21 Cells - Cultured fibroblasts              LV546 1    0.10969210
22 Cells - EBV-transformed lymphocytes       LV547 1    0.06791743
23 Colon - Sigmoid                           LV11  1    0.11890314
24 Colon - Transverse                        LV246 1    0.04432739
25 Esophagus - Gastroesophageal Junction     LV182 1    0.05770329
26 Esophagus - Mucosa                        LV84  1    0.15000958
27 Esophagus - Muscularis                    LV11  1    0.09582216
28 Heart - Atrial Appendage                  LV420 1    0.14167681
29 Heart - Left Ventricle                    LV505 1    0.07759629
30 Kidney - Cortex                           LV229 1    0.12751901
31 Liver                                     LV21  1    0.08286900
32 Lung                                      LV26  1    0.17002458
33 Minor Salivary Gland                      LV513 1    0.09481107
34 Muscle - Skeletal                         LV137 1    0.11959354
35 Nerve - Tibial                            LV329 1    0.20941674
36 Ovary                                     LV32  1    0.08968365
37 Pancreas                                  LV450 1    0.13247294
38 Pituitary                                 LV322 1    0.07195086
39 Prostate                                  LV174 1    0.10032874
40 Skin - Not Sun Exposed (Suprapubic)       LV397 1    0.07578869
41 Skin - Sun Exposed (Lower leg)            LV397 1    0.06031304
42 Small Intestine - Terminal Ileum          LV452 1    0.08023270
43 Spleen                                    LV55  1    0.11321532
44 Stomach                                   LV36  1    0.07410646
45 Testis                                    LV299 1    0.13806802
46 Thyroid                                   LV246 1    0.22655227
47 Uterus                                    LV48  1    0.11479517
48 Vagina                                    LV569 1    0.09296303
49 Whole Blood                               LV546 1    0.07421132
   Cumulative_Percent tissue_correct n_sig_terms n_true_terms best_true_padj
1   6.549590           TRUE          30          12            1.319262e-43
2   7.420449           TRUE          30          12            4.704922e-38
3  14.913246           TRUE          11          11            8.202318e-63
4  15.904544           TRUE          20          11            4.240123e-11
5   9.612166           TRUE          24           7            4.098348e-03
6   8.249628           TRUE          14          11            3.743852e-05
7  12.766679           TRUE          40           8            6.030062e-16
8   5.190586           TRUE          40           9            5.723977e-16
9   5.778310           TRUE          32          10            5.273289e-53
10  4.819995           TRUE          20          10            9.518569e-53
11  8.212689           TRUE          20          10            3.059920e-42
12  8.471785           TRUE          27          11            1.421669e-09
13  6.432283           TRUE          27           8            5.441160e-15
14  7.452930           TRUE          60           9            6.000277e-62
15 11.921840           TRUE          33           9            4.167897e-39
16  5.714900           TRUE          44          11            1.309771e-20
17  4.699289          FALSE           5           0                      NA
18 11.030734           TRUE          12           8            2.709827e-45
19  4.657874           TRUE          29           8            8.520121e-43
20  6.405835           TRUE          32           8            5.570628e-17
21 11.367536           TRUE          12          12            8.440805e-59
22  6.827435          FALSE           2           0                      NA
23 13.649070           TRUE          28          12            1.067369e-31
24  5.205252          FALSE          13           0                      NA
25  6.650232           TRUE          46          11            5.791689e-14
26 15.475565           TRUE          20          12            2.870356e-82
27 10.466040          FALSE          28           0                      NA
28 14.795453           TRUE          36          12            2.313830e-62
29  8.102165           TRUE          24          12            1.936986e-78
30 13.604549           TRUE          23           7            7.554957e-44
31  8.483334           TRUE          14          11            3.218226e-60
32 17.855873           TRUE          12          12            4.239296e-43
33 10.124788           TRUE          15          10            1.332381e-42
34 12.573999           TRUE          21          12           3.982113e-102
35 22.229819           TRUE          20          12            3.772609e-73
36  9.350741           TRUE           6           6            9.634315e-55
37 13.888514           TRUE          21          11           6.131498e-100
38  7.358033          FALSE          36           0                      NA
39 10.677973           TRUE          27           6            1.770945e-08
40  8.741476           TRUE          31          12            5.924138e-79
41  6.878730           TRUE          31          12           1.005622e-104
42  8.930474           TRUE          59          10            5.068922e-61
43 11.696234           TRUE          15          11            4.019871e-46
44  8.158157           TRUE          24          11            3.649967e-74
45 14.108817           TRUE           6           6            1.372607e-44
46 25.552691           TRUE          13          12            3.902118e-77
47 12.526431           TRUE          17           5            7.028383e-60
48 10.536830           TRUE          18           6            2.309602e-23
49  7.836033          FALSE          12           0                      NA
   matched_terms
1  GTEx_Tissues_Adipose - Subcutaneous Female 20-29 Up | GTEx_Tissues_Adipose - Subcutaneous Male 20-29 Up | GTEx_Tissues_Adipose - Subcutaneous Female 40-49 Up | GTEx_Tissues_Adipose - Subcutaneous Female 30-39 Up | GTEx_Tissues_Adipose - Subcutaneous Female 60-69 Up | GTEx_Tissues_Adipose - Subcutaneous Female 70-79 Up | GTEx_Tissues_Adipose - Subcutaneous Male 70-79 Up | GTEx_Tissues_Adipose - Subcutaneous Female 50-59 Up | GTEx_Tissues_Adipose - Subcutaneous Male 30-39 Up | GTEx_Tissues_Adipose - Subcutaneous Male 40-49 Up | GTEx_Tissues_Adipose - Subcutaneous Male 50-59 Up | GTEx_Tissues_Adipose - Subcutaneous Male 60-69 Up
2  GTEx_Tissues_Adipose - Visceral (Omentum) Female 20-29 Up | GTEx_Tissues_Adipose - Visceral (Omentum) Female 40-49 Up | GTEx_Tissues_Adipose - Visceral (Omentum) Female 30-39 Up | GTEx_Tissues_Adipose - Visceral (Omentum) Male 50-59 Up | GTEx_Tissues_Adipose - Visceral (Omentum) Female 70-79 Up | GTEx_Tissues_Adipose - Visceral (Omentum) Male 40-49 Up | GTEx_Tissues_Adipose - Visceral (Omentum) Female 50-59 Up | GTEx_Tissues_Adipose - Visceral (Omentum) Male 30-39 Up | GTEx_Tissues_Adipose - Visceral (Omentum) Female 60-69 Up | GTEx_Tissues_Adipose - Visceral (Omentum) Male 20-29 Up | GTEx_Tissues_Adipose - Visceral (Omentum) Male 60-69 Up | GTEx_Tissues_Adipose - Visceral (Omentum) Male 70-79 Up
3  GTEx_Tissues_Adrenal Gland Male 40-49 Up | GTEx_Tissues_Adrenal Gland Male 50-59 Up | GTEx_Tissues_Adrenal Gland Male 20-29 Up | GTEx_Tissues_Adrenal Gland Female 20-29 Up | GTEx_Tissues_Adrenal Gland Female 60-69 Up | GTEx_Tissues_Adrenal Gland Male 60-69 Up | GTEx_Tissues_Adrenal Gland Female 40-49 Up | GTEx_Tissues_Adrenal Gland Male 30-39 Up | GTEx_Tissues_Adrenal Gland Female 30-39 Up | GTEx_Tissues_Adrenal Gland Female 50-59 Up | GTEx_Tissues_Adrenal Gland Male 70-79 Up
4  GTEx_Tissues_Artery - Aorta Female 20-29 Up | GTEx_Tissues_Artery - Aorta Male 20-29 Up | GTEx_Tissues_Artery - Aorta Female 30-39 Up | GTEx_Tissues_Artery - Aorta Male 40-49 Up | GTEx_Tissues_Artery - Aorta Male 30-39 Up | GTEx_Tissues_Artery - Aorta Female 40-49 Up | GTEx_Tissues_Artery - Aorta Male 70-79 Up | GTEx_Tissues_Artery - Aorta Female 50-59 Up | GTEx_Tissues_Artery - Aorta Female 60-69 Up | GTEx_Tissues_Artery - Aorta Male 50-59 Up | GTEx_Tissues_Artery - Aorta Male 60-69 Up
5  GTEx_Tissues_Artery - Coronary Male 50-59 Up | GTEx_Tissues_Artery - Coronary Male 60-69 Up | GTEx_Tissues_Artery - Coronary Male 30-39 Up | GTEx_Tissues_Artery - Coronary Female 50-59 Up | GTEx_Tissues_Artery - Coronary Male 40-49 Up | GTEx_Tissues_Artery - Coronary Male 70-79 Up | GTEx_Tissues_Artery - Coronary Male 20-29 Up
6  GTEx_Tissues_Artery - Tibial Female 30-39 Up | GTEx_Tissues_Artery - Tibial Male 20-29 Up | GTEx_Tissues_Artery - Tibial Female 40-49 Up | GTEx_Tissues_Artery - Tibial Male 40-49 Up | GTEx_Tissues_Artery - Tibial Female 20-29 Up | GTEx_Tissues_Artery - Tibial Male 30-39 Up | GTEx_Tissues_Artery - Tibial Female 70-79 Up | GTEx_Tissues_Artery - Tibial Male 60-69 Up | GTEx_Tissues_Artery - Tibial Male 50-59 Up | GTEx_Tissues_Artery - Tibial Male 70-79 Up | GTEx_Tissues_Artery - Tibial Female 50-59 Up
7  GTEx_Tissues_Brain - Amygdala Female 40-49 Up | GTEx_Tissues_Brain - Amygdala Male 40-49 Up | GTEx_Tissues_Brain - Amygdala Male 20-29 Up | GTEx_Tissues_Brain - Amygdala Female 60-69 Up | GTEx_Tissues_Brain - Amygdala Male 50-59 Up | GTEx_Tissues_Brain - Amygdala Male 60-69 Up | GTEx_Tissues_Brain - Amygdala Male 70-79 Up | GTEx_Tissues_Brain - Amygdala Female 50-59 Up
8  GTEx_Tissues_Brain - Anterior Cingulate Cortex (BA24) Female 50-59 Up | GTEx_Tissues_Brain - Anterior Cingulate Cortex (BA24) Female 20-29 Up | GTEx_Tissues_Brain - Anterior Cingulate Cortex (BA24) Female 40-49 Up | GTEx_Tissues_Brain - Anterior Cingulate Cortex (BA24) Male 40-49 Up | GTEx_Tissues_Brain - Anterior Cingulate Cortex (BA24) Male 60-69 Up | GTEx_Tissues_Brain - Anterior Cingulate Cortex (BA24) Male 50-59 Up | GTEx_Tissues_Brain - Anterior Cingulate Cortex (BA24) Male 70-79 Up | GTEx_Tissues_Brain - Anterior Cingulate Cortex (BA24) Male 30-39 Up | GTEx_Tissues_Brain - Anterior Cingulate Cortex (BA24) Female 60-69 Up
9  GTEx_Tissues_Brain - Caudate (Basal Ganglia) Male 30-39 Up | GTEx_Tissues_Brain - Caudate (Basal Ganglia) Female 20-29 Up | GTEx_Tissues_Brain - Caudate (Basal Ganglia) Male 50-59 Up | GTEx_Tissues_Brain - Caudate (Basal Ganglia) Male 60-69 Up | GTEx_Tissues_Brain - Caudate (Basal Ganglia) Male 40-49 Up | GTEx_Tissues_Brain - Caudate (Basal Ganglia) Male 70-79 Up | GTEx_Tissues_Brain - Caudate (Basal Ganglia) Female 40-49 Up | GTEx_Tissues_Brain - Caudate (Basal Ganglia) Female 50-59 Up | GTEx_Tissues_Brain - Caudate (Basal Ganglia) Female 60-69 Up | GTEx_Tissues_Brain - Caudate (Basal Ganglia) Female 70-79 Up
10 GTEx_Tissues_Brain - Cerebellar Hemisphere Male 70-79 Up | GTEx_Tissues_Brain - Cerebellar Hemisphere Male 40-49 Up | GTEx_Tissues_Brain - Cerebellar Hemisphere Female 60-69 Up | GTEx_Tissues_Brain - Cerebellar Hemisphere Male 60-69 Up | GTEx_Tissues_Brain - Cerebellar Hemisphere Male 50-59 Up | GTEx_Tissues_Brain - Cerebellar Hemisphere Female 50-59 Up | GTEx_Tissues_Brain - Cerebellar Hemisphere Female 40-49 Up | GTEx_Tissues_Brain - Cerebellar Hemisphere Female 20-29 Up | GTEx_Tissues_Brain - Cerebellar Hemisphere Male 20-29 Up | GTEx_Tissues_Brain - Cerebellar Hemisphere Male 30-39 Up
11 GTEx_Tissues_Brain - Cerebellum Female 30-39 Up | GTEx_Tissues_Brain - Cerebellum Female 40-49 Up | GTEx_Tissues_Brain - Cerebellum Male 40-49 Up | GTEx_Tissues_Brain - Cerebellum Male 60-69 Up | GTEx_Tissues_Brain - Cerebellum Female 50-59 Up | GTEx_Tissues_Brain - Cerebellum Male 50-59 Up | GTEx_Tissues_Brain - Cerebellum Female 60-69 Up | GTEx_Tissues_Brain - Cerebellum Male 20-29 Up | GTEx_Tissues_Brain - Cerebellum Male 70-79 Up | GTEx_Tissues_Brain - Cerebellum Male 30-39 Up
12 GTEx_Tissues_Brain - Cortex Male 40-49 Up | GTEx_Tissues_Brain - Cortex Female 50-59 Up | GTEx_Tissues_Brain - Cortex Male 50-59 Up | GTEx_Tissues_Brain - Cortex Male 30-39 Up | GTEx_Tissues_Brain - Cortex Female 20-29 Up | GTEx_Tissues_Brain - Cortex Female 60-69 Up | GTEx_Tissues_Brain - Cortex Male 70-79 Up | GTEx_Tissues_Brain - Cortex Male 20-29 Up | GTEx_Tissues_Brain - Cortex Female 40-49 Up | GTEx_Tissues_Brain - Cortex Male 60-69 Up | GTEx_Tissues_Brain - Cortex Female 70-79 Up
13 GTEx_Tissues_Brain - Frontal Cortex (BA9) Female 50-59 Up | GTEx_Tissues_Brain - Frontal Cortex (BA9) Male 60-69 Up | GTEx_Tissues_Brain - Frontal Cortex (BA9) Female 40-49 Up | GTEx_Tissues_Brain - Frontal Cortex (BA9) Male 50-59 Up | GTEx_Tissues_Brain - Frontal Cortex (BA9) Male 40-49 Up | GTEx_Tissues_Brain - Frontal Cortex (BA9) Female 60-69 Up | GTEx_Tissues_Brain - Frontal Cortex (BA9) Male 70-79 Up | GTEx_Tissues_Brain - Frontal Cortex (BA9) Male 20-29 Up
14 GTEx_Tissues_Brain - Hippocampus Female 40-49 Up | GTEx_Tissues_Brain - Hippocampus Male 20-29 Up | GTEx_Tissues_Brain - Hippocampus Male 50-59 Up | GTEx_Tissues_Brain - Hippocampus Female 50-59 Up | GTEx_Tissues_Brain - Hippocampus Male 30-39 Up | GTEx_Tissues_Brain - Hippocampus Male 60-69 Up | GTEx_Tissues_Brain - Hippocampus Male 40-49 Up | GTEx_Tissues_Brain - Hippocampus Male 70-79 Up | GTEx_Tissues_Brain - Hippocampus Female 60-69 Up
15 GTEx_Tissues_Brain - Hypothalamus Male 50-59 Up | GTEx_Tissues_Brain - Hypothalamus Male 60-69 Up | GTEx_Tissues_Brain - Hypothalamus Male 40-49 Up | GTEx_Tissues_Brain - Hypothalamus Female 60-69 Up | GTEx_Tissues_Brain - Hypothalamus Male 70-79 Up | GTEx_Tissues_Brain - Hypothalamus Female 50-59 Up | GTEx_Tissues_Brain - Hypothalamus Female 40-49 Up | GTEx_Tissues_Brain - Hypothalamus Male 30-39 Up | GTEx_Tissues_Brain - Hypothalamus Male 20-29 Up
16 GTEx_Tissues_Brain - Nucleus Accumbens (Basal Ganglia) Male 50-59 Up | GTEx_Tissues_Brain - Nucleus Accumbens (Basal Ganglia) Female 50-59 Up | GTEx_Tissues_Brain - Nucleus Accumbens (Basal Ganglia) Male 60-69 Up | GTEx_Tissues_Brain - Nucleus Accumbens (Basal Ganglia) Male 30-39 Up | GTEx_Tissues_Brain - Nucleus Accumbens (Basal Ganglia) Female 40-49 Up | GTEx_Tissues_Brain - Nucleus Accumbens (Basal Ganglia) Female 20-29 Up | GTEx_Tissues_Brain - Nucleus Accumbens (Basal Ganglia) Male 70-79 Up | GTEx_Tissues_Brain - Nucleus Accumbens (Basal Ganglia) Male 20-29 Up | GTEx_Tissues_Brain - Nucleus Accumbens (Basal Ganglia) Male 40-49 Up | GTEx_Tissues_Brain - Nucleus Accumbens (Basal Ganglia) Female 60-69 Up | GTEx_Tissues_Brain - Nucleus Accumbens (Basal Ganglia) Female 70-79 Up
17
18 GTEx_Tissues_Brain - Spinal Cord (Cervical C-1) Male 20-29 Up | GTEx_Tissues_Brain - Spinal Cord (Cervical C-1) Male 70-79 Up | GTEx_Tissues_Brain - Spinal Cord (Cervical C-1) Female 40-49 Up | GTEx_Tissues_Brain - Spinal Cord (Cervical C-1) Female 50-59 Up | GTEx_Tissues_Brain - Spinal Cord (Cervical C-1) Male 50-59 Up | GTEx_Tissues_Brain - Spinal Cord (Cervical C-1) Male 60-69 Up | GTEx_Tissues_Brain - Spinal Cord (Cervical C-1) Female 60-69 Up | GTEx_Tissues_Brain - Spinal Cord (Cervical C-1) Male 40-49 Up
19 GTEx_Tissues_Brain - Substantia Nigra Male 40-49 Up | GTEx_Tissues_Brain - Substantia Nigra Female 40-49 Up | GTEx_Tissues_Brain - Substantia Nigra Female 60-69 Up | GTEx_Tissues_Brain - Substantia Nigra Male 60-69 Up | GTEx_Tissues_Brain - Substantia Nigra Male 50-59 Up | GTEx_Tissues_Brain - Substantia Nigra Female 50-59 Up | GTEx_Tissues_Brain - Substantia Nigra Male 20-29 Up | GTEx_Tissues_Brain - Substantia Nigra Male 70-79 Up
20 GTEx_Tissues_Breast - Mammary Tissue Male 30-39 Up | GTEx_Tissues_Breast - Mammary Tissue Male 40-49 Up | GTEx_Tissues_Breast - Mammary Tissue Male 20-29 Up | GTEx_Tissues_Breast - Mammary Tissue Female 70-79 Up | GTEx_Tissues_Breast - Mammary Tissue Male 70-79 Up | GTEx_Tissues_Breast - Mammary Tissue Male 60-69 Up | GTEx_Tissues_Breast - Mammary Tissue Male 50-59 Up | GTEx_Tissues_Breast - Mammary Tissue Female 30-39 Up
21 GTEx_Tissues_Cells - Cultured Fibroblasts Female 40-49 Up | GTEx_Tissues_Cells - Cultured Fibroblasts Male 50-59 Up | GTEx_Tissues_Cells - Cultured Fibroblasts Male 60-69 Up | GTEx_Tissues_Cells - Cultured Fibroblasts Male 40-49 Up | GTEx_Tissues_Cells - Cultured Fibroblasts Female 50-59 Up | GTEx_Tissues_Cells - Cultured Fibroblasts Male 20-29 Up | GTEx_Tissues_Cells - Cultured Fibroblasts Female 60-69 Up | GTEx_Tissues_Cells - Cultured Fibroblasts Male 30-39 Up | GTEx_Tissues_Cells - Cultured Fibroblasts Male 70-79 Up | GTEx_Tissues_Cells - Cultured Fibroblasts Female 30-39 Up | GTEx_Tissues_Cells - Cultured Fibroblasts Female 20-29 Up | GTEx_Tissues_Cells - Cultured Fibroblasts Female 70-79 Up
22
23 GTEx_Tissues_Colon - Sigmoid Female 40-49 Up | GTEx_Tissues_Colon - Sigmoid Male 40-49 Up | GTEx_Tissues_Colon - Sigmoid Male 20-29 Up | GTEx_Tissues_Colon - Sigmoid Male 30-39 Up | GTEx_Tissues_Colon - Sigmoid Male 50-59 Up | GTEx_Tissues_Colon - Sigmoid Female 60-69 Up | GTEx_Tissues_Colon - Sigmoid Female 50-59 Up | GTEx_Tissues_Colon - Sigmoid Female 20-29 Up | GTEx_Tissues_Colon - Sigmoid Male 60-69 Up | GTEx_Tissues_Colon - Sigmoid Female 30-39 Up | GTEx_Tissues_Colon - Sigmoid Female 70-79 Up | GTEx_Tissues_Colon - Sigmoid Male 70-79 Up
24
25 GTEx_Tissues_Esophagus - Gastroesophageal Junction Male 20-29 Up | GTEx_Tissues_Esophagus - Gastroesophageal Junction Male 30-39 Up | GTEx_Tissues_Esophagus - Gastroesophageal Junction Female 50-59 Up | GTEx_Tissues_Esophagus - Gastroesophageal Junction Female 30-39 Up | GTEx_Tissues_Esophagus - Gastroesophageal Junction Male 60-69 Up | GTEx_Tissues_Esophagus - Gastroesophageal Junction Male 40-49 Up | GTEx_Tissues_Esophagus - Gastroesophageal Junction Female 20-29 Up | GTEx_Tissues_Esophagus - Gastroesophageal Junction Male 50-59 Up | GTEx_Tissues_Esophagus - Gastroesophageal Junction Female 60-69 Up | GTEx_Tissues_Esophagus - Gastroesophageal Junction Female 40-49 Up | GTEx_Tissues_Esophagus - Gastroesophageal Junction Male 70-79 Up
26 GTEx_Tissues_Esophagus - Mucosa Male 40-49 Up | GTEx_Tissues_Esophagus - Mucosa Male 30-39 Up | GTEx_Tissues_Esophagus - Mucosa Male 50-59 Up | GTEx_Tissues_Esophagus - Mucosa Female 40-49 Up | GTEx_Tissues_Esophagus - Mucosa Male 20-29 Up | GTEx_Tissues_Esophagus - Mucosa Female 50-59 Up | GTEx_Tissues_Esophagus - Mucosa Female 20-29 Up | GTEx_Tissues_Esophagus - Mucosa Female 30-39 Up | GTEx_Tissues_Esophagus - Mucosa Female 60-69 Up | GTEx_Tissues_Esophagus - Mucosa Male 60-69 Up | GTEx_Tissues_Esophagus - Mucosa Female 70-79 Up | GTEx_Tissues_Esophagus - Mucosa Male 70-79 Up
27

--- cumulative25 ---

    Tissue                                   LV    Rank Mean_SHAP_Tissue
1   Adipose - Subcutaneous                   LV263 1    0.05842972
2   Adipose - Subcutaneous                   LV369 2    0.04485311
3   Adipose - Subcutaneous                   LV5   3    0.03934853
4   Adipose - Subcutaneous                   LV460 4    0.03714234
5   Adipose - Subcutaneous                   LV106 5    0.03528964
6   Adipose - Subcutaneous                   LV68  6    0.03014824
7   Adipose - Visceral (Omentum)             LV263 1    0.06652897
8   Adipose - Visceral (Omentum)             LV460 2    0.04684646
9   Adipose - Visceral (Omentum)             LV151 3    0.04355466
10  Adipose - Visceral (Omentum)             LV127 4    0.03561781
11  Adipose - Visceral (Omentum)             LV106 5    0.03444956
12  Adrenal Gland                            LV183 1    0.14297289
13  Adrenal Gland                            LV3   2    0.12072624
14  Artery - Aorta                           LV145 1    0.14942737
15  Artery - Aorta                           LV531 2    0.07685148
16  Artery - Aorta                           LV37  3    0.06615243
17  Artery - Coronary                        LV232 1    0.08830223
18  Artery - Coronary                        LV106 2    0.07543649
19  Artery - Coronary                        LV40  3    0.06522932
20  Artery - Coronary                        LV99  4    0.04594706
21  Artery - Tibial                          LV563 1    0.07735856
22  Artery - Tibial                          LV90  2    0.06921631
23  Artery - Tibial                          LV37  3    0.05900787
24  Artery - Tibial                          LV387 4    0.05695132
25  Brain - Amygdala                         LV136 1    0.11450020
26  Brain - Amygdala                         LV121 2    0.07222258
27  Brain - Amygdala                         LV188 3    0.02775137
28  Brain - Amygdala                         LV194 4    0.02312917
29  Brain - Anterior cingulate cortex (BA24) LV136 1    0.04595210
30  Brain - Anterior cingulate cortex (BA24) LV24  2    0.04055552
⋮   ⋮                                        ⋮     ⋮    ⋮
197 Small Intestine - Terminal Ileum         LV452 1    0.08023270
198 Small Intestine - Terminal Ileum         LV25  2    0.03337579
199 Small Intestine - Terminal Ileum         LV197 3    0.03100524
200 Small Intestine - Terminal Ileum         LV277 4    0.02323698
201 Small Intestine - Terminal Ileum         LV368 5    0.02308749
202 Small Intestine - Terminal Ileum         LV65  6    0.02202041
203 Small Intestine - Terminal Ileum         LV395 7    0.02024270
204 Spleen                                   LV55  1    0.11321532
205 Spleen                                   LV26  2    0.08679077
206 Spleen                                   LV183 3    0.07781769
207 Stomach                                  LV36  1    0.07410646
208 Stomach                                  LV227 2    0.07395956
209 Stomach                                  LV103 3    0.06439121
210 Stomach                                  LV175 4    0.05329318
211 Testis                                   LV299 1    0.13806802
212 Testis                                   LV84  2    0.06017041
213 Testis                                   LV134 3    0.05711730
214 Thyroid                                  LV246 1    0.22655227
215 Uterus                                   LV48  1    0.11479517
216 Uterus                                   LV174 2    0.05026691
217 Uterus                                   LV32  3    0.05022987
218 Uterus                                   LV324 4    0.04487831
219 Vagina                                   LV569 1    0.09296303
220 Vagina                                   LV80  2    0.07835380
221 Vagina                                   LV330 3    0.04837657
222 Vagina                                   LV414 4    0.04833402
223 Whole Blood                              LV546 1    0.07421132
224 Whole Blood                              LV570 2    0.06631000
225 Whole Blood                              LV238 3    0.06270082
226 Whole Blood                              LV93  4    0.04828852
    Cumulative_Percent tissue_correct n_sig_terms n_true_terms best_true_padj
1    6.549590           TRUE          30          12           1.319262e-43
2   11.577330           TRUE          35          12           5.596882e-10
3   15.988043          FALSE          29           0                     NA
4   20.151456           TRUE          32          12           2.481387e-22
5   24.107193          FALSE           0           0                     NA
6   27.486614          FALSE           6           0                     NA
7    7.420449           TRUE          30          12           4.704922e-38
8   12.645568           TRUE          32          12           5.681395e-20
9   17.503529           TRUE          19           4           4.384395e-09
10  21.476237          FALSE          26           0                     NA
11  25.318641          FALSE           0           0                     NA
12  14.913246           TRUE          11          11           8.202318e-63
13  27.505985           TRUE          17          11           7.146307e-56
14  15.904544           TRUE          20          11           4.240123e-11
15  24.084356          FALSE           9           0                     NA
16  31.125397           TRUE          36          12           1.966264e-45
17   9.612166           TRUE          24           7           4.098348e-03
18  17.823827          FALSE           0           0                     NA
19  24.924384           TRUE          39          10           6.061080e-12
20  29.925965          FALSE          32           0                     NA
21   8.249628           TRUE          14          11           3.743852e-05
22  15.630955           TRUE          35          12           3.205225e-04
23  21.923640           TRUE          36          12           1.358742e-18
24  27.997010           TRUE          56          12           7.034525e-35
25  12.766679           TRUE          40           8           6.030062e-16
26  20.819438           TRUE          66           8           3.109316e-38
27  23.913692          FALSE           7           0                     NA
28  26.492576          FALSE          13           0                     NA
29   5.190586           TRUE          40           9           5.723977e-16
30   9.771594           TRUE          34           4           1.871560e-04
⋮   ⋮                  ⋮              ⋮           ⋮            ⋮
197  8.930474           TRUE          59          10           5.068922e-61
198 12.645439           TRUE          34           7           1.624953e-03
199 16.096545           TRUE          35           6           2.735555e-04
200 18.682987          FALSE          42           0                     NA
201 21.252790           TRUE          32          10           1.752322e-22
202 23.703819           TRUE          26          10           5.518370e-64
203 25.956977          FALSE          31           0                     NA
204 11.696234           TRUE          15          11           4.019871e-46
205 20.662557          FALSE          12           0                     NA
206 28.701874          FALSE          11           0                     NA
207  8.158157           TRUE          24          11           3.649967e-74
208 16.300143           TRUE          12          11           7.782182e-75
209 23.388777           TRUE          23          11           5.058071e-11
210 29.255663           TRUE          32          11           3.895230e-69
211 14.108817           TRUE           6           6           1.372607e-44
212 20.257477          FALSE          20           0                     NA
213 26.094148          FALSE          16           0                     NA
214 25.552691           TRUE          13          12           3.902118e-77
215 12.526431           TRUE          17           5           7.028383e-60
216 18.011549           TRUE          27           5           4.227640e-17
217 23.492625          FALSE           6           0                     NA
218 28.389739          FALSE          35           0                     NA
219 10.536830           TRUE          18           6           2.309602e-23
220 19.417786           TRUE          51           6           1.655981e-51
221 24.900995           TRUE          35           6           1.875061e-10
222 30.379382          FALSE           0           0                     NA
223  7.836033          FALSE          12           0                     NA
224 14.837759           TRUE          12          12           5.688445e-81
225 21.458389          FALSE          12           0                     NA
226 26.557212          FALSE          24           0                     NA
    matched_terms
1   GTEx_Tissues_Adipose - Subcutaneous Female 20-29 Up | GTEx_Tissues_Adipose - Subcutaneous Male 20-29 Up | GTEx_Tissues_Adipose - Subcutaneous Female 40-49 Up | GTEx_Tissues_Adipose - Subcutaneous Female 30-39 Up | GTEx_Tissues_Adipose - Subcutaneous Female 60-69 Up | GTEx_Tissues_Adipose - Subcutaneous Female 70-79 Up | GTEx_Tissues_Adipose - Subcutaneous Male 70-79 Up | GTEx_Tissues_Adipose - Subcutaneous Female 50-59 Up | GTEx_Tissues_Adipose - Subcutaneous Male 30-39 Up | GTEx_Tissues_Adipose - Subcutaneous Male 40-49 Up | GTEx_Tissues_Adipose - Subcutaneous Male 50-59 Up | GTEx_Tissues_Adipose - Subcutaneous Male 60-69 Up
2   GTEx_Tissues_Adipose - Subcutaneous Male 50-59 Up | GTEx_Tissues_Adipose - Subcutaneous Male 60-69 Up | GTEx_Tissues_Adipose - Subcutaneous Female 60-69 Up | GTEx_Tissues_Adipose - Subcutaneous Male 40-49 Up | GTEx_Tissues_Adipose - Subcutaneous Male 20-29 Up | GTEx_Tissues_Adipose - Subcutaneous Male 30-39 Up | GTEx_Tissues_Adipose - Subcutaneous Female 50-59 Up | GTEx_Tissues_Adipose - Subcutaneous Female 40-49 Up | GTEx_Tissues_Adipose - Subcutaneous Female 70-79 Up | GTEx_Tissues_Adipose - Subcutaneous Female 30-39 Up | GTEx_Tissues_Adipose - Subcutaneous Male 70-79 Up | GTEx_Tissues_Adipose - Subcutaneous Female 20-29 Up
3
4   GTEx_Tissues_Adipose - Subcutaneous Male 20-29 Up | GTEx_Tissues_Adipose - Subcutaneous Female 40-49 Up | GTEx_Tissues_Adipose - Subcutaneous Female 30-39 Up | GTEx_Tissues_Adipose - Subcutaneous Male 30-39 Up | GTEx_Tissues_Adipose - Subcutaneous Male 50-59 Up | GTEx_Tissues_Adipose - Subcutaneous Female 60-69 Up | GTEx_Tissues_Adipose - Subcutaneous Female 50-59 Up | GTEx_Tissues_Adipose - Subcutaneous Female 20-29 Up | GTEx_Tissues_Adipose - Subcutaneous Male 70-79 Up | GTEx_Tissues_Adipose - Subcutaneous Male 40-49 Up | GTEx_Tissues_Adipose - Subcutaneous Female 70-79 Up | GTEx_Tissues_Adipose - Subcutaneous Male 60-69 Up
5
6
7   GTEx_Tissues_Adipose - Visceral (Omentum) Female 20-29 Up | GTEx_Tissues_Adipose - Visceral (Omentum) Female 40-49 Up | GTEx_Tissues_Adipose - Visceral (Omentum) Female 30-39 Up | GTEx_Tissues_Adipose - Visceral (Omentum) Male 50-59 Up | GTEx_Tissues_Adipose - Visceral (Omentum) Female 70-79 Up | GTEx_Tissues_Adipose - Visceral (Omentum) Male 40-49 Up | GTEx_Tissues_Adipose - Visceral (Omentum) Female 50-59 Up | GTEx_Tissues_Adipose - Visceral (Omentum) Male 30-39 Up | GTEx_Tissues_Adipose - Visceral (Omentum) Female 60-69 Up | GTEx_Tissues_Adipose - Visceral (Omentum) Male 20-29 Up | GTEx_Tissues_Adipose - Visceral (Omentum) Male 60-69 Up | GTEx_Tissues_Adipose - Visceral (Omentum) Male 70-79 Up
8   GTEx_Tissues_Adipose - Visceral (Omentum) Male 50-59 Up | GTEx_Tissues_Adipose - Visceral (Omentum) Male 40-49 Up | GTEx_Tissues_Adipose - Visceral (Omentum) Male 60-69 Up | GTEx_Tissues_Adipose - Visceral (Omentum) Male 70-79 Up | GTEx_Tissues_Adipose - Visceral (Omentum) Male 30-39 Up | GTEx_Tissues_Adipose - Visceral (Omentum) Female 40-49 Up | GTEx_Tissues_Adipose - Visceral (Omentum) Female 50-59 Up | GTEx_Tissues_Adipose - Visceral (Omentum) Female 30-39 Up | GTEx_Tissues_Adipose - Visceral (Omentum) Female 20-29 Up | GTEx_Tissues_Adipose - Visceral (Omentum) Male 20-29 Up | GTEx_Tissues_Adipose - Visceral (Omentum) Female 60-69 Up | GTEx_Tissues_Adipose - Visceral (Omentum) Female 70-79 Up
9   GTEx_Tissues_Adipose - Visceral (Omentum) Male 60-69 Up | GTEx_Tissues_Adipose - Visceral (Omentum) Male 70-79 Up | GTEx_Tissues_Adipose - Visceral (Omentum) Male 40-49 Up | GTEx_Tissues_Adipose - Visceral (Omentum) Male 50-59 Up
10
11
12  GTEx_Tissues_Adrenal Gland Male 40-49 Up | GTEx_Tissues_Adrenal Gland Male 50-59 Up | GTEx_Tissues_Adrenal Gland Male 20-29 Up | GTEx_Tissues_Adrenal Gland Female 20-29 Up | GTEx_Tissues_Adrenal Gland Female 60-69 Up | GTEx_Tissues_Adrenal Gland Male 60-69 Up | GTEx_Tissues_Adrenal Gland Female 40-49 Up | GTEx_Tissues_Adrenal Gland Male 30-39 Up | GTEx_Tissues_Adrenal Gland Female 30-39 Up | GTEx_Tissues_Adrenal Gland Female 50-59 Up | GTEx_Tissues_Adrenal Gland Male 70-79 Up
13  GTEx_Tissues_Adrenal Gland Male 50-59 Up | GTEx_Tissues_Adrenal Gland Female 40-49 Up | GTEx_Tissues_Adrenal Gland Female 60-69 Up | GTEx_Tissues_Adrenal Gland Female 50-59 Up | GTEx_Tissues_Adrenal Gland Male 60-69 Up | GTEx_Tissues_Adrenal Gland Female 20-29 Up | GTEx_Tissues_Adrenal Gland Male 30-39 Up | GTEx_Tissues_Adrenal Gland Male 40-49 Up | GTEx_Tissues_Adrenal Gland Female 30-39 Up | GTEx_Tissues_Adrenal Gland Male 20-29 Up | GTEx_Tissues_Adrenal Gland Male 70-79 Up
14  GTEx_Tissues_Artery - Aorta Female 20-29 Up | GTEx_Tissues_Artery - Aorta Male 20-29 Up | GTEx_Tissues_Artery - Aorta Female 30-39 Up | GTEx_Tissues_Artery - Aorta Male 40-49 Up | GTEx_Tissues_Artery - Aorta Male 30-39 Up | GTEx_Tissues_Artery - Aorta Female 40-49 Up | GTEx_Tissues_Artery - Aorta Male 70-79 Up | GTEx_Tissues_Artery - Aorta Female 50-59 Up | GTEx_Tissues_Artery - Aorta Female 60-69 Up | GTEx_Tissues_Artery - Aorta Male 50-59 Up | GTEx_Tissues_Artery - Aorta Male 60-69 Up
15
16  GTEx_Tissues_Artery - Aorta Female 60-69 Up | GTEx_Tissues_Artery - Aorta Male 70-79 Up | GTEx_Tissues_Artery - Aorta Female 50-59 Up | GTEx_Tissues_Artery - Aorta Male 40-49 Up | GTEx_Tissues_Artery - Aorta Male 60-69 Up | GTEx_Tissues_Artery - Aorta Male 50-59 Up | GTEx_Tissues_Artery - Aorta Female 70-79 Up | GTEx_Tissues_Artery - Aorta Female 40-49 Up | GTEx_Tissues_Artery - Aorta Male 30-39 Up | GTEx_Tissues_Artery - Aorta Female 30-39 Up | GTEx_Tissues_Artery - Aorta Female 20-29 Up | GTEx_Tissues_Artery - Aorta Male 20-29 Up
17  GTEx_Tissues_Artery - Coronary Male 50-59 Up | GTEx_Tissues_Artery - Coronary Male 60-69 Up | GTEx_Tissues_Artery - Coronary Male 30-39 Up | GTEx_Tissues_Artery - Coronary Female 50-59 Up | GTEx_Tissues_Artery - Coronary Male 40-49 Up | GTEx_Tissues_Artery - Coronary Male 70-79 Up | GTEx_Tissues_Artery - Coronary Male 20-29 Up
18
19  GTEx_Tissues_Artery - Coronary Male 50-59 Up | GTEx_Tissues_Artery - Coronary Female 60-69 Up | GTEx_Tissues_Artery - Coronary Male 60-69 Up | GTEx_Tissues_Artery - Coronary Male 40-49 Up | GTEx_Tissues_Artery - Coronary Male 20-29 Up | GTEx_Tissues_Artery - Coronary Female 50-59 Up | GTEx_Tissues_Artery - Coronary Female 40-49 Up | GTEx_Tissues_Artery - Coronary Male 70-79 Up | GTEx_Tissues_Artery - Coronary Female 20-29 Up | GTEx_Tissues_Artery - Coronary Male 30-39 Up
20
21  GTEx_Tissues_Artery - Tibial Female 30-39 Up | GTEx_Tissues_Artery - Tibial Male 20-29 Up | GTEx_Tissues_Artery - Tibial Female 40-49 Up | GTEx_Tissues_Artery - Tibial Male 40-49 Up | GTEx_Tissues_Artery - Tibial Female 20-29 Up | GTEx_Tissues_Artery - Tibial Male 30-39 Up | GTEx_Tissues_Artery - Tibial Female 70-79 Up | GTEx_Tissues_Artery - Tibial Male 60-69 Up | GTEx_Tissues_Artery - Tibial Male 50-59 Up | GTEx_Tissues_Artery - Tibial Male 70-79 Up | GTEx_Tissues_Artery - Tibial Female 50-59 Up
22  GTEx_Tissues_Artery - Tibial Female 50-59 Up | GTEx_Tissues_Artery - Tibial Female 60-69 Up | GTEx_Tissues_Artery - Tibial Female 70-79 Up | GTEx_Tissues_Artery - Tibial Male 60-69 Up | GTEx_Tissues_Artery - Tibial Male 40-49 Up | GTEx_Tissues_Artery - Tibial Male 50-59 Up | GTEx_Tissues_Artery - Tibial Male 70-79 Up | GTEx_Tissues_Artery - Tibial Female 40-49 Up | GTEx_Tissues_Artery - Tibial Male 30-39 Up | GTEx_Tissues_Artery - Tibial Female 20-29 Up | GTEx_Tissues_Artery - Tibial Male 20-29 Up | GTEx_Tissues_Artery - Tibial Female 30-39 Up
23  GTEx_Tissues_Artery - Tibial Male 60-69 Up | GTEx_Tissues_Artery - Tibial Male 50-59 Up | GTEx_Tissues_Artery - Tibial Female 70-79 Up | GTEx_Tissues_Artery - Tibial Male 70-79 Up | GTEx_Tissues_Artery - Tibial Female 60-69 Up | GTEx_Tissues_Artery - Tibial Female 50-59 Up | GTEx_Tissues_Artery - Tibial Male 40-49 Up | GTEx_Tissues_Artery - Tibial Female 40-49 Up | GTEx_Tissues_Artery - Tibial Male 30-39 Up | GTEx_Tissues_Artery - Tibial Female 30-39 Up | GTEx_Tissues_Artery - Tibial Female 20-29 Up | GTEx_Tissues_Artery - Tibial Male 20-29 Up
24  GTEx_Tissues_Artery - Tibial Female 50-59 Up | GTEx_Tissues_Artery - Tibial Female 60-69 Up | GTEx_Tissues_Artery - Tibial Male 60-69 Up | GTEx_Tissues_Artery - Tibial Male 50-59 Up | GTEx_Tissues_Artery - Tibial Male 30-39 Up | GTEx_Tissues_Artery - Tibial Female 20-29 Up | GTEx_Tissues_Artery - Tibial Female 70-79 Up | GTEx_Tissues_Artery - Tibial Male 40-49 Up | GTEx_Tissues_Artery - Tibial Male 70-79 Up | GTEx_Tissues_Artery - Tibial Female 40-49 Up | GTEx_Tissues_Artery - Tibial Female 30-39 Up | GTEx_Tissues_Artery - Tibial Male 20-29 Up
25  GTEx_Tissues_Brain - Amygdala Female 40-49 Up | GTEx_Tissues_Brain - Amygdala Male 40-49 Up | GTEx_Tissues_Brain - Amygdala Male 20-29 Up | GTEx_Tissues_Brain - Amygdala Female 60-69 Up | GTEx_Tissues_Brain - Amygdala Male 50-59 Up | GTEx_Tissues_Brain - Amygdala Male 60-69 Up | GTEx_Tissues_Brain - Amygdala Male 70-79 Up | GTEx_Tissues_Brain - Amygdala Female 50-59 Up
26  GTEx_Tissues_Brain - Amygdala Male 40-49 Up | GTEx_Tissues_Brain - Amygdala Male 50-59 Up | GTEx_Tissues_Brain - Amygdala Female 40-49 Up | GTEx_Tissues_Brain - Amygdala Male 60-69 Up | GTEx_Tissues_Brain - Amygdala Female 60-69 Up | GTEx_Tissues_Brain - Amygdala Male 70-79 Up | GTEx_Tissues_Brain - Amygdala Male 20-29 Up | GTEx_Tissues_Brain - Amygdala Female 50-59 Up
27
28
29  GTEx_Tissues_Brain - Anterior Cingulate Cortex (BA24) Female 50-59 Up | GTEx_Tissues_Brain - Anterior Cingulate Cortex (BA24) Female 20-29 Up | GTEx_Tissues_Brain - Anterior Cingulate Cortex (BA24) Female 40-49 Up | GTEx_Tissues_Brain - Anterior Cingulate Cortex (BA24) Male 40-49 Up | GTEx_Tissues_Brain - Anterior Cingulate Cortex (BA24) Male 60-69 Up | GTEx_Tissues_Brain - Anterior Cingulate Cortex (BA24) Male 50-59 Up | GTEx_Tissues_Brain - Anterior Cingulate Cortex (BA24) Male 70-79 Up | GTEx_Tissues_Brain - Anterior Cingulate Cortex (BA24) Male 30-39 Up | GTEx_Tissues_Brain - Anterior Cingulate Cortex (BA24) Female 60-69 Up
30  GTEx_Tissues_Brain - Anterior Cingulate Cortex (BA24) Male 50-59 Up | GTEx_Tissues_Brain - Anterior Cingulate Cortex (BA24) Male 60-69 Up | GTEx_Tissues_Brain - Anterior Cingulate Cortex (BA24) Male 30-39 Up | GTEx_Tissues_Brain - Anterior Cingulate Cortex (BA24) Male 70-79 Up
⋮   ⋮
197 GTEx_Tissues_Small Intestine - Terminal Ileum Male 50-59 Up | GTEx_Tissues_Small Intestine - Terminal Ileum Female 60-69 Up | GTEx_Tissues_Small Intestine - Terminal Ileum Male 60-69 Up | GTEx_Tissues_Small Intestine - Terminal Ileum Male 30-39 Up | GTEx_Tissues_Small Intestine - Terminal Ileum Male 40-49 Up | GTEx_Tissues_Small Intestine - Terminal Ileum Female 50-59 Up | GTEx_Tissues_Small Intestine - Terminal Ileum Female 30-39 Up | GTEx_Tissues_Small Intestine - Terminal Ileum Male 20-29 Up | GTEx_Tissues_Small Intestine - Terminal Ileum Female 40-49 Up | GTEx_Tissues_Small Intestine - Terminal Ileum Female 20-29 Up

In [9]:
# Per-LV correctness within the cumulative25 selection (not just "any LV correct")
per_lv_summary <- results$cumulative25$detail %>%
    dplyr::group_by(Tissue) %>%
    dplyr::summarise(
        n_lvs = dplyr::n(),
        n_correct = sum(tissue_correct),
        pct_correct = 100 * n_correct / n_lvs,
        .groups = "drop"
    ) %>%
    dplyr::arrange(pct_correct)

print(per_lv_summary, n = Inf)

total_lvs <- sum(per_lv_summary$n_lvs)
total_correct <- sum(per_lv_summary$n_correct)
cat(sprintf(
    "\nOverall: %d/%d LV-tissue rows correct (%.1f%%) across cumulative25 selection\n",
    total_correct, total_lvs, 100 * total_correct / total_lvs
))
cat(sprintf("Tissues at 100%% LV concordance: %d/%d\n",
            sum(per_lv_summary$pct_correct == 100), nrow(per_lv_summary)))

write.csv(per_lv_summary, file.path(OUT_DIR, "cumulative25", "gtex_global_alignment_per_lv_pct.csv"), row.names = FALSE)

# A tibble: 49 × 4
   Tissue                                    n_lvs n_correct pct_correct
   <chr>                                     <int>     <int>       <dbl>
 1 Pituitary                                     5         1        20
 2 Brain - Cerebellar Hemisphere                 9         2        22.2
 3 Cells - Cultured fibroblasts                  4         1        25
 4 Whole Blood                                   4         1        25
 5 Esophagus - Gastroesophageal Junction         6         2        33.3
 6 Heart - Left Ventricle                        6         2        33.3
 7 Muscle - Skeletal                             3         1        33.3
 8 Spleen                                        3         1        33.3
 9 Testis                                        3         1        33.3
10 Brain - Substantia nigra                      8         3        37.5
11 Cells - EBV-transformed lymphocytes           5         2        40
12 Adipose - Subcutaneous                        6         3        50
13 Artery - Coronary                             4         2        50
14 Brain - Amygdala                              4         2        50
15 Brain - Cerebellum                            8         4        50
16 Brain - Frontal Cortex (BA9)                  6         3        50
17 Uterus                                        4         2        50
18 Brain - Putamen (basal ganglia)               9         5        55.6
19 Brain - Hippocampus                           7         4        57.1
20 Brain - Nucleus accumbens (basal ganglia)     7         4        57.1
21 Adipose - Visceral (Omentum)                  5         3        60
22 Brain - Hypothalamus                          5         3        60
23 Brain - Spinal cord (cervical c-1)            5         3        60
24 Breast - Mammary Tissue                       5         3        60
25 Skin - Not Sun Exposed (Suprapubic)           5         3        60
26 Artery - Aorta                                3         2        66.7
27 Brain - Anterior cingulate cortex (BA24)      6         4        66.7
28 Colon - Transverse                            6         4        66.7
29 Esophagus - Mucosa                            3         2        66.7
30 Esophagus - Muscularis                        3         2        66.7
31 Minor Salivary Gland                          3         2        66.7
32 Small Intestine - Terminal Ileum              7         5        71.4
33 Ovary                                         4         3        75
34 Vagina                                        4         3        75
35 Skin - Sun Exposed (Lower leg)                5         4        80
36 Brain - Caudate (basal ganglia)               8         7        87.5
37 Adrenal Gland                                 2         2       100
38 Artery - Tibial                               4         4       100
39 Brain - Cortex                                4         4       100
40 Colon - Sigmoid                               3         3       100
41 Heart - Atrial Appendage                      3         3       100
42 Kidney - Cortex                               3         3       100
43 Liver                                         4         4       100
44 Lung                                          2         2       100
45 Nerve - Tibial                                2         2       100
46 Pancreas                                      2         2       100
47 Prostate                                      4         4       100
48 Stomach                                       4         4       100
49 Thyroid                                       1         1       100

Overall: 137/226 LV-tissue rows correct (60.6%) across cumulative25 selection

Tissues at 100% LV concordance: 13/49

In [10]:
stopifnot(file.exists(file.path(OUT_DIR, 'gtex_tissue_ora_per_lv.csv')))

for (nm in names(selections)) {
    out_dir <- file.path(OUT_DIR, nm)
    expected_rows <- nrow(selections[[nm]])
    stopifnot(nrow(results[[nm]]$detail) == expected_rows)
    stopifnot(nrow(results[[nm]]$tissue_summary) == dplyr::n_distinct(shap_all$Tissue))
    stopifnot(file.exists(file.path(out_dir, 'gtex_global_alignment_detail.csv')))
    stopifnot(file.exists(file.path(out_dir, 'gtex_global_alignment_summary.csv')))
    stopifnot(file.exists(file.path(out_dir, 'gtex_global_alignment_final_pct.csv')))
    cat(sprintf(
        '[%s] Checks passed. Denominator = %d tissues and %d selected LV/tissue rows. Final %% tissue correct = %.2f\n',
        nm, nrow(results[[nm]]$tissue_summary), nrow(results[[nm]]$detail),
        results[[nm]]$final_summary$pct_tissue_correct
    ))
}

[top1] Checks passed. Denominator = 49 tissues and 49 selected LV/tissue rows. Final % tissue correct = 87.76
[cumulative25] Checks passed. Denominator = 49 tissues and 226 selected LV/tissue rows. Final % tissue correct = 100.00