# Description

Reads the 490 drug-disease prediction HDF5 files from `011-prediction-*` notebooks and computes
final performance measures (AUROC, average precision) against the PharmacotherapyDB gold standard.

Mirrors `phenoplier/nbs/30_drug_disease_associations/100-lincs/021-prediction_performance.ipynb` exactly.

Aggregation (same as PhenoPlier):
1. Group by (trait, drug, method, tissue) → **average ranks across thresholds**.
2. Group by (trait, drug, method) → **max across tissues**.

Files expected: 2 methods × 49 tissues × 5 thresholds = 490 HDF5 files.

# Modules loading

In [1]:
%load_ext autoreload
%autoreload 2

In [2]:
from pathlib import Path
from collections import defaultdict
from IPython.display import display

import numpy as np
import pandas as pd
from tqdm import tqdm
from sklearn.metrics import roc_auc_score, average_precision_score

from pyprojroot import here

# Settings

In [3]:
N_TISSUES = 49
N_THRESHOLDS = 5
N_PREDICTION_FILES_PER_METHOD = N_TISSUES * N_THRESHOLDS  # 245
N_PREDICTION_FILES_TOTAL = 2 * N_PREDICTION_FILES_PER_METHOD  # 490

In [4]:
DATA_DIR = here('data/archs4/drug_diseases_associations')
display(DATA_DIR)
assert DATA_DIR.exists()

OUTPUT_DIR = here('output/drug_disease_analyses') / 'lincs'
display(OUTPUT_DIR)
assert OUTPUT_DIR.exists()

OUTPUT_PREDICTIONS_DIR = OUTPUT_DIR / 'predictions' / 'dotprod_neg'
display(OUTPUT_PREDICTIONS_DIR)
assert OUTPUT_PREDICTIONS_DIR.exists()

PosixPath('/home/msubirana/Documents/pivlab/clamp-analyses/data/archs4/drug_diseases_associations')

PosixPath('/home/msubirana/Documents/pivlab/clamp-analyses/output/drug_disease_analyses/lincs')

PosixPath('/home/msubirana/Documents/pivlab/clamp-analyses/output/drug_disease_analyses/lincs/predictions/dotprod_neg')

# Load PharmacotherapyDB gold standard

In [5]:
gold_standard = pd.read_pickle(DATA_DIR / 'gold_standard.pkl')
display(gold_standard.shape)
display(gold_standard.head())
display(gold_standard['true_class'].value_counts())

(998, 3)

        trait     drug  true_class
0  DOID:10652  DB00843           1
1  DOID:10652  DB00674           1
2  DOID:10652  DB01043           1
3  DOID:10652  DB00989           1
4  DOID:10652  DB00810           0

true_class
1    755
0    243
Name: count, dtype: int64

# Load drug-disease predictions

In [6]:
current_prediction_files = list(OUTPUT_PREDICTIONS_DIR.glob('*.h5'))
display(len(current_prediction_files))

assert len(current_prediction_files) == N_PREDICTION_FILES_TOTAL, (
    f'Expected {N_PREDICTION_FILES_TOTAL} files (490), found {len(current_prediction_files)}.\n'
    f'Run 011-prediction-single_gene_based.ipynb and 011-prediction-gene_module_based.ipynb first.'
)

490

In [7]:
current_prediction_files[:5]

[PosixPath('/home/msubirana/Documents/pivlab/clamp-analyses/output/drug_disease_analyses/lincs/predictions/dotprod_neg/spredixcan-mashr-zscores-Kidney_Cortex-data-top_250_genes-prediction_scores.h5'),
 PosixPath('/home/msubirana/Documents/pivlab/clamp-analyses/output/drug_disease_analyses/lincs/predictions/dotprod_neg/spredixcan-mashr-zscores-Esophagus_Muscularis-projection-top_10_genes-prediction_scores.h5'),
 PosixPath('/home/msubirana/Documents/pivlab/clamp-analyses/output/drug_disease_analyses/lincs/predictions/dotprod_neg/spredixcan-mashr-zscores-Brain_Caudate_basal_ganglia-projection-top_25_genes-prediction_scores.h5'),
 PosixPath('/home/msubirana/Documents/pivlab/clamp-analyses/output/drug_disease_analyses/lincs/predictions/dotprod_neg/spredixcan-mashr-zscores-Esophagus_Gastroesophageal_Junction-projection-top_25_genes-prediction_scores.h5'),
 PosixPath('/home/msubirana/Documents/pivlab/clamp-analyses/output/drug_disease_analyses/lincs/predictions/dotprod_neg/spredixcan-mashr-zscores-Small_Intestine_Terminal_Ileum-projection-all_genes-prediction_scores.h5')]

In [8]:
def _get_tissue(data_value):
    """
    Extracts tissue name from the 'data' metadata field.
    Handles both raw (-data) and projected (-projection) suffixes.
    E.g.: 'spredixcan-mashr-zscores-Liver-data' -> 'Liver'
         'spredixcan-mashr-zscores-Liver-projection' -> 'Liver'
    """
    if data_value.endswith('-projection'):
        return data_value.split('spredixcan-mashr-zscores-')[1].split('-projection')[0]
    else:
        return data_value.split('spredixcan-mashr-zscores-')[1].split('-data')[0]

In [9]:
# Load all prediction files, rank scores, merge with gold standard
predictions = []

for f in tqdm(current_prediction_files, ncols=100):
    # Load DOID-mapped predictions and rank within the full DOID distribution
    prediction_data = pd.read_hdf(f, key='prediction')
    prediction_data['score'] = prediction_data['score'].rank()

    # Filter to gold-standard pairs
    prediction_data = pd.merge(
        prediction_data, gold_standard, on=['trait', 'drug'], how='inner'
    )
    prediction_data['trait'] = prediction_data['trait'].astype('category')
    prediction_data['drug'] = prediction_data['drug'].astype('category')

    # Read metadata
    metadata = pd.read_hdf(f, key='metadata')

    prediction_data = prediction_data.assign(method=metadata['method'].values[0])
    prediction_data['method'] = prediction_data['method'].astype('category')

    prediction_data = prediction_data.assign(n_top_genes=metadata['n_top_genes'].values[0])

    data_value = metadata['data'].values[0]
    prediction_data = prediction_data.assign(data=data_value)
    prediction_data['data'] = prediction_data['data'].astype('category')

    # Extract tissue name from data field
    prediction_data = prediction_data.assign(tissue=_get_tissue(data_value))

    predictions.append(prediction_data)

  0%|                                                                       | 0/490 [00:00<?, ?it/s]

  0%|▏                                                              | 1/490 [00:00<01:30,  5.40it/s]

  0%|▎                                                              | 2/490 [00:00<01:21,  5.96it/s]

  1%|▍                                                              | 3/490 [00:00<01:18,  6.17it/s]

  1%|▌                                                              | 4/490 [00:00<01:17,  6.28it/s]

  1%|▋                                                              | 5/490 [00:00<01:16,  6.33it/s]

  1%|▊                                                              | 6/490 [00:00<01:15,  6.39it/s]

  1%|▉                                                              | 7/490 [00:01<01:14,  6.49it/s]

  2%|█                                                              | 8/490 [00:01<01:13,  6.55it/s]

  2%|█▏                                                             | 9/490 [00:01<01:12,  6.60it/s]

  2%|█▎                                                            | 10/490 [00:01<01:12,  6.66it/s]

  2%|█▍                                                            | 11/490 [00:01<01:11,  6.70it/s]

  2%|█▌                                                            | 12/490 [00:01<01:11,  6.71it/s]

  3%|█▋                                                            | 13/490 [00:02<01:11,  6.67it/s]

  3%|█▊                                                            | 14/490 [00:02<01:11,  6.65it/s]

  3%|█▉                                                            | 15/490 [00:02<01:11,  6.66it/s]

  3%|██                                                            | 16/490 [00:02<01:10,  6.70it/s]

  3%|██▏                                                           | 17/490 [00:02<01:10,  6.69it/s]

  4%|██▎                                                           | 18/490 [00:02<01:10,  6.72it/s]

  4%|██▍                                                           | 19/490 [00:02<01:10,  6.69it/s]

  4%|██▌                                                           | 20/490 [00:03<01:10,  6.68it/s]

  4%|██▋                                                           | 21/490 [00:03<01:09,  6.72it/s]

  4%|██▊                                                           | 22/490 [00:03<01:10,  6.64it/s]

  5%|██▉                                                           | 23/490 [00:03<01:10,  6.64it/s]

  5%|███                                                           | 24/490 [00:03<01:09,  6.67it/s]

  5%|███▏                                                          | 25/490 [00:03<01:09,  6.71it/s]

  5%|███▎                                                          | 26/490 [00:03<01:09,  6.66it/s]

  6%|███▍                                                          | 27/490 [00:04<01:09,  6.61it/s]

  6%|███▌                                                          | 28/490 [00:04<01:10,  6.59it/s]

  6%|███▋                                                          | 29/490 [00:04<01:09,  6.60it/s]

  6%|███▊                                                          | 30/490 [00:04<01:09,  6.61it/s]

  6%|███▉                                                          | 31/490 [00:04<01:08,  6.66it/s]

  7%|████                                                          | 32/490 [00:04<01:08,  6.68it/s]

  7%|████▏                                                         | 33/490 [00:05<01:08,  6.69it/s]

  7%|████▎                                                         | 34/490 [00:05<01:08,  6.67it/s]

  7%|████▍                                                         | 35/490 [00:05<01:08,  6.68it/s]

  7%|████▌                                                         | 36/490 [00:05<01:08,  6.59it/s]

  8%|████▋                                                         | 37/490 [00:05<01:08,  6.59it/s]

  8%|████▊                                                         | 38/490 [00:05<01:08,  6.60it/s]

  8%|████▉                                                         | 39/490 [00:05<01:07,  6.64it/s]

  8%|█████                                                         | 40/490 [00:06<01:08,  6.60it/s]

  8%|█████▏                                                        | 41/490 [00:06<01:08,  6.56it/s]

  9%|█████▎                                                        | 42/490 [00:06<01:08,  6.57it/s]

  9%|█████▍                                                        | 43/490 [00:06<01:07,  6.64it/s]

  9%|█████▌                                                        | 44/490 [00:06<01:07,  6.63it/s]

  9%|█████▋                                                        | 45/490 [00:06<01:06,  6.67it/s]

  9%|█████▊                                                        | 46/490 [00:06<01:08,  6.52it/s]

 10%|█████▉                                                        | 47/490 [00:07<01:07,  6.56it/s]

 10%|██████                                                        | 48/490 [00:07<01:08,  6.45it/s]

 10%|██████▏                                                       | 49/490 [00:07<01:08,  6.48it/s]

 10%|██████▎                                                       | 50/490 [00:07<01:07,  6.49it/s]

 10%|██████▍                                                       | 51/490 [00:07<01:07,  6.53it/s]

 11%|██████▌                                                       | 52/490 [00:07<01:06,  6.60it/s]

 11%|██████▋                                                       | 53/490 [00:08<01:05,  6.64it/s]

 11%|██████▊                                                       | 54/490 [00:08<01:05,  6.67it/s]

 11%|██████▉                                                       | 55/490 [00:08<01:04,  6.70it/s]

 11%|███████                                                       | 56/490 [00:08<01:04,  6.68it/s]

 12%|███████▏                                                      | 57/490 [00:08<01:05,  6.61it/s]

 12%|███████▎                                                      | 58/490 [00:08<01:05,  6.57it/s]

 12%|███████▍                                                      | 59/490 [00:08<01:05,  6.60it/s]

 12%|███████▌                                                      | 60/490 [00:09<01:05,  6.54it/s]

 12%|███████▋                                                      | 61/490 [00:09<01:05,  6.57it/s]

 13%|███████▊                                                      | 62/490 [00:09<01:09,  6.15it/s]

 13%|███████▉                                                      | 63/490 [00:09<01:08,  6.28it/s]

 13%|████████                                                      | 64/490 [00:09<01:06,  6.38it/s]

 13%|████████▏                                                     | 65/490 [00:09<01:05,  6.44it/s]

 13%|████████▎                                                     | 66/490 [00:10<01:05,  6.49it/s]

 14%|████████▍                                                     | 67/490 [00:10<01:04,  6.54it/s]

 14%|████████▌                                                     | 68/490 [00:10<01:04,  6.58it/s]

 14%|████████▋                                                     | 69/490 [00:10<01:03,  6.61it/s]

 14%|████████▊                                                     | 70/490 [00:10<01:03,  6.64it/s]

 14%|████████▉                                                     | 71/490 [00:10<01:02,  6.67it/s]

 15%|█████████                                                     | 72/490 [00:10<01:02,  6.66it/s]

 15%|█████████▏                                                    | 73/490 [00:11<01:02,  6.69it/s]

 15%|█████████▎                                                    | 74/490 [00:11<01:02,  6.65it/s]

 15%|█████████▍                                                    | 75/490 [00:11<01:02,  6.62it/s]

 16%|█████████▌                                                    | 76/490 [00:11<01:02,  6.57it/s]

 16%|█████████▋                                                    | 77/490 [00:11<01:02,  6.64it/s]

 16%|█████████▊                                                    | 78/490 [00:11<01:01,  6.67it/s]

 16%|█████████▉                                                    | 79/490 [00:12<01:01,  6.64it/s]

 16%|██████████                                                    | 80/490 [00:12<01:01,  6.62it/s]

 17%|██████████▏                                                   | 81/490 [00:12<01:01,  6.60it/s]

 17%|██████████▍                                                   | 82/490 [00:12<01:02,  6.58it/s]

 17%|██████████▌                                                   | 83/490 [00:12<01:01,  6.59it/s]

 17%|██████████▋                                                   | 84/490 [00:12<01:01,  6.59it/s]

 17%|██████████▊                                                   | 85/490 [00:12<01:01,  6.59it/s]

 18%|██████████▉                                                   | 86/490 [00:13<01:01,  6.60it/s]

 18%|███████████                                                   | 87/490 [00:13<01:01,  6.59it/s]

 18%|███████████▏                                                  | 88/490 [00:13<01:01,  6.58it/s]

 18%|███████████▎                                                  | 89/490 [00:13<01:01,  6.56it/s]

 18%|███████████▍                                                  | 90/490 [00:13<01:01,  6.55it/s]

 19%|███████████▌                                                  | 91/490 [00:13<01:00,  6.56it/s]

 19%|███████████▋                                                  | 92/490 [00:13<01:00,  6.56it/s]

 19%|███████████▊                                                  | 93/490 [00:14<01:00,  6.55it/s]

 19%|███████████▉                                                  | 94/490 [00:14<01:00,  6.56it/s]

 19%|████████████                                                  | 95/490 [00:14<01:00,  6.56it/s]

 20%|████████████▏                                                 | 96/490 [00:14<01:00,  6.56it/s]

 20%|████████████▎                                                 | 97/490 [00:14<01:00,  6.55it/s]

 20%|████████████▍                                                 | 98/490 [00:14<00:59,  6.55it/s]

 20%|████████████▌                                                 | 99/490 [00:15<00:59,  6.52it/s]

 20%|████████████▍                                                | 100/490 [00:15<00:59,  6.52it/s]

 21%|████████████▌                                                | 101/490 [00:15<00:59,  6.52it/s]

 21%|████████████▋                                                | 102/490 [00:15<00:59,  6.53it/s]

 21%|████████████▊                                                | 103/490 [00:15<00:59,  6.53it/s]

 21%|████████████▉                                                | 104/490 [00:15<00:59,  6.49it/s]

 21%|█████████████                                                | 105/490 [00:15<00:59,  6.43it/s]

 22%|█████████████▏                                               | 106/490 [00:16<01:00,  6.40it/s]

 22%|█████████████▎                                               | 107/490 [00:16<01:00,  6.38it/s]

 22%|█████████████▍                                               | 108/490 [00:16<00:59,  6.44it/s]

 22%|█████████████▌                                               | 109/490 [00:16<00:58,  6.47it/s]

 22%|█████████████▋                                               | 110/490 [00:16<00:58,  6.45it/s]

 23%|█████████████▊                                               | 111/490 [00:16<00:58,  6.47it/s]

 23%|█████████████▉                                               | 112/490 [00:17<00:58,  6.48it/s]

 23%|██████████████                                               | 113/490 [00:17<00:58,  6.50it/s]

 23%|██████████████▏                                              | 114/490 [00:17<00:58,  6.46it/s]

 23%|██████████████▎                                              | 115/490 [00:17<00:57,  6.49it/s]

 24%|██████████████▍                                              | 116/490 [00:17<00:57,  6.50it/s]

 24%|██████████████▌                                              | 117/490 [00:17<00:57,  6.52it/s]

 24%|██████████████▋                                              | 118/490 [00:17<00:56,  6.54it/s]

 24%|██████████████▊                                              | 119/490 [00:18<00:56,  6.54it/s]

 24%|██████████████▉                                              | 120/490 [00:18<00:56,  6.52it/s]

 25%|███████████████                                              | 121/490 [00:18<00:56,  6.53it/s]

 25%|███████████████▏                                             | 122/490 [00:18<00:56,  6.51it/s]

 25%|███████████████▎                                             | 123/490 [00:18<00:56,  6.51it/s]

 25%|███████████████▍                                             | 124/490 [00:18<00:56,  6.51it/s]

 26%|███████████████▌                                             | 125/490 [00:19<00:56,  6.51it/s]

 26%|███████████████▋                                             | 126/490 [00:19<00:56,  6.39it/s]

 26%|███████████████▊                                             | 127/490 [00:19<00:56,  6.40it/s]

 26%|███████████████▉                                             | 128/490 [00:19<00:56,  6.42it/s]

 26%|████████████████                                             | 129/490 [00:19<00:57,  6.31it/s]

 27%|████████████████▏                                            | 130/490 [00:19<00:57,  6.29it/s]

 27%|████████████████▎                                            | 131/490 [00:20<00:56,  6.32it/s]

 27%|████████████████▍                                            | 132/490 [00:20<00:56,  6.37it/s]

 27%|████████████████▌                                            | 133/490 [00:20<00:55,  6.41it/s]

 27%|████████████████▋                                            | 134/490 [00:20<00:55,  6.44it/s]

 28%|████████████████▊                                            | 135/490 [00:20<00:54,  6.47it/s]

 28%|████████████████▉                                            | 136/490 [00:20<00:54,  6.48it/s]

 28%|█████████████████                                            | 137/490 [00:20<00:54,  6.49it/s]

 28%|█████████████████▏                                           | 138/490 [00:21<00:55,  6.34it/s]

 28%|█████████████████▎                                           | 139/490 [00:21<00:54,  6.40it/s]

 29%|█████████████████▍                                           | 140/490 [00:21<00:54,  6.44it/s]

 29%|█████████████████▌                                           | 141/490 [00:21<00:53,  6.50it/s]

 29%|█████████████████▋                                           | 142/490 [00:21<00:53,  6.53it/s]

 29%|█████████████████▊                                           | 143/490 [00:21<00:53,  6.52it/s]

 29%|█████████████████▉                                           | 144/490 [00:22<00:52,  6.57it/s]

 30%|██████████████████                                           | 145/490 [00:22<00:52,  6.59it/s]

 30%|██████████████████▏                                          | 146/490 [00:22<00:52,  6.61it/s]

 30%|██████████████████▎                                          | 147/490 [00:22<00:51,  6.63it/s]

 30%|██████████████████▍                                          | 148/490 [00:22<00:52,  6.53it/s]

 30%|██████████████████▌                                          | 149/490 [00:22<00:52,  6.54it/s]

 31%|██████████████████▋                                          | 150/490 [00:22<00:51,  6.56it/s]

 31%|██████████████████▊                                          | 151/490 [00:23<00:51,  6.60it/s]

 31%|██████████████████▉                                          | 152/490 [00:23<00:51,  6.59it/s]

 31%|███████████████████                                          | 153/490 [00:23<00:50,  6.63it/s]

 31%|███████████████████▏                                         | 154/490 [00:23<00:51,  6.56it/s]

 32%|███████████████████▎                                         | 155/490 [00:23<00:51,  6.51it/s]

 32%|███████████████████▍                                         | 156/490 [00:23<00:51,  6.50it/s]

 32%|███████████████████▌                                         | 157/490 [00:23<00:51,  6.46it/s]

 32%|███████████████████▋                                         | 158/490 [00:24<00:51,  6.41it/s]

 32%|███████████████████▊                                         | 159/490 [00:24<00:51,  6.45it/s]

 33%|███████████████████▉                                         | 160/490 [00:24<00:50,  6.51it/s]

 33%|████████████████████                                         | 161/490 [00:24<00:50,  6.55it/s]

 33%|████████████████████▏                                        | 162/490 [00:24<00:49,  6.57it/s]

 33%|████████████████████▎                                        | 163/490 [00:24<00:49,  6.61it/s]

 33%|████████████████████▍                                        | 164/490 [00:25<00:49,  6.62it/s]

 34%|████████████████████▌                                        | 165/490 [00:25<00:49,  6.63it/s]

 34%|████████████████████▋                                        | 166/490 [00:25<00:48,  6.64it/s]

 34%|████████████████████▊                                        | 167/490 [00:25<00:49,  6.57it/s]

 34%|████████████████████▉                                        | 168/490 [00:25<00:48,  6.59it/s]

 34%|█████████████████████                                        | 169/490 [00:25<00:48,  6.64it/s]

 35%|█████████████████████▏                                       | 170/490 [00:25<00:48,  6.58it/s]

 35%|█████████████████████▎                                       | 171/490 [00:26<00:48,  6.56it/s]

 35%|█████████████████████▍                                       | 172/490 [00:26<00:48,  6.55it/s]

 35%|█████████████████████▌                                       | 173/490 [00:26<00:48,  6.49it/s]

 36%|█████████████████████▋                                       | 174/490 [00:26<00:49,  6.38it/s]

 36%|█████████████████████▊                                       | 175/490 [00:26<00:48,  6.44it/s]

 36%|█████████████████████▉                                       | 176/490 [00:26<00:48,  6.44it/s]

 36%|██████████████████████                                       | 177/490 [00:27<00:48,  6.49it/s]

 36%|██████████████████████▏                                      | 178/490 [00:27<00:47,  6.52it/s]

 37%|██████████████████████▎                                      | 179/490 [00:27<00:47,  6.55it/s]

 37%|██████████████████████▍                                      | 180/490 [00:27<00:47,  6.55it/s]

 37%|██████████████████████▌                                      | 181/490 [00:27<00:47,  6.57it/s]

 37%|██████████████████████▋                                      | 182/490 [00:27<00:46,  6.58it/s]

 37%|██████████████████████▊                                      | 183/490 [00:27<00:46,  6.57it/s]

 38%|██████████████████████▉                                      | 184/490 [00:28<00:46,  6.58it/s]

 38%|███████████████████████                                      | 185/490 [00:28<00:46,  6.57it/s]

 38%|███████████████████████▏                                     | 186/490 [00:28<00:46,  6.57it/s]

 38%|███████████████████████▎                                     | 187/490 [00:28<00:46,  6.58it/s]

 38%|███████████████████████▍                                     | 188/490 [00:28<00:45,  6.60it/s]

 39%|███████████████████████▌                                     | 189/490 [00:28<00:45,  6.59it/s]

 39%|███████████████████████▋                                     | 190/490 [00:29<00:45,  6.62it/s]

 39%|███████████████████████▊                                     | 191/490 [00:29<00:45,  6.61it/s]

 39%|███████████████████████▉                                     | 192/490 [00:29<00:45,  6.62it/s]

 39%|████████████████████████                                     | 193/490 [00:29<00:45,  6.57it/s]

 40%|████████████████████████▏                                    | 194/490 [00:29<00:45,  6.56it/s]

 40%|████████████████████████▎                                    | 195/490 [00:29<00:44,  6.56it/s]

 40%|████████████████████████▍                                    | 196/490 [00:29<00:44,  6.53it/s]

 40%|████████████████████████▌                                    | 197/490 [00:30<00:44,  6.54it/s]

 40%|████████████████████████▋                                    | 198/490 [00:30<00:44,  6.56it/s]

 41%|████████████████████████▊                                    | 199/490 [00:30<00:44,  6.51it/s]

 41%|████████████████████████▉                                    | 200/490 [00:30<00:44,  6.54it/s]

 41%|█████████████████████████                                    | 201/490 [00:30<00:44,  6.54it/s]

 41%|█████████████████████████▏                                   | 202/490 [00:30<00:43,  6.56it/s]

 41%|█████████████████████████▎                                   | 203/490 [00:31<00:43,  6.58it/s]

 42%|█████████████████████████▍                                   | 204/490 [00:31<00:43,  6.56it/s]

 42%|█████████████████████████▌                                   | 205/490 [00:31<00:43,  6.56it/s]

 42%|█████████████████████████▋                                   | 206/490 [00:31<00:43,  6.58it/s]

 42%|█████████████████████████▊                                   | 207/490 [00:31<00:42,  6.60it/s]

 42%|█████████████████████████▉                                   | 208/490 [00:31<00:42,  6.60it/s]

 43%|██████████████████████████                                   | 209/490 [00:31<00:42,  6.55it/s]

 43%|██████████████████████████▏                                  | 210/490 [00:32<00:42,  6.55it/s]

 43%|██████████████████████████▎                                  | 211/490 [00:32<00:42,  6.56it/s]

 43%|██████████████████████████▍                                  | 212/490 [00:32<00:42,  6.57it/s]

 43%|██████████████████████████▌                                  | 213/490 [00:32<00:42,  6.47it/s]

 44%|██████████████████████████▋                                  | 214/490 [00:32<00:42,  6.53it/s]

 44%|██████████████████████████▊                                  | 215/490 [00:32<00:42,  6.54it/s]

 44%|██████████████████████████▉                                  | 216/490 [00:32<00:41,  6.57it/s]

 44%|███████████████████████████                                  | 217/490 [00:33<00:42,  6.49it/s]

 44%|███████████████████████████▏                                 | 218/490 [00:33<00:41,  6.51it/s]

 45%|███████████████████████████▎                                 | 219/490 [00:33<00:41,  6.52it/s]

 45%|███████████████████████████▍                                 | 220/490 [00:33<00:41,  6.55it/s]

 45%|███████████████████████████▌                                 | 221/490 [00:33<00:41,  6.56it/s]

 45%|███████████████████████████▋                                 | 222/490 [00:33<00:40,  6.57it/s]

 46%|███████████████████████████▊                                 | 223/490 [00:34<00:40,  6.57it/s]

 46%|███████████████████████████▉                                 | 224/490 [00:34<00:40,  6.57it/s]

 46%|████████████████████████████                                 | 225/490 [00:34<00:40,  6.57it/s]

 46%|████████████████████████████▏                                | 226/490 [00:34<00:40,  6.59it/s]

 46%|████████████████████████████▎                                | 227/490 [00:34<00:39,  6.59it/s]

 47%|████████████████████████████▍                                | 228/490 [00:34<00:39,  6.59it/s]

 47%|████████████████████████████▌                                | 229/490 [00:34<00:39,  6.60it/s]

 47%|████████████████████████████▋                                | 230/490 [00:35<00:39,  6.59it/s]

 47%|████████████████████████████▊                                | 231/490 [00:35<00:39,  6.59it/s]

 47%|████████████████████████████▉                                | 232/490 [00:35<00:39,  6.59it/s]

 48%|█████████████████████████████                                | 233/490 [00:35<00:38,  6.60it/s]

 48%|█████████████████████████████▏                               | 234/490 [00:35<00:38,  6.61it/s]

 48%|█████████████████████████████▎                               | 235/490 [00:35<00:38,  6.56it/s]

 48%|█████████████████████████████▍                               | 236/490 [00:36<00:38,  6.57it/s]

 48%|█████████████████████████████▌                               | 237/490 [00:36<00:38,  6.58it/s]

 49%|█████████████████████████████▋                               | 238/490 [00:36<00:38,  6.58it/s]

 49%|█████████████████████████████▊                               | 239/490 [00:36<00:38,  6.59it/s]

 49%|█████████████████████████████▉                               | 240/490 [00:36<00:37,  6.59it/s]

 49%|██████████████████████████████                               | 241/490 [00:36<00:37,  6.59it/s]

 49%|██████████████████████████████▏                              | 242/490 [00:36<00:37,  6.59it/s]

 50%|██████████████████████████████▎                              | 243/490 [00:37<00:37,  6.58it/s]

 50%|██████████████████████████████▍                              | 244/490 [00:37<00:37,  6.56it/s]

 50%|██████████████████████████████▌                              | 245/490 [00:37<00:37,  6.55it/s]

 50%|██████████████████████████████▌                              | 246/490 [00:37<00:37,  6.57it/s]

 50%|██████████████████████████████▋                              | 247/490 [00:37<00:36,  6.58it/s]

 51%|██████████████████████████████▊                              | 248/490 [00:37<00:36,  6.57it/s]

 51%|██████████████████████████████▉                              | 249/490 [00:38<00:36,  6.57it/s]

 51%|███████████████████████████████                              | 250/490 [00:38<00:36,  6.57it/s]

 51%|███████████████████████████████▏                             | 251/490 [00:38<00:36,  6.57it/s]

 51%|███████████████████████████████▎                             | 252/490 [00:38<00:36,  6.57it/s]

 52%|███████████████████████████████▍                             | 253/490 [00:38<00:36,  6.58it/s]

 52%|███████████████████████████████▌                             | 254/490 [00:38<00:36,  6.54it/s]

 52%|███████████████████████████████▋                             | 255/490 [00:38<00:35,  6.55it/s]

 52%|███████████████████████████████▊                             | 256/490 [00:39<00:35,  6.52it/s]

 52%|███████████████████████████████▉                             | 257/490 [00:39<00:35,  6.49it/s]

 53%|████████████████████████████████                             | 258/490 [00:39<00:35,  6.53it/s]

 53%|████████████████████████████████▏                            | 259/490 [00:39<00:35,  6.53it/s]

 53%|████████████████████████████████▎                            | 260/490 [00:39<00:35,  6.54it/s]

 53%|████████████████████████████████▍                            | 261/490 [00:39<00:35,  6.53it/s]

 53%|████████████████████████████████▌                            | 262/490 [00:40<00:35,  6.47it/s]

 54%|████████████████████████████████▋                            | 263/490 [00:40<00:35,  6.44it/s]

 54%|████████████████████████████████▊                            | 264/490 [00:40<00:35,  6.38it/s]

 54%|████████████████████████████████▉                            | 265/490 [00:40<00:35,  6.30it/s]

 54%|█████████████████████████████████                            | 266/490 [00:40<00:35,  6.25it/s]

 54%|█████████████████████████████████▏                           | 267/490 [00:40<00:35,  6.27it/s]

 55%|█████████████████████████████████▎                           | 268/490 [00:40<00:35,  6.27it/s]

 55%|█████████████████████████████████▍                           | 269/490 [00:41<00:35,  6.28it/s]

 55%|█████████████████████████████████▌                           | 270/490 [00:41<00:35,  6.28it/s]

 55%|█████████████████████████████████▋                           | 271/490 [00:41<00:34,  6.31it/s]

 56%|█████████████████████████████████▊                           | 272/490 [00:41<00:34,  6.29it/s]

 56%|█████████████████████████████████▉                           | 273/490 [00:41<00:34,  6.27it/s]

 56%|██████████████████████████████████                           | 274/490 [00:41<00:35,  6.13it/s]

 56%|██████████████████████████████████▏                          | 275/490 [00:42<00:34,  6.17it/s]

 56%|██████████████████████████████████▎                          | 276/490 [00:42<00:35,  6.11it/s]

 57%|██████████████████████████████████▍                          | 277/490 [00:42<00:34,  6.16it/s]

 57%|██████████████████████████████████▌                          | 278/490 [00:42<00:34,  6.21it/s]

 57%|██████████████████████████████████▋                          | 279/490 [00:42<00:33,  6.24it/s]

 57%|██████████████████████████████████▊                          | 280/490 [00:42<00:33,  6.27it/s]

 57%|██████████████████████████████████▉                          | 281/490 [00:43<00:33,  6.29it/s]

 58%|███████████████████████████████████                          | 282/490 [00:43<00:32,  6.31it/s]

 58%|███████████████████████████████████▏                         | 283/490 [00:43<00:32,  6.32it/s]

 58%|███████████████████████████████████▎                         | 284/490 [00:43<00:32,  6.33it/s]

 58%|███████████████████████████████████▍                         | 285/490 [00:43<00:32,  6.35it/s]

 58%|███████████████████████████████████▌                         | 286/490 [00:43<00:32,  6.35it/s]

 59%|███████████████████████████████████▋                         | 287/490 [00:44<00:31,  6.35it/s]

 59%|███████████████████████████████████▊                         | 288/490 [00:44<00:31,  6.35it/s]

 59%|███████████████████████████████████▉                         | 289/490 [00:44<00:31,  6.35it/s]

 59%|████████████████████████████████████                         | 290/490 [00:44<00:31,  6.33it/s]

 59%|████████████████████████████████████▏                        | 291/490 [00:44<00:31,  6.32it/s]

 60%|████████████████████████████████████▎                        | 292/490 [00:44<00:31,  6.30it/s]

 60%|████████████████████████████████████▍                        | 293/490 [00:44<00:31,  6.30it/s]

 60%|████████████████████████████████████▌                        | 294/490 [00:45<00:31,  6.30it/s]

 60%|████████████████████████████████████▋                        | 295/490 [00:45<00:30,  6.30it/s]

 60%|████████████████████████████████████▊                        | 296/490 [00:45<00:30,  6.30it/s]

 61%|████████████████████████████████████▉                        | 297/490 [00:45<00:30,  6.27it/s]

 61%|█████████████████████████████████████                        | 298/490 [00:45<00:30,  6.32it/s]

 61%|█████████████████████████████████████▏                       | 299/490 [00:45<00:29,  6.40it/s]

 61%|█████████████████████████████████████▎                       | 300/490 [00:46<00:29,  6.45it/s]

 61%|█████████████████████████████████████▍                       | 301/490 [00:46<00:29,  6.51it/s]

 62%|█████████████████████████████████████▌                       | 302/490 [00:46<00:29,  6.47it/s]

 62%|█████████████████████████████████████▋                       | 303/490 [00:46<00:28,  6.50it/s]

 62%|█████████████████████████████████████▊                       | 304/490 [00:46<00:28,  6.52it/s]

 62%|█████████████████████████████████████▉                       | 305/490 [00:46<00:28,  6.54it/s]

 62%|██████████████████████████████████████                       | 306/490 [00:46<00:28,  6.57it/s]

 63%|██████████████████████████████████████▏                      | 307/490 [00:47<00:27,  6.59it/s]

 63%|██████████████████████████████████████▎                      | 308/490 [00:47<00:27,  6.51it/s]

 63%|██████████████████████████████████████▍                      | 309/490 [00:47<00:27,  6.49it/s]

 63%|██████████████████████████████████████▌                      | 310/490 [00:47<00:27,  6.48it/s]

 63%|██████████████████████████████████████▋                      | 311/490 [00:47<00:27,  6.51it/s]

 64%|██████████████████████████████████████▊                      | 312/490 [00:47<00:27,  6.46it/s]

 64%|██████████████████████████████████████▉                      | 313/490 [00:48<00:27,  6.49it/s]

 64%|███████████████████████████████████████                      | 314/490 [00:48<00:27,  6.52it/s]

 64%|███████████████████████████████████████▏                     | 315/490 [00:48<00:26,  6.53it/s]

 64%|███████████████████████████████████████▎                     | 316/490 [00:48<00:26,  6.51it/s]

 65%|███████████████████████████████████████▍                     | 317/490 [00:48<00:26,  6.45it/s]

 65%|███████████████████████████████████████▌                     | 318/490 [00:48<00:26,  6.51it/s]

 65%|███████████████████████████████████████▋                     | 319/490 [00:48<00:26,  6.55it/s]

 65%|███████████████████████████████████████▊                     | 320/490 [00:49<00:25,  6.56it/s]

 66%|███████████████████████████████████████▉                     | 321/490 [00:49<00:25,  6.59it/s]

 66%|████████████████████████████████████████                     | 322/490 [00:49<00:25,  6.59it/s]

 66%|████████████████████████████████████████▏                    | 323/490 [00:49<00:25,  6.50it/s]

 66%|████████████████████████████████████████▎                    | 324/490 [00:49<00:25,  6.52it/s]

 66%|████████████████████████████████████████▍                    | 325/490 [00:49<00:25,  6.53it/s]

 67%|████████████████████████████████████████▌                    | 326/490 [00:50<00:25,  6.52it/s]

 67%|████████████████████████████████████████▋                    | 327/490 [00:50<00:24,  6.53it/s]

 67%|████████████████████████████████████████▊                    | 328/490 [00:50<00:24,  6.55it/s]

 67%|████████████████████████████████████████▉                    | 329/490 [00:50<00:24,  6.54it/s]

 67%|█████████████████████████████████████████                    | 330/490 [00:50<00:24,  6.43it/s]

 68%|█████████████████████████████████████████▏                   | 331/490 [00:50<00:24,  6.46it/s]

 68%|█████████████████████████████████████████▎                   | 332/490 [00:50<00:24,  6.50it/s]

 68%|█████████████████████████████████████████▍                   | 333/490 [00:51<00:24,  6.45it/s]

 68%|█████████████████████████████████████████▌                   | 334/490 [00:51<00:24,  6.44it/s]

 68%|█████████████████████████████████████████▋                   | 335/490 [00:51<00:23,  6.47it/s]

 69%|█████████████████████████████████████████▊                   | 336/490 [00:51<00:23,  6.51it/s]

 69%|█████████████████████████████████████████▉                   | 337/490 [00:51<00:23,  6.52it/s]

 69%|██████████████████████████████████████████                   | 338/490 [00:51<00:23,  6.54it/s]

 69%|██████████████████████████████████████████▏                  | 339/490 [00:52<00:23,  6.48it/s]

 69%|██████████████████████████████████████████▎                  | 340/490 [00:52<00:23,  6.50it/s]

 70%|██████████████████████████████████████████▍                  | 341/490 [00:52<00:23,  6.44it/s]

 70%|██████████████████████████████████████████▌                  | 342/490 [00:52<00:22,  6.48it/s]

 70%|██████████████████████████████████████████▋                  | 343/490 [00:52<00:22,  6.49it/s]

 70%|██████████████████████████████████████████▊                  | 344/490 [00:52<00:22,  6.53it/s]

 70%|██████████████████████████████████████████▉                  | 345/490 [00:52<00:22,  6.53it/s]

 71%|███████████████████████████████████████████                  | 346/490 [00:53<00:22,  6.51it/s]

 71%|███████████████████████████████████████████▏                 | 347/490 [00:53<00:22,  6.48it/s]

 71%|███████████████████████████████████████████▎                 | 348/490 [00:53<00:21,  6.51it/s]

 71%|███████████████████████████████████████████▍                 | 349/490 [00:53<00:21,  6.53it/s]

 71%|███████████████████████████████████████████▌                 | 350/490 [00:53<00:21,  6.49it/s]

 72%|███████████████████████████████████████████▋                 | 351/490 [00:53<00:23,  5.85it/s]

 72%|███████████████████████████████████████████▊                 | 352/490 [00:54<00:22,  6.04it/s]

 72%|███████████████████████████████████████████▉                 | 353/490 [00:54<00:22,  6.19it/s]

 72%|████████████████████████████████████████████                 | 354/490 [00:54<00:21,  6.30it/s]

 72%|████████████████████████████████████████████▏                | 355/490 [00:54<00:21,  6.39it/s]

 73%|████████████████████████████████████████████▎                | 356/490 [00:54<00:20,  6.43it/s]

 73%|████████████████████████████████████████████▍                | 357/490 [00:54<00:20,  6.46it/s]

 73%|████████████████████████████████████████████▌                | 358/490 [00:55<00:20,  6.44it/s]

 73%|████████████████████████████████████████████▋                | 359/490 [00:55<00:20,  6.50it/s]

 73%|████████████████████████████████████████████▊                | 360/490 [00:55<00:19,  6.52it/s]

 74%|████████████████████████████████████████████▉                | 361/490 [00:55<00:19,  6.53it/s]

 74%|█████████████████████████████████████████████                | 362/490 [00:55<00:19,  6.55it/s]

 74%|█████████████████████████████████████████████▏               | 363/490 [00:55<00:19,  6.56it/s]

 74%|█████████████████████████████████████████████▎               | 364/490 [00:55<00:19,  6.57it/s]

 74%|█████████████████████████████████████████████▍               | 365/490 [00:56<00:19,  6.58it/s]

 75%|█████████████████████████████████████████████▌               | 366/490 [00:56<00:18,  6.58it/s]

 75%|█████████████████████████████████████████████▋               | 367/490 [00:56<00:18,  6.59it/s]

 75%|█████████████████████████████████████████████▊               | 368/490 [00:56<00:18,  6.60it/s]

 75%|█████████████████████████████████████████████▉               | 369/490 [00:56<00:18,  6.60it/s]

 76%|██████████████████████████████████████████████               | 370/490 [00:56<00:18,  6.55it/s]

 76%|██████████████████████████████████████████████▏              | 371/490 [00:56<00:18,  6.52it/s]

 76%|██████████████████████████████████████████████▎              | 372/490 [00:57<00:18,  6.47it/s]

 76%|██████████████████████████████████████████████▍              | 373/490 [00:57<00:18,  6.48it/s]

 76%|██████████████████████████████████████████████▌              | 374/490 [00:57<00:17,  6.52it/s]

 77%|██████████████████████████████████████████████▋              | 375/490 [00:57<00:17,  6.50it/s]

 77%|██████████████████████████████████████████████▊              | 376/490 [00:57<00:17,  6.54it/s]

 77%|██████████████████████████████████████████████▉              | 377/490 [00:57<00:17,  6.57it/s]

 77%|███████████████████████████████████████████████              | 378/490 [00:58<00:17,  6.58it/s]

 77%|███████████████████████████████████████████████▏             | 379/490 [00:58<00:16,  6.58it/s]

 78%|███████████████████████████████████████████████▎             | 380/490 [00:58<00:16,  6.58it/s]

 78%|███████████████████████████████████████████████▍             | 381/490 [00:58<00:16,  6.57it/s]

 78%|███████████████████████████████████████████████▌             | 382/490 [00:58<00:16,  6.57it/s]

 78%|███████████████████████████████████████████████▋             | 383/490 [00:58<00:16,  6.50it/s]

 78%|███████████████████████████████████████████████▊             | 384/490 [00:58<00:16,  6.50it/s]

 79%|███████████████████████████████████████████████▉             | 385/490 [00:59<00:16,  6.50it/s]

 79%|████████████████████████████████████████████████             | 386/490 [00:59<00:15,  6.53it/s]

 79%|████████████████████████████████████████████████▏            | 387/490 [00:59<00:15,  6.50it/s]

 79%|████████████████████████████████████████████████▎            | 388/490 [00:59<00:15,  6.53it/s]

 79%|████████████████████████████████████████████████▍            | 389/490 [00:59<00:15,  6.55it/s]

 80%|████████████████████████████████████████████████▌            | 390/490 [00:59<00:15,  6.56it/s]

 80%|████████████████████████████████████████████████▋            | 391/490 [01:00<00:15,  6.57it/s]

 80%|████████████████████████████████████████████████▊            | 392/490 [01:00<00:14,  6.59it/s]

 80%|████████████████████████████████████████████████▉            | 393/490 [01:00<00:14,  6.60it/s]

 80%|█████████████████████████████████████████████████            | 394/490 [01:00<00:14,  6.60it/s]

 81%|█████████████████████████████████████████████████▏           | 395/490 [01:00<00:14,  6.59it/s]

 81%|█████████████████████████████████████████████████▎           | 396/490 [01:00<00:14,  6.59it/s]

 81%|█████████████████████████████████████████████████▍           | 397/490 [01:00<00:14,  6.60it/s]

 81%|█████████████████████████████████████████████████▌           | 398/490 [01:01<00:13,  6.60it/s]

 81%|█████████████████████████████████████████████████▋           | 399/490 [01:01<00:13,  6.59it/s]

 82%|█████████████████████████████████████████████████▊           | 400/490 [01:01<00:13,  6.59it/s]

 82%|█████████████████████████████████████████████████▉           | 401/490 [01:01<00:13,  6.59it/s]

 82%|██████████████████████████████████████████████████           | 402/490 [01:01<00:13,  6.60it/s]

 82%|██████████████████████████████████████████████████▏          | 403/490 [01:01<00:13,  6.59it/s]

 82%|██████████████████████████████████████████████████▎          | 404/490 [01:02<00:13,  6.59it/s]

 83%|██████████████████████████████████████████████████▍          | 405/490 [01:02<00:12,  6.59it/s]

 83%|██████████████████████████████████████████████████▌          | 406/490 [01:02<00:12,  6.52it/s]

 83%|██████████████████████████████████████████████████▋          | 407/490 [01:02<00:12,  6.52it/s]

 83%|██████████████████████████████████████████████████▊          | 408/490 [01:02<00:12,  6.52it/s]

 83%|██████████████████████████████████████████████████▉          | 409/490 [01:02<00:12,  6.52it/s]

 84%|███████████████████████████████████████████████████          | 410/490 [01:02<00:12,  6.54it/s]

 84%|███████████████████████████████████████████████████▏         | 411/490 [01:03<00:12,  6.56it/s]

 84%|███████████████████████████████████████████████████▎         | 412/490 [01:03<00:11,  6.56it/s]

 84%|███████████████████████████████████████████████████▍         | 413/490 [01:03<00:11,  6.54it/s]

 84%|███████████████████████████████████████████████████▌         | 414/490 [01:03<00:11,  6.51it/s]

 85%|███████████████████████████████████████████████████▋         | 415/490 [01:03<00:11,  6.51it/s]

 85%|███████████████████████████████████████████████████▊         | 416/490 [01:03<00:11,  6.48it/s]

 85%|███████████████████████████████████████████████████▉         | 417/490 [01:04<00:11,  6.51it/s]

 85%|████████████████████████████████████████████████████         | 418/490 [01:04<00:11,  6.53it/s]

 86%|████████████████████████████████████████████████████▏        | 419/490 [01:04<00:10,  6.55it/s]

 86%|████████████████████████████████████████████████████▎        | 420/490 [01:04<00:10,  6.56it/s]

 86%|████████████████████████████████████████████████████▍        | 421/490 [01:04<00:10,  6.56it/s]

 86%|████████████████████████████████████████████████████▌        | 422/490 [01:04<00:10,  6.50it/s]

 86%|████████████████████████████████████████████████████▋        | 423/490 [01:04<00:10,  6.53it/s]

 87%|████████████████████████████████████████████████████▊        | 424/490 [01:05<00:10,  6.46it/s]

 87%|████████████████████████████████████████████████████▉        | 425/490 [01:05<00:10,  6.50it/s]

 87%|█████████████████████████████████████████████████████        | 426/490 [01:05<00:09,  6.46it/s]

 87%|█████████████████████████████████████████████████████▏       | 427/490 [01:05<00:09,  6.45it/s]

 87%|█████████████████████████████████████████████████████▎       | 428/490 [01:05<00:09,  6.47it/s]

 88%|█████████████████████████████████████████████████████▍       | 429/490 [01:05<00:09,  6.42it/s]

 88%|█████████████████████████████████████████████████████▌       | 430/490 [01:06<00:09,  6.41it/s]

 88%|█████████████████████████████████████████████████████▋       | 431/490 [01:06<00:09,  6.40it/s]

 88%|█████████████████████████████████████████████████████▊       | 432/490 [01:06<00:09,  6.37it/s]

 88%|█████████████████████████████████████████████████████▉       | 433/490 [01:06<00:08,  6.37it/s]

 89%|██████████████████████████████████████████████████████       | 434/490 [01:06<00:08,  6.34it/s]

 89%|██████████████████████████████████████████████████████▏      | 435/490 [01:06<00:08,  6.35it/s]

 89%|██████████████████████████████████████████████████████▎      | 436/490 [01:06<00:08,  6.35it/s]

 89%|██████████████████████████████████████████████████████▍      | 437/490 [01:07<00:08,  6.36it/s]

 89%|██████████████████████████████████████████████████████▌      | 438/490 [01:07<00:08,  6.36it/s]

 90%|██████████████████████████████████████████████████████▋      | 439/490 [01:07<00:08,  6.36it/s]

 90%|██████████████████████████████████████████████████████▊      | 440/490 [01:07<00:07,  6.35it/s]

 90%|██████████████████████████████████████████████████████▉      | 441/490 [01:07<00:07,  6.35it/s]

 90%|███████████████████████████████████████████████████████      | 442/490 [01:07<00:07,  6.35it/s]

 90%|███████████████████████████████████████████████████████▏     | 443/490 [01:08<00:07,  6.36it/s]

 91%|███████████████████████████████████████████████████████▎     | 444/490 [01:08<00:07,  6.37it/s]

 91%|███████████████████████████████████████████████████████▍     | 445/490 [01:08<00:07,  6.34it/s]

 91%|███████████████████████████████████████████████████████▌     | 446/490 [01:08<00:06,  6.34it/s]

 91%|███████████████████████████████████████████████████████▋     | 447/490 [01:08<00:06,  6.35it/s]

 91%|███████████████████████████████████████████████████████▊     | 448/490 [01:08<00:06,  6.32it/s]

 92%|███████████████████████████████████████████████████████▉     | 449/490 [01:09<00:06,  6.32it/s]

 92%|████████████████████████████████████████████████████████     | 450/490 [01:09<00:06,  6.34it/s]

 92%|████████████████████████████████████████████████████████▏    | 451/490 [01:09<00:06,  6.33it/s]

 92%|████████████████████████████████████████████████████████▎    | 452/490 [01:09<00:06,  6.32it/s]

 92%|████████████████████████████████████████████████████████▍    | 453/490 [01:09<00:05,  6.32it/s]

 93%|████████████████████████████████████████████████████████▌    | 454/490 [01:09<00:05,  6.33it/s]

 93%|████████████████████████████████████████████████████████▋    | 455/490 [01:09<00:05,  6.32it/s]

 93%|████████████████████████████████████████████████████████▊    | 456/490 [01:10<00:05,  6.35it/s]

 93%|████████████████████████████████████████████████████████▉    | 457/490 [01:10<00:05,  6.43it/s]

 93%|█████████████████████████████████████████████████████████    | 458/490 [01:10<00:04,  6.49it/s]

 94%|█████████████████████████████████████████████████████████▏   | 459/490 [01:10<00:04,  6.45it/s]

 94%|█████████████████████████████████████████████████████████▎   | 460/490 [01:10<00:04,  6.50it/s]

 94%|█████████████████████████████████████████████████████████▍   | 461/490 [01:10<00:04,  6.52it/s]

 94%|█████████████████████████████████████████████████████████▌   | 462/490 [01:11<00:04,  6.54it/s]

 94%|█████████████████████████████████████████████████████████▋   | 463/490 [01:11<00:04,  6.56it/s]

 95%|█████████████████████████████████████████████████████████▊   | 464/490 [01:11<00:03,  6.50it/s]

 95%|█████████████████████████████████████████████████████████▉   | 465/490 [01:11<00:03,  6.45it/s]

 95%|██████████████████████████████████████████████████████████   | 466/490 [01:11<00:03,  6.50it/s]

 95%|██████████████████████████████████████████████████████████▏  | 467/490 [01:11<00:03,  6.53it/s]

 96%|██████████████████████████████████████████████████████████▎  | 468/490 [01:11<00:03,  6.55it/s]

 96%|██████████████████████████████████████████████████████████▍  | 469/490 [01:12<00:03,  6.57it/s]

 96%|██████████████████████████████████████████████████████████▌  | 470/490 [01:12<00:03,  6.54it/s]

 96%|██████████████████████████████████████████████████████████▋  | 471/490 [01:12<00:02,  6.57it/s]

 96%|██████████████████████████████████████████████████████████▊  | 472/490 [01:12<00:02,  6.53it/s]

 97%|██████████████████████████████████████████████████████████▉  | 473/490 [01:12<00:02,  6.55it/s]

 97%|███████████████████████████████████████████████████████████  | 474/490 [01:12<00:02,  6.55it/s]

 97%|███████████████████████████████████████████████████████████▏ | 475/490 [01:13<00:02,  6.58it/s]

 97%|███████████████████████████████████████████████████████████▎ | 476/490 [01:13<00:02,  6.59it/s]

 97%|███████████████████████████████████████████████████████████▍ | 477/490 [01:13<00:01,  6.59it/s]

 98%|███████████████████████████████████████████████████████████▌ | 478/490 [01:13<00:01,  6.59it/s]

 98%|███████████████████████████████████████████████████████████▋ | 479/490 [01:13<00:01,  6.60it/s]

 98%|███████████████████████████████████████████████████████████▊ | 480/490 [01:13<00:01,  6.61it/s]

 98%|███████████████████████████████████████████████████████████▉ | 481/490 [01:13<00:01,  6.60it/s]

 98%|████████████████████████████████████████████████████████████ | 482/490 [01:14<00:01,  6.60it/s]

 99%|████████████████████████████████████████████████████████████▏| 483/490 [01:14<00:01,  6.61it/s]

 99%|████████████████████████████████████████████████████████████▎| 484/490 [01:14<00:00,  6.61it/s]

 99%|████████████████████████████████████████████████████████████▍| 485/490 [01:14<00:00,  6.61it/s]

 99%|████████████████████████████████████████████████████████████▌| 486/490 [01:14<00:00,  6.59it/s]

 99%|████████████████████████████████████████████████████████████▋| 487/490 [01:14<00:00,  6.59it/s]

100%|████████████████████████████████████████████████████████████▊| 488/490 [01:14<00:00,  6.48it/s]

100%|████████████████████████████████████████████████████████████▉| 489/490 [01:15<00:00,  6.51it/s]

100%|█████████████████████████████████████████████████████████████| 490/490 [01:15<00:00,  6.54it/s]

100%|█████████████████████████████████████████████████████████████| 490/490 [01:15<00:00,  6.51it/s]

In [10]:
predictions = pd.concat(predictions, ignore_index=True)

In [11]:
display(predictions.shape)
display(predictions.head())

(335650, 8)

,trait,drug,score,true_class,method,n_top_genes,data,tissue
0,DOID:0050741,DB00215,200281.5,1,Gene-based,250.0,spredixcan-mashr-zscores-Kidney_Cortex-data,Kidney_Cortex
1,DOID:0050741,DB00704,319233.0,1,Gene-based,250.0,spredixcan-mashr-zscores-Kidney_Cortex-data,Kidney_Cortex
2,DOID:0050741,DB00822,343497.0,1,Gene-based,250.0,spredixcan-mashr-zscores-Kidney_Cortex-data,Kidney_Cortex
3,DOID:10283,DB00014,116486.0,1,Gene-based,250.0,spredixcan-mashr-zscores-Kidney_Cortex-data,Kidney_Cortex
4,DOID:10283,DB00175,148768.0,0,Gene-based,250.0,spredixcan-mashr-zscores-Kidney_Cortex-data,Kidney_Cortex

## Validation checks

In [12]:
assert not predictions.isna().any().any()

_tmp = predictions['method'].value_counts()
display(_tmp)

N_PREDICTIONS = predictions[['drug', 'trait']].drop_duplicates().shape[0]
display(f'Unique drug-disease pairs: {N_PREDICTIONS}')

assert _tmp.loc['Gene-based'] == N_TISSUES * N_THRESHOLDS * N_PREDICTIONS
assert _tmp.loc['Module-based'] == N_TISSUES * N_THRESHOLDS * N_PREDICTIONS

method
Gene-based      167825
Module-based    167825
Name: count, dtype: int64

'Unique drug-disease pairs: 685'

In [13]:
_tmp = predictions.groupby(['method', 'n_top_genes'], observed=True).count()
display(_tmp)
assert np.all(_tmp == N_TISSUES * N_PREDICTIONS)

                          trait   drug  score  true_class   data  tissue
method       n_top_genes
Gene-based   -1.0         33565  33565  33565       33565  33565   33565
              50.0        33565  33565  33565       33565  33565   33565
              100.0       33565  33565  33565       33565  33565   33565
              250.0       33565  33565  33565       33565  33565   33565
              500.0       33565  33565  33565       33565  33565   33565
Module-based -1.0         33565  33565  33565       33565  33565   33565
              5.0         33565  33565  33565       33565  33565   33565
              10.0        33565  33565  33565       33565  33565   33565
              25.0        33565  33565  33565       33565  33565   33565
              50.0        33565  33565  33565       33565  33565   33565

## Save raw predictions

In [14]:
output_file = OUTPUT_DIR / 'predictions' / 'predictions_results.pkl'
display(output_file)
predictions.to_pickle(output_file)

PosixPath('/home/msubirana/Documents/pivlab/clamp-analyses/output/drug_disease_analyses/lincs/predictions/predictions_results.pkl')

# Aggregate predictions

1. Average ranks across n_top_genes thresholds (per trait, drug, method, tissue).
2. Take maximum across tissues (per trait, drug, method).

This matches the PhenoPlier aggregation exactly.

In [15]:
def _reduce_mean(x):
    return pd.Series({
        'score': x['score'].mean(),
        'true_class': x['true_class'].unique()[0],
    })


def _reduce_max(x):
    return pd.Series({
        'score': x['score'].max(),
        'true_class': x['true_class'].unique()[0],
    })

In [16]:
predictions_avg = (
    # Step 1: average across n_top_genes thresholds
    predictions
    .groupby(['trait', 'drug', 'method', 'tissue'], observed=True)
    .apply(_reduce_mean, include_groups=False)
    .dropna()
    # Step 2: take maximum across tissues
    .groupby(['trait', 'drug', 'method'], observed=True)
    .apply(_reduce_max, include_groups=False)
    .dropna()
    .sort_index()
    .reset_index()
)

In [17]:
display(predictions_avg.shape)
display(predictions_avg.head())

# Should have exactly 2 × N_PREDICTIONS rows (one per method)
assert predictions_avg.shape[0] == 2 * N_PREDICTIONS
assert predictions_avg.dropna().shape == predictions_avg.shape

(1370, 5)

          trait     drug        method     score  true_class
0  DOID:0050741  DB00215    Gene-based  316134.3         1.0
1  DOID:0050741  DB00215  Module-based  353878.5         1.0
2  DOID:0050741  DB00704    Gene-based  387103.6         1.0
3  DOID:0050741  DB00704  Module-based  393946.6         1.0
4  DOID:0050741  DB00822    Gene-based  409053.0         1.0

## Save aggregated predictions

In [18]:
output_file = OUTPUT_DIR / 'predictions' / 'predictions_results_aggregated.pkl'
display(output_file)
predictions_avg.to_pickle(output_file)

PosixPath('/home/msubirana/Documents/pivlab/clamp-analyses/output/drug_disease_analyses/lincs/predictions/predictions_results_aggregated.pkl')

# ROC performance

In [19]:
# AUROC per method and n_top_genes threshold
predictions.groupby(['method', 'tissue', 'n_top_genes'], observed=True).apply(
    lambda x: roc_auc_score(x['true_class'], x['score']), include_groups=False
).groupby(['method', 'n_top_genes'], observed=True).describe()

                          count      mean       std       min       25%  \
method       n_top_genes
Gene-based   -1.0          49.0  0.549364  0.023679  0.504653  0.536803
              50.0         49.0  0.537231  0.023829  0.481431  0.522263
              100.0        49.0  0.536558  0.018923  0.487655  0.526958
              250.0        49.0  0.538607  0.023377  0.477309  0.521321
              500.0        49.0  0.540913  0.022241  0.500984  0.523131
Module-based -1.0          49.0  0.518573  0.022370  0.457572  0.504225
              5.0          49.0  0.536431  0.028108  0.476808  0.520551
              10.0         49.0  0.537466  0.031176  0.460348  0.523657
              25.0         49.0  0.533242  0.031503  0.481455  0.504751
              50.0         49.0  0.531007  0.025644  0.463662  0.512272

                               50%       75%       max
method       n_top_genes
Gene-based   -1.0         0.550034  0.564318  0.598705
              50.0        0.535861  0.552089  0.607265
              100.0       0.536619  0.550328  0.566788
              250.0       0.539738  0.556467  0.583908
              500.0       0.544030  0.556442  0.598693
Module-based -1.0         0.519352  0.532278  0.573379
              5.0         0.533464  0.551294  0.621707
              10.0        0.539884  0.559304  0.613135
              25.0        0.536387  0.550218  0.635709
              50.0        0.529612  0.553630  0.586904

In [20]:
# Final AUROC using aggregated predictions
auroc_final = predictions_avg.groupby('method', observed=True).apply(
    lambda x: roc_auc_score(x['true_class'], x['score']), include_groups=False
).rename('AUROC')
display(auroc_final)

method
Gene-based      0.583382
Module-based    0.605737
Name: AUROC, dtype: float64

These are the final performance measures using AUROC.

# Precision-Recall performance

In [21]:
# Average precision per method and n_top_genes threshold
predictions.groupby(['method', 'tissue', 'n_top_genes'], observed=True).apply(
    lambda x: average_precision_score(x['true_class'], x['score']), include_groups=False
).groupby(['method', 'n_top_genes'], observed=True).describe()

                          count      mean       std       min       25%  \
method       n_top_genes
Gene-based   -1.0          49.0  0.823048  0.012367  0.791177  0.817139
              50.0         49.0  0.819142  0.011775  0.793504  0.811550
              100.0        49.0  0.819522  0.010505  0.782200  0.812821
              250.0        49.0  0.820481  0.012213  0.788298  0.812494
              500.0        49.0  0.820813  0.011201  0.801469  0.814246
Module-based -1.0          49.0  0.806810  0.012836  0.776331  0.796252
              5.0          49.0  0.812129  0.017114  0.776060  0.801291
              10.0         49.0  0.813750  0.018278  0.775588  0.800520
              25.0         49.0  0.813229  0.018512  0.778483  0.800619
              50.0         49.0  0.811462  0.016060  0.766112  0.799672

                               50%       75%       max
method       n_top_genes
Gene-based   -1.0         0.822989  0.828268  0.845962
              50.0        0.818870  0.827690  0.850680
              100.0       0.820163  0.825928  0.837381
              250.0       0.820298  0.829858  0.841266
              500.0       0.819441  0.828770  0.849463
Module-based -1.0         0.807951  0.817486  0.830619
              5.0         0.809984  0.821604  0.861639
              10.0        0.813314  0.829202  0.857331
              25.0        0.813917  0.826922  0.865645
              50.0        0.810987  0.822886  0.845370

In [22]:
# Final average precision using aggregated predictions
ap_final = predictions_avg.groupby('method', observed=True).apply(
    lambda x: average_precision_score(x['true_class'], x['score']), include_groups=False
).rename('AvgPrecision')
display(ap_final)

method
Gene-based      0.844942
Module-based    0.837282
Name: AvgPrecision, dtype: float64

These are the final performance measures using average precision.

# Summary

In [23]:
summary = pd.concat([auroc_final, ap_final], axis=1)
display(summary)

                 AUROC  AvgPrecision
method
Gene-based    0.583382      0.844942
Module-based  0.605737      0.837282