# ARCHS4 Biology Validation

Identify tissue- and cell-type-enriched LVs in ARCHS4 bulk RNA-seq data.
For each query, samples are matched by keyword in `source_name_ch1` / `characteristics_ch1`,
LVs are ranked by enrichment ratio in the top 1%, and significant hits are linked to pathways and GWAS traits.

💡 **Environment:** `clamp-analyses`

In [1]:
import re
import textwrap

import h5py
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import matplotlib.gridspec as gridspec
from matplotlib.colors import LinearSegmentedColormap, Normalize
from matplotlib.cm import ScalarMappable
from matplotlib.lines import Line2D
import seaborn as sns
from scipy.stats import mannwhitneyu
from statsmodels.stats.multitest import multipletests

from pyprojroot.here import here

import rpy2.robjects as ro
from rpy2.robjects.conversion import localconverter
from rpy2.robjects import pandas2ri

readRDS = ro.r["readRDS"]

## Settings

In [2]:
# ── pathway display thresholds ────────────────────────────────────────────────
FDR_THRESH_PATHWAYS  = 0.1    # pathway FDR cutoff
AUC_THRESH_PATHWAYS  = 0.6    # pathway AUC cutoff
SC_PROB_THRESH       = 0.5    # exclude samples with single-cell probability ≥ this

# ── LV selection (data-driven) ─────────────────────────────────────────────────
TOP_PERC             = 0.01   # top-1% window defines the "enriched" zone
FDR_THRESH_LVS       = 0.05   # Mann-Whitney FDR threshold for LV selection
ENRICH_RATIO_THRESH  = 2.0    # minimum enrichment ratio (observed / expected)
MIN_SAMPLES          = 10     # skip queries with fewer samples than this
MIN_N_IN_TOP1PCT     = 20     # minimum samples in top 1% for an LV to be selected

## Load archs4 model

In [3]:
def extract_B_matrix(rds_obj):
    B_matrix = rds_obj.rx2("B")
    with localconverter(ro.default_converter + pandas2ri.converter):
        B_values = ro.conversion.rpy2py(B_matrix)
    return pd.DataFrame(
        data=B_values,
        index=B_matrix.rownames if B_matrix.rownames else None,
        columns=B_matrix.colnames if B_matrix.colnames else None,
    )


def extract_summary_matrix(rds_obj):
    summary_matrix = rds_obj.rx2("summary")
    with localconverter(ro.default_converter + pandas2ri.converter):
        summary_values = ro.conversion.rpy2py(summary_matrix)
    return pd.DataFrame(
        data=summary_values,
        index=summary_matrix.rownames if summary_matrix.rownames else None,
        columns=summary_matrix.colnames if summary_matrix.colnames else None,
    )


model_rds = readRDS(str(here("output/archs4/c2cp_coverage_rs100_seed_1/CLAMPfull_C2CP.rds")))

# B matrix: rows = LVs, cols = samples → transpose to samples × LVs
B_df      = extract_B_matrix(model_rds)
lv_matrix = B_df.T

# Summary matrix: pathway–LV associations
summary_df = extract_summary_matrix(model_rds)
if "lv" in summary_df.columns and "LV" not in summary_df.columns:
    summary_df = summary_df.rename(columns={"lv": "LV"})

print(f"lv_matrix : {lv_matrix.shape}  (samples × LVs)")
print(f"summary_df: {summary_df.shape}")
print(f"summary columns: {summary_df.columns.tolist()}")
lv_matrix.head()

model_rds = None
B_df = None

import gc
gc.collect()

lv_matrix : (605614, 1728)  (samples × LVs)
summary_df: (9100, 7)
summary columns: ['pathway', 'LV', 'AUC', 'p_value', 'FDR', 'npos', 'nneg']

218

## ARCHS4 metadata & analysis helpers

Load sample-level metadata from the h5 file once, pre-extract the B matrix, and
define the `analyze(label, keyword)` helper that runs the full pipeline for any tissue or cell type.

In [4]:
h5_path = str(here("data/archs4/human_gene_v2.5.h5"))

def _decode(arr):
    return np.array([x.decode("utf-8", errors="replace") for x in arr])

with h5py.File(h5_path, "r") as f:
    geo_acc = _decode(f["meta/samples/geo_accession"][:])
    source  = _decode(f["meta/samples/source_name_ch1"][:])
    char    = _decode(f["meta/samples/characteristics_ch1"][:])
    sc_prob = f["meta/samples/singlecellprobability"][:]

# Pre-extract B matrix array for fast per-LV operations
B_arr   = lv_matrix.values
n_total = len(lv_matrix)
K_1pct  = max(1, int(round(n_total * TOP_PERC)))

print(f"Metadata loaded : {len(geo_acc):,} samples")
print(f"B matrix        : {B_arr.shape}  (samples × LVs)")
print(f"Top-1% window   : {K_1pct:,} samples")

Metadata loaded : 888,821 samples
B matrix        : (605614, 1728)  (samples × LVs)
Top-1% window   : 6,056 samples

In [5]:
def get_samples(keyword):
    """Return GSM IDs matching `keyword` in source or characteristics (bulk only)."""
    kw   = keyword.lower()
    mask = (
        (np.char.find(np.char.lower(source), kw) >= 0) |
        (np.char.find(np.char.lower(char),   kw) >= 0)
    ) & (sc_prob < SC_PROB_THRESH)
    gsms = geo_acc[mask].tolist()
    return [s for s in gsms if s in lv_matrix.index]


def compute_lv_enrichment(available_gsms):
    """Mann-Whitney enrichment of available_gsms across all LVs. Returns sorted DataFrame."""
    n_interest     = len(available_gsms)
    interest_idx   = np.array([lv_matrix.index.get_loc(s) for s in available_gsms])
    background_idx = np.setdiff1d(np.arange(n_total), interest_idx)
    i_vals         = B_arr[interest_idx, :]
    b_vals         = B_arr[background_idx, :]

    rows = []
    for j, lv in enumerate(lv_matrix.columns):
        col            = B_arr[:, j]
        threshold_1pct = np.partition(col, -K_1pct)[-K_1pct]
        n_in_top       = int((i_vals[:, j] >= threshold_1pct).sum())
        obs_prop       = n_in_top / n_interest
        enrich_ratio   = obs_prop / (K_1pct / n_total)

        sorted_col      = np.sort(col)
        ranks_from_top  = n_total - np.searchsorted(sorted_col, i_vals[:, j], side="left")
        median_rank_pct = float(np.median(ranks_from_top)) / n_total

        stat, pval = mannwhitneyu(i_vals[:, j], b_vals[:, j], alternative="greater")
        auc        = stat / (len(interest_idx) * len(background_idx))

        rows.append({
            "LV": lv, "n_in_top1pct": n_in_top,
            "prop_in_top1pct": round(obs_prop, 4),
            "enrich_ratio": round(enrich_ratio, 3),
            "median_rank_pct": round(median_rank_pct, 4),
            "AUC": auc, "pvalue": pval,
        })

    res = pd.DataFrame(rows)
    _, res["FDR"], _, _ = multipletests(res["pvalue"], method="fdr_bh")
    return res.sort_values("enrich_ratio", ascending=False)


def analyze(label, keyword):
    """Full pipeline: find samples → enrich LVs → display pathways.
    Returns the pathways DataFrame for the selected LVs."""
    pd.set_option("display.max_rows", None)
    pd.set_option("display.max_colwidth", None)

    available = get_samples(keyword)
    print(f"{'─'*64}")
    print(f"  {label}  (keyword: '{keyword}')  |  samples in model: {len(available):,}")

    if len(available) < MIN_SAMPLES:
        print(f"  ⚠ fewer than {MIN_SAMPLES} samples – skipping.")
        return None

    res_df   = compute_lv_enrichment(available)
    top_lvs  = res_df[
        (res_df["FDR"] < FDR_THRESH_LVS) &
        (res_df["enrich_ratio"] >= ENRICH_RATIO_THRESH) &
        (res_df["n_in_top1pct"] >= MIN_N_IN_TOP1PCT)
    ].copy()
    names    = top_lvs["LV"].tolist()
    expected = K_1pct * len(available) / n_total

    print(f"  Expected in top 1%: {expected:.1f}  |  Selected LVs: {len(top_lvs)}")
    display(top_lvs[["LV", "n_in_top1pct", "enrich_ratio",
                      "median_rank_pct", "AUC", "FDR"]].reset_index(drop=True))

    # pathways
    summ = summary_df[
        summary_df["LV"].isin(names) &
        (summary_df["AUC"] > AUC_THRESH_PATHWAYS) &
        (summary_df["FDR"] < FDR_THRESH_PATHWAYS)
    ]
    print("\n  Pathways:")
    if summ.empty:
        print("  (none)")
    else:
        display(summ[["LV", "pathway", "AUC", "FDR"]].sort_values(["LV", "FDR"]).reset_index(drop=True))

    return summ[["LV", "pathway", "AUC", "FDR"]].sort_values(["LV", "FDR"]).reset_index(drop=True)

## Tissues

In [6]:
adipose_pathways = analyze("Adipose", "adipose")

────────────────────────────────────────────────────────────────
  Adipose  (keyword: 'adipose')  |  samples in model: 4,000
  Expected in top 1%: 40.0  |  Selected LVs: 83

,LV,n_in_top1pct,enrich_ratio,median_rank_pct,AUC,FDR
0,LV1293,748,18.700,0.3631,0.604907,1.856156e-114
1,LV1659,683,17.075,0.4568,0.554474,4.625716e-32
2,LV680,681,17.025,0.4470,0.540987,8.799496e-19
3,LV1286,676,16.900,0.4093,0.585488,1.211858e-76
4,LV60,674,16.850,0.4466,0.561737,1.026145e-40
5,LV1033,652,16.300,0.4961,0.552450,7.767644e-30
6,LV648,604,15.100,0.3657,0.587005,2.554572e-79
7,LV1253,595,14.875,0.4144,0.583671,1.823488e-73
8,LV651,567,14.175,0.5134,0.540080,5.058537e-18
9,LV35,543,13.575,0.2391,0.639723,5.440358e-202
10,LV256,472,11.800,0.4636,0.563380,8.108359e-43
11,LV1599,450,11.250,0.3019,0.616597,4.662010e-141
12,LV88,433,10.825,0.2108,0.669955,1.551344e-298
13,LV907,330,8.250,0.3099,0.609216,5.988234e-124
14,LV1116,291,7.275,0.3024,0.615943,1.594337e-139
15,LV272,223,5.575,0.3532,0.598888,6.863661e-102
16,LV1012,219,5.475,0.3863,0.579187,5.884169e-66
17,LV231,219,5.475,0.3980,0.589116,4.160614e-83
18,LV1409,211,5.275,0.3771,0.587620,2.062757e-80
19,LV1342,204,5.100,0.3417,0.595891,6.158214e-96
20,LV180,199,4.975,0.4067,0.555554,2.816138e-33
21,LV262,198,4.950,0.4802,0.564163,7.759669e-44
22,LV729,191,4.775,0.5089,0.537022,1.387698e-15
23,LV732,176,4.400,0.4214,0.510348,2.842058e-02
24,LV359,171,4.275,0.3636,0.587202,1.144632e-79
25,LV137,163,4.075,0.4281,0.567992,4.767389e-49
26,LV333,159,3.975,0.3489,0.594291,7.922631e-93
27,LV376,152,3.800,0.4812,0.511518,1.443902e-02
28,LV636,149,3.725,0.4189,0.520681,9.344510e-06
29,LV27,148,3.700,0.5284,0.509469,4.520508e-02
30,LV1345,147,3.675,0.3757,0.563657,3.528978e-43
31,LV599,145,3.625,0.4129,0.559303,1.120254e-37
32,LV81,145,3.625,0.4226,0.535830,1.072836e-14
33,LV1407,145,3.625,0.5057,0.514127,2.611105e-03
34,LV1247,141,3.525,0.4436,0.527160,5.261033e-09
35,LV1084,140,3.500,0.4691,0.511552,1.415628e-02
36,LV533,139,3.475,0.3992,0.594149,1.459311e-92
37,LV1103,137,3.425,0.2561,0.636966,3.309903e-194
38,LV817,135,3.375,0.4446,0.518126,1.053050e-04
39,LV633,134,3.350,0.4402,0.548101,2.514038e-25
40,LV1255,133,3.325,0.2931,0.620542,1.327687e-150
41,LV302,133,3.325,0.3388,0.581842,2.337796e-70
42,LV187,132,3.300,0.4639,0.537100,1.210547e-15
43,LV943,128,3.200,0.4134,0.546466,9.951926e-24
44,LV1427,128,3.200,0.4592,0.535613,1.553969e-14
45,LV497,124,3.100,0.3656,0.553909,1.963326e-31
46,LV641,116,2.900,0.4452,0.511649,1.336139e-02
47,LV758,115,2.875,0.4130,0.565166,3.632404e-45
48,LV602,114,2.850,0.4077,0.566837,1.909712e-47
49,LV1431,112,2.800,0.2972,0.604124,7.944815e-113
50,LV1567,111,2.775,0.4231,0.539117,3.140285e-17
51,LV1280,110,2.750,0.4718,0.542713,2.853301e-20
52,LV839,108,2.700,0.3996,0.556800,1.050844e-34
53,LV545,106,2.650,0.4442,0.538260,1.512893e-16
54,LV1490,105,2.625,0.4772,0.549871,4.101962e-27
55,LV1473,103,2.575,0.4787,0.544389,8.701374e-22
56,LV115,100,2.500,0.3765,0.556425,2.849386e-34
57,LV385,99,2.475,0.4204,0.526001,2.303477e-08
58,LV124,99,2.475,0.4178,0.562444,1.303223e-41
59,LV367,98,2.450,0.4807,0.541003,8.543834e-19
60,LV1395,96,2.400,0.4178,0.573146,1.622108e-56
61,LV1217,94,2.350,0.4387,0.547247,1.740774e-24
62,LV1088,94,2.350,0.3559,0.583066,1.918572e-72
63,LV274,93,2.325,0.4034,0.533977,2.385527e-13
64,LV1242,92,2.300,0.3696,0.569804,1.280958e-51
65,LV336,92,2.300,0.3842,0.555695,1.959182e-33
66,LV555,92,2.300,0.3820,0.562505,1.095396e-41
67,LV69,91,2.275,0.3982,0.564544,2.458929e-44
68,LV924,90,2.250,0.4377,0.535201,3.106408e-14
69,LV1312,89,2.225,0.4041,0.575116,1.633397e-59
70,LV933,89,2.225,0.4502,0.520874,7.687488e-06
71,LV328,88,2.200,0.4965,0.549879,4.054623e-27
72,LV1611,87,2.175,0.3880,0.558514,9.866323e-37
73,LV654,85,2.125,0.4028,0.567610,1.620117e-48
74,LV1466,84,2.100,0.3914,0.594390,5.212350e-93
75,LV413,84,2.100,0.2830,0.632285,3.059814e-181
76,LV1685,83,2.075,0.4542,0.521595,3.648969e-06
77,LV423,83,2.075,0.4993,0.532377,3.037059e-12
78,LV514,83,2.075,0.3725,0.574998,2.419356e-59
79,LV73,82,2.050,0.3575,0.604041,1.148265e-112
80,LV598,81,2.025,0.3712,0.559964,1.709537e-38
81,LV192,81,2.025,0.3853,0.554038,1.418069e-31
82,LV93,81,2.025,0.2822,0.600489,3.612873e-105

  Pathways:

,LV,pathway,AUC,FDR
0,LV1012,C2CP_REACTOME_ABC_TRANSPORTERS_IN_LIPID_HOMEOSTASIS,0.906881,5.141231e-02
1,LV1012,C2CP_REACTOME_BUTYROPHILIN_BTN_FAMILY_INTERACTIONS,0.940989,7.283398e-02
2,LV1103,C2CP_REACTOME_ANTIGEN_PROCESSING_UB_ATP_INDEPENDENT_PROTEASOMAL_DEGRADATION,0.871444,6.564056e-02
3,LV1253,C2CP_KEGG_MEDICUS_REFERENCE_CXCR4_GNAQ_PLCB_G_CALCINEURIN_SIGNALING_PATHWAY,0.818197,7.144923e-02
4,LV1286,C2CP_BIOCARTA_P53_PATHWAY,0.994411,1.676426e-02
5,LV1286,C2CP_KEGG_MEDICUS_VARIANT_AMPLIFIED_MDM2_TO_P21_CELL_CYCLE_G1_S,1.000000,5.605625e-02
6,LV1286,C2CP_BIOCARTA_HCMV_PATHWAY,0.880063,6.697323e-02
7,LV1286,C2CP_BIOCARTA_RB_PATHWAY,0.940767,8.163289e-02
8,LV1342,C2CP_WP_OVERVIEW_OF_PROINFLAMMATORY_AND_PROFIBROTIC_MEDIATORS,0.737190,1.758426e-02
9,LV1342,C2CP_WP_OVERVIEW_OF_NANOPARTICLE_EFFECTS,0.847604,9.399659e-02
10,LV137,C2CP_REACTOME_TYPE_I_HEMIDESMOSOME_ASSEMBLY,0.997759,5.640270e-02
11,LV137,C2CP_PID_WNT_SIGNALING_PATHWAY,0.797860,9.665312e-02
12,LV1407,C2CP_KEGG_MEDICUS_REFERENCE_ANTIGEN_PROCESSING_AND_PRESENTATION_BY_MHC_CLASS_I_MOLECULES,1.000000,4.532077e-02
13,LV1431,C2CP_WP_17Q12_COPY_NUMBER_VARIATION_SYNDROME,0.750526,1.126258e-02
14,LV1599,C2CP_REACTOME_RHO_GTPASES_ACTIVATE_IQGAPS,0.894907,1.839603e-02
15,LV1611,C2CP_BIOCARTA_D4GDI_PATHWAY,0.916667,8.654483e-02
16,LV1659,C2CP_REACTOME_METABOLISM_OF_PORPHYRINS,0.913650,2.315255e-02
17,LV1659,C2CP_REACTOME_FOXO_MEDIATED_TRANSCRIPTION_OF_CELL_CYCLE_GENES,0.936435,4.416023e-02
18,LV1659,C2CP_BIOCARTA_HES_PATHWAY,0.992874,5.873577e-02
19,LV1659,C2CP_REACTOME_SPECIFICATION_OF_THE_NEURAL_PLATE_BORDER,0.933514,9.041112e-02
20,LV1685,C2CP_REACTOME_P130CAS_LINKAGE_TO_MAPK_SIGNALING_FOR_INTEGRINS,0.991889,5.633647e-02
21,LV256,C2CP_REACTOME_DEVELOPMENTAL_LINEAGES_OF_THE_MAMMARY_GLAND,0.929677,3.142651e-03
22,LV256,C2CP_REACTOME_DEVELOPMENTAL_LINEAGE_OF_MAMMARY_GLAND_LUMINAL_EPITHELIAL_CELLS,1.000000,5.325240e-03
23,LV262,C2CP_REACTOME_EUKARYOTIC_TRANSLATION_ELONGATION,0.999637,1.016828e-11
24,LV262,C2CP_KEGG_RIBOSOME,0.996339,2.253240e-11
25,LV262,C2CP_KEGG_MEDICUS_REFERENCE_TRANSLATION_INITIATION,1.000000,5.758980e-11
26,LV262,C2CP_REACTOME_RESPONSE_OF_EIF2AK4_GCN2_TO_AMINO_ACID_DEFICIENCY,0.946340,5.910003e-11
27,LV262,C2CP_REACTOME_SRP_DEPENDENT_COTRANSLATIONAL_PROTEIN_TARGETING_TO_MEMBRANE,0.925490,5.910003e-11
28,LV262,C2CP_WP_CYTOPLASMIC_RIBOSOMAL_PROTEINS,0.954451,1.044809e-09
29,LV262,C2CP_REACTOME_NONSENSE_MEDIATED_DECAY_NMD,0.821030,2.615477e-06
30,LV262,C2CP_REACTOME_SARS_COV_2_MODULATES_HOST_TRANSLATION_MACHINERY,0.921941,4.695374e-05
31,LV262,C2CP_REACTOME_SARS_COV_1_MODULATES_HOST_TRANSLATION_MACHINERY,0.889413,3.134005e-03
32,LV262,C2CP_REACTOME_ANTIGEN_PROCESSING_UB_ATP_INDEPENDENT_PROTEASOMAL_DEGRADATION,0.940996,4.076255e-02
33,LV27,C2CP_REACTOME_DEVELOPMENTAL_LINEAGE_OF_MAMMARY_GLAND_LUMINAL_EPITHELIAL_CELLS,0.813456,7.990979e-02
34,LV272,C2CP_KEGG_MEDICUS_REFERENCE_KEAP1_NRF2_SIGNALING_PATHWAY,0.895403,2.779711e-02
35,LV272,C2CP_WP_TRANSCRIPTIONAL_ACTIVATION_BY_NRF2_IN_RESPONSE_TO_PHYTOCHEMICALS,1.000000,5.513184e-02
36,LV302,C2CP_KEGG_MEDICUS_VARIANT_SCRAPIE_CONFORMATION_PRPSC_TO_26S_PROTEASOME_MEDIATED_PROTEIN_DEGRADATION,0.981859,4.324363e-05
37,LV302,C2CP_KEGG_MEDICUS_VARIANT_MUTATION_CAUSED_ABERRANT_ABETA_TO_26S_PROTEASOME_MEDIATED_PROTEIN_DEGRADATION,0.967561,8.071935e-05
38,LV302,C2CP_KEGG_MEDICUS_VARIANT_MUTATION_CAUSED_ABERRANT_SOD1_TO_26S_PROTEASOME_MEDIATED_PROTEIN_DEGRADATION,0.876920,9.837169e-04
39,LV302,C2CP_KEGG_PROTEASOME,0.852715,2.513417e-03
40,LV302,C2CP_KEGG_MEDICUS_VARIANT_MUTATION_INACTIVATED_VCP_TO_26S_PROTEASOME_MEDIATED_PROTEIN_DEGRADATION,0.876941,2.513417e-03
41,LV302,C2CP_REACTOME_REGULATION_OF_ORNITHINE_DECARBOXYLASE_ODC,0.859687,4.382892e-03
42,LV35,C2CP_REACTOME_FORMATION_OF_ATP_BY_CHEMIOSMOTIC_COUPLING,0.829779,6.543205e-02
43,LV359,C2CP_REACTOME_DEVELOPMENTAL_LINEAGE_OF_MAMMARY_GLAND_LUMINAL_EPITHELIAL_CELLS,0.854887,5.495029e-02
44,LV359,C2CP_WP_MAMMARY_GLAND_DEVELOPMENT_PUBERTY_STAGE_2_OF_4,0.980010,5.953757e-02
45,LV367,C2CP_BIOCARTA_GRANULOCYTES_PATHWAY,0.985683,5.586174e-02
46,LV413,C2CP_REACTOME_POU5F1_OCT4_SOX2_NANOG_ACTIVATE_GENES_RELATED_TO_PROLIFERATION,0.930090,8.129753e-02
47,LV497,C2CP_BIOCARTA_SM_PATHWAY,0.933180,7.504429e-02
48,LV497,C2CP_REACTOME_FOLDING_OF_ACTIN_BY_CCT_TRIC,0.918827,8.533668e-02
49,LV514,C2CP_REACTOME_XENOBIOTICS,0.982208,5.728160e-02
50,LV533,C2CP_KEGG_CIRCADIAN_RHYTHM_MAMMAL,1.000000,5.756743e-02
51,LV598,C2CP_KEGG_MEDICUS_VARIANT_AMPLIFIED_PDGFR_TO_PLCG_CAMK_SIGNALING_PATHWAY,0.974229,5.880048e-02
52,LV599,C2CP_WP_RETT_SYNDROME,0.728491,6.377020e-02
53,LV60,C2CP_KEGG_MEDICUS_REFERENCE_REGULATION_OF_GF_RTK_RAS_ERK_SIGNALING_UBIQUITINATION_OF_RTK_BY_CBL,0.962128,3.628320e-04
54,LV60,C2CP_KEGG_MEDICUS_VARIANT_MUTATION_CAUSED_ABERRANT_ABETA_TO_CROSSTALK_BETWEEN_EXTRINSIC_AND_INTRINSIC_APOPTOTIC_PATHWAYS,0.979768,3.406581e-02
55,LV60,C2CP_REACTOME_REGULATION_OF_GENE_EXPRESSION_IN_BETA_CELLS,0.965168,4.206842e-02
56,LV60,C2CP_WP_TRANSCRIPTION_FACTOR_REGULATION_IN_ADIPOGENESIS,0.809622,5.586174e-02
57,LV633,C2CP_WP_SRF_AND_MIRS_IN_SMOOTH_MUSCLE_DIFFERENTIATION_AND_PROLIFERATION,0.930328,9.004953e-02
58,LV636,C2CP_BIOCARTA_ASBCELL_PATHWAY,0.998554,2.283026e-02
59,LV636,C2CP_BIOCARTA_HSP27_PATHWAY,0.885148,7.696031e-02
60,LV648,C2CP_WP_UNFOLDED_PROTEIN_RESPONSE,0.954632,9.220328e-03
61,LV648,C2CP_REACTOME_REGULATION_OF_FOXO_TRANSCRIPTIONAL_ACTIVITY_BY_ACETYLATION,0.953978,7.039529e-02
62,LV648,C2CP_PID_NFKAPPAB_ATYPICAL_PATHWAY,0.843827,9.210761e-02
63,LV651,C2CP_REACTOME_PHOSPHORYLATION_OF_CLOCK_ACETYLATION_OF_BMAL1_ARNTL_AT_TARGET_GENE_PROMOTERS,0.956523,7.649308e-02
64,LV651,C2CP_BIOCARTA_IL17_PATHWAY,0.945279,8.418068e-02
65,LV651,C2CP_BIOCARTA_CTL_PATHWAY,0.926250,9.781409e-02
66,LV654,C2CP_REACTOME_DISSOLUTION_OF_FIBRIN_CLOT,0.983725,6.742913e-02
67,LV680,C2CP_PID_ERBB_NETWORK_PATHWAY,1.000000,6.017376e-02
68,LV680,C2CP_REACTOME_ERBB2_ACTIVATES_PTK6_SIGNALING,1.000000,6.017376e-02
69,LV680,C2CP_REACTOME_ERBB2_REGULATES_CELL_MOTILITY,1.000000,6.017376e-02
70,LV729,C2CP_KEGG_MEDICUS_PATHOGEN_HPV_E6_TO_NOTCH_SIGNALING_PATHWAY_N00380,1.000000,6.017376e-02
71,LV729,C2CP_KEGG_MEDICUS_PATHOGEN_HPV_E6_TO_NOTCH_SIGNALING_PATHWAY_N00382,1.000000,6.017376e-02
72,LV73,C2CP_WP_LTF_DANGER_SIGNAL_RESPONSE_PATHWAY,0.982757,2.001041e-02
73,LV758,C2CP_WP_PROSTAGLANDIN_SYNTHESIS_AND_REGULATION,0.901514,3.169349e-03
74,LV758,C2CP_WP_OMEGA6FATTY_ACIDS_IN_SENESCENCE,0.809301,1.261205e-02
75,LV839,C2CP_BIOCARTA_CLASSIC_PATHWAY,1.000000,5.586174e-02

In [7]:
adipose_pathways

,LV,pathway,AUC,FDR
0,LV1012,C2CP_REACTOME_ABC_TRANSPORTERS_IN_LIPID_HOMEOSTASIS,0.906881,5.141231e-02
1,LV1012,C2CP_REACTOME_BUTYROPHILIN_BTN_FAMILY_INTERACTIONS,0.940989,7.283398e-02
2,LV1103,C2CP_REACTOME_ANTIGEN_PROCESSING_UB_ATP_INDEPENDENT_PROTEASOMAL_DEGRADATION,0.871444,6.564056e-02
3,LV1253,C2CP_KEGG_MEDICUS_REFERENCE_CXCR4_GNAQ_PLCB_G_CALCINEURIN_SIGNALING_PATHWAY,0.818197,7.144923e-02
4,LV1286,C2CP_BIOCARTA_P53_PATHWAY,0.994411,1.676426e-02
5,LV1286,C2CP_KEGG_MEDICUS_VARIANT_AMPLIFIED_MDM2_TO_P21_CELL_CYCLE_G1_S,1.000000,5.605625e-02
6,LV1286,C2CP_BIOCARTA_HCMV_PATHWAY,0.880063,6.697323e-02
7,LV1286,C2CP_BIOCARTA_RB_PATHWAY,0.940767,8.163289e-02
8,LV1342,C2CP_WP_OVERVIEW_OF_PROINFLAMMATORY_AND_PROFIBROTIC_MEDIATORS,0.737190,1.758426e-02
9,LV1342,C2CP_WP_OVERVIEW_OF_NANOPARTICLE_EFFECTS,0.847604,9.399659e-02
10,LV137,C2CP_REACTOME_TYPE_I_HEMIDESMOSOME_ASSEMBLY,0.997759,5.640270e-02
11,LV137,C2CP_PID_WNT_SIGNALING_PATHWAY,0.797860,9.665312e-02
12,LV1407,C2CP_KEGG_MEDICUS_REFERENCE_ANTIGEN_PROCESSING_AND_PRESENTATION_BY_MHC_CLASS_I_MOLECULES,1.000000,4.532077e-02
13,LV1431,C2CP_WP_17Q12_COPY_NUMBER_VARIATION_SYNDROME,0.750526,1.126258e-02
14,LV1599,C2CP_REACTOME_RHO_GTPASES_ACTIVATE_IQGAPS,0.894907,1.839603e-02
15,LV1611,C2CP_BIOCARTA_D4GDI_PATHWAY,0.916667,8.654483e-02
16,LV1659,C2CP_REACTOME_METABOLISM_OF_PORPHYRINS,0.913650,2.315255e-02
17,LV1659,C2CP_REACTOME_FOXO_MEDIATED_TRANSCRIPTION_OF_CELL_CYCLE_GENES,0.936435,4.416023e-02
18,LV1659,C2CP_BIOCARTA_HES_PATHWAY,0.992874,5.873577e-02
19,LV1659,C2CP_REACTOME_SPECIFICATION_OF_THE_NEURAL_PLATE_BORDER,0.933514,9.041112e-02
20,LV1685,C2CP_REACTOME_P130CAS_LINKAGE_TO_MAPK_SIGNALING_FOR_INTEGRINS,0.991889,5.633647e-02
21,LV256,C2CP_REACTOME_DEVELOPMENTAL_LINEAGES_OF_THE_MAMMARY_GLAND,0.929677,3.142651e-03
22,LV256,C2CP_REACTOME_DEVELOPMENTAL_LINEAGE_OF_MAMMARY_GLAND_LUMINAL_EPITHELIAL_CELLS,1.000000,5.325240e-03
23,LV262,C2CP_REACTOME_EUKARYOTIC_TRANSLATION_ELONGATION,0.999637,1.016828e-11
24,LV262,C2CP_KEGG_RIBOSOME,0.996339,2.253240e-11
25,LV262,C2CP_KEGG_MEDICUS_REFERENCE_TRANSLATION_INITIATION,1.000000,5.758980e-11
26,LV262,C2CP_REACTOME_RESPONSE_OF_EIF2AK4_GCN2_TO_AMINO_ACID_DEFICIENCY,0.946340,5.910003e-11
27,LV262,C2CP_REACTOME_SRP_DEPENDENT_COTRANSLATIONAL_PROTEIN_TARGETING_TO_MEMBRANE,0.925490,5.910003e-11
28,LV262,C2CP_WP_CYTOPLASMIC_RIBOSOMAL_PROTEINS,0.954451,1.044809e-09
29,LV262,C2CP_REACTOME_NONSENSE_MEDIATED_DECAY_NMD,0.821030,2.615477e-06
30,LV262,C2CP_REACTOME_SARS_COV_2_MODULATES_HOST_TRANSLATION_MACHINERY,0.921941,4.695374e-05
31,LV262,C2CP_REACTOME_SARS_COV_1_MODULATES_HOST_TRANSLATION_MACHINERY,0.889413,3.134005e-03
32,LV262,C2CP_REACTOME_ANTIGEN_PROCESSING_UB_ATP_INDEPENDENT_PROTEASOMAL_DEGRADATION,0.940996,4.076255e-02
33,LV27,C2CP_REACTOME_DEVELOPMENTAL_LINEAGE_OF_MAMMARY_GLAND_LUMINAL_EPITHELIAL_CELLS,0.813456,7.990979e-02
34,LV272,C2CP_KEGG_MEDICUS_REFERENCE_KEAP1_NRF2_SIGNALING_PATHWAY,0.895403,2.779711e-02
35,LV272,C2CP_WP_TRANSCRIPTIONAL_ACTIVATION_BY_NRF2_IN_RESPONSE_TO_PHYTOCHEMICALS,1.000000,5.513184e-02
36,LV302,C2CP_KEGG_MEDICUS_VARIANT_SCRAPIE_CONFORMATION_PRPSC_TO_26S_PROTEASOME_MEDIATED_PROTEIN_DEGRADATION,0.981859,4.324363e-05
37,LV302,C2CP_KEGG_MEDICUS_VARIANT_MUTATION_CAUSED_ABERRANT_ABETA_TO_26S_PROTEASOME_MEDIATED_PROTEIN_DEGRADATION,0.967561,8.071935e-05
38,LV302,C2CP_KEGG_MEDICUS_VARIANT_MUTATION_CAUSED_ABERRANT_SOD1_TO_26S_PROTEASOME_MEDIATED_PROTEIN_DEGRADATION,0.876920,9.837169e-04
39,LV302,C2CP_KEGG_PROTEASOME,0.852715,2.513417e-03
40,LV302,C2CP_KEGG_MEDICUS_VARIANT_MUTATION_INACTIVATED_VCP_TO_26S_PROTEASOME_MEDIATED_PROTEIN_DEGRADATION,0.876941,2.513417e-03
41,LV302,C2CP_REACTOME_REGULATION_OF_ORNITHINE_DECARBOXYLASE_ODC,0.859687,4.382892e-03
42,LV35,C2CP_REACTOME_FORMATION_OF_ATP_BY_CHEMIOSMOTIC_COUPLING,0.829779,6.543205e-02
43,LV359,C2CP_REACTOME_DEVELOPMENTAL_LINEAGE_OF_MAMMARY_GLAND_LUMINAL_EPITHELIAL_CELLS,0.854887,5.495029e-02
44,LV359,C2CP_WP_MAMMARY_GLAND_DEVELOPMENT_PUBERTY_STAGE_2_OF_4,0.980010,5.953757e-02
45,LV367,C2CP_BIOCARTA_GRANULOCYTES_PATHWAY,0.985683,5.586174e-02
46,LV413,C2CP_REACTOME_POU5F1_OCT4_SOX2_NANOG_ACTIVATE_GENES_RELATED_TO_PROLIFERATION,0.930090,8.129753e-02
47,LV497,C2CP_BIOCARTA_SM_PATHWAY,0.933180,7.504429e-02
48,LV497,C2CP_REACTOME_FOLDING_OF_ACTIN_BY_CCT_TRIC,0.918827,8.533668e-02
49,LV514,C2CP_REACTOME_XENOBIOTICS,0.982208,5.728160e-02
50,LV533,C2CP_KEGG_CIRCADIAN_RHYTHM_MAMMAL,1.000000,5.756743e-02
51,LV598,C2CP_KEGG_MEDICUS_VARIANT_AMPLIFIED_PDGFR_TO_PLCG_CAMK_SIGNALING_PATHWAY,0.974229,5.880048e-02
52,LV599,C2CP_WP_RETT_SYNDROME,0.728491,6.377020e-02
53,LV60,C2CP_KEGG_MEDICUS_REFERENCE_REGULATION_OF_GF_RTK_RAS_ERK_SIGNALING_UBIQUITINATION_OF_RTK_BY_CBL,0.962128,3.628320e-04
54,LV60,C2CP_KEGG_MEDICUS_VARIANT_MUTATION_CAUSED_ABERRANT_ABETA_TO_CROSSTALK_BETWEEN_EXTRINSIC_AND_INTRINSIC_APOPTOTIC_PATHWAYS,0.979768,3.406581e-02
55,LV60,C2CP_REACTOME_REGULATION_OF_GENE_EXPRESSION_IN_BETA_CELLS,0.965168,4.206842e-02
56,LV60,C2CP_WP_TRANSCRIPTION_FACTOR_REGULATION_IN_ADIPOGENESIS,0.809622,5.586174e-02
57,LV633,C2CP_WP_SRF_AND_MIRS_IN_SMOOTH_MUSCLE_DIFFERENTIATION_AND_PROLIFERATION,0.930328,9.004953e-02
58,LV636,C2CP_BIOCARTA_ASBCELL_PATHWAY,0.998554,2.283026e-02
59,LV636,C2CP_BIOCARTA_HSP27_PATHWAY,0.885148,7.696031e-02
60,LV648,C2CP_WP_UNFOLDED_PROTEIN_RESPONSE,0.954632,9.220328e-03
61,LV648,C2CP_REACTOME_REGULATION_OF_FOXO_TRANSCRIPTIONAL_ACTIVITY_BY_ACETYLATION,0.953978,7.039529e-02
62,LV648,C2CP_PID_NFKAPPAB_ATYPICAL_PATHWAY,0.843827,9.210761e-02
63,LV651,C2CP_REACTOME_PHOSPHORYLATION_OF_CLOCK_ACETYLATION_OF_BMAL1_ARNTL_AT_TARGET_GENE_PROMOTERS,0.956523,7.649308e-02
64,LV651,C2CP_BIOCARTA_IL17_PATHWAY,0.945279,8.418068e-02
65,LV651,C2CP_BIOCARTA_CTL_PATHWAY,0.926250,9.781409e-02
66,LV654,C2CP_REACTOME_DISSOLUTION_OF_FIBRIN_CLOT,0.983725,6.742913e-02
67,LV680,C2CP_PID_ERBB_NETWORK_PATHWAY,1.000000,6.017376e-02
68,LV680,C2CP_REACTOME_ERBB2_ACTIVATES_PTK6_SIGNALING,1.000000,6.017376e-02
69,LV680,C2CP_REACTOME_ERBB2_REGULATES_CELL_MOTILITY,1.000000,6.017376e-02
70,LV729,C2CP_KEGG_MEDICUS_PATHOGEN_HPV_E6_TO_NOTCH_SIGNALING_PATHWAY_N00380,1.000000,6.017376e-02
71,LV729,C2CP_KEGG_MEDICUS_PATHOGEN_HPV_E6_TO_NOTCH_SIGNALING_PATHWAY_N00382,1.000000,6.017376e-02
72,LV73,C2CP_WP_LTF_DANGER_SIGNAL_RESPONSE_PATHWAY,0.982757,2.001041e-02
73,LV758,C2CP_WP_PROSTAGLANDIN_SYNTHESIS_AND_REGULATION,0.901514,3.169349e-03
74,LV758,C2CP_WP_OMEGA6FATTY_ACIDS_IN_SENESCENCE,0.809301,1.261205e-02
75,LV839,C2CP_BIOCARTA_CLASSIC_PATHWAY,1.000000,5.586174e-02

In [8]:
adrenal_gland_pathways = analyze("Adrenal gland", "adrenal gland")

────────────────────────────────────────────────────────────────
  Adrenal gland  (keyword: 'adrenal gland')  |  samples in model: 30
  Expected in top 1%: 0.3  |  Selected LVs: 0

Empty DataFrame
Columns: [LV, n_in_top1pct, enrich_ratio, median_rank_pct, AUC, FDR]
Index: []

  Pathways:
  (none)

In [9]:
adrenal_gland_pathways

Empty DataFrame
Columns: [LV, pathway, AUC, FDR]
Index: []

In [10]:
artery_pathways = analyze("Artery", "artery")

────────────────────────────────────────────────────────────────
  Artery  (keyword: 'artery')  |  samples in model: 697
  Expected in top 1%: 7.0  |  Selected LVs: 32

,LV,n_in_top1pct,enrich_ratio,median_rank_pct,AUC,FDR
0,LV1422,44,6.313,0.3700,0.592640,3.094262e-15
1,LV791,43,6.169,0.4295,0.538962,1.380842e-03
2,LV864,43,6.169,0.4406,0.546636,1.148206e-04
3,LV49,37,5.309,0.4307,0.553960,7.101209e-06
4,LV427,35,5.022,0.4538,0.544796,2.100888e-04
5,LV1602,34,4.878,0.4708,0.527620,2.734748e-02
6,LV689,33,4.735,0.4500,0.534449,5.115529e-03
7,LV1423,31,4.448,0.4878,0.532463,8.597787e-03
8,LV68,30,4.304,0.3868,0.587361,1.103939e-13
9,LV467,30,4.304,0.4580,0.539578,1.147126e-03
10,LV1090,30,4.304,0.4740,0.527831,2.602668e-02
11,LV206,27,3.874,0.4655,0.525221,4.557793e-02
12,LV1637,27,3.874,0.4650,0.544896,2.045856e-04
13,LV104,27,3.874,0.4445,0.526337,3.625559e-02
14,LV1197,26,3.730,0.4813,0.528854,2.092768e-02
15,LV1545,26,3.730,0.4559,0.528900,2.073036e-02
16,LV698,26,3.730,0.4624,0.538134,1.761056e-03
17,LV1630,26,3.730,0.4099,0.560224,4.566822e-07
18,LV399,25,3.587,0.3801,0.576839,7.202677e-11
19,LV1245,25,3.587,0.4144,0.543979,2.720234e-04
20,LV217,25,3.587,0.4763,0.538534,1.573963e-03
21,LV90,25,3.587,0.4161,0.541969,5.294204e-04
22,LV1615,25,3.587,0.4339,0.539722,1.100313e-03
23,LV1672,24,3.443,0.3834,0.585845,3.082116e-13
24,LV354,22,3.156,0.3914,0.580023,1.118247e-11
25,LV306,22,3.156,0.4483,0.542995,3.804660e-04
26,LV1314,22,3.156,0.4479,0.547853,7.532945e-05
27,LV1489,21,3.013,0.4069,0.562383,1.689494e-07
28,LV1243,20,2.870,0.4898,0.527990,2.510060e-02
29,LV44,20,2.870,0.4378,0.535699,3.581567e-03
30,LV632,20,2.870,0.4972,0.527003,3.137368e-02
31,LV907,20,2.870,0.4189,0.562370,1.689494e-07

  Pathways:

,LV,pathway,AUC,FDR
0,LV1197,C2CP_KEGG_PHENYLALANINE_METABOLISM,0.898422,0.054814
1,LV217,C2CP_KEGG_MEDICUS_VARIANT_MUTATION_INACTIVATED_PRKAR1A_TO_ACTH_CORTISOL_SIGNALING_PATHWAY,0.993649,0.012122
2,LV217,C2CP_REACTOME_NUCLEAR_RECEPTOR_TRANSCRIPTION_PATHWAY,0.791728,0.016094
3,LV217,C2CP_WP_WHITE_FAT_CELL_DIFFERENTIATION,0.835253,0.016486
4,LV217,C2CP_BIOCARTA_PCAF_PATHWAY,0.964570,0.058881
5,LV217,C2CP_KEGG_MEDICUS_VARIANT_MUTATION_INACTIVATED_ATP2B3_TO_ANGIOTENSIN_ALDOSTERONE_SIGNALING_PATHWAY,0.865324,0.066117
6,LV399,C2CP_REACTOME_ACYL_CHAIN_REMODELLING_OF_PG,1.000000,0.058193
7,LV44,C2CP_REACTOME_SIRT1_NEGATIVELY_REGULATES_RRNA_EXPRESSION,0.927785,0.000003
8,LV44,C2CP_REACTOME_ACTIVATED_PKN1_STIMULATES_TRANSCRIPTION_OF_AR_ANDROGEN_RECEPTOR_REGULATED_GENES_KLK2_AND_KLK3,0.921967,0.000012
9,LV44,C2CP_REACTOME_REPLACEMENT_OF_PROTAMINES_BY_NUCLEOSOMES_IN_THE_MALE_PRONUCLEUS,0.975729,0.000406
10,LV44,C2CP_REACTOME_DNA_METHYLATION,0.823587,0.001468
11,LV44,C2CP_REACTOME_DEFECTIVE_PYROPTOSIS,0.741786,0.014028
12,LV44,C2CP_REACTOME_ERCC6_CSB_AND_EHMT2_G9A_POSITIVELY_REGULATE_RRNA_EXPRESSION,0.737431,0.016156
13,LV467,C2CP_WP_NRXN1_DELETION_SYNDROME,0.996569,0.053376
14,LV467,C2CP_KEGG_MEDICUS_REFERENCE_KINETOCHORE_MICROTUBULE_ATTACHMENT,0.831373,0.099551
15,LV49,C2CP_BIOCARTA_VDR_PATHWAY,0.861366,0.056336
16,LV49,C2CP_WP_SMC1SMC3_ROLE_IN_DNA_DAMAGE_CORNELIA_DE_LANGE_SYNDROME,0.949801,0.083525
17,LV68,C2CP_BIOCARTA_HSWI_SNF_PATHWAY,0.972153,0.066973
18,LV68,C2CP_REACTOME_REGULATION_OF_GENE_EXPRESSION_IN_LATE_STAGE_BRANCHING_MORPHOGENESIS_PANCREATIC_BUD_PRECURSOR_CELLS,0.969261,0.068527
19,LV68,C2CP_REACTOME_PHOSPHORYLATION_OF_CLOCK_ACETYLATION_OF_BMAL1_ARNTL_AT_TARGET_GENE_PROMOTERS,0.928268,0.095075
20,LV689,C2CP_REACTOME_NEGATIVE_REGULATION_OF_NMDA_RECEPTOR_MEDIATED_NEURONAL_TRANSMISSION,0.999946,0.016008
21,LV689,C2CP_KEGG_MEDICUS_VARIANT_AMPLIFIED_PDGFR_TO_PLCG_CAMK_SIGNALING_PATHWAY,0.996545,0.056869
22,LV689,C2CP_KEGG_MEDICUS_VARIANT_AMPLIFIED_EGFR_TO_PLCG_CAMK_SIGNALING_PATHWAY,0.994804,0.057282
23,LV90,C2CP_KEGG_MEDICUS_PATHOGEN_ESCHERICHIA_EAE_TIR_TO_ACTIN_SIGNALING_PATHWAY,0.927019,0.050150
24,LV90,C2CP_KEGG_MEDICUS_REFERENCE_ANTIGEN_PROCESSING_AND_PRESENTATION_BY_MHC_CLASS_I_MOLECULES,0.998800,0.057345
25,LV90,C2CP_REACTOME_ENDOSOMAL_VACUOLAR_PATHWAY,0.997301,0.057588
26,LV90,C2CP_BIOCARTA_THELPER_PATHWAY,0.988876,0.059629

In [11]:
artery_pathways

,LV,pathway,AUC,FDR
0,LV1197,C2CP_KEGG_PHENYLALANINE_METABOLISM,0.898422,0.054814
1,LV217,C2CP_KEGG_MEDICUS_VARIANT_MUTATION_INACTIVATED_PRKAR1A_TO_ACTH_CORTISOL_SIGNALING_PATHWAY,0.993649,0.012122
2,LV217,C2CP_REACTOME_NUCLEAR_RECEPTOR_TRANSCRIPTION_PATHWAY,0.791728,0.016094
3,LV217,C2CP_WP_WHITE_FAT_CELL_DIFFERENTIATION,0.835253,0.016486
4,LV217,C2CP_BIOCARTA_PCAF_PATHWAY,0.964570,0.058881
5,LV217,C2CP_KEGG_MEDICUS_VARIANT_MUTATION_INACTIVATED_ATP2B3_TO_ANGIOTENSIN_ALDOSTERONE_SIGNALING_PATHWAY,0.865324,0.066117
6,LV399,C2CP_REACTOME_ACYL_CHAIN_REMODELLING_OF_PG,1.000000,0.058193
7,LV44,C2CP_REACTOME_SIRT1_NEGATIVELY_REGULATES_RRNA_EXPRESSION,0.927785,0.000003
8,LV44,C2CP_REACTOME_ACTIVATED_PKN1_STIMULATES_TRANSCRIPTION_OF_AR_ANDROGEN_RECEPTOR_REGULATED_GENES_KLK2_AND_KLK3,0.921967,0.000012
9,LV44,C2CP_REACTOME_REPLACEMENT_OF_PROTAMINES_BY_NUCLEOSOMES_IN_THE_MALE_PRONUCLEUS,0.975729,0.000406
10,LV44,C2CP_REACTOME_DNA_METHYLATION,0.823587,0.001468
11,LV44,C2CP_REACTOME_DEFECTIVE_PYROPTOSIS,0.741786,0.014028
12,LV44,C2CP_REACTOME_ERCC6_CSB_AND_EHMT2_G9A_POSITIVELY_REGULATE_RRNA_EXPRESSION,0.737431,0.016156
13,LV467,C2CP_WP_NRXN1_DELETION_SYNDROME,0.996569,0.053376
14,LV467,C2CP_KEGG_MEDICUS_REFERENCE_KINETOCHORE_MICROTUBULE_ATTACHMENT,0.831373,0.099551
15,LV49,C2CP_BIOCARTA_VDR_PATHWAY,0.861366,0.056336
16,LV49,C2CP_WP_SMC1SMC3_ROLE_IN_DNA_DAMAGE_CORNELIA_DE_LANGE_SYNDROME,0.949801,0.083525
17,LV68,C2CP_BIOCARTA_HSWI_SNF_PATHWAY,0.972153,0.066973
18,LV68,C2CP_REACTOME_REGULATION_OF_GENE_EXPRESSION_IN_LATE_STAGE_BRANCHING_MORPHOGENESIS_PANCREATIC_BUD_PRECURSOR_CELLS,0.969261,0.068527
19,LV68,C2CP_REACTOME_PHOSPHORYLATION_OF_CLOCK_ACETYLATION_OF_BMAL1_ARNTL_AT_TARGET_GENE_PROMOTERS,0.928268,0.095075
20,LV689,C2CP_REACTOME_NEGATIVE_REGULATION_OF_NMDA_RECEPTOR_MEDIATED_NEURONAL_TRANSMISSION,0.999946,0.016008
21,LV689,C2CP_KEGG_MEDICUS_VARIANT_AMPLIFIED_PDGFR_TO_PLCG_CAMK_SIGNALING_PATHWAY,0.996545,0.056869
22,LV689,C2CP_KEGG_MEDICUS_VARIANT_AMPLIFIED_EGFR_TO_PLCG_CAMK_SIGNALING_PATHWAY,0.994804,0.057282
23,LV90,C2CP_KEGG_MEDICUS_PATHOGEN_ESCHERICHIA_EAE_TIR_TO_ACTIN_SIGNALING_PATHWAY,0.927019,0.050150
24,LV90,C2CP_KEGG_MEDICUS_REFERENCE_ANTIGEN_PROCESSING_AND_PRESENTATION_BY_MHC_CLASS_I_MOLECULES,0.998800,0.057345
25,LV90,C2CP_REACTOME_ENDOSOMAL_VACUOLAR_PATHWAY,0.997301,0.057588
26,LV90,C2CP_BIOCARTA_THELPER_PATHWAY,0.988876,0.059629

In [12]:
bladder_pathways = analyze("Bladder", "bladder")

────────────────────────────────────────────────────────────────
  Bladder  (keyword: 'bladder')  |  samples in model: 1,227
  Expected in top 1%: 12.3  |  Selected LVs: 50

,LV,n_in_top1pct,enrich_ratio,median_rank_pct,AUC,FDR
0,LV727,114,9.291,0.4325,0.543289,1.074313e-06
1,LV14,98,7.987,0.4229,0.551838,4.325186e-09
2,LV1519,93,7.580,0.4220,0.558912,2.158713e-11
3,LV345,68,5.542,0.4643,0.538076,1.966342e-05
4,LV413,60,4.890,0.3714,0.597865,1.589010e-29
5,LV218,57,4.646,0.4293,0.568139,8.407296e-15
6,LV1470,52,4.238,0.4645,0.544152,6.649924e-07
7,LV731,49,3.994,0.3508,0.592866,9.222242e-27
8,LV1586,48,3.912,0.4734,0.528322,1.789913e-03
9,LV1373,47,3.831,0.4473,0.535607,6.753606e-05
10,LV629,46,3.749,0.4658,0.521827,1.862800e-02
11,LV677,45,3.668,0.4567,0.538792,1.371575e-05
12,LV1369,43,3.505,0.4489,0.537114,3.205971e-05
13,LV123,43,3.505,0.4316,0.546885,1.240327e-07
14,LV936,42,3.423,0.4210,0.556945,9.367047e-11
15,LV1675,39,3.179,0.4847,0.534655,1.093894e-04
16,LV1456,39,3.179,0.4498,0.547877,6.301284e-08
17,LV1334,39,3.179,0.3817,0.572178,2.315805e-16
18,LV547,39,3.179,0.4005,0.559227,1.726911e-11
19,LV1506,38,3.097,0.4310,0.558097,4.078297e-11
20,LV1383,37,3.016,0.4829,0.520191,3.114206e-02
21,LV1545,37,3.016,0.4491,0.550728,9.341031e-09
22,LV88,36,2.934,0.4219,0.539287,1.039712e-05
23,LV1203,36,2.934,0.4549,0.536737,3.886871e-05
24,LV1185,34,2.771,0.4551,0.526992,3.035032e-03
25,LV223,34,2.771,0.4782,0.532335,3.232886e-04
26,LV336,32,2.608,0.4451,0.540682,4.765794e-06
27,LV1044,32,2.608,0.4782,0.521890,1.830490e-02
28,LV787,32,2.608,0.4797,0.531919,3.899265e-04
29,LV244,32,2.608,0.4457,0.556388,1.413821e-10
30,LV1522,30,2.445,0.4656,0.531040,5.635088e-04
31,LV416,30,2.445,0.4610,0.537461,2.687908e-05
32,LV1152,29,2.364,0.4283,0.546296,1.782112e-07
33,LV1458,29,2.364,0.4874,0.524238,8.391390e-03
34,LV546,28,2.282,0.4222,0.538149,1.898066e-05
35,LV754,28,2.282,0.4430,0.542401,1.786609e-06
36,LV1171,28,2.282,0.4523,0.537511,2.640198e-05
37,LV98,27,2.201,0.4577,0.524987,6.388415e-03
38,LV1262,27,2.201,0.4064,0.546110,1.983789e-07
39,LV1344,27,2.201,0.4508,0.518518,4.968123e-02
40,LV130,26,2.119,0.5032,0.518800,4.576340e-02
41,LV1346,26,2.119,0.3943,0.561592,2.548839e-12
42,LV1103,26,2.119,0.4564,0.538278,1.780742e-05
43,LV887,26,2.119,0.4642,0.523013,1.277101e-02
44,LV822,26,2.119,0.4037,0.564927,1.388041e-13
45,LV1673,25,2.038,0.4603,0.520860,2.556095e-02
46,LV793,25,2.038,0.4544,0.545800,2.417994e-07
47,LV514,25,2.038,0.4280,0.561070,3.837033e-12
48,LV278,25,2.038,0.4525,0.542615,1.579111e-06
49,LV1254,25,2.038,0.4143,0.562488,1.243716e-12

  Pathways:

,LV,pathway,AUC,FDR
0,LV1103,C2CP_REACTOME_ANTIGEN_PROCESSING_UB_ATP_INDEPENDENT_PROTEASOMAL_DEGRADATION,0.871444,6.564056e-02
1,LV1373,C2CP_REACTOME_DEFECTIVE_EXT2_CAUSES_EXOSTOSES_2,0.942138,7.958803e-02
2,LV14,C2CP_KEGG_MEDICUS_REFERENCE_TRAIP_DEPENDENT_REPLISOME_DISASSEMBLY,0.941648,3.833069e-02
3,LV1519,C2CP_WP_ELECTRON_TRANSPORT_CHAIN_OXPHOS_SYSTEM_IN_MITOCHONDRIA,0.978760,1.362999e-11
4,LV1519,C2CP_WP_OXIDATIVE_PHOSPHORYLATION,1.000000,5.113629e-08
5,LV1519,C2CP_KEGG_MEDICUS_VARIANT_MUTATION_INACTIVATED_PINK1_TO_ELECTRON_TRANSFER_IN_COMPLEX_I,0.999229,4.900400e-06
6,LV1519,C2CP_KEGG_MEDICUS_VARIANT_MUTATION_CAUSED_ABERRANT_SNCA_TO_ELECTRON_TRANSFER_IN_COMPLEX_I,0.995800,5.927314e-06
7,LV1519,C2CP_KEGG_MEDICUS_REFERENCE_ELECTRON_TRANSFER_IN_COMPLEX_I,0.994851,2.592617e-05
8,LV1519,C2CP_REACTOME_FORMATION_OF_ATP_BY_CHEMIOSMOTIC_COUPLING,0.997951,5.321553e-03
9,LV1519,C2CP_KEGG_MEDICUS_REFERENCE_ELECTRON_TRANSFER_IN_COMPLEX_III,0.982136,6.564056e-02
10,LV1675,C2CP_REACTOME_STRIATED_MUSCLE_CONTRACTION,0.828213,5.595893e-02
11,LV1675,C2CP_WP_CAFFEINE_IN_MYOCYTES,0.797150,7.349155e-02
12,LV345,C2CP_WP_ELECTRON_TRANSPORT_CHAIN_OXPHOS_SYSTEM_IN_MITOCHONDRIA,0.753615,9.787107e-04
13,LV413,C2CP_REACTOME_POU5F1_OCT4_SOX2_NANOG_ACTIVATE_GENES_RELATED_TO_PROLIFERATION,0.930090,8.129753e-02
14,LV514,C2CP_REACTOME_XENOBIOTICS,0.982208,5.728160e-02
15,LV546,C2CP_REACTOME_TIGHT_JUNCTION_INTERACTIONS,0.960726,9.819271e-03
16,LV546,C2CP_WP_PANCREATIC_CANCER_SUBTYPES,0.822400,3.169961e-02
17,LV546,C2CP_REACTOME_DEVELOPMENTAL_LINEAGE_OF_MAMMARY_GLAND_ALVEOLAR_CELLS,0.980924,6.151162e-02
18,LV546,C2CP_REACTOME_DEVELOPMENTAL_LINEAGE_OF_MAMMARY_GLAND_LUMINAL_EPITHELIAL_CELLS,0.824936,7.194291e-02
19,LV546,C2CP_REACTOME_KERATINIZATION,0.722080,8.164208e-02
20,LV546,C2CP_WP_DEREGULATION_OF_RAB_AND_RAB_EFFECTOR_GENES_IN_BLADDER_CANCER,0.851004,9.173429e-02
21,LV547,C2CP_REACTOME_NCAM1_INTERACTIONS,0.802533,4.587444e-02
22,LV727,C2CP_KEGG_MEDICUS_VARIANT_MUTATION_CAUSED_ABERRANT_SNCA_TO_ELECTRON_TRANSFER_IN_COMPLEX_I,0.753577,3.940991e-02
23,LV727,C2CP_KEGG_VALINE_LEUCINE_AND_ISOLEUCINE_BIOSYNTHESIS,0.941699,8.125798e-02
24,LV787,C2CP_REACTOME_ACYL_CHAIN_REMODELLING_OF_PS,0.991384,5.808118e-02

In [13]:
bladder_pathways

,LV,pathway,AUC,FDR
0,LV1103,C2CP_REACTOME_ANTIGEN_PROCESSING_UB_ATP_INDEPENDENT_PROTEASOMAL_DEGRADATION,0.871444,6.564056e-02
1,LV1373,C2CP_REACTOME_DEFECTIVE_EXT2_CAUSES_EXOSTOSES_2,0.942138,7.958803e-02
2,LV14,C2CP_KEGG_MEDICUS_REFERENCE_TRAIP_DEPENDENT_REPLISOME_DISASSEMBLY,0.941648,3.833069e-02
3,LV1519,C2CP_WP_ELECTRON_TRANSPORT_CHAIN_OXPHOS_SYSTEM_IN_MITOCHONDRIA,0.978760,1.362999e-11
4,LV1519,C2CP_WP_OXIDATIVE_PHOSPHORYLATION,1.000000,5.113629e-08
5,LV1519,C2CP_KEGG_MEDICUS_VARIANT_MUTATION_INACTIVATED_PINK1_TO_ELECTRON_TRANSFER_IN_COMPLEX_I,0.999229,4.900400e-06
6,LV1519,C2CP_KEGG_MEDICUS_VARIANT_MUTATION_CAUSED_ABERRANT_SNCA_TO_ELECTRON_TRANSFER_IN_COMPLEX_I,0.995800,5.927314e-06
7,LV1519,C2CP_KEGG_MEDICUS_REFERENCE_ELECTRON_TRANSFER_IN_COMPLEX_I,0.994851,2.592617e-05
8,LV1519,C2CP_REACTOME_FORMATION_OF_ATP_BY_CHEMIOSMOTIC_COUPLING,0.997951,5.321553e-03
9,LV1519,C2CP_KEGG_MEDICUS_REFERENCE_ELECTRON_TRANSFER_IN_COMPLEX_III,0.982136,6.564056e-02
10,LV1675,C2CP_REACTOME_STRIATED_MUSCLE_CONTRACTION,0.828213,5.595893e-02
11,LV1675,C2CP_WP_CAFFEINE_IN_MYOCYTES,0.797150,7.349155e-02
12,LV345,C2CP_WP_ELECTRON_TRANSPORT_CHAIN_OXPHOS_SYSTEM_IN_MITOCHONDRIA,0.753615,9.787107e-04
13,LV413,C2CP_REACTOME_POU5F1_OCT4_SOX2_NANOG_ACTIVATE_GENES_RELATED_TO_PROLIFERATION,0.930090,8.129753e-02
14,LV514,C2CP_REACTOME_XENOBIOTICS,0.982208,5.728160e-02
15,LV546,C2CP_REACTOME_TIGHT_JUNCTION_INTERACTIONS,0.960726,9.819271e-03
16,LV546,C2CP_WP_PANCREATIC_CANCER_SUBTYPES,0.822400,3.169961e-02
17,LV546,C2CP_REACTOME_DEVELOPMENTAL_LINEAGE_OF_MAMMARY_GLAND_ALVEOLAR_CELLS,0.980924,6.151162e-02
18,LV546,C2CP_REACTOME_DEVELOPMENTAL_LINEAGE_OF_MAMMARY_GLAND_LUMINAL_EPITHELIAL_CELLS,0.824936,7.194291e-02
19,LV546,C2CP_REACTOME_KERATINIZATION,0.722080,8.164208e-02
20,LV546,C2CP_WP_DEREGULATION_OF_RAB_AND_RAB_EFFECTOR_GENES_IN_BLADDER_CANCER,0.851004,9.173429e-02
21,LV547,C2CP_REACTOME_NCAM1_INTERACTIONS,0.802533,4.587444e-02
22,LV727,C2CP_KEGG_MEDICUS_VARIANT_MUTATION_CAUSED_ABERRANT_SNCA_TO_ELECTRON_TRANSFER_IN_COMPLEX_I,0.753577,3.940991e-02
23,LV727,C2CP_KEGG_VALINE_LEUCINE_AND_ISOLEUCINE_BIOSYNTHESIS,0.941699,8.125798e-02
24,LV787,C2CP_REACTOME_ACYL_CHAIN_REMODELLING_OF_PS,0.991384,5.808118e-02

In [14]:
blood_vessel_pathways = analyze("Blood vessel", "blood vessel")

────────────────────────────────────────────────────────────────
  Blood vessel  (keyword: 'blood vessel')  |  samples in model: 80
  Expected in top 1%: 0.8  |  Selected LVs: 0

Empty DataFrame
Columns: [LV, n_in_top1pct, enrich_ratio, median_rank_pct, AUC, FDR]
Index: []

  Pathways:
  (none)

In [15]:
blood_vessel_pathways

Empty DataFrame
Columns: [LV, pathway, AUC, FDR]
Index: []

In [16]:
brain_pathways = analyze("Brain", "brain")

────────────────────────────────────────────────────────────────
  Brain  (keyword: 'brain')  |  samples in model: 8,005
  Expected in top 1%: 80.0  |  Selected LVs: 31

,LV,n_in_top1pct,enrich_ratio,median_rank_pct,AUC,FDR
0,LV1016,455,5.684,0.4334,0.543593,9.334624e-40
1,LV142,435,5.434,0.4397,0.539045,3.650415e-32
2,LV259,301,3.760,0.4542,0.531959,4.376796e-22
3,LV1272,296,3.698,0.4429,0.538533,2.196889e-31
4,LV1343,283,3.535,0.4370,0.546368,1.072498e-44
5,LV125,265,3.311,0.4609,0.532636,5.667799e-23
6,LV1496,264,3.298,0.4719,0.524908,5.339152e-14
7,LV265,260,3.248,0.4549,0.530038,1.078941e-19
8,LV874,259,3.236,0.4591,0.529333,7.608401e-19
9,LV762,251,3.136,0.4660,0.516032,1.459544e-06
10,LV1216,246,3.073,0.4574,0.536668,1.426568e-28
11,LV305,245,3.061,0.4745,0.510832,1.207757e-03
12,LV1651,233,2.911,0.4917,0.508759,8.690660e-03
13,LV1128,209,2.611,0.4773,0.522444,1.292714e-11
14,LV1024,194,2.424,0.4844,0.518848,1.400261e-08
15,LV862,191,2.386,0.4931,0.507196,3.107112e-02
16,LV1394,178,2.224,0.4642,0.528397,9.576862e-18
17,LV1543,176,2.199,0.4690,0.519814,2.419332e-09
18,LV1507,171,2.136,0.4761,0.515573,2.873566e-06
19,LV396,171,2.136,0.4607,0.535829,2.269716e-27
20,LV1355,170,2.124,0.4795,0.524423,1.624238e-13
21,LV115,169,2.111,0.4621,0.526678,7.630687e-16
22,LV375,168,2.099,0.4378,0.533745,1.871893e-24
23,LV932,168,2.099,0.4472,0.527167,2.228594e-16
24,LV74,167,2.086,0.4611,0.516366,8.705910e-07
25,LV216,165,2.061,0.4801,0.513295,6.768280e-05
26,LV11,163,2.036,0.4939,0.513889,3.112447e-05
27,LV1502,162,2.024,0.4667,0.522987,4.061132e-12
28,LV714,162,2.024,0.4681,0.518295,3.667283e-08
29,LV1533,161,2.011,0.4782,0.508794,8.431069e-03
30,LV1377,161,2.011,0.4480,0.538499,2.453516e-31

  Pathways:

,LV,pathway,AUC,FDR
0,LV1016,C2CP_REACTOME_DOPAMINE_NEUROTRANSMITTER_RELEASE_CYCLE,0.795684,0.093985
1,LV1024,C2CP_REACTOME_DEVELOPMENTAL_LINEAGE_OF_MAMMARY_GLAND_MYOEPITHELIAL_CELLS,0.992725,0.004919
2,LV1024,C2CP_REACTOME_DEVELOPMENTAL_LINEAGE_OF_MAMMARY_GLAND_LUMINAL_EPITHELIAL_CELLS,0.807711,0.087594
3,LV1024,C2CP_REACTOME_FORMATION_OF_THE_CORNIFIED_ENVELOPE,0.711649,0.096260
4,LV11,C2CP_WP_BIOMARKERS_FOR_UREA_CYCLE_DISORDERS,0.998419,0.055862
5,LV11,C2CP_KEGG_MEDICUS_REFERENCE_BILE_ACID_BIOSYNTHESIS,0.987243,0.057616
6,LV11,C2CP_WP_ANDROGEN_BIOSYNTHESIS,0.969225,0.063770
7,LV11,C2CP_REACTOME_SYNTHESIS_OF_BILE_ACIDS_AND_BILE_SALTS_VIA_24_HYDROXYCHOLESTEROL,0.964482,0.066117
8,LV11,C2CP_WP_FARNESOID_X_RECEPTOR_PATHWAY,0.959876,0.068223
9,LV11,C2CP_WP_CHOLESTASIS,0.844082,0.093431
10,LV1216,C2CP_REACTOME_NEGATIVE_REGULATION_OF_NMDA_RECEPTOR_MEDIATED_NEURONAL_TRANSMISSION,0.937267,0.053183
11,LV125,C2CP_KEGG_MEDICUS_REFERENCE_REGULATION_OF_GF_RTK_RAS_ERK_SIGNALING_PATHWAY_ADAPTOR_PROTEINS,0.933630,0.089650
12,LV1272,C2CP_WP_17Q12_COPY_NUMBER_VARIATION_SYNDROME,0.746033,0.017697
13,LV1272,C2CP_KEGG_MEDICUS_REFERENCE_SKELETAL_TYPE_VGCC_RYR_SIGNALING,1.000000,0.060706
14,LV1272,C2CP_REACTOME_PHASE_2_PLATEAU_PHASE,0.999973,0.060706
15,LV1343,C2CP_REACTOME_PHASE_0_RAPID_DEPOLARISATION,0.841948,0.067429
16,LV1343,C2CP_REACTOME_INTERACTION_BETWEEN_L1_AND_ANKYRINS,0.829808,0.076958
17,LV1543,C2CP_REACTOME_MET_ACTIVATES_PTK2_SIGNALING,0.886230,0.008311
18,LV1543,C2CP_REACTOME_ATTACHMENT_OF_BACTERIA_TO_EPITHELIAL_CELLS,0.803070,0.096143
19,LV1543,C2CP_REACTOME_FIBRONECTIN_MATRIX_FORMATION,0.803029,0.096144
20,LV216,C2CP_REACTOME_FORMATION_OF_AXIAL_MESODERM,0.998093,0.055235
21,LV265,C2CP_BIOCARTA_THELPER_PATHWAY,0.956053,0.077880
22,LV265,C2CP_WP_MIR5093P_ALTERATION_OF_YAP1ECM_AXIS,0.853656,0.093431
23,LV375,C2CP_WP_UNFOLDED_PROTEIN_RESPONSE,0.878308,0.043581
24,LV74,C2CP_WP_FATTY_ACID_BIOSYNTHESIS,0.972575,0.006316
25,LV74,C2CP_REACTOME_BIOTIN_TRANSPORT_AND_METABOLISM,0.975395,0.060438
26,LV874,C2CP_REACTOME_DOPAMINE_NEUROTRANSMITTER_RELEASE_CYCLE,0.999986,0.004923
27,LV874,C2CP_REACTOME_NEUROTRANSMITTER_RELEASE_CYCLE,0.767179,0.047124
28,LV932,C2CP_REACTOME_GLYCOGEN_BREAKDOWN_GLYCOGENOLYSIS,0.914064,0.053221

In [17]:
brain_pathways

,LV,pathway,AUC,FDR
0,LV1016,C2CP_REACTOME_DOPAMINE_NEUROTRANSMITTER_RELEASE_CYCLE,0.795684,0.093985
1,LV1024,C2CP_REACTOME_DEVELOPMENTAL_LINEAGE_OF_MAMMARY_GLAND_MYOEPITHELIAL_CELLS,0.992725,0.004919
2,LV1024,C2CP_REACTOME_DEVELOPMENTAL_LINEAGE_OF_MAMMARY_GLAND_LUMINAL_EPITHELIAL_CELLS,0.807711,0.087594
3,LV1024,C2CP_REACTOME_FORMATION_OF_THE_CORNIFIED_ENVELOPE,0.711649,0.096260
4,LV11,C2CP_WP_BIOMARKERS_FOR_UREA_CYCLE_DISORDERS,0.998419,0.055862
5,LV11,C2CP_KEGG_MEDICUS_REFERENCE_BILE_ACID_BIOSYNTHESIS,0.987243,0.057616
6,LV11,C2CP_WP_ANDROGEN_BIOSYNTHESIS,0.969225,0.063770
7,LV11,C2CP_REACTOME_SYNTHESIS_OF_BILE_ACIDS_AND_BILE_SALTS_VIA_24_HYDROXYCHOLESTEROL,0.964482,0.066117
8,LV11,C2CP_WP_FARNESOID_X_RECEPTOR_PATHWAY,0.959876,0.068223
9,LV11,C2CP_WP_CHOLESTASIS,0.844082,0.093431
10,LV1216,C2CP_REACTOME_NEGATIVE_REGULATION_OF_NMDA_RECEPTOR_MEDIATED_NEURONAL_TRANSMISSION,0.937267,0.053183
11,LV125,C2CP_KEGG_MEDICUS_REFERENCE_REGULATION_OF_GF_RTK_RAS_ERK_SIGNALING_PATHWAY_ADAPTOR_PROTEINS,0.933630,0.089650
12,LV1272,C2CP_WP_17Q12_COPY_NUMBER_VARIATION_SYNDROME,0.746033,0.017697
13,LV1272,C2CP_KEGG_MEDICUS_REFERENCE_SKELETAL_TYPE_VGCC_RYR_SIGNALING,1.000000,0.060706
14,LV1272,C2CP_REACTOME_PHASE_2_PLATEAU_PHASE,0.999973,0.060706
15,LV1343,C2CP_REACTOME_PHASE_0_RAPID_DEPOLARISATION,0.841948,0.067429
16,LV1343,C2CP_REACTOME_INTERACTION_BETWEEN_L1_AND_ANKYRINS,0.829808,0.076958
17,LV1543,C2CP_REACTOME_MET_ACTIVATES_PTK2_SIGNALING,0.886230,0.008311
18,LV1543,C2CP_REACTOME_ATTACHMENT_OF_BACTERIA_TO_EPITHELIAL_CELLS,0.803070,0.096143
19,LV1543,C2CP_REACTOME_FIBRONECTIN_MATRIX_FORMATION,0.803029,0.096144
20,LV216,C2CP_REACTOME_FORMATION_OF_AXIAL_MESODERM,0.998093,0.055235
21,LV265,C2CP_BIOCARTA_THELPER_PATHWAY,0.956053,0.077880
22,LV265,C2CP_WP_MIR5093P_ALTERATION_OF_YAP1ECM_AXIS,0.853656,0.093431
23,LV375,C2CP_WP_UNFOLDED_PROTEIN_RESPONSE,0.878308,0.043581
24,LV74,C2CP_WP_FATTY_ACID_BIOSYNTHESIS,0.972575,0.006316
25,LV74,C2CP_REACTOME_BIOTIN_TRANSPORT_AND_METABOLISM,0.975395,0.060438
26,LV874,C2CP_REACTOME_DOPAMINE_NEUROTRANSMITTER_RELEASE_CYCLE,0.999986,0.004923
27,LV874,C2CP_REACTOME_NEUROTRANSMITTER_RELEASE_CYCLE,0.767179,0.047124
28,LV932,C2CP_REACTOME_GLYCOGEN_BREAKDOWN_GLYCOGENOLYSIS,0.914064,0.053221

In [18]:
breast_pathways = analyze("Breast", "breast")

────────────────────────────────────────────────────────────────
  Breast  (keyword: 'breast')  |  samples in model: 17,357
  Expected in top 1%: 173.6  |  Selected LVs: 16

,LV,n_in_top1pct,enrich_ratio,median_rank_pct,AUC,FDR
0,LV1204,573,3.301,0.4618,0.528698,1.943191e-36
1,LV933,556,3.203,0.4825,0.519292,3.216391e-17
2,LV22,554,3.192,0.4921,0.512444,6.525862e-08
3,LV1091,547,3.152,0.4574,0.530265,2.901584e-40
4,LV739,520,2.996,0.4689,0.522641,3.259658e-23
5,LV1044,452,2.604,0.4644,0.523915,1.012077e-25
6,LV1630,441,2.541,0.4785,0.516020,2.784221e-12
7,LV734,413,2.379,0.4709,0.520815,8.098511e-20
8,LV1651,412,2.374,0.4668,0.520280,7.009986e-19
9,LV646,408,2.351,0.4881,0.506997,2.628510e-03
10,LV464,394,2.270,0.4897,0.514079,8.641875e-10
11,LV1327,376,2.166,0.4841,0.508656,1.919056e-04
12,LV156,375,2.161,0.4664,0.515196,3.504636e-11
13,LV253,369,2.126,0.4738,0.513119,1.149302e-08
14,LV83,368,2.120,0.4776,0.514759,1.274676e-10
15,LV1147,364,2.097,0.4834,0.513139,1.094621e-08

  Pathways:

,LV,pathway,AUC,FDR
0,LV1091,C2CP_WP_CILIOPATHIES,0.854116,2.023145e-11
1,LV1091,C2CP_WP_GENES_RELATED_TO_PRIMARY_CILIUM_DEVELOPMENT_BASED_ON_CRISPR,0.839100,1.530208e-06
2,LV1091,C2CP_REACTOME_INTRAFLAGELLAR_TRANSPORT,0.856616,1.655652e-03
3,LV156,C2CP_REACTOME_REGULATION_OF_NPAS4_GENE_EXPRESSION,0.989290,6.100384e-02
4,LV156,C2CP_REACTOME_REGULATION_OF_MITF_M_DEPENDENT_GENES_INVOLVED_IN_APOPTOSIS,0.866391,8.326865e-02
5,LV22,C2CP_WP_CILIOPATHIES,0.845144,1.117994e-10
6,LV253,C2CP_KEGG_MEDICUS_ENV_FACTOR_DCE_TO_DNA_ADDUCTS,0.998822,1.767292e-02
7,LV734,C2CP_KEGG_MEDICUS_ENV_FACTOR_TCDD_TO_AHR_SIGNALING_PATHWAY,1.000000,1.834856e-02
8,LV739,C2CP_KEGG_GLYCOSPHINGOLIPID_BIOSYNTHESIS_LACTO_AND_NEOLACTO_SERIES,0.921836,2.309212e-02
9,LV739,C2CP_REACTOME_BLOOD_GROUP_SYSTEMS_BIOSYNTHESIS,0.967580,3.131583e-02

In [19]:
breast_pathways

,LV,pathway,AUC,FDR
0,LV1091,C2CP_WP_CILIOPATHIES,0.854116,2.023145e-11
1,LV1091,C2CP_WP_GENES_RELATED_TO_PRIMARY_CILIUM_DEVELOPMENT_BASED_ON_CRISPR,0.839100,1.530208e-06
2,LV1091,C2CP_REACTOME_INTRAFLAGELLAR_TRANSPORT,0.856616,1.655652e-03
3,LV156,C2CP_REACTOME_REGULATION_OF_NPAS4_GENE_EXPRESSION,0.989290,6.100384e-02
4,LV156,C2CP_REACTOME_REGULATION_OF_MITF_M_DEPENDENT_GENES_INVOLVED_IN_APOPTOSIS,0.866391,8.326865e-02
5,LV22,C2CP_WP_CILIOPATHIES,0.845144,1.117994e-10
6,LV253,C2CP_KEGG_MEDICUS_ENV_FACTOR_DCE_TO_DNA_ADDUCTS,0.998822,1.767292e-02
7,LV734,C2CP_KEGG_MEDICUS_ENV_FACTOR_TCDD_TO_AHR_SIGNALING_PATHWAY,1.000000,1.834856e-02
8,LV739,C2CP_KEGG_GLYCOSPHINGOLIPID_BIOSYNTHESIS_LACTO_AND_NEOLACTO_SERIES,0.921836,2.309212e-02
9,LV739,C2CP_REACTOME_BLOOD_GROUP_SYSTEMS_BIOSYNTHESIS,0.967580,3.131583e-02

In [20]:
cervix_pathways = analyze("Cervix", "cervix")

────────────────────────────────────────────────────────────────
  Cervix  (keyword: 'cervix')  |  samples in model: 681
  Expected in top 1%: 6.8  |  Selected LVs: 44

,LV,n_in_top1pct,enrich_ratio,median_rank_pct,AUC,FDR
0,LV1466,54,7.930,0.4512,0.539507,1.424746e-03
1,LV568,54,7.930,0.3157,0.597170,7.117555e-16
2,LV1423,40,5.874,0.4021,0.547951,9.313039e-05
3,LV1502,38,5.580,0.4644,0.554731,6.650593e-06
4,LV891,34,4.993,0.4091,0.556018,4.001122e-06
5,LV971,33,4.846,0.4586,0.546971,1.292233e-04
6,LV1156,32,4.699,0.4061,0.561285,4.089615e-07
7,LV1117,31,4.552,0.4302,0.563521,1.427284e-07
8,LV1452,30,4.405,0.4519,0.535493,4.495844e-03
9,LV1362,28,4.112,0.4055,0.543579,4.068911e-04
10,LV720,27,3.965,0.4332,0.542113,6.485885e-04
11,LV96,27,3.965,0.4558,0.560182,6.580478e-07
12,LV328,27,3.965,0.4349,0.542286,6.146781e-04
13,LV365,27,3.965,0.4708,0.537582,2.497378e-03
14,LV1,26,3.818,0.4363,0.532877,8.922625e-03
15,LV724,26,3.818,0.4383,0.552023,1.952696e-05
16,LV1237,26,3.818,0.4366,0.543225,4.492444e-04
17,LV671,25,3.671,0.4528,0.531513,1.241643e-02
18,LV1594,25,3.671,0.4149,0.553313,1.200586e-05
19,LV719,25,3.671,0.3739,0.594792,2.348337e-15
20,LV1607,24,3.524,0.3865,0.565860,4.817624e-08
21,LV1028,24,3.524,0.4458,0.539521,1.424575e-03
22,LV1311,24,3.524,0.4687,0.526474,3.842784e-02
23,LV53,24,3.524,0.3453,0.586465,4.197725e-13
24,LV1271,24,3.524,0.4106,0.547061,1.262419e-04
25,LV1483,23,3.377,0.3825,0.566788,3.137325e-08
26,LV352,23,3.377,0.3633,0.564169,1.118170e-07
27,LV335,23,3.377,0.4520,0.530932,1.438848e-02
28,LV4,23,3.377,0.3677,0.585281,8.697679e-13
29,LV62,22,3.231,0.3726,0.593334,5.844954e-15
30,LV1625,22,3.231,0.4501,0.529692,1.895073e-02
31,LV1511,22,3.231,0.4435,0.547736,9.873563e-05
32,LV1269,21,3.084,0.3969,0.560602,5.469307e-07
33,LV1145,21,3.084,0.4317,0.546943,1.297784e-04
34,LV114,21,3.084,0.4508,0.540584,1.040610e-03
35,LV409,21,3.084,0.4334,0.526473,3.842784e-02
36,LV432,21,3.084,0.3468,0.587902,1.721767e-13
37,LV1684,21,3.084,0.4689,0.535383,4.636198e-03
38,LV1305,20,2.937,0.4649,0.532460,9.815726e-03
39,LV1584,20,2.937,0.4586,0.526578,3.774619e-02
40,LV1530,20,2.937,0.4325,0.551554,2.369441e-05
41,LV964,20,2.937,0.3970,0.560645,5.430112e-07
42,LV1225,20,2.937,0.4188,0.550703,3.259286e-05
43,LV302,20,2.937,0.4661,0.534325,6.077983e-03

  Pathways:

,LV,pathway,AUC,FDR
0,LV1028,C2CP_WP_METHIONINE_METABOLISM_LEADING_TO_SULFUR_AMINO_ACIDS_AND_RELATED_DISORDERS,0.963774,7.144923e-02
1,LV114,C2CP_REACTOME_KILLING_MECHANISMS,0.933013,9.130877e-02
2,LV1145,C2CP_KEGG_MEDICUS_REFERENCE_MDM2_P21_CELL_CYCLE_G1_S_N00536,0.965898,7.039529e-02
3,LV1225,C2CP_KEGG_MEDICUS_REFERENCE_BMP_SIGNALING_PATHWAY,0.868451,7.187528e-02
4,LV1269,C2CP_KEGG_MEDICUS_VARIANT_MUTATION_CAUSED_ABERRANT_SOD1_TO_26S_PROTEASOME_MEDIATED_PROTEIN_DEGRADATION,0.986098,3.313303e-05
5,LV1269,C2CP_KEGG_MEDICUS_VARIANT_MUTATION_CAUSED_ABERRANT_HTT_TO_26S_PROTEASOME_MEDIATED_PROTEIN_DEGRADATION,0.999766,7.165267e-05
6,LV1269,C2CP_KEGG_MEDICUS_VARIANT_SCRAPIE_CONFORMATION_PRPSC_TO_26S_PROTEASOME_MEDIATED_PROTEIN_DEGRADATION,0.997593,7.758650e-05
7,LV1269,C2CP_KEGG_MEDICUS_VARIANT_MUTATION_INACTIVATED_VCP_TO_26S_PROTEASOME_MEDIATED_PROTEIN_DEGRADATION,0.986418,1.159550e-04
8,LV1269,C2CP_KEGG_MEDICUS_VARIANT_MUTATION_CAUSED_ABERRANT_ABETA_TO_26S_PROTEASOME_MEDIATED_PROTEIN_DEGRADATION,0.982703,1.355744e-04
9,LV1269,C2CP_KEGG_MEDICUS_REFERENCE_26S_PROTEASOME_MEDIATED_PROTEIN_DEGRADATION,0.972103,2.088242e-04
10,LV1269,C2CP_KEGG_MEDICUS_VARIANT_MUTATION_INACTIVATED_UBQLN2_TO_26S_PROTEASOME_MEDIATED_PROTEIN_DEGRADATION,0.956963,3.558377e-04
11,LV1269,C2CP_BIOCARTA_PROTEASOME_PATHWAY,0.999964,1.785997e-02
12,LV1269,C2CP_WP_NSP1_FROM_SARSCOV2_INHIBITS_TRANSLATION_INITIATION_IN_THE_HOST_CELL,0.965509,3.008970e-02
13,LV1269,C2CP_BIOCARTA_SM_PATHWAY,0.994085,5.939067e-02
14,LV1271,C2CP_PID_INTEGRIN3_PATHWAY,0.786049,2.474244e-02
15,LV1271,C2CP_WP_OSTEOBLAST_SIGNALING,0.998034,5.621459e-02
16,LV1271,C2CP_REACTOME_DISSOLUTION_OF_FIBRIN_CLOT,0.960982,6.852737e-02
17,LV1271,C2CP_BIOCARTA_PLATELETAPP_PATHWAY,0.959262,6.962403e-02
18,LV1305,C2CP_REACTOME_METABOLISM_OF_AMINE_DERIVED_HORMONES,0.928997,8.583220e-02
19,LV1483,C2CP_KEGG_MEDICUS_REFERENCE_LOADING_OF_THE_SMC5_SMC6_COMPLEX,0.971932,6.890285e-02
20,LV1530,C2CP_KEGG_MEDICUS_REFERENCE_BLOCKING_UBIQUITINATION_OF_H2AK119_BY_CK2,0.941860,9.210761e-02
21,LV1594,C2CP_REACTOME_MRNA_SPLICING,0.782896,5.264914e-09
22,LV1607,C2CP_REACTOME_HEPARAN_SULFATE_HEPARIN_HS_GAG_METABOLISM,0.831488,3.008970e-02
23,LV302,C2CP_KEGG_MEDICUS_VARIANT_SCRAPIE_CONFORMATION_PRPSC_TO_26S_PROTEASOME_MEDIATED_PROTEIN_DEGRADATION,0.981859,4.324363e-05
24,LV302,C2CP_KEGG_MEDICUS_VARIANT_MUTATION_CAUSED_ABERRANT_ABETA_TO_26S_PROTEASOME_MEDIATED_PROTEIN_DEGRADATION,0.967561,8.071935e-05
25,LV302,C2CP_KEGG_MEDICUS_VARIANT_MUTATION_CAUSED_ABERRANT_SOD1_TO_26S_PROTEASOME_MEDIATED_PROTEIN_DEGRADATION,0.876920,9.837169e-04
26,LV302,C2CP_KEGG_PROTEASOME,0.852715,2.513417e-03
27,LV302,C2CP_KEGG_MEDICUS_VARIANT_MUTATION_INACTIVATED_VCP_TO_26S_PROTEASOME_MEDIATED_PROTEIN_DEGRADATION,0.876941,2.513417e-03
28,LV302,C2CP_REACTOME_REGULATION_OF_ORNITHINE_DECARBOXYLASE_ODC,0.859687,4.382892e-03
29,LV352,C2CP_KEGG_MEDICUS_VARIANT_MLL_ENL_FUSION_TO_TRANSCRIPTIONAL_ACTIVATION,0.948266,7.912769e-02
30,LV352,C2CP_REACTOME_GRB2_EVENTS_IN_ERBB2_SIGNALING,0.929178,9.195666e-02
31,LV4,C2CP_REACTOME_MITOCHONDRIAL_TRANSLATION_ELONGATION,0.982674,3.491544e-10
32,LV4,C2CP_REACTOME_MITOCHONDRIAL_TRANSLATION,0.866429,1.302586e-07
33,LV4,C2CP_KEGG_MEDICUS_REFERENCE_MITOCHONDRIAL_COMPLEX_UCP1_IN_THERMOGENESIS,0.864713,2.615113e-04
34,LV4,C2CP_WP_MITOCHONDRIAL_COMPLEX_IV_ASSEMBLY,0.835834,3.119430e-02
35,LV4,C2CP_KEGG_MEDICUS_REFERENCE_26S_PROTEASOME_MEDIATED_PROTEIN_DEGRADATION,0.735601,9.611163e-02
36,LV53,C2CP_REACTOME_EUKARYOTIC_TRANSLATION_ELONGATION,0.871080,4.365134e-07
37,LV53,C2CP_REACTOME_SRP_DEPENDENT_COTRANSLATIONAL_PROTEIN_TARGETING_TO_MEMBRANE,0.787211,3.033154e-05
38,LV53,C2CP_REACTOME_SELENOAMINO_ACID_METABOLISM,0.769286,7.071167e-05
39,LV53,C2CP_KEGG_RIBOSOME,0.807836,9.601244e-05
40,LV53,C2CP_KEGG_MEDICUS_REFERENCE_TRANSLATION_INITIATION,0.797058,3.157917e-04
41,LV568,C2CP_REACTOME_ACTIVATION_OF_THE_TFAP2_AP_2_FAMILY_OF_TRANSCRIPTION_FACTORS,0.938314,7.504429e-02
42,LV568,C2CP_WP_ESTROGEN_METABOLISM_WP697,0.853523,7.900415e-02
43,LV62,C2CP_WP_ELECTRON_TRANSPORT_CHAIN_OXPHOS_SYSTEM_IN_MITOCHONDRIA,0.933483,1.486160e-10
44,LV62,C2CP_WP_OXIDATIVE_PHOSPHORYLATION,0.975491,1.178694e-07
45,LV62,C2CP_KEGG_MEDICUS_REFERENCE_MITOCHONDRIAL_COMPLEX_UCP1_IN_THERMOGENESIS,0.944173,1.053472e-06
46,LV62,C2CP_KEGG_MEDICUS_VARIANT_MUTATION_INACTIVATED_PINK1_TO_ELECTRON_TRANSFER_IN_COMPLEX_I,0.966362,1.372559e-05
47,LV62,C2CP_KEGG_MEDICUS_REFERENCE_ELECTRON_TRANSFER_IN_COMPLEX_I,0.958140,7.165267e-05
48,LV62,C2CP_REACTOME_FORMATION_OF_ATP_BY_CHEMIOSMOTIC_COUPLING,0.993605,4.524891e-03
49,LV719,C2CP_REACTOME_SYNAPTIC_ADHESION_LIKE_MOLECULES,0.900868,5.700133e-02
50,LV96,C2CP_WP_SMC1SMC3_ROLE_IN_DNA_DAMAGE_CORNELIA_DE_LANGE_SYNDROME,0.999318,5.953087e-02
51,LV96,C2CP_REACTOME_ESTABLISHMENT_OF_SISTER_CHROMATID_COHESION,0.971769,7.144923e-02

In [21]:
cervix_pathways

,LV,pathway,AUC,FDR
0,LV1028,C2CP_WP_METHIONINE_METABOLISM_LEADING_TO_SULFUR_AMINO_ACIDS_AND_RELATED_DISORDERS,0.963774,7.144923e-02
1,LV114,C2CP_REACTOME_KILLING_MECHANISMS,0.933013,9.130877e-02
2,LV1145,C2CP_KEGG_MEDICUS_REFERENCE_MDM2_P21_CELL_CYCLE_G1_S_N00536,0.965898,7.039529e-02
3,LV1225,C2CP_KEGG_MEDICUS_REFERENCE_BMP_SIGNALING_PATHWAY,0.868451,7.187528e-02
4,LV1269,C2CP_KEGG_MEDICUS_VARIANT_MUTATION_CAUSED_ABERRANT_SOD1_TO_26S_PROTEASOME_MEDIATED_PROTEIN_DEGRADATION,0.986098,3.313303e-05
5,LV1269,C2CP_KEGG_MEDICUS_VARIANT_MUTATION_CAUSED_ABERRANT_HTT_TO_26S_PROTEASOME_MEDIATED_PROTEIN_DEGRADATION,0.999766,7.165267e-05
6,LV1269,C2CP_KEGG_MEDICUS_VARIANT_SCRAPIE_CONFORMATION_PRPSC_TO_26S_PROTEASOME_MEDIATED_PROTEIN_DEGRADATION,0.997593,7.758650e-05
7,LV1269,C2CP_KEGG_MEDICUS_VARIANT_MUTATION_INACTIVATED_VCP_TO_26S_PROTEASOME_MEDIATED_PROTEIN_DEGRADATION,0.986418,1.159550e-04
8,LV1269,C2CP_KEGG_MEDICUS_VARIANT_MUTATION_CAUSED_ABERRANT_ABETA_TO_26S_PROTEASOME_MEDIATED_PROTEIN_DEGRADATION,0.982703,1.355744e-04
9,LV1269,C2CP_KEGG_MEDICUS_REFERENCE_26S_PROTEASOME_MEDIATED_PROTEIN_DEGRADATION,0.972103,2.088242e-04
10,LV1269,C2CP_KEGG_MEDICUS_VARIANT_MUTATION_INACTIVATED_UBQLN2_TO_26S_PROTEASOME_MEDIATED_PROTEIN_DEGRADATION,0.956963,3.558377e-04
11,LV1269,C2CP_BIOCARTA_PROTEASOME_PATHWAY,0.999964,1.785997e-02
12,LV1269,C2CP_WP_NSP1_FROM_SARSCOV2_INHIBITS_TRANSLATION_INITIATION_IN_THE_HOST_CELL,0.965509,3.008970e-02
13,LV1269,C2CP_BIOCARTA_SM_PATHWAY,0.994085,5.939067e-02
14,LV1271,C2CP_PID_INTEGRIN3_PATHWAY,0.786049,2.474244e-02
15,LV1271,C2CP_WP_OSTEOBLAST_SIGNALING,0.998034,5.621459e-02
16,LV1271,C2CP_REACTOME_DISSOLUTION_OF_FIBRIN_CLOT,0.960982,6.852737e-02
17,LV1271,C2CP_BIOCARTA_PLATELETAPP_PATHWAY,0.959262,6.962403e-02
18,LV1305,C2CP_REACTOME_METABOLISM_OF_AMINE_DERIVED_HORMONES,0.928997,8.583220e-02
19,LV1483,C2CP_KEGG_MEDICUS_REFERENCE_LOADING_OF_THE_SMC5_SMC6_COMPLEX,0.971932,6.890285e-02
20,LV1530,C2CP_KEGG_MEDICUS_REFERENCE_BLOCKING_UBIQUITINATION_OF_H2AK119_BY_CK2,0.941860,9.210761e-02
21,LV1594,C2CP_REACTOME_MRNA_SPLICING,0.782896,5.264914e-09
22,LV1607,C2CP_REACTOME_HEPARAN_SULFATE_HEPARIN_HS_GAG_METABOLISM,0.831488,3.008970e-02
23,LV302,C2CP_KEGG_MEDICUS_VARIANT_SCRAPIE_CONFORMATION_PRPSC_TO_26S_PROTEASOME_MEDIATED_PROTEIN_DEGRADATION,0.981859,4.324363e-05
24,LV302,C2CP_KEGG_MEDICUS_VARIANT_MUTATION_CAUSED_ABERRANT_ABETA_TO_26S_PROTEASOME_MEDIATED_PROTEIN_DEGRADATION,0.967561,8.071935e-05
25,LV302,C2CP_KEGG_MEDICUS_VARIANT_MUTATION_CAUSED_ABERRANT_SOD1_TO_26S_PROTEASOME_MEDIATED_PROTEIN_DEGRADATION,0.876920,9.837169e-04
26,LV302,C2CP_KEGG_PROTEASOME,0.852715,2.513417e-03
27,LV302,C2CP_KEGG_MEDICUS_VARIANT_MUTATION_INACTIVATED_VCP_TO_26S_PROTEASOME_MEDIATED_PROTEIN_DEGRADATION,0.876941,2.513417e-03
28,LV302,C2CP_REACTOME_REGULATION_OF_ORNITHINE_DECARBOXYLASE_ODC,0.859687,4.382892e-03
29,LV352,C2CP_KEGG_MEDICUS_VARIANT_MLL_ENL_FUSION_TO_TRANSCRIPTIONAL_ACTIVATION,0.948266,7.912769e-02
30,LV352,C2CP_REACTOME_GRB2_EVENTS_IN_ERBB2_SIGNALING,0.929178,9.195666e-02
31,LV4,C2CP_REACTOME_MITOCHONDRIAL_TRANSLATION_ELONGATION,0.982674,3.491544e-10
32,LV4,C2CP_REACTOME_MITOCHONDRIAL_TRANSLATION,0.866429,1.302586e-07
33,LV4,C2CP_KEGG_MEDICUS_REFERENCE_MITOCHONDRIAL_COMPLEX_UCP1_IN_THERMOGENESIS,0.864713,2.615113e-04
34,LV4,C2CP_WP_MITOCHONDRIAL_COMPLEX_IV_ASSEMBLY,0.835834,3.119430e-02
35,LV4,C2CP_KEGG_MEDICUS_REFERENCE_26S_PROTEASOME_MEDIATED_PROTEIN_DEGRADATION,0.735601,9.611163e-02
36,LV53,C2CP_REACTOME_EUKARYOTIC_TRANSLATION_ELONGATION,0.871080,4.365134e-07
37,LV53,C2CP_REACTOME_SRP_DEPENDENT_COTRANSLATIONAL_PROTEIN_TARGETING_TO_MEMBRANE,0.787211,3.033154e-05
38,LV53,C2CP_REACTOME_SELENOAMINO_ACID_METABOLISM,0.769286,7.071167e-05
39,LV53,C2CP_KEGG_RIBOSOME,0.807836,9.601244e-05
40,LV53,C2CP_KEGG_MEDICUS_REFERENCE_TRANSLATION_INITIATION,0.797058,3.157917e-04
41,LV568,C2CP_REACTOME_ACTIVATION_OF_THE_TFAP2_AP_2_FAMILY_OF_TRANSCRIPTION_FACTORS,0.938314,7.504429e-02
42,LV568,C2CP_WP_ESTROGEN_METABOLISM_WP697,0.853523,7.900415e-02
43,LV62,C2CP_WP_ELECTRON_TRANSPORT_CHAIN_OXPHOS_SYSTEM_IN_MITOCHONDRIA,0.933483,1.486160e-10
44,LV62,C2CP_WP_OXIDATIVE_PHOSPHORYLATION,0.975491,1.178694e-07
45,LV62,C2CP_KEGG_MEDICUS_REFERENCE_MITOCHONDRIAL_COMPLEX_UCP1_IN_THERMOGENESIS,0.944173,1.053472e-06
46,LV62,C2CP_KEGG_MEDICUS_VARIANT_MUTATION_INACTIVATED_PINK1_TO_ELECTRON_TRANSFER_IN_COMPLEX_I,0.966362,1.372559e-05
47,LV62,C2CP_KEGG_MEDICUS_REFERENCE_ELECTRON_TRANSFER_IN_COMPLEX_I,0.958140,7.165267e-05
48,LV62,C2CP_REACTOME_FORMATION_OF_ATP_BY_CHEMIOSMOTIC_COUPLING,0.993605,4.524891e-03
49,LV719,C2CP_REACTOME_SYNAPTIC_ADHESION_LIKE_MOLECULES,0.900868,5.700133e-02
50,LV96,C2CP_WP_SMC1SMC3_ROLE_IN_DNA_DAMAGE_CORNELIA_DE_LANGE_SYNDROME,0.999318,5.953087e-02
51,LV96,C2CP_REACTOME_ESTABLISHMENT_OF_SISTER_CHROMATID_COHESION,0.971769,7.144923e-02

In [22]:
colon_pathways = analyze("Colon", "colon")

────────────────────────────────────────────────────────────────
  Colon  (keyword: 'colon')  |  samples in model: 5,768
  Expected in top 1%: 57.7  |  Selected LVs: 24

,LV,n_in_top1pct,enrich_ratio,median_rank_pct,AUC,FDR
0,LV1723,207,3.589,0.4753,0.513889,9.005612e-04
1,LV1218,201,3.485,0.4658,0.517250,3.016837e-05
2,LV1048,200,3.467,0.4601,0.527359,1.700139e-11
3,LV8,198,3.433,0.4625,0.518875,4.805176e-06
4,LV978,193,3.346,0.4599,0.519449,2.423844e-06
5,LV1409,171,2.965,0.4732,0.518699,5.908984e-06
6,LV520,151,2.618,0.4830,0.512915,2.169933e-03
7,LV349,143,2.479,0.4826,0.517469,2.370567e-05
8,LV1416,138,2.393,0.4837,0.513984,8.266831e-04
9,LV1652,134,2.323,0.4753,0.521210,2.326445e-07
10,LV215,132,2.289,0.4529,0.528056,5.185805e-12
11,LV724,131,2.271,0.4777,0.509723,2.480512e-02
12,LV389,128,2.219,0.4768,0.517467,2.370567e-05
13,LV1078,127,2.202,0.4781,0.509003,3.878064e-02
14,LV527,124,2.150,0.5006,0.508964,3.958450e-02
15,LV936,123,2.133,0.4666,0.527660,1.002915e-11
16,LV1420,123,2.133,0.4768,0.517571,2.153925e-05
17,LV1609,122,2.115,0.4751,0.512384,3.376804e-03
18,LV630,121,2.098,0.4795,0.512008,4.615473e-03
19,LV1561,121,2.098,0.4935,0.518783,5.357094e-06
20,LV221,120,2.080,0.4693,0.526469,8.057567e-11
21,LV1594,119,2.063,0.4770,0.522401,4.558828e-08
22,LV274,118,2.046,0.4741,0.516522,6.464578e-05
23,LV590,117,2.028,0.4618,0.525696,2.608342e-10

  Pathways:

,LV,pathway,AUC,FDR
0,LV1048,C2CP_REACTOME_APOPTOSIS_INDUCED_DNA_FRAGMENTATION,0.940064,7.291895e-02
1,LV1218,C2CP_REACTOME_BASE_EXCISION_REPAIR_AP_SITE_FORMATION,0.975499,1.336140e-06
2,LV1218,C2CP_REACTOME_RECOGNITION_AND_ASSOCIATION_OF_DNA_GLYCOSYLASE_WITH_SITE_CONTAINING_AN_AFFECTED_PURINE,0.972102,2.262292e-05
3,LV1218,C2CP_WP_TELOMERE_END_PACKAGING_AND_NEURODEVELOPMENTAL_DISORDERS,0.883677,2.164796e-03
4,LV1218,C2CP_REACTOME_REPLACEMENT_OF_PROTAMINES_BY_NUCLEOSOMES_IN_THE_MALE_PRONUCLEUS,0.914875,4.702992e-03
5,LV1218,C2CP_WP_TESSADORIBICKNELLVAN_HAAFTEN_SYNDROME_VARIANTS_NUCLEOSOME_ASSEMBLY,1.000000,1.977278e-02
6,LV1218,C2CP_REACTOME_DEPOSITION_OF_NEW_CENPA_CONTAINING_NUCLEOSOMES_AT_THE_CENTROMERE,0.721876,3.503176e-02
7,LV1218,C2CP_REACTOME_DNA_METHYLATION,0.701250,7.184344e-02
8,LV1218,C2CP_REACTOME_CONDENSATION_OF_PROPHASE_CHROMOSOMES,0.668963,9.986911e-02
9,LV1416,C2CP_REACTOME_BIOTIN_TRANSPORT_AND_METABOLISM,0.960350,7.447777e-02
10,LV1420,C2CP_REACTOME_MEIOTIC_RECOMBINATION,0.833417,9.408245e-05
11,LV1420,C2CP_REACTOME_INHIBITION_OF_DNA_RECOMBINATION_AT_TELOMERE,0.870496,1.057661e-04
12,LV1420,C2CP_REACTOME_TRANSCRIPTIONAL_REGULATION_BY_SMALL_RNAS,0.812408,5.318460e-04
13,LV1420,C2CP_REACTOME_DNA_METHYLATION,0.840944,8.864573e-04
14,LV1420,C2CP_REACTOME_RECOGNITION_AND_ASSOCIATION_OF_DNA_GLYCOSYLASE_WITH_SITE_CONTAINING_AN_AFFECTED_PURINE,0.849927,2.513417e-03
15,LV1420,C2CP_REACTOME_ACTIVATED_PKN1_STIMULATES_TRANSCRIPTION_OF_AR_ANDROGEN_RECEPTOR_REGULATED_GENES_KLK2_AND_KLK3,0.805951,3.771898e-03
16,LV1420,C2CP_REACTOME_SIRT1_NEGATIVELY_REGULATES_RRNA_EXPRESSION,0.760770,1.214457e-02
17,LV1594,C2CP_REACTOME_MRNA_SPLICING,0.782896,5.264914e-09
18,LV1652,C2CP_WP_DISORDERS_OF_GALACTOSE_METABOLISM,0.984595,5.758828e-02
19,LV1652,C2CP_WP_DEREGULATION_OF_RAB_AND_RAB_EFFECTOR_GENES_IN_BLADDER_CANCER,0.878449,6.536690e-02
20,LV520,C2CP_WP_22Q112_COPY_NUMBER_VARIATION_SYNDROME,0.695576,1.248701e-02

In [23]:
colon_pathways

,LV,pathway,AUC,FDR
0,LV1048,C2CP_REACTOME_APOPTOSIS_INDUCED_DNA_FRAGMENTATION,0.940064,7.291895e-02
1,LV1218,C2CP_REACTOME_BASE_EXCISION_REPAIR_AP_SITE_FORMATION,0.975499,1.336140e-06
2,LV1218,C2CP_REACTOME_RECOGNITION_AND_ASSOCIATION_OF_DNA_GLYCOSYLASE_WITH_SITE_CONTAINING_AN_AFFECTED_PURINE,0.972102,2.262292e-05
3,LV1218,C2CP_WP_TELOMERE_END_PACKAGING_AND_NEURODEVELOPMENTAL_DISORDERS,0.883677,2.164796e-03
4,LV1218,C2CP_REACTOME_REPLACEMENT_OF_PROTAMINES_BY_NUCLEOSOMES_IN_THE_MALE_PRONUCLEUS,0.914875,4.702992e-03
5,LV1218,C2CP_WP_TESSADORIBICKNELLVAN_HAAFTEN_SYNDROME_VARIANTS_NUCLEOSOME_ASSEMBLY,1.000000,1.977278e-02
6,LV1218,C2CP_REACTOME_DEPOSITION_OF_NEW_CENPA_CONTAINING_NUCLEOSOMES_AT_THE_CENTROMERE,0.721876,3.503176e-02
7,LV1218,C2CP_REACTOME_DNA_METHYLATION,0.701250,7.184344e-02
8,LV1218,C2CP_REACTOME_CONDENSATION_OF_PROPHASE_CHROMOSOMES,0.668963,9.986911e-02
9,LV1416,C2CP_REACTOME_BIOTIN_TRANSPORT_AND_METABOLISM,0.960350,7.447777e-02
10,LV1420,C2CP_REACTOME_MEIOTIC_RECOMBINATION,0.833417,9.408245e-05
11,LV1420,C2CP_REACTOME_INHIBITION_OF_DNA_RECOMBINATION_AT_TELOMERE,0.870496,1.057661e-04
12,LV1420,C2CP_REACTOME_TRANSCRIPTIONAL_REGULATION_BY_SMALL_RNAS,0.812408,5.318460e-04
13,LV1420,C2CP_REACTOME_DNA_METHYLATION,0.840944,8.864573e-04
14,LV1420,C2CP_REACTOME_RECOGNITION_AND_ASSOCIATION_OF_DNA_GLYCOSYLASE_WITH_SITE_CONTAINING_AN_AFFECTED_PURINE,0.849927,2.513417e-03
15,LV1420,C2CP_REACTOME_ACTIVATED_PKN1_STIMULATES_TRANSCRIPTION_OF_AR_ANDROGEN_RECEPTOR_REGULATED_GENES_KLK2_AND_KLK3,0.805951,3.771898e-03
16,LV1420,C2CP_REACTOME_SIRT1_NEGATIVELY_REGULATES_RRNA_EXPRESSION,0.760770,1.214457e-02
17,LV1594,C2CP_REACTOME_MRNA_SPLICING,0.782896,5.264914e-09
18,LV1652,C2CP_WP_DISORDERS_OF_GALACTOSE_METABOLISM,0.984595,5.758828e-02
19,LV1652,C2CP_WP_DEREGULATION_OF_RAB_AND_RAB_EFFECTOR_GENES_IN_BLADDER_CANCER,0.878449,6.536690e-02
20,LV520,C2CP_WP_22Q112_COPY_NUMBER_VARIATION_SYNDROME,0.695576,1.248701e-02

In [24]:
esophagus_pathways = analyze("Esophagus", "esophagus")

────────────────────────────────────────────────────────────────
  Esophagus  (keyword: 'esophagus')  |  samples in model: 650
  Expected in top 1%: 6.5  |  Selected LVs: 57

,LV,n_in_top1pct,enrich_ratio,median_rank_pct,AUC,FDR
0,LV291,60,9.231,0.4335,0.537580,2.094774e-03
1,LV146,50,7.692,0.4163,0.558250,1.264360e-06
2,LV690,46,7.077,0.4441,0.559454,7.504734e-07
3,LV1229,44,6.769,0.3967,0.583665,2.686565e-12
4,LV1351,44,6.769,0.4688,0.531330,1.074605e-02
5,LV1344,40,6.154,0.4125,0.578666,4.577100e-11
6,LV21,40,6.154,0.3959,0.563331,1.289232e-07
7,LV111,39,6.000,0.4235,0.536407,2.925917e-03
8,LV1706,37,5.692,0.3830,0.571889,1.875738e-09
9,LV1542,36,5.539,0.4627,0.542799,4.451802e-04
10,LV83,35,5.385,0.3769,0.583489,2.958586e-12
11,LV82,35,5.385,0.3623,0.601092,2.441943e-17
12,LV1006,35,5.385,0.4281,0.553748,8.213675e-06
13,LV354,35,5.385,0.4100,0.573709,6.930220e-10
14,LV871,34,5.231,0.4232,0.551486,2.005441e-05
15,LV880,32,4.923,0.4232,0.581273,1.044897e-11
16,LV1547,31,4.769,0.4832,0.534341,5.082032e-03
17,LV691,30,4.615,0.4804,0.535690,3.539736e-03
18,LV34,30,4.615,0.4055,0.534814,4.465880e-03
19,LV149,29,4.462,0.3659,0.599097,9.441652e-17
20,LV1365,28,4.308,0.3821,0.563981,9.435093e-08
21,LV1657,28,4.308,0.4054,0.573036,9.865123e-10
22,LV485,27,4.154,0.3471,0.606871,3.113889e-19
23,LV976,27,4.154,0.3907,0.544049,2.977986e-04
24,LV1702,26,4.000,0.3843,0.556145,3.124789e-06
25,LV733,26,4.000,0.4670,0.540787,8.246779e-04
26,LV1608,26,4.000,0.4297,0.540402,9.309396e-04
27,LV494,26,4.000,0.4622,0.529981,1.492342e-02
28,LV376,26,4.000,0.4634,0.526583,3.130431e-02
29,LV640,25,3.846,0.4583,0.538651,1.540605e-03
30,LV1557,25,3.846,0.3129,0.623960,2.090365e-25
31,LV432,25,3.846,0.3817,0.575365,2.861309e-10
32,LV569,24,3.692,0.4772,0.524841,4.481193e-02
33,LV1694,24,3.692,0.4461,0.543005,4.192551e-04
34,LV1092,24,3.692,0.4114,0.551746,1.821579e-05
35,LV246,24,3.692,0.4773,0.527034,2.849624e-02
36,LV390,24,3.692,0.3471,0.607454,2.095203e-19
37,LV294,24,3.692,0.3809,0.560925,4.028118e-07
38,LV891,23,3.539,0.3919,0.566709,2.591947e-08
39,LV783,23,3.539,0.3946,0.557330,1.881578e-06
40,LV330,23,3.539,0.4166,0.567866,1.531444e-08
41,LV1600,23,3.539,0.4293,0.538328,1.705464e-03
42,LV306,23,3.539,0.4913,0.529765,1.552257e-02
43,LV1584,22,3.385,0.4441,0.538945,1.419942e-03
44,LV1389,22,3.385,0.4302,0.541844,5.877977e-04
45,LV1563,22,3.385,0.3491,0.596316,6.448408e-16
46,LV162,22,3.385,0.3799,0.593652,4.249921e-15
47,LV343,22,3.385,0.3589,0.559613,7.033700e-07
48,LV774,22,3.385,0.4350,0.532788,7.638685e-03
49,LV41,22,3.385,0.3995,0.547597,8.550591e-05
50,LV879,22,3.385,0.4310,0.548679,5.822009e-05
51,LV670,22,3.385,0.4437,0.532386,8.334203e-03
52,LV439,21,3.231,0.3532,0.586712,3.912078e-13
53,LV1114,21,3.231,0.4081,0.548554,6.071716e-05
54,LV694,21,3.231,0.4256,0.554953,4.965771e-06
55,LV788,20,3.077,0.4089,0.560920,4.028118e-07
56,LV324,20,3.077,0.4229,0.539330,1.284136e-03

  Pathways:

,LV,pathway,AUC,FDR
0,LV1114,C2CP_WP_STRIATED_MUSCLE_CONTRACTION_PATHWAY,0.971312,9.061594e-04
1,LV1114,C2CP_REACTOME_STRIATED_MUSCLE_CONTRACTION,0.986739,2.108424e-03
2,LV1365,C2CP_REACTOME_O_LINKED_GLYCOSYLATION,0.761779,5.595218e-04
3,LV1365,C2CP_WP_MATRIX_METALLOPROTEINASES,0.919316,2.171194e-02
4,LV1365,C2CP_WP_MONOAMINE_GPCRS,1.000000,5.756743e-02
5,LV1365,C2CP_REACTOME_DISEASES_ASSOCIATED_WITH_O_GLYCOSYLATION_OF_PROTEINS,0.715655,6.290342e-02
6,LV1389,C2CP_KEGG_LYSOSOME,0.831486,2.778235e-07
7,LV1389,C2CP_REACTOME_REGULATION_OF_MITF_M_DEPENDENT_GENES_INVOLVED_IN_LYSOSOME_BIOGENESIS_AND_AUTOPHAGY,0.983702,1.822399e-02
8,LV1389,C2CP_WP_DEGRADATION_PATHWAY_OF_SPHINGOLIPIDS_INCLUDING_DISEASES,0.998904,5.568239e-02
9,LV149,C2CP_REACTOME_CS_DS_DEGRADATION,0.858506,8.731811e-02
10,LV1542,C2CP_REACTOME_PHOSPHORYLATION_OF_CD3_AND_TCR_ZETA_CHAINS,0.984851,7.443848e-03
11,LV1542,C2CP_KEGG_AUTOIMMUNE_THYROID_DISEASE,0.819936,4.011300e-02
12,LV1563,C2CP_BIOCARTA_MITOCHONDRIA_PATHWAY,0.890924,6.564056e-02
13,LV1608,C2CP_KEGG_PRIMARY_BILE_ACID_BIOSYNTHESIS,0.997442,5.015040e-02
14,LV162,C2CP_KEGG_MEDICUS_REFERENCE_GLYCOLYSIS,0.850731,5.761553e-02
15,LV1657,C2CP_PID_CD40_PATHWAY,0.765746,9.669561e-02
16,LV1702,C2CP_WP_TYROBP_CAUSAL_NETWORK_IN_MICROGLIA,0.894192,7.502069e-05
17,LV1702,C2CP_WP_MICROGLIA_PATHOGEN_PHAGOCYTOSIS_PATHWAY,0.932639,2.518206e-04
18,LV1702,C2CP_REACTOME_DECTIN_2_FAMILY,0.990210,5.919917e-02
19,LV246,C2CP_REACTOME_CD22_MEDIATED_BCR_REGULATION,0.980485,9.085059e-06
20,LV246,C2CP_REACTOME_ROLE_OF_LAT2_NTAL_LAB_ON_CALCIUM_MOBILIZATION,0.925382,1.526822e-05
21,LV246,C2CP_REACTOME_INITIAL_TRIGGERING_OF_COMPLEMENT,0.904864,4.452524e-05
22,LV246,C2CP_REACTOME_CREATION_OF_C4_AND_C2_ACTIVATORS,0.892864,2.038217e-04
23,LV246,C2CP_REACTOME_FCGR_ACTIVATION,0.867523,6.010797e-04
24,LV246,C2CP_REACTOME_SCAVENGING_OF_HEME_FROM_PLASMA,0.842587,1.703368e-03
25,LV246,C2CP_REACTOME_ANTIGEN_ACTIVATES_B_CELL_RECEPTOR_BCR_LEADING_TO_GENERATION_OF_SECOND_MESSENGERS,0.769875,4.079762e-03
26,LV246,C2CP_REACTOME_FCERI_MEDIATED_CA_2_MOBILIZATION,0.748688,9.415429e-03
27,LV246,C2CP_REACTOME_ROLE_OF_PHOSPHOLIPIDS_IN_PHAGOCYTOSIS,0.730308,2.291280e-02
28,LV294,C2CP_REACTOME_SYNTHESIS_OF_PROSTAGLANDINS_PG_AND_THROMBOXANES_TX,0.998142,5.939019e-02
29,LV324,C2CP_REACTOME_COLLAGEN_FORMATION,0.852151,1.395395e-05
30,LV324,C2CP_REACTOME_COLLAGEN_CHAIN_TRIMERIZATION,0.965591,2.141750e-04
31,LV324,C2CP_REACTOME_COLLAGEN_BIOSYNTHESIS_AND_MODIFYING_ENZYMES,0.861339,3.340383e-04
32,LV324,C2CP_PID_SYNDECAN_1_PATHWAY,0.715568,7.345468e-02
33,LV324,C2CP_KEGG_MEDICUS_REFERENCE_COPII_VESICLE_FORMATION,0.938275,8.629152e-02
34,LV324,C2CP_WP_TYPE_I_COLLAGEN_SYNTHESIS_IN_THE_CONTEXT_OF_OSTEOGENESIS_IMPERFECTA,0.772281,9.147147e-02
35,LV330,C2CP_KEGG_CITRATE_CYCLE_TCA_CYCLE,0.979598,6.355925e-04
36,LV330,C2CP_WP_TCA_CYCLE_AKA_KREBS_OR_CITRIC_ACID_CYCLE,0.999346,9.166647e-03
37,LV330,C2CP_WP_TCA_CYCLE_AND_DEFICIENCY_OF_PYRUVATE_DEHYDROGENASE_COMPLEX_PDHC,0.966233,1.644763e-02
38,LV330,C2CP_KEGG_MEDICUS_REFERENCE_CITRATE_CYCLE_SECOND_CARBON_OXIDATION_2,0.999809,4.221366e-02
39,LV330,C2CP_KEGG_MEDICUS_REFERENCE_BETA_OXIDATION,0.997412,4.358119e-02
40,LV330,C2CP_KEGG_MEDICUS_REFERENCE_ISOLEUCINE_DEGRADATION,0.984470,5.070175e-02
41,LV330,C2CP_WP_HOSTPATHOGEN_INTERACTION_OF_HUMAN_CORONAVIRUSES_APOPTOSIS,0.807361,6.852737e-02
42,LV34,C2CP_REACTOME_SYNTHESIS_OF_BILE_ACIDS_AND_BILE_SALTS_VIA_24_HYDROXYCHOLESTEROL,0.931741,8.821433e-02
43,LV640,C2CP_WP_GLUTATHIONE_METABOLISM,0.940051,4.992725e-02
44,LV640,C2CP_REACTOME_ASPIRIN_ADME,0.939759,5.008835e-02
45,LV640,C2CP_BIOCARTA_NKCELLS_PATHWAY,0.888609,7.154306e-02
46,LV640,C2CP_WP_DEVELOPMENT_OF_PULMONARY_DENDRITIC_CELLS_AND_MACROPHAGE_SUBSETS,0.960843,8.072884e-02
47,LV733,C2CP_REACTOME_SIGNALING_BY_FLT3_ITD_AND_TKD_MUTANTS,0.959308,2.012805e-02
48,LV733,C2CP_SA_MMP_CYTOKINE_CONNECTION,0.958837,2.029828e-02
49,LV871,C2CP_WP_PEPTIDE_GPCRS,0.809123,2.596898e-02
50,LV879,C2CP_KEGG_ALLOGRAFT_REJECTION,1.000000,3.894095e-04
51,LV879,C2CP_KEGG_AUTOIMMUNE_THYROID_DISEASE,0.999991,3.894095e-04
52,LV879,C2CP_KEGG_ANTIGEN_PROCESSING_AND_PRESENTATION,0.766651,1.284769e-02
53,LV879,C2CP_KEGG_GRAFT_VERSUS_HOST_DISEASE,0.860593,1.785997e-02
54,LV879,C2CP_KEGG_MEDICUS_PATHOGEN_HTLV_1_TAX_TO_NFY_MEDIATED_TRANSCRIPTION,0.999982,2.058628e-02
55,LV880,C2CP_WP_2Q112_COPY_NUMBER_VARIATION_SYNDROME,0.760439,7.291649e-02

In [25]:
esophagus_pathways

,LV,pathway,AUC,FDR
0,LV1114,C2CP_WP_STRIATED_MUSCLE_CONTRACTION_PATHWAY,0.971312,9.061594e-04
1,LV1114,C2CP_REACTOME_STRIATED_MUSCLE_CONTRACTION,0.986739,2.108424e-03
2,LV1365,C2CP_REACTOME_O_LINKED_GLYCOSYLATION,0.761779,5.595218e-04
3,LV1365,C2CP_WP_MATRIX_METALLOPROTEINASES,0.919316,2.171194e-02
4,LV1365,C2CP_WP_MONOAMINE_GPCRS,1.000000,5.756743e-02
5,LV1365,C2CP_REACTOME_DISEASES_ASSOCIATED_WITH_O_GLYCOSYLATION_OF_PROTEINS,0.715655,6.290342e-02
6,LV1389,C2CP_KEGG_LYSOSOME,0.831486,2.778235e-07
7,LV1389,C2CP_REACTOME_REGULATION_OF_MITF_M_DEPENDENT_GENES_INVOLVED_IN_LYSOSOME_BIOGENESIS_AND_AUTOPHAGY,0.983702,1.822399e-02
8,LV1389,C2CP_WP_DEGRADATION_PATHWAY_OF_SPHINGOLIPIDS_INCLUDING_DISEASES,0.998904,5.568239e-02
9,LV149,C2CP_REACTOME_CS_DS_DEGRADATION,0.858506,8.731811e-02
10,LV1542,C2CP_REACTOME_PHOSPHORYLATION_OF_CD3_AND_TCR_ZETA_CHAINS,0.984851,7.443848e-03
11,LV1542,C2CP_KEGG_AUTOIMMUNE_THYROID_DISEASE,0.819936,4.011300e-02
12,LV1563,C2CP_BIOCARTA_MITOCHONDRIA_PATHWAY,0.890924,6.564056e-02
13,LV1608,C2CP_KEGG_PRIMARY_BILE_ACID_BIOSYNTHESIS,0.997442,5.015040e-02
14,LV162,C2CP_KEGG_MEDICUS_REFERENCE_GLYCOLYSIS,0.850731,5.761553e-02
15,LV1657,C2CP_PID_CD40_PATHWAY,0.765746,9.669561e-02
16,LV1702,C2CP_WP_TYROBP_CAUSAL_NETWORK_IN_MICROGLIA,0.894192,7.502069e-05
17,LV1702,C2CP_WP_MICROGLIA_PATHOGEN_PHAGOCYTOSIS_PATHWAY,0.932639,2.518206e-04
18,LV1702,C2CP_REACTOME_DECTIN_2_FAMILY,0.990210,5.919917e-02
19,LV246,C2CP_REACTOME_CD22_MEDIATED_BCR_REGULATION,0.980485,9.085059e-06
20,LV246,C2CP_REACTOME_ROLE_OF_LAT2_NTAL_LAB_ON_CALCIUM_MOBILIZATION,0.925382,1.526822e-05
21,LV246,C2CP_REACTOME_INITIAL_TRIGGERING_OF_COMPLEMENT,0.904864,4.452524e-05
22,LV246,C2CP_REACTOME_CREATION_OF_C4_AND_C2_ACTIVATORS,0.892864,2.038217e-04
23,LV246,C2CP_REACTOME_FCGR_ACTIVATION,0.867523,6.010797e-04
24,LV246,C2CP_REACTOME_SCAVENGING_OF_HEME_FROM_PLASMA,0.842587,1.703368e-03
25,LV246,C2CP_REACTOME_ANTIGEN_ACTIVATES_B_CELL_RECEPTOR_BCR_LEADING_TO_GENERATION_OF_SECOND_MESSENGERS,0.769875,4.079762e-03
26,LV246,C2CP_REACTOME_FCERI_MEDIATED_CA_2_MOBILIZATION,0.748688,9.415429e-03
27,LV246,C2CP_REACTOME_ROLE_OF_PHOSPHOLIPIDS_IN_PHAGOCYTOSIS,0.730308,2.291280e-02
28,LV294,C2CP_REACTOME_SYNTHESIS_OF_PROSTAGLANDINS_PG_AND_THROMBOXANES_TX,0.998142,5.939019e-02
29,LV324,C2CP_REACTOME_COLLAGEN_FORMATION,0.852151,1.395395e-05
30,LV324,C2CP_REACTOME_COLLAGEN_CHAIN_TRIMERIZATION,0.965591,2.141750e-04
31,LV324,C2CP_REACTOME_COLLAGEN_BIOSYNTHESIS_AND_MODIFYING_ENZYMES,0.861339,3.340383e-04
32,LV324,C2CP_PID_SYNDECAN_1_PATHWAY,0.715568,7.345468e-02
33,LV324,C2CP_KEGG_MEDICUS_REFERENCE_COPII_VESICLE_FORMATION,0.938275,8.629152e-02
34,LV324,C2CP_WP_TYPE_I_COLLAGEN_SYNTHESIS_IN_THE_CONTEXT_OF_OSTEOGENESIS_IMPERFECTA,0.772281,9.147147e-02
35,LV330,C2CP_KEGG_CITRATE_CYCLE_TCA_CYCLE,0.979598,6.355925e-04
36,LV330,C2CP_WP_TCA_CYCLE_AKA_KREBS_OR_CITRIC_ACID_CYCLE,0.999346,9.166647e-03
37,LV330,C2CP_WP_TCA_CYCLE_AND_DEFICIENCY_OF_PYRUVATE_DEHYDROGENASE_COMPLEX_PDHC,0.966233,1.644763e-02
38,LV330,C2CP_KEGG_MEDICUS_REFERENCE_CITRATE_CYCLE_SECOND_CARBON_OXIDATION_2,0.999809,4.221366e-02
39,LV330,C2CP_KEGG_MEDICUS_REFERENCE_BETA_OXIDATION,0.997412,4.358119e-02
40,LV330,C2CP_KEGG_MEDICUS_REFERENCE_ISOLEUCINE_DEGRADATION,0.984470,5.070175e-02
41,LV330,C2CP_WP_HOSTPATHOGEN_INTERACTION_OF_HUMAN_CORONAVIRUSES_APOPTOSIS,0.807361,6.852737e-02
42,LV34,C2CP_REACTOME_SYNTHESIS_OF_BILE_ACIDS_AND_BILE_SALTS_VIA_24_HYDROXYCHOLESTEROL,0.931741,8.821433e-02
43,LV640,C2CP_WP_GLUTATHIONE_METABOLISM,0.940051,4.992725e-02
44,LV640,C2CP_REACTOME_ASPIRIN_ADME,0.939759,5.008835e-02
45,LV640,C2CP_BIOCARTA_NKCELLS_PATHWAY,0.888609,7.154306e-02
46,LV640,C2CP_WP_DEVELOPMENT_OF_PULMONARY_DENDRITIC_CELLS_AND_MACROPHAGE_SUBSETS,0.960843,8.072884e-02
47,LV733,C2CP_REACTOME_SIGNALING_BY_FLT3_ITD_AND_TKD_MUTANTS,0.959308,2.012805e-02
48,LV733,C2CP_SA_MMP_CYTOKINE_CONNECTION,0.958837,2.029828e-02
49,LV871,C2CP_WP_PEPTIDE_GPCRS,0.809123,2.596898e-02
50,LV879,C2CP_KEGG_ALLOGRAFT_REJECTION,1.000000,3.894095e-04
51,LV879,C2CP_KEGG_AUTOIMMUNE_THYROID_DISEASE,0.999991,3.894095e-04
52,LV879,C2CP_KEGG_ANTIGEN_PROCESSING_AND_PRESENTATION,0.766651,1.284769e-02
53,LV879,C2CP_KEGG_GRAFT_VERSUS_HOST_DISEASE,0.860593,1.785997e-02
54,LV879,C2CP_KEGG_MEDICUS_PATHOGEN_HTLV_1_TAX_TO_NFY_MEDIATED_TRANSCRIPTION,0.999982,2.058628e-02
55,LV880,C2CP_WP_2Q112_COPY_NUMBER_VARIATION_SYNDROME,0.760439,7.291649e-02

In [26]:
heart_pathways = analyze("Heart", "heart")

────────────────────────────────────────────────────────────────
  Heart  (keyword: 'heart')  |  samples in model: 1,959
  Expected in top 1%: 19.6  |  Selected LVs: 96

,LV,n_in_top1pct,enrich_ratio,median_rank_pct,AUC,FDR
0,LV82,177,9.035,0.3623,0.580442,6.603973e-32
1,LV104,117,5.973,0.4525,0.535464,3.407298e-07
2,LV351,105,5.360,0.5016,0.518120,1.140058e-02
3,LV967,100,5.105,0.4510,0.539211,1.586296e-08
4,LV1493,98,5.003,0.4643,0.534760,5.682765e-07
5,LV1282,95,4.850,0.4728,0.540943,3.413076e-09
6,LV882,95,4.850,0.4607,0.524598,5.108630e-04
7,LV1562,92,4.696,0.4654,0.525421,3.214283e-04
8,LV1166,88,4.492,0.4426,0.548019,3.710843e-12
9,LV162,86,4.390,0.4510,0.534230,8.321574e-07
10,LV191,82,4.186,0.4100,0.565291,1.741339e-21
11,LV164,81,4.135,0.4905,0.514608,4.433006e-02
12,LV83,81,4.135,0.4642,0.525484,3.101323e-04
13,LV214,78,3.982,0.4528,0.549531,7.952526e-13
14,LV1680,75,3.829,0.4288,0.546888,1.159024e-11
15,LV472,74,3.778,0.4817,0.518389,1.028351e-02
16,LV119,72,3.675,0.4697,0.523072,1.125376e-03
17,LV1527,71,3.624,0.4598,0.534321,7.806035e-07
18,LV269,69,3.522,0.4258,0.541757,1.589426e-09
19,LV952,69,3.522,0.4551,0.530469,1.332671e-05
20,LV1223,67,3.420,0.4678,0.517454,1.495030e-02
21,LV1432,63,3.216,0.4393,0.536038,2.179821e-07
22,LV1352,62,3.165,0.4258,0.535746,2.710468e-07
23,LV1057,62,3.165,0.4445,0.526383,1.832927e-04
24,LV323,62,3.165,0.4437,0.547716,4.923732e-12
25,LV844,61,3.114,0.4623,0.522347,1.617998e-03
26,LV396,61,3.114,0.4698,0.521032,3.015458e-03
27,LV1036,60,3.063,0.4581,0.532988,2.124256e-06
28,LV1498,59,3.012,0.4764,0.521230,2.749536e-03
29,LV15,59,3.012,0.4589,0.515284,3.467014e-02
30,LV1323,58,2.961,0.4646,0.518842,8.452994e-03
31,LV861,58,2.961,0.4459,0.544759,9.571316e-11
32,LV581,57,2.910,0.4621,0.516166,2.494795e-02
33,LV86,56,2.859,0.4384,0.547467,6.400569e-12
34,LV298,55,2.808,0.4517,0.526070,2.194539e-04
35,LV1600,55,2.808,0.4252,0.542495,8.295108e-10
36,LV1576,54,2.757,0.4525,0.526000,2.282326e-04
37,LV1406,54,2.757,0.4750,0.524441,5.532083e-04
38,LV370,54,2.757,0.4361,0.535883,2.441008e-07
39,LV915,54,2.757,0.4421,0.546935,1.119621e-11
40,LV1609,53,2.706,0.4982,0.515521,3.164182e-02
41,LV1322,53,2.706,0.4306,0.535069,4.610701e-07
42,LV1465,53,2.706,0.4584,0.538754,2.326299e-08
43,LV673,52,2.654,0.4066,0.558153,2.795296e-17
44,LV1644,52,2.654,0.4486,0.528272,5.635408e-05
45,LV1362,52,2.654,0.4386,0.537025,9.698503e-08
46,LV1035,51,2.603,0.4625,0.523738,8.072071e-04
47,LV445,51,2.603,0.4365,0.541274,2.514692e-09
48,LV456,51,2.603,0.4641,0.529412,2.732742e-05
49,LV997,50,2.552,0.4628,0.518843,8.452994e-03
50,LV578,50,2.552,0.4446,0.550288,3.515367e-13
51,LV105,50,2.552,0.4581,0.519916,5.186936e-03
52,LV643,50,2.552,0.4343,0.537758,5.284539e-08
53,LV814,50,2.552,0.4973,0.517667,1.384902e-02
54,LV1573,50,2.552,0.4725,0.524660,4.940281e-04
55,LV1325,49,2.501,0.4783,0.515589,3.083162e-02
56,LV1071,49,2.501,0.4677,0.520491,3.959061e-03
57,LV1692,49,2.501,0.4366,0.543387,3.576245e-10
58,LV361,48,2.450,0.4466,0.534628,6.282409e-07
59,LV352,48,2.450,0.4158,0.532271,3.690945e-06
60,LV677,48,2.450,0.4378,0.556808,1.651664e-16
61,LV344,48,2.450,0.4772,0.516740,1.999580e-02
62,LV1278,48,2.450,0.4687,0.517304,1.593691e-02
63,LV1660,46,2.348,0.4616,0.524125,6.561157e-04
64,LV183,46,2.348,0.4666,0.534626,6.282409e-07
65,LV1629,46,2.348,0.4751,0.521084,2.948427e-03
66,LV888,45,2.297,0.4603,0.523079,1.124129e-03
67,LV482,45,2.297,0.4428,0.546044,2.745226e-11
68,LV1636,45,2.297,0.4756,0.520631,3.718693e-03
69,LV1083,44,2.246,0.4674,0.516177,2.487933e-02
70,LV1616,44,2.246,0.4762,0.520494,3.959061e-03
71,LV378,44,2.246,0.4692,0.521319,2.663430e-03
72,LV1184,44,2.246,0.4693,0.524195,6.354827e-04
73,LV897,44,2.246,0.4242,0.542535,8.060186e-10
74,LV862,43,2.195,0.4567,0.515603,3.077891e-02
75,LV1379,43,2.195,0.4628,0.529063,3.452769e-05
76,LV1618,43,2.195,0.4715,0.528798,4.020049e-05
77,LV1135,43,2.195,0.4390,0.526308,1.912867e-04
78,LV983,43,2.195,0.4275,0.533029,2.067358e-06
79,LV1102,43,2.195,0.4217,0.548614,1.998315e-12
80,LV212,42,2.144,0.4660,0.538435,3.022758e-08
81,LV808,42,2.144,0.4549,0.524181,6.386620e-04
82,LV1128,42,2.144,0.4594,0.530679,1.162417e-05
83,LV1333,42,2.144,0.4422,0.530659,1.174538e-05
84,LV1447,42,2.144,0.5010,0.517519,1.460607e-02
85,LV349,42,2.144,0.4657,0.529906,1.961256e-05
86,LV1564,42,2.144,0.4405,0.539276,1.506201e-08
87,LV1514,41,2.093,0.4279,0.537871,4.859737e-08
88,LV522,41,2.093,0.4441,0.535150,4.363661e-07
89,LV420,41,2.093,0.4748,0.521262,2.720388e-03
90,LV145,40,2.042,0.3987,0.575652,2.236515e-28
91,LV1024,40,2.042,0.4753,0.517928,1.238585e-02
92,LV686,40,2.042,0.4237,0.549323,9.632553e-13
93,LV89,40,2.042,0.4816,0.518448,1.003434e-02
94,LV1433,40,2.042,0.4337,0.550176,3.904221e-13
95,LV721,40,2.042,0.4329,0.531986,4.536427e-06

  Pathways:

,LV,pathway,AUC,FDR
0,LV1024,C2CP_REACTOME_DEVELOPMENTAL_LINEAGE_OF_MAMMARY_GLAND_MYOEPITHELIAL_CELLS,0.992725,0.004919
1,LV1024,C2CP_REACTOME_DEVELOPMENTAL_LINEAGE_OF_MAMMARY_GLAND_LUMINAL_EPITHELIAL_CELLS,0.807711,0.087594
2,LV1024,C2CP_REACTOME_FORMATION_OF_THE_CORNIFIED_ENVELOPE,0.711649,0.096260
3,LV105,C2CP_WP_SULFATION_BIOTRANSFORMATION_REACTION,0.996219,0.015614
4,LV105,C2CP_WP_TAMOXIFEN_METABOLISM,0.999700,0.055682
5,LV1057,C2CP_BIOCARTA_VITCB_PATHWAY,0.934916,0.093600
6,LV1166,C2CP_BIOCARTA_COMP_PATHWAY,0.960698,0.026963
7,LV1166,C2CP_BIOCARTA_CLASSIC_PATHWAY,0.988744,0.057588
8,LV119,C2CP_WP_NOTCH1_REGULATION_OF_ENDOTHELIAL_CELL_CALCIFICATION,0.991041,0.018023
9,LV119,C2CP_WP_OLIGODENDROCYTE_DEVELOPMENT,0.801646,0.028716
10,LV119,C2CP_REACTOME_YAP1_AND_WWTR1_TAZ_STIMULATED_GENE_EXPRESSION,0.956162,0.072916
11,LV1278,C2CP_REACTOME_CHROMATIN_MODIFICATIONS_DURING_THE_MATERNAL_TO_ZYGOTIC_TRANSITION_MZT,0.739040,0.014291
12,LV1278,C2CP_REACTOME_ASSEMBLY_OF_THE_ORC_COMPLEX_AT_THE_ORIGIN_OF_REPLICATION,0.738931,0.014330
13,LV1278,C2CP_REACTOME_CONDENSATION_OF_PROPHASE_CHROMOSOMES,0.704524,0.033033
14,LV1278,C2CP_REACTOME_REPLACEMENT_OF_PROTAMINES_BY_NUCLEOSOMES_IN_THE_MALE_PRONUCLEUS,0.755027,0.066373
15,LV1278,C2CP_REACTOME_SIRT1_NEGATIVELY_REGULATES_RRNA_EXPRESSION,0.665161,0.090870
16,LV1282,C2CP_WP_1P36_COPY_NUMBER_VARIATION_SYNDROME,0.836119,0.000007
17,LV1322,C2CP_BIOCARTA_PLATELETAPP_PATHWAY,0.998852,0.054850
18,LV1433,C2CP_REACTOME_LAMININ_INTERACTIONS,0.818455,0.029892
19,LV145,C2CP_REACTOME_AMINE_LIGAND_BINDING_RECEPTORS,0.931038,0.086353
20,LV15,C2CP_WP_CHOLESTEROL_SYNTHESIS_DISORDERS,0.899240,0.056336
21,LV15,C2CP_KEGG_STEROID_BIOSYNTHESIS,0.893015,0.057665
22,LV1527,C2CP_WP_TYROBP_CAUSAL_NETWORK_IN_MICROGLIA,0.856276,0.000363
23,LV1527,C2CP_BIOCARTA_CYTOKINE_PATHWAY,0.973048,0.063433
24,LV1562,C2CP_WP_TYROBP_CAUSAL_NETWORK_IN_MICROGLIA,0.751391,0.022576
25,LV1562,C2CP_WP_CELL_INTERACTIONS_IN_PANCREATIC_CANCER_MICROENVIRONMENT,0.833559,0.048747
26,LV1562,C2CP_WP_COVID19_ADVERSE_OUTCOME_PATHWAY,0.982100,0.062685
27,LV1564,C2CP_REACTOME_COMMON_PATHWAY_OF_FIBRIN_CLOT_FORMATION,0.886587,0.061209
28,LV1564,C2CP_REACTOME_FORMATION_OF_FIBRIN_CLOT_CLOTTING_CASCADE,0.774977,0.083269
29,LV1576,C2CP_REACTOME_ASPARTATE_AND_ASPARAGINE_METABOLISM,0.922978,0.091734
30,LV1616,C2CP_REACTOME_TRYPTOPHAN_CATABOLISM,0.975463,0.060706
31,LV1616,C2CP_WP_ESTROGEN_RECEPTOR_PATHWAY,0.960560,0.067668
32,LV162,C2CP_KEGG_MEDICUS_REFERENCE_GLYCOLYSIS,0.850731,0.057616
33,LV1636,C2CP_REACTOME_OLFACTORY_SIGNALING_PATHWAY,0.752855,0.066973
34,LV1636,C2CP_REACTOME_PROTEIN_LIPOYLATION,0.963968,0.071661
35,LV1636,C2CP_KEGG_OLFACTORY_TRANSDUCTION,0.712628,0.079608
36,LV1692,C2CP_REACTOME_CARNITINE_SHUTTLE,1.000000,0.056395
37,LV214,C2CP_REACTOME_INTERLEUKIN_2_FAMILY_SIGNALING,0.764312,0.057345
38,LV214,C2CP_WP_HEMATOPOIETIC_STEM_CELL_DIFFERENTIATION,0.701026,0.093161
39,LV298,C2CP_WP_CORI_CYCLE,0.999344,0.052773
40,LV298,C2CP_WP_GLYCOLYSIS_IN_SENESCENCE,0.968724,0.060174
41,LV351,C2CP_REACTOME_SIGNALING_BY_KIT_IN_DISEASE,0.812643,0.076099
42,LV352,C2CP_KEGG_MEDICUS_VARIANT_MLL_ENL_FUSION_TO_TRANSCRIPTIONAL_ACTIVATION,0.948266,0.079128
43,LV352,C2CP_REACTOME_GRB2_EVENTS_IN_ERBB2_SIGNALING,0.929178,0.091957
44,LV361,C2CP_KEGG_SPHINGOLIPID_METABOLISM,0.977475,0.000639
45,LV361,C2CP_WP_SPHINGOLIPID_METABOLISM_INTEGRATED_PATHWAY,0.991204,0.001656
46,LV370,C2CP_PID_S1P_META_PATHWAY,0.836569,0.060174
47,LV482,C2CP_REACTOME_RECEPTOR_TYPE_TYROSINE_PROTEIN_PHOSPHATASES,0.858607,0.082837
48,LV578,C2CP_REACTOME_MOLECULES_ASSOCIATED_WITH_ELASTIC_FIBRES,0.921864,0.003410
49,LV578,C2CP_REACTOME_ECM_PROTEOGLYCANS,0.767134,0.010830
50,LV578,C2CP_WP_MIR5093P_ALTERATION_OF_YAP1ECM_AXIS,0.978643,0.024742
51,LV581,C2CP_BIOCARTA_PLATELETAPP_PATHWAY,0.958372,0.066973
52,LV581,C2CP_REACTOME_PI_3K_CASCADE_FGFR4,0.941481,0.076805
53,LV643,C2CP_REACTOME_ASSEMBLY_OF_ACTIVE_LPL_AND_LIPC_LIPASE_COMPLEXES,0.988301,0.061093
54,LV643,C2CP_WP_FAMILIAL_HYPERLIPIDEMIA_TYPE_1,0.953858,0.079588
55,LV673,C2CP_REACTOME_FIBRONECTIN_MATRIX_FORMATION,0.809890,0.079588
56,LV686,C2CP_WP_OMEGA6FATTY_ACIDS_IN_SENESCENCE,0.851749,0.001850
57,LV686,C2CP_WP_OMEGA3FATTY_ACIDS_IN_SENESCENCE,0.952917,0.003135
58,LV686,C2CP_WP_SIGNALING_LIPIDS,0.922378,0.017584
59,LV686,C2CP_WP_LIPID_METABOLISM_IN_SENESCENT_CELLS,0.948888,0.074285
60,LV686,C2CP_WP_EICOSANOID_SYNTHESIS,0.811975,0.079608
61,LV721,C2CP_REACTOME_CGMP_EFFECTS,1.000000,0.019885
62,LV721,C2CP_WP_MATRIX_METALLOPROTEINASES,0.896319,0.037607
63,LV721,C2CP_REACTOME_NITRIC_OXIDE_STIMULATES_GUANYLATE_CYCLASE,0.874802,0.052654
64,LV721,C2CP_REACTOME_ACTIVATION_OF_MATRIX_METALLOPROTEINASES,0.835106,0.052747
65,LV721,C2CP_KEGG_MEDICUS_PATHOGEN_EBV_EBNA3C_TO_P53_MEDIATED_TRANSCRIPTION,1.000000,0.059629
66,LV808,C2CP_REACTOME_INTERLEUKIN_20_FAMILY_SIGNALING,0.922986,0.052773
67,LV808,C2CP_BIOCARTA_IL10_PATHWAY,0.999946,0.057282
68,LV86,C2CP_REACTOME_CELL_EXTRACELLULAR_MATRIX_INTERACTIONS,0.989144,0.016422
69,LV86,C2CP_REACTOME_NCAM1_INTERACTIONS,0.817495,0.030307
70,LV888,C2CP_WP_PATHOPHYSIOLOGICAL_ROLES_OF_DUX4_IN_FSHD1,0.983912,0.056567
71,LV89,C2CP_REACTOME_MITOCHONDRIAL_MRNA_MODIFICATION,0.940351,0.084681
72,LV915,C2CP_WP_ULCERATIVE_COLITIS_SIGNALING,0.845826,0.093161
73,LV967,C2CP_WP_SIGNALING_LIPIDS,0.985629,0.004966
74,LV967,C2CP_REACTOME_BIOSYNTHESIS_OF_SPECIALIZED_PRORESOLVING_MEDIATORS_SPMS,0.994328,0.016156
75,LV967,C2CP_WP_OMEGA3FATTY_ACIDS_IN_SENESCENCE,0.845075,0.034066
76,LV967,C2CP_WP_LEUKOTRIENE_METABOLIC_PATHWAY,0.995801,0.056336

In [27]:
heart_pathways

,LV,pathway,AUC,FDR
0,LV1024,C2CP_REACTOME_DEVELOPMENTAL_LINEAGE_OF_MAMMARY_GLAND_MYOEPITHELIAL_CELLS,0.992725,0.004919
1,LV1024,C2CP_REACTOME_DEVELOPMENTAL_LINEAGE_OF_MAMMARY_GLAND_LUMINAL_EPITHELIAL_CELLS,0.807711,0.087594
2,LV1024,C2CP_REACTOME_FORMATION_OF_THE_CORNIFIED_ENVELOPE,0.711649,0.096260
3,LV105,C2CP_WP_SULFATION_BIOTRANSFORMATION_REACTION,0.996219,0.015614
4,LV105,C2CP_WP_TAMOXIFEN_METABOLISM,0.999700,0.055682
5,LV1057,C2CP_BIOCARTA_VITCB_PATHWAY,0.934916,0.093600
6,LV1166,C2CP_BIOCARTA_COMP_PATHWAY,0.960698,0.026963
7,LV1166,C2CP_BIOCARTA_CLASSIC_PATHWAY,0.988744,0.057588
8,LV119,C2CP_WP_NOTCH1_REGULATION_OF_ENDOTHELIAL_CELL_CALCIFICATION,0.991041,0.018023
9,LV119,C2CP_WP_OLIGODENDROCYTE_DEVELOPMENT,0.801646,0.028716
10,LV119,C2CP_REACTOME_YAP1_AND_WWTR1_TAZ_STIMULATED_GENE_EXPRESSION,0.956162,0.072916
11,LV1278,C2CP_REACTOME_CHROMATIN_MODIFICATIONS_DURING_THE_MATERNAL_TO_ZYGOTIC_TRANSITION_MZT,0.739040,0.014291
12,LV1278,C2CP_REACTOME_ASSEMBLY_OF_THE_ORC_COMPLEX_AT_THE_ORIGIN_OF_REPLICATION,0.738931,0.014330
13,LV1278,C2CP_REACTOME_CONDENSATION_OF_PROPHASE_CHROMOSOMES,0.704524,0.033033
14,LV1278,C2CP_REACTOME_REPLACEMENT_OF_PROTAMINES_BY_NUCLEOSOMES_IN_THE_MALE_PRONUCLEUS,0.755027,0.066373
15,LV1278,C2CP_REACTOME_SIRT1_NEGATIVELY_REGULATES_RRNA_EXPRESSION,0.665161,0.090870
16,LV1282,C2CP_WP_1P36_COPY_NUMBER_VARIATION_SYNDROME,0.836119,0.000007
17,LV1322,C2CP_BIOCARTA_PLATELETAPP_PATHWAY,0.998852,0.054850
18,LV1433,C2CP_REACTOME_LAMININ_INTERACTIONS,0.818455,0.029892
19,LV145,C2CP_REACTOME_AMINE_LIGAND_BINDING_RECEPTORS,0.931038,0.086353
20,LV15,C2CP_WP_CHOLESTEROL_SYNTHESIS_DISORDERS,0.899240,0.056336
21,LV15,C2CP_KEGG_STEROID_BIOSYNTHESIS,0.893015,0.057665
22,LV1527,C2CP_WP_TYROBP_CAUSAL_NETWORK_IN_MICROGLIA,0.856276,0.000363
23,LV1527,C2CP_BIOCARTA_CYTOKINE_PATHWAY,0.973048,0.063433
24,LV1562,C2CP_WP_TYROBP_CAUSAL_NETWORK_IN_MICROGLIA,0.751391,0.022576
25,LV1562,C2CP_WP_CELL_INTERACTIONS_IN_PANCREATIC_CANCER_MICROENVIRONMENT,0.833559,0.048747
26,LV1562,C2CP_WP_COVID19_ADVERSE_OUTCOME_PATHWAY,0.982100,0.062685
27,LV1564,C2CP_REACTOME_COMMON_PATHWAY_OF_FIBRIN_CLOT_FORMATION,0.886587,0.061209
28,LV1564,C2CP_REACTOME_FORMATION_OF_FIBRIN_CLOT_CLOTTING_CASCADE,0.774977,0.083269
29,LV1576,C2CP_REACTOME_ASPARTATE_AND_ASPARAGINE_METABOLISM,0.922978,0.091734
30,LV1616,C2CP_REACTOME_TRYPTOPHAN_CATABOLISM,0.975463,0.060706
31,LV1616,C2CP_WP_ESTROGEN_RECEPTOR_PATHWAY,0.960560,0.067668
32,LV162,C2CP_KEGG_MEDICUS_REFERENCE_GLYCOLYSIS,0.850731,0.057616
33,LV1636,C2CP_REACTOME_OLFACTORY_SIGNALING_PATHWAY,0.752855,0.066973
34,LV1636,C2CP_REACTOME_PROTEIN_LIPOYLATION,0.963968,0.071661
35,LV1636,C2CP_KEGG_OLFACTORY_TRANSDUCTION,0.712628,0.079608
36,LV1692,C2CP_REACTOME_CARNITINE_SHUTTLE,1.000000,0.056395
37,LV214,C2CP_REACTOME_INTERLEUKIN_2_FAMILY_SIGNALING,0.764312,0.057345
38,LV214,C2CP_WP_HEMATOPOIETIC_STEM_CELL_DIFFERENTIATION,0.701026,0.093161
39,LV298,C2CP_WP_CORI_CYCLE,0.999344,0.052773
40,LV298,C2CP_WP_GLYCOLYSIS_IN_SENESCENCE,0.968724,0.060174
41,LV351,C2CP_REACTOME_SIGNALING_BY_KIT_IN_DISEASE,0.812643,0.076099
42,LV352,C2CP_KEGG_MEDICUS_VARIANT_MLL_ENL_FUSION_TO_TRANSCRIPTIONAL_ACTIVATION,0.948266,0.079128
43,LV352,C2CP_REACTOME_GRB2_EVENTS_IN_ERBB2_SIGNALING,0.929178,0.091957
44,LV361,C2CP_KEGG_SPHINGOLIPID_METABOLISM,0.977475,0.000639
45,LV361,C2CP_WP_SPHINGOLIPID_METABOLISM_INTEGRATED_PATHWAY,0.991204,0.001656
46,LV370,C2CP_PID_S1P_META_PATHWAY,0.836569,0.060174
47,LV482,C2CP_REACTOME_RECEPTOR_TYPE_TYROSINE_PROTEIN_PHOSPHATASES,0.858607,0.082837
48,LV578,C2CP_REACTOME_MOLECULES_ASSOCIATED_WITH_ELASTIC_FIBRES,0.921864,0.003410
49,LV578,C2CP_REACTOME_ECM_PROTEOGLYCANS,0.767134,0.010830
50,LV578,C2CP_WP_MIR5093P_ALTERATION_OF_YAP1ECM_AXIS,0.978643,0.024742
51,LV581,C2CP_BIOCARTA_PLATELETAPP_PATHWAY,0.958372,0.066973
52,LV581,C2CP_REACTOME_PI_3K_CASCADE_FGFR4,0.941481,0.076805
53,LV643,C2CP_REACTOME_ASSEMBLY_OF_ACTIVE_LPL_AND_LIPC_LIPASE_COMPLEXES,0.988301,0.061093
54,LV643,C2CP_WP_FAMILIAL_HYPERLIPIDEMIA_TYPE_1,0.953858,0.079588
55,LV673,C2CP_REACTOME_FIBRONECTIN_MATRIX_FORMATION,0.809890,0.079588
56,LV686,C2CP_WP_OMEGA6FATTY_ACIDS_IN_SENESCENCE,0.851749,0.001850
57,LV686,C2CP_WP_OMEGA3FATTY_ACIDS_IN_SENESCENCE,0.952917,0.003135
58,LV686,C2CP_WP_SIGNALING_LIPIDS,0.922378,0.017584
59,LV686,C2CP_WP_LIPID_METABOLISM_IN_SENESCENT_CELLS,0.948888,0.074285
60,LV686,C2CP_WP_EICOSANOID_SYNTHESIS,0.811975,0.079608
61,LV721,C2CP_REACTOME_CGMP_EFFECTS,1.000000,0.019885
62,LV721,C2CP_WP_MATRIX_METALLOPROTEINASES,0.896319,0.037607
63,LV721,C2CP_REACTOME_NITRIC_OXIDE_STIMULATES_GUANYLATE_CYCLASE,0.874802,0.052654
64,LV721,C2CP_REACTOME_ACTIVATION_OF_MATRIX_METALLOPROTEINASES,0.835106,0.052747
65,LV721,C2CP_KEGG_MEDICUS_PATHOGEN_EBV_EBNA3C_TO_P53_MEDIATED_TRANSCRIPTION,1.000000,0.059629
66,LV808,C2CP_REACTOME_INTERLEUKIN_20_FAMILY_SIGNALING,0.922986,0.052773
67,LV808,C2CP_BIOCARTA_IL10_PATHWAY,0.999946,0.057282
68,LV86,C2CP_REACTOME_CELL_EXTRACELLULAR_MATRIX_INTERACTIONS,0.989144,0.016422
69,LV86,C2CP_REACTOME_NCAM1_INTERACTIONS,0.817495,0.030307
70,LV888,C2CP_WP_PATHOPHYSIOLOGICAL_ROLES_OF_DUX4_IN_FSHD1,0.983912,0.056567
71,LV89,C2CP_REACTOME_MITOCHONDRIAL_MRNA_MODIFICATION,0.940351,0.084681
72,LV915,C2CP_WP_ULCERATIVE_COLITIS_SIGNALING,0.845826,0.093161
73,LV967,C2CP_WP_SIGNALING_LIPIDS,0.985629,0.004966
74,LV967,C2CP_REACTOME_BIOSYNTHESIS_OF_SPECIALIZED_PRORESOLVING_MEDIATORS_SPMS,0.994328,0.016156
75,LV967,C2CP_WP_OMEGA3FATTY_ACIDS_IN_SENESCENCE,0.845075,0.034066
76,LV967,C2CP_WP_LEUKOTRIENE_METABOLIC_PATHWAY,0.995801,0.056336

In [28]:
kidney_pathways = analyze("Kidney", "kidney")

────────────────────────────────────────────────────────────────
  Kidney  (keyword: 'kidney')  |  samples in model: 4,820
  Expected in top 1%: 48.2  |  Selected LVs: 23

,LV,n_in_top1pct,enrich_ratio,median_rank_pct,AUC,FDR
0,LV1458,141,2.925,0.4801,0.515349,7.476036e-04
1,LV1363,135,2.801,0.4818,0.520117,7.429937e-06
2,LV1235,135,2.801,0.4819,0.516869,2.055134e-04
3,LV1218,134,2.780,0.4825,0.514879,1.095508e-03
4,LV1516,122,2.531,0.4692,0.526813,1.445294e-09
5,LV112,122,2.531,0.4719,0.525565,8.571958e-09
6,LV1468,121,2.510,0.4860,0.509576,4.175956e-02
7,LV978,118,2.448,0.4662,0.524816,2.396947e-08
8,LV741,114,2.365,0.4565,0.527133,9.671337e-10
9,LV130,113,2.344,0.4845,0.509814,3.668733e-02
10,LV1723,112,2.324,0.4433,0.526933,1.241380e-09
11,LV51,111,2.303,0.4708,0.518364,4.654200e-05
12,LV29,111,2.303,0.5006,0.509478,4.423134e-02
13,LV35,108,2.241,0.4555,0.527360,7.026731e-10
14,LV18,107,2.220,0.4689,0.520129,7.367182e-06
15,LV1237,103,2.137,0.4677,0.522686,3.549496e-07
16,LV1431,100,2.075,0.4504,0.530676,4.338227e-12
17,LV704,100,2.075,0.4700,0.528327,1.753352e-10
18,LV1048,98,2.033,0.4689,0.527350,7.036016e-10
19,LV41,98,2.033,0.4653,0.519981,8.490449e-06
20,LV885,98,2.033,0.4891,0.511156,1.655809e-02
21,LV1321,98,2.033,0.4794,0.515239,8.199992e-04
22,LV1665,97,2.012,0.4646,0.523880,8.211489e-08

  Pathways:

,LV,pathway,AUC,FDR
0,LV1048,C2CP_REACTOME_APOPTOSIS_INDUCED_DNA_FRAGMENTATION,0.940064,7.291895e-02
1,LV1218,C2CP_REACTOME_BASE_EXCISION_REPAIR_AP_SITE_FORMATION,0.975499,1.336140e-06
2,LV1218,C2CP_REACTOME_RECOGNITION_AND_ASSOCIATION_OF_DNA_GLYCOSYLASE_WITH_SITE_CONTAINING_AN_AFFECTED_PURINE,0.972102,2.262292e-05
3,LV1218,C2CP_WP_TELOMERE_END_PACKAGING_AND_NEURODEVELOPMENTAL_DISORDERS,0.883677,2.164796e-03
4,LV1218,C2CP_REACTOME_REPLACEMENT_OF_PROTAMINES_BY_NUCLEOSOMES_IN_THE_MALE_PRONUCLEUS,0.914875,4.702992e-03
5,LV1218,C2CP_WP_TESSADORIBICKNELLVAN_HAAFTEN_SYNDROME_VARIANTS_NUCLEOSOME_ASSEMBLY,1.000000,1.977278e-02
6,LV1218,C2CP_REACTOME_DEPOSITION_OF_NEW_CENPA_CONTAINING_NUCLEOSOMES_AT_THE_CENTROMERE,0.721876,3.503176e-02
7,LV1218,C2CP_REACTOME_DNA_METHYLATION,0.701250,7.184344e-02
8,LV1218,C2CP_REACTOME_CONDENSATION_OF_PROPHASE_CHROMOSOMES,0.668963,9.986911e-02
9,LV1363,C2CP_REACTOME_EUKARYOTIC_TRANSLATION_ELONGATION,1.000000,8.684349e-12
10,LV1363,C2CP_REACTOME_NONSENSE_MEDIATED_DECAY_NMD,0.943448,1.424064e-11
11,LV1363,C2CP_KEGG_RIBOSOME,0.999607,1.553372e-11
12,LV1363,C2CP_WP_CYTOPLASMIC_RIBOSOMAL_PROTEINS,0.998249,1.559218e-11
13,LV1363,C2CP_KEGG_MEDICUS_REFERENCE_TRANSLATION_INITIATION,1.000000,4.043613e-11
14,LV1363,C2CP_REACTOME_SELENOAMINO_ACID_METABOLISM,0.914500,5.484201e-11
15,LV1363,C2CP_REACTOME_SRP_DEPENDENT_COTRANSLATIONAL_PROTEIN_TARGETING_TO_MEMBRANE,0.901789,5.503772e-10
16,LV1431,C2CP_WP_17Q12_COPY_NUMBER_VARIATION_SYNDROME,0.750526,1.126258e-02
17,LV1468,C2CP_REACTOME_DISEASES_ASSOCIATED_WITH_O_GLYCOSYLATION_OF_PROTEINS,0.761777,2.752038e-02
18,LV1665,C2CP_KEGG_MEDICUS_PATHOGEN_HIV_GP120_TO_CXCR4_GNAQ_PLCB_G_CALCINEURIN,0.889137,6.271650e-02
19,LV1665,C2CP_KEGG_MEDICUS_REFERENCE_EGF_EGFR_PLCG_CALCINEURIN_SIGNALING_PATHWAY,0.845203,9.579708e-02
20,LV18,C2CP_REACTOME_SCAVENGING_OF_HEME_FROM_PLASMA,0.829136,2.020740e-03
21,LV18,C2CP_REACTOME_CD22_MEDIATED_BCR_REGULATION,0.827051,4.138516e-03
22,LV18,C2CP_REACTOME_INITIAL_TRIGGERING_OF_COMPLEMENT,0.746484,2.100930e-02
23,LV18,C2CP_REACTOME_ANTIGEN_ACTIVATES_B_CELL_RECEPTOR_BCR_LEADING_TO_GENERATION_OF_SECOND_MESSENGERS,0.679781,5.993772e-02
24,LV29,C2CP_BIOCARTA_BLYMPHOCYTE_PATHWAY,0.997301,5.495029e-02
25,LV29,C2CP_REACTOME_GAP_JUNCTION_DEGRADATION,0.927804,8.583096e-02
26,LV35,C2CP_REACTOME_FORMATION_OF_ATP_BY_CHEMIOSMOTIC_COUPLING,0.829779,6.543205e-02
27,LV51,C2CP_REACTOME_ACETYLCHOLINE_REGULATES_INSULIN_SECRETION,0.922987,8.908425e-02

In [29]:
kidney_pathways

,LV,pathway,AUC,FDR
0,LV1048,C2CP_REACTOME_APOPTOSIS_INDUCED_DNA_FRAGMENTATION,0.940064,7.291895e-02
1,LV1218,C2CP_REACTOME_BASE_EXCISION_REPAIR_AP_SITE_FORMATION,0.975499,1.336140e-06
2,LV1218,C2CP_REACTOME_RECOGNITION_AND_ASSOCIATION_OF_DNA_GLYCOSYLASE_WITH_SITE_CONTAINING_AN_AFFECTED_PURINE,0.972102,2.262292e-05
3,LV1218,C2CP_WP_TELOMERE_END_PACKAGING_AND_NEURODEVELOPMENTAL_DISORDERS,0.883677,2.164796e-03
4,LV1218,C2CP_REACTOME_REPLACEMENT_OF_PROTAMINES_BY_NUCLEOSOMES_IN_THE_MALE_PRONUCLEUS,0.914875,4.702992e-03
5,LV1218,C2CP_WP_TESSADORIBICKNELLVAN_HAAFTEN_SYNDROME_VARIANTS_NUCLEOSOME_ASSEMBLY,1.000000,1.977278e-02
6,LV1218,C2CP_REACTOME_DEPOSITION_OF_NEW_CENPA_CONTAINING_NUCLEOSOMES_AT_THE_CENTROMERE,0.721876,3.503176e-02
7,LV1218,C2CP_REACTOME_DNA_METHYLATION,0.701250,7.184344e-02
8,LV1218,C2CP_REACTOME_CONDENSATION_OF_PROPHASE_CHROMOSOMES,0.668963,9.986911e-02
9,LV1363,C2CP_REACTOME_EUKARYOTIC_TRANSLATION_ELONGATION,1.000000,8.684349e-12
10,LV1363,C2CP_REACTOME_NONSENSE_MEDIATED_DECAY_NMD,0.943448,1.424064e-11
11,LV1363,C2CP_KEGG_RIBOSOME,0.999607,1.553372e-11
12,LV1363,C2CP_WP_CYTOPLASMIC_RIBOSOMAL_PROTEINS,0.998249,1.559218e-11
13,LV1363,C2CP_KEGG_MEDICUS_REFERENCE_TRANSLATION_INITIATION,1.000000,4.043613e-11
14,LV1363,C2CP_REACTOME_SELENOAMINO_ACID_METABOLISM,0.914500,5.484201e-11
15,LV1363,C2CP_REACTOME_SRP_DEPENDENT_COTRANSLATIONAL_PROTEIN_TARGETING_TO_MEMBRANE,0.901789,5.503772e-10
16,LV1431,C2CP_WP_17Q12_COPY_NUMBER_VARIATION_SYNDROME,0.750526,1.126258e-02
17,LV1468,C2CP_REACTOME_DISEASES_ASSOCIATED_WITH_O_GLYCOSYLATION_OF_PROTEINS,0.761777,2.752038e-02
18,LV1665,C2CP_KEGG_MEDICUS_PATHOGEN_HIV_GP120_TO_CXCR4_GNAQ_PLCB_G_CALCINEURIN,0.889137,6.271650e-02
19,LV1665,C2CP_KEGG_MEDICUS_REFERENCE_EGF_EGFR_PLCG_CALCINEURIN_SIGNALING_PATHWAY,0.845203,9.579708e-02
20,LV18,C2CP_REACTOME_SCAVENGING_OF_HEME_FROM_PLASMA,0.829136,2.020740e-03
21,LV18,C2CP_REACTOME_CD22_MEDIATED_BCR_REGULATION,0.827051,4.138516e-03
22,LV18,C2CP_REACTOME_INITIAL_TRIGGERING_OF_COMPLEMENT,0.746484,2.100930e-02
23,LV18,C2CP_REACTOME_ANTIGEN_ACTIVATES_B_CELL_RECEPTOR_BCR_LEADING_TO_GENERATION_OF_SECOND_MESSENGERS,0.679781,5.993772e-02
24,LV29,C2CP_BIOCARTA_BLYMPHOCYTE_PATHWAY,0.997301,5.495029e-02
25,LV29,C2CP_REACTOME_GAP_JUNCTION_DEGRADATION,0.927804,8.583096e-02
26,LV35,C2CP_REACTOME_FORMATION_OF_ATP_BY_CHEMIOSMOTIC_COUPLING,0.829779,6.543205e-02
27,LV51,C2CP_REACTOME_ACETYLCHOLINE_REGULATES_INSULIN_SECRETION,0.922987,8.908425e-02

In [30]:
liver_pathways = analyze("Liver", "liver")

────────────────────────────────────────────────────────────────
  Liver  (keyword: 'liver')  |  samples in model: 9,197
  Expected in top 1%: 92.0  |  Selected LVs: 18

,LV,n_in_top1pct,enrich_ratio,median_rank_pct,AUC,FDR
0,LV1434,763,8.296,0.4509,0.537629,1.005073e-33
1,LV303,744,8.090,0.4269,0.557874,1.067666e-78
2,LV15,738,8.025,0.4487,0.548030,3.106115e-54
3,LV19,720,7.829,0.4129,0.572685,5.892540e-124
4,LV298,442,4.806,0.4753,0.533055,2.222827e-26
5,LV1468,287,3.121,0.4883,0.507955,1.511532e-02
6,LV1420,285,3.099,0.4680,0.536547,6.544606e-32
7,LV13,227,2.468,0.4873,0.514297,7.058793e-06
8,LV1495,217,2.360,0.4470,0.534376,2.099654e-28
9,LV60,213,2.316,0.4916,0.517854,1.603373e-08
10,LV1076,199,2.164,0.4870,0.523151,1.702273e-13
11,LV336,197,2.142,0.4666,0.520416,9.241118e-11
12,LV1051,196,2.131,0.4878,0.517641,2.403782e-08
13,LV382,196,2.131,0.4479,0.538405,4.177575e-35
14,LV297,196,2.131,0.4809,0.510952,7.054511e-04
15,LV173,193,2.099,0.4199,0.561752,1.687954e-89
16,LV441,192,2.088,0.4770,0.509096,5.225274e-03
17,LV633,189,2.055,0.4712,0.531257,1.137284e-23

  Pathways:

,LV,pathway,AUC,FDR
0,LV1420,C2CP_REACTOME_MEIOTIC_RECOMBINATION,0.833417,9.408245e-05
1,LV1420,C2CP_REACTOME_INHIBITION_OF_DNA_RECOMBINATION_AT_TELOMERE,0.870496,1.057661e-04
2,LV1420,C2CP_REACTOME_TRANSCRIPTIONAL_REGULATION_BY_SMALL_RNAS,0.812408,5.318460e-04
3,LV1420,C2CP_REACTOME_DNA_METHYLATION,0.840944,8.864573e-04
4,LV1420,C2CP_REACTOME_RECOGNITION_AND_ASSOCIATION_OF_DNA_GLYCOSYLASE_WITH_SITE_CONTAINING_AN_AFFECTED_PURINE,0.849927,2.513417e-03
5,LV1420,C2CP_REACTOME_ACTIVATED_PKN1_STIMULATES_TRANSCRIPTION_OF_AR_ANDROGEN_RECEPTOR_REGULATED_GENES_KLK2_AND_KLK3,0.805951,3.771898e-03
6,LV1420,C2CP_REACTOME_SIRT1_NEGATIVELY_REGULATES_RRNA_EXPRESSION,0.760770,1.214457e-02
7,LV1434,C2CP_REACTOME_ASSEMBLY_OF_THE_ORC_COMPLEX_AT_THE_ORIGIN_OF_REPLICATION,0.967495,4.026426e-07
8,LV1434,C2CP_REACTOME_BASE_EXCISION_REPAIR,0.843248,3.386783e-05
9,LV1434,C2CP_WP_TELOMERE_END_PACKAGING_AND_NEURODEVELOPMENTAL_DISORDERS,0.981626,3.918928e-05
10,LV1434,C2CP_REACTOME_BASE_EXCISION_REPAIR_AP_SITE_FORMATION,0.888455,1.159089e-04
11,LV1434,C2CP_REACTOME_RECOGNITION_AND_ASSOCIATION_OF_DNA_GLYCOSYLASE_WITH_SITE_CONTAINING_AN_AFFECTED_PURINE,0.911919,2.518206e-04
12,LV1434,C2CP_REACTOME_DNA_METHYLATION,0.844461,8.800311e-04
13,LV1434,C2CP_REACTOME_ACTIVATED_PKN1_STIMULATES_TRANSCRIPTION_OF_AR_ANDROGEN_RECEPTOR_REGULATED_GENES_KLK2_AND_KLK3,0.816557,2.860619e-03
14,LV1434,C2CP_REACTOME_REPLACEMENT_OF_PROTAMINES_BY_NUCLEOSOMES_IN_THE_MALE_PRONUCLEUS,0.915474,4.068586e-03
15,LV1468,C2CP_REACTOME_DISEASES_ASSOCIATED_WITH_O_GLYCOSYLATION_OF_PROTEINS,0.761777,2.752038e-02
16,LV15,C2CP_WP_CHOLESTEROL_SYNTHESIS_DISORDERS,0.899240,5.633647e-02
17,LV15,C2CP_KEGG_STEROID_BIOSYNTHESIS,0.893015,5.766489e-02
18,LV173,C2CP_WP_DOPAMINE_METABOLISM,0.984512,5.318305e-02
19,LV173,C2CP_REACTOME_ATF6_ATF6_ALPHA_ACTIVATES_CHAPERONE_GENES,0.957662,5.973986e-02
20,LV19,C2CP_KEGG_MEDICUS_VARIANT_MUTATION_CAUSED_ABERRANT_ABETA_TO_TRANSPORT_OF_CALCIUM,0.990792,5.495029e-02
21,LV19,C2CP_BIOCARTA_HSP27_PATHWAY,0.957938,6.393137e-02
22,LV19,C2CP_KEGG_MEDICUS_REFERENCE_INTRINSIC_APOPTOTIC_PATHWAY,0.929198,8.072884e-02
23,LV19,C2CP_REACTOME_P38MAPK_EVENTS,0.927373,8.164208e-02
24,LV297,C2CP_REACTOME_RRNA_PROCESSING_IN_THE_MITOCHONDRION,0.860338,8.125798e-02
25,LV298,C2CP_WP_CORI_CYCLE,0.999344,5.277268e-02
26,LV298,C2CP_WP_GLYCOLYSIS_IN_SENESCENCE,0.968724,6.017376e-02
27,LV303,C2CP_BIOCARTA_HIF_PATHWAY,0.979321,5.481384e-02
28,LV303,C2CP_WP_NAD_METABOLISM_SIRTUINS_AND_AGING,0.902207,9.211364e-02
29,LV382,C2CP_WP_GENES_CONTROLLING_NEPHROGENESIS,0.816152,1.662352e-02
30,LV382,C2CP_REACTOME_KIDNEY_DEVELOPMENT,0.740822,8.781485e-02
31,LV441,C2CP_REACTOME_MET_ACTIVATES_PTK2_SIGNALING,0.904670,5.354576e-03
32,LV441,C2CP_KEGG_ECM_RECEPTOR_INTERACTION,0.719864,2.065730e-02
33,LV60,C2CP_KEGG_MEDICUS_REFERENCE_REGULATION_OF_GF_RTK_RAS_ERK_SIGNALING_UBIQUITINATION_OF_RTK_BY_CBL,0.962128,3.628320e-04
34,LV60,C2CP_KEGG_MEDICUS_VARIANT_MUTATION_CAUSED_ABERRANT_ABETA_TO_CROSSTALK_BETWEEN_EXTRINSIC_AND_INTRINSIC_APOPTOTIC_PATHWAYS,0.979768,3.406581e-02
35,LV60,C2CP_REACTOME_REGULATION_OF_GENE_EXPRESSION_IN_BETA_CELLS,0.965168,4.206842e-02
36,LV60,C2CP_WP_TRANSCRIPTION_FACTOR_REGULATION_IN_ADIPOGENESIS,0.809622,5.586174e-02
37,LV633,C2CP_WP_SRF_AND_MIRS_IN_SMOOTH_MUSCLE_DIFFERENTIATION_AND_PROLIFERATION,0.930328,9.004953e-02

In [31]:
liver_pathways

,LV,pathway,AUC,FDR
0,LV1420,C2CP_REACTOME_MEIOTIC_RECOMBINATION,0.833417,9.408245e-05
1,LV1420,C2CP_REACTOME_INHIBITION_OF_DNA_RECOMBINATION_AT_TELOMERE,0.870496,1.057661e-04
2,LV1420,C2CP_REACTOME_TRANSCRIPTIONAL_REGULATION_BY_SMALL_RNAS,0.812408,5.318460e-04
3,LV1420,C2CP_REACTOME_DNA_METHYLATION,0.840944,8.864573e-04
4,LV1420,C2CP_REACTOME_RECOGNITION_AND_ASSOCIATION_OF_DNA_GLYCOSYLASE_WITH_SITE_CONTAINING_AN_AFFECTED_PURINE,0.849927,2.513417e-03
5,LV1420,C2CP_REACTOME_ACTIVATED_PKN1_STIMULATES_TRANSCRIPTION_OF_AR_ANDROGEN_RECEPTOR_REGULATED_GENES_KLK2_AND_KLK3,0.805951,3.771898e-03
6,LV1420,C2CP_REACTOME_SIRT1_NEGATIVELY_REGULATES_RRNA_EXPRESSION,0.760770,1.214457e-02
7,LV1434,C2CP_REACTOME_ASSEMBLY_OF_THE_ORC_COMPLEX_AT_THE_ORIGIN_OF_REPLICATION,0.967495,4.026426e-07
8,LV1434,C2CP_REACTOME_BASE_EXCISION_REPAIR,0.843248,3.386783e-05
9,LV1434,C2CP_WP_TELOMERE_END_PACKAGING_AND_NEURODEVELOPMENTAL_DISORDERS,0.981626,3.918928e-05
10,LV1434,C2CP_REACTOME_BASE_EXCISION_REPAIR_AP_SITE_FORMATION,0.888455,1.159089e-04
11,LV1434,C2CP_REACTOME_RECOGNITION_AND_ASSOCIATION_OF_DNA_GLYCOSYLASE_WITH_SITE_CONTAINING_AN_AFFECTED_PURINE,0.911919,2.518206e-04
12,LV1434,C2CP_REACTOME_DNA_METHYLATION,0.844461,8.800311e-04
13,LV1434,C2CP_REACTOME_ACTIVATED_PKN1_STIMULATES_TRANSCRIPTION_OF_AR_ANDROGEN_RECEPTOR_REGULATED_GENES_KLK2_AND_KLK3,0.816557,2.860619e-03
14,LV1434,C2CP_REACTOME_REPLACEMENT_OF_PROTAMINES_BY_NUCLEOSOMES_IN_THE_MALE_PRONUCLEUS,0.915474,4.068586e-03
15,LV1468,C2CP_REACTOME_DISEASES_ASSOCIATED_WITH_O_GLYCOSYLATION_OF_PROTEINS,0.761777,2.752038e-02
16,LV15,C2CP_WP_CHOLESTEROL_SYNTHESIS_DISORDERS,0.899240,5.633647e-02
17,LV15,C2CP_KEGG_STEROID_BIOSYNTHESIS,0.893015,5.766489e-02
18,LV173,C2CP_WP_DOPAMINE_METABOLISM,0.984512,5.318305e-02
19,LV173,C2CP_REACTOME_ATF6_ATF6_ALPHA_ACTIVATES_CHAPERONE_GENES,0.957662,5.973986e-02
20,LV19,C2CP_KEGG_MEDICUS_VARIANT_MUTATION_CAUSED_ABERRANT_ABETA_TO_TRANSPORT_OF_CALCIUM,0.990792,5.495029e-02
21,LV19,C2CP_BIOCARTA_HSP27_PATHWAY,0.957938,6.393137e-02
22,LV19,C2CP_KEGG_MEDICUS_REFERENCE_INTRINSIC_APOPTOTIC_PATHWAY,0.929198,8.072884e-02
23,LV19,C2CP_REACTOME_P38MAPK_EVENTS,0.927373,8.164208e-02
24,LV297,C2CP_REACTOME_RRNA_PROCESSING_IN_THE_MITOCHONDRION,0.860338,8.125798e-02
25,LV298,C2CP_WP_CORI_CYCLE,0.999344,5.277268e-02
26,LV298,C2CP_WP_GLYCOLYSIS_IN_SENESCENCE,0.968724,6.017376e-02
27,LV303,C2CP_BIOCARTA_HIF_PATHWAY,0.979321,5.481384e-02
28,LV303,C2CP_WP_NAD_METABOLISM_SIRTUINS_AND_AGING,0.902207,9.211364e-02
29,LV382,C2CP_WP_GENES_CONTROLLING_NEPHROGENESIS,0.816152,1.662352e-02
30,LV382,C2CP_REACTOME_KIDNEY_DEVELOPMENT,0.740822,8.781485e-02
31,LV441,C2CP_REACTOME_MET_ACTIVATES_PTK2_SIGNALING,0.904670,5.354576e-03
32,LV441,C2CP_KEGG_ECM_RECEPTOR_INTERACTION,0.719864,2.065730e-02
33,LV60,C2CP_KEGG_MEDICUS_REFERENCE_REGULATION_OF_GF_RTK_RAS_ERK_SIGNALING_UBIQUITINATION_OF_RTK_BY_CBL,0.962128,3.628320e-04
34,LV60,C2CP_KEGG_MEDICUS_VARIANT_MUTATION_CAUSED_ABERRANT_ABETA_TO_CROSSTALK_BETWEEN_EXTRINSIC_AND_INTRINSIC_APOPTOTIC_PATHWAYS,0.979768,3.406581e-02
35,LV60,C2CP_REACTOME_REGULATION_OF_GENE_EXPRESSION_IN_BETA_CELLS,0.965168,4.206842e-02
36,LV60,C2CP_WP_TRANSCRIPTION_FACTOR_REGULATION_IN_ADIPOGENESIS,0.809622,5.586174e-02
37,LV633,C2CP_WP_SRF_AND_MIRS_IN_SMOOTH_MUSCLE_DIFFERENTIATION_AND_PROLIFERATION,0.930328,9.004953e-02

In [32]:
lung_pathways = analyze("Lung", "lung")

────────────────────────────────────────────────────────────────
  Lung  (keyword: 'lung')  |  samples in model: 12,053
  Expected in top 1%: 120.5  |  Selected LVs: 3

       LV  n_in_top1pct  enrich_ratio  median_rank_pct       AUC           FDR
0  LV1373           307         2.547           0.4828  0.506985  1.549307e-02
1   LV186           265         2.199           0.4888  0.510744  1.501030e-04
2   LV222           248         2.058           0.4763  0.517431  4.955622e-10

  Pathways:

       LV                                          pathway       AUC       FDR
0  LV1373  C2CP_REACTOME_DEFECTIVE_EXT2_CAUSES_EXOSTOSES_2  0.942138  0.079588

In [33]:
lung_pathways

       LV                                          pathway       AUC       FDR
0  LV1373  C2CP_REACTOME_DEFECTIVE_EXT2_CAUSES_EXOSTOSES_2  0.942138  0.079588

In [34]:
muscle_pathways = analyze("Muscle", "muscle")

────────────────────────────────────────────────────────────────
  Muscle  (keyword: 'muscle')  |  samples in model: 4,572
  Expected in top 1%: 45.7  |  Selected LVs: 34

,LV,n_in_top1pct,enrich_ratio,median_rank_pct,AUC,FDR
0,LV147,216,4.725,0.4600,0.531013,6.850254e-12
1,LV732,212,4.637,0.4566,0.526167,8.835424e-09
2,LV1188,161,3.522,0.4760,0.515595,7.577196e-04
3,LV94,145,3.172,0.4793,0.517178,1.963966e-04
4,LV1145,143,3.128,0.4457,0.525753,1.489558e-08
5,LV418,143,3.128,0.4631,0.522528,7.918254e-07
6,LV1103,139,3.040,0.4650,0.528239,5.084648e-10
7,LV13,128,2.800,0.4447,0.534494,1.676039e-14
8,LV1674,128,2.800,0.4680,0.519455,2.317620e-05
9,LV1388,112,2.450,0.4689,0.524940,4.141597e-08
10,LV257,110,2.406,0.4587,0.518322,7.044856e-05
11,LV1658,109,2.384,0.4773,0.513814,3.006043e-03
12,LV1362,109,2.384,0.4503,0.535943,1.484766e-15
13,LV1412,108,2.362,0.4875,0.511669,1.344113e-02
14,LV221,107,2.340,0.4741,0.516758,2.833350e-04
15,LV351,102,2.231,0.4655,0.523348,3.053130e-07
16,LV1227,101,2.209,0.4938,0.512597,7.212050e-03
17,LV370,101,2.209,0.4912,0.523710,2.004720e-07
18,LV47,101,2.209,0.4372,0.549776,7.481133e-29
19,LV1296,100,2.187,0.4401,0.531979,1.361055e-12
20,LV1571,100,2.187,0.4959,0.510355,2.952231e-02
21,LV374,99,2.165,0.4874,0.510445,2.815477e-02
22,LV310,97,2.122,0.4467,0.535021,7.286535e-15
23,LV82,96,2.100,0.4817,0.511917,1.145657e-02
24,LV959,96,2.100,0.4632,0.531108,5.917976e-12
25,LV744,95,2.078,0.4569,0.525435,2.224113e-08
26,LV1300,95,2.078,0.4481,0.536346,7.412647e-16
27,LV1662,94,2.056,0.4617,0.520049,1.260648e-05
28,LV484,94,2.056,0.4575,0.518505,5.860570e-05
29,LV828,93,2.034,0.4524,0.534651,1.302604e-14
30,LV737,93,2.034,0.4804,0.516497,3.549764e-04
31,LV1241,92,2.012,0.4830,0.526371,6.779905e-09
32,LV1525,92,2.012,0.4636,0.519604,1.981143e-05
33,LV99,92,2.012,0.4626,0.522621,7.120201e-07

  Pathways:

,LV,pathway,AUC,FDR
0,LV1103,C2CP_REACTOME_ANTIGEN_PROCESSING_UB_ATP_INDEPENDENT_PROTEASOMAL_DEGRADATION,0.871444,0.065641
1,LV1145,C2CP_KEGG_MEDICUS_REFERENCE_MDM2_P21_CELL_CYCLE_G1_S_N00536,0.965898,0.070395
2,LV1227,C2CP_WP_TRANSCRIPTIONAL_CASCADE_REGULATING_ADIPOGENESIS,0.984989,0.057418
3,LV1227,C2CP_WP_NAD_METABOLISM_SIRTUINS_AND_AGING,0.952929,0.070179
4,LV1300,C2CP_WP_STATIN_INHIBITION_OF_CHOLESTEROL_PRODUCTION,0.935820,0.017507
5,LV1300,C2CP_WP_FAMILIAL_HYPERLIPIDEMIA_TYPE_3,1.000000,0.058237
6,LV1300,C2CP_WP_FAMILIAL_HYPERLIPIDEMIA_TYPE_5,1.000000,0.058237
7,LV1412,C2CP_REACTOME_FIBRONECTIN_MATRIX_FORMATION,0.924274,0.016461
8,LV1412,C2CP_REACTOME_ATTACHMENT_OF_BACTERIA_TO_EPITHELIAL_CELLS,0.795323,0.094570
9,LV147,C2CP_REACTOME_SIRT1_NEGATIVELY_REGULATES_RRNA_EXPRESSION,0.673349,0.074990
10,LV351,C2CP_REACTOME_SIGNALING_BY_KIT_IN_DISEASE,0.812643,0.076099
11,LV370,C2CP_PID_S1P_META_PATHWAY,0.836569,0.060174
12,LV374,C2CP_WP_DENGUE2_INTERACTIONS_WITH_COMPLEMENT_AND_COAGULATION_CASCADES,0.979372,0.000007
13,LV374,C2CP_KEGG_COMPLEMENT_AND_COAGULATION_CASCADES,0.903684,0.000094
14,LV374,C2CP_WP_COMPLEMENT_AND_COAGULATION_CASCADES,0.828051,0.004614
15,LV374,C2CP_REACTOME_COMMON_PATHWAY_OF_FIBRIN_CLOT_FORMATION,0.999800,0.015603
16,LV47,C2CP_REACTOME_FORMATION_OF_THE_NEPHRIC_DUCT,0.979670,0.020589
17,LV484,C2CP_SA_REG_CASCADE_OF_CYCLIN_EXPR,0.985842,0.054814
18,LV94,C2CP_KEGG_MEDICUS_REFERENCE_TCR_PLCG_ITPR_SIGNALING_PATHWAY,0.971610,0.020010
19,LV94,C2CP_BIOCARTA_THELPER_PATHWAY,0.995888,0.054850
20,LV94,C2CP_BIOCARTA_TCYTOTOXIC_PATHWAY,0.990633,0.055862
21,LV94,C2CP_WP_REGULATION_OF_CYTOTOXIC_T_CELL_RESPONSES_BY_MALAT1_MIR1516_CIRCUIT,0.962533,0.063632
22,LV94,C2CP_BIOCARTA_TCRA_PATHWAY,0.940778,0.075258
23,LV959,C2CP_REACTOME_METABOLISM_OF_FAT_SOLUBLE_VITAMINS,0.877860,0.004569
24,LV99,C2CP_WP_GLYCOLYSIS_AND_GLUCONEOGENESIS,0.777899,0.043380
25,LV99,C2CP_WP_CORI_CYCLE,0.991210,0.055907
26,LV99,C2CP_WP_AEROBIC_GLYCOLYSIS_AUGMENTED,0.987606,0.056403
27,LV99,C2CP_PID_RHODOPSIN_PATHWAY,0.981519,0.057616
28,LV99,C2CP_BIOCARTA_PDZS_PATHWAY,0.839849,0.093431

In [35]:
muscle_pathways

,LV,pathway,AUC,FDR
0,LV1103,C2CP_REACTOME_ANTIGEN_PROCESSING_UB_ATP_INDEPENDENT_PROTEASOMAL_DEGRADATION,0.871444,0.065641
1,LV1145,C2CP_KEGG_MEDICUS_REFERENCE_MDM2_P21_CELL_CYCLE_G1_S_N00536,0.965898,0.070395
2,LV1227,C2CP_WP_TRANSCRIPTIONAL_CASCADE_REGULATING_ADIPOGENESIS,0.984989,0.057418
3,LV1227,C2CP_WP_NAD_METABOLISM_SIRTUINS_AND_AGING,0.952929,0.070179
4,LV1300,C2CP_WP_STATIN_INHIBITION_OF_CHOLESTEROL_PRODUCTION,0.935820,0.017507
5,LV1300,C2CP_WP_FAMILIAL_HYPERLIPIDEMIA_TYPE_3,1.000000,0.058237
6,LV1300,C2CP_WP_FAMILIAL_HYPERLIPIDEMIA_TYPE_5,1.000000,0.058237
7,LV1412,C2CP_REACTOME_FIBRONECTIN_MATRIX_FORMATION,0.924274,0.016461
8,LV1412,C2CP_REACTOME_ATTACHMENT_OF_BACTERIA_TO_EPITHELIAL_CELLS,0.795323,0.094570
9,LV147,C2CP_REACTOME_SIRT1_NEGATIVELY_REGULATES_RRNA_EXPRESSION,0.673349,0.074990
10,LV351,C2CP_REACTOME_SIGNALING_BY_KIT_IN_DISEASE,0.812643,0.076099
11,LV370,C2CP_PID_S1P_META_PATHWAY,0.836569,0.060174
12,LV374,C2CP_WP_DENGUE2_INTERACTIONS_WITH_COMPLEMENT_AND_COAGULATION_CASCADES,0.979372,0.000007
13,LV374,C2CP_KEGG_COMPLEMENT_AND_COAGULATION_CASCADES,0.903684,0.000094
14,LV374,C2CP_WP_COMPLEMENT_AND_COAGULATION_CASCADES,0.828051,0.004614
15,LV374,C2CP_REACTOME_COMMON_PATHWAY_OF_FIBRIN_CLOT_FORMATION,0.999800,0.015603
16,LV47,C2CP_REACTOME_FORMATION_OF_THE_NEPHRIC_DUCT,0.979670,0.020589
17,LV484,C2CP_SA_REG_CASCADE_OF_CYCLIN_EXPR,0.985842,0.054814
18,LV94,C2CP_KEGG_MEDICUS_REFERENCE_TCR_PLCG_ITPR_SIGNALING_PATHWAY,0.971610,0.020010
19,LV94,C2CP_BIOCARTA_THELPER_PATHWAY,0.995888,0.054850
20,LV94,C2CP_BIOCARTA_TCYTOTOXIC_PATHWAY,0.990633,0.055862
21,LV94,C2CP_WP_REGULATION_OF_CYTOTOXIC_T_CELL_RESPONSES_BY_MALAT1_MIR1516_CIRCUIT,0.962533,0.063632
22,LV94,C2CP_BIOCARTA_TCRA_PATHWAY,0.940778,0.075258
23,LV959,C2CP_REACTOME_METABOLISM_OF_FAT_SOLUBLE_VITAMINS,0.877860,0.004569
24,LV99,C2CP_WP_GLYCOLYSIS_AND_GLUCONEOGENESIS,0.777899,0.043380
25,LV99,C2CP_WP_CORI_CYCLE,0.991210,0.055907
26,LV99,C2CP_WP_AEROBIC_GLYCOLYSIS_AUGMENTED,0.987606,0.056403
27,LV99,C2CP_PID_RHODOPSIN_PATHWAY,0.981519,0.057616
28,LV99,C2CP_BIOCARTA_PDZS_PATHWAY,0.839849,0.093431

In [36]:
nerve_pathways = analyze("Nerve", "nerve")

────────────────────────────────────────────────────────────────
  Nerve  (keyword: 'nerve')  |  samples in model: 143
  Expected in top 1%: 1.4  |  Selected LVs: 22

,LV,n_in_top1pct,enrich_ratio,median_rank_pct,AUC,FDR
0,LV132,50,34.966,0.1979,0.791178,3.687987e-31
1,LV509,44,30.770,0.1249,0.677494,1.673339e-12
2,LV512,43,30.071,0.3350,0.642430,1.694525e-08
3,LV1215,39,27.273,0.0840,0.688743,6.038280e-14
4,LV403,36,25.175,0.3691,0.619010,2.828425e-06
5,LV120,35,24.476,0.1532,0.707110,1.567605e-16
6,LV1528,31,21.679,0.1627,0.718195,3.740090e-18
7,LV1494,28,19.581,0.1355,0.678511,1.257412e-12
8,LV1063,28,19.581,0.3331,0.611247,1.273902e-05
9,LV78,28,19.581,0.4610,0.588809,5.509696e-04
10,LV415,27,18.882,0.2660,0.714820,1.144963e-17
11,LV279,26,18.182,0.3283,0.629760,3.027523e-07
12,LV1667,26,18.182,0.2294,0.715657,8.571332e-18
13,LV33,25,17.483,0.3132,0.671733,8.598380e-12
14,LV453,24,16.784,0.0806,0.636422,6.773030e-08
15,LV548,24,16.784,0.1824,0.712424,2.444300e-17
16,LV1109,24,16.784,0.4150,0.577379,2.719926e-03
17,LV1571,22,15.385,0.1292,0.685105,1.877929e-13
18,LV1260,22,15.385,0.4153,0.616271,4.906901e-06
19,LV1577,21,14.686,0.1462,0.753381,8.745923e-24
20,LV184,21,14.686,0.3511,0.642219,1.758162e-08
21,LV565,20,13.986,0.4341,0.603893,4.722143e-05

  Pathways:

,LV,pathway,AUC,FDR
0,LV1109,C2CP_REACTOME_TRYPTOPHAN_CATABOLISM,0.985284,0.057616
1,LV120,C2CP_WP_ULCERATIVE_COLITIS_SIGNALING,0.986072,0.018224
2,LV120,C2CP_WP_IL23_INHIBITORS_IN_INFLAMMATORY_BOWEL_DISEASE,0.994238,0.056403
3,LV1215,C2CP_KEGG_ALLOGRAFT_REJECTION,1.000000,0.000334
4,LV1215,C2CP_KEGG_GRAFT_VERSUS_HOST_DISEASE,0.972925,0.000809
5,LV1215,C2CP_KEGG_ASTHMA,0.985244,0.007149
6,LV1215,C2CP_REACTOME_CHEMOKINE_RECEPTORS_BIND_CHEMOKINES,0.843191,0.007149
7,LV1215,C2CP_BIOCARTA_ASBCELL_PATHWAY,1.000000,0.058991
8,LV1577,C2CP_REACTOME_SYNTHESIS_OF_GLYCOSYLPHOSPHATIDYLINOSITOL_GPI,0.887161,0.066373
9,LV1667,C2CP_BIOCARTA_PLATELETAPP_PATHWAY,0.964891,0.058957
10,LV403,C2CP_WP_REGULATION_OF_CYTOTOXIC_T_CELL_RESPONSES_BY_MALAT1_MIR1516_CIRCUIT,0.959524,0.068053
11,LV453,C2CP_WP_FAMILIAL_HYPERLIPIDEMIA_TYPE_3,1.000000,0.058800
12,LV453,C2CP_REACTOME_PLASMA_LIPOPROTEIN_ASSEMBLY,0.990441,0.061512
13,LV453,C2CP_REACTOME_GBP_MEDIATED_HOST_DEFENSE,0.945016,0.087318
14,LV509,C2CP_REACTOME_LGI_ADAM_INTERACTIONS,0.966324,0.062645
15,LV78,C2CP_BIOCARTA_TCYTOTOXIC_PATHWAY,0.973657,0.061150

In [37]:
nerve_pathways

,LV,pathway,AUC,FDR
0,LV1109,C2CP_REACTOME_TRYPTOPHAN_CATABOLISM,0.985284,0.057616
1,LV120,C2CP_WP_ULCERATIVE_COLITIS_SIGNALING,0.986072,0.018224
2,LV120,C2CP_WP_IL23_INHIBITORS_IN_INFLAMMATORY_BOWEL_DISEASE,0.994238,0.056403
3,LV1215,C2CP_KEGG_ALLOGRAFT_REJECTION,1.000000,0.000334
4,LV1215,C2CP_KEGG_GRAFT_VERSUS_HOST_DISEASE,0.972925,0.000809
5,LV1215,C2CP_KEGG_ASTHMA,0.985244,0.007149
6,LV1215,C2CP_REACTOME_CHEMOKINE_RECEPTORS_BIND_CHEMOKINES,0.843191,0.007149
7,LV1215,C2CP_BIOCARTA_ASBCELL_PATHWAY,1.000000,0.058991
8,LV1577,C2CP_REACTOME_SYNTHESIS_OF_GLYCOSYLPHOSPHATIDYLINOSITOL_GPI,0.887161,0.066373
9,LV1667,C2CP_BIOCARTA_PLATELETAPP_PATHWAY,0.964891,0.058957
10,LV403,C2CP_WP_REGULATION_OF_CYTOTOXIC_T_CELL_RESPONSES_BY_MALAT1_MIR1516_CIRCUIT,0.959524,0.068053
11,LV453,C2CP_WP_FAMILIAL_HYPERLIPIDEMIA_TYPE_3,1.000000,0.058800
12,LV453,C2CP_REACTOME_PLASMA_LIPOPROTEIN_ASSEMBLY,0.990441,0.061512
13,LV453,C2CP_REACTOME_GBP_MEDIATED_HOST_DEFENSE,0.945016,0.087318
14,LV509,C2CP_REACTOME_LGI_ADAM_INTERACTIONS,0.966324,0.062645
15,LV78,C2CP_BIOCARTA_TCYTOTOXIC_PATHWAY,0.973657,0.061150

In [38]:
ovary_pathways = analyze("Ovary", "ovary")

────────────────────────────────────────────────────────────────
  Ovary  (keyword: 'ovary')  |  samples in model: 594
  Expected in top 1%: 5.9  |  Selected LVs: 37

,LV,n_in_top1pct,enrich_ratio,median_rank_pct,AUC,FDR
0,LV1006,83,13.973,0.4299,0.564533,3.511730e-07
1,LV886,76,12.795,0.3343,0.614018,6.225218e-20
2,LV312,69,11.616,0.3117,0.623273,3.476261e-23
3,LV725,65,10.943,0.4321,0.571059,1.915344e-08
4,LV1522,64,10.775,0.4616,0.554288,2.017842e-05
5,LV575,52,8.754,0.4442,0.542616,9.158954e-04
6,LV937,52,8.754,0.3555,0.584975,1.467149e-11
7,LV712,50,8.418,0.4071,0.572039,1.228605e-08
8,LV1061,44,7.408,0.3832,0.579188,3.443122e-10
9,LV1428,42,7.071,0.3893,0.587954,2.846236e-12
10,LV164,41,6.903,0.2703,0.634860,4.530056e-27
11,LV1074,41,6.903,0.3003,0.621662,1.230718e-22
12,LV1469,36,6.061,0.4033,0.591375,3.859655e-13
13,LV374,35,5.892,0.4783,0.533317,1.054637e-02
14,LV759,34,5.724,0.4578,0.548064,1.711920e-04
15,LV1583,34,5.724,0.4269,0.546228,3.053743e-04
16,LV732,33,5.556,0.4151,0.580850,1.379409e-10
17,LV224,33,5.556,0.4466,0.543423,7.263772e-04
18,LV841,32,5.387,0.3791,0.593943,8.400748e-14
19,LV402,31,5.219,0.4878,0.536451,4.899459e-03
20,LV786,30,5.051,0.4269,0.559806,2.504433e-06
21,LV6,28,4.714,0.3785,0.542416,9.694001e-04
22,LV1051,27,4.546,0.4573,0.534412,8.144459e-03
23,LV659,26,4.377,0.3530,0.612258,2.136290e-19
24,LV74,25,4.209,0.4294,0.577748,6.827679e-10
25,LV1138,25,4.209,0.4201,0.563394,5.641317e-07
26,LV1674,25,4.209,0.4482,0.530853,1.811669e-02
27,LV25,24,4.040,0.4076,0.556528,8.834574e-06
28,LV1397,23,3.872,0.4179,0.571939,1.280242e-08
29,LV1538,23,3.872,0.3645,0.582776,5.121763e-11
30,LV1067,22,3.704,0.4005,0.564714,3.273743e-07
31,LV1148,22,3.704,0.4596,0.531950,1.432951e-02
32,LV677,22,3.704,0.4265,0.564244,3.901695e-07
33,LV392,22,3.704,0.4597,0.536117,5.353996e-03
34,LV1114,21,3.535,0.3916,0.565731,2.112295e-07
35,LV223,20,3.367,0.3571,0.594916,4.736771e-14
36,LV585,20,3.367,0.4164,0.549754,9.669654e-05

  Pathways:

,LV,pathway,AUC,FDR
0,LV1061,C2CP_KEGG_GLYCINE_SERINE_AND_THREONINE_METABOLISM,0.889486,0.015817
1,LV1061,C2CP_WP_DISORDERS_OF_FRUCTOSE_METABOLISM,1.000000,0.056403
2,LV1074,C2CP_WP_ANDROGEN_BIOSYNTHESIS,1.000000,0.058800
3,LV1114,C2CP_WP_STRIATED_MUSCLE_CONTRACTION_PATHWAY,0.971312,0.000906
4,LV1114,C2CP_REACTOME_STRIATED_MUSCLE_CONTRACTION,0.986739,0.002108
5,LV1138,C2CP_KEGG_STEROID_BIOSYNTHESIS,0.964529,0.023092
6,LV1148,C2CP_REACTOME_PRC2_METHYLATES_HISTONES_AND_DNA,0.902929,0.000007
7,LV1148,C2CP_REACTOME_DEFECTIVE_PYROPTOSIS,0.893290,0.000014
8,LV1148,C2CP_REACTOME_RECOGNITION_AND_ASSOCIATION_OF_DNA_GLYCOSYLASE_WITH_SITE_CONTAINING_AN_AFFECTED_PURINE,0.952526,0.000036
9,LV1148,C2CP_REACTOME_REGULATION_OF_ENDOGENOUS_RETROELEMENTS_BY_THE_HUMAN_SILENCING_HUB_HUSH_COMPLEX,0.841785,0.000438
10,LV1148,C2CP_REACTOME_DNA_METHYLATION,0.849236,0.000633
11,LV1148,C2CP_REACTOME_REPLACEMENT_OF_PROTAMINES_BY_NUCLEOSOMES_IN_THE_MALE_PRONUCLEUS,0.919283,0.003329
12,LV1148,C2CP_REACTOME_RUNX1_REGULATES_GENES_INVOLVED_IN_MEGAKARYOCYTE_DIFFERENTIATION_AND_PLATELET_FUNCTION,0.672023,0.057001
13,LV1148,C2CP_WP_TELOMERE_END_PACKAGING_AND_NEURODEVELOPMENTAL_DISORDERS,0.731058,0.071943
14,LV1469,C2CP_KEGG_MEDICUS_REFERENCE_BETA_OXIDATION,1.000000,0.055862
15,LV25,C2CP_KEGG_MEDICUS_PATHOGEN_SALMONELLA_SOPE_TO_RAC_SIGNALING_PATHWAY,0.968730,0.008272
16,LV25,C2CP_BIOCARTA_AGPCR_PATHWAY,0.947582,0.079608
17,LV25,C2CP_KEGG_MEDICUS_PATHOGEN_SHIGELLA_IPAC_TO_ACTIN_SIGNALING_PATHWAY,0.925207,0.095436
18,LV312,C2CP_BIOCARTA_COMP_PATHWAY,1.000000,0.017065
19,LV374,C2CP_WP_DENGUE2_INTERACTIONS_WITH_COMPLEMENT_AND_COAGULATION_CASCADES,0.979372,0.000007
20,LV374,C2CP_KEGG_COMPLEMENT_AND_COAGULATION_CASCADES,0.903684,0.000094
21,LV374,C2CP_WP_COMPLEMENT_AND_COAGULATION_CASCADES,0.828051,0.004614
22,LV374,C2CP_REACTOME_COMMON_PATHWAY_OF_FIBRIN_CLOT_FORMATION,0.999800,0.015603
23,LV392,C2CP_REACTOME_INTERLEUKIN_2_SIGNALING,0.999347,0.051412
24,LV392,C2CP_KEGG_MEDICUS_REFERENCE_IL2_FAMILY_TO_JAK_STAT_SIGNALING_PATHWAY,0.844418,0.086740
25,LV402,C2CP_REACTOME_GLYOXYLATE_METABOLISM_AND_GLYCINE_DEGRADATION,0.973050,0.063788
26,LV575,C2CP_KEGG_COMPLEMENT_AND_COAGULATION_CASCADES,0.978972,0.000003
27,LV575,C2CP_WP_COMPLEMENT_AND_COAGULATION_CASCADES,0.911140,0.000273
28,LV575,C2CP_WP_DENGUE2_INTERACTIONS_WITH_COMPLEMENT_AND_COAGULATION_CASCADES,0.911140,0.000273
29,LV6,C2CP_WP_MIRNA_TARGETS_IN_ECM_AND_MEMBRANE_RECEPTORS,0.839965,0.035939
30,LV6,C2CP_WP_TGFB_SMAD_SIGNALING,0.913604,0.097634
31,LV659,C2CP_WP_TYROBP_CAUSAL_NETWORK_IN_MICROGLIA,0.874035,0.000199
32,LV659,C2CP_WP_MICROGLIA_PATHOGEN_PHAGOCYTOSIS_PATHWAY,0.867959,0.002791
33,LV659,C2CP_REACTOME_FREE_FATTY_ACIDS_REGULATE_INSULIN_SECRETION,0.983479,0.061004
34,LV712,C2CP_REACTOME_RESPONSE_TO_METAL_IONS,1.000000,0.056869
35,LV712,C2CP_WP_ZINC_HOMEOSTASIS,0.780331,0.060174
36,LV725,C2CP_WP_MICROGLIA_PATHOGEN_PHAGOCYTOSIS_PATHWAY,0.944830,0.000110
37,LV725,C2CP_REACTOME_TRAFFICKING_AND_PROCESSING_OF_ENDOSOMAL_TLR,0.962588,0.066973
38,LV74,C2CP_WP_FATTY_ACID_BIOSYNTHESIS,0.972575,0.006316
39,LV74,C2CP_REACTOME_BIOTIN_TRANSPORT_AND_METABOLISM,0.975395,0.060438
40,LV786,C2CP_KEGG_MEDICUS_REFERENCE_COPI_VESICLE_FORMATION,0.982759,0.005432
41,LV786,C2CP_REACTOME_CYTOSOLIC_TRNA_AMINOACYLATION,0.917521,0.019970
42,LV786,C2CP_WP_NGLYCAN_BIOSYNTHESIS,0.743694,0.025372
43,LV786,C2CP_WP_PHOTODYNAMIC_THERAPYINDUCED_UNFOLDED_PROTEIN_RESPONSE,0.832668,0.045261
44,LV786,C2CP_KEGG_MEDICUS_REFERENCE_COPII_VESICLE_FORMATION,0.995340,0.056709
45,LV786,C2CP_WP_GLYCOSYLATION_AND_RELATED_CONGENITAL_DEFECTS,0.783307,0.076727
46,LV937,C2CP_WP_TAMOXIFEN_METABOLISM,1.000000,0.054814

In [39]:
ovary_pathways

,LV,pathway,AUC,FDR
0,LV1061,C2CP_KEGG_GLYCINE_SERINE_AND_THREONINE_METABOLISM,0.889486,0.015817
1,LV1061,C2CP_WP_DISORDERS_OF_FRUCTOSE_METABOLISM,1.000000,0.056403
2,LV1074,C2CP_WP_ANDROGEN_BIOSYNTHESIS,1.000000,0.058800
3,LV1114,C2CP_WP_STRIATED_MUSCLE_CONTRACTION_PATHWAY,0.971312,0.000906
4,LV1114,C2CP_REACTOME_STRIATED_MUSCLE_CONTRACTION,0.986739,0.002108
5,LV1138,C2CP_KEGG_STEROID_BIOSYNTHESIS,0.964529,0.023092
6,LV1148,C2CP_REACTOME_PRC2_METHYLATES_HISTONES_AND_DNA,0.902929,0.000007
7,LV1148,C2CP_REACTOME_DEFECTIVE_PYROPTOSIS,0.893290,0.000014
8,LV1148,C2CP_REACTOME_RECOGNITION_AND_ASSOCIATION_OF_DNA_GLYCOSYLASE_WITH_SITE_CONTAINING_AN_AFFECTED_PURINE,0.952526,0.000036
9,LV1148,C2CP_REACTOME_REGULATION_OF_ENDOGENOUS_RETROELEMENTS_BY_THE_HUMAN_SILENCING_HUB_HUSH_COMPLEX,0.841785,0.000438
10,LV1148,C2CP_REACTOME_DNA_METHYLATION,0.849236,0.000633
11,LV1148,C2CP_REACTOME_REPLACEMENT_OF_PROTAMINES_BY_NUCLEOSOMES_IN_THE_MALE_PRONUCLEUS,0.919283,0.003329
12,LV1148,C2CP_REACTOME_RUNX1_REGULATES_GENES_INVOLVED_IN_MEGAKARYOCYTE_DIFFERENTIATION_AND_PLATELET_FUNCTION,0.672023,0.057001
13,LV1148,C2CP_WP_TELOMERE_END_PACKAGING_AND_NEURODEVELOPMENTAL_DISORDERS,0.731058,0.071943
14,LV1469,C2CP_KEGG_MEDICUS_REFERENCE_BETA_OXIDATION,1.000000,0.055862
15,LV25,C2CP_KEGG_MEDICUS_PATHOGEN_SALMONELLA_SOPE_TO_RAC_SIGNALING_PATHWAY,0.968730,0.008272
16,LV25,C2CP_BIOCARTA_AGPCR_PATHWAY,0.947582,0.079608
17,LV25,C2CP_KEGG_MEDICUS_PATHOGEN_SHIGELLA_IPAC_TO_ACTIN_SIGNALING_PATHWAY,0.925207,0.095436
18,LV312,C2CP_BIOCARTA_COMP_PATHWAY,1.000000,0.017065
19,LV374,C2CP_WP_DENGUE2_INTERACTIONS_WITH_COMPLEMENT_AND_COAGULATION_CASCADES,0.979372,0.000007
20,LV374,C2CP_KEGG_COMPLEMENT_AND_COAGULATION_CASCADES,0.903684,0.000094
21,LV374,C2CP_WP_COMPLEMENT_AND_COAGULATION_CASCADES,0.828051,0.004614
22,LV374,C2CP_REACTOME_COMMON_PATHWAY_OF_FIBRIN_CLOT_FORMATION,0.999800,0.015603
23,LV392,C2CP_REACTOME_INTERLEUKIN_2_SIGNALING,0.999347,0.051412
24,LV392,C2CP_KEGG_MEDICUS_REFERENCE_IL2_FAMILY_TO_JAK_STAT_SIGNALING_PATHWAY,0.844418,0.086740
25,LV402,C2CP_REACTOME_GLYOXYLATE_METABOLISM_AND_GLYCINE_DEGRADATION,0.973050,0.063788
26,LV575,C2CP_KEGG_COMPLEMENT_AND_COAGULATION_CASCADES,0.978972,0.000003
27,LV575,C2CP_WP_COMPLEMENT_AND_COAGULATION_CASCADES,0.911140,0.000273
28,LV575,C2CP_WP_DENGUE2_INTERACTIONS_WITH_COMPLEMENT_AND_COAGULATION_CASCADES,0.911140,0.000273
29,LV6,C2CP_WP_MIRNA_TARGETS_IN_ECM_AND_MEMBRANE_RECEPTORS,0.839965,0.035939
30,LV6,C2CP_WP_TGFB_SMAD_SIGNALING,0.913604,0.097634
31,LV659,C2CP_WP_TYROBP_CAUSAL_NETWORK_IN_MICROGLIA,0.874035,0.000199
32,LV659,C2CP_WP_MICROGLIA_PATHOGEN_PHAGOCYTOSIS_PATHWAY,0.867959,0.002791
33,LV659,C2CP_REACTOME_FREE_FATTY_ACIDS_REGULATE_INSULIN_SECRETION,0.983479,0.061004
34,LV712,C2CP_REACTOME_RESPONSE_TO_METAL_IONS,1.000000,0.056869
35,LV712,C2CP_WP_ZINC_HOMEOSTASIS,0.780331,0.060174
36,LV725,C2CP_WP_MICROGLIA_PATHOGEN_PHAGOCYTOSIS_PATHWAY,0.944830,0.000110
37,LV725,C2CP_REACTOME_TRAFFICKING_AND_PROCESSING_OF_ENDOSOMAL_TLR,0.962588,0.066973
38,LV74,C2CP_WP_FATTY_ACID_BIOSYNTHESIS,0.972575,0.006316
39,LV74,C2CP_REACTOME_BIOTIN_TRANSPORT_AND_METABOLISM,0.975395,0.060438
40,LV786,C2CP_KEGG_MEDICUS_REFERENCE_COPI_VESICLE_FORMATION,0.982759,0.005432
41,LV786,C2CP_REACTOME_CYTOSOLIC_TRNA_AMINOACYLATION,0.917521,0.019970
42,LV786,C2CP_WP_NGLYCAN_BIOSYNTHESIS,0.743694,0.025372
43,LV786,C2CP_WP_PHOTODYNAMIC_THERAPYINDUCED_UNFOLDED_PROTEIN_RESPONSE,0.832668,0.045261
44,LV786,C2CP_KEGG_MEDICUS_REFERENCE_COPII_VESICLE_FORMATION,0.995340,0.056709
45,LV786,C2CP_WP_GLYCOSYLATION_AND_RELATED_CONGENITAL_DEFECTS,0.783307,0.076727
46,LV937,C2CP_WP_TAMOXIFEN_METABOLISM,1.000000,0.054814

In [40]:
pancreas_pathways = analyze("Pancreas", "pancreas")

────────────────────────────────────────────────────────────────
  Pancreas  (keyword: 'pancreas')  |  samples in model: 1,324
  Expected in top 1%: 13.2  |  Selected LVs: 55

,LV,n_in_top1pct,enrich_ratio,median_rank_pct,AUC,FDR
0,LV1262,85,6.420,0.4598,0.528107,1.892101e-03
1,LV919,60,4.532,0.4853,0.527406,2.489906e-03
2,LV936,59,4.456,0.4470,0.551143,5.756161e-09
3,LV584,58,4.381,0.4428,0.552321,2.721787e-09
4,LV30,54,4.079,0.4878,0.520635,2.538278e-02
5,LV620,53,4.003,0.4487,0.528014,1.960784e-03
6,LV1535,51,3.852,0.4379,0.538598,1.380308e-05
7,LV1481,50,3.777,0.4874,0.520350,2.773402e-02
8,LV891,47,3.550,0.4933,0.519436,3.637251e-02
9,LV1699,47,3.550,0.4775,0.523311,1.075235e-02
10,LV497,46,3.474,0.4419,0.541075,3.455504e-06
11,LV1438,45,3.399,0.4523,0.527581,2.366478e-03
12,LV898,42,3.172,0.4618,0.526288,3.877325e-03
13,LV1083,41,3.097,0.4838,0.522244,1.545961e-02
14,LV730,41,3.097,0.4801,0.529655,9.965642e-04
15,LV276,39,2.946,0.4604,0.526448,3.642517e-03
16,LV562,38,2.870,0.4386,0.537216,2.706757e-05
17,LV941,38,2.870,0.4883,0.531598,4.405365e-04
18,LV1004,37,2.795,0.4601,0.537297,2.603612e-05
19,LV804,37,2.795,0.5087,0.519015,4.123568e-02
20,LV1319,36,2.719,0.4728,0.524258,7.797030e-03
21,LV412,34,2.568,0.4386,0.541475,2.938987e-06
22,LV1154,34,2.568,0.4758,0.520576,2.578127e-02
23,LV169,34,2.568,0.4557,0.546669,1.133966e-07
24,LV827,34,2.568,0.4269,0.543620,9.025736e-07
25,LV268,34,2.568,0.4619,0.533616,1.726967e-04
26,LV649,34,2.568,0.4322,0.548183,4.510993e-08
27,LV513,33,2.493,0.4556,0.530330,7.472927e-04
28,LV1282,33,2.493,0.4144,0.544091,6.799863e-07
29,LV1557,33,2.493,0.4427,0.550651,7.410213e-09
30,LV916,33,2.493,0.4850,0.519932,3.154257e-02
31,LV1724,33,2.493,0.4649,0.539792,7.210554e-06
32,LV895,32,2.417,0.4502,0.541800,2.447971e-06
33,LV132,32,2.417,0.4436,0.540373,5.339010e-06
34,LV1189,32,2.417,0.4919,0.521029,2.243738e-02
35,LV444,32,2.417,0.4372,0.542965,1.268160e-06
36,LV1452,32,2.417,0.4899,0.519921,3.157385e-02
37,LV141,31,2.341,0.4455,0.531920,3.853233e-04
38,LV1424,31,2.341,0.4387,0.539730,7.303464e-06
39,LV307,31,2.341,0.4828,0.521086,2.203913e-02
40,LV1706,31,2.341,0.4752,0.530873,6.043084e-04
41,LV484,30,2.266,0.4605,0.527426,2.479605e-03
42,LV811,30,2.266,0.4361,0.547809,5.592813e-08
43,LV309,30,2.266,0.4334,0.536249,4.514208e-05
44,LV800,29,2.190,0.4817,0.520722,2.474240e-02
45,LV1389,29,2.190,0.4863,0.521960,1.696248e-02
46,LV194,28,2.115,0.4892,0.533138,2.129872e-04
47,LV899,28,2.115,0.4511,0.523476,1.012939e-02
48,LV1401,28,2.115,0.4219,0.558111,4.389583e-11
49,LV727,28,2.115,0.4837,0.518577,4.653849e-02
50,LV1058,28,2.115,0.4418,0.542697,1.462232e-06
51,LV905,27,2.039,0.4185,0.546816,1.046884e-07
52,LV983,27,2.039,0.4799,0.519058,4.087495e-02
53,LV1400,27,2.039,0.4521,0.533949,1.504395e-04
54,LV1217,27,2.039,0.4481,0.552668,2.209785e-09

  Pathways:

,LV,pathway,AUC,FDR
0,LV1058,C2CP_REACTOME_RESPONSE_TO_METAL_IONS,0.998664,5.640270e-02
1,LV1058,C2CP_WP_ZINC_HOMEOSTASIS,0.769963,6.682021e-02
2,LV1189,C2CP_REACTOME_TP53_REGULATES_TRANSCRIPTION_OF_DEATH_RECEPTORS_AND_LIGANDS,0.972506,5.852795e-02
3,LV1282,C2CP_WP_1P36_COPY_NUMBER_VARIATION_SYNDROME,0.836119,6.926451e-06
4,LV1389,C2CP_KEGG_LYSOSOME,0.831486,2.778235e-07
5,LV1389,C2CP_REACTOME_REGULATION_OF_MITF_M_DEPENDENT_GENES_INVOLVED_IN_LYSOSOME_BIOGENESIS_AND_AUTOPHAGY,0.983702,1.822399e-02
6,LV1389,C2CP_WP_DEGRADATION_PATHWAY_OF_SPHINGOLIPIDS_INCLUDING_DISEASES,0.998904,5.568239e-02
7,LV1438,C2CP_REACTOME_CRMPS_IN_SEMA3A_SIGNALING,0.855342,8.864064e-02
8,LV1724,C2CP_KEGG_MEDICUS_REFERENCE_ANTEROGRADE_AXONAL_TRANSPORT,0.804480,8.868812e-02
9,LV194,C2CP_KEGG_P53_SIGNALING_PATHWAY,0.717945,2.972456e-02
10,LV194,C2CP_WP_MIRNA_REGULATION_OF_P53_PATHWAY_IN_PROSTATE_CANCER,0.762894,9.781409e-02
11,LV268,C2CP_WP_INTERFERONMEDIATED_SIGNALING,0.865648,7.289858e-02
12,LV30,C2CP_REACTOME_COLLAGEN_CHAIN_TRIMERIZATION,0.853627,6.856006e-03
13,LV30,C2CP_PID_INTEGRIN4_PATHWAY,0.947725,7.347583e-02
14,LV30,C2CP_REACTOME_DS_GAG_BIOSYNTHESIS,0.944775,7.561221e-02
15,LV307,C2CP_WP_TYPE_II_INTERFERON_SIGNALING,0.852473,1.329803e-02
16,LV307,C2CP_BIOCARTA_CLASSIC_PATHWAY,0.983400,5.686918e-02
17,LV309,C2CP_REACTOME_CASPASE_ACTIVATION_VIA_DEATH_RECEPTORS_IN_THE_PRESENCE_OF_LIGAND,0.999057,1.429074e-02
18,LV309,C2CP_WP_NANOMATERIAL_INDUCED_APOPTOSIS,0.858950,5.118256e-02
19,LV309,C2CP_REACTOME_REGULATION_BY_C_FLIP,0.999946,5.484971e-02
20,LV412,C2CP_PID_INTEGRIN_CS_PATHWAY,0.959186,3.227810e-03
21,LV412,C2CP_KEGG_MEDICUS_REFERENCE_ITGA_B_FAK_CDC42_SIGNALING_PATHWAY,0.824944,5.447253e-02
22,LV412,C2CP_KEGG_MEDICUS_REFERENCE_ITGA_B_RHOGEF_RHOA_SIGNALING_PATHWAY,0.805989,9.079167e-02
23,LV484,C2CP_SA_REG_CASCADE_OF_CYCLIN_EXPR,0.985842,5.481384e-02
24,LV497,C2CP_BIOCARTA_SM_PATHWAY,0.933180,7.504429e-02
25,LV497,C2CP_REACTOME_FOLDING_OF_ACTIN_BY_CCT_TRIC,0.918827,8.533668e-02
26,LV562,C2CP_KEGG_MEDICUS_VARIANT_AMPLIFIED_PDGFR_TO_PLCG_CAMK_SIGNALING_PATHWAY,0.999293,5.484971e-02
27,LV727,C2CP_KEGG_MEDICUS_VARIANT_MUTATION_CAUSED_ABERRANT_SNCA_TO_ELECTRON_TRANSFER_IN_COMPLEX_I,0.753577,3.940991e-02
28,LV727,C2CP_KEGG_VALINE_LEUCINE_AND_ISOLEUCINE_BIOSYNTHESIS,0.941699,8.125798e-02
29,LV804,C2CP_REACTOME_ENTEROBACTERIAL_FACTORS_ANTAGONIZE_HOST_DEFENSE,0.999946,5.590718e-02
30,LV898,C2CP_REACTOME_SPHINGOLIPID_CATABOLISM,0.989128,5.523544e-02
31,LV941,C2CP_WP_ASPIRIN_AND_MIRNAS,0.960292,6.043886e-02

In [41]:
pancreas_pathways

,LV,pathway,AUC,FDR
0,LV1058,C2CP_REACTOME_RESPONSE_TO_METAL_IONS,0.998664,5.640270e-02
1,LV1058,C2CP_WP_ZINC_HOMEOSTASIS,0.769963,6.682021e-02
2,LV1189,C2CP_REACTOME_TP53_REGULATES_TRANSCRIPTION_OF_DEATH_RECEPTORS_AND_LIGANDS,0.972506,5.852795e-02
3,LV1282,C2CP_WP_1P36_COPY_NUMBER_VARIATION_SYNDROME,0.836119,6.926451e-06
4,LV1389,C2CP_KEGG_LYSOSOME,0.831486,2.778235e-07
5,LV1389,C2CP_REACTOME_REGULATION_OF_MITF_M_DEPENDENT_GENES_INVOLVED_IN_LYSOSOME_BIOGENESIS_AND_AUTOPHAGY,0.983702,1.822399e-02
6,LV1389,C2CP_WP_DEGRADATION_PATHWAY_OF_SPHINGOLIPIDS_INCLUDING_DISEASES,0.998904,5.568239e-02
7,LV1438,C2CP_REACTOME_CRMPS_IN_SEMA3A_SIGNALING,0.855342,8.864064e-02
8,LV1724,C2CP_KEGG_MEDICUS_REFERENCE_ANTEROGRADE_AXONAL_TRANSPORT,0.804480,8.868812e-02
9,LV194,C2CP_KEGG_P53_SIGNALING_PATHWAY,0.717945,2.972456e-02
10,LV194,C2CP_WP_MIRNA_REGULATION_OF_P53_PATHWAY_IN_PROSTATE_CANCER,0.762894,9.781409e-02
11,LV268,C2CP_WP_INTERFERONMEDIATED_SIGNALING,0.865648,7.289858e-02
12,LV30,C2CP_REACTOME_COLLAGEN_CHAIN_TRIMERIZATION,0.853627,6.856006e-03
13,LV30,C2CP_PID_INTEGRIN4_PATHWAY,0.947725,7.347583e-02
14,LV30,C2CP_REACTOME_DS_GAG_BIOSYNTHESIS,0.944775,7.561221e-02
15,LV307,C2CP_WP_TYPE_II_INTERFERON_SIGNALING,0.852473,1.329803e-02
16,LV307,C2CP_BIOCARTA_CLASSIC_PATHWAY,0.983400,5.686918e-02
17,LV309,C2CP_REACTOME_CASPASE_ACTIVATION_VIA_DEATH_RECEPTORS_IN_THE_PRESENCE_OF_LIGAND,0.999057,1.429074e-02
18,LV309,C2CP_WP_NANOMATERIAL_INDUCED_APOPTOSIS,0.858950,5.118256e-02
19,LV309,C2CP_REACTOME_REGULATION_BY_C_FLIP,0.999946,5.484971e-02
20,LV412,C2CP_PID_INTEGRIN_CS_PATHWAY,0.959186,3.227810e-03
21,LV412,C2CP_KEGG_MEDICUS_REFERENCE_ITGA_B_FAK_CDC42_SIGNALING_PATHWAY,0.824944,5.447253e-02
22,LV412,C2CP_KEGG_MEDICUS_REFERENCE_ITGA_B_RHOGEF_RHOA_SIGNALING_PATHWAY,0.805989,9.079167e-02
23,LV484,C2CP_SA_REG_CASCADE_OF_CYCLIN_EXPR,0.985842,5.481384e-02
24,LV497,C2CP_BIOCARTA_SM_PATHWAY,0.933180,7.504429e-02
25,LV497,C2CP_REACTOME_FOLDING_OF_ACTIN_BY_CCT_TRIC,0.918827,8.533668e-02
26,LV562,C2CP_KEGG_MEDICUS_VARIANT_AMPLIFIED_PDGFR_TO_PLCG_CAMK_SIGNALING_PATHWAY,0.999293,5.484971e-02
27,LV727,C2CP_KEGG_MEDICUS_VARIANT_MUTATION_CAUSED_ABERRANT_SNCA_TO_ELECTRON_TRANSFER_IN_COMPLEX_I,0.753577,3.940991e-02
28,LV727,C2CP_KEGG_VALINE_LEUCINE_AND_ISOLEUCINE_BIOSYNTHESIS,0.941699,8.125798e-02
29,LV804,C2CP_REACTOME_ENTEROBACTERIAL_FACTORS_ANTAGONIZE_HOST_DEFENSE,0.999946,5.590718e-02
30,LV898,C2CP_REACTOME_SPHINGOLIPID_CATABOLISM,0.989128,5.523544e-02
31,LV941,C2CP_WP_ASPIRIN_AND_MIRNAS,0.960292,6.043886e-02

In [42]:
pituitary_pathways = analyze("Pituitary", "pituitary")

────────────────────────────────────────────────────────────────
  Pituitary  (keyword: 'pituitary')  |  samples in model: 25
  Expected in top 1%: 0.2  |  Selected LVs: 0

Empty DataFrame
Columns: [LV, n_in_top1pct, enrich_ratio, median_rank_pct, AUC, FDR]
Index: []

  Pathways:
  (none)

In [43]:
pituitary_pathways

Empty DataFrame
Columns: [LV, pathway, AUC, FDR]
Index: []

In [44]:
prostate_pathways = analyze("Prostate", "prostate")

────────────────────────────────────────────────────────────────
  Prostate  (keyword: 'prostate')  |  samples in model: 6,335
  Expected in top 1%: 63.3  |  Selected LVs: 15

,LV,n_in_top1pct,enrich_ratio,median_rank_pct,AUC,FDR
0,LV1362,202,3.189,0.4770,0.512236,2.255821e-03
1,LV1561,184,2.905,0.4710,0.527038,2.826329e-12
2,LV299,178,2.810,0.4745,0.525512,4.906036e-11
3,LV1432,174,2.747,0.4762,0.521807,2.423404e-08
4,LV1145,169,2.668,0.4865,0.509832,1.489998e-02
5,LV1172,162,2.557,0.4856,0.520106,2.903725e-07
6,LV1601,161,2.541,0.4775,0.515220,1.206832e-04
7,LV37,157,2.478,0.4854,0.509274,2.240084e-02
8,LV873,154,2.431,0.4856,0.515248,1.177483e-04
9,LV746,149,2.352,0.4788,0.515544,8.576832e-05
10,LV435,134,2.115,0.4626,0.530758,2.579224e-15
11,LV279,134,2.115,0.4862,0.512298,2.142245e-03
12,LV174,132,2.084,0.4842,0.514611,2.286823e-04
13,LV1470,132,2.084,0.4768,0.513668,5.905841e-04
14,LV1151,127,2.005,0.4848,0.512096,2.538029e-03

  Pathways:

,LV,pathway,AUC,FDR
0,LV1145,C2CP_KEGG_MEDICUS_REFERENCE_MDM2_P21_CELL_CYCLE_G1_S_N00536,0.965898,0.070395
1,LV1151,C2CP_KEGG_MEDICUS_VARIANT_MUTATION_CAUSED_ABERRANT_ABETA_TO_MACHR_CA2_APOPTOTIC_PATHWAY,0.893499,0.061869
2,LV1172,C2CP_REACTOME_MOLECULES_ASSOCIATED_WITH_ELASTIC_FIBRES,1.000000,0.000361
3,LV1172,C2CP_REACTOME_ELASTIC_FIBRE_FORMATION,0.814207,0.016491
4,LV1172,C2CP_WP_MAJOR_RECEPTORS_TARGETED_BY_EPINEPHRINE_AND_NOREPINEPHRINE,0.977844,0.069074
5,LV174,C2CP_REACTOME_ACTIVATED_PKN1_STIMULATES_TRANSCRIPTION_OF_AR_ANDROGEN_RECEPTOR_REGULATED_GENES_KLK2_AND_KLK3,0.697288,0.066117

In [45]:
prostate_pathways

,LV,pathway,AUC,FDR
0,LV1145,C2CP_KEGG_MEDICUS_REFERENCE_MDM2_P21_CELL_CYCLE_G1_S_N00536,0.965898,0.070395
1,LV1151,C2CP_KEGG_MEDICUS_VARIANT_MUTATION_CAUSED_ABERRANT_ABETA_TO_MACHR_CA2_APOPTOTIC_PATHWAY,0.893499,0.061869
2,LV1172,C2CP_REACTOME_MOLECULES_ASSOCIATED_WITH_ELASTIC_FIBRES,1.000000,0.000361
3,LV1172,C2CP_REACTOME_ELASTIC_FIBRE_FORMATION,0.814207,0.016491
4,LV1172,C2CP_WP_MAJOR_RECEPTORS_TARGETED_BY_EPINEPHRINE_AND_NOREPINEPHRINE,0.977844,0.069074
5,LV174,C2CP_REACTOME_ACTIVATED_PKN1_STIMULATES_TRANSCRIPTION_OF_AR_ANDROGEN_RECEPTOR_REGULATED_GENES_KLK2_AND_KLK3,0.697288,0.066117

In [46]:
skin_pathways = analyze("Skin", "skin")

────────────────────────────────────────────────────────────────
  Skin  (keyword: 'skin')  |  samples in model: 10,464
  Expected in top 1%: 104.6  |  Selected LVs: 33

,LV,n_in_top1pct,enrich_ratio,median_rank_pct,AUC,FDR
0,LV135,344,3.288,0.4406,0.541302,5.786093e-46
1,LV937,305,2.915,0.4739,0.521869,7.145982e-14
2,LV1236,295,2.819,0.4943,0.512331,3.067113e-05
3,LV1224,286,2.733,0.4837,0.517112,5.565893e-09
4,LV11,275,2.628,0.4588,0.528980,2.388256e-23
5,LV1138,273,2.609,0.5006,0.508203,5.893561e-03
6,LV1061,273,2.609,0.4677,0.527091,1.382651e-20
7,LV312,264,2.523,0.4760,0.521063,5.780055e-13
8,LV1425,264,2.523,0.5017,0.511274,1.403307e-04
9,LV171,249,2.380,0.4954,0.507519,1.181465e-02
10,LV138,246,2.351,0.4817,0.519252,4.933023e-11
11,LV1428,241,2.303,0.4605,0.527577,2.780698e-21
12,LV544,238,2.275,0.4577,0.528510,1.178957e-22
13,LV57,237,2.265,0.4827,0.513048,1.002295e-05
14,LV617,237,2.265,0.4842,0.515657,1.028619e-07
15,LV1067,233,2.227,0.4481,0.538282,1.056664e-39
16,LV712,229,2.189,0.4844,0.507752,9.356116e-03
17,LV1186,228,2.179,0.4981,0.518936,1.019509e-10
18,LV460,227,2.169,0.4916,0.505977,4.665919e-02
19,LV1522,224,2.141,0.4852,0.508294,5.377522e-03
20,LV1273,223,2.131,0.4664,0.526219,2.267066e-19
21,LV1361,223,2.131,0.4742,0.515277,2.096523e-07
22,LV1402,221,2.112,0.4327,0.543401,1.684651e-50
23,LV1039,218,2.083,0.5009,0.508308,5.312913e-03
24,LV1159,217,2.074,0.4964,0.506531,2.957768e-02
25,LV1141,216,2.064,0.4698,0.514663,6.438436e-07
26,LV253,216,2.064,0.4635,0.518399,3.444158e-10
27,LV664,215,2.055,0.4592,0.533974,1.351458e-31
28,LV1469,215,2.055,0.4933,0.507706,9.766262e-03
29,LV1445,212,2.026,0.4943,0.506601,2.795092e-02
30,LV1507,211,2.016,0.4864,0.508864,2.907466e-03
31,LV288,210,2.007,0.4770,0.522978,3.481301e-15
32,LV36,210,2.007,0.4930,0.506837,2.253019e-02

  Pathways:

,LV,pathway,AUC,FDR
0,LV1039,C2CP_BIOCARTA_COMP_PATHWAY,0.968842,0.022100
1,LV1039,C2CP_BIOCARTA_CLASSIC_PATHWAY,0.929976,0.085337
2,LV1061,C2CP_KEGG_GLYCINE_SERINE_AND_THREONINE_METABOLISM,0.889486,0.015817
3,LV1061,C2CP_WP_DISORDERS_OF_FRUCTOSE_METABOLISM,1.000000,0.056403
4,LV11,C2CP_WP_BIOMARKERS_FOR_UREA_CYCLE_DISORDERS,0.998419,0.055862
5,LV11,C2CP_KEGG_MEDICUS_REFERENCE_BILE_ACID_BIOSYNTHESIS,0.987243,0.057616
6,LV11,C2CP_WP_ANDROGEN_BIOSYNTHESIS,0.969225,0.063770
7,LV11,C2CP_REACTOME_SYNTHESIS_OF_BILE_ACIDS_AND_BILE_SALTS_VIA_24_HYDROXYCHOLESTEROL,0.964482,0.066117
8,LV11,C2CP_WP_FARNESOID_X_RECEPTOR_PATHWAY,0.959876,0.068223
9,LV11,C2CP_WP_CHOLESTASIS,0.844082,0.093431
10,LV1138,C2CP_KEGG_STEROID_BIOSYNTHESIS,0.964529,0.023092
11,LV1273,C2CP_REACTOME_SYNTHESIS_OF_BILE_ACIDS_AND_BILE_SALTS_VIA_24_HYDROXYCHOLESTEROL,0.983968,0.063308
12,LV135,C2CP_REACTOME_KERATINIZATION,0.861313,0.003217
13,LV135,C2CP_REACTOME_FORMATION_OF_THE_CORNIFIED_ENVELOPE,0.806304,0.016156
14,LV135,C2CP_REACTOME_APOPTOTIC_CLEAVAGE_OF_CELL_ADHESION_PROTEINS,0.982877,0.060174
15,LV135,C2CP_KEGG_MEDICUS_PATHOGEN_ESCHERICHIA_EAE_TIR_TCCP_TO_ACTIN_SIGNALING_PATHWAY,0.924746,0.094833
16,LV1361,C2CP_KEGG_LINOLEIC_ACID_METABOLISM,0.964886,0.022622
17,LV1361,C2CP_REACTOME_DEVELOPMENTAL_CELL_LINEAGES_OF_THE_INTEGUMENTARY_SYSTEM,0.707323,0.063632
18,LV138,C2CP_WP_PROSTAGLANDIN_SIGNALING,0.783145,0.062716
19,LV138,C2CP_REACTOME_INTERLEUKIN_10_SIGNALING,0.741806,0.065922
20,LV1402,C2CP_BIOCARTA_CLASSIC_PATHWAY,1.000000,0.059199
21,LV1402,C2CP_WP_MARKERS_OF_KIDNEY_CELL_LINEAGE,0.721820,0.071943
22,LV1469,C2CP_KEGG_MEDICUS_REFERENCE_BETA_OXIDATION,1.000000,0.055862
23,LV253,C2CP_KEGG_MEDICUS_ENV_FACTOR_DCE_TO_DNA_ADDUCTS,0.998822,0.017673
24,LV312,C2CP_BIOCARTA_COMP_PATHWAY,1.000000,0.017065
25,LV460,C2CP_REACTOME_BIOSYNTHESIS_OF_SPECIALIZED_PRORESOLVING_MEDIATORS_SPMS,0.881019,0.066389
26,LV544,C2CP_REACTOME_BINDING_AND_UPTAKE_OF_LIGANDS_BY_SCAVENGER_RECEPTORS,0.776026,0.001672
27,LV544,C2CP_REACTOME_COMPLEMENT_CASCADE,0.669432,0.067416
28,LV617,C2CP_REACTOME_LGI_ADAM_INTERACTIONS,0.954498,0.084159
29,LV664,C2CP_REACTOME_INTRINSIC_PATHWAY_OF_FIBRIN_CLOT_FORMATION,0.979230,0.018613
30,LV664,C2CP_WP_METABOLIC_PATHWAY_OF_LDL_HDL_AND_TG_INCLUDING_DISEASES,0.930852,0.040290
31,LV664,C2CP_WP_FAMILIAL_HYPERLIPIDEMIA_TYPE_5,0.987484,0.056869
32,LV712,C2CP_REACTOME_RESPONSE_TO_METAL_IONS,1.000000,0.056869
33,LV712,C2CP_WP_ZINC_HOMEOSTASIS,0.780331,0.060174
34,LV937,C2CP_WP_TAMOXIFEN_METABOLISM,1.000000,0.054814

In [47]:
skin_pathways

,LV,pathway,AUC,FDR
0,LV1039,C2CP_BIOCARTA_COMP_PATHWAY,0.968842,0.022100
1,LV1039,C2CP_BIOCARTA_CLASSIC_PATHWAY,0.929976,0.085337
2,LV1061,C2CP_KEGG_GLYCINE_SERINE_AND_THREONINE_METABOLISM,0.889486,0.015817
3,LV1061,C2CP_WP_DISORDERS_OF_FRUCTOSE_METABOLISM,1.000000,0.056403
4,LV11,C2CP_WP_BIOMARKERS_FOR_UREA_CYCLE_DISORDERS,0.998419,0.055862
5,LV11,C2CP_KEGG_MEDICUS_REFERENCE_BILE_ACID_BIOSYNTHESIS,0.987243,0.057616
6,LV11,C2CP_WP_ANDROGEN_BIOSYNTHESIS,0.969225,0.063770
7,LV11,C2CP_REACTOME_SYNTHESIS_OF_BILE_ACIDS_AND_BILE_SALTS_VIA_24_HYDROXYCHOLESTEROL,0.964482,0.066117
8,LV11,C2CP_WP_FARNESOID_X_RECEPTOR_PATHWAY,0.959876,0.068223
9,LV11,C2CP_WP_CHOLESTASIS,0.844082,0.093431
10,LV1138,C2CP_KEGG_STEROID_BIOSYNTHESIS,0.964529,0.023092
11,LV1273,C2CP_REACTOME_SYNTHESIS_OF_BILE_ACIDS_AND_BILE_SALTS_VIA_24_HYDROXYCHOLESTEROL,0.983968,0.063308
12,LV135,C2CP_REACTOME_KERATINIZATION,0.861313,0.003217
13,LV135,C2CP_REACTOME_FORMATION_OF_THE_CORNIFIED_ENVELOPE,0.806304,0.016156
14,LV135,C2CP_REACTOME_APOPTOTIC_CLEAVAGE_OF_CELL_ADHESION_PROTEINS,0.982877,0.060174
15,LV135,C2CP_KEGG_MEDICUS_PATHOGEN_ESCHERICHIA_EAE_TIR_TCCP_TO_ACTIN_SIGNALING_PATHWAY,0.924746,0.094833
16,LV1361,C2CP_KEGG_LINOLEIC_ACID_METABOLISM,0.964886,0.022622
17,LV1361,C2CP_REACTOME_DEVELOPMENTAL_CELL_LINEAGES_OF_THE_INTEGUMENTARY_SYSTEM,0.707323,0.063632
18,LV138,C2CP_WP_PROSTAGLANDIN_SIGNALING,0.783145,0.062716
19,LV138,C2CP_REACTOME_INTERLEUKIN_10_SIGNALING,0.741806,0.065922
20,LV1402,C2CP_BIOCARTA_CLASSIC_PATHWAY,1.000000,0.059199
21,LV1402,C2CP_WP_MARKERS_OF_KIDNEY_CELL_LINEAGE,0.721820,0.071943
22,LV1469,C2CP_KEGG_MEDICUS_REFERENCE_BETA_OXIDATION,1.000000,0.055862
23,LV253,C2CP_KEGG_MEDICUS_ENV_FACTOR_DCE_TO_DNA_ADDUCTS,0.998822,0.017673
24,LV312,C2CP_BIOCARTA_COMP_PATHWAY,1.000000,0.017065
25,LV460,C2CP_REACTOME_BIOSYNTHESIS_OF_SPECIALIZED_PRORESOLVING_MEDIATORS_SPMS,0.881019,0.066389
26,LV544,C2CP_REACTOME_BINDING_AND_UPTAKE_OF_LIGANDS_BY_SCAVENGER_RECEPTORS,0.776026,0.001672
27,LV544,C2CP_REACTOME_COMPLEMENT_CASCADE,0.669432,0.067416
28,LV617,C2CP_REACTOME_LGI_ADAM_INTERACTIONS,0.954498,0.084159
29,LV664,C2CP_REACTOME_INTRINSIC_PATHWAY_OF_FIBRIN_CLOT_FORMATION,0.979230,0.018613
30,LV664,C2CP_WP_METABOLIC_PATHWAY_OF_LDL_HDL_AND_TG_INCLUDING_DISEASES,0.930852,0.040290
31,LV664,C2CP_WP_FAMILIAL_HYPERLIPIDEMIA_TYPE_5,0.987484,0.056869
32,LV712,C2CP_REACTOME_RESPONSE_TO_METAL_IONS,1.000000,0.056869
33,LV712,C2CP_WP_ZINC_HOMEOSTASIS,0.780331,0.060174
34,LV937,C2CP_WP_TAMOXIFEN_METABOLISM,1.000000,0.054814

In [48]:
small_intestine_pathways = analyze("Small intestine", "small intestine")

────────────────────────────────────────────────────────────────
  Small intestine  (keyword: 'small intestine')  |  samples in model: 304
  Expected in top 1%: 3.0  |  Selected LVs: 44

,LV,n_in_top1pct,enrich_ratio,median_rank_pct,AUC,FDR
0,LV467,61,20.066,0.3493,0.610196,1.353767e-10
1,LV7,57,18.750,0.4049,0.575432,1.191857e-05
2,LV245,55,18.093,0.3446,0.644541,3.157366e-17
3,LV217,51,16.777,0.2893,0.642512,8.862230e-17
4,LV829,50,16.448,0.3128,0.647851,5.961917e-18
5,LV1017,45,14.803,0.2950,0.635749,2.265524e-15
6,LV342,42,13.816,0.1700,0.711022,1.488095e-34
7,LV909,39,12.829,0.2982,0.648181,5.058000e-18
8,LV1217,38,12.500,0.3876,0.585287,7.036494e-07
9,LV1022,38,12.500,0.3395,0.616316,1.175259e-11
10,LV473,35,11.513,0.3072,0.625142,2.957075e-13
11,LV975,35,11.513,0.3872,0.593260,5.785330e-08
12,LV1666,34,11.184,0.3580,0.598852,8.663746e-09
13,LV1235,34,11.184,0.4199,0.586731,4.538138e-07
14,LV726,33,10.856,0.4408,0.556480,1.087956e-03
15,LV939,32,10.527,0.3726,0.604003,1.366266e-09
16,LV90,31,10.198,0.2829,0.670010,3.101600e-23
17,LV768,31,10.198,0.3682,0.565142,1.621976e-04
18,LV474,30,9.869,0.2686,0.673925,3.836595e-24
19,LV809,30,9.869,0.3117,0.600795,4.376744e-09
20,LV1631,30,9.869,0.3146,0.603831,1.447291e-09
21,LV67,29,9.540,0.2272,0.673508,4.606129e-24
22,LV1651,28,9.211,0.4309,0.579227,4.170164e-06
23,LV1047,28,9.211,0.2809,0.676860,6.375259e-25
24,LV1118,28,9.211,0.3543,0.590437,1.426254e-07
25,LV633,26,8.553,0.3886,0.547308,6.422813e-03
26,LV57,26,8.553,0.3998,0.566565,1.148332e-04
27,LV959,26,8.553,0.4170,0.604743,1.038447e-09
28,LV1543,25,8.224,0.4236,0.544058,1.150794e-02
29,LV692,25,8.224,0.3220,0.652056,6.216431e-19
30,LV445,24,7.895,0.4043,0.594367,3.977351e-08
31,LV1446,24,7.895,0.3500,0.617722,6.670577e-12
32,LV303,24,7.895,0.4004,0.556127,1.167286e-03
33,LV179,24,7.895,0.4483,0.573705,1.859242e-05
34,LV114,24,7.895,0.2686,0.672809,6.753006e-24
35,LV1318,23,7.566,0.3697,0.593183,5.895385e-08
36,LV1298,23,7.566,0.3851,0.585931,5.787485e-07
37,LV1537,23,7.566,0.2301,0.677423,5.072072e-25
38,LV142,22,7.237,0.3193,0.646067,1.475345e-17
39,LV1241,22,7.237,0.4490,0.549271,4.477769e-03
40,LV534,21,6.908,0.2293,0.643446,5.497772e-17
41,LV1014,20,6.579,0.3838,0.617839,6.421782e-12
42,LV257,20,6.579,0.2760,0.636909,1.333038e-15
43,LV491,20,6.579,0.2759,0.637588,9.661788e-16

  Pathways:

,LV,pathway,AUC,FDR
0,LV1017,C2CP_KEGG_MEDICUS_ENV_FACTOR_IRON_TO_ANTEROGRADE_AXONAL_TRANSPORT,0.910452,0.049927
1,LV1047,C2CP_KEGG_MEDICUS_REFERENCE_PTH_PTH1R_PKA_SIGNALING_PATHWAY,0.916603,0.097814
2,LV1118,C2CP_WP_HEDGEHOG_SIGNALING_WP4249,0.834746,0.013760
3,LV1118,C2CP_BIOCARTA_COMP_PATHWAY,0.999855,0.016156
4,LV1118,C2CP_REACTOME_ACTIVATION_OF_SMO,1.000000,0.016156
5,LV114,C2CP_REACTOME_KILLING_MECHANISMS,0.933013,0.091309
6,LV1298,C2CP_KEGG_MEDICUS_REFERENCE_IGF2_IGF1R_PI3K_SIGNALING_PATHWAY,1.000000,0.057345
7,LV1298,C2CP_REACTOME_INTERLEUKIN_6_SIGNALING,1.000000,0.057345
8,LV1537,C2CP_REACTOME_CARNITINE_SHUTTLE,0.929781,0.096074
9,LV1543,C2CP_REACTOME_MET_ACTIVATES_PTK2_SIGNALING,0.886230,0.008311
10,LV1543,C2CP_REACTOME_ATTACHMENT_OF_BACTERIA_TO_EPITHELIAL_CELLS,0.803070,0.096143
11,LV1543,C2CP_REACTOME_FIBRONECTIN_MATRIX_FORMATION,0.803029,0.096144
12,LV1631,C2CP_REACTOME_DOPAMINE_NEUROTRANSMITTER_RELEASE_CYCLE,1.000000,0.004525
13,LV1631,C2CP_REACTOME_NEUROTRANSMITTER_RELEASE_CYCLE,0.790131,0.025180
14,LV1666,C2CP_REACTOME_FRS_MEDIATED_FGFR1_SIGNALING,0.999909,0.017423
15,LV1666,C2CP_REACTOME_PHOSPHOLIPASE_C_MEDIATED_CASCADE_FGFR2,1.000000,0.057567
16,LV217,C2CP_KEGG_MEDICUS_VARIANT_MUTATION_INACTIVATED_PRKAR1A_TO_ACTH_CORTISOL_SIGNALING_PATHWAY,0.993649,0.012122
17,LV217,C2CP_REACTOME_NUCLEAR_RECEPTOR_TRANSCRIPTION_PATHWAY,0.791728,0.016094
18,LV217,C2CP_WP_WHITE_FAT_CELL_DIFFERENTIATION,0.835253,0.016486
19,LV217,C2CP_BIOCARTA_PCAF_PATHWAY,0.964570,0.058881
20,LV217,C2CP_KEGG_MEDICUS_VARIANT_MUTATION_INACTIVATED_ATP2B3_TO_ANGIOTENSIN_ALDOSTERONE_SIGNALING_PATHWAY,0.865324,0.066117
21,LV303,C2CP_BIOCARTA_HIF_PATHWAY,0.979321,0.054814
22,LV303,C2CP_WP_NAD_METABOLISM_SIRTUINS_AND_AGING,0.902207,0.092114
23,LV342,C2CP_REACTOME_CRMPS_IN_SEMA3A_SIGNALING,0.967529,0.022830
24,LV467,C2CP_WP_NRXN1_DELETION_SYNDROME,0.996569,0.053376
25,LV467,C2CP_KEGG_MEDICUS_REFERENCE_KINETOCHORE_MICROTUBULE_ATTACHMENT,0.831373,0.099551
26,LV474,C2CP_WP_DISORDERS_OF_GALACTOSE_METABOLISM,0.933682,0.087594
27,LV474,C2CP_REACTOME_CARNITINE_SHUTTLE,0.928048,0.091628
28,LV491,C2CP_BIOCARTA_COMP_PATHWAY,0.947863,0.035421
29,LV491,C2CP_BIOCARTA_CLASSIC_PATHWAY,0.920677,0.097814
30,LV633,C2CP_WP_SRF_AND_MIRS_IN_SMOOTH_MUSCLE_DIFFERENTIATION_AND_PROLIFERATION,0.930328,0.090050
31,LV768,C2CP_KEGG_PRIMARY_BILE_ACID_BIOSYNTHESIS,0.928859,0.093161
32,LV809,C2CP_REACTOME_FGFR1C_LIGAND_BINDING_AND_ACTIVATION,0.954516,0.071449
33,LV809,C2CP_REACTOME_PHOSPHOLIPASE_C_MEDIATED_CASCADE_FGFR2,0.943647,0.078276
34,LV90,C2CP_KEGG_MEDICUS_PATHOGEN_ESCHERICHIA_EAE_TIR_TO_ACTIN_SIGNALING_PATHWAY,0.927019,0.050150
35,LV90,C2CP_KEGG_MEDICUS_REFERENCE_ANTIGEN_PROCESSING_AND_PRESENTATION_BY_MHC_CLASS_I_MOLECULES,0.998800,0.057345
36,LV90,C2CP_REACTOME_ENDOSOMAL_VACUOLAR_PATHWAY,0.997301,0.057588
37,LV90,C2CP_BIOCARTA_THELPER_PATHWAY,0.988876,0.059629
38,LV939,C2CP_WP_MIR5093P_ALTERATION_OF_YAP1ECM_AXIS,0.904749,0.056336
39,LV959,C2CP_REACTOME_METABOLISM_OF_FAT_SOLUBLE_VITAMINS,0.877860,0.004569

In [49]:
small_intestine_pathways

,LV,pathway,AUC,FDR
0,LV1017,C2CP_KEGG_MEDICUS_ENV_FACTOR_IRON_TO_ANTEROGRADE_AXONAL_TRANSPORT,0.910452,0.049927
1,LV1047,C2CP_KEGG_MEDICUS_REFERENCE_PTH_PTH1R_PKA_SIGNALING_PATHWAY,0.916603,0.097814
2,LV1118,C2CP_WP_HEDGEHOG_SIGNALING_WP4249,0.834746,0.013760
3,LV1118,C2CP_BIOCARTA_COMP_PATHWAY,0.999855,0.016156
4,LV1118,C2CP_REACTOME_ACTIVATION_OF_SMO,1.000000,0.016156
5,LV114,C2CP_REACTOME_KILLING_MECHANISMS,0.933013,0.091309
6,LV1298,C2CP_KEGG_MEDICUS_REFERENCE_IGF2_IGF1R_PI3K_SIGNALING_PATHWAY,1.000000,0.057345
7,LV1298,C2CP_REACTOME_INTERLEUKIN_6_SIGNALING,1.000000,0.057345
8,LV1537,C2CP_REACTOME_CARNITINE_SHUTTLE,0.929781,0.096074
9,LV1543,C2CP_REACTOME_MET_ACTIVATES_PTK2_SIGNALING,0.886230,0.008311
10,LV1543,C2CP_REACTOME_ATTACHMENT_OF_BACTERIA_TO_EPITHELIAL_CELLS,0.803070,0.096143
11,LV1543,C2CP_REACTOME_FIBRONECTIN_MATRIX_FORMATION,0.803029,0.096144
12,LV1631,C2CP_REACTOME_DOPAMINE_NEUROTRANSMITTER_RELEASE_CYCLE,1.000000,0.004525
13,LV1631,C2CP_REACTOME_NEUROTRANSMITTER_RELEASE_CYCLE,0.790131,0.025180
14,LV1666,C2CP_REACTOME_FRS_MEDIATED_FGFR1_SIGNALING,0.999909,0.017423
15,LV1666,C2CP_REACTOME_PHOSPHOLIPASE_C_MEDIATED_CASCADE_FGFR2,1.000000,0.057567
16,LV217,C2CP_KEGG_MEDICUS_VARIANT_MUTATION_INACTIVATED_PRKAR1A_TO_ACTH_CORTISOL_SIGNALING_PATHWAY,0.993649,0.012122
17,LV217,C2CP_REACTOME_NUCLEAR_RECEPTOR_TRANSCRIPTION_PATHWAY,0.791728,0.016094
18,LV217,C2CP_WP_WHITE_FAT_CELL_DIFFERENTIATION,0.835253,0.016486
19,LV217,C2CP_BIOCARTA_PCAF_PATHWAY,0.964570,0.058881
20,LV217,C2CP_KEGG_MEDICUS_VARIANT_MUTATION_INACTIVATED_ATP2B3_TO_ANGIOTENSIN_ALDOSTERONE_SIGNALING_PATHWAY,0.865324,0.066117
21,LV303,C2CP_BIOCARTA_HIF_PATHWAY,0.979321,0.054814
22,LV303,C2CP_WP_NAD_METABOLISM_SIRTUINS_AND_AGING,0.902207,0.092114
23,LV342,C2CP_REACTOME_CRMPS_IN_SEMA3A_SIGNALING,0.967529,0.022830
24,LV467,C2CP_WP_NRXN1_DELETION_SYNDROME,0.996569,0.053376
25,LV467,C2CP_KEGG_MEDICUS_REFERENCE_KINETOCHORE_MICROTUBULE_ATTACHMENT,0.831373,0.099551
26,LV474,C2CP_WP_DISORDERS_OF_GALACTOSE_METABOLISM,0.933682,0.087594
27,LV474,C2CP_REACTOME_CARNITINE_SHUTTLE,0.928048,0.091628
28,LV491,C2CP_BIOCARTA_COMP_PATHWAY,0.947863,0.035421
29,LV491,C2CP_BIOCARTA_CLASSIC_PATHWAY,0.920677,0.097814
30,LV633,C2CP_WP_SRF_AND_MIRS_IN_SMOOTH_MUSCLE_DIFFERENTIATION_AND_PROLIFERATION,0.930328,0.090050
31,LV768,C2CP_KEGG_PRIMARY_BILE_ACID_BIOSYNTHESIS,0.928859,0.093161
32,LV809,C2CP_REACTOME_FGFR1C_LIGAND_BINDING_AND_ACTIVATION,0.954516,0.071449
33,LV809,C2CP_REACTOME_PHOSPHOLIPASE_C_MEDIATED_CASCADE_FGFR2,0.943647,0.078276
34,LV90,C2CP_KEGG_MEDICUS_PATHOGEN_ESCHERICHIA_EAE_TIR_TO_ACTIN_SIGNALING_PATHWAY,0.927019,0.050150
35,LV90,C2CP_KEGG_MEDICUS_REFERENCE_ANTIGEN_PROCESSING_AND_PRESENTATION_BY_MHC_CLASS_I_MOLECULES,0.998800,0.057345
36,LV90,C2CP_REACTOME_ENDOSOMAL_VACUOLAR_PATHWAY,0.997301,0.057588
37,LV90,C2CP_BIOCARTA_THELPER_PATHWAY,0.988876,0.059629
38,LV939,C2CP_WP_MIR5093P_ALTERATION_OF_YAP1ECM_AXIS,0.904749,0.056336
39,LV959,C2CP_REACTOME_METABOLISM_OF_FAT_SOLUBLE_VITAMINS,0.877860,0.004569

In [50]:
spleen_pathways = analyze("Spleen", "spleen")

────────────────────────────────────────────────────────────────
  Spleen  (keyword: 'spleen')  |  samples in model: 501
  Expected in top 1%: 5.0  |  Selected LVs: 9

       LV  n_in_top1pct  enrich_ratio  median_rank_pct       AUC           FDR
0   LV727            47         9.381           0.4603  0.549886  8.156842e-04
1    LV70            40         7.984           0.3311  0.586178  2.593821e-09
2   LV611            36         7.186           0.4395  0.556788  1.273424e-04
3   LV527            31         6.188           0.4214  0.551378  5.787568e-04
4    LV14            30         5.988           0.4554  0.547540  1.481580e-03
5   LV103            28         5.589           0.4445  0.549160  9.757160e-04
6  LV1635            21         4.192           0.4474  0.536591  1.637668e-02
7   LV573            21         4.192           0.3972  0.559915  4.902470e-05
8  LV1019            20         3.992           0.4474  0.539256  9.791345e-03

  Pathways:

,LV,pathway,AUC,FDR
0,LV1019,C2CP_KEGG_MEDICUS_REFERENCE_PTH_PTH1R_PKA_SIGNALING_PATHWAY,0.957200,0.065724
1,LV103,C2CP_PID_RHODOPSIN_PATHWAY,0.997573,0.055910
2,LV14,C2CP_KEGG_MEDICUS_REFERENCE_TRAIP_DEPENDENT_REPLISOME_DISASSEMBLY,0.941648,0.038331
3,LV1635,C2CP_KEGG_MEDICUS_ENV_FACTOR_DCE_TO_DNA_ADDUCTS,0.855302,0.081620
4,LV70,C2CP_WP_STRIATED_MUSCLE_CONTRACTION_PATHWAY,0.902925,0.004298
5,LV727,C2CP_KEGG_MEDICUS_VARIANT_MUTATION_CAUSED_ABERRANT_SNCA_TO_ELECTRON_TRANSFER_IN_COMPLEX_I,0.753577,0.039410
6,LV727,C2CP_KEGG_VALINE_LEUCINE_AND_ISOLEUCINE_BIOSYNTHESIS,0.941699,0.081258

In [51]:
spleen_pathways

,LV,pathway,AUC,FDR
0,LV1019,C2CP_KEGG_MEDICUS_REFERENCE_PTH_PTH1R_PKA_SIGNALING_PATHWAY,0.957200,0.065724
1,LV103,C2CP_PID_RHODOPSIN_PATHWAY,0.997573,0.055910
2,LV14,C2CP_KEGG_MEDICUS_REFERENCE_TRAIP_DEPENDENT_REPLISOME_DISASSEMBLY,0.941648,0.038331
3,LV1635,C2CP_KEGG_MEDICUS_ENV_FACTOR_DCE_TO_DNA_ADDUCTS,0.855302,0.081620
4,LV70,C2CP_WP_STRIATED_MUSCLE_CONTRACTION_PATHWAY,0.902925,0.004298
5,LV727,C2CP_KEGG_MEDICUS_VARIANT_MUTATION_CAUSED_ABERRANT_SNCA_TO_ELECTRON_TRANSFER_IN_COMPLEX_I,0.753577,0.039410
6,LV727,C2CP_KEGG_VALINE_LEUCINE_AND_ISOLEUCINE_BIOSYNTHESIS,0.941699,0.081258

In [52]:
stomach_pathways = analyze("Stomach", "stomach")

────────────────────────────────────────────────────────────────
  Stomach  (keyword: 'stomach')  |  samples in model: 436
  Expected in top 1%: 4.4  |  Selected LVs: 37

,LV,n_in_top1pct,enrich_ratio,median_rank_pct,AUC,FDR
0,LV125,48,11.009,0.3814,0.575706,2.483966e-07
1,LV290,43,9.863,0.4613,0.547495,1.274104e-03
2,LV1721,42,9.633,0.3715,0.565979,6.836624e-06
3,LV51,39,8.945,0.4085,0.556451,1.241536e-04
4,LV1216,39,8.945,0.3706,0.586919,3.082885e-09
5,LV1453,35,8.028,0.4772,0.546152,1.762662e-03
6,LV1403,34,7.798,0.3991,0.572143,8.707240e-07
7,LV346,33,7.569,0.3428,0.601545,3.857716e-12
8,LV284,32,7.340,0.4825,0.539355,7.831299e-03
9,LV361,31,7.110,0.5103,0.539841,7.110624e-03
10,LV1543,29,6.652,0.4844,0.541571,4.931584e-03
11,LV409,29,6.652,0.4575,0.558758,6.520978e-05
12,LV741,28,6.422,0.3606,0.603476,1.506406e-12
13,LV12,28,6.422,0.3081,0.612311,1.455593e-14
14,LV617,27,6.193,0.3688,0.587767,2.193359e-09
15,LV1047,25,5.734,0.4341,0.551289,5.017273e-04
16,LV612,25,5.734,0.4393,0.550238,6.584622e-04
17,LV531,25,5.734,0.4632,0.544472,2.603354e-03
18,LV665,24,5.505,0.3419,0.622643,4.024769e-17
19,LV1258,23,5.275,0.4737,0.539852,7.107549e-03
20,LV634,23,5.275,0.3255,0.611394,2.377035e-14
21,LV1635,23,5.275,0.3897,0.575073,3.112263e-07
22,LV525,23,5.275,0.3903,0.559826,4.809248e-05
23,LV991,23,5.275,0.4003,0.554224,2.297602e-04
24,LV1057,23,5.275,0.4628,0.559616,5.060293e-05
25,LV197,22,5.046,0.3571,0.584041,1.019161e-08
26,LV917,22,5.046,0.4187,0.553480,2.817279e-04
27,LV673,22,5.046,0.3173,0.593189,1.876318e-10
28,LV803,22,5.046,0.4634,0.570641,1.482144e-06
29,LV304,21,4.817,0.4742,0.537570,1.132975e-02
30,LV241,21,4.817,0.4024,0.557892,8.233399e-05
31,LV1338,21,4.817,0.4213,0.577981,1.050961e-07
32,LV370,20,4.587,0.4190,0.578916,7.506938e-08
33,LV127,20,4.587,0.4225,0.551936,4.224909e-04
34,LV824,20,4.587,0.4860,0.540949,5.615835e-03
35,LV1527,20,4.587,0.3814,0.585459,5.564000e-09
36,LV874,20,4.587,0.3838,0.589748,9.018008e-10

  Pathways:

,LV,pathway,AUC,FDR
0,LV1047,C2CP_KEGG_MEDICUS_REFERENCE_PTH_PTH1R_PKA_SIGNALING_PATHWAY,0.916603,0.097814
1,LV1057,C2CP_BIOCARTA_VITCB_PATHWAY,0.934916,0.093600
2,LV12,C2CP_KEGG_MEDICUS_PATHOGEN_SHIGELLA_IPAC_TO_ACTIN_SIGNALING_PATHWAY,0.983742,0.062716
3,LV12,C2CP_KEGG_MEDICUS_REFERENCE_ARNO_ARF_ACTB_G_SIGNALING_PATHWAY,0.797179,0.069078
4,LV1216,C2CP_REACTOME_NEGATIVE_REGULATION_OF_NMDA_RECEPTOR_MEDIATED_NEURONAL_TRANSMISSION,0.937267,0.053183
5,LV125,C2CP_KEGG_MEDICUS_REFERENCE_REGULATION_OF_GF_RTK_RAS_ERK_SIGNALING_PATHWAY_ADAPTOR_PROTEINS,0.933630,0.089650
6,LV1258,C2CP_REACTOME_PHASE_0_RAPID_DEPOLARISATION,1.000000,0.005192
7,LV1258,C2CP_REACTOME_MUSCLE_CONTRACTION,0.637225,0.050150
8,LV1258,C2CP_REACTOME_ION_HOMEOSTASIS,0.726109,0.066564
9,LV1258,C2CP_WP_PANCREATIC_CANCER_SUBTYPES,0.752519,0.092620
10,LV127,C2CP_BIOCARTA_CLASSIC_PATHWAY,0.955657,0.069624
11,LV1527,C2CP_WP_TYROBP_CAUSAL_NETWORK_IN_MICROGLIA,0.856276,0.000363
12,LV1527,C2CP_BIOCARTA_CYTOKINE_PATHWAY,0.973048,0.063433
13,LV1543,C2CP_REACTOME_MET_ACTIVATES_PTK2_SIGNALING,0.886230,0.008311
14,LV1543,C2CP_REACTOME_ATTACHMENT_OF_BACTERIA_TO_EPITHELIAL_CELLS,0.803070,0.096143
15,LV1543,C2CP_REACTOME_FIBRONECTIN_MATRIX_FORMATION,0.803029,0.096144
16,LV1635,C2CP_KEGG_MEDICUS_ENV_FACTOR_DCE_TO_DNA_ADDUCTS,0.855302,0.081620
17,LV1721,C2CP_KEGG_MEDICUS_REFERENCE_ITGA_B_RHOGEF_RHOA_SIGNALING_PATHWAY,1.000000,0.005245
18,LV197,C2CP_REACTOME_STRIATED_MUSCLE_CONTRACTION,0.849746,0.028716
19,LV241,C2CP_WP_GENES_TARGETED_BY_MIRNAS_IN_ADIPOCYTES,0.975828,0.058800
20,LV304,C2CP_BIOCARTA_THELPER_PATHWAY,0.982791,0.055862
21,LV346,C2CP_KEGG_MEDICUS_REFERENCE_AUTOPHAGY_VESICLE_NUCLEATION_ELONGATION_MATURATION_PI3P_SYNTHESIS_BY_PI3KC3_C1,0.958549,0.073260
22,LV361,C2CP_KEGG_SPHINGOLIPID_METABOLISM,0.977475,0.000639
23,LV361,C2CP_WP_SPHINGOLIPID_METABOLISM_INTEGRATED_PATHWAY,0.991204,0.001656
24,LV370,C2CP_PID_S1P_META_PATHWAY,0.836569,0.060174
25,LV51,C2CP_REACTOME_ACETYLCHOLINE_REGULATES_INSULIN_SECRETION,0.922987,0.089084
26,LV612,C2CP_KEGG_MEDICUS_REFERENCE_MICROTUBULE_DEPOLYMERIZATION_AT_THE_MINUS_ENDS,0.994018,0.022830
27,LV612,C2CP_REACTOME_TRANSPORT_OF_CONNEXONS_TO_THE_PLASMA_MEMBRANE,0.934182,0.053918
28,LV617,C2CP_REACTOME_LGI_ADAM_INTERACTIONS,0.954498,0.084159
29,LV634,C2CP_WP_COMPLEMENT_AND_COAGULATION_CASCADES,0.793860,0.018339
30,LV634,C2CP_REACTOME_COMMON_PATHWAY_OF_FIBRIN_CLOT_FORMATION,1.000000,0.020745
31,LV634,C2CP_REACTOME_INTRINSIC_PATHWAY_OF_FIBRIN_CLOT_FORMATION,1.000000,0.020745
32,LV665,C2CP_REACTOME_GABA_SYNTHESIS_RELEASE_REUPTAKE_AND_DEGRADATION,0.963752,0.029490
33,LV665,C2CP_REACTOME_VOLTAGE_GATED_POTASSIUM_CHANNELS,0.938458,0.043380
34,LV665,C2CP_REACTOME_LGI_ADAM_INTERACTIONS,0.935118,0.089741
35,LV673,C2CP_REACTOME_FIBRONECTIN_MATRIX_FORMATION,0.809890,0.079588
36,LV824,C2CP_REACTOME_DEGRADATION_OF_CRY_AND_PER_PROTEINS,0.966348,0.000030
37,LV824,C2CP_KEGG_MEDICUS_VARIANT_MUTATION_CAUSED_ABERRANT_SNCA_TO_26S_PROTEASOME_MEDIATED_PROTEIN_DEGRADATION,0.957231,0.000429
38,LV824,C2CP_KEGG_MEDICUS_VARIANT_MUTATION_CAUSED_ABERRANT_ABETA_TO_26S_PROTEASOME_MEDIATED_PROTEIN_DEGRADATION,0.920106,0.001610
39,LV824,C2CP_REACTOME_VIF_MEDIATED_DEGRADATION_OF_APOBEC3G,0.892526,0.001627
40,LV824,C2CP_KEGG_MEDICUS_VARIANT_MUTATION_INACTIVATED_UBQLN2_TO_26S_PROTEASOME_MEDIATED_PROTEIN_DEGRADATION,0.914625,0.001893
41,LV874,C2CP_REACTOME_DOPAMINE_NEUROTRANSMITTER_RELEASE_CYCLE,0.999986,0.004923
42,LV874,C2CP_REACTOME_NEUROTRANSMITTER_RELEASE_CYCLE,0.767179,0.047124
43,LV991,C2CP_BIOCARTA_NUCLEARRS_PATHWAY,0.948567,0.015852

In [53]:
stomach_pathways

,LV,pathway,AUC,FDR
0,LV1047,C2CP_KEGG_MEDICUS_REFERENCE_PTH_PTH1R_PKA_SIGNALING_PATHWAY,0.916603,0.097814
1,LV1057,C2CP_BIOCARTA_VITCB_PATHWAY,0.934916,0.093600
2,LV12,C2CP_KEGG_MEDICUS_PATHOGEN_SHIGELLA_IPAC_TO_ACTIN_SIGNALING_PATHWAY,0.983742,0.062716
3,LV12,C2CP_KEGG_MEDICUS_REFERENCE_ARNO_ARF_ACTB_G_SIGNALING_PATHWAY,0.797179,0.069078
4,LV1216,C2CP_REACTOME_NEGATIVE_REGULATION_OF_NMDA_RECEPTOR_MEDIATED_NEURONAL_TRANSMISSION,0.937267,0.053183
5,LV125,C2CP_KEGG_MEDICUS_REFERENCE_REGULATION_OF_GF_RTK_RAS_ERK_SIGNALING_PATHWAY_ADAPTOR_PROTEINS,0.933630,0.089650
6,LV1258,C2CP_REACTOME_PHASE_0_RAPID_DEPOLARISATION,1.000000,0.005192
7,LV1258,C2CP_REACTOME_MUSCLE_CONTRACTION,0.637225,0.050150
8,LV1258,C2CP_REACTOME_ION_HOMEOSTASIS,0.726109,0.066564
9,LV1258,C2CP_WP_PANCREATIC_CANCER_SUBTYPES,0.752519,0.092620
10,LV127,C2CP_BIOCARTA_CLASSIC_PATHWAY,0.955657,0.069624
11,LV1527,C2CP_WP_TYROBP_CAUSAL_NETWORK_IN_MICROGLIA,0.856276,0.000363
12,LV1527,C2CP_BIOCARTA_CYTOKINE_PATHWAY,0.973048,0.063433
13,LV1543,C2CP_REACTOME_MET_ACTIVATES_PTK2_SIGNALING,0.886230,0.008311
14,LV1543,C2CP_REACTOME_ATTACHMENT_OF_BACTERIA_TO_EPITHELIAL_CELLS,0.803070,0.096143
15,LV1543,C2CP_REACTOME_FIBRONECTIN_MATRIX_FORMATION,0.803029,0.096144
16,LV1635,C2CP_KEGG_MEDICUS_ENV_FACTOR_DCE_TO_DNA_ADDUCTS,0.855302,0.081620
17,LV1721,C2CP_KEGG_MEDICUS_REFERENCE_ITGA_B_RHOGEF_RHOA_SIGNALING_PATHWAY,1.000000,0.005245
18,LV197,C2CP_REACTOME_STRIATED_MUSCLE_CONTRACTION,0.849746,0.028716
19,LV241,C2CP_WP_GENES_TARGETED_BY_MIRNAS_IN_ADIPOCYTES,0.975828,0.058800
20,LV304,C2CP_BIOCARTA_THELPER_PATHWAY,0.982791,0.055862
21,LV346,C2CP_KEGG_MEDICUS_REFERENCE_AUTOPHAGY_VESICLE_NUCLEATION_ELONGATION_MATURATION_PI3P_SYNTHESIS_BY_PI3KC3_C1,0.958549,0.073260
22,LV361,C2CP_KEGG_SPHINGOLIPID_METABOLISM,0.977475,0.000639
23,LV361,C2CP_WP_SPHINGOLIPID_METABOLISM_INTEGRATED_PATHWAY,0.991204,0.001656
24,LV370,C2CP_PID_S1P_META_PATHWAY,0.836569,0.060174
25,LV51,C2CP_REACTOME_ACETYLCHOLINE_REGULATES_INSULIN_SECRETION,0.922987,0.089084
26,LV612,C2CP_KEGG_MEDICUS_REFERENCE_MICROTUBULE_DEPOLYMERIZATION_AT_THE_MINUS_ENDS,0.994018,0.022830
27,LV612,C2CP_REACTOME_TRANSPORT_OF_CONNEXONS_TO_THE_PLASMA_MEMBRANE,0.934182,0.053918
28,LV617,C2CP_REACTOME_LGI_ADAM_INTERACTIONS,0.954498,0.084159
29,LV634,C2CP_WP_COMPLEMENT_AND_COAGULATION_CASCADES,0.793860,0.018339
30,LV634,C2CP_REACTOME_COMMON_PATHWAY_OF_FIBRIN_CLOT_FORMATION,1.000000,0.020745
31,LV634,C2CP_REACTOME_INTRINSIC_PATHWAY_OF_FIBRIN_CLOT_FORMATION,1.000000,0.020745
32,LV665,C2CP_REACTOME_GABA_SYNTHESIS_RELEASE_REUPTAKE_AND_DEGRADATION,0.963752,0.029490
33,LV665,C2CP_REACTOME_VOLTAGE_GATED_POTASSIUM_CHANNELS,0.938458,0.043380
34,LV665,C2CP_REACTOME_LGI_ADAM_INTERACTIONS,0.935118,0.089741
35,LV673,C2CP_REACTOME_FIBRONECTIN_MATRIX_FORMATION,0.809890,0.079588
36,LV824,C2CP_REACTOME_DEGRADATION_OF_CRY_AND_PER_PROTEINS,0.966348,0.000030
37,LV824,C2CP_KEGG_MEDICUS_VARIANT_MUTATION_CAUSED_ABERRANT_SNCA_TO_26S_PROTEASOME_MEDIATED_PROTEIN_DEGRADATION,0.957231,0.000429
38,LV824,C2CP_KEGG_MEDICUS_VARIANT_MUTATION_CAUSED_ABERRANT_ABETA_TO_26S_PROTEASOME_MEDIATED_PROTEIN_DEGRADATION,0.920106,0.001610
39,LV824,C2CP_REACTOME_VIF_MEDIATED_DEGRADATION_OF_APOBEC3G,0.892526,0.001627
40,LV824,C2CP_KEGG_MEDICUS_VARIANT_MUTATION_INACTIVATED_UBQLN2_TO_26S_PROTEASOME_MEDIATED_PROTEIN_DEGRADATION,0.914625,0.001893
41,LV874,C2CP_REACTOME_DOPAMINE_NEUROTRANSMITTER_RELEASE_CYCLE,0.999986,0.004923
42,LV874,C2CP_REACTOME_NEUROTRANSMITTER_RELEASE_CYCLE,0.767179,0.047124
43,LV991,C2CP_BIOCARTA_NUCLEARRS_PATHWAY,0.948567,0.015852

In [54]:
testis_pathways = analyze("Testis", "testis")

────────────────────────────────────────────────────────────────
  Testis  (keyword: 'testis')  |  samples in model: 317
  Expected in top 1%: 3.2  |  Selected LVs: 28

,LV,n_in_top1pct,enrich_ratio,median_rank_pct,AUC,FDR
0,LV1466,41,12.934,0.4160,0.574019,3.334786e-05
1,LV969,40,12.619,0.4403,0.569282,1.101555e-04
2,LV990,39,12.303,0.3793,0.584448,1.821272e-06
3,LV793,37,11.672,0.4467,0.559871,9.036201e-04
4,LV1046,37,11.672,0.3452,0.580272,6.367846e-06
5,LV30,34,10.726,0.4165,0.541066,2.794064e-02
6,LV1502,33,10.410,0.4070,0.550928,5.303150e-03
7,LV891,33,10.410,0.4686,0.561584,6.383867e-04
8,LV568,32,10.095,0.4993,0.542487,2.276106e-02
9,LV1507,25,7.887,0.4344,0.557036,1.612297e-03
10,LV671,25,7.887,0.4124,0.587061,8.178434e-07
11,LV1259,24,7.571,0.3633,0.588310,5.806333e-07
12,LV1028,24,7.571,0.3665,0.599556,1.634084e-08
13,LV301,24,7.571,0.3500,0.604357,3.239388e-09
14,LV1594,24,7.571,0.3083,0.624655,1.454328e-12
15,LV1483,24,7.571,0.5282,0.538680,3.945449e-02
16,LV233,24,7.571,0.4002,0.553101,3.521121e-03
17,LV1271,24,7.571,0.4406,0.547775,9.498498e-03
18,LV335,23,7.256,0.3488,0.590910,2.759757e-07
19,LV724,23,7.256,0.3534,0.595800,5.572016e-08
20,LV63,23,7.256,0.3404,0.589203,4.487838e-07
21,LV100,22,6.940,0.5175,0.553766,3.102220e-03
22,LV1051,22,6.940,0.4421,0.546820,1.120312e-02
23,LV1674,22,6.940,0.3699,0.593956,1.045863e-07
24,LV319,21,6.625,0.4311,0.560045,8.834383e-04
25,LV720,21,6.625,0.4388,0.577489,1.330202e-05
26,LV713,20,6.309,0.4911,0.542895,2.152266e-02
27,LV1355,20,6.309,0.2895,0.606384,1.481768e-09

  Pathways:

,LV,pathway,AUC,FDR
0,LV100,C2CP_KEGG_MEDICUS_REFERENCE_TCR_PLCG_ITPR_SIGNALING_PATHWAY,0.943106,3.503176e-02
1,LV100,C2CP_WP_REGULATION_OF_CYTOTOXIC_T_CELL_RESPONSES_BY_MALAT1_MIR1516_CIRCUIT,0.991172,5.686918e-02
2,LV1028,C2CP_WP_METHIONINE_METABOLISM_LEADING_TO_SULFUR_AMINO_ACIDS_AND_RELATED_DISORDERS,0.963774,7.144923e-02
3,LV1259,C2CP_REACTOME_SYNTHESIS_OF_GLYCOSYLPHOSPHATIDYLINOSITOL_GPI,0.954780,3.542061e-02
4,LV1259,C2CP_BIOCARTA_ATRBRCA_PATHWAY,0.872571,5.031171e-02
5,LV1271,C2CP_PID_INTEGRIN3_PATHWAY,0.786049,2.474244e-02
6,LV1271,C2CP_WP_OSTEOBLAST_SIGNALING,0.998034,5.621459e-02
7,LV1271,C2CP_REACTOME_DISSOLUTION_OF_FIBRIN_CLOT,0.960982,6.852737e-02
8,LV1271,C2CP_BIOCARTA_PLATELETAPP_PATHWAY,0.959262,6.962403e-02
9,LV1483,C2CP_KEGG_MEDICUS_REFERENCE_LOADING_OF_THE_SMC5_SMC6_COMPLEX,0.971932,6.890285e-02
10,LV1594,C2CP_REACTOME_MRNA_SPLICING,0.782896,5.264914e-09
11,LV30,C2CP_REACTOME_COLLAGEN_CHAIN_TRIMERIZATION,0.853627,6.856006e-03
12,LV30,C2CP_PID_INTEGRIN4_PATHWAY,0.947725,7.347583e-02
13,LV30,C2CP_REACTOME_DS_GAG_BIOSYNTHESIS,0.944775,7.561221e-02
14,LV568,C2CP_REACTOME_ACTIVATION_OF_THE_TFAP2_AP_2_FAMILY_OF_TRANSCRIPTION_FACTORS,0.938314,7.504429e-02
15,LV568,C2CP_WP_ESTROGEN_METABOLISM_WP697,0.853523,7.900415e-02
16,LV63,C2CP_REACTOME_REGULATION_OF_MITF_M_DEPENDENT_GENES_INVOLVED_IN_LYSOSOME_BIOGENESIS_AND_AUTOPHAGY,0.958247,2.695306e-02
17,LV63,C2CP_KEGG_MEDICUS_REFERENCE_COPI_VESICLE_FORMATION,0.893609,2.861171e-02
18,LV990,C2CP_REACTOME_FORMATION_OF_THE_URETERIC_BUD,1.000000,1.985729e-02
19,LV990,C2CP_REACTOME_KIDNEY_DEVELOPMENT,0.789378,4.710126e-02

In [55]:
testis_pathways

,LV,pathway,AUC,FDR
0,LV100,C2CP_KEGG_MEDICUS_REFERENCE_TCR_PLCG_ITPR_SIGNALING_PATHWAY,0.943106,3.503176e-02
1,LV100,C2CP_WP_REGULATION_OF_CYTOTOXIC_T_CELL_RESPONSES_BY_MALAT1_MIR1516_CIRCUIT,0.991172,5.686918e-02
2,LV1028,C2CP_WP_METHIONINE_METABOLISM_LEADING_TO_SULFUR_AMINO_ACIDS_AND_RELATED_DISORDERS,0.963774,7.144923e-02
3,LV1259,C2CP_REACTOME_SYNTHESIS_OF_GLYCOSYLPHOSPHATIDYLINOSITOL_GPI,0.954780,3.542061e-02
4,LV1259,C2CP_BIOCARTA_ATRBRCA_PATHWAY,0.872571,5.031171e-02
5,LV1271,C2CP_PID_INTEGRIN3_PATHWAY,0.786049,2.474244e-02
6,LV1271,C2CP_WP_OSTEOBLAST_SIGNALING,0.998034,5.621459e-02
7,LV1271,C2CP_REACTOME_DISSOLUTION_OF_FIBRIN_CLOT,0.960982,6.852737e-02
8,LV1271,C2CP_BIOCARTA_PLATELETAPP_PATHWAY,0.959262,6.962403e-02
9,LV1483,C2CP_KEGG_MEDICUS_REFERENCE_LOADING_OF_THE_SMC5_SMC6_COMPLEX,0.971932,6.890285e-02
10,LV1594,C2CP_REACTOME_MRNA_SPLICING,0.782896,5.264914e-09
11,LV30,C2CP_REACTOME_COLLAGEN_CHAIN_TRIMERIZATION,0.853627,6.856006e-03
12,LV30,C2CP_PID_INTEGRIN4_PATHWAY,0.947725,7.347583e-02
13,LV30,C2CP_REACTOME_DS_GAG_BIOSYNTHESIS,0.944775,7.561221e-02
14,LV568,C2CP_REACTOME_ACTIVATION_OF_THE_TFAP2_AP_2_FAMILY_OF_TRANSCRIPTION_FACTORS,0.938314,7.504429e-02
15,LV568,C2CP_WP_ESTROGEN_METABOLISM_WP697,0.853523,7.900415e-02
16,LV63,C2CP_REACTOME_REGULATION_OF_MITF_M_DEPENDENT_GENES_INVOLVED_IN_LYSOSOME_BIOGENESIS_AND_AUTOPHAGY,0.958247,2.695306e-02
17,LV63,C2CP_KEGG_MEDICUS_REFERENCE_COPI_VESICLE_FORMATION,0.893609,2.861171e-02
18,LV990,C2CP_REACTOME_FORMATION_OF_THE_URETERIC_BUD,1.000000,1.985729e-02
19,LV990,C2CP_REACTOME_KIDNEY_DEVELOPMENT,0.789378,4.710126e-02

In [56]:
thyroid_pathways = analyze("Thyroid", "thyroid")

────────────────────────────────────────────────────────────────
  Thyroid  (keyword: 'thyroid')  |  samples in model: 730
  Expected in top 1%: 7.3  |  Selected LVs: 46

,LV,n_in_top1pct,enrich_ratio,median_rank_pct,AUC,FDR
0,LV1379,98,13.425,0.4684,0.534016,4.548617e-03
1,LV1584,74,10.137,0.4116,0.572724,4.676374e-10
2,LV824,69,9.452,0.4049,0.555848,1.940397e-06
3,LV1198,47,6.439,0.4350,0.538232,1.343598e-03
4,LV122,46,6.302,0.4645,0.528860,1.719018e-02
5,LV669,37,5.069,0.3650,0.588286,2.557595e-14
6,LV910,37,5.069,0.4695,0.534281,4.266444e-03
7,LV626,33,4.521,0.4523,0.561625,1.445480e-07
8,LV300,32,4.384,0.4587,0.534916,3.597841e-03
9,LV993,31,4.247,0.4237,0.549571,2.485281e-05
10,LV872,30,4.110,0.4316,0.550712,1.728448e-05
11,LV107,30,4.110,0.4262,0.550159,2.070457e-05
12,LV582,28,3.836,0.3764,0.570287,1.756789e-09
13,LV813,28,3.836,0.3879,0.567657,6.482005e-09
14,LV1367,27,3.699,0.4551,0.536128,2.552115e-03
15,LV1558,27,3.699,0.4798,0.525440,3.625251e-02
16,LV255,26,3.562,0.4544,0.535941,2.656679e-03
17,LV1035,26,3.562,0.4987,0.525904,3.324493e-02
18,LV164,26,3.562,0.4013,0.569105,3.388998e-09
19,LV182,26,3.562,0.4088,0.568338,4.563074e-09
20,LV1344,26,3.562,0.4676,0.526036,3.221473e-02
21,LV1718,26,3.562,0.4441,0.534390,4.155085e-03
22,LV519,26,3.562,0.4302,0.543601,2.252304e-04
23,LV443,26,3.562,0.4360,0.545909,9.776861e-05
24,LV407,25,3.425,0.3737,0.580621,3.658320e-12
25,LV352,24,3.288,0.4567,0.534994,3.532071e-03
26,LV57,24,3.288,0.4466,0.534052,4.514155e-03
27,LV1351,24,3.288,0.4606,0.530425,1.159497e-02
28,LV144,24,3.288,0.4583,0.530944,1.028701e-02
29,LV246,23,3.151,0.3830,0.570690,1.421940e-09
30,LV449,23,3.151,0.4060,0.555016,2.802280e-06
31,LV224,23,3.151,0.4620,0.529991,1.292478e-02
32,LV991,23,3.151,0.3869,0.574525,1.599526e-10
33,LV1321,22,3.014,0.4298,0.546422,8.347238e-05
34,LV1350,22,3.014,0.4534,0.539710,8.502820e-04
35,LV1359,22,3.014,0.4622,0.545494,1.140788e-04
36,LV555,22,3.014,0.4618,0.539143,1.007978e-03
37,LV1364,21,2.877,0.4176,0.546577,7.871759e-05
38,LV1274,21,2.877,0.4480,0.546323,8.560159e-05
39,LV1614,21,2.877,0.4474,0.537456,1.695108e-03
40,LV1667,21,2.877,0.4643,0.530503,1.136482e-02
41,LV1404,21,2.877,0.4440,0.564216,3.896182e-08
42,LV346,21,2.877,0.4792,0.536389,2.363034e-03
43,LV40,21,2.877,0.3578,0.588368,2.557595e-14
44,LV577,20,2.740,0.4669,0.529115,1.623225e-02
45,LV1130,20,2.740,0.4203,0.545116,1.310619e-04

  Pathways:

,LV,pathway,AUC,FDR
0,LV107,C2CP_BIOCARTA_PCAF_PATHWAY,0.943891,7.657923e-02
1,LV107,C2CP_KEGG_MEDICUS_REFERENCE_N_GLYCAN_BIOSYNTHESIS,0.847796,8.908425e-02
2,LV1198,C2CP_PID_TOLL_ENDOGENOUS_PATHWAY,0.944938,1.308568e-02
3,LV1198,C2CP_REACTOME_NUCLEOTIDE_LIKE_PURINERGIC_RECEPTORS,0.942841,8.164208e-02
4,LV1404,C2CP_WP_T_CELL_MODULATION_AND_DESMOPLASIA_IN_PANCREATIC_CANCER,0.791943,1.194679e-02
5,LV1404,C2CP_WP_EXTRAFOLLICULAR_AND_FOLLICULAR_B_CELL_ACTIVATION_BY_SARSCOV2,0.718821,4.876198e-02
6,LV1404,C2CP_WP_LUPUS_PATHOGENESIS,1.000000,5.904476e-02
7,LV144,C2CP_WP_BMP2WNT4FOXO1_PATHWAY_IN_PRIMARY_ENDOMETRIAL_STROMAL_CELL_DIFFERENTIATION,0.917308,9.781409e-02
8,LV1614,C2CP_REACTOME_DS_GAG_BIOSYNTHESIS,0.997765,5.808118e-02
9,LV1667,C2CP_BIOCARTA_PLATELETAPP_PATHWAY,0.964891,5.895727e-02
10,LV1718,C2CP_BIOCARTA_PLATELETAPP_PATHWAY,0.999837,4.956140e-02
11,LV246,C2CP_REACTOME_CD22_MEDIATED_BCR_REGULATION,0.980485,9.085059e-06
12,LV246,C2CP_REACTOME_ROLE_OF_LAT2_NTAL_LAB_ON_CALCIUM_MOBILIZATION,0.925382,1.526822e-05
13,LV246,C2CP_REACTOME_INITIAL_TRIGGERING_OF_COMPLEMENT,0.904864,4.452524e-05
14,LV246,C2CP_REACTOME_CREATION_OF_C4_AND_C2_ACTIVATORS,0.892864,2.038217e-04
15,LV246,C2CP_REACTOME_FCGR_ACTIVATION,0.867523,6.010797e-04
16,LV246,C2CP_REACTOME_SCAVENGING_OF_HEME_FROM_PLASMA,0.842587,1.703368e-03
17,LV246,C2CP_REACTOME_ANTIGEN_ACTIVATES_B_CELL_RECEPTOR_BCR_LEADING_TO_GENERATION_OF_SECOND_MESSENGERS,0.769875,4.079762e-03
18,LV246,C2CP_REACTOME_FCERI_MEDIATED_CA_2_MOBILIZATION,0.748688,9.415429e-03
19,LV246,C2CP_REACTOME_ROLE_OF_PHOSPHOLIPIDS_IN_PHAGOCYTOSIS,0.730308,2.291280e-02
20,LV255,C2CP_BIOCARTA_IL17_PATHWAY,0.997601,5.532236e-02
21,LV255,C2CP_WP_REGULATION_OF_CYTOTOXIC_T_CELL_RESPONSES_BY_MALAT1_MIR1516_CIRCUIT,0.992367,5.633647e-02
22,LV300,C2CP_WP_DENGUE2_INTERACTIONS_WITH_COMPLEMENT_AND_COAGULATION_CASCADES,0.966306,3.316403e-05
23,LV300,C2CP_KEGG_COMPLEMENT_AND_COAGULATION_CASCADES,0.940614,3.539731e-05
24,LV300,C2CP_REACTOME_FORMATION_OF_FIBRIN_CLOT_CLOTTING_CASCADE,0.934612,7.778283e-03
25,LV300,C2CP_REACTOME_COMMON_PATHWAY_OF_FIBRIN_CLOT_FORMATION,1.000000,2.029828e-02
26,LV346,C2CP_KEGG_MEDICUS_REFERENCE_AUTOPHAGY_VESICLE_NUCLEATION_ELONGATION_MATURATION_PI3P_SYNTHESIS_BY_PI3KC3_C1,0.958549,7.325982e-02
27,LV352,C2CP_KEGG_MEDICUS_VARIANT_MLL_ENL_FUSION_TO_TRANSCRIPTIONAL_ACTIVATION,0.948266,7.912769e-02
28,LV352,C2CP_REACTOME_GRB2_EVENTS_IN_ERBB2_SIGNALING,0.929178,9.195666e-02
29,LV40,C2CP_REACTOME_IMMUNOREGULATORY_INTERACTIONS_BETWEEN_A_LYMPHOID_AND_A_NON_LYMPHOID_CELL,0.820764,2.246799e-08
30,LV40,C2CP_REACTOME_FCGR_ACTIVATION,0.988473,1.569137e-06
31,LV40,C2CP_REACTOME_ROLE_OF_PHOSPHOLIPIDS_IN_PHAGOCYTOSIS,0.919664,2.887393e-06
32,LV40,C2CP_REACTOME_CREATION_OF_C4_AND_C2_ACTIVATORS,0.917852,7.071167e-05
33,LV40,C2CP_REACTOME_CD22_MEDIATED_BCR_REGULATION,0.912113,2.392749e-04
34,LV40,C2CP_REACTOME_SCAVENGING_OF_HEME_FROM_PLASMA,0.829874,2.994012e-03
35,LV40,C2CP_REACTOME_ANTIGEN_ACTIVATES_B_CELL_RECEPTOR_BCR_LEADING_TO_GENERATION_OF_SECOND_MESSENGERS,0.777689,3.134871e-03
36,LV40,C2CP_REACTOME_COMPLEMENT_CASCADE,0.753977,4.064108e-03
37,LV626,C2CP_BIOCARTA_LAIR_PATHWAY,1.000000,1.393060e-02
38,LV626,C2CP_WP_CELLS_AND_MOLECULES_INVOLVED_IN_LOCAL_ACUTE_INFLAMMATORY_RESPONSE,1.000000,1.393060e-02
39,LV626,C2CP_BIOCARTA_NO2IL12_PATHWAY,0.998176,5.495029e-02
40,LV813,C2CP_REACTOME_BASIGIN_INTERACTIONS,0.913020,1.828997e-02
41,LV813,C2CP_WP_GENES_CONTROLLING_NEPHROGENESIS,0.738999,5.819287e-02
42,LV813,C2CP_PID_INTEGRIN4_PATHWAY,0.975825,5.873577e-02
43,LV813,C2CP_REACTOME_RESPONSE_TO_METAL_IONS,0.930591,8.164208e-02
44,LV824,C2CP_REACTOME_DEGRADATION_OF_CRY_AND_PER_PROTEINS,0.966348,3.033154e-05
45,LV824,C2CP_KEGG_MEDICUS_VARIANT_MUTATION_CAUSED_ABERRANT_SNCA_TO_26S_PROTEASOME_MEDIATED_PROTEIN_DEGRADATION,0.957231,4.288396e-04
46,LV824,C2CP_KEGG_MEDICUS_VARIANT_MUTATION_CAUSED_ABERRANT_ABETA_TO_26S_PROTEASOME_MEDIATED_PROTEIN_DEGRADATION,0.920106,1.610097e-03
47,LV824,C2CP_REACTOME_VIF_MEDIATED_DEGRADATION_OF_APOBEC3G,0.892526,1.627312e-03
48,LV824,C2CP_KEGG_MEDICUS_VARIANT_MUTATION_INACTIVATED_UBQLN2_TO_26S_PROTEASOME_MEDIATED_PROTEIN_DEGRADATION,0.914625,1.893348e-03
49,LV872,C2CP_KEGG_MEDICUS_PATHOGEN_HPV_E6_TO_NOTCH_SIGNALING_PATHWAY_N00380,0.986533,5.756743e-02
50,LV991,C2CP_BIOCARTA_NUCLEARRS_PATHWAY,0.948567,1.585213e-02

In [57]:
thyroid_pathways

,LV,pathway,AUC,FDR
0,LV107,C2CP_BIOCARTA_PCAF_PATHWAY,0.943891,7.657923e-02
1,LV107,C2CP_KEGG_MEDICUS_REFERENCE_N_GLYCAN_BIOSYNTHESIS,0.847796,8.908425e-02
2,LV1198,C2CP_PID_TOLL_ENDOGENOUS_PATHWAY,0.944938,1.308568e-02
3,LV1198,C2CP_REACTOME_NUCLEOTIDE_LIKE_PURINERGIC_RECEPTORS,0.942841,8.164208e-02
4,LV1404,C2CP_WP_T_CELL_MODULATION_AND_DESMOPLASIA_IN_PANCREATIC_CANCER,0.791943,1.194679e-02
5,LV1404,C2CP_WP_EXTRAFOLLICULAR_AND_FOLLICULAR_B_CELL_ACTIVATION_BY_SARSCOV2,0.718821,4.876198e-02
6,LV1404,C2CP_WP_LUPUS_PATHOGENESIS,1.000000,5.904476e-02
7,LV144,C2CP_WP_BMP2WNT4FOXO1_PATHWAY_IN_PRIMARY_ENDOMETRIAL_STROMAL_CELL_DIFFERENTIATION,0.917308,9.781409e-02
8,LV1614,C2CP_REACTOME_DS_GAG_BIOSYNTHESIS,0.997765,5.808118e-02
9,LV1667,C2CP_BIOCARTA_PLATELETAPP_PATHWAY,0.964891,5.895727e-02
10,LV1718,C2CP_BIOCARTA_PLATELETAPP_PATHWAY,0.999837,4.956140e-02
11,LV246,C2CP_REACTOME_CD22_MEDIATED_BCR_REGULATION,0.980485,9.085059e-06
12,LV246,C2CP_REACTOME_ROLE_OF_LAT2_NTAL_LAB_ON_CALCIUM_MOBILIZATION,0.925382,1.526822e-05
13,LV246,C2CP_REACTOME_INITIAL_TRIGGERING_OF_COMPLEMENT,0.904864,4.452524e-05
14,LV246,C2CP_REACTOME_CREATION_OF_C4_AND_C2_ACTIVATORS,0.892864,2.038217e-04
15,LV246,C2CP_REACTOME_FCGR_ACTIVATION,0.867523,6.010797e-04
16,LV246,C2CP_REACTOME_SCAVENGING_OF_HEME_FROM_PLASMA,0.842587,1.703368e-03
17,LV246,C2CP_REACTOME_ANTIGEN_ACTIVATES_B_CELL_RECEPTOR_BCR_LEADING_TO_GENERATION_OF_SECOND_MESSENGERS,0.769875,4.079762e-03
18,LV246,C2CP_REACTOME_FCERI_MEDIATED_CA_2_MOBILIZATION,0.748688,9.415429e-03
19,LV246,C2CP_REACTOME_ROLE_OF_PHOSPHOLIPIDS_IN_PHAGOCYTOSIS,0.730308,2.291280e-02
20,LV255,C2CP_BIOCARTA_IL17_PATHWAY,0.997601,5.532236e-02
21,LV255,C2CP_WP_REGULATION_OF_CYTOTOXIC_T_CELL_RESPONSES_BY_MALAT1_MIR1516_CIRCUIT,0.992367,5.633647e-02
22,LV300,C2CP_WP_DENGUE2_INTERACTIONS_WITH_COMPLEMENT_AND_COAGULATION_CASCADES,0.966306,3.316403e-05
23,LV300,C2CP_KEGG_COMPLEMENT_AND_COAGULATION_CASCADES,0.940614,3.539731e-05
24,LV300,C2CP_REACTOME_FORMATION_OF_FIBRIN_CLOT_CLOTTING_CASCADE,0.934612,7.778283e-03
25,LV300,C2CP_REACTOME_COMMON_PATHWAY_OF_FIBRIN_CLOT_FORMATION,1.000000,2.029828e-02
26,LV346,C2CP_KEGG_MEDICUS_REFERENCE_AUTOPHAGY_VESICLE_NUCLEATION_ELONGATION_MATURATION_PI3P_SYNTHESIS_BY_PI3KC3_C1,0.958549,7.325982e-02
27,LV352,C2CP_KEGG_MEDICUS_VARIANT_MLL_ENL_FUSION_TO_TRANSCRIPTIONAL_ACTIVATION,0.948266,7.912769e-02
28,LV352,C2CP_REACTOME_GRB2_EVENTS_IN_ERBB2_SIGNALING,0.929178,9.195666e-02
29,LV40,C2CP_REACTOME_IMMUNOREGULATORY_INTERACTIONS_BETWEEN_A_LYMPHOID_AND_A_NON_LYMPHOID_CELL,0.820764,2.246799e-08
30,LV40,C2CP_REACTOME_FCGR_ACTIVATION,0.988473,1.569137e-06
31,LV40,C2CP_REACTOME_ROLE_OF_PHOSPHOLIPIDS_IN_PHAGOCYTOSIS,0.919664,2.887393e-06
32,LV40,C2CP_REACTOME_CREATION_OF_C4_AND_C2_ACTIVATORS,0.917852,7.071167e-05
33,LV40,C2CP_REACTOME_CD22_MEDIATED_BCR_REGULATION,0.912113,2.392749e-04
34,LV40,C2CP_REACTOME_SCAVENGING_OF_HEME_FROM_PLASMA,0.829874,2.994012e-03
35,LV40,C2CP_REACTOME_ANTIGEN_ACTIVATES_B_CELL_RECEPTOR_BCR_LEADING_TO_GENERATION_OF_SECOND_MESSENGERS,0.777689,3.134871e-03
36,LV40,C2CP_REACTOME_COMPLEMENT_CASCADE,0.753977,4.064108e-03
37,LV626,C2CP_BIOCARTA_LAIR_PATHWAY,1.000000,1.393060e-02
38,LV626,C2CP_WP_CELLS_AND_MOLECULES_INVOLVED_IN_LOCAL_ACUTE_INFLAMMATORY_RESPONSE,1.000000,1.393060e-02
39,LV626,C2CP_BIOCARTA_NO2IL12_PATHWAY,0.998176,5.495029e-02
40,LV813,C2CP_REACTOME_BASIGIN_INTERACTIONS,0.913020,1.828997e-02
41,LV813,C2CP_WP_GENES_CONTROLLING_NEPHROGENESIS,0.738999,5.819287e-02
42,LV813,C2CP_PID_INTEGRIN4_PATHWAY,0.975825,5.873577e-02
43,LV813,C2CP_REACTOME_RESPONSE_TO_METAL_IONS,0.930591,8.164208e-02
44,LV824,C2CP_REACTOME_DEGRADATION_OF_CRY_AND_PER_PROTEINS,0.966348,3.033154e-05
45,LV824,C2CP_KEGG_MEDICUS_VARIANT_MUTATION_CAUSED_ABERRANT_SNCA_TO_26S_PROTEASOME_MEDIATED_PROTEIN_DEGRADATION,0.957231,4.288396e-04
46,LV824,C2CP_KEGG_MEDICUS_VARIANT_MUTATION_CAUSED_ABERRANT_ABETA_TO_26S_PROTEASOME_MEDIATED_PROTEIN_DEGRADATION,0.920106,1.610097e-03
47,LV824,C2CP_REACTOME_VIF_MEDIATED_DEGRADATION_OF_APOBEC3G,0.892526,1.627312e-03
48,LV824,C2CP_KEGG_MEDICUS_VARIANT_MUTATION_INACTIVATED_UBQLN2_TO_26S_PROTEASOME_MEDIATED_PROTEIN_DEGRADATION,0.914625,1.893348e-03
49,LV872,C2CP_KEGG_MEDICUS_PATHOGEN_HPV_E6_TO_NOTCH_SIGNALING_PATHWAY_N00380,0.986533,5.756743e-02
50,LV991,C2CP_BIOCARTA_NUCLEARRS_PATHWAY,0.948567,1.585213e-02

In [58]:
uterus_pathways = analyze("Uterus", "uterus")

────────────────────────────────────────────────────────────────
  Uterus  (keyword: 'uterus')  |  samples in model: 254
  Expected in top 1%: 2.5  |  Selected LVs: 19

,LV,n_in_top1pct,enrich_ratio,median_rank_pct,AUC,FDR
0,LV154,77,30.316,0.3366,0.636424,2.515271e-13
1,LV1137,76,29.922,0.2762,0.632052,1.391847e-12
2,LV222,71,27.953,0.1779,0.700933,2.666745e-27
3,LV1591,62,24.410,0.2079,0.666540,3.418694e-19
4,LV378,51,20.079,0.2256,0.694528,1.174200e-25
5,LV348,42,16.536,0.4383,0.590598,1.374396e-06
6,LV58,37,14.567,0.4166,0.587374,3.244134e-06
7,LV347,36,14.174,0.2016,0.646273,3.976953e-15
8,LV587,35,13.780,0.3252,0.654383,1.080231e-16
9,LV492,31,12.205,0.3425,0.600901,7.215632e-08
10,LV203,31,12.205,0.0366,0.715566,4.332419e-31
11,LV170,30,11.811,0.4945,0.549470,9.913249e-03
12,LV1367,28,11.024,0.4531,0.568062,3.253253e-04
13,LV713,27,10.630,0.1660,0.700489,3.428319e-27
14,LV1180,25,9.843,0.1880,0.690226,1.358379e-24
15,LV177,24,9.449,0.3575,0.612120,2.031892e-09
16,LV307,23,9.055,0.2121,0.679595,4.442179e-22
17,LV65,22,8.662,0.4115,0.591448,1.085586e-06
18,LV1177,20,7.874,0.3107,0.609697,4.580162e-09

  Pathways:

,LV,pathway,AUC,FDR
0,LV1177,C2CP_WP_CHOLESTASIS,0.913228,0.054950
1,LV1177,C2CP_WP_DRUG_INDUCTION_OF_BILE_ACID_PATHWAY,1.000000,0.056056
2,LV1180,C2CP_WP_GPCRS_CLASS_B_SECRETINLIKE,0.984452,0.058237
3,LV1180,C2CP_REACTOME_REVERSIBLE_HYDRATION_OF_CARBON_DIOXIDE,0.953410,0.071449
4,LV1180,C2CP_WP_KYNURENINE_PATHWAY_AND_LINKS_TO_CELL_SENESCENCE,0.793972,0.097634
5,LV154,C2CP_REACTOME_LYSINE_CATABOLISM,0.917719,0.086049
6,LV177,C2CP_REACTOME_HEME_BIOSYNTHESIS,0.996484,0.054850
7,LV307,C2CP_WP_TYPE_II_INTERFERON_SIGNALING,0.852473,0.013298
8,LV307,C2CP_BIOCARTA_CLASSIC_PATHWAY,0.983400,0.056869
9,LV492,C2CP_REACTOME_ERYTHROCYTES_TAKE_UP_CARBON_DIOXIDE_AND_RELEASE_OXYGEN,0.998097,0.049667
10,LV492,C2CP_WP_HEMOGLOBIN_SWITCHING_EMBRYONIC_FETAL_AND_ADULT,0.982386,0.055862
11,LV65,C2CP_KEGG_MEDICUS_PATHOGEN_HTLV_1_TAX_TO_NFY_MEDIATED_TRANSCRIPTION,0.861582,0.079608

In [59]:
uterus_pathways

,LV,pathway,AUC,FDR
0,LV1177,C2CP_WP_CHOLESTASIS,0.913228,0.054950
1,LV1177,C2CP_WP_DRUG_INDUCTION_OF_BILE_ACID_PATHWAY,1.000000,0.056056
2,LV1180,C2CP_WP_GPCRS_CLASS_B_SECRETINLIKE,0.984452,0.058237
3,LV1180,C2CP_REACTOME_REVERSIBLE_HYDRATION_OF_CARBON_DIOXIDE,0.953410,0.071449
4,LV1180,C2CP_WP_KYNURENINE_PATHWAY_AND_LINKS_TO_CELL_SENESCENCE,0.793972,0.097634
5,LV154,C2CP_REACTOME_LYSINE_CATABOLISM,0.917719,0.086049
6,LV177,C2CP_REACTOME_HEME_BIOSYNTHESIS,0.996484,0.054850
7,LV307,C2CP_WP_TYPE_II_INTERFERON_SIGNALING,0.852473,0.013298
8,LV307,C2CP_BIOCARTA_CLASSIC_PATHWAY,0.983400,0.056869
9,LV492,C2CP_REACTOME_ERYTHROCYTES_TAKE_UP_CARBON_DIOXIDE_AND_RELEASE_OXYGEN,0.998097,0.049667
10,LV492,C2CP_WP_HEMOGLOBIN_SWITCHING_EMBRYONIC_FETAL_AND_ADULT,0.982386,0.055862
11,LV65,C2CP_KEGG_MEDICUS_PATHOGEN_HTLV_1_TAX_TO_NFY_MEDIATED_TRANSCRIPTION,0.861582,0.079608

In [60]:
vagina_pathways = analyze("Vagina", "vagina")

────────────────────────────────────────────────────────────────
  Vagina  (keyword: 'vagina')  |  samples in model: 167
  Expected in top 1%: 1.7  |  Selected LVs: 9

       LV  n_in_top1pct  enrich_ratio  median_rank_pct       AUC           FDR
0   LV111            33        19.761           0.3608  0.577297  1.353735e-03
1  LV1409            33        19.761           0.4637  0.579587  9.653585e-04
2   LV697            31        18.563           0.2007  0.693621  3.209655e-16
3   LV919            30        17.964           0.2507  0.682524  1.668792e-14
4  LV1608            29        17.366           0.2262  0.657856  4.318099e-11
5   LV302            26        15.569           0.3820  0.627720  8.194049e-08
6   LV228            25        14.970           0.4234  0.599691  3.186639e-05
7  LV1113            22        13.174           0.2073  0.682706  1.663747e-14
8   LV926            21        12.575           0.2462  0.673960  2.481900e-13

  Pathways:

,LV,pathway,AUC,FDR
0,LV1113,C2CP_REACTOME_CD22_MEDIATED_BCR_REGULATION,0.913083,0.000215
1,LV1113,C2CP_REACTOME_CREATION_OF_C4_AND_C2_ACTIVATORS,0.843735,0.001656
2,LV1113,C2CP_REACTOME_ROLE_OF_LAT2_NTAL_LAB_ON_CALCIUM_MOBILIZATION,0.715548,0.056336
3,LV1113,C2CP_REACTOME_SCAVENGING_OF_HEME_FROM_PLASMA,0.717561,0.060492
4,LV1608,C2CP_KEGG_PRIMARY_BILE_ACID_BIOSYNTHESIS,0.997442,0.050150
5,LV302,C2CP_KEGG_MEDICUS_VARIANT_SCRAPIE_CONFORMATION_PRPSC_TO_26S_PROTEASOME_MEDIATED_PROTEIN_DEGRADATION,0.981859,0.000043
6,LV302,C2CP_KEGG_MEDICUS_VARIANT_MUTATION_CAUSED_ABERRANT_ABETA_TO_26S_PROTEASOME_MEDIATED_PROTEIN_DEGRADATION,0.967561,0.000081
7,LV302,C2CP_KEGG_MEDICUS_VARIANT_MUTATION_CAUSED_ABERRANT_SOD1_TO_26S_PROTEASOME_MEDIATED_PROTEIN_DEGRADATION,0.876920,0.000984
8,LV302,C2CP_KEGG_PROTEASOME,0.852715,0.002513
9,LV302,C2CP_KEGG_MEDICUS_VARIANT_MUTATION_INACTIVATED_VCP_TO_26S_PROTEASOME_MEDIATED_PROTEIN_DEGRADATION,0.876941,0.002513
10,LV302,C2CP_REACTOME_REGULATION_OF_ORNITHINE_DECARBOXYLASE_ODC,0.859687,0.004383
11,LV697,C2CP_REACTOME_FIBRONECTIN_MATRIX_FORMATION,1.000000,0.003764
12,LV926,C2CP_REACTOME_CYTOCHROME_P450_ARRANGED_BY_SUBSTRATE_TYPE,0.930527,0.000379
13,LV926,C2CP_REACTOME_PHASE_I_FUNCTIONALIZATION_OF_COMPOUNDS,0.738264,0.012145
14,LV926,C2CP_REACTOME_ASPIRIN_ADME,0.978717,0.026862

In [61]:
vagina_pathways

,LV,pathway,AUC,FDR
0,LV1113,C2CP_REACTOME_CD22_MEDIATED_BCR_REGULATION,0.913083,0.000215
1,LV1113,C2CP_REACTOME_CREATION_OF_C4_AND_C2_ACTIVATORS,0.843735,0.001656
2,LV1113,C2CP_REACTOME_ROLE_OF_LAT2_NTAL_LAB_ON_CALCIUM_MOBILIZATION,0.715548,0.056336
3,LV1113,C2CP_REACTOME_SCAVENGING_OF_HEME_FROM_PLASMA,0.717561,0.060492
4,LV1608,C2CP_KEGG_PRIMARY_BILE_ACID_BIOSYNTHESIS,0.997442,0.050150
5,LV302,C2CP_KEGG_MEDICUS_VARIANT_SCRAPIE_CONFORMATION_PRPSC_TO_26S_PROTEASOME_MEDIATED_PROTEIN_DEGRADATION,0.981859,0.000043
6,LV302,C2CP_KEGG_MEDICUS_VARIANT_MUTATION_CAUSED_ABERRANT_ABETA_TO_26S_PROTEASOME_MEDIATED_PROTEIN_DEGRADATION,0.967561,0.000081
7,LV302,C2CP_KEGG_MEDICUS_VARIANT_MUTATION_CAUSED_ABERRANT_SOD1_TO_26S_PROTEASOME_MEDIATED_PROTEIN_DEGRADATION,0.876920,0.000984
8,LV302,C2CP_KEGG_PROTEASOME,0.852715,0.002513
9,LV302,C2CP_KEGG_MEDICUS_VARIANT_MUTATION_INACTIVATED_VCP_TO_26S_PROTEASOME_MEDIATED_PROTEIN_DEGRADATION,0.876941,0.002513
10,LV302,C2CP_REACTOME_REGULATION_OF_ORNITHINE_DECARBOXYLASE_ODC,0.859687,0.004383
11,LV697,C2CP_REACTOME_FIBRONECTIN_MATRIX_FORMATION,1.000000,0.003764
12,LV926,C2CP_REACTOME_CYTOCHROME_P450_ARRANGED_BY_SUBSTRATE_TYPE,0.930527,0.000379
13,LV926,C2CP_REACTOME_PHASE_I_FUNCTIONALIZATION_OF_COMPOUNDS,0.738264,0.012145
14,LV926,C2CP_REACTOME_ASPIRIN_ADME,0.978717,0.026862

In [62]:
whole_blood_pathways = analyze("Whole blood", "whole blood")

────────────────────────────────────────────────────────────────
  Whole blood  (keyword: 'whole blood')  |  samples in model: 13,094
  Expected in top 1%: 130.9  |  Selected LVs: 17

,LV,n_in_top1pct,enrich_ratio,median_rank_pct,AUC,FDR
0,LV147,360,2.749,0.4723,0.528077,4.416171e-27
1,LV127,319,2.436,0.4460,0.529464,1.149726e-29
2,LV1342,317,2.421,0.4875,0.507127,7.305645e-03
3,LV294,301,2.299,0.4667,0.528134,3.555649e-27
4,LV158,300,2.291,0.4883,0.513559,2.508816e-07
5,LV1290,299,2.284,0.4876,0.521207,5.026827e-16
6,LV1375,285,2.177,0.4622,0.530334,2.125829e-31
7,LV1362,276,2.108,0.4946,0.509669,2.596214e-04
8,LV480,276,2.108,0.4518,0.524976,9.213245e-22
9,LV1661,273,2.085,0.4754,0.526394,4.311146e-24
10,LV848,272,2.077,0.4956,0.507711,3.649069e-03
11,LV675,272,2.077,0.4902,0.507065,7.831623e-03
12,LV1121,269,2.054,0.4897,0.508626,1.134434e-03
13,LV410,269,2.054,0.4952,0.510315,9.637750e-05
14,LV27,268,2.047,0.4805,0.514206,6.357512e-08
15,LV1487,267,2.039,0.4852,0.508551,1.251701e-03
16,LV1174,265,2.024,0.4741,0.509549,3.099781e-04

  Pathways:

,LV,pathway,AUC,FDR
0,LV1174,C2CP_KEGG_MEDICUS_REFERENCE_HORMONE_LIKE_CYTOKINE_TO_JAK_STAT_SIGNALING_PATHWAY,0.945302,0.084957
1,LV127,C2CP_BIOCARTA_CLASSIC_PATHWAY,0.955657,0.069624
2,LV1342,C2CP_WP_OVERVIEW_OF_PROINFLAMMATORY_AND_PROFIBROTIC_MEDIATORS,0.737190,0.017584
3,LV1342,C2CP_WP_OVERVIEW_OF_NANOPARTICLE_EFFECTS,0.847604,0.093997
4,LV147,C2CP_REACTOME_SIRT1_NEGATIVELY_REGULATES_RRNA_EXPRESSION,0.673349,0.074990
5,LV1487,C2CP_REACTOME_ATTACHMENT_OF_BACTERIA_TO_EPITHELIAL_CELLS,0.807443,0.082372
6,LV1661,C2CP_REACTOME_TRANSPORT_OF_CONNEXONS_TO_THE_PLASMA_MEMBRANE,0.997554,0.020745
7,LV27,C2CP_REACTOME_DEVELOPMENTAL_LINEAGE_OF_MAMMARY_GLAND_LUMINAL_EPITHELIAL_CELLS,0.813456,0.079910
8,LV294,C2CP_REACTOME_SYNTHESIS_OF_PROSTAGLANDINS_PG_AND_THROMBOXANES_TX,0.998142,0.059390
9,LV410,C2CP_REACTOME_SYNTHESIS_OF_BILE_ACIDS_AND_BILE_SALTS_VIA_24_HYDROXYCHOLESTEROL,0.998609,0.054361

In [63]:
whole_blood_pathways

,LV,pathway,AUC,FDR
0,LV1174,C2CP_KEGG_MEDICUS_REFERENCE_HORMONE_LIKE_CYTOKINE_TO_JAK_STAT_SIGNALING_PATHWAY,0.945302,0.084957
1,LV127,C2CP_BIOCARTA_CLASSIC_PATHWAY,0.955657,0.069624
2,LV1342,C2CP_WP_OVERVIEW_OF_PROINFLAMMATORY_AND_PROFIBROTIC_MEDIATORS,0.737190,0.017584
3,LV1342,C2CP_WP_OVERVIEW_OF_NANOPARTICLE_EFFECTS,0.847604,0.093997
4,LV147,C2CP_REACTOME_SIRT1_NEGATIVELY_REGULATES_RRNA_EXPRESSION,0.673349,0.074990
5,LV1487,C2CP_REACTOME_ATTACHMENT_OF_BACTERIA_TO_EPITHELIAL_CELLS,0.807443,0.082372
6,LV1661,C2CP_REACTOME_TRANSPORT_OF_CONNEXONS_TO_THE_PLASMA_MEMBRANE,0.997554,0.020745
7,LV27,C2CP_REACTOME_DEVELOPMENTAL_LINEAGE_OF_MAMMARY_GLAND_LUMINAL_EPITHELIAL_CELLS,0.813456,0.079910
8,LV294,C2CP_REACTOME_SYNTHESIS_OF_PROSTAGLANDINS_PG_AND_THROMBOXANES_TX,0.998142,0.059390
9,LV410,C2CP_REACTOME_SYNTHESIS_OF_BILE_ACIDS_AND_BILE_SALTS_VIA_24_HYDROXYCHOLESTEROL,0.998609,0.054361

In [64]:
_tissue_dfs = {
    "Adipose":                 adipose_pathways,
    "Adrenal gland":           adrenal_gland_pathways,
    "Artery":                  artery_pathways,
    "Bladder":                 bladder_pathways,
    "Blood vessel":            blood_vessel_pathways,
    "Brain":                   brain_pathways,
    "Breast":                  breast_pathways,
    "Cervix":                  cervix_pathways,
    "Colon":                   colon_pathways,
    "Esophagus":               esophagus_pathways,
    "Heart":                   heart_pathways,
    "Kidney":                  kidney_pathways,
    "Liver":                   liver_pathways,
    "Lung":                    lung_pathways,
    "Muscle":                  muscle_pathways,
    "Nerve":                   nerve_pathways,
    "Ovary":                   ovary_pathways,
    "Pancreas":                pancreas_pathways,
    "Pituitary":               pituitary_pathways,
    "Prostate":                prostate_pathways,
    "Skin":                    skin_pathways,
    "Small intestine":         small_intestine_pathways,
    "Spleen":                  spleen_pathways,
    "Stomach":                 stomach_pathways,
    "Testis":                  testis_pathways,
    "Thyroid":                 thyroid_pathways,
    "Uterus":                  uterus_pathways,
    "Vagina":                  vagina_pathways,
    "Whole blood":             whole_blood_pathways,
}

_frames = [df.assign(tissue=t) for t, df in _tissue_dfs.items() if df is not None and not df.empty]
tissues_combined = pd.concat(_frames, ignore_index=True)[["tissue", "LV", "pathway", "AUC", "FDR"]]

_unique_mask = tissues_combined["pathway"].map(
    tissues_combined.groupby("pathway")["tissue"].nunique() == 1
)
tissues_unique = (
    tissues_combined[_unique_mask]
    .sort_values(["tissue", "FDR"])
    .reset_index(drop=True)
)

display(tissues_unique)

,tissue,LV,pathway,AUC,FDR
0,Adipose,LV262,C2CP_REACTOME_RESPONSE_OF_EIF2AK4_GCN2_TO_AMINO_ACID_DEFICIENCY,0.946340,5.910003e-11
1,Adipose,LV262,C2CP_REACTOME_SARS_COV_2_MODULATES_HOST_TRANSLATION_MACHINERY,0.921941,4.695374e-05
2,Adipose,LV262,C2CP_REACTOME_SARS_COV_1_MODULATES_HOST_TRANSLATION_MACHINERY,0.889413,3.134005e-03
3,Adipose,LV256,C2CP_REACTOME_DEVELOPMENTAL_LINEAGES_OF_THE_MAMMARY_GLAND,0.929677,3.142651e-03
4,Adipose,LV758,C2CP_WP_PROSTAGLANDIN_SYNTHESIS_AND_REGULATION,0.901514,3.169349e-03
5,Adipose,LV1286,C2CP_BIOCARTA_P53_PATHWAY,0.994411,1.676426e-02
6,Adipose,LV1599,C2CP_REACTOME_RHO_GTPASES_ACTIVATE_IQGAPS,0.894907,1.839603e-02
7,Adipose,LV73,C2CP_WP_LTF_DANGER_SIGNAL_RESPONSE_PATHWAY,0.982757,2.001041e-02
8,Adipose,LV1659,C2CP_REACTOME_METABOLISM_OF_PORPHYRINS,0.913650,2.315255e-02
9,Adipose,LV272,C2CP_KEGG_MEDICUS_REFERENCE_KEAP1_NRF2_SIGNALING_PATHWAY,0.895403,2.779711e-02
10,Adipose,LV1659,C2CP_REACTOME_FOXO_MEDIATED_TRANSCRIPTION_OF_CELL_CYCLE_GENES,0.936435,4.416023e-02
11,Adipose,LV1012,C2CP_REACTOME_ABC_TRANSPORTERS_IN_LIPID_HOMEOSTASIS,0.906881,5.141231e-02
12,Adipose,LV272,C2CP_WP_TRANSCRIPTIONAL_ACTIVATION_BY_NRF2_IN_RESPONSE_TO_PHYTOCHEMICALS,1.000000,5.513184e-02
13,Adipose,LV367,C2CP_BIOCARTA_GRANULOCYTES_PATHWAY,0.985683,5.586174e-02
14,Adipose,LV1286,C2CP_KEGG_MEDICUS_VARIANT_AMPLIFIED_MDM2_TO_P21_CELL_CYCLE_G1_S,1.000000,5.605625e-02
15,Adipose,LV1685,C2CP_REACTOME_P130CAS_LINKAGE_TO_MAPK_SIGNALING_FOR_INTEGRINS,0.991889,5.633647e-02
16,Adipose,LV137,C2CP_REACTOME_TYPE_I_HEMIDESMOSOME_ASSEMBLY,0.997759,5.640270e-02
17,Adipose,LV533,C2CP_KEGG_CIRCADIAN_RHYTHM_MAMMAL,1.000000,5.756743e-02
18,Adipose,LV1659,C2CP_BIOCARTA_HES_PATHWAY,0.992874,5.873577e-02
19,Adipose,LV359,C2CP_WP_MAMMARY_GLAND_DEVELOPMENT_PUBERTY_STAGE_2_OF_4,0.980010,5.953757e-02
20,Adipose,LV680,C2CP_PID_ERBB_NETWORK_PATHWAY,1.000000,6.017376e-02
21,Adipose,LV680,C2CP_REACTOME_ERBB2_ACTIVATES_PTK6_SIGNALING,1.000000,6.017376e-02
22,Adipose,LV680,C2CP_REACTOME_ERBB2_REGULATES_CELL_MOTILITY,1.000000,6.017376e-02
23,Adipose,LV729,C2CP_KEGG_MEDICUS_PATHOGEN_HPV_E6_TO_NOTCH_SIGNALING_PATHWAY_N00382,1.000000,6.017376e-02
24,Adipose,LV599,C2CP_WP_RETT_SYNDROME,0.728491,6.377020e-02
25,Adipose,LV1286,C2CP_BIOCARTA_HCMV_PATHWAY,0.880063,6.697323e-02
26,Adipose,LV648,C2CP_REACTOME_REGULATION_OF_FOXO_TRANSCRIPTIONAL_ACTIVITY_BY_ACETYLATION,0.953978,7.039529e-02
27,Adipose,LV1253,C2CP_KEGG_MEDICUS_REFERENCE_CXCR4_GNAQ_PLCB_G_CALCINEURIN_SIGNALING_PATHWAY,0.818197,7.144923e-02
28,Adipose,LV1012,C2CP_REACTOME_BUTYROPHILIN_BTN_FAMILY_INTERACTIONS,0.940989,7.283398e-02
29,Adipose,LV1286,C2CP_BIOCARTA_RB_PATHWAY,0.940767,8.163289e-02
30,Adipose,LV1611,C2CP_BIOCARTA_D4GDI_PATHWAY,0.916667,8.654483e-02
31,Adipose,LV1659,C2CP_REACTOME_SPECIFICATION_OF_THE_NEURAL_PLATE_BORDER,0.933514,9.041112e-02
32,Adipose,LV648,C2CP_PID_NFKAPPAB_ATYPICAL_PATHWAY,0.843827,9.210761e-02
33,Adipose,LV137,C2CP_PID_WNT_SIGNALING_PATHWAY,0.797860,9.665312e-02
34,Adipose,LV651,C2CP_BIOCARTA_CTL_PATHWAY,0.926250,9.781409e-02
35,Artery,LV44,C2CP_REACTOME_ERCC6_CSB_AND_EHMT2_G9A_POSITIVELY_REGULATE_RRNA_EXPRESSION,0.737431,1.615600e-02
36,Artery,LV1197,C2CP_KEGG_PHENYLALANINE_METABOLISM,0.898422,5.481384e-02
37,Artery,LV49,C2CP_BIOCARTA_VDR_PATHWAY,0.861366,5.633647e-02
38,Artery,LV689,C2CP_KEGG_MEDICUS_VARIANT_AMPLIFIED_EGFR_TO_PLCG_CAMK_SIGNALING_PATHWAY,0.994804,5.728160e-02
39,Artery,LV399,C2CP_REACTOME_ACYL_CHAIN_REMODELLING_OF_PG,1.000000,5.819287e-02
40,Artery,LV68,C2CP_BIOCARTA_HSWI_SNF_PATHWAY,0.972153,6.697323e-02
41,Artery,LV68,C2CP_REACTOME_REGULATION_OF_GENE_EXPRESSION_IN_LATE_STAGE_BRANCHING_MORPHOGENESIS_PANCREATIC_BUD_PRECURSOR_CELLS,0.969261,6.852737e-02
42,Bladder,LV546,C2CP_REACTOME_TIGHT_JUNCTION_INTERACTIONS,0.960726,9.819271e-03
43,Bladder,LV787,C2CP_REACTOME_ACYL_CHAIN_REMODELLING_OF_PS,0.991384,5.808118e-02
44,Bladder,LV546,C2CP_REACTOME_DEVELOPMENTAL_LINEAGE_OF_MAMMARY_GLAND_ALVEOLAR_CELLS,0.980924,6.151162e-02
45,Bladder,LV1519,C2CP_KEGG_MEDICUS_REFERENCE_ELECTRON_TRANSFER_IN_COMPLEX_III,0.982136,6.564056e-02
46,Bladder,LV1675,C2CP_WP_CAFFEINE_IN_MYOCYTES,0.797150,7.349155e-02
47,Brain,LV932,C2CP_REACTOME_GLYCOGEN_BREAKDOWN_GLYCOGENOLYSIS,0.914064,5.322060e-02
48,Brain,LV216,C2CP_REACTOME_FORMATION_OF_AXIAL_MESODERM,0.998093,5.523544e-02
49,Brain,LV1272,C2CP_KEGG_MEDICUS_REFERENCE_SKELETAL_TYPE_VGCC_RYR_SIGNALING,1.000000,6.070649e-02
50,Brain,LV1272,C2CP_REACTOME_PHASE_2_PLATEAU_PHASE,0.999973,6.070649e-02
51,Brain,LV1343,C2CP_REACTOME_INTERACTION_BETWEEN_L1_AND_ANKYRINS,0.829808,7.695794e-02
52,Breast,LV1091,C2CP_WP_CILIOPATHIES,0.854116,2.023145e-11
53,Breast,LV22,C2CP_WP_CILIOPATHIES,0.845144,1.117994e-10
54,Breast,LV1091,C2CP_WP_GENES_RELATED_TO_PRIMARY_CILIUM_DEVELOPMENT_BASED_ON_CRISPR,0.839100,1.530208e-06
55,Breast,LV1091,C2CP_REACTOME_INTRAFLAGELLAR_TRANSPORT,0.856616,1.655652e-03
56,Breast,LV734,C2CP_KEGG_MEDICUS_ENV_FACTOR_TCDD_TO_AHR_SIGNALING_PATHWAY,1.000000,1.834856e-02
57,Breast,LV739,C2CP_KEGG_GLYCOSPHINGOLIPID_BIOSYNTHESIS_LACTO_AND_NEOLACTO_SERIES,0.921836,2.309212e-02
58,Breast,LV739,C2CP_REACTOME_BLOOD_GROUP_SYSTEMS_BIOSYNTHESIS,0.967580,3.131583e-02
59,Breast,LV156,C2CP_REACTOME_REGULATION_OF_NPAS4_GENE_EXPRESSION,0.989290,6.100384e-02
60,Breast,LV156,C2CP_REACTOME_REGULATION_OF_MITF_M_DEPENDENT_GENES_INVOLVED_IN_APOPTOSIS,0.866391,8.326865e-02
61,Cervix,LV4,C2CP_REACTOME_MITOCHONDRIAL_TRANSLATION_ELONGATION,0.982674,3.491544e-10
62,Cervix,LV4,C2CP_REACTOME_MITOCHONDRIAL_TRANSLATION,0.866429,1.302586e-07
63,Cervix,LV62,C2CP_KEGG_MEDICUS_REFERENCE_MITOCHONDRIAL_COMPLEX_UCP1_IN_THERMOGENESIS,0.944173,1.053472e-06
64,Cervix,LV1269,C2CP_KEGG_MEDICUS_VARIANT_MUTATION_CAUSED_ABERRANT_HTT_TO_26S_PROTEASOME_MEDIATED_PROTEIN_DEGRADATION,0.999766,7.165267e-05
65,Cervix,LV1269,C2CP_KEGG_MEDICUS_REFERENCE_26S_PROTEASOME_MEDIATED_PROTEIN_DEGRADATION,0.972103,2.088242e-04
66,Cervix,LV4,C2CP_KEGG_MEDICUS_REFERENCE_MITOCHONDRIAL_COMPLEX_UCP1_IN_THERMOGENESIS,0.864713,2.615113e-04
67,Cervix,LV1269,C2CP_BIOCARTA_PROTEASOME_PATHWAY,0.999964,1.785997e-02
68,Cervix,LV1269,C2CP_WP_NSP1_FROM_SARSCOV2_INHIBITS_TRANSLATION_INITIATION_IN_THE_HOST_CELL,0.965509,3.008970e-02
69,Cervix,LV1607,C2CP_REACTOME_HEPARAN_SULFATE_HEPARIN_HS_GAG_METABOLISM,0.831488,3.008970e-02
70,Cervix,LV4,C2CP_WP_MITOCHONDRIAL_COMPLEX_IV_ASSEMBLY,0.835834,3.119430e-02
71,Cervix,LV719,C2CP_REACTOME_SYNAPTIC_ADHESION_LIKE_MOLECULES,0.900868,5.700133e-02
72,Cervix,LV96,C2CP_REACTOME_ESTABLISHMENT_OF_SISTER_CHROMATID_COHESION,0.971769,7.144923e-02
73,Cervix,LV1225,C2CP_KEGG_MEDICUS_REFERENCE_BMP_SIGNALING_PATHWAY,0.868451,7.187528e-02
74,Cervix,LV1305,C2CP_REACTOME_METABOLISM_OF_AMINE_DERIVED_HORMONES,0.928997,8.583220e-02
75,Cervix,LV1530,C2CP_KEGG_MEDICUS_REFERENCE_BLOCKING_UBIQUITINATION_OF_H2AK119_BY_CK2,0.941860,9.210761e-02
76,Cervix,LV4,C2CP_KEGG_MEDICUS_REFERENCE_26S_PROTEASOME_MEDIATED_PROTEIN_DEGRADATION,0.735601,9.611163e-02
77,Colon,LV520,C2CP_WP_22Q112_COPY_NUMBER_VARIATION_SYNDROME,0.695576,1.248701e-02
78,Esophagus,LV324,C2CP_REACTOME_COLLAGEN_FORMATION,0.852151,1.395395e-05
79,Esophagus,LV324,C2CP_REACTOME_COLLAGEN_BIOSYNTHESIS_AND_MODIFYING_ENZYMES,0.861339,3.340383e-04
80,Esophagus,LV879,C2CP_KEGG_AUTOIMMUNE_THYROID_DISEASE,0.999991,3.894095e-04
81,Esophagus,LV1365,C2CP_REACTOME_O_LINKED_GLYCOSYLATION,0.761779,5.595218e-04
82,Esophagus,LV330,C2CP_KEGG_CITRATE_CYCLE_TCA_CYCLE,0.979598,6.355925e-04
83,Esophagus,LV1542,C2CP_REACTOME_PHOSPHORYLATION_OF_CD3_AND_TCR_ZETA_CHAINS,0.984851,7.443848e-03
84,Esophagus,LV330,C2CP_WP_TCA_CYCLE_AKA_KREBS_OR_CITRIC_ACID_CYCLE,0.999346,9.166647e-03
85,Esophagus,LV879,C2CP_KEGG_ANTIGEN_PROCESSING_AND_PRESENTATION,0.766651,1.284769e-02
86,Esophagus,LV330,C2CP_WP_TCA_CYCLE_AND_DEFICIENCY_OF_PYRUVATE_DEHYDROGENASE_COMPLEX_PDHC,0.966233,1.644763e-02
87,Esophagus,LV733,C2CP_REACTOME_SIGNALING_BY_FLT3_ITD_AND_TKD_MUTANTS,0.959308,2.012805e-02
88,Esophagus,LV733,C2CP_SA_MMP_CYTOKINE_CONNECTION,0.958837,2.029828e-02
89,Esophagus,LV871,C2CP_WP_PEPTIDE_GPCRS,0.809123,2.596898e-02
90,Esophagus,LV1542,C2CP_KEGG_AUTOIMMUNE_THYROID_DISEASE,0.819936,4.011300e-02
91,Esophagus,LV330,C2CP_KEGG_MEDICUS_REFERENCE_CITRATE_CYCLE_SECOND_CARBON_OXIDATION_2,0.999809,4.221366e-02
92,Esophagus,LV640,C2CP_WP_GLUTATHIONE_METABOLISM,0.940051,4.992725e-02
93,Esophagus,LV330,C2CP_KEGG_MEDICUS_REFERENCE_ISOLEUCINE_DEGRADATION,0.984470,5.070175e-02
94,Esophagus,LV1365,C2CP_WP_MONOAMINE_GPCRS,1.000000,5.756743e-02
95,Esophagus,LV1702,C2CP_REACTOME_DECTIN_2_FAMILY,0.990210,5.919917e-02
96,Esophagus,LV1563,C2CP_BIOCARTA_MITOCHONDRIA_PATHWAY,0.890924,6.564056e-02
97,Esophagus,LV330,C2CP_WP_HOSTPATHOGEN_INTERACTION_OF_HUMAN_CORONAVIRUSES_APOPTOSIS,0.807361,6.852737e-02
98,Esophagus,LV640,C2CP_BIOCARTA_NKCELLS_PATHWAY,0.888609,7.154306e-02
99,Esophagus,LV880,C2CP_WP_2Q112_COPY_NUMBER_VARIATION_SYNDROME,0.760439,7.291649e-02
100,Esophagus,LV324,C2CP_PID_SYNDECAN_1_PATHWAY,0.715568,7.345468e-02
101,Esophagus,LV640,C2CP_WP_DEVELOPMENT_OF_PULMONARY_DENDRITIC_CELLS_AND_MACROPHAGE_SUBSETS,0.960843,8.072884e-02
102,Esophagus,LV149,C2CP_REACTOME_CS_DS_DEGRADATION,0.858506,8.731811e-02
103,Esophagus,LV324,C2CP_WP_TYPE_I_COLLAGEN_SYNTHESIS_IN_THE_CONTEXT_OF_OSTEOGENESIS_IMPERFECTA,0.772281,9.147147e-02
104,Esophagus,LV1657,C2CP_PID_CD40_PATHWAY,0.765746,9.669561e-02
105,Heart,LV686,C2CP_WP_OMEGA3FATTY_ACIDS_IN_SENESCENCE,0.952917,3.134871e-03
106,Heart,LV967,C2CP_WP_SIGNALING_LIPIDS,0.985629,4.965758e-03
107,Heart,LV578,C2CP_REACTOME_ECM_PROTEOGLYCANS,0.767134,1.083028e-02
108,Heart,LV1278,C2CP_REACTOME_CHROMATIN_MODIFICATIONS_DURING_THE_MATERNAL_TO_ZYGOTIC_TRANSITION_MZT,0.739040,1.429074e-02
109,Heart,LV105,C2CP_WP_SULFATION_BIOTRANSFORMATION_REACTION,0.996219,1.561410e-02
110,Heart,LV86,C2CP_REACTOME_CELL_EXTRACELLULAR_MATRIX_INTERACTIONS,0.989144,1.642194e-02
111,Heart,LV686,C2CP_WP_SIGNALING_LIPIDS,0.922378,1.758426e-02
112,Heart,LV119,C2CP_WP_NOTCH1_REGULATION_OF_ENDOTHELIAL_CELL_CALCIFICATION,0.991041,1.802303e-02
113,Heart,LV721,C2CP_REACTOME_CGMP_EFFECTS,1.000000,1.988485e-02
114,Heart,LV119,C2CP_WP_OLIGODENDROCYTE_DEVELOPMENT,0.801646,2.871627e-02
115,Heart,LV1433,C2CP_REACTOME_LAMININ_INTERACTIONS,0.818455,2.989234e-02
116,Heart,LV967,C2CP_WP_OMEGA3FATTY_ACIDS_IN_SENESCENCE,0.845075,3.406581e-02
117,Heart,LV1562,C2CP_WP_CELL_INTERACTIONS_IN_PANCREATIC_CANCER_MICROENVIRONMENT,0.833559,4.874676e-02
118,Heart,LV721,C2CP_REACTOME_NITRIC_OXIDE_STIMULATES_GUANYLATE_CYCLASE,0.874802,5.265413e-02
119,Heart,LV721,C2CP_REACTOME_ACTIVATION_OF_MATRIX_METALLOPROTEINASES,0.835106,5.274658e-02
120,Heart,LV808,C2CP_REACTOME_INTERLEUKIN_20_FAMILY_SIGNALING,0.922986,5.277268e-02
121,Heart,LV967,C2CP_WP_LEUKOTRIENE_METABOLIC_PATHWAY,0.995801,5.633647e-02
122,Heart,LV888,C2CP_WP_PATHOPHYSIOLOGICAL_ROLES_OF_DUX4_IN_FSHD1,0.983912,5.656717e-02
123,Heart,LV808,C2CP_BIOCARTA_IL10_PATHWAY,0.999946,5.728160e-02
124,Heart,LV214,C2CP_REACTOME_INTERLEUKIN_2_FAMILY_SIGNALING,0.764312,5.734513e-02
125,Heart,LV721,C2CP_KEGG_MEDICUS_PATHOGEN_EBV_EBNA3C_TO_P53_MEDIATED_TRANSCRIPTION,1.000000,5.962944e-02
126,Heart,LV643,C2CP_REACTOME_ASSEMBLY_OF_ACTIVE_LPL_AND_LIPC_LIPASE_COMPLEXES,0.988301,6.109260e-02
127,Heart,LV1562,C2CP_WP_COVID19_ADVERSE_OUTCOME_PATHWAY,0.982100,6.268478e-02
128,Heart,LV1636,C2CP_REACTOME_OLFACTORY_SIGNALING_PATHWAY,0.752855,6.697323e-02
129,Heart,LV1616,C2CP_WP_ESTROGEN_RECEPTOR_PATHWAY,0.960560,6.766785e-02
130,Heart,LV1636,C2CP_REACTOME_PROTEIN_LIPOYLATION,0.963968,7.166138e-02
131,Heart,LV119,C2CP_REACTOME_YAP1_AND_WWTR1_TAZ_STIMULATED_GENE_EXPRESSION,0.956162,7.291649e-02
132,Heart,LV686,C2CP_WP_LIPID_METABOLISM_IN_SENESCENT_CELLS,0.948888,7.428539e-02
133,Heart,LV581,C2CP_REACTOME_PI_3K_CASCADE_FGFR4,0.941481,7.680501e-02
134,Heart,LV643,C2CP_WP_FAMILIAL_HYPERLIPIDEMIA_TYPE_1,0.953858,7.958803e-02
135,Heart,LV1636,C2CP_KEGG_OLFACTORY_TRANSDUCTION,0.712628,7.960772e-02
136,Heart,LV686,C2CP_WP_EICOSANOID_SYNTHESIS,0.811975,7.960772e-02
137,Heart,LV482,C2CP_REACTOME_RECEPTOR_TYPE_TYROSINE_PROTEIN_PHOSPHATASES,0.858607,8.283704e-02
138,Heart,LV89,C2CP_REACTOME_MITOCHONDRIAL_MRNA_MODIFICATION,0.940351,8.468086e-02
139,Heart,LV145,C2CP_REACTOME_AMINE_LIGAND_BINDING_RECEPTORS,0.931038,8.635277e-02
140,Heart,LV1576,C2CP_REACTOME_ASPARTATE_AND_ASPARAGINE_METABOLISM,0.922978,9.173429e-02
141,Heart,LV214,C2CP_WP_HEMATOPOIETIC_STEM_CELL_DIFFERENTIATION,0.701026,9.316146e-02
142,Kidney,LV29,C2CP_BIOCARTA_BLYMPHOCYTE_PATHWAY,0.997301,5.495029e-02
143,Kidney,LV1665,C2CP_KEGG_MEDICUS_PATHOGEN_HIV_GP120_TO_CXCR4_GNAQ_PLCB_G_CALCINEURIN,0.889137,6.271650e-02
144,Kidney,LV29,C2CP_REACTOME_GAP_JUNCTION_DEGRADATION,0.927804,8.583096e-02
145,Kidney,LV1665,C2CP_KEGG_MEDICUS_REFERENCE_EGF_EGFR_PLCG_CALCINEURIN_SIGNALING_PATHWAY,0.845203,9.579708e-02
146,Liver,LV1434,C2CP_REACTOME_BASE_EXCISION_REPAIR,0.843248,3.386783e-05
147,Liver,LV441,C2CP_KEGG_ECM_RECEPTOR_INTERACTION,0.719864,2.065730e-02
148,Liver,LV173,C2CP_WP_DOPAMINE_METABOLISM,0.984512,5.318305e-02
149,Liver,LV19,C2CP_KEGG_MEDICUS_VARIANT_MUTATION_CAUSED_ABERRANT_ABETA_TO_TRANSPORT_OF_CALCIUM,0.990792,5.495029e-02
150,Liver,LV173,C2CP_REACTOME_ATF6_ATF6_ALPHA_ACTIVATES_CHAPERONE_GENES,0.957662,5.973986e-02
151,Liver,LV19,C2CP_KEGG_MEDICUS_REFERENCE_INTRINSIC_APOPTOTIC_PATHWAY,0.929198,8.072884e-02
152,Liver,LV297,C2CP_REACTOME_RRNA_PROCESSING_IN_THE_MITOCHONDRION,0.860338,8.125798e-02
153,Liver,LV19,C2CP_REACTOME_P38MAPK_EVENTS,0.927373,8.164208e-02
154,Muscle,LV1300,C2CP_WP_STATIN_INHIBITION_OF_CHOLESTEROL_PRODUCTION,0.935820,1.750729e-02
155,Muscle,LV47,C2CP_REACTOME_FORMATION_OF_THE_NEPHRIC_DUCT,0.979670,2.058945e-02
156,Muscle,LV99,C2CP_WP_GLYCOLYSIS_AND_GLUCONEOGENESIS,0.777899,4.338030e-02
157,Muscle,LV99,C2CP_WP_AEROBIC_GLYCOLYSIS_AUGMENTED,0.987606,5.640270e-02
158,Muscle,LV1227,C2CP_WP_TRANSCRIPTIONAL_CASCADE_REGULATING_ADIPOGENESIS,0.984989,5.741837e-02
159,Muscle,LV94,C2CP_BIOCARTA_TCRA_PATHWAY,0.940778,7.525822e-02
160,Muscle,LV99,C2CP_BIOCARTA_PDZS_PATHWAY,0.839849,9.343105e-02
161,Nerve,LV1215,C2CP_KEGG_ASTHMA,0.985244,7.149207e-03
162,Nerve,LV1215,C2CP_REACTOME_CHEMOKINE_RECEPTORS_BIND_CHEMOKINES,0.843191,7.149207e-03
163,Nerve,LV120,C2CP_WP_IL23_INHIBITORS_IN_INFLAMMATORY_BOWEL_DISEASE,0.994238,5.640270e-02
164,Nerve,LV453,C2CP_REACTOME_PLASMA_LIPOPROTEIN_ASSEMBLY,0.990441,6.151162e-02
165,Nerve,LV453,C2CP_REACTOME_GBP_MEDIATED_HOST_DEFENSE,0.945016,8.731811e-02
166,Ovary,LV1148,C2CP_REACTOME_PRC2_METHYLATES_HISTONES_AND_DNA,0.902929,7.498550e-06
167,Ovary,LV1148,C2CP_REACTOME_REGULATION_OF_ENDOGENOUS_RETROELEMENTS_BY_THE_HUMAN_SILENCING_HUB_HUSH_COMPLEX,0.841785,4.381675e-04
168,Ovary,LV25,C2CP_KEGG_MEDICUS_PATHOGEN_SALMONELLA_SOPE_TO_RAC_SIGNALING_PATHWAY,0.968730,8.271667e-03
169,Ovary,LV786,C2CP_REACTOME_CYTOSOLIC_TRNA_AMINOACYLATION,0.917521,1.996987e-02
170,Ovary,LV786,C2CP_WP_NGLYCAN_BIOSYNTHESIS,0.743694,2.537190e-02
171,Ovary,LV6,C2CP_WP_MIRNA_TARGETS_IN_ECM_AND_MEMBRANE_RECEPTORS,0.839965,3.593903e-02
172,Ovary,LV786,C2CP_WP_PHOTODYNAMIC_THERAPYINDUCED_UNFOLDED_PROTEIN_RESPONSE,0.832668,4.526120e-02
173,Ovary,LV392,C2CP_REACTOME_INTERLEUKIN_2_SIGNALING,0.999347,5.141231e-02
174,Ovary,LV1148,C2CP_REACTOME_RUNX1_REGULATES_GENES_INVOLVED_IN_MEGAKARYOCYTE_DIFFERENTIATION_AND_PLATELET_FUNCTION,0.672023,5.700133e-02
175,Ovary,LV659,C2CP_REACTOME_FREE_FATTY_ACIDS_REGULATE_INSULIN_SECRETION,0.983479,6.100384e-02
176,Ovary,LV402,C2CP_REACTOME_GLYOXYLATE_METABOLISM_AND_GLYCINE_DEGRADATION,0.973050,6.378750e-02
177,Ovary,LV725,C2CP_REACTOME_TRAFFICKING_AND_PROCESSING_OF_ENDOSOMAL_TLR,0.962588,6.697323e-02
178,Ovary,LV786,C2CP_WP_GLYCOSYLATION_AND_RELATED_CONGENITAL_DEFECTS,0.783307,7.672700e-02
179,Ovary,LV25,C2CP_BIOCARTA_AGPCR_PATHWAY,0.947582,7.960772e-02
180,Ovary,LV392,C2CP_KEGG_MEDICUS_REFERENCE_IL2_FAMILY_TO_JAK_STAT_SIGNALING_PATHWAY,0.844418,8.673978e-02
181,Ovary,LV6,C2CP_WP_TGFB_SMAD_SIGNALING,0.913604,9.763373e-02
182,Pancreas,LV412,C2CP_PID_INTEGRIN_CS_PATHWAY,0.959186,3.227810e-03
183,Pancreas,LV309,C2CP_REACTOME_CASPASE_ACTIVATION_VIA_DEATH_RECEPTORS_IN_THE_PRESENCE_OF_LIGAND,0.999057,1.429074e-02
184,Pancreas,LV194,C2CP_KEGG_P53_SIGNALING_PATHWAY,0.717945,2.972456e-02
185,Pancreas,LV309,C2CP_WP_NANOMATERIAL_INDUCED_APOPTOSIS,0.858950,5.118256e-02
186,Pancreas,LV412,C2CP_KEGG_MEDICUS_REFERENCE_ITGA_B_FAK_CDC42_SIGNALING_PATHWAY,0.824944,5.447253e-02
187,Pancreas,LV309,C2CP_REACTOME_REGULATION_BY_C_FLIP,0.999946,5.484971e-02
188,Pancreas,LV898,C2CP_REACTOME_SPHINGOLIPID_CATABOLISM,0.989128,5.523544e-02
189,Pancreas,LV804,C2CP_REACTOME_ENTEROBACTERIAL_FACTORS_ANTAGONIZE_HOST_DEFENSE,0.999946,5.590718e-02
190,Pancreas,LV1189,C2CP_REACTOME_TP53_REGULATES_TRANSCRIPTION_OF_DEATH_RECEPTORS_AND_LIGANDS,0.972506,5.852795e-02
191,Pancreas,LV941,C2CP_WP_ASPIRIN_AND_MIRNAS,0.960292,6.043886e-02
192,Pancreas,LV268,C2CP_WP_INTERFERONMEDIATED_SIGNALING,0.865648,7.289858e-02
193,Pancreas,LV1724,C2CP_KEGG_MEDICUS_REFERENCE_ANTEROGRADE_AXONAL_TRANSPORT,0.804480,8.868812e-02
194,Pancreas,LV194,C2CP_WP_MIRNA_REGULATION_OF_P53_PATHWAY_IN_PROSTATE_CANCER,0.762894,9.781409e-02
195,Prostate,LV1172,C2CP_REACTOME_ELASTIC_FIBRE_FORMATION,0.814207,1.649109e-02
196,Prostate,LV1151,C2CP_KEGG_MEDICUS_VARIANT_MUTATION_CAUSED_ABERRANT_ABETA_TO_MACHR_CA2_APOPTOTIC_PATHWAY,0.893499,6.186924e-02
197,Prostate,LV1172,C2CP_WP_MAJOR_RECEPTORS_TARGETED_BY_EPINEPHRINE_AND_NOREPINEPHRINE,0.977844,6.907387e-02
198,Skin,LV544,C2CP_REACTOME_BINDING_AND_UPTAKE_OF_LIGANDS_BY_SCAVENGER_RECEPTORS,0.776026,1.672075e-03
199,Skin,LV1361,C2CP_KEGG_LINOLEIC_ACID_METABOLISM,0.964886,2.262181e-02
200,Skin,LV664,C2CP_WP_METABOLIC_PATHWAY_OF_LDL_HDL_AND_TG_INCLUDING_DISEASES,0.930852,4.028956e-02
201,Skin,LV135,C2CP_REACTOME_APOPTOTIC_CLEAVAGE_OF_CELL_ADHESION_PROTEINS,0.982877,6.017376e-02
202,Skin,LV138,C2CP_WP_PROSTAGLANDIN_SIGNALING,0.783145,6.271650e-02
203,Skin,LV1361,C2CP_REACTOME_DEVELOPMENTAL_CELL_LINEAGES_OF_THE_INTEGUMENTARY_SYSTEM,0.707323,6.363215e-02
204,Skin,LV138,C2CP_REACTOME_INTERLEUKIN_10_SIGNALING,0.741806,6.592190e-02
205,Skin,LV1402,C2CP_WP_MARKERS_OF_KIDNEY_CELL_LINEAGE,0.721820,7.194291e-02
206,Skin,LV135,C2CP_KEGG_MEDICUS_PATHOGEN_ESCHERICHIA_EAE_TIR_TCCP_TO_ACTIN_SIGNALING_PATHWAY,0.924746,9.483258e-02
207,Small intestine,LV1118,C2CP_WP_HEDGEHOG_SIGNALING_WP4249,0.834746,1.376017e-02
208,Small intestine,LV1118,C2CP_REACTOME_ACTIVATION_OF_SMO,1.000000,1.615600e-02
209,Small intestine,LV1666,C2CP_REACTOME_FRS_MEDIATED_FGFR1_SIGNALING,0.999909,1.742348e-02
210,Small intestine,LV1017,C2CP_KEGG_MEDICUS_ENV_FACTOR_IRON_TO_ANTEROGRADE_AXONAL_TRANSPORT,0.910452,4.992725e-02
211,Small intestine,LV1298,C2CP_KEGG_MEDICUS_REFERENCE_IGF2_IGF1R_PI3K_SIGNALING_PATHWAY,1.000000,5.734513e-02
212,Small intestine,LV1298,C2CP_REACTOME_INTERLEUKIN_6_SIGNALING,1.000000,5.734513e-02
213,Small intestine,LV1666,C2CP_REACTOME_PHOSPHOLIPASE_C_MEDIATED_CASCADE_FGFR2,1.000000,5.756743e-02
214,Small intestine,LV809,C2CP_REACTOME_FGFR1C_LIGAND_BINDING_AND_ACTIVATION,0.954516,7.144923e-02
215,Small intestine,LV809,C2CP_REACTOME_PHOSPHOLIPASE_C_MEDIATED_CASCADE_FGFR2,0.943647,7.827631e-02
216,Stomach,LV612,C2CP_KEGG_MEDICUS_REFERENCE_MICROTUBULE_DEPOLYMERIZATION_AT_THE_MINUS_ENDS,0.994018,2.283026e-02
217,Stomach,LV665,C2CP_REACTOME_GABA_SYNTHESIS_RELEASE_REUPTAKE_AND_DEGRADATION,0.963752,2.948974e-02
218,Stomach,LV665,C2CP_REACTOME_VOLTAGE_GATED_POTASSIUM_CHANNELS,0.938458,4.338030e-02
219,Stomach,LV1258,C2CP_REACTOME_MUSCLE_CONTRACTION,0.637225,5.015040e-02
220,Stomach,LV241,C2CP_WP_GENES_TARGETED_BY_MIRNAS_IN_ADIPOCYTES,0.975828,5.880048e-02
221,Stomach,LV1258,C2CP_REACTOME_ION_HOMEOSTASIS,0.726109,6.656400e-02
222,Stomach,LV12,C2CP_KEGG_MEDICUS_REFERENCE_ARNO_ARF_ACTB_G_SIGNALING_PATHWAY,0.797179,6.907777e-02
223,Testis,LV990,C2CP_REACTOME_FORMATION_OF_THE_URETERIC_BUD,1.000000,1.985729e-02
224,Testis,LV1259,C2CP_BIOCARTA_ATRBRCA_PATHWAY,0.872571,5.031171e-02
225,Thyroid,LV40,C2CP_REACTOME_IMMUNOREGULATORY_INTERACTIONS_BETWEEN_A_LYMPHOID_AND_A_NON_LYMPHOID_CELL,0.820764,2.246799e-08