# GTEx model building with PCA, NFM and ICA

💡 **Environment:** `clamp-analyses`

## Libraries

In [9]:
from pathlib import Path
import numpy as np
import pandas as pd
from pyprojroot.here import here

from sklearn.preprocessing import StandardScaler
from sklearn.decomposition import PCA, NMF, FastICA
import joblib

## Input

In [10]:
gtex_data = pd.read_csv(here("output/gtex/df_gtex_fbm_filt.csv"), index_col=0).astype(np.float32)

In [11]:
K = pd.read_csv(here("output/gtex/CLAMP_K_gtex.csv"))
n_components = int(K['x'].iloc[0])

print(f"Number of components: {n_components}")

Number of components: 412

## Output

In [12]:
out_dir = Path(here("output/gtex"))
out_dir.mkdir(parents=True, exist_ok=True)

# PCA

In [13]:
X = gtex_data.T  # samples x genes

pca = PCA(n_components=n_components, svd_solver="auto", random_state=0)
W = pca.fit_transform(X)   # samples x comps
H = pca.components_               # comps x genes

pc_names = [f"PC{i+1}" for i in range(W.shape[1])]

gtex_pca_scores   = pd.DataFrame(W, index=gtex_data.columns, columns=pc_names)   # samples x comps
gtex_pca_loadings = pd.DataFrame(H, index=pc_names, columns=gtex_data.index)    # comps x genes
gtex_pca_B = gtex_pca_scores.T
gtex_pca_B.index.name = "PC"

gtex_pca_B.to_pickle(out_dir / "gtex_pca_B.pkl")
gtex_pca_scores.to_pickle(out_dir / "gtex_pca_scores.pkl")
gtex_pca_loadings.to_pickle(out_dir / "gtex_pca_loadings.pkl")

In [14]:
gtex_pca_B.head()

,GTEX-1117F-0226-SM-5GZZ7,GTEX-1117F-0426-SM-5EGHI,GTEX-1117F-0526-SM-5EGHJ,GTEX-1117F-0626-SM-5N9CS,GTEX-1117F-0726-SM-5GIEN,GTEX-1117F-1326-SM-5EGHH,GTEX-1117F-2426-SM-5EGGH,GTEX-1117F-2526-SM-5GZY6,GTEX-1117F-2826-SM-5GZXL,GTEX-1117F-2926-SM-5GZYI,...,GTEX-ZZPU-1126-SM-5N9CW,GTEX-ZZPU-1226-SM-5N9CK,GTEX-ZZPU-1326-SM-5GZWS,GTEX-ZZPU-1426-SM-5GZZ6,GTEX-ZZPU-1826-SM-5E43L,GTEX-ZZPU-2126-SM-5EGIU,GTEX-ZZPU-2226-SM-5EGIV,GTEX-ZZPU-2426-SM-5E44I,GTEX-ZZPU-2626-SM-5E45Y,GTEX-ZZPU-2726-SM-5NQ8O
PC,,,,,,,,,,,,,,,,,,,,,
PC1,84.420029,-71.704224,61.518284,93.491318,-70.403069,-10.793814,125.474030,73.683159,39.082577,31.023224,...,-49.669197,20.674231,73.425835,-23.001381,16.341808,89.849915,-15.991726,31.217785,-84.271957,28.372385
PC2,-34.006042,-18.352432,-31.801682,-11.326074,-17.874300,-47.900570,1.370214,-31.237488,-30.852812,-43.721603,...,-6.907743,-5.560464,1.115276,-17.848866,-6.578599,8.008773,-43.369427,-15.860630,-13.707017,-35.314266
PC3,-4.317805,-55.056194,-29.385786,-20.059296,-28.841259,-4.676625,-2.078890,34.484310,-6.360046,12.580085,...,-46.490414,-7.465416,22.277187,-1.794215,-50.160477,-9.280725,24.122108,-61.772095,-71.058632,-31.196869
PC4,10.149643,-31.035181,21.364058,39.329826,19.357561,28.099739,32.057774,-59.406162,9.050770,-47.222794,...,3.812448,-6.047722,11.740240,-10.784277,8.594497,5.633543,-82.292160,21.471983,-40.803791,18.156712
PC5,8.714396,-29.464331,3.403821,9.115057,13.809155,11.056372,15.000657,29.756529,13.495264,36.100899,...,-9.150019,-19.180962,23.801428,14.507213,-11.331697,3.912096,12.602109,-10.915994,-50.053707,-5.756362

# ICA

In [15]:
X = gtex_data.T  # samples x genes

ica = FastICA(n_components=n_components, random_state=0, max_iter=2000)
W = ica.fit_transform(X)  # samples x comps
H = ica.mixing_.T                # comps x genes

ic_names = [f"IC{i+1}" for i in range(W.shape[1])]

gtex_ica_scores   = pd.DataFrame(W, index=gtex_data.columns, columns=ic_names)   # samples x comps
gtex_ica_loadings = pd.DataFrame(H, index=ic_names, columns=gtex_data.index)    # comps x genes
gtex_ica_B = gtex_ica_scores.T
gtex_ica_B.index.name = "IC"

gtex_ica_B.to_pickle(out_dir / "gtex_ica_B.pkl")
gtex_ica_scores.to_pickle(out_dir / "gtex_ica_scores.pkl")
gtex_ica_loadings.to_pickle(out_dir / "gtex_ica_loadings.pkl")

In [16]:
gtex_ica_B.head()

,GTEX-1117F-0226-SM-5GZZ7,GTEX-1117F-0426-SM-5EGHI,GTEX-1117F-0526-SM-5EGHJ,GTEX-1117F-0626-SM-5N9CS,GTEX-1117F-0726-SM-5GIEN,GTEX-1117F-1326-SM-5EGHH,GTEX-1117F-2426-SM-5EGGH,GTEX-1117F-2526-SM-5GZY6,GTEX-1117F-2826-SM-5GZXL,GTEX-1117F-2926-SM-5GZYI,...,GTEX-ZZPU-1126-SM-5N9CW,GTEX-ZZPU-1226-SM-5N9CK,GTEX-ZZPU-1326-SM-5GZWS,GTEX-ZZPU-1426-SM-5GZZ6,GTEX-ZZPU-1826-SM-5E43L,GTEX-ZZPU-2126-SM-5EGIU,GTEX-ZZPU-2226-SM-5EGIV,GTEX-ZZPU-2426-SM-5E44I,GTEX-ZZPU-2626-SM-5E45Y,GTEX-ZZPU-2726-SM-5NQ8O
IC,,,,,,,,,,,,,,,,,,,,,
IC1,1.796228,0.664526,1.421167,1.087034,-0.201645,0.913363,0.361837,0.848674,0.086164,-0.033433,...,1.343985,0.364812,0.973619,0.448605,0.667813,0.443279,0.943064,1.060817,0.078975,0.127862
IC2,-0.062564,0.147491,0.308304,-0.125828,0.549538,-0.076885,-0.754191,0.883902,0.292437,0.158624,...,0.085799,-0.477908,-0.262785,-0.107240,7.032897,0.143213,-0.472363,0.287478,0.295041,-0.092289
IC3,-0.428415,-0.364448,-0.759950,-1.369856,-0.107267,-1.604781,-1.458617,-1.120249,-2.642924,-0.366950,...,-0.009946,-0.575917,-0.270715,-0.149163,-0.262376,-0.447313,-0.648420,0.477851,0.599776,7.284383
IC4,-0.024523,-0.425844,-0.525286,0.117632,0.501587,-0.114861,0.744238,-0.208491,-0.357858,0.213126,...,-0.097798,-0.131751,-0.142668,-0.785224,-0.559524,-0.460373,-0.543441,-0.078709,0.291911,-0.127460
IC5,0.527308,-0.264413,0.135769,0.500031,0.293080,0.481762,-0.339963,0.012383,-0.550853,0.248215,...,0.090614,0.173668,0.075829,0.653688,0.429700,0.414966,0.485763,0.229030,0.221431,-0.227580

# NMF

In [17]:
# non negative input need it
gene_min = gtex_data.min(axis=1)                 
gtex_data_nmf = gtex_data.sub(gene_min, axis=0)

In [ ]:
X = gtex_data_nmf.T  # samples x genes (non-negative)

nmf = NMF(n_components=n_components, init="nndsvd", random_state=0, max_iter=1000)
W = nmf.fit_transform(X)  # samples x comps
H = nmf.components_       # comps x genes

lv_names = [f"LV{i+1}" for i in range(W.shape[1])]

gtex_nmf_scores   = pd.DataFrame(W, index=gtex_data.columns, columns=lv_names)  # samples x comps
gtex_nmf_loadings = pd.DataFrame(H, index=lv_names, columns=gtex_data.index)   # comps x genes
gtex_nmf_B = gtex_nmf_scores.T
gtex_nmf_B.index.name = "LV"

gtex_nmf_B.to_pickle(out_dir / "gtex_nmf_B.pkl")
gtex_nmf_scores.to_pickle(out_dir / "gtex_nmf_scores.pkl")
gtex_nmf_loadings.to_pickle(out_dir / "gtex_nmf_loadings.pkl")

In [ ]:
gtex_nmf_B.head()

,GTEX-1117F-0226-SM-5GZZ7,GTEX-1117F-0426-SM-5EGHI,GTEX-1117F-0526-SM-5EGHJ,GTEX-1117F-0626-SM-5N9CS,GTEX-1117F-0726-SM-5GIEN,GTEX-1117F-1326-SM-5EGHH,GTEX-1117F-2426-SM-5EGGH,GTEX-1117F-2526-SM-5GZY6,GTEX-1117F-2826-SM-5GZXL,GTEX-1117F-2926-SM-5GZYI,...,GTEX-ZZPU-1126-SM-5N9CW,GTEX-ZZPU-1226-SM-5N9CK,GTEX-ZZPU-1326-SM-5GZWS,GTEX-ZZPU-1426-SM-5GZZ6,GTEX-ZZPU-1826-SM-5E43L,GTEX-ZZPU-2126-SM-5EGIU,GTEX-ZZPU-2226-SM-5EGIV,GTEX-ZZPU-2426-SM-5E44I,GTEX-ZZPU-2626-SM-5E45Y,GTEX-ZZPU-2726-SM-5NQ8O
LV,,,,,,,,,,,,,,,,,,,,,
LV1,0.705968,0.000000,0.629308,0.770160,0.370649,0.493055,0.808041,0.623231,0.681236,0.621713,...,0.470611,0.713613,0.715113,0.602532,0.868140,0.680908,0.594427,0.784961,0.117370,0.722300
LV2,0.000000,0.000000,0.000000,0.010266,0.010871,0.009960,0.000000,0.000000,0.000000,0.002410,...,0.002873,0.001588,0.003282,0.004192,0.006558,0.000221,0.000000,0.001387,0.011055,0.000000
LV3,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.003877,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
LV4,0.057670,0.000000,0.028650,0.000000,0.000000,0.000000,0.000000,0.011973,0.039785,0.000000,...,0.023976,0.002056,0.007304,0.001145,0.000209,0.000000,0.031932,0.021048,0.008610,0.022829
LV5,0.000000,0.004336,0.000000,0.000000,0.001137,0.003251,0.000000,0.185885,0.000000,0.504287,...,0.000000,0.005109,0.004484,0.009668,0.000111,0.000102,0.348907,0.000000,0.008623,0.000000